/* ============================================================
   LEONIDAKIT — armes : source de vérité
   Chaque arme porte son niveau de certitude :
     st: 'officiel'  nom publié par Rockstar dans un support officiel
     st: 'vu'        visible dans un média officiel, nom non communiqué
   Aucune donnée issue de fuites.
   Images : visuels officiels Rockstar listés dans outils/armes-medias.json (registre outils/medias-officiels.json).
   Fiches et hub régénérés par node outils/gen-armes.cjs ; les textes sont écrits ici, pas dans les fiches.
   ============================================================ */
window.LK_ARMES = [
{"id":"girardi-es9","nom":"Girardi ES9","fr":"Jason’s pistol","cat":"pistolet","slot":"poing","st":"officiel","src":"Ultimate Edition pre-order material","insp":"Beretta 92FS","mun":"Pistol ammo","portee":"Short to medium","ctx":"Jason’s personal pistol, named by Rockstar in the Ultimate Edition reveal, which includes an engraved version of it. It’s the most visible handgun in the official media.","perso":"jason","ue":true},
{"id":"klose-k17","nom":"Klose K17","fr":"Lucia’s pistol","cat":"pistolet","slot":"poing","st":"officiel","src":"Ultimate Edition pre-order material","insp":"Glock 17 / SIG P320","mun":"Pistol ammo","portee":"Short to medium","ctx":"Lucia’s personal pistol, named by Rockstar, with a rose-engraved version in the Ultimate Edition. A modern pistol with a polymer frame and an accessory rail.","perso":"lucia","ue":true},
{"id":"nipper-38","nom":"Nipper .38","fr":"Compact pistol","cat":"pistolet","slot":"poing","st":"officiel","src":"Name engraved on the weapon, official cover art","insp":"Bersa Thunder 380","mun":"Pistol ammo","portee":"Short","ctx":"The small pistol Lucia holds on the official cover art. Its name is readable on the slide: it’s one of the few weapons whose name comes straight from a Rockstar image.","perso":"lucia"},
{"id":"hawk-little-morgan","nom":"Hawk & Little Morgan","fr":"Engraved revolvers","cat":"pistolet","slot":"poing","st":"officiel","src":"Ultimate Edition pre-order material","insp":"Smith & Wesson 629","mun":"Pistol ammo","portee":"Medium","ctx":"A pair of engraved revolvers, one for Jason, the other for Lucia, described by Rockstar as inspired by the Vercetti Estate in Vice City. Palm-tree grips, name engravings and a high-performance scope.","ue":true},
{"id":"pistolet-custom","nom":"Custom pistol","fr":null,"cat":"pistolet","slot":"poing","st":"vu","src":"Trailer 2","insp":"Colt 1911","mun":"Pistol ammo","portee":"Short to medium","ctx":"A pistol with a custom finish, seen in an indoor scene. The visible finishes suggest that weapon customization is back."},
{"id":"pistolet-auto","nom":"Select-fire pistol","fr":null,"cat":"pistolet","slot":"poing","st":"vu","src":"August 27, 2026 Extended Look","insp":"Glock with a switch","mun":"Pistol ammo","portee":"Short","ctx":"A pistol fitted with a fire selector at the back of the slide, a detail visible in the gameplay footage. It would turn a semi-automatic pistol into a burst-fire weapon."},
{"id":"mustang-357","nom":"Mustang .357","fr":"Bikers’ revolver","cat":"pistolet","slot":"poing","st":"officiel","src":"Name engraved on the weapon, official Ambrosia screenshot","insp":"Colt Python","mun":"Pistol ammo","portee":"Medium","ctx":"The big revolver a female biker waves in the third Ambrosia screenshot, as she hangs on the neck of a gang member wearing the Enforcer patch. The name Mustang .357 is engraved on the weapon: it’s the fifth weapon whose name comes straight from a Rockstar image. Vented barrel and big Colt Python cylinder, the classic movie magnum, here in the hands of the backcountry bikers."},
{"id":"fusil-double","nom":"Double-barrel shotgun","fr":null,"cat":"pompe","slot":"longue","st":"vu","src":"Trailer 2","insp":"Side-by-side hunting shotgun","mun":"Shotgun shells","portee":"Very short","ctx":"A side-by-side double-barrel shotgun, tied to rural areas and swamps in the official media. The bearded man in the foreground of the sixth Grassrivers screenshot carries one on his shoulder, with engraved fittings and a wooden stock, in front of the alligator hanging in his workshop."},
{"id":"fusil-pompe","nom":"Pump shotgun","fr":null,"cat":"pompe","slot":"longue","st":"vu","src":"Trailer 1","insp":"Mossberg 590","mun":"Shotgun shells","portee":"Very short","ctx":"A classic pump shotgun, sighted during shootout scenes. A short-range weapon typical of the series."},
{"id":"micro-smg","nom":"Tropical-pattern SMG","fr":null,"cat":"pm","slot":"poing","st":"vu","src":"Ultimate Edition artwork","insp":"Mini Uzi","mun":"Pistol ammo","portee":"Short","ctx":"A compact submachine gun with a tropical pattern, shown in the Ultimate Edition artwork without Rockstar publishing its name. Usable one-handed, in the tradition of drive-by weapons.","ue":true},
{"id":"smg-compact","nom":"Compact SMG","fr":null,"cat":"pm","slot":"poing","st":"vu","src":"August 27, 2026 Extended Look","insp":"Škorpion","mun":"Pistol ammo","portee":"Short","ctx":"A very short automatic weapon, sighted in a close-quarters action scene."},
{"id":"smg","nom":"Submachine gun","fr":null,"cat":"pm","slot":"longue","st":"vu","src":"Trailer 2","insp":"H&K MP5","mun":"Pistol ammo","portee":"Short to medium","ctx":"A submachine gun held two-handed by Jason and Lucia during the Trailer 2 heist. Jason’s version has a red dot sight."},
{"id":"pm-tactique","nom":"Folding-stock SMG","fr":null,"cat":"pm","slot":"longue","st":"vu","src":"Ultimate Edition artwork","insp":null,"mun":"Pistol ammo","portee":"Short to medium","ctx":"Lying on a car’s bench seat between stacks of cash, with a matching pistol, in the Weapon Pattern artwork of the Vintage Vice City Pack. Folded stock, straight magazine in front of the grip, turquoise palm-tree finish: a modern, compact submachine gun, not the same as the small tropical-pattern SMG Jason holds in the outfit artwork. Its name hasn’t been announced.","ue":true,"fam":"Modern SMG with a folding stock"},
{"id":"carabine","nom":"Carbine","fr":null,"cat":"assaut","slot":"longue","st":"vu","src":"Trailer 2","insp":"AR-15 / M4","mun":"Rifle ammo","portee":"Medium to long","ctx":"A modern carbine with a telescoping stock, visible in several action sequences."},
{"id":"fusil-assaut","nom":"Assault rifle","fr":null,"cat":"assaut","slot":"longue","st":"vu","src":"Trailer 1","insp":"AK","mun":"Rifle ammo","portee":"Medium to long","ctx":"An assault rifle with a distinctive curved magazine, sighted in the hands of antagonists."},
{"id":"fusil-precision","nom":"Bolt-action rifle","fr":null,"cat":"precision","slot":"longue","st":"vu","src":"August 27, 2026 Extended Look","insp":"Remington 700","mun":"Rifle ammo","portee":"Long gun","ctx":"A scoped bolt-action rifle, sighted in a long-range shooting situation."},
{"id":"fusil-semi-auto","nom":"Semi-automatic rifle","fr":null,"cat":"precision","slot":"longue","st":"vu","src":"Official screenshots","insp":"Springfield M1A","mun":"Rifle ammo","portee":"Long gun","ctx":"The long scoped rifle with a wooden stock held by one of the three men posing in front of their airboat, in the first Grassrivers screenshot. The long receiver and traditional stock recall the M1A, the civilian version of the M14: a hunting and long-range shooting weapon, more rugged than the bolt-action rifle, and right at home in the swamps."},
{"id":"mitrailleuse","nom":"Combat machine gun","fr":null,"cat":"mitrailleuse","slot":"longue","st":"vu","src":"August 27, 2026 Extended Look","insp":"M249 SAW","mun":"Heavy ammo","portee":"Medium","ctx":"A belt-fed support weapon, the heaviest one sighted so far."},
{"id":"batte","nom":"Baseball bat","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Trailer 1","insp":null,"mun":null,"portee":"Melee","ctx":"Baseball bat, a recurring melee weapon in the series. The melee animations were redone with motion capture.","fam":"Aluminum baseball bat"},
{"id":"couteau-cran","nom":"Switchblade","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Ultimate Edition artwork","insp":null,"mun":null,"portee":"Melee","ctx":"A knife with a retractable blade, visible in the Ultimate Edition artwork next to the engraved revolvers.","ue":true,"fam":"Folding switchblade"},
{"id":"club-golf","nom":"Golf club","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Trailer 2","insp":null,"mun":null,"portee":"Melee","ctx":"A golf club you can use as a melee weapon, in the tradition of everyday objects turned into weapons.","fam":"Golf iron"},
{"id":"marteau","nom":"Hammer","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"August 27, 2026 Extended Look","insp":null,"mun":null,"portee":"Melee","ctx":"A construction hammer, sighted as an improvised weapon.","fam":"Carpenter’s hammer"},
{"id":"queue-billard","nom":"Pool cue","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"August 27, 2026 Extended Look","insp":null,"mun":null,"portee":"Melee","ctx":"A pool cue, a melee weapon tied to Leonida’s leisure spots.","fam":"American pool cue"},
{"id":"molotov","nom":"Molotov cocktail","fr":null,"cat":"projectile","slot":"poing","st":"vu","src":"Trailer 2","insp":null,"mun":null,"portee":"Jet","ctx":"Molotov cocktail, the series’ classic incendiary throwable.","fam":"Improvised incendiary bottle"},
{"id":"fumigene","nom":"Smoke grenade","fr":null,"cat":"projectile","slot":"poing","st":"vu","src":"August 27, 2026 Extended Look","insp":null,"mun":null,"portee":"Jet","ctx":"Smoke grenade, a non-lethal throwable used to hide your movement.","fam":"Hand-thrown smoke grenade"},
{"id":"harpon","nom":"Speargun","fr":null,"cat":"speciale","slot":"longue","st":"vu","src":"August 27, 2026 Extended Look","insp":null,"mun":"Harpoons","portee":"Short, underwater","ctx":"Speargun, an underwater weapon. It’s new to the series: it comes with the underwater areas you can explore.","fam":"Band-powered underwater speargun"},
{"id":"lance-grenades","nom":"Grenade launcher","fr":null,"cat":"speciale","slot":"longue","st":"vu","src":"Trailer 2","insp":"Milkor MGL","mun":"Grenades","portee":"Medium","ctx":"Lucia holds it during the police chase in Trailer 2, just as a vehicle explodes behind her. The big cylinder sticking out under the barrel leaves no doubt: a Milkor MGL-style revolver grenade launcher, the return of the series’ most spectacular heavy weapon."}
];
window.LK_ARMES_CATS = {
  pistolet:'Pistols', pompe:'Shotguns', pm:'Submachine guns', assaut:"Assault rifles",
  precision:'Precision rifles', mitrailleuse:'Machine guns', melee:'Melee', projectile:'Throwables', speciale:'Special'
};
