/* ============================================================
   LEONIDAKIT — armes : source de vérité
   Chaque arme porte son niveau de certitude :
     st: 'officiel'  nom publié par Rockstar dans un support officiel
     st: 'vu'        visible dans un média officiel, nom non communiqué
   Aucune donnée issue de fuites.
   Images : visuels officiels Rockstar listés dans outils/armes-medias.json (registre outils/medias-officiels.json).
   Fiches et hub régénérés par node outils/gen-armes.cjs ; les textes sont écrits ici, pas dans les fiches.
   ============================================================ */
window.LK_ARMES = [
{"id":"girardi-es9","nom":"Girardi ES9","fr":"Jason’s pistol","cat":"pistolet","slot":"poing","st":"officiel","src":"Ultimate Edition pre-order material","insp":"Beretta 92FS","mun":"Pistol ammo","portee":"Short to medium","ctx":"Jason’s personal pistol, named by Rockstar in the Ultimate Edition presentation, which includes an engraved version of it. It’s the most visible sidearm in the official material.","perso":"jason","ue":true},
{"id":"klose-k17","nom":"Klose K17","fr":"Lucia’s pistol","cat":"pistolet","slot":"poing","st":"officiel","src":"Ultimate Edition pre-order material","insp":"Glock 17 / SIG P320","mun":"Pistol ammo","portee":"Short to medium","ctx":"Lucia’s personal pistol, named by Rockstar, with a rose-engraved version in the Ultimate Edition. Modern pistol with a polymer frame and an accessory rail.","perso":"lucia","ue":true},
{"id":"nipper-38","nom":"Nipper .38","fr":"Compact pistol","cat":"pistolet","slot":"poing","st":"officiel","src":"Name engraved on the weapon, official cover art","insp":"Bersa Thunder 380","mun":"Pistol ammo","portee":"Short","ctx":"The small pistol Lucia holds on the official cover art. Its name is readable on the slide: it’s one of the few weapons whose name comes straight from a Rockstar image.","perso":"lucia"},
{"id":"hawk-little-morgan","nom":"Hawk & Little Morgan","fr":"Engraved revolvers","cat":"pistolet","slot":"poing","st":"officiel","src":"Ultimate Edition pre-order material","insp":"Smith & Wesson 629","mun":"Pistol ammo","portee":"Medium","ctx":"A pair of engraved revolvers, one for Jason, the other for Lucia, described by Rockstar as inspired by the Vercetti estate in Vice City. Palm-tree grips, name engravings and a high-performance scope.","ue":true},
{"id":"pistolet-custom","nom":"Custom pistol","fr":null,"cat":"pistolet","slot":"poing","st":"vu","src":"Second trailer","insp":"Colt 1911","mun":"Pistol ammo","portee":"Short to medium","ctx":"Pistol with a custom finish, seen during an indoor scene. The visible finishes suggest weapon customization is back."},
{"id":"pistolet-auto","nom":"Select-fire pistol","fr":null,"cat":"pistolet","slot":"poing","st":"vu","src":"Extended Look from August 27, 2026","insp":"Glock with a switch","mun":"Pistol ammo","portee":"Short","ctx":"Pistol fitted with a fire selector at the back of the slide, a detail visible in the gameplay footage. It would turn a semi-automatic pistol into a burst-fire weapon."},
{"id":"mustang-357","nom":"Mustang .357","fr":"Bikers’ revolver","cat":"pistolet","slot":"poing","st":"officiel","src":"Name engraved on the weapon, official Ambrosia screenshot","insp":"Colt Python","mun":"Pistol ammo","portee":"Medium","ctx":"The big revolver a female biker waves around on the third Ambrosia screenshot, hanging on the neck of a gang member with the Enforcer patch. The name Mustang .357 is engraved on the weapon: it’s the fifth weapon whose name comes straight from a Rockstar image. Vented barrel and big cylinder of the Colt Python, the movie magnum, here in the hands of backcountry bikers."},
{"id":"fusil-double","nom":"Double-barrel shotgun","fr":null,"cat":"pompe","slot":"longue","st":"vu","src":"Second trailer","insp":"Side-by-side hunting shotgun","mun":"Shells","portee":"Very short","ctx":"Side-by-side double-barreled shotgun, tied to rural areas and swamps in the official material. The bearded man in the foreground of the sixth Grassrivers screenshot carries one on his shoulder, with engraved fittings and a wooden stock, in front of the alligator hanging in his workshop."},
{"id":"fusil-pompe","nom":"Pump shotgun","fr":null,"cat":"pompe","slot":"longue","st":"vu","src":"First trailer","insp":"Mossberg 590","mun":"Shells","portee":"Very short","ctx":"Classic pump-action shotgun, seen during shootout scenes. A short-range weapon typical of the series."},
{"id":"micro-smg","nom":"Tropical-pattern SMG","fr":null,"cat":"pm","slot":"poing","st":"vu","src":"Ultimate Edition image","insp":"Mini Uzi","mun":"Pistol ammo","portee":"Short","ctx":"Compact submachine gun with a tropical pattern, shown in the Ultimate Edition image without Rockstar releasing its name. Usable with one hand, in the tradition of drive-by weapons.","ue":true},
{"id":"smg-compact","nom":"Compact SMG","fr":null,"cat":"pm","slot":"poing","st":"vu","src":"Extended Look from August 27, 2026","insp":"Škorpion","mun":"Pistol ammo","portee":"Short","ctx":"Very short automatic weapon, seen in a close-quarters action scene."},
{"id":"smg","nom":"Submachine gun","fr":null,"cat":"pm","slot":"longue","st":"vu","src":"Second trailer","insp":"H&K MP5","mun":"Pistol ammo","portee":"Short to medium","ctx":"Submachine gun held two-handed by Jason and Lucia during the heist in the second trailer. Jason’s version has a red dot sight."},
{"id":"pm-tactique","nom":"Folding-stock SMG","fr":null,"cat":"pm","slot":"longue","st":"vu","src":"Ultimate Edition image","insp":null,"mun":"Pistol ammo","portee":"Short to medium","ctx":"Lying on a car seat between bundles of cash, with a matching pistol, in the Weapon Pattern image of the Vintage Vice City Pack. Folded stock, straight magazine in front of the grip, turquoise palm-tree finish: a modern, compact submachine gun, different from the small tropical-pattern SMG Jason holds in the outfit images. Its name hasn’t been released.","ue":true,"fam":"Modern submachine gun with a folding stock"},
{"id":"carabine","nom":"Carbine","fr":null,"cat":"assaut","slot":"longue","st":"vu","src":"Second trailer","insp":"AR-15 / M4","mun":"Rifle ammo","portee":"Medium to long","ctx":"Modern carbine with a telescoping stock, visible in several action sequences."},
{"id":"fusil-assaut","nom":"Assault rifle","fr":null,"cat":"assaut","slot":"longue","st":"vu","src":"First trailer","insp":"AK","mun":"Rifle ammo","portee":"Medium to long","ctx":"Assault rifle with a distinctive curved magazine, seen in the hands of antagonists."},
{"id":"fusil-precision","nom":"Bolt-action rifle","fr":null,"cat":"precision","slot":"longue","st":"vu","src":"Extended Look from August 27, 2026","insp":"Remington 700","mun":"Rifle ammo","portee":"Long","ctx":"Bolt-action rifle fitted with a scope, seen in a long-range shooting context."},
{"id":"fusil-semi-auto","nom":"Semi-automatic rifle","fr":null,"cat":"precision","slot":"longue","st":"vu","src":"Official screenshots","insp":"Springfield M1A","mun":"Rifle ammo","portee":"Long","ctx":"The long rifle with a wooden stock and scope held by one of the three men posing in front of their airboat, on the first Grassrivers screenshot. The long receiver and traditional stock recall the M1A, the civilian version of the M14: a hunting and long-range shooting weapon, more rugged than the bolt-action rifle, and right at home in the swamps."},
{"id":"mitrailleuse","nom":"Combat machine gun","fr":null,"cat":"mitrailleuse","slot":"longue","st":"vu","src":"Extended Look from August 27, 2026","insp":"M249 SAW","mun":"Heavy ammo","portee":"Medium","ctx":"Belt-fed support weapon, the heaviest seen so far."},
{"id":"batte","nom":"Baseball bat","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"First trailer","insp":null,"mun":null,"portee":"Close quarters","ctx":"Baseball bat, a recurring melee weapon in the series. Melee animations were redone with motion capture.","fam":"Aluminum baseball bat"},
{"id":"couteau-cran","nom":"Switchblade","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Ultimate Edition image","insp":null,"mun":null,"portee":"Close quarters","ctx":"Knife with a retractable blade, visible in the Ultimate Edition image next to the engraved revolvers.","ue":true,"fam":"Folding switchblade knife"},
{"id":"club-golf","nom":"Golf club","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Second trailer","insp":null,"mun":null,"portee":"Close quarters","ctx":"Golf club usable as a melee weapon, in the line of everyday objects turned into weapons.","fam":"Golf iron"},
{"id":"marteau","nom":"Hammer","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Extended Look from August 27, 2026","insp":null,"mun":null,"portee":"Close quarters","ctx":"Construction hammer, seen as an improvised weapon.","fam":"Claw hammer"},
{"id":"queue-billard","nom":"Pool cue","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Extended Look from August 27, 2026","insp":null,"mun":null,"portee":"Close quarters","ctx":"Pool cue, a melee weapon tied to Leonida’s leisure spots.","fam":"Pool cue"},
{"id":"molotov","nom":"Molotov cocktail","fr":null,"cat":"projectile","slot":"poing","st":"vu","src":"Second trailer","insp":null,"mun":null,"portee":"Jet","ctx":"Molotov cocktail, a classic incendiary throwable in the series.","fam":"Improvised incendiary bottle"},
{"id":"fumigene","nom":"Smoke grenade","fr":null,"cat":"projectile","slot":"poing","st":"vu","src":"Extended Look from August 27, 2026","insp":null,"mun":null,"portee":"Jet","ctx":"Smoke grenade, a non-lethal throwable used to cover a move.","fam":"Hand-thrown smoke grenade"},
{"id":"harpon","nom":"Speargun","fr":null,"cat":"speciale","slot":"longue","st":"vu","src":"Extended Look from August 27, 2026","insp":null,"mun":"Spears","portee":"Short, underwater","ctx":"Speargun, an underwater weapon. It’s new to the series: it goes with the explorable underwater areas.","fam":"Band-powered underwater speargun"},
{"id":"lance-grenades","nom":"Grenade launcher","fr":null,"cat":"speciale","slot":"longue","st":"vu","src":"Second trailer","insp":"Milkor MGL","mun":"Grenades","portee":"Medium","ctx":"Lucia holds it during the police chase in the second trailer, just as a vehicle explodes behind her. The big cylinder sticking out under the barrel leaves no doubt: a Milkor MGL-style revolver grenade launcher, the return of the series’ most spectacular heavy weapon."}
];
window.LK_ARMES_CATS = {
  pistolet:'Pistols', pompe:'Shotguns', pm:'Submachine guns', assaut:"Assault rifles",
  precision:'Precision rifles', mitrailleuse:'Machine guns', melee:'Melee', projectile:'Throwables', speciale:'Special'
};
