/* Mon business plan (v7.34) : un programme mission par mission, avec ses propres réponses.
   Le plan ne prend rien en silence dans les huit calculs : il pose ses questions (but, situation, missions, achats d'avant).
   Tout chiffre vient du moteur (LKCalcEngine.missionPlan) via le scénario partagé (LKCalcScenario) ; ce fichier ne fait
   que présenter : réponse, prochaine partie, programme dans l'ordre, plans de secours, suivi du réel avec recalcul complet,
   point de départ, stratégie, échéance, détails (partie par partie, et si, courbe, calendrier, formule), fiche enregistrée. */
(function(global){'use strict';
const B=global.LKCalcScenario;
function create(env){
 const {esc,money,hours,field,stats,warning,btn,select,table,state,sourceActivities,visual,api,problem,itemFor,selectedCard,combobox,step,refresh,fold,explainBlock,analysisOf}=env;
 const E=global.LKCalcEngine,nf=new Intl.NumberFormat('en-US',{maximumFractionDigits:2}),$=id=>document.getElementById(id);
 const STRATEGY_LABEL=B.STRATEGY_LABEL;
 const ORDINALS=['First','Second','Third','Fourth','Fifth','Sixth','Seventh','Eighth','Ninth','Tenth'];
 const KIND_LABEL={purchase:'Buy something',amount:'Have a sum of money',unlock:'Unlock something with experience (rank, XP, reputation…)'};
 function planDate(days,base){const d=base?new Date(base):new Date();if(!Number.isFinite(d.getTime()))return '—';d.setDate(d.getDate()+days);return d.toLocaleDateString('en-US',{day:'numeric',month:'long'});}
 const dayOf=(n,dpw)=>n<=0?0:Math.floor((n-1)/dpw)*7+((n-1)%dpw)+1;
 const pct=v=>v===null||!Number.isFinite(v)?'—':nf.format(Math.round(v*10)/10)+'%';
 const plural=(n,w,ws)=>n+' '+(E.plural(n)?(ws||w+'s'):w);
 const units=(s,n)=>(Number.isFinite(n)?nf.format(Math.round(n*100)/100):'—')+' '+esc(s.plan.goal.unitLabel||'points');
 const sessionLabel=s=>s.plan.situation.dailyMinutes?hours(s.plan.situation.dailyMinutes/60):'no set duration';
 function goalName(s){const g=s.plan.goal;return g.kind==='amount'?'a goal of '+money(g.target):g.kind==='unlock'?'unlocking '+(g.name||'my goal'):(g.name||'my purchase');}
 function goalShort(s){const g=s.plan.goal;return g.kind==='amount'?money(g.target):(g.name||(g.kind==='unlock'?'my goal':'my purchase'));}
 function parse(v){const P=E.parseLocalizedNumber;if(v===undefined||v===null)return null;if(String(v).trim()==='')return null;const r=P(String(v));return r.valid?r.value:null;}
 /* ---------- Formulaire : cinq questions, toutes propres au plan ---------- */
 function markup(){const s=state(),p=s.plan,g=p.goal,si=p.situation;
  const goalBlock=g.kind==='purchase'
   ?combobox('plan-search','I want to buy (search the site)','plan')+btn('Enter a custom purchase','data-b-plan-free="1"')+'<div id="plan-selection">'+(g.itemId?selectedCard({itemId:g.itemId,name:g.name}):'')+'<div class="calc-fields">'+field('plan.goal.name','Name of my purchase',g.name,{type:'text',id:'plan-name'})+field('plan.goal.price',g.referencePrice!==null?'It costs ($)':'The price I imagine ($)',g.price,{id:'plan-price',hint:g.referencePrice!==null?'Site price: '+money(g.referencePrice)+'. You can enter another price.':'The in-game price isn’t known yet: enter the one you imagine.'})+field('plan.goal.boostHourly','Once bought, it will earn me extra ($ per hour)',g.boostHourly,{id:'plan-boost',hint:'0 if it’s a just-for-fun purchase. Only count the extra it earns you.'})+'</div>'+(g.referencePrice!==null?btn('Restore the site price','data-b-plan-price-reset="1"'):'')+'</div>'
   :g.kind==='amount'
   ?'<div class="calc-fields">'+field('plan.goal.target','I want to have ($)',g.target,{id:'plan-target',hint:'Just below, choose what “have” means to you.'})+select('plan.goal.meaning','To me, “have” means',[['available','Money available, on top of what I set aside'],['held','Money in total, including the money set aside'],['cumulative','Money earned from now on, not counting what I already have']],g.meaning||'available')+'</div>'
   :'<div class="calc-fields">'+field('plan.goal.name','What I want to unlock',g.name,{type:'text',id:'plan-name',hint:'A car, a weapon, a place… anything you earn with experience.'})+field('plan.goal.unitLabel','It’s earned in',g.unitLabel,{type:'text',id:'plan-units-label',hint:'XP points, levels, reputation… whatever word you want.'})+field('plan.goal.targetUnits','You need to reach ('+esc(g.unitLabel||'points')+')',g.targetUnits,{id:'plan-units-target'})+field('plan.goal.currentUnits','I already have ('+esc(g.unitLabel||'points')+')',g.currentUnits,{id:'plan-units-current'})+field('plan.goal.alsoPrice','And it also costs, once unlocked ($)',g.alsoPrice,{id:'plan-also-price',hint:'Leave 0 if it’s free once unlocked.'})+'</div><p class="calc-note">The game hasn’t said yet how experience is earned. Enter what you know, or what you imagine: the plan works with your numbers.</p>';
  const missionSources=[...s.activities.map(a=>['mine:'+a.id,a.name+' · My activities']),...sourceActivities.map(a=>['site:'+a.id,a.name+' · from the site'])];
  const missionsBlock=p.source==='missions'
   ?'<div id="plan-missions">'+(p.missions.length?p.missions.map((m,i)=>missionCard(s,m,i)).join(''):'<p class="calc-empty">No missions yet. Add the ones you can do: the plan will tell you which ones to chain and in what order.</p>')+'</div><div class="b-plan-add">'+btn('Add a mission','data-b-plan-m-add="1"',true)+(missionSources.length?'<label class="calc-label" for="plan-m-source">Or reuse a mission you already entered</label><div class="b-plan-add-row"><select id="plan-m-source">'+missionSources.map(([k,l])=>'<option value="'+esc(k)+'">'+esc(l)+'</option>').join('')+'</select>'+btn('Add this mission','data-b-plan-m-import="1"')+'</div>':'')+'</div><p class="calc-note">These are copies: changing a mission here changes nothing in My activities, and vice versa.</p>'
   :'<div class="calc-fields">'+field('plan.situation.hourly','I earn about ($ per hour of play)',si.hourly,{id:'plan-hourly',hint:'What you keep once your fees are paid. Your own number.'})+(g.kind==='unlock'?field('plan.situation.unitsHourly','I earn about ('+esc(g.unitLabel||'points')+' per hour)',si.unitsHourly,{id:'plan-units-hourly'}):'')+'</div>';
  const prereqBlock='<div id="plan-prereqs">'+(p.prerequisites.length?p.prerequisites.map((a,i)=>prereqCard(s,a,i)).join(''):'<p class="calc-empty">No purchases before your goal. Add what you need to buy first (gear, vehicle, property…), if anything.</p>')+'</div>'+combobox('plan-prereq-search','Add a purchase before the goal (search the site)','plan-prereq')+btn('Add a custom purchase','data-b-plan-p-add="1"')+'<div class="calc-fields">'+select('plan.strategy','In what order should I buy them?',Object.entries(STRATEGY_LABEL),p.strategy)+field('plan.situation.upkeepPerSession','I spend per session ($): consumables, ammo…',si.upkeepPerSession,{id:'plan-upkeep',hint:'Taken out of what you earn. Put 0 if you don’t know.'})+'</div>';
  const form='<div class="b-plan-import"><p class="calc-note">The business plan has its own boxes: nothing is pulled automatically from the eight calculations. If you want to start from your numbers in My calculations, click here, then change whatever you like.</p>'+btn('Reuse my numbers from My calculations','data-b-plan-import-calcs="1"')+'</div><div class="calc-fields calc-steps">'
   +step(1,'What’s your goal?',select('plan.goal.kind','My goal',Object.entries(KIND_LABEL),g.kind)+goalBlock,'The goal decides everything else: a purchase has a price, a sum is earned little by little, an unlock is earned with points.')
   +step(2,'Where do you stand?','<div class="calc-fields">'+field('plan.situation.capital','I already have ($)',si.capital,{id:'plan-capital'})+field('plan.situation.reserve','Money I set aside ($)',si.reserve,{id:'plan-reserve'})+field('plan.situation.dailyMinutes','A session lasts (minutes)',si.dailyMinutes,{id:'plan-daily',min:1,max:1440,hint:'The schedule is built session by session. Leave empty if you don’t count in sessions: you’ll get a path in play time, with no calendar.'})+field('plan.situation.daysPerWeek','How many days per week do I play?',si.daysPerWeek,{id:'plan-days',min:1,max:7,integer:true})+field('plan.situation.players','How many of us play (players)',si.players??1,{id:'plan-players',min:1,max:100,integer:true,hint:'A mission that needs more players than your group is left out of the plan, and the plan says so.'})+'</div>','With what you have and your session duration, the plan counts in sessions, then in days.')
   +step(3,'How do you earn your money?',select('plan.source','I earn my money',[['missions','With my missions: the plan tells me which ones to do and in what order'],['hourly','Little by little: I earn roughly a set amount per hour']],p.source)+missionsBlock,'With your missions, the plan picks, in each session, the ones that earn the most in the time you have. It’s the fastest path it can find.')
   +step(4,'Before your goal',prereqBlock,'A purchase that unlocks a mission or earns money speeds up what comes next; the plan places it at the right moment, as soon as you can pay for it.')
   +step(5,'What matters to you','<div class="calc-fields">'+select('plan.priority','I prefer',[['balanced','A good balance: I keep my money set aside'],['fast','As fast as possible: I can use my money set aside'],['safe','Safety first: I never touch my money set aside'],['cheap','The cheapest over the whole path: I keep my money set aside']],p.priority)+field('plan.deadlineDays','I want to get there in (days, if you like)',p.deadlineDays,{id:'plan-deadline',min:1,max:36500,integer:true,hint:'Leave empty if you have no date. We’ll tell you if it’s doable at your pace.'})+'<div class="b-expert">'+field('plan.maxRepeat','Same mission in a row, at most',p.maxRepeat,{id:'plan-max-repeat',min:1,max:256,integer:true})+'</div></div>','What you prefer decides the order of purchases, and whether your money set aside can be used.')
   +'</div><p class="calc-note">The plan updates itself every time you change a number. Save it to find it again with its full plan sheet, print it, or share the link.</p>';
  return '<section class="calc-panel" id="panel-plan" role="tabpanel" aria-labelledby="tab-plan" hidden><div class="calc-grid"><div class="calc-card"><p class="calc-kicker">MY BUSINESS PLAN</p><h3>Tell me your goal, I’ll build your schedule.</h3><p class="calc-card-desc">Answer the five questions: the plan tells you what to do first, second, third, session after session, with the fastest path to your goal, and what to do if things don’t go as planned.</p>'+form+'</div><div class="calc-card calc-result" id="plan-results"></div></div><div id="plan-report"></div><div class="b-stage-actions">'+btn('Download my plan as text (to read or send)','data-b-plan-export="1"')+'</div><p class="calc-note">To keep this plan with its sheet: “☆ Save the plan”, at the top or bottom of the workspace. You’ll find it later in “My calculations”.</p><div class="b-expert calc-card calc-subsection" id="expert-plan"></div></section>';}
 /* Revue de conformité (v7.53) : prévu, commencé et réalisé sont trois états distincts. « Commencé » se voit partout mais
    ne crédite rien (ni argent ni déblocage) ; seul « fait » (ou un relevé réel) compte dans le calcul. */
 function stateRadios(kind,i,st,labels){const name='plan-'+kind+'-state-'+i;return '<fieldset class="b-plan-state"><legend>Where I stand</legend>'+[['planned',labels[0]],['started',labels[1]],['done',labels[2]]].map(([v,l])=>'<label class="calc-check"><input type="radio" name="'+name+'" value="'+v+'" data-b-plan-'+kind+'-state="'+i+'" '+(st===v?'checked':'')+'> '+esc(l)+'</label>').join('')+'</fieldset>';}
 const mState=m=>m.once&&m.done?'done':m.started?'started':'planned',pState=a=>a.owned?'done':a.started?'started':'planned';
 function planStatus(s,r){const p=s.plan,once=p.missions.filter(m=>m.once),buy=p.prerequisites;const n={planned:0,started:0,done:0};once.forEach(m=>n[mState(m)]++);buy.forEach(a=>n[pState(a)]++);
  const real=p.log.length,label=real||n.started||n.done?(r&&r.valid&&(r.continuous?r.totalMinutes===0:r.totalSessions===0)&&real?'Achieved':'Started'):'Planned';
  const steps=n.planned+n.started+n.done,detail=steps?'Progress: '+plural(n.planned,'planned','planned')+', '+plural(n.started,'started','started')+(n.started?(n.started>1?' (not yet in the total)':' (not yet in the total)'):'')+', '+plural(n.done,'done','done')+(real?' · '+plural(real,'session')+(real>1?' logged with your real results':' logged with your real result')+' so far':'')+'.':real?plural(real,'session')+(real>1?' logged with your real results':' logged with your real result')+' so far.':'Nothing started yet: this is a forecast. After a session, “enter what I actually have” switches it to “started”.';
  return '<p class="b-plan-status" data-plan-status="'+label.toLowerCase()+'"><span class="calc-tag">'+esc(label.toUpperCase())+'</span> '+esc(detail)+'</p>';}
 function missionSummary(s,m,i){const p=s.plan,r=E.activity({...m,units:m.units});return '<span>'+esc(m.name||'Mission '+(i+1))+'<i class="b-plan-mission-edit">edit</i></span><small>'+(m.once&&m.done?'done · ':m.started?'started · ':'')+(r.valid?money(r.net)+' per mission · '+money(r.hourly)+' per hour, cooldown included':'numbers to fill in: '+esc(r.reason||''))+(m.requires.length?' · after '+esc(m.requires.map(id=>p.prerequisites.find(x=>x.id===id)?.name||id).join(', ')):'')+(m.owned?' · starting purchase already paid':'')+(m.once?(m.done?' · already done':' · just once'):'')+((m.requiresMissions||[]).length?' · after the mission '+esc(m.requiresMissions.map(id=>p.missions.find(x=>x.id===id)?.name||id).join(', ')):'')+'</small>';}
 function prereqHead(s,a,i){return '<span class="calc-tag">'+(i+1)+'</span><strong>'+esc(a.name)+'</strong><small>'+(a.owned?'already owned':a.price===null?'price to enter':money(a.price))+(a.boostHourly>0?' · +'+money(a.boostHourly)+'/h after that':'')+(a.minutes>0?' · '+hours(a.minutes/60)+' to get it':'')+((s.plan.locked||[]).includes(a.id)?' · must-have':'')+'</small>';}
 function syncForm(s){s.plan.missions.forEach((m,i)=>{const n=document.querySelector('[data-b-plan-m-summary="'+i+'"]');if(n){const h=missionSummary(s,m,i);if(n.innerHTML!==h)n.innerHTML=h;}});s.plan.prerequisites.forEach((a,i)=>{const n=document.querySelector('[data-b-plan-p-head="'+i+'"]');if(n){const h=prereqHead(s,a,i);if(n.innerHTML!==h)n.innerHTML=h;}});}
 function missionCard(s,m,i){const p=s.plan,g=p.goal,r=E.activity({...m,units:m.units}),pre='plan.missions.'+i+'.';
  return '<details class="b-plan-mission" '+(i===p.missions.length-1&&p.missions.length<=2?'open':'')+'><summary data-b-plan-m-summary="'+i+'">'+missionSummary(s,m,i)+'</summary><div class="calc-fields">'+field(pre+'name','Mission name',m.name,{type:'text',id:'plan-m-'+i+'-name'})+field(pre+'reward','Reward ($)',m.reward,{id:'plan-m-'+i+'-reward'})+field(pre+'duration','Duration (min)',m.duration,{id:'plan-m-'+i+'-duration',min:1,max:1e6})+field(pre+'cost','Fees each time ($)',m.cost,{id:'plan-m-'+i+'-cost'})+field(pre+'prep','Prep (min)',m.prep,{id:'plan-m-'+i+'-prep',max:1e6})+field(pre+'cooldown','Cooldown before replaying (min)',m.cooldown,{id:'plan-m-'+i+'-cooldown',max:1e6})+field(pre+'share','My share (%)',m.share,{id:'plan-m-'+i+'-share',max:100})+field(pre+'players','Played with (players)',m.players??1,{id:'plan-m-'+i+'-players',min:1,max:100,integer:true})+field(pre+'investment','To buy once before starting ($)',m.investment,{id:'plan-m-'+i+'-investment'})+(g.kind==='unlock'?field(pre+'units',esc(g.unitLabel||'Points')+' earned per mission',m.units,{id:'plan-m-'+i+'-units'}):'')+'</div><label class="calc-check"><input type="checkbox" data-b-plan-m-owned="'+i+'" '+(m.owned?'checked':'')+'> I’ve already paid what’s needed to start</label><label class="calc-check"><input type="checkbox" data-b-plan-m-once="'+i+'" '+(m.once?'checked':'')+'> Mission to do just once (it unlocks what comes next)</label>'+(m.once?stateRadios('m',i,mState(m),['Planned','Started (not counted yet)','Already done']):'')+(p.prerequisites.length?'<fieldset class="b-plan-requires"><legend>You must first have bought:</legend>'+p.prerequisites.map(a=>'<label class="calc-check"><input type="checkbox" data-b-plan-m-req="'+i+'|'+esc(a.id)+'" '+(m.requires.includes(a.id)?'checked':'')+'> '+esc(a.name)+'</label>').join('')+'</fieldset>':'')+(p.missions.length>1?'<fieldset class="b-plan-requires"><legend>You must first have done the mission:</legend>'+p.missions.filter(o=>o.id!==m.id).map(o=>'<label class="calc-check"><input type="checkbox" data-b-plan-m-reqm="'+i+'|'+esc(o.id)+'" '+((m.requiresMissions||[]).includes(o.id)?'checked':'')+'> '+esc(o.name)+(o.once?' (just once)':'')+'</label>').join('')+'</fieldset>':'')+'<div class="b-plan-card-actions">'+btn('Remove this mission','data-b-plan-m-remove="'+i+'"')+'</div></details>';}
 function prereqCard(s,a,i){const pre='plan.prerequisites.'+i+'.',item=itemFor({itemId:a.itemId});
  return '<article class="b-plan-prereq" data-b-plan-prereq="'+esc(a.id)+'"><div class="b-plan-prereq-head" data-b-plan-p-head="'+i+'">'+prereqHead(s,a,i)+'</div><div class="calc-fields">'+field(pre+'name','Name',a.name,{type:'text',id:'plan-p-'+i+'-name'})+field(pre+'price',a.referencePrice!==null?'Price ($)':'Price, based on what you imagine ($)',a.price,{id:'plan-p-'+i+'-price',hint:a.referencePrice!==null?'Site price: '+money(a.referencePrice)+'.':(item?'':'')})+field(pre+'boostHourly','It will earn me extra ($ per hour)',a.boostHourly,{id:'plan-p-'+i+'-boost',hint:'Only what this purchase earns on top. 0 otherwise.'})+field(pre+'minutes','Time to get it (min)',a.minutes,{id:'plan-p-'+i+'-minutes',max:1e6,hint:'Travel, purchase mission… Leave empty if it’s instant.'})+field(pre+'usagePerSession','What it costs each session ($)',a.usagePerSession,{id:'plan-p-'+i+'-usage',hint:'Fuel, maintenance… your number. Empty = nothing counted (no confirmed cost in GTA VI).'})+'</div>'+stateRadios('p',i,pState(a),['Planned','Started (not mine yet)','Already mine'])+'<label class="calc-check"><input type="checkbox" data-b-plan-p-lock="'+esc(a.id)+'" '+((s.plan.locked||[]).includes(a.id)?'checked':'')+'> Must-have: no approach removes it from the plan</label>'+prereqRequires(s,a,i)+'<div class="b-plan-card-actions">'+btn('↑','data-b-plan-p-up="'+i+'" aria-label="Move up '+esc(a.name)+'" '+(i===0?'disabled':''))+btn('↓','data-b-plan-p-down="'+i+'" aria-label="Move down '+esc(a.name)+'" '+(i===s.plan.prerequisites.length-1?'disabled':''))+btn('Remove','data-b-plan-p-remove="'+i+'"')+'</div></article>';}
 /* ---------- Phases : « en premier, en deuxième… », le cœur du programme ---------- */
 function stepsText(steps){return steps.map((st,i)=>(i?(i===steps.length-1?' then ':', '):'')+'“'+esc(st.name)+'” ×'+st.runs).join('');}
 function phaseCards(s,r,base){const p=s.plan,g=p.goal,dpw=r.input.daysPerWeek,D=sessionLabel(s),byName=n=>r.purchases.find(x=>x.name===n),cards=[];
  if(r.totalSessions===0)return '<ol class="b-timeline"><li class="b-phase is-goal"><span class="b-phase-n">✓</span><div><p class="b-phase-k">Right now</p><h4>'+esc(g.kind==='purchase'?'Buy '+goalShort(s):g.kind==='unlock'?'You can already unlock '+goalShort(s):'You already have '+goalShort(s))+'</h4><p>'+esc(g.kind==='purchase'?'You’ll still have '+money(r.finalCash-(r.input.goalPrice||0))+(r.input.reserve?', including '+money(r.input.reserve)+' set aside':'')+'.':'Choose a bigger goal, or a new purchase.')+'</p></div></li></ol>';
  r.phases.forEach((ph,i)=>{const range=ph.count===1?'Session '+ph.from:'Sessions '+ph.from+' to '+ph.to+' · '+plural(ph.count,'session');
   const doText=ph.steps.length?'Do '+stepsText(ph.steps)+(ph.count>1?' every session':'')+'.':'Play '+D+': you earn about '+money(ph.gain)+' per session'+(r.input.hourly>0?' based on your own earnings per hour':'')+'.';
   const boosters=r.purchases.filter(x=>x.boostHourly>0&&((x.atSession!==null&&x.atSession<ph.from)||(x.owned&&x.atSession===null))),passive=boosters.reduce((a,x)=>a+x.boostHourly,0)*r.input.sessionMinutes/60,extras=[];
   if(passive>0)extras.push('+'+money(passive)+' per session thanks to '+boosters.map(x=>'“'+esc(x.name)+'”').join(', '));if(r.input.hourly>0&&ph.steps.length)extras.push('+'+money(r.input.hourly*r.input.sessionMinutes/60)+' from your earnings per hour');if(r.input.upkeepPerSession>0)extras.push('−'+money(r.input.upkeepPerSession)+' in expenses per session');
   const extra=extras.join(' · ');
   const figures=[['Per session','+'+money(ph.gain)+(g.kind==='unlock'&&ph.unitsGain>0?' · +'+units(s,ph.unitsGain):'')],['You go from',money(ph.cashBefore)+' to '+money(ph.cashAfter)],['When',ph.from===ph.to?'day '+dayOf(ph.from,dpw)+' (around '+planDate(dayOf(ph.from,dpw),base)+')':'from day '+dayOf(ph.from,dpw)+' to day '+dayOf(ph.to,dpw)+' (around '+planDate(dayOf(ph.to,dpw),base)+')']];
   const after=ph.purchasesAfter.length?'<p class="b-phase-after"><b>After session '+ph.to+':</b> buy '+ph.purchasesAfter.map(n=>{const x=byName(n);return '“'+esc(n)+'”'+(x?' ('+money(x.price)+(x.boostHourly>0?', +'+money(x.boostHourly)+'/h after that':'')+')':'');}).join(', ')+'.</p>':'';
   cards.push('<li class="b-phase"><span class="b-phase-n">'+(i+1)+'</span><div><p class="b-phase-k">'+esc(ORDINALS[i]||'Step '+(i+1))+' · '+esc(range)+'</p><h4>'+doText+'</h4>'+(extra?'<p class="calc-note">Also counted in the total: '+extra+'.</p>':'')+'<div class="b-tiles">'+figures.map(([l,v])=>'<span><small>'+esc(l)+'</small><b>'+v+'</b></span>').join('')+'</div>'+after+'</div></li>');});
  const N=r.totalSessions,dayN=dayOf(N,dpw);
  cards.push('<li class="b-phase is-goal"><span class="b-phase-n">★</span><div><p class="b-phase-k">Goal reached · after session '+N+' · day '+dayN+' (around '+planDate(dayN,base)+')</p><h4>'+esc(g.kind==='purchase'?'Buy '+goalShort(s)+' ('+money(r.input.goalPrice)+')':g.kind==='unlock'?'You unlock '+goalShort(s)+(r.input.goalPrice>0?' and you pay for it ('+money(r.input.goalPrice)+')':''):g.meaning==='held'?'You have '+money(g.target)+' in total':g.meaning==='cumulative'?'You’ve earned '+money(g.target)+' since the start':'You have '+money(g.target)+' on hand')+'</h4><p>'+esc((g.kind==='purchase'||(g.kind==='unlock'&&r.input.goalPrice>0)?'You still have '+money(r.finalCash-(r.input.goalPrice||0))+(r.input.reserve?', including '+money(r.input.reserve)+' set aside':'')+'.':'You keep '+money(r.input.reserve)+' set aside.')+(g.kind==='purchase'&&g.boostHourly>0?' After that, this purchase earns you '+money(g.boostHourly)+' more per hour: paid back after '+hours(r.input.goalPrice/g.boostHourly)+' of play.':'')+(g.kind==='purchase'&&!(g.boostHourly>0)?' It’s a just-for-fun purchase: it won’t pay for itself, and that’s fine.':''))+'</p></div></li>');
  return '<ol class="b-timeline">'+cards.join('')+'</ol>';}
 function programSummary(r){if(!r||!r.valid)return '';if(r.continuous){const l=(r.route||[]).slice(0,8).map(x=>x.type==='acquire'?'buy '+x.name:x.type==='unlock'?x.name+' (once)':x.name+' ×'+x.runs);return l.join(' → ')+((r.route||[]).length>8?' → …':'');}return r.phases.map(ph=>(ph.count===1?'Session '+ph.from:'Sessions '+ph.from+'–'+ph.to)+': '+(ph.steps.length?ph.steps.map(st=>st.name+' ×'+st.runs).join(', '):'your earnings per hour')+(ph.purchasesAfter.length?' → then buy '+ph.purchasesAfter.join(', '):'')).join(' · ');}
 function prereqRequires(s,a,i){const others=[...s.plan.prerequisites.filter(o=>o.id!==a.id).map(o=>[o.id,o.name]),...s.plan.missions.filter(m=>m.once).map(m=>[m.id,'the mission “'+m.name+'”'])];
  return others.length?'<fieldset class="b-plan-requires"><legend>You must first have:</legend>'+others.map(([id,n])=>'<label class="calc-check"><input type="checkbox" data-b-plan-p-req="'+i+'|'+esc(id)+'" '+((a.requires||[]).includes(id)?'checked':'')+'> '+esc(n)+'</label>').join('')+'</fieldset>':'';}
 /* ---------- v7.49 : parcours sans durée de partie, chaîne des étapes, point bas, variantes gardées ---------- */
 const isFlow=r=>!!(r&&r.continuous);
 const timeText=r=>hours((r.totalMinutes||0)/60)+' of play';
 function goalStep(s){const g=s.plan.goal;return g.kind==='purchase'?'Buy '+goalShort(s):g.kind==='unlock'?'Unlock '+goalShort(s):'Reach '+goalShort(s);}
 function routeSteps(s,r,o={}){const p=s.plan,max=o.max||40,steps=[{type:'start',name:'Start',detail:money(r.startCash)+' on hand'+(r.input.reserve?' · '+money(r.input.reserve)+' set aside':''),cash:r.startCash}];
  p.prerequisites.filter(a=>a.owned).forEach(a=>steps.push({type:'start',name:a.name,detail:'Already owned'}));
  p.missions.filter(m=>m.once&&m.done).forEach(m=>steps.push({type:'start',name:m.name,detail:'Already done'}));
  p.prerequisites.filter(a=>!a.owned&&a.started).concat(p.missions.filter(m=>!(m.once&&m.done)&&m.started)).forEach(x=>steps.push({type:'start',name:x.name,detail:'Started: not counted yet (tick “done” when it’s finished)'}));
  const list=(r.route||[]).filter(x=>o.all||x.type!=='run');
  list.slice(0,max).forEach(x=>{const when=isFlow(r)?(x.start>0?'after '+hours(x.start/60)+' of play':'from the start'):x.where==='before'?'before your first session':x.where==='after'?'after session '+x.session:'during session '+x.session;
   /* v7.54 : un achat d’avant qui vient d’une fiche du site est cliquable (fiche) ; sinon, aucun lien inventé. */
   if(x.type==='acquire'){const pr=p.prerequisites.find(a=>a.id===x.id||a.name===x.name),item=pr&&pr.itemId?itemFor({itemId:pr.itemId}):null;steps.push({type:'acquire',name:x.name,url:item&&item.url?item.url:undefined,detail:'−'+money(x.spend)+' · '+when+(x.minutes>0?' · '+hours(x.minutes/60)+' to get it':''),cash:x.cashAfter});}
   else if(x.type==='unlock')steps.push({type:'unlock',name:x.name,detail:['just once',x.spend?'−'+money(x.spend):'',x.receive?'+'+money(x.receive):'',when].filter(Boolean).join(' · '),cash:x.cashAfter});
   else steps.push({type:'run',name:x.name+(x.runs>1?' ×'+x.runs:''),detail:'+'+money(x.receive-x.spend)+' net · '+hours(x.minutes/60),cash:x.cashAfter});});
  if(list.length>max)steps.push({type:'run',name:'… and '+plural(list.length-max,'step')+' more',detail:'All the steps are in “Each step”, in Expert mode.'});
  steps.push({type:'goal',name:goalStep(s),detail:isFlow(r)?'after '+timeText(r):r.totalSessions===0?'right now':'after session '+r.totalSessions,cash:r.finalCash});
  return steps;}
 function lowText(r){const L=r&&r.lowPoint;if(!L||!Number.isFinite(L.cash)||L.cash>=r.startCash-1e-9)return '';return ' Lowest point: '+money(L.cash)+(L.at?' — '+L.at.charAt(0).toLowerCase()+L.at.slice(1):'')+(r.input.reserve>0&&L.cash>=r.input.reserve-1e-9?', never below the money set aside.':r.input.reserve===0&&L.cash<((r.keptReserve??0))?', below what you wanted to set aside.':'.');}
 function lowLine(r){const t=lowText(r);return t?'<p class="b-lowpoint">'+esc(t.trim())+'</p>':'';}
 function routeBlock(s,r){if(!(r.route||[]).some(x=>x.type==='acquire'||x.type==='unlock'))return '';return visual.chain(routeSteps(s,r),{title:'The path, in order',question:'What you buy or unlock, and when: each step opens the next.',note:'A purchase is paid only once what it requires is done and the money allows it, without touching the money set aside.'});}
 function flowNext(s,r){const first=(r.route||[]).slice(0,4);if(!first.length)return '';return '<div class="calc-next-action"><strong>To start</strong><ol class="b-next-steps">'+first.map(x=>'<li>'+(x.type==='acquire'?'Buy “'+esc(x.name)+'” <span>−'+money(x.spend)+'</span>':x.type==='unlock'?'Do “'+esc(x.name)+'” (just once) <span>'+(x.receive-x.spend>=0?'+':'−')+money(Math.abs(x.receive-x.spend))+'</span>':'“'+esc(x.name)+'” ×'+x.runs+' <span>+'+money(x.receive-x.spend)+'</span>')+'</li>').join('')+'</ol>'+btn('After playing, enter what I actually have','data-b-focus="plan-actual"')+'</div>';}
 function incompleteBlock(s){const x=analysisOf?analysisOf('plan',s):null;if(!x||!x.incomplete||!x.incomplete.length)return '';const p=s.plan;
  const steps=p.prerequisites.map(a=>({type:a.owned?'start':a.price===null?'missing':'acquire',name:a.name,detail:a.owned?'Already owned':a.price===null?'Price to come: enter the price you imagine to complete the path':money(a.price)}));steps.push({type:'goal',label:'Your goal',name:goalStep(s),detail:'Calculated as soon as the path is complete'});
  return visual.chain(steps,{title:'Path to complete',question:'An unknown price is never counted as free: enter it to get the plan.'})+'<div class="b-plan-card-actions">'+x.incomplete.map(z=>btn('Enter the price of “'+z.name+'”','data-b-focus="'+esc(z.field)+'"')).join('')+'</div>';}
 const VARIANT_KEYS=['goal','situation','source','missions','prerequisites','priority','strategy','maxRepeat','deadlineDays'];
 function variantOf(s){const p=s.plan,v={id:'v-'+Date.now().toString(36)+'-'+(p.variants||[]).length,label:(goalName(s)+' · '+(p.source==='missions'?plural(p.missions.length,'mission'):money(p.situation.hourly)+'/h')).slice(0,120),at:new Date().toISOString().slice(0,10)};VARIANT_KEYS.forEach(k=>{v[k]=B.copy(p[k]);});return v;}
 function variantState(s,v){const c=B.copy(s);VARIANT_KEYS.forEach(k=>{if(v[k]!==undefined)c.plan[k]=B.copy(v[k]);});c.plan.variant='auto';return c;}
 function variantResult(s,v){try{return B.evaluate('plan',variantState(s,v));}catch(e){return {valid:false,reason:e.message};}}
 function variantCell(r){return !r||!r.valid?'To complete':r.continuous?timeText(r):(r.totalSessions===0?'Already possible':plural(r.totalSessions,'session')+' · '+plural(r.days,'day'));}
 function savedVariants(s,r){const list=s.plan.variants||[];
  let html='<p class="calc-note">A variant keeps a full copy of the plan (goal, situation, missions, purchases before the goal). Nothing is overwritten: loading a variant stores the current plan in its place.</p><div class="b-plan-card-actions">'+btn('Keep this plan as a variant','data-b-plan-vsave="1"'+(list.length>=5?' disabled':''))+'</div>';
  if(list.length)html+=table([['Variant','Kept on','Result','Money at the end'],['Current plan','—',variantCell(r),r&&r.valid?money(r.finalCash):'—'],...list.map(v=>{const x=variantResult(s,v);return [v.label,v.at||'—',variantCell(x),x&&x.valid?money(x.finalCash):'—'];})],'The current plan and your variants, recalculated with the same rules',true)+'<ul class="b-variant-list">'+list.map(v=>'<li><span>'+esc(v.label)+'</span>'+btn('Load this variant','data-b-plan-vload="'+esc(v.id)+'"')+btn('Remove','data-b-plan-vdel="'+esc(v.id)+'"')+'</li>').join('')+'</ul>';
  else html+='<p class="calc-empty">No variant kept yet. Keep this one before trying something else: you’ll be able to compare and go back.</p>';
  if(list.length>=5)html+='<p class="calc-note">Five variants max: remove one to keep another.</p>';
  return html;}
 /* ---------- Rendu principal ---------- */
 function render(){const s=state(),p=s.plan,g=p.goal,si=p.situation,r=B.evaluate('plan',s),mode=s.views.plan||'quick',expert=mode==='advanced',details=expert;syncForm(s);
  let head='<p class="calc-kicker">MY ANSWER</p><span class="calc-tag">WITH YOUR NUMBERS</span>';
  if(!r.valid){/* v7.54 : bloqué par l’argent de côté (aucun chiffre ne manque) : deux sorties proposées, sans parler d’une case à corriger. */
   if(r.blockedByReserve)head+=warning(r.reason)+'<p class="b-problem">'+btn('Choose “As fast as possible”','data-b-focus="f-plan-priority"')+' '+btn('Change the money set aside','data-b-focus="plan-reserve"')+'</p>'+incompleteBlock(s)+'<div class="calc-next-action"><strong>To get your schedule</strong><p>Nothing is missing: your money set aside is what’s blocking. Either choose “As fast as possible” in “I prefer” (the plan then dips into the money set aside, and tells you so at each step), or lower the money set aside, or add a cheaper mission to start.</p></div>';
   else head+=warning(r.reason)+problem(r.reason,'plan')+incompleteBlock(s)+'<div class="calc-next-action"><strong>To get your schedule</strong><p>A number or a choice is missing in the plan questions. Fix the highlighted box: the plan works itself out, session by session.</p></div>';
   $('plan-results').innerHTML=head;$('plan-report').innerHTML='';$('expert-plan').innerHTML='';markSkips(s);return;}
  const D=sessionLabel(s),dpw=r.input.daysPerWeek,reached=r.continuous?r.totalMinutes===0:r.totalSessions===0,next=B.planNextSession(r),first=r.phases[0];
  const meaning=g.kind==='amount'?(g.meaning||'available'):'available',needMoney=meaning==='held'?Math.max(0,r.goalMoney-r.startCash):meaning==='cumulative'?r.goalMoney:Math.max(0,r.goalMoney+r.input.reserve-r.startCash),parts=[];if(g.kind==='unlock'&&r.startUnits<r.input.targetUnits)parts.push(units(s,r.input.targetUnits-r.startUnits));if(needMoney>0||g.kind!=='unlock')parts.push(money(needMoney));
  const missingText='you still need <b>'+parts.join(' and ')+'</b>';
  const how=p.source==='missions'?'with your missions':'earning '+money(si.hourly)+' per hour',flow=isFlow(r);
  /* v7.54 : un but venu d’une fiche dont l’achat n’est pas confirmé garde sa condition jusque dans la réponse du plan (revue v7.53). */
  const goalItem=g.kind!=='amount'&&g.itemId?itemFor({itemId:g.itemId}):null,toConfirm=goalItem&&goalItem.purchasable!==true?' <i>Purchase to be confirmed in GTA VI: the plan assumes it can be bought.</i>':'';
  const phrase=reached?'Good news: you can already '+esc(g.kind==='purchase'?'buy '+goalShort(s):g.kind==='unlock'?'unlock '+goalShort(s):'have '+goalShort(s))+' with what you have, without touching what you set aside.'+toConfirm
   :flow?'For '+esc(goalName(s))+', '+missingText+'. '+how.charAt(0).toUpperCase()+how.slice(1)+', you get there in <b>'+timeText(r)+'</b>, step by step. Without a session duration, there’s no calendar: enter one to get your sessions and days.'+toConfirm
   :'For '+esc(goalName(s))+', '+missingText+'. '+how.charAt(0).toUpperCase()+how.slice(1)+', you get there in <b>'+plural(r.totalSessions,'session')+'</b> of '+D+', that’s <b>'+plural(r.days,'day')+'</b> (around '+planDate(r.days)+').'+(first&&first.steps.length?' First: '+stepsText(first.steps)+'.':'')+toConfirm;
  head+='<p class="b-answer calc-answer" data-short="'+esc(reached?'All set!':flow?timeText(r):plural(r.totalSessions,'session')+' · '+plural(r.days,'day'))+'">'+phrase+'</p>'+stats((()=>{const fin=g.kind==='purchase'&&Number.isFinite(r.input.goalPrice)?['Left after buying your goal',money(r.finalCash-r.input.goalPrice)]:['You’ll have at the end',money(r.finalCash)];return flow?[['Play time',hours(r.totalMinutes/60)],['Steps',String((r.route||[]).length)],fin]:[['Sessions of '+D,String(r.totalSessions)],['Days',String(r.days)],fin];})())+lowLine(r);
  if(g.kind==='unlock'&&r.input.targetUnits>0)head+=visual.progress('plan-progress',esc(g.unitLabel||'Points')+' already earned',Math.min(r.startUnits,r.input.targetUnits),r.input.targetUnits,'Start: '+units(s,r.startUnits)+'. Target: '+units(s,r.input.targetUnits)+'. 100% = unlocked.');
  else if(meaning==='cumulative')head+=visual.progress('plan-progress','Earned from now on',0,r.goalMoney,'You’re aiming for '+money(r.goalMoney)+' earned from now on: what you already have doesn’t count. 100% = goal reached.');
  else{const need=r.goalMoney+(meaning==='held'?0:r.input.reserve)+r.purchases.filter(x=>!x.owned||x.atSession).reduce((a,x)=>a+(x.atSession?x.price:0),0);head+=visual.progress('plan-progress','What you already have',Math.min(r.startCash,need),need,'Start: '+money(r.startCash)+'. Target: '+money(need)+' (everything you need in total, purchases before the goal included). 100% = you can pay for your goal.');}
  head+=planStatus(s,r);
  /* v7.52 (lot 5) : le plan choisi touche à l’argent mis de côté (seul chemin trouvé, ou « le plus vite » demandé) : c’est dit
     tout de suite, avec la raison et le point bas, jamais seulement dans le détail des stratégies. */
  {const kept=si.reserve??0;if(kept>0&&r.input.reserve<kept){const why=((r.strategies&&r.strategies.candidates)||[]).find(c=>c.id==='asIs');head+=warning('This plan dips into your '+money(kept)+' set aside'+(p.priority==='fast'?': you asked to go as fast as possible.':p.strategy==='useReserve'?': that’s the order you chose.':(why&&!why.valid&&why.reason?'. If you keep that money: '+why.reason:': it’s the fastest path found.'))+(r.lowPoint&&Number.isFinite(r.lowPoint.cash)?' At the lowest point, you’ll have '+money(r.lowPoint.cash)+'.':''));}}
  if(r.variant!=='auto')head+='<p class="b-variant-note"><span class="calc-tag">BACKUP PLAN</span> You’re following “'+esc(variantLabel(s,r))+'”. '+btn('Back to the best plan','data-b-plan-variant="auto"')+'</p>';
  if(reached)head+='<div class="calc-next-action"><strong>Your next step</strong><p>'+esc(g.kind==='purchase'?'Buy '+goalShort(s)+' whenever you like, leaving you with '+money(r.finalCash-(r.input.goalPrice||0))+'. Then choose a new goal.':'Your goal is reached. Choose a bigger one, or a purchase.')+'</p></div>';
  else if(flow)head+=flowNext(s,r);
  else if(next)head+='<div class="calc-next-action"><strong>Your next session ('+D+')</strong>'+(next.steps.length?'<ol class="b-next-steps">'+next.steps.map(st=>'<li>“'+esc(st.name)+'” ×'+st.runs+' <span>+'+money(st.net)+'</span></li>').join('')+'</ol>':'<p>Play '+D+': about +'+money(next.gain)+'.</p>')+'<p>'+esc('You go from '+money(r.startCash)+' to '+money(next.cashAfter+next.purchases.reduce((a,n)=>{const x=r.purchases.find(y=>y.name===n);return a+(x?x.price:0);},0))+'.')+(next.purchases.length?' <b>Then buy: '+esc(next.purchases.join(', '))+'</b> → you still have '+money(next.cashAfter)+'.':'')+(g.kind==='unlock'&&next.unitsGain>0?' +'+units(s,next.unitsGain)+'.':'')+'</p>'+btn('After playing, enter what I actually have','data-b-focus="plan-actual"')+'</div>';
  if(explainBlock&&analysisOf)head+=explainBlock(analysisOf('plan',s),'plan');
  $('plan-results').innerHTML=head;markSkips(s);
  /* ---- Le document : des « gros points » repliables. La réponse est au-dessus ; ici, chaque point s'ouvre d'un geste. ---- */
  const obs=B.planObserved(s),deadline=B.planDeadline(s,r),curve=B.planCurve(r);
  let doc='<div class="calc-card calc-subsection b-doc"><div class="b-doc-head"><div><p class="calc-kicker">MY BUSINESS PLAN · '+esc(new Date().toLocaleDateString('en-US',{day:'numeric',month:'long',year:'numeric'}))+'</p><h3>'+esc(goalName(s).charAt(0).toUpperCase()+goalName(s).slice(1))+'</h3><p class="b-doc-meta">'+esc(reached?'Already possible with what you have.':(flow?timeText(r):plural(r.totalSessions,'session')+' of '+D+' · '+plural(r.days,'day'))+' · '+(p.source==='missions'?plural(p.missions.length,'mission')+' to choose from':money(si.hourly)+' per hour')+(r.purchases.some(x=>!x.owned||x.atSession)?' · '+plural(r.purchases.filter(x=>x.atSession).length,'purchase')+' before the goal':'')+' · your numbers, not the game’s')+'</p></div><div class="b-doc-tools">'+btn('Expand all','data-b-fold-all="open"')+btn('Collapse all','data-b-fold-all="close"')+'</div></div><p class="b-doc-hint">Tap a section to open it. The key numbers are already in each title.</p>';
  let n=0;const section=(id,title,teaser,lead,body,tone)=>fold('plan-'+id,{n:++n,title,teaser,tone,body:()=>(lead?'<p class="b-doc-lead">'+lead+'</p>':'')+(typeof body==='function'?body():body)});
  /* 1. Programme */
  if(flow)doc+=section('program','Your path, in order',reached?'Already possible: nothing to do before your goal':'<b>'+timeText(r)+'</b> · '+plural((r.route||[]).length,'step')+' · no calendar','What to do, in order, with no break between sessions. Enter a session duration to get the schedule session by session, and your dates.',()=>visual.chain(routeSteps(s,r,{all:true,max:24}),{title:'The path, in order',question:'Read from top to bottom: each step opens the next.',note:'At each moment, we take the mission that earns the most per minute among those available; a purchase before the goal is paid as soon as it can be, without touching the money set aside.'})+lowLine(r),'main');
  else doc+=section('program','Your schedule, in order',reached?'Already possible: nothing to do before your goal':(first&&first.steps.length?'First: '+stepsText(first.steps)+' · <b>'+plural(r.totalSessions,'session')+'</b>, '+plural(r.phases.length,'step'):'<b>'+plural(r.totalSessions,'session')+'</b> of '+D+' · '+plural(r.days,'day')),reached?'':'What to do first, second, third… It’s the fastest path found with your missions and your time.',()=>phaseCards(s,r)+routeBlock(s,r)+lowLine(r)+(reached?'':'<p class="calc-note">How the order is chosen: in each session, we take the missions that earn the most in the session’s time, with the money you have at that moment. A purchase before the goal happens as soon as you can pay for it without touching the money you set aside; if it unlocks a mission or earns money, what follows goes faster.'+(r.limited?' The schedule comes from the sequences compared at each session: a faster one may exist.':'')+'</p>'),'main');
  /* 2. Plans de secours (calculés seulement quand on ouvre le point) */
  if(!reached){const late=obs&&obs.last&&obs.last.gap!==null&&obs.last.gap<-1e-9;
   const intro=late?'Your last session earned <b>'+money(obs.last.gain)+'</b> instead of <b>'+money(obs.last.plannedGain)+'</b> planned. The plan above already starts again from what you have; still, here are other ways to get there, with their time.':'If a mission doesn’t fit, if you earn less than planned, or if you’d rather do things differently: each plan is calculated from the same situation. Pick one, and the schedule follows.';
   doc+=section('alternatives','If things don’t go as planned',late?'<b>'+money(obs.last.gain)+'</b> earned instead of '+money(obs.last.plannedGain)+' planned · plans A, B, C…':(r.variant!=='auto'?'You’re following a backup plan · the others are here':'Plans A, B, C… calculated from your situation, ready if you earn less than planned'),intro,()=>{const alt=B.planAlternatives(s,r),plans=alt.valid?alt.plans:[],curId=r.variant==='auto'?'all':r.variant,ok=plans.filter(x=>x.valid).sort((a,b)=>(a.id===curId?-1:b.id===curId?1:0)),ko=plans.filter(x=>!x.valid);
    return (ok.length?'<ol class="b-alts">'+ok.slice(0,5).map((x,i)=>'<li class="b-alt'+(x.id===curId?' is-current':'')+'"><span class="b-alt-letter">'+String.fromCharCode(65+i)+'</span><div><h4>Plan '+String.fromCharCode(65+i)+' · '+esc(x.label)+(x.id===curId?' <span class="calc-tag">YOUR CURRENT PLAN</span>':'')+'</h4><div class="b-tiles">'+(flow?'<span><small>Play time</small><b>'+hours((x.totalMinutes||0)/60)+'</b></span>':'<span><small>Sessions</small><b>'+x.totalSessions+'</b></span><span><small>Days</small><b>'+x.days+'</b></span>')+'<span><small>At the end</small><b>'+money(x.finalCash)+'</b></span></div><p class="b-alt-program">'+esc(programSummary(alt.results[x.id]))+'</p>'+(x.note?'<p class="calc-note">'+esc(x.note)+'</p>':'')+(x.id!==curId?btn('Follow this plan','data-b-plan-variant="'+esc(x.id)+'"'):'')+'</div></li>').join('')+'</ol>':'<p>'+esc(alt.valid?'No other plan works with these numbers.':alt.reason)+'</p>')+(ko.length?'<p class="calc-note"><b>Not possible with these numbers:</b> '+ko.map(x=>esc(x.label)+' ('+esc(x.reason||'not reached')+')').join(' · ')+'</p>':'');},late?'alert':'');}
  /* 3. Suivi du réel */
  doc+=section('actual','After playing: where do you really stand?',obs?'<b>'+plural(obs.sessions,'session')+(obs.sessions>1?'</b> logged with your results':'</b> logged with your result')+' · last: '+(obs.last.gain>=0?'+':'−')+money(Math.abs(obs.last.gain))+(obs.last.gap===null?'':' ('+(obs.last.gap>=0?'+':'−')+money(Math.abs(obs.last.gap))+' compared with the plan)'):'Enter what you have after your session: the whole plan recalculates','Enter what you have now and what you did. The whole plan recalculates from there: missions, purchases, sessions, days. Nothing is counted twice.',()=>actualForm(s,r,obs));
  /* 4. Point de départ */
  const start=[['Money on hand',money(si.capital),'plan-capital'],['Set aside',money(r.input.reserve)+(r.input.reserve!==(si.reserve??0)?' (you chose “as fast as possible”)':''),'plan-reserve'],['A session',flow?'no set duration: a path with no calendar':D+' · '+dpw+' days/week','plan-daily'],['Expenses per session',money(si.upkeepPerSession||0),'plan-upkeep'],
   p.source==='missions'?['Missions to choose from',p.missions.map(m=>m.name).join(', ')||'none',p.missions.length?'plan-m-0-reward':'plan-m-source']:['Earnings per hour (your number)',money(si.hourly),'plan-hourly'],
   g.kind==='purchase'?['Your goal',esc(g.name||'my purchase')+' · '+money(g.price)+(g.boostHourly>0?' · +'+money(g.boostHourly)+'/h after that':''),'plan-price']:g.kind==='amount'?['Your goal','have '+money(g.target),'plan-target']:['Your goal','unlock '+esc(g.name||'my goal')+' · '+units(s,g.targetUnits)+(g.alsoPrice>0?' · then '+money(g.alsoPrice):''),'plan-units-target'],
   ['Purchases before the goal',p.prerequisites.length?p.prerequisites.map(a=>a.name+(a.owned?' (already owned)':' ('+money(a.price)+(a.boostHourly>0?', +'+money(a.boostHourly)+'/h':'')+')')).join(' · '):'none','plan-prereq-search']];
  doc+=section('start','Your starting point',esc(money(si.capital)+' on hand · '+D+' · '+dpw+' days/week · '+(p.source==='missions'?plural(p.missions.length,'mission'):money(si.hourly)+'/h')),'The numbers behind this plan. Change one: everything recalculates.','<ul class="b-assumptions">'+start.map(([l,v,f])=>'<li><span>'+esc(l)+'</span><b>'+v+'</b>'+btn('Edit','data-b-focus="'+f+'"')+'</li>').join('')+'</ul><p class="calc-note">Nothing comes from the real game: prices, earnings and times are your numbers, or the ones the site gives as benchmarks.</p>');
  /* 5. Stratégie */
  const st=r.strategies;
  if(st&&st.valid&&st.candidates.filter(c=>c.valid).length>1){const rec=st.candidates.find(c=>c.id===st.recommended),asIs=st.candidates.find(c=>c.id==='asIs');
   const why=rec&&asIs&&rec.id!=='asIs'&&rec.valid&&asIs.valid?((flow?rec.totalMinutes<asIs.totalMinutes-1e-9:rec.totalSessions<asIs.totalSessions)?'you save '+(flow?hours((asIs.totalMinutes-rec.totalMinutes)/60)+' of play':plural(asIs.totalSessions-rec.totalSessions,'session'))+' compared with your order':'the same '+(flow?'play time':'number of sessions')+' as your order, with '+(rec.reserveKept?'your money set aside untouched':'more money at the end')):p.priority==='cheap'?'it’s the approach that leaves the most money at the end among those that keep your money set aside':p.priority==='safe'?'it’s the approach with the highest lowest point among those that keep your money set aside':'it’s the fastest approach among those that '+(p.priority==='fast'?'were compared':'keep your money set aside');
   doc+=section('strategy','Order of the purchases before the goal','Recommended: <b>'+esc(rec?rec.label:'')+'</b> · '+st.candidates.filter(c=>c.valid).length+' approaches compared','Same goal, same numbers: only the order of purchases, or the money set aside, changes.','<p class="b-strategy-answer"><b>'+esc(rec?rec.label:'')+'</b> : '+esc(why)+'.</p>'+table([['Approach',flow?'Play time':'Sessions','Days','Money at the end','Lowest point','Reserve kept'],...st.candidates.map(c=>[(c.id===st.recommended?'★ ':'')+c.label+(c.note?' — '+c.note:''),c.valid?(flow?hours((c.totalMinutes||0)/60):String(c.totalSessions)):'Not possible: '+c.reason,c.valid&&!flow?String(c.days):'—',c.valid?money(c.finalCash):'—',c.valid&&c.lowCash!==null&&c.lowCash!==undefined?money(c.lowCash):'—',c.reserveKept?'Yes':'No'])],'Orders compared with a full recalculation',true)+'<p class="calc-note">We compare '+st.explored+' approaches; there may be a better one. Those that drop a purchase you asked for are never recommended.</p>');}
  /* 6. Échéance */
  if(p.deadlineDays){let body='';if(!deadline||!deadline.valid)body=warning(deadline?deadline.reason:'Deadline can’t be calculated.');
   else if(deadline.feasible)body='<p class="b-strategy-answer"><b>Yes</b>, it’s doable: you finish on day '+deadline.days+', with '+plural(deadline.spareDays,'day')+' to spare.</p>';
   else body='<p class="b-strategy-answer"><b>Not at your current pace</b>: you’d finish on day '+deadline.days+', that’s '+plural(deadline.spareDays,'day')+' too late.</p><ul class="b-thresholds">'+(deadline.everydayDays!==null?'<li>Play <b>every day</b>: you finish on day '+deadline.everydayDays+'.</li>':'')+(deadline.requiredSessionMinutes!==null?'<li>Or sessions of <b>'+hours(deadline.requiredSessionMinutes/60)+'</b> instead of '+D+'.</li>':'')+(deadline.requiredHourly!==null?'<li>Or earn <b>'+money(deadline.requiredHourly)+' per hour</b> instead of '+money(si.hourly)+'.</li>':'')+(deadline.everydayDays===null&&deadline.requiredSessionMinutes===null&&deadline.requiredHourly===null?'<li>No simple tweak is enough: lower the goal or change missions.</li>':'')+'<li>Otherwise, the earliest date: <b>day '+r.days+'</b> (around '+planDate(r.days)+').</li></ul>';
   doc+=section('deadline','Your deadline: '+plural(p.deadlineDays,'day'),deadline&&deadline.valid?(deadline.feasible?'<b>Doable</b> · '+plural(deadline.spareDays,'day')+' to spare':'<b>Not at your pace</b> · day '+deadline.days+' instead of '+p.deadlineDays):'To check','',body,deadline&&deadline.valid&&!deadline.feasible?'alert':'');}
  /* 7+. Détails */
  if(details&&!reached){
   const rows=r.sessions.slice(0,60).map(se=>['Session '+se.index+' · day '+dayOf(se.index,dpw),se.steps.length?se.steps.map(st=>st.name+' ×'+st.runs).join(', '):'your earnings per hour','+'+money(se.gain)+(g.kind==='unlock'&&se.unitsGain>0?' · +'+nf.format(Math.round(se.unitsGain*100)/100):''),money(se.cashAfter),se.purchases.length?se.purchases.join(', '):'—']);
   if(flow)doc+=section('route-table','Each step',plural((r.route||[]).length,'step')+' · from '+money(r.startCash)+' to '+money(r.finalCash),'Each step of the path, with what it costs, what it earns and what you have after.',()=>table([['When','Step','Paid','Received','Then you have'],...(r.route||[]).slice(0,120).map(x=>[hours(x.start/60),x.type==='acquire'?'Buy “'+x.name+'”':x.type==='unlock'?'“'+x.name+'” (just once)':'“'+x.name+'” ×'+x.runs,x.spend?'−'+money(x.spend):'—',x.receive?'+'+money(x.receive):'—',money(x.cashAfter)])],'The full path'+((r.route||[]).length>120?' (first 120 steps out of '+r.route.length+')':''),true));
   else doc+=section('sessions','Session by session',plural(r.totalSessions,'session')+' · from '+money(r.startCash)+' to '+money(r.finalCash),'Each session with its missions, what it earns, what you have after and what you buy.',()=>table([['Session','Missions','Earned','Then you have','Purchase'],...rows],'The full schedule'+(r.sessions.length>60?' (first 60 sessions out of '+r.sessions.length+')':''),true));
   doc+=section('variants','What if…?','Longer sessions, one more day, higher prices, missions that earn less…','The same plan, fully recalculated with one number changed.',()=>{const v=variants(s,r);return table([['What if…',flow?'Play time':'Sessions','Days','Money at the end'],...v.map(x=>[x.label,x.r.valid&&x.r.reached?(flow?hours(x.r.totalMinutes/60):String(x.r.totalSessions)):'Impossible',x.r.valid&&x.r.reached&&!flow?String(x.r.days):'—',x.r.valid?money(x.r.finalCash):'—'])],'To see what matters most',true);});
   doc+=section('thresholds','What changes everything','30 more min per session, the purchase before the goal right away…','',()=>{const v=variants(s,r),thresholds=[];const longer=v.find(x=>x.id==='longer');if(longer&&longer.r.valid&&longer.r.reached)thresholds.push(longer.r.totalSessions<r.totalSessions?'With <b>30 more min per session</b>, you finish in <b>'+plural(longer.r.totalSessions,'session')+'</b> instead of '+r.totalSessions+'.':'<b>30 more min per session</b> don’t change the number of sessions ('+r.totalSessions+'): time isn’t what’s holding you back.');
    const firstBuy=r.purchases.find(x=>x.atSession);if(firstBuy&&firstBuy.atSession>1)thresholds.push('You still need <b>'+money(Math.max(0,firstBuy.price+r.input.reserve-r.startCash))+'</b> to buy “'+esc(firstBuy.name)+'” right now.');
    if(g.kind==='unlock'&&r.missingUnits===0&&r.startUnits<r.input.targetUnits)thresholds.push('You still need <b>'+units(s,r.input.targetUnits-r.startUnits)+'</b> to unlock '+esc(goalShort(s))+'.');
    return thresholds.length?'<ul class="b-thresholds">'+thresholds.map(t=>'<li>'+t+'</li>').join('')+'</ul>':'<p class="calc-note">With these numbers, no small change makes a big difference to the plan.</p>';});
   if(curve.length>1)doc+=section('curve','Your money over the plan','The planned curve'+(p.log.length?' and your real points (clickable)':'')+' · '+money(r.startCash)+' → '+money(r.finalCash),'',()=>visual.chart('c-plan-curve',{title:'Your money, session after session',question:'When does each purchase become possible, and where will you be?',xTitle:'Play time (hours)',yTitle:'Money on hand ($)',unit:'$',xUnit:'h',area:false,series:[{name:'Planned with your numbers',kind:'forecast',step:true,points:curve.map(pt=>({x:pt.hours,y:pt.cash,label:pt.label,key:pt.purchase}))},...(p.log.length?[{name:'Real (what you entered)',kind:'realized',dots:true,points:p.log.map((e,i)=>({x:e.minutes/60,y:e.capital,label:new Date(e.at).toLocaleDateString('en-US'),edit:'log:'+i}))}]:[])],thresholds:r.input.reserve>0?[{y:r.input.reserve,label:'Money set aside'}]:[],reading:(flow?'Money jumps all at once with each reward and drops with each fee or purchase: nothing is smoothed out.':'Each step of the curve is one session: its money is counted at the end of the session, including the purchases made right after. The plan ends after '+plural(r.totalSessions,'session')+'.')+lowText(r),note:'The “real” points come from your updates; they aren’t smoothed. Click a real point to fix or remove it.'}));
   const cal=[...r.purchases.filter(x=>x.atSession).map(x=>['Buy “'+x.name+'”','after session '+x.atSession,'day '+dayOf(x.atSession,dpw),planDate(dayOf(x.atSession,dpw))]),[g.kind==='purchase'?'Buy '+goalShort(s):g.kind==='unlock'?'Unlock '+goalShort(s):'You have '+goalShort(s),'after session '+r.totalSessions,'day '+r.days,planDate(r.days)]];
   if(!flow)doc+=section('calendar','Your calendar','Goal around <b>'+esc(planDate(r.days))+'</b>'+(cal.length>1?' · '+plural(cal.length-1,'purchase')+' before':''),'If you play '+D+' per session, '+dpw+' day'+(E.plural(dpw)?'s':'')+' per week, starting today.',table([['Step','When','Day','Estimated date'],...cal],'The key moments',true));
   doc+=section('method','How is it calculated?','Session after session, with your numbers, nothing made up','','<p class="calc-note">Session after session: with the money you have at that moment, we look for the missions that earn the most in the session’s time (fees paid up front, reward at the end, prep and cooldown counted, a mission is done in full or not at all). We take out your expenses per session and add what your purchases already made earn you. Then we pay for the purchases before the goal, in order, as soon as the money goes above the price without touching the money set aside; a purchase can unlock a mission. We stop when you can pay for your goal (and have the points, if any are needed). Days = sessions spread over your play days per week, starting today. Nothing comes from the real game.</p>'+(flow?'<p class="calc-note">Without a session duration, the path chains the steps with no break: at each moment, the mission that earns the most per minute among those available, the purchases before the goal as soon as they can be paid, the cooldowns when needed. So there are no days, only play time.</p>':''));}
  else if(!reached&&mode!=='advanced')doc+='<div class="b-doc-more"><p class="calc-note">Each session, the “what ifs”, the curve and the calendar are in Expert mode.</p>'+btn('View in Expert mode','data-b-mode="advanced"')+'</div>';
  doc+=section('saved','My plan variants',(p.variants||[]).length?'<b>'+plural(p.variants.length,'variant')+(p.variants.length>1?'</b> saved as backups':'</b> saved as backup')+' · compare with your current plan':'Save this plan before trying something else','',()=>savedVariants(s,r));
  doc+='<div class="b-plan-links">'+btn('Prepare my next session','data-open="session"')+btn('Check what a purchase earns','data-open="roi"')+btn('Compare purchases','data-open="compare"')+'</div></div>';
  $('plan-report').innerHTML=doc;
  $('expert-plan').innerHTML=expert?expertBlock(s,r):'';
 }
 function markSkips(s){document.querySelectorAll('#panel-plan .calc-step[data-step="4"]').forEach(n=>{if(!s.plan.prerequisites.length&&s.plan.goal.kind==='amount')n.dataset.skip='1';else delete n.dataset.skip;});}
 function variantLabel(s,r){if(r.variant==='auto')return '';const alt=B.planAlternatives(s,r);const x=alt.valid?alt.plans.find(y=>y.id===r.variant):null;return x?x.label:r.variant;}
 function variants(s,r){const i=r.input,out=[];const run=(id,label,changes)=>out.push({id,label,r:E.missionPlan({...i,...changes})});
  if(i.sessionMinutes)run('longer','Sessions 30 min longer',{sessionMinutes:i.sessionMinutes+30});
  if(i.sessionMinutes&&i.daysPerWeek<7)run('everyday','One more play day per week',{daysPerWeek:i.daysPerWeek+1});
  run('prices','Prices are 20% higher',{goalPrice:i.goalPrice===null?null:i.goalPrice*1.2,target:i.target===null?null:i.target*1.2,purchases:i.purchases.map(x=>({...x,price:x.price*1.2}))});
  run('less',s.plan.source==='missions'?'My missions earn 20% less':'I earn 20% less',s.plan.source==='missions'?{activities:i.activities.map(a=>({...a,reward:a.reward===null?null:a.reward*0.8}))}:{hourly:i.hourly*0.8});
  if(i.reserve>0)run('reserve','I also spend my money set aside',{reserve:0});
  return out;}
 function actualForm(s,r,obs){const p=s.plan,g=p.goal,si=p.situation,next=B.planNextSession(r);
  let html='<div class="calc-fields b-actual"><div class="calc-field"><label class="calc-label" for="plan-actual">I now have ($)</label><input id="plan-actual" type="text" inputmode="decimal" maxlength="25" data-number="1" data-min="0" data-max="1000000000000" value="" placeholder="'+esc(nf.format(si.capital??0))+'"><small>Your cash on hand after your session.</small></div><div class="calc-field"><label class="calc-label" for="plan-actual-minutes">I played (minutes)</label><input id="plan-actual-minutes" type="text" inputmode="decimal" maxlength="6" data-number="1" data-min="0" data-max="100000" value="'+esc(si.dailyMinutes??'')+'"></div>';
  if(g.kind==='unlock')html+='<div class="calc-field"><label class="calc-label" for="plan-actual-units">I now have ('+esc(g.unitLabel||'points')+')</label><input id="plan-actual-units" type="text" inputmode="decimal" maxlength="25" data-number="1" data-min="0" data-max="1000000000000" value="" placeholder="'+esc(nf.format(g.currentUnits??0))+'"></div>';
  if(p.source==='missions')html+=p.missions.map(m=>{const planned=next?next.steps.find(st=>st.id===m.id):null;return '<div class="calc-field"><label class="calc-label" for="plan-actual-runs-'+esc(m.id)+'">« '+esc(m.name)+'” done how many times?</label><input id="plan-actual-runs-'+esc(m.id)+'" data-b-plan-actual-runs="'+esc(m.id)+'" type="text" inputmode="numeric" maxlength="6" data-number="1" data-min="0" data-max="100000" value="" placeholder="'+(planned?'planned: '+planned.runs:'0')+'"></div>';}).join('');
  html+='<div class="calc-field wide"><label class="calc-label" for="plan-actual-note">A note, if you want</label><input id="plan-actual-note" type="text" maxlength="300" value="" placeholder="What happened during the session"></div></div>';
  const buyable=p.prerequisites.filter(a=>!a.owned);if(buyable.length)html+='<fieldset class="b-plan-requires"><legend>During this session, I bought:</legend>'+buyable.map(a=>'<label class="calc-check"><input type="checkbox" data-b-plan-actual-bought="'+esc(a.id)+'"> '+esc(a.name)+(a.price!==null?' ('+money(a.price)+')':'')+'</label>').join('')+'</fieldset>';
  html+='<div class="b-plan-card-actions">'+btn('Update my plan','data-b-plan-log="1"',true)+(p.log.length?btn('Clear history','data-b-plan-clear="1"'):'')+'</div><p class="calc-note" id="plan-log-feedback" role="status"></p>';
  if(obs&&obs.last){const L=obs.last,gap=L.gap;
   html+='<div class="b-bilan"><p class="calc-kicker">YOUR LAST SESSION RECAP</p><div class="b-tiles">'+[['Planned',L.plannedGain===null?'—':'+'+money(L.plannedGain)],['Actual','+'+money(L.gain)],['Difference',gap===null?'—':(gap>=0?'+':'−')+money(Math.abs(gap))],['Your real pace',obs.hourly===null?'—':money(Math.round(obs.hourly))+' per hour']].map(([l,v])=>'<span><small>'+esc(l)+'</small><b>'+v+'</b></span>').join('')+'</div><p>'+esc(gap===null?'The plan restarts from what you have now.':gap>=0?'You’re ahead: the plan restarts from what you have, and it’s shorter.':'You earned less than planned: the plan restarts from what you have, and the “If things don’t go as planned” section suggests other routes.')+(obs.sessions>1?' Over your '+obs.sessions+' logged sessions, you earn an average of '+money(obs.perSession)+' per session.':'')+'</p>'+(p.source==='hourly'&&obs.hourly!==null&&Math.abs(obs.hourly-(si.hourly||0))>1?btn('Use my real pace ('+money(obs.hourly)+' per hour)','data-b-plan-adopt="1"'):'')+'</div>';}
  if(p.log.length){const rows=p.log.slice().reverse().map(e=>{const d=new Date(e.at),date=Number.isFinite(d.getTime())?d.toLocaleDateString('en-US',{day:'numeric',month:'short'}):'—';return [date,hours(e.minutes/60),e.plannedGain===null?'—':'+'+money(e.plannedGain),e.gain===null?'—':'+'+money(e.gain),money(e.capital),e.forecast===null?'—':money(e.forecast),Object.keys(e.runs).length?Object.entries(e.runs).filter(([,n])=>n>0).map(([id,n])=>(p.missions.find(m=>m.id===id)?.name||id)+' ×'+n).join(', ')+(e.purchases.length?' · bought: '+e.purchases.map(id=>p.prerequisites.find(a=>a.id===id)?.name||id).join(', '):''):(e.purchases.length?'bought: '+e.purchases.map(id=>p.prerequisites.find(a=>a.id===id)?.name||id).join(', '):'—'),e.note||'—'];});
   html+=table([['Date','Total played','Planned (session)','Actual (session)','I had','The plan expected','Done','Note'],...rows],'Actual vs. planned, session by session',true)+'<p class="calc-note">“The plan expected” = the money expected after that play time, according to the plan before the update. The current plan always restarts from your actual numbers.</p>';}
  return html;}
 function expertBlock(s,r){const RAW={totalSessions:'Sessions',totalMinutes:'Play time (min)',activeMinutes:'Time in missions (min)',days:'Days',weeks:'Weeks',finalCash:'Money at the end ($)',finalUnits:'Points at the end',missing:'Still missing ($)',missingUnits:'Points still missing',averagePerSession:'Earned per session, on average ($)',goalMoney:'Money to have ($)',startCash:'Starting money ($)',startUnits:'Starting points'};const rows=Object.entries(r).filter(([k,v])=>RAW[k]&&(typeof v==='number'||v===null)).map(([k,v])=>[RAW[k],v===null?'Can’t be calculated yet':nf.format(v)]);const i=r.input;
  return '<div class="b-doc b-doc--light"><div class="b-doc-title b-doc-title--plain"><span class="b-doc-num">★</span><div><h3>Expert mode: every detail</h3><p class="b-doc-lead">Expert mode shows everything: each session, the “what ifs”, the curve, the calendar and every number in the calculation. They’re the same numbers as in Simple, with the details.</p></div></div>'+fold('plan-x-inputs',{n:1,title:'The numbers used',teaser:esc(money(i.capital)+' · set aside '+money(i.reserve)+' · '+(i.sessionMinutes?hours(i.sessionMinutes/60):'no set duration')+' · purchase order: '+STRATEGY_LABEL[r.strategy||'asIs']),body:()=>table([['Number','Value'],['Money',money(i.capital)],['Set aside',money(i.reserve)],['Session duration',(i.sessionMinutes?hours(i.sessionMinutes/60):'no set duration')],['Days per week',String(i.daysPerWeek)],['Expenses per session',money(i.upkeepPerSession)],['I earn per hour',money(i.hourly)],['Missions',i.activities.map(a=>a.name).join(', ')||'none'],['Goal',i.goalPrice!==null?i.goalName+': '+money(i.goalPrice):i.target!==null?'Reach '+money(i.target):'Unlock '+i.goalName],['Points to reach',i.targetUnits===null?'—':nf.format(i.targetUnits)+' (already '+nf.format(i.currentUnits)+')'],['Purchases before the goal (counted)',i.purchases.map(x=>x.name).join(', ')||'none'],['Purchase order',STRATEGY_LABEL[r.strategy||'asIs']],['Plan followed',!r.variant||r.variant==='auto'?'the calculator chooses':String(r.variant)]],'The numbers used')})+fold('plan-x-raw',{n:2,title:'All the numbers in the calculation',teaser:esc(rows.length+' numbers'),body:()=>table(rows,'All the numbers in the calculation')})+'</div>';}
 /* ---------- Événements propres au plan ---------- */
 function event(ev){const el=ev.target,s=state(),p=s.plan;
  if(ev.type==='change'){
   if(el.dataset.field==='plan.goal.kind'){if(B.PLAN_KINDS.includes(el.value))p.goal.kind=el.value;p.variant='auto';refresh(el.id);return true;}
   if(el.dataset.field==='plan.source'){if(B.PLAN_SOURCES.includes(el.value))p.source=el.value;p.variant='auto';refresh(el.id);return true;}
   if(el.dataset.field==='plan.strategy'){p.strategy=B.STRATEGIES.includes(el.value)?el.value:'auto';api.changed();return true;}
   if(el.dataset.bPlanMOwned!==undefined){const m=p.missions[Number(el.dataset.bPlanMOwned)];if(m)m.owned=el.checked;api.changed();return true;}
   if(el.dataset.bPlanMReq!==undefined){const [i,id]=el.dataset.bPlanMReq.split('|'),m=p.missions[Number(i)];if(m){m.requires=el.checked?[...new Set([...m.requires,id])]:m.requires.filter(x=>x!==id);}api.changed();return true;}
   if(el.dataset.bPlanMOnce!==undefined){const m=p.missions[Number(el.dataset.bPlanMOnce)];if(m){m.once=el.checked;if(!m.once)m.done=false;}p.variant='auto';refresh(el.id);return true;}
   if(el.dataset.bPlanMState!==undefined){const m=p.missions[Number(el.dataset.bPlanMState)];if(m&&el.checked){m.done=el.value==='done'&&m.once;m.started=el.value==='started';}p.variant='auto';api.changed();return true;}
   if(el.dataset.bPlanPState!==undefined){const a=p.prerequisites[Number(el.dataset.bPlanPState)];if(a&&el.checked){a.owned=el.value==='done';a.started=el.value==='started';}p.variant='auto';api.changed();return true;}
   if(el.dataset.bPlanMDone!==undefined){const m=p.missions[Number(el.dataset.bPlanMDone)];if(m)m.done=el.checked&&m.once;p.variant='auto';api.changed();return true;}
   if(el.dataset.bPlanMReqm!==undefined){const [i,id]=el.dataset.bPlanMReqm.split('|'),m=p.missions[Number(i)];if(m&&id!==m.id){m.requiresMissions=el.checked?[...new Set([...(m.requiresMissions||[]),id])]:(m.requiresMissions||[]).filter(x=>x!==id);}p.variant='auto';api.changed();return true;}
   if(el.dataset.bPlanPReq!==undefined){const [i,id]=el.dataset.bPlanPReq.split('|'),a=p.prerequisites[Number(i)];if(a&&id!==a.id){a.requires=el.checked?[...new Set([...(a.requires||[]),id])]:(a.requires||[]).filter(x=>x!==id);}p.variant='auto';api.changed();return true;}
   if(el.dataset.bPlanPLock!==undefined){const id=el.dataset.bPlanPLock;p.locked=el.checked?[...new Set([...(p.locked||[]),id])]:(p.locked||[]).filter(x=>x!==id);p.variant='auto';api.changed();return true;}
   if(el.dataset.bPlanPOwned!==undefined){const a=p.prerequisites[Number(el.dataset.bPlanPOwned)];if(a)a.owned=el.checked;p.variant='auto';api.changed();return true;}
   if(el.dataset.bPlanActualBought!==undefined||el.dataset.bPlanActualRuns!==undefined)return true;
  }
  if(ev.type==='input'&&(el.id==='plan-actual'||el.id==='plan-actual-minutes'||el.id==='plan-actual-units'||el.id==='plan-actual-note'||el.dataset.bPlanActualRuns!==undefined))return true;
  if(ev.type==='click'){const button=el.closest('button');if(!button)return false;const d=button.dataset;
   if(d.bPlanImportCalcs){importFromCalcs(s);p.variant='auto';refresh('plan-capital');api.notify('Your numbers from My calculations were copied into the plan. You can change them here without changing anything there.');return true;}
   if(d.bPlanFree){p.goal.kind='purchase';p.goal.itemId='';p.goal.referencePrice=null;if(!p.goal.name)p.goal.name='My goal';refresh('plan-name');return true;}
   if(d.bPlanPriceReset){p.goal.price=p.goal.referencePrice;refresh('plan-price');return true;}
   if(d.bPlanMAdd){if(p.missions.length>=12){api.notify('Twelve missions max in the plan.');return true;}const id='m-'+Date.now().toString(36)+'-'+p.missions.length;p.missions.push({...B.copy(B.planMissionTemplate),id,name:'Mission '+(p.missions.length+1)});p.source='missions';p.variant='auto';refresh('plan-m-'+(p.missions.length-1)+'-name');return true;}
   if(d.bPlanMImport){const sel=$('plan-m-source');if(!sel)return true;const [kind,id]=sel.value.split(':'),a=(kind==='mine'?s.activities:sourceActivities).find(x=>x.id===id);if(!a)return true;if(p.missions.length>=12){api.notify('Twelve missions max in the plan.');return true;}
    p.missions.push({...B.copy(B.planMissionTemplate),id:'m-'+Date.now().toString(36)+'-'+p.missions.length,name:a.name,reward:a.reward??null,cost:a.cost??0,duration:a.duration??null,prep:a.prep??0,cooldown:a.cooldown??0,share:a.share??100,investment:a.investment??0,owned:a.owned===true});p.source='missions';p.variant='auto';refresh('plan-m-'+(p.missions.length-1)+'-name');api.notify('“'+a.name+'” copied into the plan.');return true;}
   if(d.bPlanMRemove!==undefined){const [gone]=p.missions.splice(Number(d.bPlanMRemove),1);if(gone){p.missions.forEach(m=>{m.requiresMissions=(m.requiresMissions||[]).filter(x=>x!==gone.id);});p.prerequisites.forEach(a=>{a.requires=(a.requires||[]).filter(x=>x!==gone.id);});p.locked=(p.locked||[]).filter(x=>x!==gone.id);}p.variant='auto';refresh('plan-m-source');return true;}
   if(d.bPlanPAdd){if(p.prerequisites.length>=20){api.notify('Twenty purchases before the goal, max.');return true;}p.prerequisites.push({...B.copy(B.planPrereqTemplate),id:'p-'+Date.now().toString(36)+'-'+p.prerequisites.length,name:'My purchase before the goal'});p.variant='auto';refresh('plan-p-'+(p.prerequisites.length-1)+'-name');return true;}
   if(d.bPlanPRemove!==undefined){const [a]=p.prerequisites.splice(Number(d.bPlanPRemove),1);if(a){p.missions.forEach(m=>{m.requires=m.requires.filter(x=>x!==a.id);});p.prerequisites.forEach(o=>{o.requires=(o.requires||[]).filter(x=>x!==a.id);});p.locked=(p.locked||[]).filter(x=>x!==a.id);}p.variant='auto';refresh('plan-prereq-search');return true;}
   if(d.bPlanPUp!==undefined||d.bPlanPDown!==undefined){const i=Number(d.bPlanPUp??d.bPlanPDown),j=i+(d.bPlanPUp!==undefined?-1:1);if(j>=0&&j<p.prerequisites.length)[p.prerequisites[i],p.prerequisites[j]]=[p.prerequisites[j],p.prerequisites[i]];refresh();return true;}
   if(d.bPlanVariant!==undefined){p.variant=d.bPlanVariant||'auto';api.changed();api.notify(p.variant==='auto'?'Back to the best plan found.':'The schedule now follows this backup plan.');return true;}
   if(d.bPlanAdopt){const obs=B.planObserved(s);if(obs&&obs.hourly!==null){p.situation.hourly=Math.round(obs.hourly);document.querySelectorAll('[data-field="plan.situation.hourly"]').forEach(i=>{i.value=p.situation.hourly;});api.changed();api.notify('Your earnings per hour are now what you actually got: '+money(p.situation.hourly)+'.');}return true;}
   if(d.bPlanVsave){p.variants=p.variants||[];if(p.variants.length>=5){api.notify('Five variants max: remove one to keep another.');return true;}p.variants.push(variantOf(s));api.changed();api.notify('Plan saved as a variant. You can now try something else.');return true;}
   if(d.bPlanVload){const k=(p.variants||[]).findIndex(v=>v.id===d.bPlanVload);if(k<0)return true;const v=p.variants[k],current=variantOf(s);VARIANT_KEYS.forEach(key=>{if(v[key]!==undefined)p[key]=B.copy(v[key]);});p.variants.splice(k,1,current);p.variant='auto';refresh('plan-capital');api.notify('Variant restored. The previous plan is saved in its place among your variants: nothing is lost.');return true;}
   if(d.bPlanVdel){p.variants=(p.variants||[]).filter(v=>v.id!==d.bPlanVdel);api.changed();api.notify('Variant removed.');return true;}
   if(d.bPlanLog){return logSession(s);}
   if(d.bPlanClear){p.log=[];p.playedMinutes=0;p.sessionsPlayed=0;api.changed();api.notify('History cleared. Your current money is kept.');return true;}
   if(d.bPlanExport){const r=B.evaluate('plan',s);const text=exportText(s,r);const blob=new Blob([text],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mon-business-plan-leonidakit.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);api.notify('Plan exported as readable text.');return true;}
  }
  return false;}
 /* v7.54 : « Reprendre mes chiffres » copie tout ce que les huit calculs ont pris en compte (revue v7.53, écart B1) : le sens du but,
    les dépenses par partie, le groupe, et pour chaque achat d’avant son coût d’usage par partie, son gain (écrit ou venu de
    « Ça vaut le coup ? »), ses dépendances et ce qu’il a de « déjà à moi ». Une option ou un frais inconnu reste inconnu : le prix
    de l’achat devient « à écrire », jamais 0. Chaque mission garde son nombre de joueurs. */
 function importFromCalcs(s){const p=s.plan,g=s.goal;p.situation.capital=g.capital;p.situation.reserve=g.reserve??0;p.situation.hourly=g.hourly;p.situation.dailyMinutes=g.dailyMinutes??s.session.usualMinutes??s.session.minutes;p.situation.daysPerWeek=s.session.daysPerWeek??7;
  p.situation.players=Number.isInteger(g.players)&&g.players>0?g.players:1;if(Number.isFinite(g.upkeepPerSession))p.situation.upkeepPerSession=g.upkeepPerSession;
  if(p.goal.kind==='amount'&&p.goal.target===null)p.goal.target=g.target;if(p.goal.kind==='amount'&&g.meaning&&B.GOAL_MEANINGS.includes(g.meaning))p.goal.meaning=g.meaning;
  const total=a=>a.price===null||a.extras===null||a.fees===null?null:a.price+(a.extras||0)+(a.fees||0);
  const boost=a=>{if(a.owned)return 0;if(a.incomeMode==='personal'&&Number.isFinite(a.boostHourly))return a.boostHourly;if(a.incomeMode==='roi'&&s.roi.key===a.key){const r=B.roi(s,sourceActivities);return ['new','improve'].includes(s.roi.mode)&&r.valid&&Number.isFinite(r.netHourly)?Math.max(0,r.netHourly):0;}return 0;};
  const usage=a=>{const u=B.usageOf(s,a,itemFor(a));return u&&u.perSession&&typeof u.perSession.v==='number'&&Number.isFinite(u.perSession.v)&&u.perSession.s!=='unconfirmed'?u.perSession.v:null;};
  const byKey={},existing=new Map(p.prerequisites.map(a=>[a.itemId||a.name,a]));
  s.order.keys.forEach(k=>{const a=B.asset(s,k);if(!a)return;const found=existing.get(a.itemId||a.name);if(found){byKey[k]=found.id;return;}if(p.prerequisites.length>=20)return;const id='p-'+Date.now().toString(36)+'-'+p.prerequisites.length;byKey[k]=id;p.prerequisites.push({...B.copy(B.planPrereqTemplate),id,name:a.name,itemId:a.itemId||'',referencePrice:a.referencePrice??null,price:total(a),boostHourly:boost(a),owned:a.owned===true,usagePerSession:usage(a),requires:[]});});
  s.order.keys.forEach(k=>{const a=B.asset(s,k),pr=p.prerequisites.find(x=>x.id===byKey[k]);if(!a||!pr)return;pr.requires=[...new Set([...(pr.requires||[]),...(a.requires||[]).map(r=>byKey[r]).filter(Boolean)])];});
  const names=new Set(p.missions.map(m=>m.name));s.activities.filter(a=>Number.isFinite(a.reward)&&Number.isFinite(a.duration)&&s.session.enabled.includes(a.id)).forEach(a=>{if(names.has(a.name)||p.missions.length>=12)return;p.missions.push({...B.copy(B.planMissionTemplate),id:'m-'+Date.now().toString(36)+'-'+p.missions.length,name:a.name,reward:a.reward,cost:a.cost??0,duration:a.duration,prep:a.prep??0,cooldown:a.cooldown??0,share:a.share??100,investment:a.investment??0,owned:a.owned===true,players:Number.isInteger(a.players)&&a.players>0?a.players:1,requires:(a.requiresPurchaseIds||[]).map(id=>{const k=s.assets.find(x=>x.itemId===id)?.key;return k?byKey[k]:null;}).filter(Boolean)});});
  if(s.model==='cycles'&&p.missions.length)p.source='missions';}
 function logSession(s){const p=s.plan,g=s.plan.goal,fb=$('plan-log-feedback');
  const cap=parse($('plan-actual')?.value),mins=parse($('plan-actual-minutes')?.value);
  if(cap===null||cap<0||cap>1e12){if(fb)fb.textContent='Enter what you have now, as a number (for example 350,000).';$('plan-actual')?.focus();return true;}
  if(mins===null||mins<0||mins>1e5){if(fb)fb.textContent='Enter the time played in minutes (for example 60).';$('plan-actual-minutes')?.focus();return true;}
  let unitsNow=null;if(g.kind==='unlock'){const v=parse($('plan-actual-units')?.value);if(v!==null){if(v<0||v>1e12){if(fb)fb.textContent='Enter your '+g.unitLabel+' as a number.';$('plan-actual-units')?.focus();return true;}unitsNow=v;}}
  const runs={};document.querySelectorAll('[data-b-plan-actual-runs]').forEach(el=>{const v=parse(el.value);if(v!==null&&v>=0)runs[el.dataset.bPlanActualRuns]=Math.round(v);});
  const bought=[...document.querySelectorAll('[data-b-plan-actual-bought]:checked')].map(el=>el.dataset.bPlanActualBought).filter(id=>p.prerequisites.some(a=>a.id===id));
  const note=String($('plan-actual-note')?.value||'').slice(0,300);
  // v7.49 : une même mise à jour envoyée deux fois n’est comptée qu’une fois (identifiant tiré de son contenu et du point de départ).
  const logId=B.planLogId({prev:p.situation.capital,cap,mins,runs,bought,units:unitsNow,count:p.log.length?p.log[p.log.length-1].id||p.log.length:0});
  if(p.log.some(e=>e.id===logId)){if(fb)fb.textContent='This session is already logged: nothing is counted twice.';return true;}
  const before=B.evaluate('plan',s),curve=before.valid?B.planCurve(before):[],next=B.planNextSession(before);
  const at=E.planCashAt({points:curve.map(pt=>({hours:pt.hours,cash:pt.cash})),hours:((p.playedMinutes||0)+mins)/60}),forecast=at&&at.valid?at.cash:null;
  const spent=bought.reduce((a,id)=>a+(p.prerequisites.find(x=>x.id===id)?.price||0),0),gain=Number.isFinite(p.situation.capital)?cap-p.situation.capital+spent:null,plannedGain=next?next.gain:null;
  const unitsGain=unitsNow!==null&&Number.isFinite(g.currentUnits)?unitsNow-g.currentUnits:null;
  p.situation.capital=cap;if(unitsNow!==null)g.currentUnits=unitsNow;bought.forEach(id=>{const a=p.prerequisites.find(x=>x.id===id);if(a)a.owned=true;});
  p.playedMinutes=(p.playedMinutes||0)+mins;p.sessionsPlayed=(p.sessionsPlayed||0)+1;
  p.log.push({id:logId,at:new Date().toISOString(),capital:cap,minutes:p.playedMinutes,forecast,note,units:unitsNow,unitsGain,gain,plannedGain,sessionMinutes:mins,runs,purchases:bought});if(p.log.length>60)p.log=p.log.slice(-60);
  document.querySelectorAll('[data-field="plan.situation.capital"]').forEach(i=>{i.value=cap;});if(unitsNow!==null)document.querySelectorAll('[data-field="plan.goal.currentUnits"]').forEach(i=>{i.value=unitsNow;});
  if(bought.length)refresh('plan-actual');else api.changed();
  const gap=plannedGain===null||gain===null?null:gain-plannedGain;
  /* v7.51 (lot 4) : un achat déclaré fait range le véhicule ou l’arme de la fiche dans son carnet (garage, arsenal). Le
     journal des réalisations (carnets-core.js) tient l’identifiant de la partie : enregistrer deux fois ne range rien deux
     fois. Une prévision du plan, elle, ne coche jamais rien et ne retire jamais rien. */
  const ranged=[];if(bought.length&&global.LKCarnets){try{const K=global.LKCarnets.create({storage:global.localStorage});bought.forEach(id=>{const a=p.prerequisites.find(x=>x.id===id),item=a&&a.itemId?itemFor({itemId:a.itemId}):null,fam=item?({vehicle:'vehicules',weapon:'armes'})[item.type]:null;if(!fam||!/^[a-z0-9][a-z0-9-]{0,99}$/.test(item.id))return;const r=K.applyEvent('plan:'+logId+':'+id,[{type:'own',famille:fam,id:item.id}]);if(r&&r.applied)ranged.push(item.name+(fam==='armes'?' (My arsenal)':' (My garage)'));});}catch(e){/* stockage indisponible : le plan reste juste, rien n’est annoncé */}}
  api.notify('Plan recalculated from '+money(cap)+'.'+(gap===null?'':gap>=0?' You’ve earned '+money(gap)+' more than planned.':' You’ve earned '+money(-gap)+' less than planned: check the backup plans.')+(ranged.length?' Added to your trackers: '+ranged.join(', ')+'.':''));return true;}
 /* ---------- Fiche complète (enregistrement) : le plan entier, lisible comme un document ---------- */
 function sheet(cfg,at){const s=cfg,p=s.plan,g=p.goal,si=p.situation,r=B.evaluate('plan',s),base=at||new Date().toISOString(),date=new Date(base),dateText=Number.isFinite(date.getTime())?date.toLocaleDateString('en-US',{day:'numeric',month:'long',year:'numeric'}):'—';
  let html='<article class="b-sheet"><div class="b-sheet-head"><p class="calc-kicker">LEONIDAKIT · BUSINESS PLAN SHEET</p><h2 id="calc-sheet-title">'+esc(s.name||'My plan')+'</h2><p class="b-doc-meta">'+esc('Goal: '+goalName(s)+' · saved on '+dateText)+'</p></div>';
  if(!r.valid){html+='<p class="calc-warning">'+esc('Plan couldn’t be calculated when it was saved: '+r.reason)+'</p></article>';return html;}
  const D=sessionLabel(s),dpw=r.input.daysPerWeek,reached=r.continuous?r.totalMinutes===0:r.totalSessions===0;
  html+='<section><h3>In short</h3><div class="b-tiles">'+(isFlow(r)?[['Play time',hours(r.totalMinutes/60)]]:[['Sessions of '+D,String(r.totalSessions)],['Days',String(r.days)]]).concat([['Start',money(r.startCash)],['At the end',money(r.finalCash)]]).map(([l,v])=>'<span><small>'+esc(l)+'</small><b>'+v+'</b></span>').join('')+'</div><p>'+esc(reached?'The goal is already possible with what you have.':isFlow(r)?'It takes '+timeText(r)+', step by step (no calendar).'+lowText(r):'It takes '+plural(r.totalSessions,'session')+' of '+D+', '+dpw+' day'+(E.plural(dpw)?'s':'')+' per week: around '+planDate(r.days,base)+' if you start on '+dateText+'.')+'</p></section>';
  html+='<section><h3>The goal</h3><p>'+esc(g.kind==='purchase'?(g.name||'My purchase')+' — '+money(g.price)+(g.boostHourly>0?', it will earn '+money(g.boostHourly)+' more per hour once bought':', fun purchase'):g.kind==='amount'?(g.meaning==='held'?'Reach '+money(g.target)+' in total, money set aside included':g.meaning==='cumulative'?'Earn '+money(g.target)+' starting now':'Reach '+money(g.target)+' on hand, on top of the money set aside'):'Unlock '+(g.name||'my goal')+': reach '+nf.format(g.targetUnits)+' '+g.unitLabel+' (already '+nf.format(g.currentUnits||0)+')'+(g.alsoPrice>0?', then pay '+money(g.alsoPrice):''))+'.</p></section>';
  html+='<section><h3>Where I stand</h3><ul class="b-sheet-list"><li>Cash on hand: <b>'+money(si.capital)+'</b></li><li>Set aside: <b>'+money(si.reserve)+'</b>'+(r.input.reserve!==(si.reserve??0)?' (you chose “as fast as possible”)':'')+'</li><li>One session: <b>'+D+'</b>, '+dpw+' day'+(E.plural(dpw)?'s':'')+' per week</li>'+(si.upkeepPerSession>0?'<li>Expenses per session: <b>'+money(si.upkeepPerSession)+'</b></li>':'')+(p.source==='hourly'?'<li>I earn about <b>'+money(si.hourly)+' per hour</b></li>':'')+'</ul></section>';
  if(p.source==='missions'&&p.missions.length)html+='<section><h3>My missions</h3>'+table([['Mission','Reward','Fees','Duration','Cooldown','Per mission','Per hour'+(g.kind==='unlock'?'':'')].concat(g.kind==='unlock'?[g.unitLabel]:[]),...p.missions.map(m=>{const a=E.activity(m);return [m.name+(m.requires.length?' (after: '+m.requires.map(id=>p.prerequisites.find(x=>x.id===id)?.name||id).join(', ')+')':''),money(m.reward),money(m.cost),hours(((m.duration||0)+(m.prep||0))/60),m.cooldown?hours(m.cooldown/60):'—',a.valid?money(a.net):'—',a.valid?money(a.hourly):'—'].concat(g.kind==='unlock'?[nf.format(m.units||0)]:[]);})],'Your numbers, fees paid first, reward at the end',true)+'</section>';
  html+='<section><h3>The schedule, in order</h3>'+(isFlow(r)?visual.chain(routeSteps(s,r,{all:true,max:30}),{title:'The path, in order'}):phaseCards(s,r,base)+routeBlock(s,r))+'</section>';
  if(r.purchases.length)html+='<section><h3>My purchases and investments</h3>'+table([['Purchase','Price','When','What it earns afterward'],...r.purchases.map(x=>[x.name,money(x.price),x.owned&&!x.atSession?'already owned':x.atSession&&isFlow(r)?'along the way':x.atSession?'after session '+x.atSession+' · day '+dayOf(x.atSession,dpw)+' (around '+planDate(dayOf(x.atSession,dpw),base)+')':'not in this plan',x.boostHourly>0?'+'+money(x.boostHourly)+' per hour'+(x.price>0?' · paid back after '+hours(x.price/x.boostHourly)+' of play':''):'nothing extra'])],'Each purchase is paid for when the money allows, without touching the money set aside',true)+'</section>';
  if(!reached){const alt=B.planAlternatives(s,r),curId=r.variant==='auto'?'all':r.variant,ok=alt.valid?alt.plans.filter(x=>x.valid).sort((a,b)=>(a.id===curId?-1:b.id===curId?1:0)):[];if(ok.length>1)html+='<section><h3>If things don’t go as planned</h3><ol class="b-sheet-alts">'+ok.slice(0,4).map((x,i)=>'<li><b>Plan '+String.fromCharCode(65+i)+' · '+esc(x.label)+'</b> : '+(isFlow(r)?hours((x.totalMinutes||0)/60)+' of play':plural(x.totalSessions,'session')+', '+plural(x.days,'day'))+', '+money(x.finalCash)+' at the end. '+esc(programSummary(alt.results[x.id]))+'</li>').join('')+'</ol></section>';}
  if(p.log.length)html+='<section><h3>What I actually did</h3>'+table([['Date','Total played','Planned (session)','Actual (session)','I had','Note'],...p.log.slice().reverse().map(e=>{const d=new Date(e.at);return [Number.isFinite(d.getTime())?d.toLocaleDateString('en-US'):'—',hours(e.minutes/60),e.plannedGain===null?'—':'+'+money(e.plannedGain),e.gain===null?'—':'+'+money(e.gain),money(e.capital),e.note||'—'];})],'My updates',true)+'</section>';
  html+='<div class="b-sheet-foot"><p>These are your numbers, not the game’s: no GTA VI price, earnings or mechanic is promised. Recalculate at leonidakit.com/en/calculateurs.html?tool=plan.</p></div></article>';return html;}
 function shortSummary(s){const r=B.evaluate('plan',s);const name=goalName(s);if(!r.valid)return 'Goal: '+name+' · plan incomplete ('+r.reason+')';return 'Goal: '+name+' · '+(r.totalSessions===0||(r.continuous&&r.totalMinutes===0)?'already possible':r.continuous?timeText(r):plural(r.totalSessions,'session')+' of '+sessionLabel(s)+' · '+plural(r.days,'day'))+' · '+(s.plan.source==='missions'?plural(s.plan.missions.length,'mission'):money(s.plan.situation.hourly)+'/h')+(r.purchases.some(x=>x.atSession)?' · '+plural(r.purchases.filter(x=>x.atSession).length,'purchase')+' before the goal':'');}
 function exportText(s,r){const p=s.plan,g=p.goal,si=p.situation;const lines=['MY BUSINESS PLAN — Leonidakit ('+new Date().toLocaleDateString('en-US')+')','Goal: '+goalName(s),'Start: '+money(si.capital)+' on hand, '+money(si.reserve)+' set aside, sessions of '+sessionLabel(s)+', '+(si.daysPerWeek??7)+' days/week'+(p.source==='hourly'?', '+money(si.hourly)+' per hour':', '+p.missions.length+' mission'+(E.plural(p.missions.length)?'s':'')),''];
  if(!r.valid){lines.push('Plan can’t be calculated: '+r.reason);return lines.join('\n');}
  lines.push(r.totalSessions===0||(r.continuous&&r.totalMinutes===0)?'The goal is already possible.':r.continuous?'Path: '+timeText(r)+', no calendar. At the end: '+money(r.finalCash)+'.'+lowText(r):r.totalSessions+' sessions, '+r.days+' days (around '+planDate(r.days)+'). At the end: '+money(r.finalCash)+'.','','SCHEDULE, IN ORDER');
  if(r.continuous)(r.route||[]).slice(0,80).forEach((x,i)=>lines.push((i+1)+'. '+hours(x.start/60)+': '+(x.type==='acquire'?'buy “'+x.name+' » (−'+money(x.spend)+')':x.type==='unlock'?'“'+x.name+'”, once only':'“'+x.name+'” ×'+x.runs+' (+'+money(x.receive-x.spend)+' net)')+' — you have '+money(x.cashAfter)));
  else r.phases.forEach((ph,i)=>lines.push((i+1)+'. '+(ph.count===1?'Session '+ph.from:'Sessions '+ph.from+' to '+ph.to)+': '+(ph.steps.length?ph.steps.map(st=>st.name+' ×'+st.runs).join(', '):'your earnings per hour')+' — +'+money(ph.gain)+' per session, from '+money(ph.cashBefore)+' to '+money(ph.cashAfter)+(ph.purchasesAfter.length?' — then buy '+ph.purchasesAfter.join(', '):'')));
  if(r.totalSessions>0||(r.continuous&&r.totalMinutes>0))lines.push((r.continuous?'★ After '+timeText(r):(r.phases.length+1)+'. After session '+r.totalSessions)+': '+(g.kind==='purchase'?'buy '+(g.name||'your goal'):g.kind==='unlock'?'you unlock '+(g.name||'your goal'):'you have '+money(g.target))+'.');
  if(p.log.length){lines.push('','TRACKING');p.log.forEach(e=>lines.push(new Date(e.at).toLocaleDateString('en-US')+' · played '+hours(e.minutes/60)+' · planned '+(e.plannedGain===null?'—':'+'+money(e.plannedGain))+' · actual '+(e.gain===null?'—':'+'+money(e.gain))+' · I had '+money(e.capital)));}
  /* v7.54 : les hypothèses du plan sont écrites dans l’export (sens du but, groupe, dépenses par partie, simulations, priorité). */
  const MEAN={held:'the total amount you hold',available:'the amount available beyond the money set aside',cumulative:'the amount earned from now on'},PRIO={balanced:'a good balance, keeping the money set aside',fast:'as fast as possible, money set aside can be used',safe:'safety, money set aside never touched',cheap:'the cheapest over the whole path, keeping the money set aside'};
  const hyp=['ASSUMPTIONS',g.kind==='amount'?'Reach '+money(g.target)+', meaning: '+(MEAN[g.meaning]||MEAN.available)+'.':'Goal: '+(g.name||'a purchase')+(g.price!==null&&g.price!==undefined?' to '+money(g.price)+' (your price)':''),'Priority: '+(PRIO[p.priority]||PRIO.balanced)+'.','We play with '+(si.players??1)+' player'+(E.plural(si.players??1)?'s':'')+'.',(si.upkeepPerSession||0)>0?'Expenses per session: '+money(si.upkeepPerSession)+'.':'No expenses per session entered.',(r.input&&r.input.ammoPerAttempt)?'Simulated ammo: '+money(r.input.ammoPerAttempt)+' per attempt (simulation, not game data).':'No simulated mechanics.'];
  p.prerequisites.filter(a=>!a.owned&&(a.usagePerSession||0)>0).forEach(a=>hyp.push('“'+a.name+'” costs '+money(a.usagePerSession)+' every session (your number).'));
  if(r.input&&r.input.excludedMissions&&r.input.excludedMissions.length)hyp.push('Excluded (need more players): '+r.input.excludedMissions.map(m=>'“'+m.name+'”').join(', ')+'.');
  if(r.note)hyp.push(r.note);
  lines.push('',...hyp,'','These are your numbers, not the game’s. Recalculated at leonidakit.com/en/calculateurs.html?tool=plan');return lines.join('\n');}
 return {markup,render,event,sheet,shortSummary,exportText,goalName,STRATEGY_LABEL};
}
global.LKCalcPlan={create};
})(window);
