/* ============================================================
   LEONIDAKIT — armes : source de vérité
   Chaque arme porte son niveau de certitude :
     st: 'officiel'  nom publié par Rockstar dans un support officiel
     st: 'vu'        visible dans un média officiel, nom non communiqué
   Aucune donnée issue de fuites.
   Images : visuels officiels Rockstar listés dans outils/armes-medias.json (registre outils/medias-officiels.json).
   Fiches et hub régénérés par node outils/gen-armes.cjs ; les textes sont écrits ici, pas dans les fiches.
   ============================================================ */
window.LK_ARMES = [
{"id":"girardi-es9","nom":"Girardi ES9","fr":"Jasons Pistole","cat":"pistolet","slot":"poing","st":"officiel","src":"Vorbestellungsmaterial der Ultimate Edition","insp":"Beretta 92FS","mun":"Pistolenmunition","portee":"Kurz bis mittel","ctx":"Jasons persönliche Pistole, von Rockstar in der Präsentation der Ultimate Edition benannt, die eine gravierte Version davon enthält. Sie ist die am häufigsten zu sehende Handfeuerwaffe im offiziellen Material.","perso":"jason","ue":true},
{"id":"klose-k17","nom":"Klose K17","fr":"Lucias Pistole","cat":"pistolet","slot":"poing","st":"officiel","src":"Vorbestellungsmaterial der Ultimate Edition","insp":"Glock 17 / SIG P320","mun":"Pistolenmunition","portee":"Kurz bis mittel","ctx":"Lucias persönliche Pistole, von Rockstar benannt, mit einer mit Rosen gravierten Version in der Ultimate Edition. Moderne Pistole mit Polymergriffstück und Zubehörschiene.","perso":"lucia","ue":true},
{"id":"nipper-38","nom":"Nipper .38","fr":"Kompaktpistole","cat":"pistolet","slot":"poing","st":"officiel","src":"Name auf der Waffe eingraviert, offizielles Cover","insp":"Bersa Thunder 380","mun":"Pistolenmunition","portee":"Kurz","ctx":"Die kleine Pistole, die Lucia auf dem offiziellen Cover hält. Ihr Name ist auf dem Schlitten lesbar: Sie ist eine der wenigen Waffen, deren Name direkt von einem Bild von Rockstar stammt.","perso":"lucia"},
{"id":"hawk-little-morgan","nom":"Hawk & Little Morgan","fr":"Gravierte Revolver","cat":"pistolet","slot":"poing","st":"officiel","src":"Vorbestellungsmaterial der Ultimate Edition","insp":"Smith & Wesson 629","mun":"Pistolenmunition","portee":"Mittel","ctx":"Ein Paar gravierter Revolver, einer für Jason, einer für Lucia, laut Rockstar inspiriert vom Vercetti-Anwesen in Vice City. Griffschalen mit Palmen, Namensgravuren und ein Hochleistungszielfernrohr.","ue":true},
{"id":"pistolet-custom","nom":"Custom-Pistole","fr":null,"cat":"pistolet","slot":"poing","st":"vu","src":"Zweiter Trailer","insp":"Colt 1911","mun":"Pistolenmunition","portee":"Kurz bis mittel","ctx":"Pistole mit individueller Optik, zu sehen in einer Innenszene. Die sichtbaren Oberflächen lassen vermuten, dass die Waffenanpassung zurückkehrt."},
{"id":"pistolet-auto","nom":"Pistole mit Feuerwahlhebel","fr":null,"cat":"pistolet","slot":"poing","st":"vu","src":"Extended Look vom 27. August 2026","insp":"Glock mit Switch","mun":"Pistolenmunition","portee":"Kurz","ctx":"Pistole mit einem Feuerwahlschalter hinten am Schlitten, ein Detail, das in den Gameplay-Szenen zu sehen ist. Er würde eine halbautomatische Pistole in eine Waffe mit Feuerstößen verwandeln."},
{"id":"mustang-357","nom":"Mustang .357","fr":"Biker-Revolver","cat":"pistolet","slot":"poing","st":"officiel","src":"Name auf der Waffe eingraviert, offizieller Screenshot von Ambrosia","insp":"Colt Python","mun":"Pistolenmunition","portee":"Mittel","ctx":"Der große Revolver, den eine Bikerin auf dem dritten Screenshot von Ambrosia schwenkt, während sie am Hals eines Gangmitglieds mit Enforcer-Aufnäher hängt. Der Name Mustang .357 ist auf der Waffe eingraviert: Sie ist die fünfte Waffe, deren Name direkt von einem Bild von Rockstar stammt. Belüfteter Lauf und große Trommel eines Colt Python, des Kino-Magnums schlechthin, hier in den Händen der Biker aus dem Hinterland."},
{"id":"fusil-double","nom":"Doppelläufige Schrotflinte","fr":null,"cat":"pompe","slot":"longue","st":"vu","src":"Zweiter Trailer","insp":"Doppelläufige Querflinte","mun":"Schrotpatronen","portee":"Sehr kurz","ctx":"Flinte mit zwei nebeneinanderliegenden Läufen, im offiziellen Material mit ländlichen Gegenden und Sümpfen verbunden. Der Bärtige im Vordergrund des sechsten Screenshots von Grassrivers trägt eine auf der Schulter, mit gravierten Beschlägen und Holzschaft, vor dem aufgehängten Alligator in seiner Werkstatt."},
{"id":"fusil-pompe","nom":"Pumpgun","fr":null,"cat":"pompe","slot":"longue","st":"vu","src":"Erster Trailer","insp":"Mossberg 590","mun":"Schrotpatronen","portee":"Sehr kurz","ctx":"Klassische Pumpgun, in Schießereiszenen zu sehen. Eine Waffe mit kurzer Reichweite, typisch für die Reihe."},
{"id":"micro-smg","nom":"MP mit Tropenmuster","fr":null,"cat":"pm","slot":"poing","st":"vu","src":"Bild der Ultimate Edition","insp":"Mini Uzi","mun":"Pistolenmunition","portee":"Kurz","ctx":"Kompakte Maschinenpistole mit tropischem Muster, im Bild der Ultimate Edition gezeigt, ohne dass Rockstar ihren Namen veröffentlicht hat. Einhändig nutzbar, in der Tradition der Drive-by-Waffen.","ue":true},
{"id":"smg-compact","nom":"Kompakte MP","fr":null,"cat":"pm","slot":"poing","st":"vu","src":"Extended Look vom 27. August 2026","insp":"Škorpion","mun":"Pistolenmunition","portee":"Kurz","ctx":"Sehr kurze automatische Waffe, in einer Nahkampf-Actionszene zu sehen."},
{"id":"smg","nom":"Maschinenpistole","fr":null,"cat":"pm","slot":"longue","st":"vu","src":"Zweiter Trailer","insp":"H&K MP5","mun":"Pistolenmunition","portee":"Kurz bis mittel","ctx":"Maschinenpistole, die Jason und Lucia beim Raubüberfall im zweiten Trailer beidhändig halten. Jasons Version hat ein Rotpunktvisier."},
{"id":"pm-tactique","nom":"MP mit Klappschaft","fr":null,"cat":"pm","slot":"longue","st":"vu","src":"Bild der Ultimate Edition","insp":null,"mun":"Pistolenmunition","portee":"Kurz bis mittel","ctx":"Liegt auf der Sitzbank eines Autos zwischen Geldbündeln, mit einer passenden Pistole, im Bild Weapon Pattern des Vintage Vice City Pack. Eingeklappter Schaft, gerades Magazin vor dem Griff, türkisfarbene Oberfläche mit Palmen: eine moderne, kompakte Maschinenpistole, nicht zu verwechseln mit der kleinen MP mit Tropenmuster, die Jason auf den Outfit-Bildern hält. Ihr Name wurde nicht genannt.","ue":true,"fam":"Moderne Maschinenpistole mit Klappschaft"},
{"id":"carabine","nom":"Karabiner","fr":null,"cat":"assaut","slot":"longue","st":"vu","src":"Zweiter Trailer","insp":"AR-15 / M4","mun":"Gewehrmunition","portee":"Mittel bis weit","ctx":"Moderner Karabiner mit Teleskopschaft, in mehreren Actionszenen zu sehen."},
{"id":"fusil-assaut","nom":"Sturmgewehr","fr":null,"cat":"assaut","slot":"longue","st":"vu","src":"Erster Trailer","insp":"AK","mun":"Gewehrmunition","portee":"Mittel bis weit","ctx":"Sturmgewehr mit dem typischen gebogenen Magazin, in den Händen von Gegenspielern zu sehen."},
{"id":"fusil-precision","nom":"Repetiergewehr","fr":null,"cat":"precision","slot":"longue","st":"vu","src":"Extended Look vom 27. August 2026","insp":"Remington 700","mun":"Gewehrmunition","portee":"Lang","ctx":"Repetierbüchse mit Zielfernrohr, in einer Szene mit Schüssen auf Distanz zu sehen."},
{"id":"fusil-semi-auto","nom":"Halbautomatisches Gewehr","fr":null,"cat":"precision","slot":"longue","st":"vu","src":"Offizielle Screenshots","insp":"Springfield M1A","mun":"Gewehrmunition","portee":"Lang","ctx":"Das lange Gewehr mit Holzschaft und Zielfernrohr, das einer der drei Männer hält, die auf dem ersten Screenshot von Grassrivers vor ihrem Propellerboot posieren. Das lange Gehäuse und der klassische Schaft erinnern an das M1A, die zivile Version des M14: eine Waffe für die Jagd und weite Schüsse, rustikaler als die Repetierbüchse und in den Sümpfen genau am richtigen Platz."},
{"id":"mitrailleuse","nom":"Kampf-MG","fr":null,"cat":"mitrailleuse","slot":"longue","st":"vu","src":"Extended Look vom 27. August 2026","insp":"M249 SAW","mun":"Schwere Munition","portee":"Mittel","ctx":"Gurtgespeiste Unterstützungswaffe, die schwerste, die bisher zu sehen war."},
{"id":"batte","nom":"Baseballschläger","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Erster Trailer","insp":null,"mun":null,"portee":"Nahkampf","ctx":"Baseballschläger, eine wiederkehrende Nahkampfwaffe der Reihe. Die Nahkampfanimationen wurden per Motion Capture neu aufgenommen.","fam":"Aluminium-Baseballschläger"},
{"id":"couteau-cran","nom":"Springmesser","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Bild der Ultimate Edition","insp":null,"mun":null,"portee":"Nahkampf","ctx":"Messer mit einziehbarer Klinge, im Bild der Ultimate Edition neben den gravierten Revolvern zu sehen.","ue":true,"fam":"Klappbares Springmesser"},
{"id":"club-golf","nom":"Golfschläger","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Zweiter Trailer","insp":null,"mun":null,"portee":"Nahkampf","ctx":"Golfschläger als Nahkampfwaffe, in der Tradition der zweckentfremdeten Alltagsgegenstände.","fam":"Golfeisen"},
{"id":"marteau","nom":"Hammer","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Extended Look vom 27. August 2026","insp":null,"mun":null,"portee":"Nahkampf","ctx":"Bauhammer, als improvisierte Waffe zu sehen.","fam":"Zimmermannshammer"},
{"id":"queue-billard","nom":"Billardqueue","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Extended Look vom 27. August 2026","insp":null,"mun":null,"portee":"Nahkampf","ctx":"Billardqueue, eine Nahkampfwaffe, die zu den Freizeitorten von Leonida passt.","fam":"Poolbillard-Queue"},
{"id":"molotov","nom":"Molotowcocktail","fr":null,"cat":"projectile","slot":"poing","st":"vu","src":"Zweiter Trailer","insp":null,"mun":null,"portee":"Jet","ctx":"Molotowcocktail, ein klassisches Brandwurfgeschoss der Reihe.","fam":"Improvisierte Brandflasche"},
{"id":"fumigene","nom":"Rauchgranate","fr":null,"cat":"projectile","slot":"poing","st":"vu","src":"Extended Look vom 27. August 2026","insp":null,"mun":null,"portee":"Jet","ctx":"Rauchgranate, ein nicht tödliches Wurfgeschoss, um eine Bewegung zu verschleiern.","fam":"Handrauchgranate"},
{"id":"harpon","nom":"Harpunengewehr","fr":null,"cat":"speciale","slot":"longue","st":"vu","src":"Extended Look vom 27. August 2026","insp":null,"mun":"Harpunenpfeile","portee":"Kurz, unter Wasser","ctx":"Harpune, eine Unterwasserwaffe. Sie ist neu in der Reihe: Sie kommt zusammen mit den erkundbaren Unterwasserbereichen.","fam":"Unterwasser-Harpune mit Gummizügen"},
{"id":"lance-grenades","nom":"Granatwerfer","fr":null,"cat":"speciale","slot":"longue","st":"vu","src":"Zweiter Trailer","insp":"Milkor MGL","mun":"Granaten","portee":"Mittel","ctx":"Lucia hält ihn während der Verfolgungsjagd mit der Polizei im zweiten Trailer, genau als hinter ihr ein Fahrzeug explodiert. Die große Trommel unter dem Lauf lässt keinen Zweifel: ein Trommel-Granatwerfer im Stil des Milkor MGL, die Rückkehr der spektakulärsten schweren Waffe der Reihe."}
];
window.LK_ARMES_CATS = {
  pistolet:'Pistolen', pompe:'Schrotflinten', pm:'Maschinenpistolen', assaut:"Sturmgewehre",
  precision:'Präzisionsgewehre', mitrailleuse:'Maschinengewehre', melee:'Nahkampf', projectile:'Wurfwaffen', speciale:'Spezialwaffen'
};
