/* v7.61 : pluriel selon la langue de la page : français n > 1 (« 0 coché », « 1,5 million ») ; anglais, espagnol n ≠ 1 (« 0 marcados ») */
var lkPluriel=function(n){return ((typeof document!=='undefined'&&document.documentElement&&document.documentElement.lang)||'fr').slice(0,2)==='fr'?n>1:n!==1;};
/* Mon business plan (v7.34) : un programme mission par mission, avec ses propres réponses.
   Le plan ne prend rien en silence dans les huit calculs : il pose ses questions (but, situation, missions, achats d'avant).
   Tout chiffre vient du moteur (LKCalcEngine.missionPlan) via le scénario partagé (LKCalcScenario) ; ce fichier ne fait
   que présenter : réponse, prochaine partie, programme dans l'ordre, plans de secours, suivi du réel avec recalcul complet,
   point de départ, stratégie, échéance, détails (partie par partie, et si, courbe, calendrier, formule), fiche enregistrée. */
(function(global){'use strict';
const B=global.LKCalcScenario;
function create(env){
 const {esc,money,hours,field,stats,warning,btn,select,table,state,sourceActivities,visual,api,problem,itemFor,selectedCard,combobox,step,refresh,fold,explainBlock,analysisOf}=env;
 const E=global.LKCalcEngine,nf=new Intl.NumberFormat('de-DE',{maximumFractionDigits:2}),$=id=>document.getElementById(id);
 const STRATEGY_LABEL=B.STRATEGY_LABEL;
 const ORDINALS=['Zuerst','Als Zweites','Als Drittes','Als Viertes','Als Fünftes','Als Sechstes','Als Siebtes','Als Achtes','Als Neuntes','Als Zehntes'];
 const KIND_LABEL={purchase:'Etwas kaufen',amount:'Eine Geldsumme haben',unlock:'Etwas mit Erfahrung freischalten (Rang, XP, Ruf …)'};
 function planDate(days,base){const d=base?new Date(base):new Date();if(!Number.isFinite(d.getTime()))return '—';d.setDate(d.getDate()+days);return d.toLocaleDateString('de-DE',{day:'numeric',month:'long'});}
 const dayOf=(n,dpw)=>n<=0?0:Math.floor((n-1)/dpw)*7+((n-1)%dpw)+1;
 const pct=v=>v===null||!Number.isFinite(v)?'—':nf.format(Math.round(v*10)/10)+' %';
 const plural=(n,w,ws)=>n+(E.plural(n)?ws:w); /* v7.62 : singulier et pluriel écrits en entier, espace devant (« 3 jours », allemand « 3 Tage ») */
 const units=(s,n)=>(Number.isFinite(n)?nf.format(Math.round(n*100)/100):'—')+' '+esc(s.plan.goal.unitLabel||'points');
 const sessionLabel=s=>s.plan.situation.dailyMinutes?hours(s.plan.situation.dailyMinutes/60):'freie Dauer';
 function goalName(s){const g=s.plan.goal;return g.kind==='amount'?'Kontostand von '+money(g.target):g.kind==='unlock'?'Freischaltung von '+(g.name||'mein Ziel'):(g.name||'mein Kauf');}
 function goalShort(s){const g=s.plan.goal;return g.kind==='amount'?money(g.target):(g.name||(g.kind==='unlock'?'mein Ziel':'mein Kauf'));}
 function parse(v){const P=E.parseLocalizedNumber;if(v===undefined||v===null)return null;if(String(v).trim()==='')return null;const r=P(String(v));return r.valid?r.value:null;}
 /* ---------- Formulaire : cinq questions, toutes propres au plan ---------- */
 function markup(){const s=state(),p=s.plan,g=p.goal,si=p.situation;
  const goalBlock=g.kind==='purchase'
   ?combobox('plan-search','Ich will kaufen (auf der Seite suchen)','plan')+btn('Eigenen Kauf eintragen','data-b-plan-free="1"')+'<div id="plan-selection">'+(g.itemId?selectedCard({itemId:g.itemId,name:g.name}):'')+'<div class="calc-fields">'+field('plan.goal.name','Name meines Kaufs',g.name,{type:'text',id:'plan-name'})+field('plan.goal.price',g.referencePrice!==null?'Das kostet ($)':'Der Preis, den ich mir vorstelle ($)',g.price,{id:'plan-price',hint:g.referencePrice!==null?'Preis laut Seite: '+money(g.referencePrice)+'. Du kannst einen anderen Preis eingeben.':'Der Preis im Spiel ist noch nicht bekannt: Gib den ein, den du dir vorstellst.'})+field('plan.goal.boostHourly','Einmal gekauft, bringt es mir zusätzlich ($ pro Stunde)',g.boostHourly,{id:'plan-boost',hint:'0, wenn es ein Spaßkauf ist. Zähl nur, was er zusätzlich einbringt.'})+'</div>'+(g.referencePrice!==null?btn('Preis der Seite wiederherstellen','data-b-plan-price-reset="1"'):'')+'</div>'
   :g.kind==='amount'
   ?'<div class="calc-fields">'+field('plan.goal.target','Ich will haben ($)',g.target,{id:'plan-target',hint:'Wähle direkt darunter, was „haben“ für dich bedeutet.'})+select('plan.goal.meaning','„Haben“ heißt für mich',[['available','Verfügbares Geld, zusätzlich zu dem, was ich zurücklege'],['held','Geld insgesamt, Rücklage inklusive'],['cumulative','Ab jetzt verdientes Geld, ohne das, was ich schon habe']],g.meaning||'available')+'</div>'
   :'<div class="calc-fields">'+field('plan.goal.name','Was ich freischalten will',g.name,{type:'text',id:'plan-name',hint:'Ein Auto, eine Waffe, ein Ort … alles, was man mit Erfahrung bekommt.'})+field('plan.goal.unitLabel','Man bekommt es in',g.unitLabel,{type:'text',id:'plan-units-label',hint:'XP-Punkte, Level, Ruf … das Wort, das du willst.'})+field('plan.goal.targetUnits','Das musst du erreichen ('+esc(g.unitLabel||'points')+')',g.targetUnits,{id:'plan-units-target'})+field('plan.goal.currentUnits','Ich habe schon ('+esc(g.unitLabel||'points')+')',g.currentUnits,{id:'plan-units-current'})+field('plan.goal.alsoPrice','Und es kostet auch, einmal freigeschaltet ($)',g.alsoPrice,{id:'plan-also-price',hint:'Lass 0 stehen, wenn es nach dem Freischalten kostenlos ist.'})+'</div><p class="calc-note">Das Spiel hat noch nicht verraten, wie man Erfahrung bekommt. Gib ein, was du weißt oder was du dir vorstellst: Der Plan rechnet mit deinen Zahlen.</p>';
  const missionSources=[...s.activities.map(a=>['mine:'+a.id,a.name+' · meine Aktivitäten']),...sourceActivities.map(a=>['site:'+a.id,a.name+' · von der Seite'])];
  const missionsBlock=p.source==='missions'
   ?'<div id="plan-missions">'+(p.missions.length?p.missions.map((m,i)=>missionCard(s,m,i)).join(''):'<p class="calc-empty">Noch keine Missionen. Füge die hinzu, die du machen kannst: Der Plan sagt dir, welche du nacheinander spielst und in welcher Reihenfolge.</p>')+'</div><div class="b-plan-add">'+btn('Mission hinzufügen','data-b-plan-m-add="1"',true)+(missionSources.length?'<label class="calc-label" for="plan-m-source">Oder eine schon eingetragene Mission übernehmen</label><div class="b-plan-add-row"><select id="plan-m-source">'+missionSources.map(([k,l])=>'<option value="'+esc(k)+'">'+esc(l)+'</option>').join('')+'</select>'+btn('Diese Mission hinzufügen','data-b-plan-m-import="1"')+'</div>':'')+'</div><p class="calc-note">Das sind Kopien: Wenn du hier eine Mission änderst, ändert sich nichts in „Meine Aktivitäten“, und umgekehrt.</p>'
   :'<div class="calc-fields">'+field('plan.situation.hourly','Ich verdiene ungefähr ($ pro Spielstunde)',si.hourly,{id:'plan-hourly',hint:'Was dir nach Abzug deiner Kosten bleibt. Deine eigene Zahl.'})+(g.kind==='unlock'?field('plan.situation.unitsHourly','Ich verdiene ungefähr ('+esc(g.unitLabel||'points')+' pro Stunde)',si.unitsHourly,{id:'plan-units-hourly'}):'')+'</div>';
  const prereqBlock='<div id="plan-prereqs">'+(p.prerequisites.length?p.prerequisites.map((a,i)=>prereqCard(s,a,i)).join(''):'<p class="calc-empty">Kein Kauf vor deinem Ziel. Füge hinzu, was du zuerst kaufen musst (Ausrüstung, Fahrzeug, Immobilie …), falls nötig.</p>')+'</div>'+combobox('plan-prereq-search','Kauf vor dem Ziel hinzufügen (auf der Seite suchen)','plan-prereq')+btn('Eigenen Kauf hinzufügen','data-b-plan-p-add="1"')+'<div class="calc-fields">'+select('plan.strategy','In welcher Reihenfolge kaufen?',Object.entries(STRATEGY_LABEL),p.strategy)+field('plan.situation.upkeepPerSession','Meine Ausgaben pro Session ($): Verbrauchsgüter, Munition …',si.upkeepPerSession,{id:'plan-upkeep',hint:'Wird von deinen Einnahmen abgezogen. Trag 0 ein, wenn du es nicht weißt.'})+'</div>';
  const form='<div class="b-plan-import"><p class="calc-note">Der Businessplan hat eigene Felder: Nichts wird automatisch aus den acht Berechnungen übernommen. Wenn du mit deinen Zahlen aus „Meine Berechnungen“ starten willst, klick hier und ändere dann, was du willst.</p>'+btn('Meine Zahlen aus „Meine Berechnungen“ übernehmen','data-b-plan-import-calcs="1"')+'</div><div class="calc-fields calc-steps">'
   +step(1,'Was ist dein Ziel?',select('plan.goal.kind','Mein Ziel',Object.entries(KIND_LABEL),g.kind)+goalBlock,'Das Ziel bestimmt alles andere: Ein Kauf hat einen Preis, eine Summe verdienst du nach und nach, eine Freischaltung bekommst du mit Punkten.')
   +step(2,'Wo stehst du?','<div class="calc-fields">'+field('plan.situation.capital','Ich habe schon ($)',si.capital,{id:'plan-capital'})+field('plan.situation.reserve','Geld, das ich zurücklege ($)',si.reserve,{id:'plan-reserve'})+field('plan.situation.dailyMinutes','Eine Session dauert (Minuten)',si.dailyMinutes,{id:'plan-daily',min:1,max:1440,hint:'Der Ablauf wird Session für Session erstellt. Lass das Feld leer, wenn du nicht in Sessions rechnest: Dann bekommst du einen Weg in Spielzeit, ohne Kalender.'})+field('plan.situation.daysPerWeek','Wie viele Tage pro Woche spiele ich?',si.daysPerWeek,{id:'plan-days',min:1,max:7,integer:true})+field('plan.situation.players','Wir sind (Spieler)',si.players??1,{id:'plan-players',min:1,max:100,integer:true,hint:'Eine Mission, die mehr Spieler braucht, als deine Gruppe hat, fliegt aus dem Plan – und das wird angezeigt.'})+'</div>','Mit dem, was du hast, und der Dauer deiner Sessions rechnet der Plan in Sessions, dann in Tagen.')
   +step(3,'Wie verdienst du dein Geld?',select('plan.source','Ich verdiene mein Geld',[['missions','Mit meinen Missionen: Der Plan sagt mir, welche ich mache und in welcher Reihenfolge'],['hourly','Nach und nach: Ich verdiene ungefähr einen festen Betrag pro Stunde']],p.source)+missionsBlock,'Mit deinen Missionen wählt der Plan in jeder Session die aus, die in deiner Zeit am meisten einbringen. Das ist der schnellste Weg, den er findet.')
   +step(4,'Vor deinem Ziel',prereqBlock,'Ein Kauf, der eine Mission freischaltet oder Geld bringt, beschleunigt den Rest; der Plan setzt ihn an die richtige Stelle, sobald du ihn bezahlen kannst.')
   +step(5,'Was dir wichtig ist','<div class="calc-fields">'+select('plan.priority','Ich bevorzuge',[['balanced','Ein gutes Gleichgewicht: Meine Rücklage bleibt unangetastet'],['fast','So schnell es geht: Ich darf meine Rücklage antasten'],['safe','Sicherheit: Ich taste meine Rücklage nie an'],['cheap','Am günstigsten über den ganzen Weg: Meine Rücklage bleibt unangetastet']],p.priority)+field('plan.deadlineDays','Ich will es in so vielen Tagen schaffen (wenn du willst)',p.deadlineDays,{id:'plan-deadline',min:1,max:36500,integer:true,hint:'Lass das Feld leer, wenn du kein Datum hast. Wir sagen dir, ob es in deinem Tempo machbar ist.'})+'<div class="b-expert">'+field('plan.maxRepeat','Dieselbe Mission höchstens so oft hintereinander',p.maxRepeat,{id:'plan-max-repeat',min:1,max:256,integer:true})+'</div></div>','Was du bevorzugst, bestimmt die Reihenfolge der Käufe und ob deine Rücklage genutzt werden darf.')
   +'</div><p class="calc-note">Der Plan rechnet sich bei jeder geänderten Zahl von selbst neu. Speichere ihn, um ihn mit seinem vollständigen Planblatt wiederzufinden, druck ihn aus oder teile den Link.</p>';
  return '<section class="calc-panel" id="panel-plan" role="tabpanel" aria-labelledby="tab-plan" hidden><div class="calc-grid"><div class="calc-card"><p class="calc-kicker">MEIN BUSINESSPLAN</p><h3>Sag mir dein Ziel, ich erstelle dir den Ablauf.</h3><p class="calc-card-desc">Beantworte die fünf Fragen: Der Plan sagt dir, was du zuerst, als Zweites, als Drittes machst, Session für Session, mit dem schnellsten Weg zu deinem Ziel – und was du tust, wenn es nicht wie geplant läuft.</p>'+form+'</div><div class="calc-card calc-result" id="plan-results"></div></div><div id="plan-report"></div><div class="b-stage-actions">'+btn('Meinen Plan als Text herunterladen (zum Lesen oder Verschicken)','data-b-plan-export="1"')+'</div><p class="calc-note">Um diesen Plan mit seinem Planblatt zu behalten: „☆ Plan speichern“, oben oder unten im Arbeitsbereich. Danach findest du ihn unter „Meine Berechnungen“.</p><div class="b-expert calc-card calc-subsection" id="expert-plan"></div></section>';}
 /* Revue de conformité (v7.53) : prévu, commencé et réalisé sont trois états distincts. « Commencé » se voit partout mais
    ne crédite rien (ni argent ni déblocage) ; seul « fait » (ou un relevé réel) compte dans le calcul. */
 function stateRadios(kind,i,st,labels){const name='plan-'+kind+'-state-'+i;return '<fieldset class="b-plan-state"><legend>Wo ich stehe</legend>'+[['planned',labels[0]],['started',labels[1]],['done',labels[2]]].map(([v,l])=>'<label class="calc-check"><input type="radio" name="'+name+'" value="'+v+'" data-b-plan-'+kind+'-state="'+i+'" '+(st===v?'checked':'')+'> '+esc(l)+'</label>').join('')+'</fieldset>';}
 const mState=m=>m.once&&m.done?'done':m.started?'started':'planned',pState=a=>a.owned?'done':a.started?'started':'planned';
 function planStatus(s,r){const p=s.plan,once=p.missions.filter(m=>m.once),buy=p.prerequisites;const n={planned:0,started:0,done:0};once.forEach(m=>n[mState(m)]++);buy.forEach(a=>n[pState(a)]++);
  const real=p.log.length,label=real||n.started||n.done?(r&&r.valid&&(r.continuous?r.totalMinutes===0:r.totalSessions===0)&&real?'Erreicht':'Begonnen'):'Geplant';
  const steps=n.planned+n.started+n.done,detail=steps?'Schritte: '+plural(n.planned,' geplant',' geplant')+', '+plural(n.started,' begonnen',' begonnen')+(n.started?(lkPluriel(n.started)?' (noch nicht mitgezählt)':' (noch nicht mitgezählt)'):'')+', '+plural(n.done,' erledigt',' erledigt')+(real?' · '+plural(real,' Session',' Sessions')+(lkPluriel(real)?' mit echten Ergebnissen':' mit echtem Ergebnis')+' erfasst':'')+'.':real?plural(real,' Session',' Sessions')+(lkPluriel(real)?' mit echten Ergebnissen':' mit echtem Ergebnis')+' erfasst.':'Noch nichts begonnen: Das ist eine Prognose. Nach einer Session setzt der Button „Nach dem Spielen eintragen, was ich wirklich habe“ sie auf „begonnen“.';
  return '<p class="b-plan-status" data-plan-status="'+label.toLowerCase()+'"><span class="calc-tag">'+esc(label.toUpperCase())+'</span> '+esc(detail)+'</p>';}
 function missionSummary(s,m,i){const p=s.plan,r=E.activity({...m,units:m.units});return '<span>'+esc(m.name||'Mission '+(i+1))+'<i class="b-plan-mission-edit">bearbeiten</i></span><small>'+(m.once&&m.done?'erledigt · ':m.started?'begonnen · ':'')+(r.valid?money(r.net)+' pro Mission · '+money(r.hourly)+' pro Stunde, Wartezeit inklusive':'Zahlen fehlen: '+esc(r.reason||''))+(m.requires.length?' · nach '+esc(m.requires.map(id=>p.prerequisites.find(x=>x.id===id)?.name||id).join(', ')):'')+(m.owned?' · Startkauf schon bezahlt':'')+(m.once?(m.done?' · schon erledigt':' · nur einmal'):'')+((m.requiresMissions||[]).length?' · nach der Mission '+esc(m.requiresMissions.map(id=>p.missions.find(x=>x.id===id)?.name||id).join(', ')):'')+'</small>';}
 function prereqHead(s,a,i){return '<span class="calc-tag">'+(i+1)+'</span><strong>'+esc(a.name)+'</strong><small>'+(a.owned?'schon im Besitz':a.price===null?'Preis einzutragen':money(a.price))+(a.boostHourly>0?' · +'+money(a.boostHourly)+'/Std. danach':'')+(a.minutes>0?' · '+hours(a.minutes/60)+' zum Beschaffen':'')+((s.plan.locked||[]).includes(a.id)?' · unverzichtbar':'')+'</small>';}
 function syncForm(s){s.plan.missions.forEach((m,i)=>{const n=document.querySelector('[data-b-plan-m-summary="'+i+'"]');if(n){const h=missionSummary(s,m,i);if(n.innerHTML!==h)n.innerHTML=h;}});s.plan.prerequisites.forEach((a,i)=>{const n=document.querySelector('[data-b-plan-p-head="'+i+'"]');if(n){const h=prereqHead(s,a,i);if(n.innerHTML!==h)n.innerHTML=h;}});}
 function missionCard(s,m,i){const p=s.plan,g=p.goal,r=E.activity({...m,units:m.units}),pre='plan.missions.'+i+'.';
  return '<details class="b-plan-mission" '+(i===p.missions.length-1&&p.missions.length<=2?'open':'')+'><summary data-b-plan-m-summary="'+i+'">'+missionSummary(s,m,i)+'</summary><div class="calc-fields">'+field(pre+'name','Name der Mission',m.name,{type:'text',id:'plan-m-'+i+'-name'})+field(pre+'reward','Belohnung ($)',m.reward,{id:'plan-m-'+i+'-reward'})+field(pre+'duration','Dauer (min)',m.duration,{id:'plan-m-'+i+'-duration',min:1,max:1e6})+field(pre+'cost','Kosten jedes Mal ($)',m.cost,{id:'plan-m-'+i+'-cost'})+field(pre+'prep','Vorbereitung (min)',m.prep,{id:'plan-m-'+i+'-prep',max:1e6})+field(pre+'cooldown','Wartezeit vor dem nächsten Mal (min)',m.cooldown,{id:'plan-m-'+i+'-cooldown',max:1e6})+field(pre+'share','Mein Anteil (%)',m.share,{id:'plan-m-'+i+'-share',max:100})+field(pre+'players','Spielbar mit (Spieler)',m.players??1,{id:'plan-m-'+i+'-players',min:1,max:100,integer:true})+field(pre+'investment','Einmal vor dem Start zu kaufen ($)',m.investment,{id:'plan-m-'+i+'-investment'})+(g.kind==='unlock'?field(pre+'units',esc(g.unitLabel||'Punkte')+' pro Mission verdient',m.units,{id:'plan-m-'+i+'-units'}):'')+'</div><label class="calc-check"><input type="checkbox" data-b-plan-m-owned="'+i+'" '+(m.owned?'checked':'')+'> Ich habe schon bezahlt, was für den Start nötig ist</label><label class="calc-check"><input type="checkbox" data-b-plan-m-once="'+i+'" '+(m.once?'checked':'')+'> Mission nur einmal zu machen (sie schaltet den Rest frei)</label>'+(m.once?stateRadios('m',i,mState(m),['Geplant','Begonnen (noch nicht gezählt)','Schon erledigt']):'')+(p.prerequisites.length?'<fieldset class="b-plan-requires"><legend>Vorher musst du gekauft haben:</legend>'+p.prerequisites.map(a=>'<label class="calc-check"><input type="checkbox" data-b-plan-m-req="'+i+'|'+esc(a.id)+'" '+(m.requires.includes(a.id)?'checked':'')+'> '+esc(a.name)+'</label>').join('')+'</fieldset>':'')+(p.missions.length>1?'<fieldset class="b-plan-requires"><legend>Vorher musst du diese Mission erledigt haben:</legend>'+p.missions.filter(o=>o.id!==m.id).map(o=>'<label class="calc-check"><input type="checkbox" data-b-plan-m-reqm="'+i+'|'+esc(o.id)+'" '+((m.requiresMissions||[]).includes(o.id)?'checked':'')+'> '+esc(o.name)+(o.once?' (nur einmal)':'')+'</label>').join('')+'</fieldset>':'')+'<div class="b-plan-card-actions">'+btn('Diese Mission entfernen','data-b-plan-m-remove="'+i+'"')+'</div></details>';}
 function prereqCard(s,a,i){const pre='plan.prerequisites.'+i+'.',item=itemFor({itemId:a.itemId});
  return '<article class="b-plan-prereq" data-b-plan-prereq="'+esc(a.id)+'"><div class="b-plan-prereq-head" data-b-plan-p-head="'+i+'">'+prereqHead(s,a,i)+'</div><div class="calc-fields">'+field(pre+'name','Name',a.name,{type:'text',id:'plan-p-'+i+'-name'})+field(pre+'price',a.referencePrice!==null?'Preis ($)':'Preis, den du dir vorstellst ($)',a.price,{id:'plan-p-'+i+'-price',hint:a.referencePrice!==null?'Preis laut Seite: '+money(a.referencePrice)+'.':(item?'':'')})+field(pre+'boostHourly','Es bringt mir zusätzlich ($ pro Stunde)',a.boostHourly,{id:'plan-p-'+i+'-boost',hint:'Nur, was dieser Kauf zusätzlich einbringt. Sonst 0.'})+field(pre+'minutes','Zeit bis zum Erhalt (min)',a.minutes,{id:'plan-p-'+i+'-minutes',max:1e6,hint:'Anfahrt, Kaufmission … Lass das Feld leer, wenn es sofort geht.'})+field(pre+'usagePerSession','Was es jede Session kostet ($)',a.usagePerSession,{id:'plan-p-'+i+'-usage',hint:'Sprit, Wartung … deine Zahl. Leer = nichts gezählt (keine bestätigten Kosten in GTA VI).'})+'</div>'+stateRadios('p',i,pState(a),['Geplant','Begonnen (noch nicht meins)','Schon meins'])+'<label class="calc-check"><input type="checkbox" data-b-plan-p-lock="'+esc(a.id)+'" '+((s.plan.locked||[]).includes(a.id)?'checked':'')+'> Unverzichtbar: Kein Vorgehen nimmt ihn aus dem Plan</label>'+prereqRequires(s,a,i)+'<div class="b-plan-card-actions">'+btn('↑','data-b-plan-p-up="'+i+'" aria-label="Nach oben: '+esc(a.name)+'" '+(i===0?'disabled':''))+btn('↓','data-b-plan-p-down="'+i+'" aria-label="Nach unten: '+esc(a.name)+'" '+(i===s.plan.prerequisites.length-1?'disabled':''))+btn('Entfernen','data-b-plan-p-remove="'+i+'"')+'</div></article>';}
 /* ---------- Phases : « en premier, en deuxième… », le cœur du programme ---------- */
 function stepsText(steps){return steps.map((st,i)=>(i?(i===steps.length-1?' dann ':', '):'')+'„'+esc(st.name)+'“ ×'+st.runs).join('');}
 function phaseCards(s,r,base){const p=s.plan,g=p.goal,dpw=r.input.daysPerWeek,D=sessionLabel(s),byName=n=>r.purchases.find(x=>x.name===n),cards=[];
  if(r.totalSessions===0)return '<ol class="b-timeline"><li class="b-phase is-goal"><span class="b-phase-n">✓</span><div><p class="b-phase-k">Schon jetzt</p><h4>'+esc(g.kind==='purchase'?'Kaufe '+goalShort(s):g.kind==='unlock'?'Schon freischaltbar: '+goalShort(s):'Du hast schon '+goalShort(s))+'</h4><p>'+esc(g.kind==='purchase'?'Dir bleiben dann '+money(r.finalCash-(r.input.goalPrice||0))+(r.input.reserve?', davon '+money(r.input.reserve)+' Rücklage':'')+'.':'Wähle ein größeres Ziel oder einen neuen Kauf.')+'</p></div></li></ol>';
  r.phases.forEach((ph,i)=>{const range=ph.count===1?'Session '+ph.from:'Sessions '+ph.from+' bis '+ph.to+' · '+plural(ph.count,' Session',' Sessions');
   const doText=ph.steps.length?'Mach '+stepsText(ph.steps)+(ph.count>1?' in jeder Session':'')+'.':'Spiel '+D+': Du verdienst ungefähr '+money(ph.gain)+' pro Session'+(r.input.hourly>0?' mit deiner Zahl pro Stunde':'')+'.';
   const boosters=r.purchases.filter(x=>x.boostHourly>0&&((x.atSession!==null&&x.atSession<ph.from)||(x.owned&&x.atSession===null))),passive=boosters.reduce((a,x)=>a+x.boostHourly,0)*r.input.sessionMinutes/60,extras=[];
   if(passive>0)extras.push('+'+money(passive)+' pro Session dank '+boosters.map(x=>'„'+esc(x.name)+'“').join(', '));if(r.input.hourly>0&&ph.steps.length)extras.push('+'+money(r.input.hourly*r.input.sessionMinutes/60)+' mit deinen Einnahmen pro Stunde');if(r.input.upkeepPerSession>0)extras.push('−'+money(r.input.upkeepPerSession)+' Ausgaben pro Session');
   const extra=extras.join(' · ');
   const figures=[['Pro Session','+'+money(ph.gain)+(g.kind==='unlock'&&ph.unitsGain>0?' · +'+units(s,ph.unitsGain):'')],['Dein Geld geht von',money(ph.cashBefore)+' auf '+money(ph.cashAfter)],['Wann',ph.from===ph.to?'Tag '+dayOf(ph.from,dpw)+' (etwa am '+planDate(dayOf(ph.from,dpw),base)+')':'von Tag '+dayOf(ph.from,dpw)+' bis Tag '+dayOf(ph.to,dpw)+' (etwa am '+planDate(dayOf(ph.to,dpw),base)+')']];
   const after=ph.purchasesAfter.length?'<p class="b-phase-after"><b>Nach Session '+ph.to+':</b> kaufe '+ph.purchasesAfter.map(n=>{const x=byName(n);return '„'+esc(n)+'“'+(x?' ('+money(x.price)+(x.boostHourly>0?', +'+money(x.boostHourly)+'/Std. danach':'')+')':'');}).join(', ')+'.</p>':'';
   cards.push('<li class="b-phase"><span class="b-phase-n">'+(i+1)+'</span><div><p class="b-phase-k">'+esc(ORDINALS[i]||'Schritt '+(i+1))+' · '+esc(range)+'</p><h4>'+doText+'</h4>'+(extra?'<p class="calc-note">Ebenfalls in der Summe: '+extra+'.</p>':'')+'<div class="b-tiles">'+figures.map(([l,v])=>'<span><small>'+esc(l)+'</small><b>'+v+'</b></span>').join('')+'</div>'+after+'</div></li>');});
  const N=r.totalSessions,dayN=dayOf(N,dpw);
  cards.push('<li class="b-phase is-goal"><span class="b-phase-n">★</span><div><p class="b-phase-k">Ziel erreicht · nach Session '+N+' · Tag '+dayN+' (etwa am '+planDate(dayN,base)+')</p><h4>'+esc(g.kind==='purchase'?'Kaufe '+goalShort(s)+' ('+money(r.input.goalPrice)+')':g.kind==='unlock'?'Du schaltest frei: '+goalShort(s)+(r.input.goalPrice>0?' und bezahlst es ('+money(r.input.goalPrice)+')':''):g.meaning==='held'?'Du hast '+money(g.target)+' insgesamt':g.meaning==='cumulative'?'Du hast '+money(g.target)+' seit dem Start verdient':'Du hast '+money(g.target)+' in der Tasche')+'</h4><p>'+esc((g.kind==='purchase'||(g.kind==='unlock'&&r.input.goalPrice>0)?'Dir bleiben '+money(r.finalCash-(r.input.goalPrice||0))+(r.input.reserve?', davon '+money(r.input.reserve)+' Rücklage':'')+'.':'Du hast weiterhin '+money(r.input.reserve)+' zurückgelegt.')+(g.kind==='purchase'&&g.boostHourly>0?' Danach bringt dir dieser Kauf '+money(g.boostHourly)+' mehr pro Stunde ein: wieder eingespielt nach '+hours(r.input.goalPrice/g.boostHourly)+' Spielzeit.':'')+(g.kind==='purchase'&&!(g.boostHourly>0)?' Das ist ein Spaßkauf: Er spielt sich nicht von selbst wieder ein, und das ist okay.':''))+'</p></div></li>');
  return '<ol class="b-timeline">'+cards.join('')+'</ol>';}
 function programSummary(r){if(!r||!r.valid)return '';if(r.continuous){const l=(r.route||[]).slice(0,8).map(x=>x.type==='acquire'?'kaufe '+x.name:x.type==='unlock'?x.name+' (einmal)':x.name+' ×'+x.runs);return l.join(' → ')+((r.route||[]).length>8?' → …':'');}return r.phases.map(ph=>(ph.count===1?'Session '+ph.from:'Sessions '+ph.from+'–'+ph.to)+': '+(ph.steps.length?ph.steps.map(st=>st.name+' ×'+st.runs).join(', '):'deine Einnahmen pro Stunde')+(ph.purchasesAfter.length?' → dann kaufe '+ph.purchasesAfter.join(', '):'')).join(' · ');}
 function prereqRequires(s,a,i){const others=[...s.plan.prerequisites.filter(o=>o.id!==a.id).map(o=>[o.id,o.name]),...s.plan.missions.filter(m=>m.once).map(m=>[m.id,'die Mission „'+m.name+'“'])];
  return others.length?'<fieldset class="b-plan-requires"><legend>Vorher brauchst du:</legend>'+others.map(([id,n])=>'<label class="calc-check"><input type="checkbox" data-b-plan-p-req="'+i+'|'+esc(id)+'" '+((a.requires||[]).includes(id)?'checked':'')+'> '+esc(n)+'</label>').join('')+'</fieldset>':'';}
 /* ---------- v7.49 : parcours sans durée de partie, chaîne des étapes, point bas, variantes gardées ---------- */
 const isFlow=r=>!!(r&&r.continuous);
 const timeText=r=>hours((r.totalMinutes||0)/60)+' Spielzeit';
 function goalStep(s){const g=s.plan.goal;return g.kind==='purchase'?'Kauf von '+goalShort(s):g.kind==='unlock'?'Freischaltung '+goalShort(s):'Kontostand von '+goalShort(s);}
 function routeSteps(s,r,o={}){const p=s.plan,max=o.max||40,steps=[{type:'start',name:'Start',detail:money(r.startCash)+' in der Tasche'+(r.input.reserve?' · '+money(r.input.reserve)+' Rücklage':''),cash:r.startCash}];
  p.prerequisites.filter(a=>a.owned).forEach(a=>steps.push({type:'start',name:a.name,detail:'Schon besessen'}));
  p.missions.filter(m=>m.once&&m.done).forEach(m=>steps.push({type:'start',name:m.name,detail:'Schon erledigt'}));
  p.prerequisites.filter(a=>!a.owned&&a.started).concat(p.missions.filter(m=>!(m.once&&m.done)&&m.started)).forEach(x=>steps.push({type:'start',name:x.name,detail:'Begonnen: noch nicht gezählt (hak „erledigt“ ab, wenn es fertig ist)'}));
  const list=(r.route||[]).filter(x=>o.all||x.type!=='run');
  list.slice(0,max).forEach(x=>{const when=isFlow(r)?(x.start>0?'nach '+hours(x.start/60)+' Spielzeit':'gleich zu Beginn'):x.where==='before'?'vor deiner ersten Session':x.where==='after'?'nach Session '+x.session:'während Session '+x.session;
   /* v7.54 : un achat d’avant qui vient d’une fiche du site est cliquable (fiche) ; sinon, aucun lien inventé. */
   if(x.type==='acquire'){const pr=p.prerequisites.find(a=>a.id===x.id||a.name===x.name),item=pr&&pr.itemId?itemFor({itemId:pr.itemId}):null;steps.push({type:'acquire',name:x.name,url:item&&item.url?item.url:undefined,detail:'−'+money(x.spend)+' · '+when+(x.minutes>0?' · '+hours(x.minutes/60)+' zum Beschaffen':''),cash:x.cashAfter});}
   else if(x.type==='unlock')steps.push({type:'unlock',name:x.name,detail:['nur einmal',x.spend?'−'+money(x.spend):'',x.receive?'+'+money(x.receive):'',when].filter(Boolean).join(' · '),cash:x.cashAfter});
   else steps.push({type:'run',name:x.name+(x.runs>1?' ×'+x.runs:''),detail:'+'+money(x.receive-x.spend)+' net · '+hours(x.minutes/60),cash:x.cashAfter});});
  if(list.length>max)steps.push({type:'run',name:'… und '+plural(list.length-max,' Schritt',' Schritte')+' mehr',detail:'Alle Schritte stehen unter „Einzelschritte“ im Expertenmodus.'});
  steps.push({type:'goal',name:goalStep(s),detail:isFlow(r)?'nach '+timeText(r):r.totalSessions===0?'sofort':'nach Session '+r.totalSessions,cash:r.finalCash});
  return steps;}
 function lowText(r){const L=r&&r.lowPoint;if(!L||!Number.isFinite(L.cash)||L.cash>=r.startCash-1e-9)return '';return ' Tiefster Stand: '+money(L.cash)+(L.at?' — '+L.at.charAt(0).toLowerCase()+L.at.slice(1):'')+(r.input.reserve>0&&L.cash>=r.input.reserve-1e-9?', nie unter dem Geld, das du beiseitelegst.':r.input.reserve===0&&L.cash<((r.keptReserve??0))?', unter dem, was du beiseitelegen wolltest.':'.');}
 function lowLine(r){const t=lowText(r);return t?'<p class="b-lowpoint">'+esc(t.trim())+'</p>':'';}
 function routeBlock(s,r){if(!(r.route||[]).some(x=>x.type==='acquire'||x.type==='unlock'))return '';return visual.chain(routeSteps(s,r),{title:'Der Weg, der Reihe nach',question:'Was du kaufst oder freischaltest, und wann: Jeder Schritt öffnet den nächsten.',note:'Ein Kauf wird erst bezahlt, wenn seine Voraussetzungen erfüllt sind und das Geld reicht, ohne die Rücklage anzutasten.'});}
 function flowNext(s,r){const first=(r.route||[]).slice(0,4);if(!first.length)return '';return '<div class="calc-next-action"><strong>Zum Start</strong><ol class="b-next-steps">'+first.map(x=>'<li>'+(x.type==='acquire'?'Kaufe „'+esc(x.name)+'“ <span>−'+money(x.spend)+'</span>':x.type==='unlock'?'Mach „'+esc(x.name)+'“ (nur einmal) <span>'+(x.receive-x.spend>=0?'+':'−')+money(Math.abs(x.receive-x.spend))+'</span>':'„'+esc(x.name)+'“ ×'+x.runs+' <span>+'+money(x.receive-x.spend)+'</span>')+'</li>').join('')+'</ol>'+btn('Nach dem Spielen eintragen, was ich wirklich habe','data-b-focus="plan-actual"')+'</div>';}
 function incompleteBlock(s){const x=analysisOf?analysisOf('plan',s):null;if(!x||!x.incomplete||!x.incomplete.length)return '';const p=s.plan;
  const steps=p.prerequisites.map(a=>({type:a.owned?'start':a.price===null?'missing':'acquire',name:a.name,detail:a.owned?'Schon besessen':a.price===null?'Preis folgt: Gib den Preis ein, den du dir vorstellst, um den Weg zu vervollständigen':money(a.price)}));steps.push({type:'goal',label:'Dein Ziel',name:goalStep(s),detail:'Berechnet, sobald der Weg vollständig ist'});
  return visual.chain(steps,{title:'Weg vervollständigen',question:'Ein unbekannter Preis zählt nie als kostenlos: Gib ihn ein, um den Plan zu bekommen.'})+'<div class="b-plan-card-actions">'+x.incomplete.map(z=>btn('Preis eintragen für „'+z.name+'“','data-b-focus="'+esc(z.field)+'"')).join('')+'</div>';}
 const VARIANT_KEYS=['goal','situation','source','missions','prerequisites','priority','strategy','maxRepeat','deadlineDays'];
 function variantOf(s){const p=s.plan,v={id:'v-'+Date.now().toString(36)+'-'+(p.variants||[]).length,label:(goalName(s)+' · '+(p.source==='missions'?plural(p.missions.length,' Mission',' Missionen'):money(p.situation.hourly)+'/h')).slice(0,120),at:new Date().toISOString().slice(0,10)};VARIANT_KEYS.forEach(k=>{v[k]=B.copy(p[k]);});return v;}
 function variantState(s,v){const c=B.copy(s);VARIANT_KEYS.forEach(k=>{if(v[k]!==undefined)c.plan[k]=B.copy(v[k]);});c.plan.variant='auto';return c;}
 function variantResult(s,v){try{return B.evaluate('plan',variantState(s,v));}catch(e){return {valid:false,reason:e.message};}}
 function variantCell(r){return !r||!r.valid?'Zu ergänzen':r.continuous?timeText(r):(r.totalSessions===0?'Schon möglich':plural(r.totalSessions,' Session',' Sessions')+' · '+plural(r.days,' Tag',' Tage'));}
 function savedVariants(s,r){const list=s.plan.variants||[];
  let html='<p class="calc-note">Eine Variante speichert eine vollständige Kopie des Plans (Ziel, Ausgangslage, Missionen, Käufe vor dem Ziel). Nichts wird überschrieben: Wenn du eine Variante lädst, wird der aktuelle Plan an ihrer Stelle abgelegt.</p><div class="b-plan-card-actions">'+btn('Diesen Plan als Variante behalten','data-b-plan-vsave="1"'+(list.length>=5?' disabled':''))+'</div>';
  if(list.length)html+=table([['Variante','Behalten am','Ergebnis','Geld am Ende'],['Aktueller Plan','—',variantCell(r),r&&r.valid?money(r.finalCash):'—'],...list.map(v=>{const x=variantResult(s,v);return [v.label,v.at||'—',variantCell(x),x&&x.valid?money(x.finalCash):'—'];})],'Der aktuelle Plan und deine Varianten, mit denselben Regeln neu berechnet',true)+'<ul class="b-variant-list">'+list.map(v=>'<li><span>'+esc(v.label)+'</span>'+btn('Diese Variante laden','data-b-plan-vload="'+esc(v.id)+'"')+btn('Entfernen','data-b-plan-vdel="'+esc(v.id)+'"')+'</li>').join('')+'</ul>';
  else html+='<p class="calc-empty">Noch keine Variante behalten. Behalte diese hier, bevor du etwas anderes ausprobierst: So kannst du vergleichen und zurückgehen.</p>';
  if(list.length>=5)html+='<p class="calc-note">Höchstens fünf Varianten: Entferne eine, um eine andere zu behalten.</p>';
  return html;}
 /* ---------- Rendu principal ---------- */
 function render(){const s=state(),p=s.plan,g=p.goal,si=p.situation,r=B.evaluate('plan',s),mode=s.views.plan||'quick',expert=mode==='advanced',details=expert;syncForm(s);
  let head='<p class="calc-kicker">MEINE ANTWORT</p><span class="calc-tag">MIT DEINEN ZAHLEN</span>';
  if(!r.valid){/* v7.54 : bloqué par l’argent de côté (aucun chiffre ne manque) : deux sorties proposées, sans parler d’une case à corriger. */
   if(r.blockedByReserve)head+=warning(r.reason)+'<p class="b-problem">'+btn('„So schnell es geht“ wählen','data-b-focus="f-plan-priority"')+' '+btn('Rücklage ändern','data-b-focus="plan-reserve"')+'</p>'+incompleteBlock(s)+'<div class="calc-next-action"><strong>So bekommst du deinen Ablauf</strong><p>Es fehlt nichts: Deine Rücklage blockiert. Entweder wählst du „So schnell es geht“ bei „Ich bevorzuge“ (dann greift der Plan auf die Rücklage zu und sagt es dir bei jedem Schritt), oder du senkst die Rücklage oder fügst eine Mission hinzu, deren Start weniger kostet.</p></div>';
   else head+=warning(r.reason)+problem(r.reason,'plan')+incompleteBlock(s)+'<div class="calc-next-action"><strong>So bekommst du deinen Ablauf</strong><p>In den Fragen des Plans fehlt eine Zahl oder eine Auswahl. Korrigiere das markierte Feld: Der Plan rechnet sich von selbst, Session für Session.</p></div>';
   $('plan-results').innerHTML=head;$('plan-report').innerHTML='';$('expert-plan').innerHTML='';markSkips(s);return;}
  const D=sessionLabel(s),dpw=r.input.daysPerWeek,reached=r.continuous?r.totalMinutes===0:r.totalSessions===0,next=B.planNextSession(r),first=r.phases[0];
  const meaning=g.kind==='amount'?(g.meaning||'available'):'available',needMoney=meaning==='held'?Math.max(0,r.goalMoney-r.startCash):meaning==='cumulative'?r.goalMoney:Math.max(0,r.goalMoney+r.input.reserve-r.startCash),parts=[];if(g.kind==='unlock'&&r.startUnits<r.input.targetUnits)parts.push(units(s,r.input.targetUnits-r.startUnits));if(needMoney>0||g.kind!=='unlock')parts.push(money(needMoney));
  const missingText=': Dir fehlen noch <b>'+parts.join(' und ')+'</b>';
  const how=p.source==='missions'?'mit deinen Missionen':'mit '+money(si.hourly)+' pro Stunde',flow=isFlow(r);
  /* v7.54 : un but venu d’une fiche dont l’achat n’est pas confirmé garde sa condition jusque dans la réponse du plan (revue v7.53). */
  const goalItem=g.kind!=='amount'&&g.itemId?itemFor({itemId:g.itemId}):null,toConfirm=goalItem&&goalItem.purchasable!==true?' <i>Kauf in GTA VI noch unbestätigt: Der Plan nimmt an, dass man es kaufen kann.</i>':'';
  const phrase=reached?'Gute Nachricht: Schon jetzt möglich: '+esc(g.kind==='purchase'?'Kauf von '+goalShort(s):g.kind==='unlock'?'Freischaltung von '+goalShort(s):'Kontostand von '+goalShort(s))+' mit dem, was du hast, ohne das anzutasten, was du beiseitelegst.'+toConfirm
   :flow?'{but}'.replace('{but}',esc(goalName(s)))+missingText+'. '+how.charAt(0).toUpperCase()+how.slice(1)+': Du schaffst es in <b>'+timeText(r)+'</b>, Schritt für Schritt. Ohne Sessiondauer gibt es keinen Kalender: Gib sie ein, um deine Sessions und Tage zu bekommen.'+toConfirm
   :'{but}'.replace('{but}',esc(goalName(s)))+missingText+'. '+how.charAt(0).toUpperCase()+how.slice(1)+': Du schaffst es in <b>'+plural(r.totalSessions,' Session',' Sessions')+'</b> von '+D+', also <b>'+plural(r.days,' Tag',' Tage')+'</b> (etwa am '+planDate(r.days)+').'+(first&&first.steps.length?' Zuerst: '+stepsText(first.steps)+'.':'')+toConfirm;
  head+='<p class="b-answer calc-answer" data-short="'+esc(reached?'Passt!':flow?timeText(r):plural(r.totalSessions,' Session',' Sessions')+' · '+plural(r.days,' Tag',' Tage'))+'">'+phrase+'</p>'+stats((()=>{const fin=g.kind==='purchase'&&Number.isFinite(r.input.goalPrice)?['Rest nach dem Kauf deines Ziels',money(r.finalCash-r.input.goalPrice)]:['Du hast am Ende',money(r.finalCash)];return flow?[['Spielzeit',hours(r.totalMinutes/60)],['Schritte',String((r.route||[]).length)],fin]:[['Sessions von '+D,String(r.totalSessions)],['Tage',String(r.days)],fin];})())+lowLine(r);
  if(g.kind==='unlock'&&r.input.targetUnits>0)head+=visual.progress('plan-progress',esc(g.unitLabel||'Punkte')+' schon verdient',Math.min(r.startUnits,r.input.targetUnits),r.input.targetUnits,'Start: '+units(s,r.startUnits)+'. Ziel: '+units(s,r.input.targetUnits)+'. 100 % = freigeschaltet.');
  else if(meaning==='cumulative')head+=visual.progress('plan-progress','Ab jetzt schon verdient',0,r.goalMoney,'Du willst '+money(r.goalMoney)+' ab jetzt verdienen: Was du schon hast, wird nicht mitgerechnet. 100 % = Ziel erreicht.');
  else{const need=r.goalMoney+(meaning==='held'?0:r.input.reserve)+r.purchases.filter(x=>!x.owned||x.atSession).reduce((a,x)=>a+(x.atSession?x.price:0),0);head+=visual.progress('plan-progress','Was du schon hast',Math.min(r.startCash,need),need,'Start: '+money(r.startCash)+'. Ziel: '+money(need)+' (alles, was du insgesamt gehabt haben musst, samt allem, was du vor dem Ziel kaufst). 100 % = Du kannst dein Ziel bezahlen.');}
  head+=planStatus(s,r);
  /* v7.52 (lot 5) : le plan choisi touche à l’argent mis de côté (seul chemin trouvé, ou « le plus vite » demandé) : c’est dit
     tout de suite, avec la raison et le point bas, jamais seulement dans le détail des stratégies. */
  {const kept=si.reserve??0;if(kept>0&&r.input.reserve<kept){const why=((r.strategies&&r.strategies.candidates)||[]).find(c=>c.id==='asIs');head+=warning('Dieser Plan nutzt deine '+money(kept)+' Rücklage'+(p.priority==='fast'?': Du hast „so schnell es geht“ eingestellt.':p.strategy==='useReserve'?': Das ist die Reihenfolge, die du festgelegt hast.':(why&&!why.valid&&why.reason?'. Wenn du sie behältst: '+why.reason:': Das ist der schnellste gefundene Weg.'))+(r.lowPoint&&Number.isFinite(r.lowPoint.cash)?' Am tiefsten Punkt hast du '+money(r.lowPoint.cash)+'.':''));}}
  if(r.variant!=='auto')head+='<p class="b-variant-note"><span class="calc-tag">AUSWEICHPLAN</span> Du folgst „'+esc(variantLabel(s,r))+'“. '+btn('Zurück zum besten Plan','data-b-plan-variant="auto"')+'</p>';
  if(reached)head+='<div class="calc-next-action"><strong>Dein nächster Schritt</strong><p>'+esc(g.kind==='purchase'?'Kaufe '+goalShort(s)+' wann immer du willst: Dir bleiben dann '+money(r.finalCash-(r.input.goalPrice||0))+'. Wähle danach ein neues Ziel.':'Dein Ziel ist erreicht. Wähle ein größeres oder einen Kauf.')+'</p></div>';
  else if(flow)head+=flowNext(s,r);
  else if(next)head+='<div class="calc-next-action"><strong>Deine nächste Session ('+D+')</strong>'+(next.steps.length?'<ol class="b-next-steps">'+next.steps.map(st=>'<li>„'+esc(st.name)+'“ ×'+st.runs+' <span>+'+money(st.net)+'</span></li>').join('')+'</ol>':'<p>Spiel '+D+': etwa +'+money(next.gain)+'.</p>')+'<p>'+esc('Dein Geld geht von '+money(r.startCash)+' auf '+money(next.cashAfter+next.purchases.reduce((a,n)=>{const x=r.purchases.find(y=>y.name===n);return a+(x?x.price:0);},0))+'.')+(next.purchases.length?' <b>Dann kaufe: '+esc(next.purchases.join(', '))+'</b> → dir bleiben '+money(next.cashAfter)+'.':'')+(g.kind==='unlock'&&next.unitsGain>0?' +'+units(s,next.unitsGain)+'.':'')+'</p>'+btn('Nach dem Spielen eintragen, was ich wirklich habe','data-b-focus="plan-actual"')+'</div>';
  if(explainBlock&&analysisOf)head+=explainBlock(analysisOf('plan',s),'plan');
  $('plan-results').innerHTML=head;markSkips(s);
  /* ---- Le document : des « gros points » repliables. La réponse est au-dessus ; ici, chaque point s'ouvre d'un geste. ---- */
  const obs=B.planObserved(s),deadline=B.planDeadline(s,r),curve=B.planCurve(r);
  let doc='<div class="calc-card calc-subsection b-doc"><div class="b-doc-head"><div><p class="calc-kicker">MEIN BUSINESSPLAN · '+esc(new Date().toLocaleDateString('de-DE',{day:'numeric',month:'long',year:'numeric'}))+'</p><h3>'+esc(goalName(s).charAt(0).toUpperCase()+goalName(s).slice(1))+'</h3><p class="b-doc-meta">'+esc(reached?'Schon möglich mit dem, was du hast.':(flow?timeText(r):plural(r.totalSessions,' Session',' Sessions')+' von '+D+' · '+plural(r.days,' Tag',' Tage'))+' · '+(p.source==='missions'?plural(p.missions.length,' Mission',' Missionen')+' zur Auswahl':money(si.hourly)+' pro Stunde')+(r.purchases.some(x=>!x.owned||x.atSession)?' · '+plural(r.purchases.filter(x=>x.atSession).length,' Kauf',' Käufe')+' vor dem Ziel':'')+' · deine Zahlen, nicht die des Spiels')+'</p></div><div class="b-doc-tools">'+btn('Alles aufklappen','data-b-fold-all="open"')+btn('Alles zuklappen','data-b-fold-all="close"')+'</div></div><p class="b-doc-hint">Tippe auf einen Punkt, um ihn zu öffnen. Die wichtigen Zahlen stehen schon in jedem Titel.</p>';
  let n=0;const section=(id,title,teaser,lead,body,tone)=>fold('plan-'+id,{n:++n,title,teaser,tone,body:()=>(lead?'<p class="b-doc-lead">'+lead+'</p>':'')+(typeof body==='function'?body():body)});
  /* 1. Programme */
  if(flow)doc+=section('program','Dein Weg, der Reihe nach',reached?'Schon möglich: Vor deinem Ziel ist nichts zu tun':'<b>'+timeText(r)+'</b> · '+plural((r.route||[]).length,' Schritt',' Schritte')+' · ohne Kalender','Was zu tun ist, der Reihe nach, ohne Pause zwischen zwei Sessions. Gib die Sessiondauer ein, um den Ablauf Session für Session und deine Daten zu bekommen.',()=>visual.chain(routeSteps(s,r,{all:true,max:24}),{title:'Der Weg, der Reihe nach',question:'Von oben nach unten lesen: Jeder Schritt öffnet den nächsten.',note:'In jedem Moment nehmen wir unter den möglichen Missionen die, die pro Minute am meisten einbringt; ein Kauf vor dem Ziel wird bezahlt, sobald es geht, ohne die Rücklage anzutasten.'})+lowLine(r),'main');
  else doc+=section('program','Dein Ablauf, der Reihe nach',reached?'Schon möglich: Vor deinem Ziel ist nichts zu tun':(first&&first.steps.length?'Zuerst: '+stepsText(first.steps)+' · <b>'+plural(r.totalSessions,' Session',' Sessions')+'</b>, '+plural(r.phases.length,' Schritt',' Schritte'):'<b>'+plural(r.totalSessions,' Session',' Sessions')+'</b> von '+D+' · '+plural(r.days,' Tag',' Tage')),reached?'':'Was du zuerst, als Zweites, als Drittes machst … Das ist der schnellste Weg, der mit deinen Missionen und deiner Zeit gefunden wurde.',()=>phaseCards(s,r)+routeBlock(s,r)+lowLine(r)+(reached?'':'<p class="calc-note">So wird die Reihenfolge gewählt: In jeder Session nehmen wir die Missionen, die in der Zeit der Session am meisten einbringen, mit dem Geld, das du gerade hast. Ein Kauf vor dem Ziel passiert, sobald du ihn bezahlen kannst, ohne das Geld anzutasten, das du zurücklegst; schaltet er eine Mission frei oder bringt er Geld, geht der Rest schneller.'+(r.limited?' Der Ablauf entsteht aus den Abfolgen, die in jeder Session verglichen werden: Es kann einen schnelleren geben.':'')+'</p>'),'main');
  /* 2. Plans de secours (calculés seulement quand on ouvre le point) */
  if(!reached){const late=obs&&obs.last&&obs.last.gap!==null&&obs.last.gap<-1e-9;
   const intro=late?'Deine letzte Session brachte <b>'+money(obs.last.gain)+'</b> statt <b>'+money(obs.last.plannedGain)+'</b> (geplant). Der Plan oben startet schon neu von dem, was du hast; hier trotzdem andere Wege zum Ziel, mit ihrer Zeit.':'Wenn eine Mission nicht reinpasst, du weniger verdienst als geplant oder es lieber anders machen willst: Jeder Plan wird mit derselben Ausgangslage berechnet. Wähle einen, der Ablauf folgt.';
   doc+=section('alternatives','Wenn es nicht wie geplant läuft',late?'<b>'+money(obs.last.gain)+'</b> verdient statt '+money(obs.last.plannedGain)+' (geplant) · Pläne A, B, C …':(r.variant!=='auto'?'Du folgst einem Ausweichplan · die anderen sind hier':'Pläne A, B, C … für deine Ausgangslage berechnet, bereit, falls du weniger verdienst als geplant'),intro,()=>{const alt=B.planAlternatives(s,r),plans=alt.valid?alt.plans:[],curId=r.variant==='auto'?'all':r.variant,ok=plans.filter(x=>x.valid).sort((a,b)=>(a.id===curId?-1:b.id===curId?1:0)),ko=plans.filter(x=>!x.valid);
    return (ok.length?'<ol class="b-alts">'+ok.slice(0,5).map((x,i)=>'<li class="b-alt'+(x.id===curId?' is-current':'')+'"><span class="b-alt-letter">'+String.fromCharCode(65+i)+'</span><div><h4>Plan '+String.fromCharCode(65+i)+' · '+esc(x.label)+(x.id===curId?' <span class="calc-tag">DEIN AKTUELLER PLAN</span>':'')+'</h4><div class="b-tiles">'+(flow?'<span><small>Spielzeit</small><b>'+hours((x.totalMinutes||0)/60)+'</b></span>':'<span><small>Sessions</small><b>'+x.totalSessions+'</b></span><span><small>Tage</small><b>'+x.days+'</b></span>')+'<span><small>Am Ende</small><b>'+money(x.finalCash)+'</b></span></div><p class="b-alt-program">'+esc(programSummary(alt.results[x.id]))+'</p>'+(x.note?'<p class="calc-note">'+esc(x.note)+'</p>':'')+(x.id!==curId?btn('Diesem Plan folgen','data-b-plan-variant="'+esc(x.id)+'"'):'')+'</div></li>').join('')+'</ol>':'<p>'+esc(alt.valid?'Mit diesen Zahlen funktioniert kein anderer Plan.':alt.reason)+'</p>')+(ko.length?'<p class="calc-note"><b>Mit diesen Zahlen unmöglich:</b> '+ko.map(x=>esc(x.label)+' ('+esc(x.reason||'nicht erreicht')+')').join(' · ')+'</p>':'');},late?'alert':'');}
  /* 3. Suivi du réel */
  doc+=section('actual','Nach dem Spielen: Wo stehst du wirklich?',obs?'<b>'+plural(obs.sessions,' Session',' Sessions')+(lkPluriel(obs.sessions)?'</b> erfasst':'</b> erfasst')+' · zuletzt: '+(obs.last.gain>=0?'+':'−')+money(Math.abs(obs.last.gain))+(obs.last.gap===null?'':' ('+(obs.last.gap>=0?'+':'−')+money(Math.abs(obs.last.gap))+' gegenüber dem Plan)'):'Gib nach deiner Session ein, was du hast: Der ganze Plan wird neu berechnet','Gib ein, was du jetzt hast und was du gemacht hast. Der ganze Plan wird von da aus neu berechnet: Missionen, Käufe, Sessions, Tage. Nichts wird doppelt gezählt.',()=>actualForm(s,r,obs));
  /* 4. Point de départ */
  const start=[['Geld in der Tasche',money(si.capital),'plan-capital'],['Zurückgelegt',money(r.input.reserve)+(r.input.reserve!==(si.reserve??0)?' (Auswahl: „so schnell es geht“)':''),'plan-reserve'],['Eine Session',flow?'freie Dauer: Weg ohne Kalender':D+' · '+dpw+' Tage/Woche','plan-daily'],['Ausgaben pro Session',money(si.upkeepPerSession||0),'plan-upkeep'],
   p.source==='missions'?['Missionen zur Auswahl',p.missions.map(m=>m.name).join(', ')||'keine',p.missions.length?'plan-m-0-reward':'plan-m-source']:['Einnahmen pro Stunde (deine Zahl)',money(si.hourly),'plan-hourly'],
   g.kind==='purchase'?['Dein Ziel',esc(g.name||'mein Kauf')+' · '+money(g.price)+(g.boostHourly>0?' · +'+money(g.boostHourly)+'/Std. danach':''),'plan-price']:g.kind==='amount'?['Dein Ziel','Kontostand von '+money(g.target),'plan-target']:['Dein Ziel','Freischaltung von '+esc(g.name||'mein Ziel')+' · '+units(s,g.targetUnits)+(g.alsoPrice>0?' · dann '+money(g.alsoPrice):''),'plan-units-target'],
   ['Käufe vor dem Ziel',p.prerequisites.length?p.prerequisites.map(a=>a.name+(a.owned?' (schon besessen)':' ('+money(a.price)+(a.boostHourly>0?', +'+money(a.boostHourly)+'/h':'')+')')).join(' · '):'keine','plan-prereq-search']];
  doc+=section('start','Dein Ausgangspunkt',esc(money(si.capital)+' in der Tasche · '+D+' · '+dpw+' Tage/Woche · '+(p.source==='missions'?plural(p.missions.length,' Mission',' Missionen'):money(si.hourly)+'/h')),'Die Zahlen hinter diesem Plan. Ändere eine: Alles wird neu berechnet.','<ul class="b-assumptions">'+start.map(([l,v,f])=>'<li><span>'+esc(l)+'</span><b>'+v+'</b>'+btn('Ändern','data-b-focus="'+f+'"')+'</li>').join('')+'</ul><p class="calc-note">Nichts stammt aus dem echten Spiel: Preise, Einnahmen und Zeiten sind deine Zahlen oder die, die die Seite als Richtwerte angibt.</p>');
  /* 5. Stratégie */
  const st=r.strategies;
  if(st&&st.valid&&st.candidates.filter(c=>c.valid).length>1){const rec=st.candidates.find(c=>c.id===st.recommended),asIs=st.candidates.find(c=>c.id==='asIs');
   const why=rec&&asIs&&rec.id!=='asIs'&&rec.valid&&asIs.valid?((flow?rec.totalMinutes<asIs.totalMinutes-1e-9:rec.totalSessions<asIs.totalSessions)?'du sparst '+(flow?hours((asIs.totalMinutes-rec.totalMinutes)/60)+' Spielzeit':plural(asIs.totalSessions-rec.totalSessions,' Session',' Sessions'))+' gegenüber deiner Reihenfolge':'gleiche '+(flow?'Spielzeit':'Anzahl Sessions')+' wie deine Reihenfolge, mit '+(rec.reserveKept?'unangetasteter Rücklage':'mehr Geld am Ende')):p.priority==='cheap'?'das ist das Vorgehen mit dem meisten Geld am Ende, unter denen, die dein beiseitegelegtes Geld nicht antasten':p.priority==='safe'?'das ist das Vorgehen mit dem besten Tiefststand unter denen, die dein beiseitegelegtes Geld nicht antasten':'das ist das schnellste Vorgehen unter denen, die '+(p.priority==='fast'?'verglichen wurden':'dein beiseitegelegtes Geld nicht antasten');
   doc+=section('strategy','Die Reihenfolge der Käufe vor dem Ziel','Empfohlen: <b>'+esc(rec?rec.label:'')+'</b> · '+st.candidates.filter(c=>c.valid).length+' Vorgehensweisen verglichen','Gleiches Ziel, gleiche Zahlen: Nur die Reihenfolge der Käufe oder die Rücklage ändert sich.','<p class="b-strategy-answer"><b>'+esc(rec?rec.label:'')+'</b>: '+esc(why)+'.</p>'+table([['Vorgehen',flow?'Spielzeit':'Sessions','Tage','Geld am Ende','Tiefster Stand','Rücklage behalten'],...st.candidates.map(c=>[(c.id===st.recommended?'★ ':'')+c.label+(c.note?' — '+c.note:''),c.valid?(flow?hours((c.totalMinutes||0)/60):String(c.totalSessions)):'Unmöglich: '+c.reason,c.valid&&!flow?String(c.days):'—',c.valid?money(c.finalCash):'—',c.valid&&c.lowCash!==null&&c.lowCash!==undefined?money(c.lowCash):'—',c.reserveKept?'Ja':'Nein'])],'Reihenfolgen, durch komplette Neuberechnung verglichen',true)+'<p class="calc-note">Wir vergleichen '+st.explored+' Vorgehensweisen; es kann eine bessere geben. Vorgehensweisen, die einen gewünschten Kauf weglassen, werden nie empfohlen.</p>');}
  /* 6. Échéance */
  if(p.deadlineDays){let body='';if(!deadline||!deadline.valid)body=warning(deadline?deadline.reason:'Frist nicht berechenbar.');
   else if(deadline.feasible)body='<p class="b-strategy-answer"><b>Ja</b>, das ist machbar: Du bist fertig an Tag '+deadline.days+', mit '+plural(deadline.spareDays,' Tag',' Tage')+' Puffer.</p>';
   else body='<p class="b-strategy-answer"><b>Nicht in deinem aktuellen Tempo</b>: Fertig wärst du erst an Tag '+deadline.days+', also '+plural(deadline.spareDays,' Tag',' Tage')+' zu spät.</p><ul class="b-thresholds">'+(deadline.everydayDays!==null?'<li>Spiel <b>jeden Tag</b>: Dann bist du fertig an Tag '+deadline.everydayDays+'.</li>':'')+(deadline.requiredSessionMinutes!==null?'<li>Oder Sessions von <b>'+hours(deadline.requiredSessionMinutes/60)+'</b> statt '+D+'.</li>':'')+(deadline.requiredHourly!==null?'<li>Oder verdiene <b>'+money(deadline.requiredHourly)+' pro Stunde</b> statt '+money(si.hourly)+'.</li>':'')+(deadline.everydayDays===null&&deadline.requiredSessionMinutes===null&&deadline.requiredHourly===null?'<li>Keine einfache Änderung reicht: Senk das Ziel oder wechsle die Missionen.</li>':'')+'<li>Sonst das früheste Datum: <b>Tag '+r.days+'</b> (etwa am '+planDate(r.days)+').</li></ul>';
   doc+=section('deadline','Deine Frist: '+plural(p.deadlineDays,' Tag',' Tage'),deadline&&deadline.valid?(deadline.feasible?'<b>Machbar</b> · '+plural(deadline.spareDays,' Tag',' Tage')+' Puffer':'<b>Nicht in deinem Tempo</b> · Tag '+deadline.days+' statt '+p.deadlineDays):'Zu prüfen','',body,deadline&&deadline.valid&&!deadline.feasible?'alert':'');}
  /* 7+. Détails */
  if(details&&!reached){
   const rows=r.sessions.slice(0,60).map(se=>['Session '+se.index+' · Tag '+dayOf(se.index,dpw),se.steps.length?se.steps.map(st=>st.name+' ×'+st.runs).join(', '):'deine Einnahmen pro Stunde','+'+money(se.gain)+(g.kind==='unlock'&&se.unitsGain>0?' · +'+nf.format(Math.round(se.unitsGain*100)/100):''),money(se.cashAfter),se.purchases.length?se.purchases.join(', '):'—']);
   if(flow)doc+=section('route-table','Einzelschritte',plural((r.route||[]).length,' Schritt',' Schritte')+' · von '+money(r.startCash)+' auf '+money(r.finalCash),'Jeder Schritt des Wegs, mit dem, was er kostet, was er einbringt und was du danach hast.',()=>table([['Wann','Schritt','Bezahlt','Erhalten','Danach hast du'],...(r.route||[]).slice(0,120).map(x=>[hours(x.start/60),x.type==='acquire'?'Kaufe „'+x.name+'“':x.type==='unlock'?'„'+x.name+'“ (nur einmal)':'„'+x.name+'“ ×'+x.runs,x.spend?'−'+money(x.spend):'—',x.receive?'+'+money(x.receive):'—',money(x.cashAfter)])],'Der ganze Weg'+((r.route||[]).length>120?' (erste 120 Schritte von '+r.route.length+')':''),true));
   else doc+=section('sessions','Session für Session',plural(r.totalSessions,' Session',' Sessions')+' · von '+money(r.startCash)+' auf '+money(r.finalCash),'Jede Session mit ihren Missionen, was sie einbringt, was du danach hast und was du kaufst.',()=>table([['Session','Missions','Verdient','Danach hast du','Kauf'],...rows],'Der ganze Ablauf'+(r.sessions.length>60?' (erste 60 Sessions von '+r.sessions.length+')':''),true));
   doc+=section('variants','Was wäre, wenn …?','Längere Sessions, ein Tag mehr, höhere Preise, Missionen, die weniger einbringen …','Derselbe Plan, komplett neu berechnet mit einer geänderten Zahl.',()=>{const v=variants(s,r);return table([['Was wäre, wenn …',flow?'Spielzeit':'Sessions','Tage','Geld am Ende'],...v.map(x=>[x.label,x.r.valid&&x.r.reached?(flow?hours(x.r.totalMinutes/60):String(x.r.totalSessions)):'Unmöglich',x.r.valid&&x.r.reached&&!flow?String(x.r.days):'—',x.r.valid?money(x.r.finalCash):'—'])],'Um zu sehen, was am meisten zählt',true);});
   doc+=section('thresholds','Was alles ändert','30 min mehr pro Session, der Kauf vor dem Ziel sofort …','',()=>{const v=variants(s,r),thresholds=[];const longer=v.find(x=>x.id==='longer');if(longer&&longer.r.valid&&longer.r.reached)thresholds.push(longer.r.totalSessions<r.totalSessions?'Mit <b>30 min mehr pro Session</b>: Du schaffst es in <b>'+plural(longer.r.totalSessions,' Session',' Sessions')+'</b> statt '+r.totalSessions+'.':'<b>30 min mehr pro Session</b> lassen die Anzahl der Sessions gleich ('+r.totalSessions+'): Die Zeit ist nicht das, was bremst.');
    const firstBuy=r.purchases.find(x=>x.atSession);if(firstBuy&&firstBuy.atSession>1)thresholds.push('Dir fehlen <b>'+money(Math.max(0,firstBuy.price+r.input.reserve-r.startCash))+'</b>, um „'+esc(firstBuy.name)+'“ sofort zu kaufen.');
    if(g.kind==='unlock'&&r.missingUnits===0&&r.startUnits<r.input.targetUnits)thresholds.push('Dir fehlen <b>'+units(s,r.input.targetUnits-r.startUnits)+'</b> für die Freischaltung von '+esc(goalShort(s))+'.');
    return thresholds.length?'<ul class="b-thresholds">'+thresholds.map(t=>'<li>'+t+'</li>').join('')+'</ul>':'<p class="calc-note">Mit diesen Zahlen ändert keine kleine Anpassung den Plan stark.</p>';});
   if(curve.length>1)doc+=section('curve','Dein Geld im Verlauf des Plans','Die geplante Kurve'+(p.log.length?' und deine echten Punkte (anklickbar)':'')+' · '+money(r.startCash)+' → '+money(r.finalCash),'',()=>visual.chart('c-plan-curve',{title:'Dein Geld, Session für Session',question:'Wann wird jeder Kauf möglich, und wo stehst du dann?',xTitle:'Spielzeit (Stunden)',yTitle:'Geld in der Tasche ($)',unit:'$',xUnit:'h',area:false,series:[{name:'Geplant mit deinen Zahlen',kind:'forecast',step:true,points:curve.map(pt=>({x:pt.hours,y:pt.cash,label:pt.label,key:pt.purchase}))},...(p.log.length?[{name:'Echt (was du eingetragen hast)',kind:'realized',dots:true,points:p.log.map((e,i)=>({x:e.minutes/60,y:e.capital,label:new Date(e.at).toLocaleDateString('de-DE'),edit:'log:'+i}))}]:[])],thresholds:r.input.reserve>0?[{y:r.input.reserve,label:'Rücklage'}]:[],reading:(flow?'Das Geld springt bei jeder Belohnung auf einmal hoch und fällt bei allen Kosten oder Käufen: Nichts wird geglättet.':'Jede Stufe ist eine Session: Ihr Geld wird am Ende der Session gezählt, Käufe direkt danach inklusive. Der Plan endet nach '+plural(r.totalSessions,' Session',' Sessions')+'.')+lowText(r),note:'Die „echten“ Punkte stammen aus deinen Aktualisierungen; sie sind nicht geglättet. Klick auf einen echten Punkt, um ihn zu korrigieren oder zu entfernen.'}));
   const cal=[...r.purchases.filter(x=>x.atSession).map(x=>['Kaufe „'+x.name+'“','nach Session '+x.atSession,'Tag '+dayOf(x.atSession,dpw),planDate(dayOf(x.atSession,dpw))]),[g.kind==='purchase'?'Kaufe '+goalShort(s):g.kind==='unlock'?'Schalte frei: '+goalShort(s):'Du hast '+goalShort(s),'nach Session '+r.totalSessions,'Tag '+r.days,planDate(r.days)]];
   if(!flow)doc+=section('calendar','Dein Kalender','Ziel etwa am <b>'+esc(planDate(r.days))+'</b>'+(cal.length>1?' · '+plural(cal.length-1,' Kauf',' Käufe')+' vorher':''),'Bei '+D+' pro Session, '+dpw+(E.plural(dpw)?' Tage':' Tag')+' pro Woche, ab heute gerechnet.',table([['Schritt','Wann','Tag','Geschätztes Datum'],...cal],'Die wichtigen Momente',true));
   doc+=section('method','Wie wird das berechnet?','Session für Session, mit deinen Zahlen, ohne etwas zu erfinden','','<p class="calc-note">Session für Session: Mit dem Geld, das du in diesem Moment hast, suchen wir die Missionen, die in der Zeit der Session am meisten einbringen (Kosten vorher bezahlt, Belohnung am Ende, Vorbereitung und Wartezeit eingerechnet, eine Mission wird ganz oder gar nicht gemacht). Wir ziehen deine Ausgaben pro Session ab und rechnen dazu, was deine schon getätigten Käufe einbringen. Dann bezahlen wir die Käufe vor dem Ziel der Reihe nach, sobald das Geld den Preis übersteigt, ohne die Rücklage anzutasten; ein Kauf kann eine Mission freischalten. Wir hören auf, sobald du dein Ziel bezahlen kannst (und die Punkte hast, falls nötig). Tage = Sessions, verteilt auf deine Spieltage pro Woche, ab heute gerechnet. Nichts stammt aus dem echten Spiel.</p>'+(flow?'<p class="calc-note">Ohne Sessiondauer reiht der Weg die Schritte ohne Pause aneinander: In jedem Moment die mögliche Mission, die pro Minute am meisten einbringt, die Käufe vor dem Ziel, sobald sie bezahlbar sind, die Wartezeiten, wenn nötig. Deshalb gibt es keine Tage, nur Spielzeit.</p>':''));}
  else if(!reached&&mode!=='advanced')doc+='<div class="b-doc-more"><p class="calc-note">Jede Session, die „Was wäre, wenn“-Fälle, die Kurve und der Kalender stehen im Expertenmodus.</p>'+btn('Im Expertenmodus ansehen','data-b-mode="advanced"')+'</div>';
  doc+=section('saved','Meine Plan-Varianten',(p.variants||[]).length?'<b>'+plural(p.variants.length,' Variante',' Varianten')+(lkPluriel(p.variants.length)?'</b> gespeichert':'</b> behalten')+' · vergleiche sie mit dem aktuellen Plan':'Behalte diesen Plan, bevor du etwas anderes ausprobierst','',()=>savedVariants(s,r));
  doc+='<div class="b-plan-links">'+btn('Meine nächste Session vorbereiten','data-open="session"')+btn('Prüfen, was ein Kauf einbringt','data-open="roi"')+btn('Käufe vergleichen','data-open="compare"')+'</div></div>';
  $('plan-report').innerHTML=doc;
  $('expert-plan').innerHTML=expert?expertBlock(s,r):'';
 }
 function markSkips(s){document.querySelectorAll('#panel-plan .calc-step[data-step="4"]').forEach(n=>{if(!s.plan.prerequisites.length&&s.plan.goal.kind==='amount')n.dataset.skip='1';else delete n.dataset.skip;});}
 function variantLabel(s,r){if(r.variant==='auto')return '';const alt=B.planAlternatives(s,r);const x=alt.valid?alt.plans.find(y=>y.id===r.variant):null;return x?x.label:r.variant;}
 function variants(s,r){const i=r.input,out=[];const run=(id,label,changes)=>out.push({id,label,r:E.missionPlan({...i,...changes})});
  if(i.sessionMinutes)run('longer','Sessions mit 30 min mehr',{sessionMinutes:i.sessionMinutes+30});
  if(i.sessionMinutes&&i.daysPerWeek<7)run('everyday','Ein Spieltag mehr pro Woche',{daysPerWeek:i.daysPerWeek+1});
  run('prices','Die Preise sind 20 % höher',{goalPrice:i.goalPrice===null?null:i.goalPrice*1.2,target:i.target===null?null:i.target*1.2,purchases:i.purchases.map(x=>({...x,price:x.price*1.2}))});
  run('less',s.plan.source==='missions'?'Meine Missionen bringen 20 % weniger ein':'Ich verdiene 20 % weniger',s.plan.source==='missions'?{activities:i.activities.map(a=>({...a,reward:a.reward===null?null:a.reward*0.8}))}:{hourly:i.hourly*0.8});
  if(i.reserve>0)run('reserve','Ich gebe auch meine Rücklage aus',{reserve:0});
  return out;}
 function actualForm(s,r,obs){const p=s.plan,g=p.goal,si=p.situation,next=B.planNextSession(r);
  let html='<div class="calc-fields b-actual"><div class="calc-field"><label class="calc-label" for="plan-actual">Ich habe jetzt ($)</label><input id="plan-actual" type="text" inputmode="decimal" maxlength="25" data-number="1" data-min="0" data-max="1000000000000" value="" placeholder="'+esc(nf.format(si.capital??0))+'"><small>Dein Geld in der Tasche nach deiner Session.</small></div><div class="calc-field"><label class="calc-label" for="plan-actual-minutes">Ich habe gespielt (Minuten)</label><input id="plan-actual-minutes" type="text" inputmode="decimal" maxlength="6" data-number="1" data-min="0" data-max="100000" value="'+esc(si.dailyMinutes??'')+'"></div>';
  if(g.kind==='unlock')html+='<div class="calc-field"><label class="calc-label" for="plan-actual-units">Ich habe jetzt ('+esc(g.unitLabel||'points')+')</label><input id="plan-actual-units" type="text" inputmode="decimal" maxlength="25" data-number="1" data-min="0" data-max="1000000000000" value="" placeholder="'+esc(nf.format(g.currentUnits??0))+'"></div>';
  if(p.source==='missions')html+=p.missions.map(m=>{const planned=next?next.steps.find(st=>st.id===m.id):null;return '<div class="calc-field"><label class="calc-label" for="plan-actual-runs-'+esc(m.id)+'">„'+esc(m.name)+'“ wie oft erledigt?</label><input id="plan-actual-runs-'+esc(m.id)+'" data-b-plan-actual-runs="'+esc(m.id)+'" type="text" inputmode="numeric" maxlength="6" data-number="1" data-min="0" data-max="100000" value="" placeholder="'+(planned?'geplant: '+planned.runs:'0')+'"></div>';}).join('');
  html+='<div class="calc-field wide"><label class="calc-label" for="plan-actual-note">Eine Notiz, wenn du willst</label><input id="plan-actual-note" type="text" maxlength="300" value="" placeholder="Was in der Session passiert ist"></div></div>';
  const buyable=p.prerequisites.filter(a=>!a.owned);if(buyable.length)html+='<fieldset class="b-plan-requires"><legend>In dieser Session habe ich gekauft:</legend>'+buyable.map(a=>'<label class="calc-check"><input type="checkbox" data-b-plan-actual-bought="'+esc(a.id)+'"> '+esc(a.name)+(a.price!==null?' ('+money(a.price)+')':'')+'</label>').join('')+'</fieldset>';
  html+='<div class="b-plan-card-actions">'+btn('Meinen Plan aktualisieren','data-b-plan-log="1"',true)+(p.log.length?btn('Verlauf löschen','data-b-plan-clear="1"'):'')+'</div><p class="calc-note" id="plan-log-feedback" role="status"></p>';
  if(obs&&obs.last){const L=obs.last,gap=L.gap;
   html+='<div class="b-bilan"><p class="calc-kicker">BILANZ DEINER LETZTEN SESSION</p><div class="b-tiles">'+[['Geplant',L.plannedGain===null?'—':'+'+money(L.plannedGain)],['Tatsächlich','+'+money(L.gain)],['Abweichung',gap===null?'—':(gap>=0?'+':'−')+money(Math.abs(gap))],['Dein echtes Tempo',obs.hourly===null?'—':money(Math.round(obs.hourly))+' pro Stunde']].map(([l,v])=>'<span><small>'+esc(l)+'</small><b>'+v+'</b></span>').join('')+'</div><p>'+esc(gap===null?'Der Plan startet neu von dem, was du jetzt hast.':gap>=0?'Du bist voraus: Der Plan startet neu von dem, was du hast, und er ist kürzer.':'Du hast weniger verdient als geplant: Der Plan startet neu von dem, was du hast, und der Abschnitt „Wenn es nicht wie geplant läuft“ schlägt andere Wege vor.')+(obs.sessions>1?' Über deine '+obs.sessions+' erfassten Sessions verdienst du im Schnitt '+money(obs.perSession)+' pro Session.':'')+'</p>'+(p.source==='hourly'&&obs.hourly!==null&&Math.abs(obs.hourly-(si.hourly||0))>1?btn('Mein echtes Tempo übernehmen ('+money(obs.hourly)+' pro Stunde)','data-b-plan-adopt="1"'):'')+'</div>';}
  if(p.log.length){const rows=p.log.slice().reverse().map(e=>{const d=new Date(e.at),date=Number.isFinite(d.getTime())?d.toLocaleDateString('de-DE',{day:'numeric',month:'short'}):'—';return [date,hours(e.minutes/60),e.plannedGain===null?'—':'+'+money(e.plannedGain),e.gain===null?'—':'+'+money(e.gain),money(e.capital),e.forecast===null?'—':money(e.forecast),Object.keys(e.runs).length?Object.entries(e.runs).filter(([,n])=>n>0).map(([id,n])=>(p.missions.find(m=>m.id===id)?.name||id)+' ×'+n).join(', ')+(e.purchases.length?' · gekauft: '+e.purchases.map(id=>p.prerequisites.find(a=>a.id===id)?.name||id).join(', '):''):(e.purchases.length?'gekauft: '+e.purchases.map(id=>p.prerequisites.find(a=>a.id===id)?.name||id).join(', '):'—'),e.note||'—'];});
   html+=table([['Date','Insgesamt gespielt','Geplant (Session)','Tatsächlich (Session)','Ich hatte','Der Plan sah vor','Erledigt','Note'],...rows],'Tatsächlich gegen geplant, Session für Session',true)+'<p class="calc-note">„Der Plan sah vor“ = das Geld, das nach dieser Spielzeit erwartet wurde, laut dem Plan vor der Aktualisierung. Der aktuelle Plan startet immer neu vom tatsächlichen Stand.</p>';}
  return html;}
 function expertBlock(s,r){const RAW={totalSessions:'Sessions',totalMinutes:'Spielzeit (min)',activeMinutes:'Zeit in Missionen (min)',days:'Tage',weeks:'Wochen',finalCash:'Geld am Ende ($)',finalUnits:'Punkte am Ende',missing:'Es fehlen ($)',missingUnits:'Fehlende Punkte',averagePerSession:'Verdient pro Session, im Schnitt ($)',goalMoney:'Zielbetrag ($)',startCash:'Geld am Start ($)',startUnits:'Punkte am Start'};const rows=Object.entries(r).filter(([k,v])=>RAW[k]&&(typeof v==='number'||v===null)).map(([k,v])=>[RAW[k],v===null?'Noch nicht berechenbar':nf.format(v)]);const i=r.input;
  return '<div class="b-doc b-doc--light"><div class="b-doc-title b-doc-title--plain"><span class="b-doc-num">★</span><div><h3>Expertenmodus: alle Details</h3><p class="b-doc-lead">Der Expertenmodus zeigt alles: jede Session, die „Was wäre, wenn“-Fälle, die Kurve, den Kalender und alle Zahlen der Berechnung. Es sind dieselben Zahlen wie im Modus „Einfach“, nur mit allen Details.</p></div></div>'+fold('plan-x-inputs',{n:1,title:'Die verwendeten Zahlen',teaser:esc(money(i.capital)+' · zurückgelegt '+money(i.reserve)+' · '+(i.sessionMinutes?hours(i.sessionMinutes/60):'freie Dauer')+' · Reihenfolge der Käufe: '+STRATEGY_LABEL[r.strategy||'asIs']),body:()=>table([['Zahl','Wert'],['Geld',money(i.capital)],['Zurückgelegt',money(i.reserve)],['Sessiondauer',(i.sessionMinutes?hours(i.sessionMinutes/60):'freie Dauer')],['Tage pro Woche',String(i.daysPerWeek)],['Ausgaben pro Session',money(i.upkeepPerSession)],['Ich verdiene pro Stunde',money(i.hourly)],['Missions',i.activities.map(a=>a.name).join(', ')||'keine'],['Ziel',i.goalPrice!==null?i.goalName+': '+money(i.goalPrice):i.target!==null?'Kontostand von '+money(i.target):'Freischaltung '+i.goalName],['Zu erreichende Punkte',i.targetUnits===null?'—':nf.format(i.targetUnits)+' (schon '+nf.format(i.currentUnits)+')'],['Berücksichtigte Käufe vor dem Ziel',i.purchases.map(x=>x.name).join(', ')||'keine'],['Reihenfolge der Käufe',STRATEGY_LABEL[r.strategy||'asIs']],['Verfolgter Plan',!r.variant||r.variant==='auto'?'der Rechner wählt':String(r.variant)]],'Die verwendeten Zahlen')})+fold('plan-x-raw',{n:2,title:'Alle Zahlen der Berechnung',teaser:esc(rows.length+' Zahlen'),body:()=>table(rows,'Alle Zahlen der Berechnung')})+'</div>';}
 /* ---------- Événements propres au plan ---------- */
 function event(ev){const el=ev.target,s=state(),p=s.plan;
  if(ev.type==='change'){
   if(el.dataset.field==='plan.goal.kind'){if(B.PLAN_KINDS.includes(el.value))p.goal.kind=el.value;p.variant='auto';refresh(el.id);return true;}
   if(el.dataset.field==='plan.source'){if(B.PLAN_SOURCES.includes(el.value))p.source=el.value;p.variant='auto';refresh(el.id);return true;}
   if(el.dataset.field==='plan.strategy'){p.strategy=B.STRATEGIES.includes(el.value)?el.value:'auto';api.changed();return true;}
   if(el.dataset.bPlanMOwned!==undefined){const m=p.missions[Number(el.dataset.bPlanMOwned)];if(m)m.owned=el.checked;api.changed();return true;}
   if(el.dataset.bPlanMReq!==undefined){const [i,id]=el.dataset.bPlanMReq.split('|'),m=p.missions[Number(i)];if(m){m.requires=el.checked?[...new Set([...m.requires,id])]:m.requires.filter(x=>x!==id);}api.changed();return true;}
   if(el.dataset.bPlanMOnce!==undefined){const m=p.missions[Number(el.dataset.bPlanMOnce)];if(m){m.once=el.checked;if(!m.once)m.done=false;}p.variant='auto';refresh(el.id);return true;}
   if(el.dataset.bPlanMState!==undefined){const m=p.missions[Number(el.dataset.bPlanMState)];if(m&&el.checked){m.done=el.value==='done'&&m.once;m.started=el.value==='started';}p.variant='auto';api.changed();return true;}
   if(el.dataset.bPlanPState!==undefined){const a=p.prerequisites[Number(el.dataset.bPlanPState)];if(a&&el.checked){a.owned=el.value==='done';a.started=el.value==='started';}p.variant='auto';api.changed();return true;}
   if(el.dataset.bPlanMDone!==undefined){const m=p.missions[Number(el.dataset.bPlanMDone)];if(m)m.done=el.checked&&m.once;p.variant='auto';api.changed();return true;}
   if(el.dataset.bPlanMReqm!==undefined){const [i,id]=el.dataset.bPlanMReqm.split('|'),m=p.missions[Number(i)];if(m&&id!==m.id){m.requiresMissions=el.checked?[...new Set([...(m.requiresMissions||[]),id])]:(m.requiresMissions||[]).filter(x=>x!==id);}p.variant='auto';api.changed();return true;}
   if(el.dataset.bPlanPReq!==undefined){const [i,id]=el.dataset.bPlanPReq.split('|'),a=p.prerequisites[Number(i)];if(a&&id!==a.id){a.requires=el.checked?[...new Set([...(a.requires||[]),id])]:(a.requires||[]).filter(x=>x!==id);}p.variant='auto';api.changed();return true;}
   if(el.dataset.bPlanPLock!==undefined){const id=el.dataset.bPlanPLock;p.locked=el.checked?[...new Set([...(p.locked||[]),id])]:(p.locked||[]).filter(x=>x!==id);p.variant='auto';api.changed();return true;}
   if(el.dataset.bPlanPOwned!==undefined){const a=p.prerequisites[Number(el.dataset.bPlanPOwned)];if(a)a.owned=el.checked;p.variant='auto';api.changed();return true;}
   if(el.dataset.bPlanActualBought!==undefined||el.dataset.bPlanActualRuns!==undefined)return true;
  }
  if(ev.type==='input'&&(el.id==='plan-actual'||el.id==='plan-actual-minutes'||el.id==='plan-actual-units'||el.id==='plan-actual-note'||el.dataset.bPlanActualRuns!==undefined))return true;
  if(ev.type==='click'){const button=el.closest('button');if(!button)return false;const d=button.dataset;
   if(d.bPlanImportCalcs){importFromCalcs(s);p.variant='auto';refresh('plan-capital');api.notify('Deine Zahlen aus „Meine Berechnungen“ wurden in den Plan kopiert. Du kannst sie hier ändern, ohne dort etwas zu ändern.');return true;}
   if(d.bPlanFree){p.goal.kind='purchase';p.goal.itemId='';p.goal.referencePrice=null;if(!p.goal.name)p.goal.name='Mein Ziel';refresh('plan-name');return true;}
   if(d.bPlanPriceReset){p.goal.price=p.goal.referencePrice;refresh('plan-price');return true;}
   if(d.bPlanMAdd){if(p.missions.length>=12){api.notify('Höchstens zwölf Missionen im Plan.');return true;}const id='m-'+Date.now().toString(36)+'-'+p.missions.length;p.missions.push({...B.copy(B.planMissionTemplate),id,name:'Mission '+(p.missions.length+1)});p.source='missions';p.variant='auto';refresh('plan-m-'+(p.missions.length-1)+'-name');return true;}
   if(d.bPlanMImport){const sel=$('plan-m-source');if(!sel)return true;const [kind,id]=sel.value.split(':'),a=(kind==='mine'?s.activities:sourceActivities).find(x=>x.id===id);if(!a)return true;if(p.missions.length>=12){api.notify('Höchstens zwölf Missionen im Plan.');return true;}
    p.missions.push({...B.copy(B.planMissionTemplate),id:'m-'+Date.now().toString(36)+'-'+p.missions.length,name:a.name,reward:a.reward??null,cost:a.cost??0,duration:a.duration??null,prep:a.prep??0,cooldown:a.cooldown??0,share:a.share??100,investment:a.investment??0,owned:a.owned===true});p.source='missions';p.variant='auto';refresh('plan-m-'+(p.missions.length-1)+'-name');api.notify('„'+a.name+'“ in den Plan kopiert.');return true;}
   if(d.bPlanMRemove!==undefined){const [gone]=p.missions.splice(Number(d.bPlanMRemove),1);if(gone){p.missions.forEach(m=>{m.requiresMissions=(m.requiresMissions||[]).filter(x=>x!==gone.id);});p.prerequisites.forEach(a=>{a.requires=(a.requires||[]).filter(x=>x!==gone.id);});p.locked=(p.locked||[]).filter(x=>x!==gone.id);}p.variant='auto';refresh('plan-m-source');return true;}
   if(d.bPlanPAdd){if(p.prerequisites.length>=20){api.notify('Höchstens zwanzig Käufe vor dem Ziel.');return true;}p.prerequisites.push({...B.copy(B.planPrereqTemplate),id:'p-'+Date.now().toString(36)+'-'+p.prerequisites.length,name:'Mein Kauf vor dem Ziel'});p.variant='auto';refresh('plan-p-'+(p.prerequisites.length-1)+'-name');return true;}
   if(d.bPlanPRemove!==undefined){const [a]=p.prerequisites.splice(Number(d.bPlanPRemove),1);if(a){p.missions.forEach(m=>{m.requires=m.requires.filter(x=>x!==a.id);});p.prerequisites.forEach(o=>{o.requires=(o.requires||[]).filter(x=>x!==a.id);});p.locked=(p.locked||[]).filter(x=>x!==a.id);}p.variant='auto';refresh('plan-prereq-search');return true;}
   if(d.bPlanPUp!==undefined||d.bPlanPDown!==undefined){const i=Number(d.bPlanPUp??d.bPlanPDown),j=i+(d.bPlanPUp!==undefined?-1:1);if(j>=0&&j<p.prerequisites.length)[p.prerequisites[i],p.prerequisites[j]]=[p.prerequisites[j],p.prerequisites[i]];refresh();return true;}
   if(d.bPlanVariant!==undefined){p.variant=d.bPlanVariant||'auto';api.changed();api.notify(p.variant==='auto'?'Zurück zum besten gefundenen Plan.':'Der Ablauf folgt jetzt diesem Ausweichplan.');return true;}
   if(d.bPlanAdopt){const obs=B.planObserved(s);if(obs&&obs.hourly!==null){p.situation.hourly=Math.round(obs.hourly);document.querySelectorAll('[data-field="plan.situation.hourly"]').forEach(i=>{i.value=p.situation.hourly;});api.changed();api.notify('Deine Einnahmen pro Stunde entsprechen jetzt dem, was du wirklich hattest: '+money(p.situation.hourly)+'.');}return true;}
   if(d.bPlanVsave){p.variants=p.variants||[];if(p.variants.length>=5){api.notify('Höchstens fünf Varianten: Entferne eine, um eine andere zu behalten.');return true;}p.variants.push(variantOf(s));api.changed();api.notify('Plan als Variante behalten. Du kannst jetzt etwas anderes ausprobieren.');return true;}
   if(d.bPlanVload){const k=(p.variants||[]).findIndex(v=>v.id===d.bPlanVload);if(k<0)return true;const v=p.variants[k],current=variantOf(s);VARIANT_KEYS.forEach(key=>{if(v[key]!==undefined)p[key]=B.copy(v[key]);});p.variants.splice(k,1,current);p.variant='auto';refresh('plan-capital');api.notify('Variante geladen. Der vorherige Plan ist an ihrer Stelle in deinen Varianten gespeichert: Nichts geht verloren.');return true;}
   if(d.bPlanVdel){p.variants=(p.variants||[]).filter(v=>v.id!==d.bPlanVdel);api.changed();api.notify('Variante entfernt.');return true;}
   if(d.bPlanLog){return logSession(s);}
   if(d.bPlanClear){p.log=[];p.playedMinutes=0;p.sessionsPlayed=0;api.changed();api.notify('Verlauf gelöscht. Dein aktuelles Geld bleibt erhalten.');return true;}
   if(d.bPlanExport){const r=B.evaluate('plan',s);const text=exportText(s,r);const blob=new Blob([text],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mon-business-plan-leonidakit.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);api.notify('Plan als lesbarer Text exportiert.');return true;}
  }
  return false;}
 /* v7.54 : « Reprendre mes chiffres » copie tout ce que les huit calculs ont pris en compte (revue v7.53, écart B1) : le sens du but,
    les dépenses par partie, le groupe, et pour chaque achat d’avant son coût d’usage par partie, son gain (écrit ou venu de
    « Ça vaut le coup ? »), ses dépendances et ce qu’il a de « déjà à moi ». Une option ou un frais inconnu reste inconnu : le prix
    de l’achat devient « à écrire », jamais 0. Chaque mission garde son nombre de joueurs. */
 function importFromCalcs(s){const p=s.plan,g=s.goal;p.situation.capital=g.capital;p.situation.reserve=g.reserve??0;p.situation.hourly=g.hourly;p.situation.dailyMinutes=g.dailyMinutes??s.session.usualMinutes??s.session.minutes;p.situation.daysPerWeek=s.session.daysPerWeek??7;
  p.situation.players=Number.isInteger(g.players)&&g.players>0?g.players:1;if(Number.isFinite(g.upkeepPerSession))p.situation.upkeepPerSession=g.upkeepPerSession;
  if(p.goal.kind==='amount'&&p.goal.target===null)p.goal.target=g.target;if(p.goal.kind==='amount'&&g.meaning&&B.GOAL_MEANINGS.includes(g.meaning))p.goal.meaning=g.meaning;
  const total=a=>a.price===null||a.extras===null||a.fees===null?null:a.price+(a.extras||0)+(a.fees||0);
  const boost=a=>{if(a.owned)return 0;if(a.incomeMode==='personal'&&Number.isFinite(a.boostHourly))return a.boostHourly;if(a.incomeMode==='roi'&&s.roi.key===a.key){const r=B.roi(s,sourceActivities);return ['new','improve'].includes(s.roi.mode)&&r.valid&&Number.isFinite(r.netHourly)?Math.max(0,r.netHourly):0;}return 0;};
  const usage=a=>{const u=B.usageOf(s,a,itemFor(a));return u&&u.perSession&&typeof u.perSession.v==='number'&&Number.isFinite(u.perSession.v)&&u.perSession.s!=='unconfirmed'?u.perSession.v:null;};
  const byKey={},existing=new Map(p.prerequisites.map(a=>[a.itemId||a.name,a]));
  s.order.keys.forEach(k=>{const a=B.asset(s,k);if(!a)return;const found=existing.get(a.itemId||a.name);if(found){byKey[k]=found.id;return;}if(p.prerequisites.length>=20)return;const id='p-'+Date.now().toString(36)+'-'+p.prerequisites.length;byKey[k]=id;p.prerequisites.push({...B.copy(B.planPrereqTemplate),id,name:a.name,itemId:a.itemId||'',referencePrice:a.referencePrice??null,price:total(a),boostHourly:boost(a),owned:a.owned===true,usagePerSession:usage(a),requires:[]});});
  s.order.keys.forEach(k=>{const a=B.asset(s,k),pr=p.prerequisites.find(x=>x.id===byKey[k]);if(!a||!pr)return;pr.requires=[...new Set([...(pr.requires||[]),...(a.requires||[]).map(r=>byKey[r]).filter(Boolean)])];});
  const names=new Set(p.missions.map(m=>m.name));s.activities.filter(a=>Number.isFinite(a.reward)&&Number.isFinite(a.duration)&&s.session.enabled.includes(a.id)).forEach(a=>{if(names.has(a.name)||p.missions.length>=12)return;p.missions.push({...B.copy(B.planMissionTemplate),id:'m-'+Date.now().toString(36)+'-'+p.missions.length,name:a.name,reward:a.reward,cost:a.cost??0,duration:a.duration,prep:a.prep??0,cooldown:a.cooldown??0,share:a.share??100,investment:a.investment??0,owned:a.owned===true,players:Number.isInteger(a.players)&&a.players>0?a.players:1,requires:(a.requiresPurchaseIds||[]).map(id=>{const k=s.assets.find(x=>x.itemId===id)?.key;return k?byKey[k]:null;}).filter(Boolean)});});
  if(s.model==='cycles'&&p.missions.length)p.source='missions';}
 function logSession(s){const p=s.plan,g=s.plan.goal,fb=$('plan-log-feedback');
  const cap=parse($('plan-actual')?.value),mins=parse($('plan-actual-minutes')?.value);
  if(cap===null||cap<0||cap>1e12){if(fb)fb.textContent='Gib ein, was du jetzt hast, als Zahl (zum Beispiel 350.000).';$('plan-actual')?.focus();return true;}
  if(mins===null||mins<0||mins>1e5){if(fb)fb.textContent='Gib die gespielte Zeit in Minuten ein (zum Beispiel 60).';$('plan-actual-minutes')?.focus();return true;}
  let unitsNow=null;if(g.kind==='unlock'){const v=parse($('plan-actual-units')?.value);if(v!==null){if(v<0||v>1e12){if(fb)fb.textContent='Gib deine '+g.unitLabel+' als Zahl ein.';$('plan-actual-units')?.focus();return true;}unitsNow=v;}}
  const runs={};document.querySelectorAll('[data-b-plan-actual-runs]').forEach(el=>{const v=parse(el.value);if(v!==null&&v>=0)runs[el.dataset.bPlanActualRuns]=Math.round(v);});
  const bought=[...document.querySelectorAll('[data-b-plan-actual-bought]:checked')].map(el=>el.dataset.bPlanActualBought).filter(id=>p.prerequisites.some(a=>a.id===id));
  const note=String($('plan-actual-note')?.value||'').slice(0,300);
  // v7.49 : une même mise à jour envoyée deux fois n’est comptée qu’une fois (identifiant tiré de son contenu et du point de départ).
  const logId=B.planLogId({prev:p.situation.capital,cap,mins,runs,bought,units:unitsNow,count:p.log.length?p.log[p.log.length-1].id||p.log.length:0});
  if(p.log.some(e=>e.id===logId)){if(fb)fb.textContent='Diese Session ist schon gespeichert: Nichts wird doppelt gezählt.';return true;}
  const before=B.evaluate('plan',s),curve=before.valid?B.planCurve(before):[],next=B.planNextSession(before);
  const at=E.planCashAt({points:curve.map(pt=>({hours:pt.hours,cash:pt.cash})),hours:((p.playedMinutes||0)+mins)/60}),forecast=at&&at.valid?at.cash:null;
  const spent=bought.reduce((a,id)=>a+(p.prerequisites.find(x=>x.id===id)?.price||0),0),gain=Number.isFinite(p.situation.capital)?cap-p.situation.capital+spent:null,plannedGain=next?next.gain:null;
  const unitsGain=unitsNow!==null&&Number.isFinite(g.currentUnits)?unitsNow-g.currentUnits:null;
  p.situation.capital=cap;if(unitsNow!==null)g.currentUnits=unitsNow;bought.forEach(id=>{const a=p.prerequisites.find(x=>x.id===id);if(a)a.owned=true;});
  p.playedMinutes=(p.playedMinutes||0)+mins;p.sessionsPlayed=(p.sessionsPlayed||0)+1;
  p.log.push({id:logId,at:new Date().toISOString(),capital:cap,minutes:p.playedMinutes,forecast,note,units:unitsNow,unitsGain,gain,plannedGain,sessionMinutes:mins,runs,purchases:bought});if(p.log.length>60)p.log=p.log.slice(-60);
  document.querySelectorAll('[data-field="plan.situation.capital"]').forEach(i=>{i.value=cap;});if(unitsNow!==null)document.querySelectorAll('[data-field="plan.goal.currentUnits"]').forEach(i=>{i.value=unitsNow;});
  if(bought.length)refresh('plan-actual');else api.changed();
  const gap=plannedGain===null||gain===null?null:gain-plannedGain;
  /* v7.51 (lot 4) : un achat déclaré fait range le véhicule ou l’arme de la fiche dans son carnet (garage, arsenal). Le
     journal des réalisations (carnets-core.js) tient l’identifiant de la partie : enregistrer deux fois ne range rien deux
     fois. Une prévision du plan, elle, ne coche jamais rien et ne retire jamais rien. */
  const ranged=[];if(bought.length&&global.LKCarnets){try{const K=global.LKCarnets.create({storage:global.localStorage});bought.forEach(id=>{const a=p.prerequisites.find(x=>x.id===id),item=a&&a.itemId?itemFor({itemId:a.itemId}):null,fam=item?({vehicle:'vehicules',weapon:'armes'})[item.type]:null;if(!fam||!/^[a-z0-9][a-z0-9-]{0,99}$/.test(item.id))return;const r=K.applyEvent('plan:'+logId+':'+id,[{type:'own',famille:fam,id:item.id}]);if(r&&r.applied)ranged.push(item.name+(fam==='armes'?' (Mein Arsenal)':' (Meine Garage)'));});}catch(e){/* stockage indisponible : le plan reste juste, rien n’est annoncé */}}
  api.notify('Plan neu berechnet ab '+money(cap)+'.'+(gap===null?'':gap>=0?' Du hast '+money(gap)+' mehr verdient als geplant.':' Du hast '+money(-gap)+' weniger verdient als geplant: Sieh dir die Alternativen zum Plan an.')+(ranged.length?' In deinen Trackern abgelegt: '+ranged.join(', ')+'.':''));return true;}
 /* ---------- Fiche complète (enregistrement) : le plan entier, lisible comme un document ---------- */
 function sheet(cfg,at){const s=cfg,p=s.plan,g=p.goal,si=p.situation,r=B.evaluate('plan',s),base=at||new Date().toISOString(),date=new Date(base),dateText=Number.isFinite(date.getTime())?date.toLocaleDateString('de-DE',{day:'numeric',month:'long',year:'numeric'}):'—';
  let html='<article class="b-sheet"><div class="b-sheet-head"><p class="calc-kicker">LEONIDAKIT · BUSINESSPLAN-BLATT</p><h2 id="calc-sheet-title">'+esc(s.name||'Mein Plan')+'</h2><p class="b-doc-meta">'+esc('Ziel: '+goalName(s)+' · gespeichert am '+dateText)+'</p></div>';
  if(!r.valid){html+='<p class="calc-warning">'+esc('Plan beim Speichern nicht berechenbar: '+r.reason)+'</p></article>';return html;}
  const D=sessionLabel(s),dpw=r.input.daysPerWeek,reached=r.continuous?r.totalMinutes===0:r.totalSessions===0;
  html+='<section><h3>Kurz gesagt</h3><div class="b-tiles">'+(isFlow(r)?[['Spielzeit',hours(r.totalMinutes/60)]]:[['Sessions von '+D,String(r.totalSessions)],['Tage',String(r.days)]]).concat([['Start',money(r.startCash)],['Am Ende',money(r.finalCash)]]).map(([l,v])=>'<span><small>'+esc(l)+'</small><b>'+v+'</b></span>').join('')+'</div><p>'+esc(reached?'Das Ziel ist mit dem, was du hast, schon erreichbar.':isFlow(r)?'Du brauchst '+timeText(r)+', Schritt um Schritt (ohne Kalender).'+lowText(r):'Du brauchst '+plural(r.totalSessions,' Session',' Sessions')+' von '+D+', '+dpw+(E.plural(dpw)?' Tage':' Tag')+' pro Woche: etwa am '+planDate(r.days,base)+' bei Start am '+dateText+'.')+'</p></section>';
  html+='<section><h3>Das Ziel</h3><p>'+esc(g.kind==='purchase'?(g.name||'Mein Kauf')+' — '+money(g.price)+(g.boostHourly>0?', er bringt '+money(g.boostHourly)+' mehr pro Stunde ein, sobald er gekauft ist':', Kauf nur zum Spaß'):g.kind==='amount'?(g.meaning==='held'?'Kontostand von '+money(g.target)+' insgesamt, beiseitegelegtes Geld inklusive':g.meaning==='cumulative'?'Verdiene '+money(g.target)+' ab jetzt':'Kontostand von '+money(g.target)+' in der Tasche, plus das beiseitegelegte Geld'):'Freischaltung '+(g.name||'mein Ziel')+': erreiche '+nf.format(g.targetUnits)+' '+g.unitLabel+' (schon '+nf.format(g.currentUnits||0)+')'+(g.alsoPrice>0?', danach kostet es '+money(g.alsoPrice):''))+'.</p></section>';
  html+='<section><h3>Wo ich stehe</h3><ul class="b-sheet-list"><li>Geld in der Tasche: <b>'+money(si.capital)+'</b></li><li>Zurückgelegt: <b>'+money(si.reserve)+'</b>'+(r.input.reserve!==(si.reserve??0)?' (Auswahl: „so schnell es geht“)':'')+'</li><li>Eine Session: <b>'+D+'</b>, '+dpw+(E.plural(dpw)?' Tage':' Tag')+' pro Woche</li>'+(si.upkeepPerSession>0?'<li>Ausgaben pro Session: <b>'+money(si.upkeepPerSession)+'</b></li>':'')+(p.source==='hourly'?'<li>Ich verdiene ungefähr <b>'+money(si.hourly)+' pro Stunde</b></li>':'')+'</ul></section>';
  if(p.source==='missions'&&p.missions.length)html+='<section><h3>Meine Missionen</h3>'+table([['Mission','Belohnung','Kosten','Dauer','Wartezeit','Pro Mission','Pro Stunde'+(g.kind==='unlock'?'':'')].concat(g.kind==='unlock'?[g.unitLabel]:[]),...p.missions.map(m=>{const a=E.activity(m);return [m.name+(m.requires.length?' (nach: '+m.requires.map(id=>p.prerequisites.find(x=>x.id===id)?.name||id).join(', ')+')':''),money(m.reward),money(m.cost),hours(((m.duration||0)+(m.prep||0))/60),m.cooldown?hours(m.cooldown/60):'—',a.valid?money(a.net):'—',a.valid?money(a.hourly):'—'].concat(g.kind==='unlock'?[nf.format(m.units||0)]:[]);})],'Deine Zahlen, Kosten vorher bezahlt, Belohnung am Ende',true)+'</section>';
  html+='<section><h3>Der Ablauf, der Reihe nach</h3>'+(isFlow(r)?visual.chain(routeSteps(s,r,{all:true,max:30}),{title:'Der Weg, der Reihe nach'}):phaseCards(s,r,base)+routeBlock(s,r))+'</section>';
  if(r.purchases.length)html+='<section><h3>Meine Käufe und Investitionen</h3>'+table([['Kauf','Preis','Wann','Was er danach einbringt'],...r.purchases.map(x=>[x.name,money(x.price),x.owned&&!x.atSession?'schon im Besitz':x.atSession&&isFlow(r)?'unterwegs':x.atSession?'nach Session '+x.atSession+' · Tag '+dayOf(x.atSession,dpw)+' (etwa am '+planDate(dayOf(x.atSession,dpw),base)+')':'nicht in diesem Plan',x.boostHourly>0?'+'+money(x.boostHourly)+' pro Stunde'+(x.price>0?' · wieder eingespielt nach '+hours(x.price/x.boostHourly)+' Spielzeit':''):'nichts zusätzlich'])],'Jeder Kauf wird bezahlt, sobald das Geld reicht, ohne die Rücklage anzutasten',true)+'</section>';
  if(!reached){const alt=B.planAlternatives(s,r),curId=r.variant==='auto'?'all':r.variant,ok=alt.valid?alt.plans.filter(x=>x.valid).sort((a,b)=>(a.id===curId?-1:b.id===curId?1:0)):[];if(ok.length>1)html+='<section><h3>Wenn es nicht wie geplant läuft</h3><ol class="b-sheet-alts">'+ok.slice(0,4).map((x,i)=>'<li><b>Plan '+String.fromCharCode(65+i)+' · '+esc(x.label)+'</b>: '+(isFlow(r)?hours((x.totalMinutes||0)/60)+' Spielzeit':plural(x.totalSessions,' Session',' Sessions')+', '+plural(x.days,' Tag',' Tage'))+', '+money(x.finalCash)+' am Ende. '+esc(programSummary(alt.results[x.id]))+'</li>').join('')+'</ol></section>';}
  if(p.log.length)html+='<section><h3>Was ich wirklich gemacht habe</h3>'+table([['Date','Insgesamt gespielt','Geplant (Session)','Tatsächlich (Session)','Ich hatte','Note'],...p.log.slice().reverse().map(e=>{const d=new Date(e.at);return [Number.isFinite(d.getTime())?d.toLocaleDateString('de-DE'):'—',hours(e.minutes/60),e.plannedGain===null?'—':'+'+money(e.plannedGain),e.gain===null?'—':'+'+money(e.gain),money(e.capital),e.note||'—'];})],'Meine Aktualisierungen',true)+'</section>';
  html+='<div class="b-sheet-foot"><p>Das sind deine Zahlen, nicht die des Spiels: Kein Preis, keine Einnahme und keine Mechanik von GTA VI ist versprochen. Neu berechnen auf leonidakit.com/de/calculateurs.html?tool=plan.</p></div></article>';return html;}
 function shortSummary(s){const r=B.evaluate('plan',s);const name=goalName(s);if(!r.valid)return 'Ziel: '+name+' · Plan unvollständig ('+r.reason+')';return 'Ziel: '+name+' · '+(r.totalSessions===0||(r.continuous&&r.totalMinutes===0)?'schon möglich':r.continuous?timeText(r):plural(r.totalSessions,' Session',' Sessions')+' von '+sessionLabel(s)+' · '+plural(r.days,' Tag',' Tage'))+' · '+(s.plan.source==='missions'?plural(s.plan.missions.length,' Mission',' Missionen'):money(s.plan.situation.hourly)+'/h')+(r.purchases.some(x=>x.atSession)?' · '+plural(r.purchases.filter(x=>x.atSession).length,' Kauf',' Käufe')+' vor dem Ziel':'');}
 function exportText(s,r){const p=s.plan,g=p.goal,si=p.situation;const lines=['MEIN BUSINESSPLAN — Leonidakit ('+new Date().toLocaleDateString('de-DE')+')','Ziel: '+goalName(s),'Start: '+money(si.capital)+' in der Tasche, '+money(si.reserve)+' zurückgelegt, Sessions von '+sessionLabel(s)+', '+(si.daysPerWeek??7)+' Tage/Woche'+(p.source==='hourly'?', '+money(si.hourly)+' pro Stunde':', '+p.missions.length+(E.plural(p.missions.length)?' Missionen':' Mission')),''];
  if(!r.valid){lines.push('Plan nicht berechenbar: '+r.reason);return lines.join('\n');}
  lines.push(r.totalSessions===0||(r.continuous&&r.totalMinutes===0)?'Das Ziel ist schon erreichbar.':r.continuous?'Weg mit '+timeText(r)+', ohne Kalender. Am Ende: '+money(r.finalCash)+'.'+lowText(r):r.totalSessions+' Sessions, '+r.days+' Tage (etwa am '+planDate(r.days)+'). Am Ende: '+money(r.finalCash)+'.','','ABLAUF, DER REIHE NACH');
  if(r.continuous)(r.route||[]).slice(0,80).forEach((x,i)=>lines.push((i+1)+'. '+hours(x.start/60)+': '+(x.type==='acquire'?'kaufe „'+x.name+'“ (−'+money(x.spend)+')':x.type==='unlock'?'„'+x.name+'“, nur einmal':'„'+x.name+'“ ×'+x.runs+' (+'+money(x.receive-x.spend)+' net)')+' — du hast '+money(x.cashAfter)));
  else r.phases.forEach((ph,i)=>lines.push((i+1)+'. '+(ph.count===1?'Session '+ph.from:'Sessions '+ph.from+' bis '+ph.to)+': '+(ph.steps.length?ph.steps.map(st=>st.name+' ×'+st.runs).join(', '):'deine Einnahmen pro Stunde')+' — +'+money(ph.gain)+' pro Session, von '+money(ph.cashBefore)+' auf '+money(ph.cashAfter)+(ph.purchasesAfter.length?' — dann kaufe '+ph.purchasesAfter.join(', '):'')));
  if(r.totalSessions>0||(r.continuous&&r.totalMinutes>0))lines.push((r.continuous?'★ Nach '+timeText(r):(r.phases.length+1)+'. Nach Session '+r.totalSessions)+': '+(g.kind==='purchase'?'kaufe '+(g.name||'dein Ziel'):g.kind==='unlock'?'Freischaltung von '+(g.name||'dein Ziel'):'du hast '+money(g.target))+'.');
  if(p.log.length){lines.push('','FORTSCHRITT');p.log.forEach(e=>lines.push(new Date(e.at).toLocaleDateString('de-DE')+' · gespielt '+hours(e.minutes/60)+' · geplant '+(e.plannedGain===null?'—':'+'+money(e.plannedGain))+' · tatsächlich '+(e.gain===null?'—':'+'+money(e.gain))+' · ich hatte '+money(e.capital)));}
  /* v7.54 : les hypothèses du plan sont écrites dans l’export (sens du but, groupe, dépenses par partie, simulations, priorité). */
  const MEAN={held:'die Summe, die du insgesamt hast',available:'die Summe, die nach dem beiseitegelegten Geld frei bleibt',cumulative:'die ab jetzt verdiente Summe'},PRIO={balanced:'ein gutes Gleichgewicht, beiseitegelegtes Geld bleibt unangetastet',fast:'so schnell es geht, beiseitegelegtes Geld nutzbar',safe:'Sicherheit, beiseitegelegtes Geld nie angetastet',cheap:'am billigsten auf dem ganzen Weg, beiseitegelegtes Geld bleibt unangetastet'};
  const hyp=['ANNAHMEN',g.kind==='amount'?'Kontostand von '+money(g.target)+', das heißt: '+(MEAN[g.meaning]||MEAN.available)+'.':'Ziel: '+(g.name||'ein Kauf')+(g.price!==null&&g.price!==undefined?' bis '+money(g.price)+' (dein Preis)':''),'Priorität: '+(PRIO[p.priority]||PRIO.balanced)+'.','Wir sind '+(si.players??1)+(E.plural(si.players??1)?' Spieler':' Spieler')+'.',(si.upkeepPerSession||0)>0?'Ausgaben pro Session: '+money(si.upkeepPerSession)+'.':'Keine Ausgaben pro Session eingetragen.',(r.input&&r.input.ammoPerAttempt)?'Simulierte Munition: '+money(r.input.ammoPerAttempt)+' pro Versuch (Simulation, keine Spieldaten).':'Keine simulierte Mechanik.'];
  p.prerequisites.filter(a=>!a.owned&&(a.usagePerSession||0)>0).forEach(a=>hyp.push('„'+a.name+'“ kostet '+money(a.usagePerSession)+' pro Session (deine Zahl).'));
  if(r.input&&r.input.excludedMissions&&r.input.excludedMissions.length)hyp.push('Ausgeschlossen (zu viele Spieler): '+r.input.excludedMissions.map(m=>'„'+m.name+'“').join(', ')+'.');
  if(r.note)hyp.push(r.note);
  lines.push('',...hyp,'','Das sind deine Zahlen, nicht die des Spiels. Berechnet auf leonidakit.com/de/calculateurs.html?tool=plan');return lines.join('\n');}
 return {markup,render,event,sheet,shortSummary,exportText,goalName,STRATEGY_LABEL};
}
global.LKCalcPlan={create};
})(window);
