/* ============================================================
   LEONIDAKIT — armes : source de vérité
   Chaque arme porte son niveau de certitude :
     st: 'officiel'  nom publié par Rockstar dans un support officiel
     st: 'vu'        visible dans un média officiel, nom non communiqué
   Aucune donnée issue de fuites.
   Images : visuels officiels Rockstar listés dans outils/armes-medias.json (registre outils/medias-officiels.json).
   Fiches et hub régénérés par node outils/gen-armes.cjs ; les textes sont écrits ici, pas dans les fiches.
   ============================================================ */
window.LK_ARMES = [
{"id":"girardi-es9","nom":"Girardi ES9","fr":"Pistolet de Jason","cat":"pistolet","slot":"poing","st":"officiel","src":"Matériel de précommande de l’édition Ultimate","insp":"Beretta 92FS","mun":"Munitions de pistolet","portee":"Courte à moyenne","ctx":"Le pistolet personnel de Jason, nommé par Rockstar dans la présentation de l’édition Ultimate, qui en propose une version gravée. C’est l’arme de poing la plus visible des supports officiels.","perso":"jason","ue":true},
{"id":"klose-k17","nom":"Klose K17","fr":"Pistolet de Lucia","cat":"pistolet","slot":"poing","st":"officiel","src":"Matériel de précommande de l’édition Ultimate","insp":"Glock 17 / SIG P320","mun":"Munitions de pistolet","portee":"Courte à moyenne","ctx":"Le pistolet personnel de Lucia, nommé par Rockstar avec une version gravée de roses dans l’édition Ultimate. Pistolet moderne à carcasse polymère et rail accessoire.","perso":"lucia","ue":true},
{"id":"nipper-38","nom":"Nipper .38","fr":"Pistolet compact","cat":"pistolet","slot":"poing","st":"officiel","src":"Nom gravé sur l’arme, jaquette officielle","insp":"Bersa Thunder 380","mun":"Munitions de pistolet","portee":"Courte","ctx":"Le petit pistolet que Lucia tient sur la jaquette officielle. Son nom est lisible sur la culasse : c’est l’une des rares armes dont le nom vient directement d’un visuel de Rockstar.","perso":"lucia"},
{"id":"hawk-little-morgan","nom":"Hawk & Little Morgan","fr":"Revolvers gravés","cat":"pistolet","slot":"poing","st":"officiel","src":"Matériel de précommande de l’édition Ultimate","insp":"Smith & Wesson 629","mun":"Munitions de pistolet","portee":"Moyenne","ctx":"Une paire de revolvers gravés, l’un pour Jason, l’autre pour Lucia, décrits par Rockstar comme inspirés du domaine Vercetti de Vice City. Crosses à palmiers, gravures nominatives et lunette haute performance.","ue":true},
{"id":"pistolet-custom","nom":"Pistolet personnalisé","fr":null,"cat":"pistolet","slot":"poing","st":"vu","src":"Second trailer","insp":"Colt 1911","mun":"Munitions de pistolet","portee":"Courte à moyenne","ctx":"Pistolet à habillage personnalisé, visible lors d’une scène d’intérieur. Les finitions apparentes laissent penser que la personnalisation d’armes est de retour."},
{"id":"pistolet-auto","nom":"Pistolet à sélecteur","fr":null,"cat":"pistolet","slot":"poing","st":"vu","src":"Extended Look du 27 août 2026","insp":"Glock avec switch","mun":"Munitions de pistolet","portee":"Courte","ctx":"Pistolet équipé d’un sélecteur de tir à l’arrière de la culasse, un détail visible dans les séquences de gameplay. Il transformerait un pistolet semi-automatique en arme à rafales."},
{"id":"mustang-357","nom":"Mustang .357","fr":"Revolver des motards","cat":"pistolet","slot":"poing","st":"officiel","src":"Nom gravé sur l’arme, capture officielle d’Ambrosia","insp":"Colt Python","mun":"Munitions de pistolet","portee":"Moyenne","ctx":"Le gros revolver qu’une motarde brandit sur la troisième capture d’Ambrosia, pendue au cou d’un membre du gang à l’écusson Enforcer. Le nom Mustang .357 est gravé sur l’arme : c’est la cinquième arme dont le nom vient directement d’un visuel de Rockstar. Canon ventilé et gros barillet de Colt Python, la magnum de cinéma, ici aux mains des bikers de l’arrière-pays."},
{"id":"fusil-double","nom":"Fusil à canon double","fr":null,"cat":"pompe","slot":"longue","st":"vu","src":"Second trailer","insp":"Fusil de chasse juxtaposé","mun":"Cartouches","portee":"Très courte","ctx":"Fusil à deux canons juxtaposés, associé aux zones rurales et aux marécages dans les supports officiels. Le barbu au premier plan de la sixième capture de Grassrivers en porte un sur l’épaule, garnitures gravées et crosse en bois, devant l’alligator suspendu de son atelier."},
{"id":"fusil-pompe","nom":"Fusil à pompe","fr":null,"cat":"pompe","slot":"longue","st":"vu","src":"Premier trailer","insp":"Mossberg 590","mun":"Cartouches","portee":"Très courte","ctx":"Fusil à pompe classique, aperçu lors de scènes d’affrontement. Arme de courte portée typique de la série."},
{"id":"micro-smg","nom":"PM à motif tropical","fr":null,"cat":"pm","slot":"poing","st":"vu","src":"Visuel de l’édition Ultimate","insp":"Mini Uzi","mun":"Munitions de pistolet","portee":"Courte","ctx":"Pistolet-mitrailleur compact à motif tropical, montré dans le visuel de l’édition Ultimate sans que Rockstar en publie le nom. Utilisable d’une main, dans la tradition des armes de drive-by.","ue":true},
{"id":"smg-compact","nom":"PM compact","fr":null,"cat":"pm","slot":"poing","st":"vu","src":"Extended Look du 27 août 2026","insp":"Škorpion","mun":"Munitions de pistolet","portee":"Courte","ctx":"Arme automatique très courte, aperçue dans une scène d’action rapprochée."},
{"id":"smg","nom":"Pistolet-mitrailleur","fr":null,"cat":"pm","slot":"longue","st":"vu","src":"Second trailer","insp":"H&K MP5","mun":"Munitions de pistolet","portee":"Courte à moyenne","ctx":"Pistolet-mitrailleur tenu à deux mains par Jason et Lucia pendant le braquage du second trailer. La version de Jason porte un viseur point rouge."},
{"id":"pm-tactique","nom":"PM à crosse rabattable","fr":null,"cat":"pm","slot":"longue","st":"vu","src":"Visuel de l’édition Ultimate","insp":null,"mun":"Munitions de pistolet","portee":"Courte à moyenne","ctx":"Posé sur la banquette d’une voiture entre les liasses de billets, avec un pistolet assorti, dans le visuel Weapon Pattern du Vintage Vice City Pack. Crosse repliée, chargeur droit devant la poignée, finition turquoise à palmiers : un pistolet-mitrailleur moderne et compact, distinct du petit PM à motif tropical que Jason tient sur les visuels de tenues. Son nom n’est pas communiqué.","ue":true,"fam":"Pistolet-mitrailleur moderne à crosse repliable"},
{"id":"carabine","nom":"Carabine","fr":null,"cat":"assaut","slot":"longue","st":"vu","src":"Second trailer","insp":"AR-15 / M4","mun":"Munitions de fusil","portee":"Moyenne à longue","ctx":"Carabine moderne à crosse télescopique, visible dans plusieurs séquences d’action."},
{"id":"fusil-assaut","nom":"Fusil d’assaut","fr":null,"cat":"assaut","slot":"longue","st":"vu","src":"Premier trailer","insp":"AK","mun":"Munitions de fusil","portee":"Moyenne à longue","ctx":"Fusil d’assaut au chargeur courbe caractéristique, aperçu dans les mains d’antagonistes."},
{"id":"fusil-precision","nom":"Fusil à verrou","fr":null,"cat":"precision","slot":"longue","st":"vu","src":"Extended Look du 27 août 2026","insp":"Remington 700","mun":"Munitions de fusil","portee":"Longue","ctx":"Fusil à verrou équipé d’une lunette, aperçu dans un contexte de tir à distance."},
{"id":"fusil-semi-auto","nom":"Fusil semi-automatique","fr":null,"cat":"precision","slot":"longue","st":"vu","src":"Captures officielles","insp":"Springfield M1A","mun":"Munitions de fusil","portee":"Longue","ctx":"Le long fusil à crosse en bois et lunette que tient l’un des trois hommes posant devant leur hydroglisseur, sur la première capture de Grassrivers. Boîtier allongé et crosse traditionnelle rappellent le M1A, le dérivé civil du M14 : une arme de chasse et de tir à longue distance, plus rustique que le fusil à verrou, et parfaitement à sa place dans les marais."},
{"id":"mitrailleuse","nom":"Mitrailleuse de combat","fr":null,"cat":"mitrailleuse","slot":"longue","st":"vu","src":"Extended Look du 27 août 2026","insp":"M249 SAW","mun":"Munitions lourdes","portee":"Moyenne","ctx":"Arme d’appui à chargement par bande, la plus lourde aperçue à ce jour."},
{"id":"batte","nom":"Batte de baseball","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Premier trailer","insp":null,"mun":null,"portee":"Corps à corps","ctx":"Batte de baseball, arme de mêlée récurrente de la série. Les animations de corps à corps ont été refaites en capture de mouvement.","fam":"Batte de baseball en aluminium"},
{"id":"couteau-cran","nom":"Couteau à cran d’arrêt","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Visuel de l’édition Ultimate","insp":null,"mun":null,"portee":"Corps à corps","ctx":"Couteau à lame rétractable, visible dans le visuel de l’édition Ultimate aux côtés des revolvers gravés.","ue":true,"fam":"Couteau pliant à cran d’arrêt"},
{"id":"club-golf","nom":"Club de golf","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Second trailer","insp":null,"mun":null,"portee":"Corps à corps","ctx":"Club de golf utilisable comme arme de mêlée, dans la lignée des objets du quotidien détournés.","fam":"Fer de golf"},
{"id":"marteau","nom":"Marteau","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Extended Look du 27 août 2026","insp":null,"mun":null,"portee":"Corps à corps","ctx":"Marteau de chantier, aperçu comme arme improvisée.","fam":"Marteau de charpentier"},
{"id":"queue-billard","nom":"Queue de billard","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Extended Look du 27 août 2026","insp":null,"mun":null,"portee":"Corps à corps","ctx":"Queue de billard, arme de mêlée liée aux lieux de loisirs de Leonida.","fam":"Queue de billard américain"},
{"id":"molotov","nom":"Cocktail Molotov","fr":null,"cat":"projectile","slot":"poing","st":"vu","src":"Second trailer","insp":null,"mun":null,"portee":"Jet","ctx":"Cocktail Molotov, projectile incendiaire classique de la série.","fam":"Bouteille incendiaire improvisée"},
{"id":"fumigene","nom":"Grenade fumigène","fr":null,"cat":"projectile","slot":"poing","st":"vu","src":"Extended Look du 27 août 2026","insp":null,"mun":null,"portee":"Jet","ctx":"Grenade fumigène, projectile non létal servant à masquer un déplacement.","fam":"Grenade fumigène à main"},
{"id":"harpon","nom":"Fusil-harpon","fr":null,"cat":"speciale","slot":"longue","st":"vu","src":"Extended Look du 27 août 2026","insp":null,"mun":"Harpons","portee":"Courte, sous l’eau","ctx":"Fusil-harpon, arme sous-marine. C’est une nouveauté pour la série : elle accompagne les zones immergées explorables.","fam":"Fusil-harpon sous-marin à sandows"},
{"id":"lance-grenades","nom":"Lance-grenades","fr":null,"cat":"speciale","slot":"longue","st":"vu","src":"Second trailer","insp":"Milkor MGL","mun":"Grenades","portee":"Moyenne","ctx":"Lucia le tient pendant la poursuite avec la police du second trailer, au moment où un véhicule explose derrière elle. Le gros barillet qui dépasse sous le canon ne laisse aucun doute : un lance-grenades à barillet de type Milkor MGL, le retour de l’arme lourde la plus spectaculaire de la série."}
];
window.LK_ARMES_CATS = {
  pistolet:'Pistolets', pompe:'Fusils à pompe', pm:'Pistolets-mitrailleurs', assaut:"Fusils d’assaut",
  precision:'Précision', mitrailleuse:'Mitrailleuses', melee:'Mêlée', projectile:'Projectiles', speciale:'Spéciales'
};
