/* Mon business plan (v7.33) : de l'objectif au programme exécutable.
   Tout chiffre vient du moteur (LKCalcEngine) via le scénario partagé (LKCalcScenario) ; ce fichier
   ne fait que présenter : point de départ, stratégie recommandée et alternatives, étapes avec dépenses,
   gains, solde et avancement, prochaine partie, échéance, seuils, suivi du réel et recalcul. */
(function(global){'use strict';
const B=global.LKCalcScenario;
function create(env){
 const {esc,money,hours,field,stats,warning,btn,select,table,lookup,itemFor,state,sourceActivities,visual,api,decision,problem}=env;
 const E=global.LKCalcEngine,nf=new Intl.NumberFormat('fr-FR',{maximumFractionDigits:2}),$=id=>document.getElementById(id);
 const STRATEGY_LABEL={auto:'Laisser le calculateur choisir',asIs:'Dans l’ordre que j’ai donné',byPayback:'Ce qui rapporte le plus vite d’abord',cheapFirst:'Le moins cher d’abord',skipNoBoost:'Seulement les achats qui rapportent',direct:'Directement vers mon but, sans achat avant',useReserve:'En touchant à l’argent mis de côté'};
 function planDate(days){const d=new Date();d.setDate(d.getDate()+days);return d.toLocaleDateString('fr-FR',{day:'numeric',month:'long'});}
 const pct=v=>v===null||!Number.isFinite(v)?'—':nf.format(Math.round(v*10)/10)+' %';
 /* Formulaire (4 questions) */
 function markup(ctx){const s=state(),p=s.plan,a=p.kind==='purchase'?lookup(p.key):null,i=a?s.assets.indexOf(a):-1,acts=B.activities(s,sourceActivities),{combobox,selectedCard,priceField,step}=ctx;
  const goalBlock=p.kind==='purchase'?combobox('plan-search','Je veux acheter (cherche dans le site)','plan')+btn('Écrire un achat libre','data-b-plan-free="1"')+'<div id="plan-selection">'+(a?selectedCard(a)+(!a.itemId?field('assets.'+i+'.name','Nom de mon achat',a.name,{type:'text',id:'plan-name'}):'')+priceField(a.key,'plan-price'):warning('Choisis ce que tu veux acheter, ou écris un achat libre.'))+'</div>':field('plan.target','Je veux avoir ($)',p.target===null?s.goal.target:p.target,{id:'plan-target',hint:'La somme que tu veux avoir en poche, en plus de ce que tu gardes de côté.'});
  const owned=s.assets.filter(x=>x.owned).map(x=>x.name);
  const form='<div class="calc-fields calc-steps">'
   +step(1,'Quel est ton but ?',select('plan.kind','Mon but',[['purchase','Acheter quelque chose'],['amount','Avoir une somme d’argent']],p.kind)+goalBlock,'Le but décide de tout le reste : un achat a un prix, une somme se gagne petit à petit.')
   +step(2,'Où en es-tu ?','<div class="calc-fields">'+field('goal.capital','J’ai déjà ($)',s.goal.capital,{id:'plan-capital'})+field('goal.reserve','Argent que je garde de côté ($)',s.goal.reserve,{id:'plan-reserve'})+select('plan.activity','Comment je gagne mon argent',[['','Je gagne à peu près ce chiffre par heure'],...acts.map(x=>[x.id,x.name+(x.status==='manual'?' · mes chiffres':' · du site')])],p.activity)+(p.activity?'<p class="calc-note wide">Gain par heure de cette activité : <b>'+money(B.planBaseHourly(s,sourceActivities))+'</b> (frais, préparation et attente comptés). Change ses chiffres dans Mes activités.</p>':field('goal.hourly','Je gagne à peu près ($ par heure de jeu)',s.goal.hourly,{id:'plan-hourly',hint:'Ce qu’il te reste une fois tes frais payés. Ton chiffre à toi.'}))+field('goal.dailyMinutes','Je joue par jour (minutes)',s.goal.dailyMinutes,{id:'plan-daily',max:1440})+field('session.daysPerWeek','Combien de jours par semaine ?',s.session.daysPerWeek,{id:'plan-days',min:1,max:7,integer:true})+'</div>'+(owned.length?'<p class="calc-note">Tu possèdes déjà : '+esc(owned.join(', '))+'. Ces achats ne sont pas recomptés.</p>':''),'Avec ce que tu as et ce que tu gagnes, on calcule le temps de jeu ; avec ton rythme, on le traduit en jours.')
   +step(3,'Avant et après','<label class="calc-check"><input type="checkbox" data-b-plan-prereq="1" '+(p.usePrerequisites?'checked':'')+'> Compter mes achats de « Quoi acheter d’abord ? » comme des étapes avant mon but</label>'+(p.usePrerequisites&&s.order.keys.filter(k=>k!==p.key).length?'<p class="calc-note">Avant : '+esc(s.order.keys.filter(k=>k!==p.key).map(k=>lookup(k)?.name).filter(Boolean).join(', '))+'</p>':'<p class="calc-note">Aucun achat avant pour l’instant.'+(p.usePrerequisites?' Ajoute-les dans « Quoi acheter d’abord ? » si tu as besoin d’équipement avant ton but.':'')+'</p>')+btn('Voir mes achats d’avant','data-open="order"')+'<div class="calc-fields">'+field('plan.upkeepPerSession','Je dépense par partie ($) : consommables, munitions…',p.upkeepPerSession,{id:'plan-upkeep',hint:'Enlevé de ce que tu gagnes. Mets 0 si tu ne sais pas.'})+(a?select('assets.'+i+'.incomeMode','Après l’achat, est-ce qu’il me fait gagner de l’argent ?',[['none','Non, c’est pour le plaisir'],['personal','Oui, à peu près ce chiffre par heure (je l’écris)'],['roi','Oui, ce que dit « Ça vaut le coup ? »']],a.incomeMode)+field('assets.'+i+'.boostHourly','Il me fera gagner en plus ($ par heure)',a.boostHourly,{id:'plan-boost'}):'')+'</div>','Un achat qui rapporte accélère la suite ; une dépense par partie ralentit tout le plan.')
   +step(4,'Ce qui compte pour toi',select('plan.priority','Je préfère',[['balanced','Un bon équilibre : je garde ma réserve'],['fast','Le plus vite possible : je peux toucher à ma réserve'],['safe','La sécurité : je ne touche jamais à ma réserve']],p.priority)+select('plan.strategy','Ordre des achats d’avant',Object.entries(STRATEGY_LABEL),p.strategy)+field('plan.deadlineDays','Je veux y arriver en (jours, si tu veux)',p.deadlineDays,{id:'plan-deadline',min:1,max:36500,integer:true,hint:'Laisse vide si tu n’as pas de date. On te dira si c’est faisable avec ton rythme.'}),'Le calculateur compare plusieurs façons de faire ; ta priorité décide laquelle il te conseille.')
   +'</div><p class="calc-note">Le plan se refait tout seul à chaque chiffre changé. Enregistre-le pour le retrouver, imprime-le, ou partage le lien.</p>';
  return '<section class="calc-panel" id="panel-plan" role="tabpanel" aria-labelledby="tab-plan" hidden><div class="calc-grid"><div class="calc-card"><p class="calc-kicker">MON BUSINESS PLAN</p><h3>Dis-moi ton but, je te fais le plan.</h3><p class="calc-card-desc">Remplis la fiche : le plan te dit ce qu’il te manque, combien de temps il te faut, quoi faire en premier, en deuxième, en troisième, et ce que tu fais dès ta prochaine partie.</p>'+form+'</div><div class="calc-card calc-result" id="plan-results"></div></div><div id="plan-report"></div><div class="b-stage-actions">'+btn('Enregistrer mon plan','data-b-save="plan"',true)+btn('Imprimer mon plan','data-b-print="1"')+btn('Exporter mon plan (fichier)','data-b-plan-export="1"')+'</div><p class="calc-note">Retrouve tes versions dans « Mes plans enregistrés » ci-dessous.</p><div class="b-expert calc-card calc-subsection" id="expert-plan"></div></section>';}
 /* Étape → clé d'achat (les achats d'avant gardent l'ordre de l'entrée du moteur ; le but est le dernier) */
 function stepKeys(s,input,r){const keys=[];const byName=new Map();s.order.keys.forEach(k=>{const a=lookup(k);if(a&&!byName.has(a.name))byName.set(a.name,k);});r.steps.forEach(st=>{if(st.kind==='goal')keys.push(s.plan.kind==='purchase'?s.plan.key:null);else keys.push(byName.get(st.name)||null);});return keys;}
 function goalTotal(input){return (input.goalPrice??0)+(input.target??0)+input.prerequisites.reduce((a,x)=>a+(x.price||0),0);}
 function render(){const s=state(),p=s.plan,r=B.evaluate('plan',s,sourceActivities),input=B.planInput(s,sourceActivities),mode=s.views.plan||'quick',expert=mode==='advanced',details=expert||p.details;
  const dpw=input.daysPerWeek,goalName=p.kind==='purchase'?(lookup(p.key)?.name||'mon achat'):'avoir '+money(input.target);
  let head='<p class="calc-kicker">MA RÉPONSE</p><span class="calc-tag">AVEC TES CHIFFRES</span>';
  if(!r.valid){head+=warning(r.reason)+problem(r.reason,'plan')+'<div class="calc-next-action"><strong>Pour avoir ton plan</strong><p>Il manque un chiffre ou un choix à gauche. Corrige la case indiquée : le plan se calcule tout seul.</p></div>';$('plan-results').innerHTML=head;$('plan-report').innerHTML='';$('expert-plan').innerHTML='';return;}
  const daily=hours(s.goal.dailyMinutes/60),reached=r.totalHours===0,keys=stepKeys(s,input,r),total=goalTotal(input),next=B.planNextSession(s,sourceActivities,r),deadline=B.planDeadline(s,sourceActivities),curve=B.planCurve(s,sourceActivities,r);
  const phrase=reached?'Bonne nouvelle : tu peux déjà '+(p.kind==='purchase'?'acheter '+esc(goalName):esc(goalName))+' avec ce que tu as, sans toucher à ce que tu gardes de côté.':'Pour '+(p.kind==='purchase'?'acheter '+esc(goalName):esc(goalName))+', il te manque <b>'+money(r.missing)+'</b>. En jouant <b>'+daily+'</b> par jour, '+dpw+' jour'+(dpw>1?'s':'')+' par semaine, tu y arrives en <b>'+hours(r.totalHours)+'</b> de jeu, soit <b>'+r.days+' jour'+(r.days>1?'s':'')+'</b> (vers le '+planDate(r.days)+').';
  head+='<p class="b-answer calc-answer" data-short="'+esc(reached?'C’est bon !':hours(r.totalHours)+' de jeu · '+r.days+' jours')+'">'+phrase+'</p>'+stats([['Il te manque',money(r.missing)],['Temps de jeu',hours(r.totalHours)],['Parties de '+daily,String(r.sessions)]])+visual.progress('plan-progress','Ce que tu as déjà',Math.min(s.goal.capital,s.goal.capital+r.missing),s.goal.capital+r.missing,'Départ : '+money(s.goal.capital)+'. Cible : '+money(s.goal.capital+r.missing)+' (tout ce qu’il faut avoir eu, achats d’avant compris). 100 % = tu peux payer ton but.');
  /* Prochaine action : concrète, dans la situation du joueur */
  if(reached)head+='<div class="calc-next-action"><strong>Ta prochaine étape</strong><p>'+esc(p.kind==='purchase'?'Achète '+goalName+' quand tu veux : il te restera '+money(s.goal.capital-(input.goalPrice||0))+'. Ensuite, choisis un nouveau but.':'Ton but est atteint. Choisis-en un plus grand, ou un achat.')+'</p></div>';
  else if(next.valid)head+='<div class="calc-next-action"><strong>Ta prochaine partie ('+hours(next.minutes/60)+')</strong><p>'+esc(next.mode==='activity'?(next.runs?next.runs+' × « '+(next.detail.name||'ton activité')+' » : +'+money(next.gain)+', tu auras '+money(next.capitalAfter)+'.':'Aucune mission complète ne tient dans '+hours(next.minutes/60)+' : allonge ta partie ou choisis une activité plus courte.'):'Joue '+hours(next.minutes/60)+' : +'+money(next.gain)+' environ, tu auras '+money(next.capitalAfter)+'.')+(next.reached.length?' Pendant cette partie, tu pourras acheter : '+esc(next.reached.join(', '))+'.':r.steps[0]&&r.steps[0].atHours===0&&r.steps[0].kind!=='goal'?' Commence par acheter « '+esc(r.steps[0].name)+' » : tu peux le payer tout de suite.':'')+'</p>'+btn('Après avoir joué, écrire ce que j’ai vraiment','data-b-focus="plan-actual"')+'</div>';
  if(mode!=='advanced')head+='<label class="calc-check"><input type="checkbox" data-b-plan-details="1" '+(p.details?'checked':'')+'> Afficher plus de détails (chiffres après chaque étape, calendrier, variantes, courbe)</label>';
  $('plan-results').innerHTML=head;
  /* Pas à pas : « Avant et après » ne sert que s’il y a des achats d’avant ou un achat qui peut rapporter. */
  document.querySelectorAll('#panel-plan .calc-step[data-step="3"]').forEach(n=>{if(p.kind==='amount'&&!s.order.keys.length)n.dataset.skip='1';else delete n.dataset.skip;});
  /* ---- Rapport ---- */
  let report='<div class="calc-card calc-subsection b-plan-report">';
  /* 1. Point de départ et hypothèses décisives */
  const originHourly=p.activity?'gain de « '+(B.activities(s,sourceActivities).find(x=>x.id===p.activity)?.name||'')+' »':'ton chiffre';
  const doneBoost=B.planDoneBoost(s);
  report+='<h3>Ton point de départ</h3><ul class="b-assumptions">'
   +'<li><span>Argent en poche</span><b>'+money(s.goal.capital)+'</b>'+btn('Modifier','data-b-focus="plan-capital"')+'</li>'
   +'<li><span>Gardé de côté</span><b>'+money(input.reserve)+(input.reserve!==s.goal.reserve?' (ta priorité « vite » l’utilise)':'')+'</b>'+btn('Modifier','data-b-focus="plan-reserve"')+'</li>'
   +'<li><span>Gain par heure ('+esc(originHourly)+(doneBoost?' + achats faits':'')+')</span><b>'+money(input.hourly)+(r.upkeepHourly?' − '+money(r.upkeepHourly)+' de dépenses = '+money(r.effectiveHourly):'')+'</b>'+btn('Modifier','data-b-focus="'+(p.activity?'f-plan-activity':'plan-hourly')+'"')+'</li>'
   +'<li><span>Rythme</span><b>'+daily+' par jour · '+dpw+' j/semaine</b>'+btn('Modifier','data-b-focus="plan-daily"')+'</li>'
   +(p.kind==='purchase'?'<li><span>Prix de ton but</span><b>'+money(input.goalPrice)+'</b>'+btn('Modifier','data-b-focus="plan-price"')+'</li>':'<li><span>Somme visée</span><b>'+money(input.target)+'</b>'+btn('Modifier','data-b-focus="plan-target"')+'</li>')
   +(input.allPrerequisites.length?'<li><span>Achats d’avant</span><b>'+esc(input.allPrerequisites.map(x=>x.name+' ('+money(x.price)+(x.boostHourly>0?', +'+money(x.boostHourly)+'/h':'')+')').join(' · '))+'</b>'+btn('Modifier','data-open="order"')+'</li>':'')
   +(s.assets.some(x=>x.owned)?'<li><span>Déjà possédé</span><b>'+esc(s.assets.filter(x=>x.owned).map(x=>x.name).join(', '))+'</b></li>':'')+'</ul>'
   +'<p class="calc-note">Rien ne vient du vrai jeu : prix, gains et temps sont tes chiffres, ou ceux que le site indique comme repères. Le plan change dès que tu en changes un.</p>';
  if(doneBoost)report+='<label class="calc-check"><input type="checkbox" data-b-plan-done-boost="1" '+(p.countDoneBoost?'checked':'')+'> Compter ce que rapportent mes achats déjà faits ('+money(doneBoost)+'/h) en plus de mon chiffre. Décoche si ton chiffre les inclut déjà.</label>';
  /* 2. Stratégie recommandée et alternatives */
  const st=r.strategies||(p.strategy!=='auto'?B.planStrategies(s,sourceActivities):null);
  const label=c=>c.id==='asIs'&&!input.allPrerequisites.length?'Directement vers ton but':STRATEGY_LABEL[c.id]||c.id;
  if(st&&st.valid&&st.candidates.filter(c=>c.valid).length>1){const rec=st.candidates.find(c=>c.id===st.recommended),asIs=st.candidates.find(c=>c.id==='asIs'),chosen=p.strategy==='auto'?rec:st.candidates.find(c=>c.id===p.strategy);
   const why=rec&&asIs&&rec.id!=='asIs'&&rec.valid&&asIs.valid?(rec.totalHours<asIs.totalHours?'tu gagnes '+hours(asIs.totalHours-rec.totalHours)+' de jeu par rapport à ton ordre':'même délai que ton ordre, avec '+(rec.reserveKept?'ta réserve gardée':'plus d’argent à la fin')):'c’est la façon la plus rapide parmi celles qui '+(p.priority==='fast'?'ont été comparées':'gardent ton argent de côté');
   report+='<h3>La stratégie conseillée</h3><p class="b-strategy-answer"><b>'+esc(label(rec))+'</b> : '+esc(why)+'.'+(chosen&&chosen.id!==st.recommended?' Tu as choisi « '+esc(label(chosen))+' » : le plan ci-dessous suit ton choix.':'')+'</p>';
   report+=table([['Façon de faire','Temps de jeu','Jours','Argent à la fin','Réserve gardée'],...st.candidates.map(c=>[(c.id===st.recommended?'★ ':'')+label(c)+(c.note?' — '+c.note:''),c.valid?hours(c.totalHours):'Impossible : '+c.reason,c.valid?String(c.days):'—',c.valid?money(c.finalCapital):'—',c.reserveKept?'Oui':'Non'])],'Même but, mêmes chiffres : seul l’ordre ou la réserve change',true);
   report+='<p class="calc-note">On compare '+st.explored+' façons de faire raisonnables ; il peut en exister une meilleure. « Seulement les achats qui rapportent » et « Directement vers mon but » retirent des achats que tu avais demandés : ils ne sont conseillés que si tu peux t’en passer.</p>';}
  /* 3. Les étapes */
  let paid=0;const steps=[];
  if(input.reserve>0)steps.push({title:'Garde '+money(input.reserve)+' de côté',text:'Cet argent ne sert pas au plan : il reste là en cas de coup dur.',detail:'Ton argent utilisable au départ : '+money(s.goal.capital-input.reserve)+'.'});
  if(p.activity){const act=B.activities(s,sourceActivities).find(x=>x.id===p.activity);if(act)steps.push({title:'Gagne ton argent avec « '+act.name+' »',text:'À peu près '+money(input.hourly)+' par heure de jeu, frais et attente comptés.',detail:'Récompense '+money(act.reward)+' × ta part '+act.share+' % − frais '+money(act.cost)+', pour '+act.duration+' min de mission'+(act.prep?' + '+act.prep+' min de préparation':'')+(act.cooldown?' + '+act.cooldown+' min d’attente':'')+'.'});}
  else steps.push({title:'Gagne à peu près '+money(input.hourly)+' par heure',text:'C’est ton chiffre à toi. S’il baisse, le plan s’allonge (voir « Et si… ? »).',detail:p.upkeepPerSession>0?'Tes dépenses par partie ('+money(p.upkeepPerSession)+') enlèvent '+money(r.upkeepHourly)+' par heure : on compte avec '+money(r.effectiveHourly)+' par heure.':'Aucune dépense par partie comptée.'});
  let rateBefore=Math.max(0,r.effectiveHourly);
  r.steps.forEach((stp,i)=>{const isGoal=stp.kind==='goal',isAmount=isGoal&&p.kind==='amount',key=keys[i],asset=key?lookup(key):null,price=isAmount?0:(isGoal?input.goalPrice:(input.prerequisites[i]||{}).price)||0;
   const earnedWhileWaiting=stp.waitHours*rateBefore;paid+=price;const progress=total>0?(isAmount?(stp.capitalAfter-input.reserve)/total:paid/total)*100:null;
   const when=stp.atHours===0?'dès maintenant':'après '+hours(stp.atHours)+' de jeu'+(stp.days?' (≈ jour '+stp.days+', vers le '+planDate(stp.days)+')':'');
   steps.push({key,asset,goal:isGoal,title:(isGoal?(p.kind==='purchase'?'Achète ':'Objectif : ')+stp.name:'Achète d’abord '+stp.name)+' — '+when,
    text:isAmount?'La somme que tu voulais, en plus de ce que tu gardes de côté.':(stp.waitHours>0?'Il faut d’abord jouer '+hours(stp.waitHours)+' de plus pour le payer ('+money(earnedWhileWaiting)+' gagnés pendant ce temps).':'Tu peux le payer tout de suite.')+(isGoal?' C’est ton but.':''),
    detail:'Dépense : '+money(price)+' · après cette étape il te reste '+money(stp.capitalAfter)+', tu gagnes '+money(stp.hourlyAfter)+' par heure'+(progress!==null?' · avancement '+pct(progress):'')+'.',
    figures:[['Dépense',money(price)],['Gagné en attendant',money(earnedWhileWaiting)],['Il te reste après',money(stp.capitalAfter)],['Avancement',pct(progress)]]});
   rateBefore=stp.hourlyAfter===null?rateBefore:stp.hourlyAfter;});
  if(p.kind==='purchase'){const a=lookup(p.key);if(r.payback!==null)steps.push({title:'Ensuite, il se rembourse',text:'D’après ce que tu as écrit, il te fait gagner '+money(input.goalIncomeHourly)+' de plus par heure : remboursé après '+hours(r.payback)+' de jeu.',detail:'Prix ÷ gain en plus par heure = '+hours(r.payback)+'. Ce gain, c’est ton hypothèse, pas une promesse du jeu.'});else steps.push({title:'Ensuite, profite',text:'C’est un achat plaisir : il ne se rembourse pas tout seul. Si tu penses qu’il te fait gagner de l’argent, écris-le dans « Avant et après ».',detail:a?'Prix retenu : '+money(a.price===null?null:a.price+a.extras+a.fees)+'.':''});}
  const doneList=p.done.map(k=>lookup(k)).filter(Boolean);
  report+='<h3>Ton plan, étape par étape</h3>'+(doneList.length?'<p class="b-plan-done"><b>Déjà fait :</b> '+esc(doneList.map(a=>a.name).join(', '))+'. '+btn('Annuler « fait »','data-b-plan-undone="1"')+'</p>':'')
   +'<ol class="b-plan-steps">'+steps.map((x,i)=>'<li class="b-plan-step'+(x.goal?' is-goal':'')+'"><span class="calc-tag">'+(i+1)+'</span><div><h4>'+esc(x.title)+'</h4><p>'+esc(x.text)+'</p>'+(details&&x.figures?'<div class="b-step-figures">'+x.figures.map(([l,v])=>'<span><small>'+esc(l)+'</small><b>'+esc(v)+'</b></span>').join('')+'</div>':details&&x.detail?'<p class="calc-note">'+esc(x.detail)+'</p>':'')+(x.key&&x.asset&&!x.asset.owned?btn(x.goal?'J’ai acheté mon but ✓':'C’est fait ✓ ('+esc(x.asset.name)+' acheté)','data-b-plan-done="'+esc(x.key)+'"'):'')+'</div></li>').join('')+'</ol>';
  /* 4. Suivi du réel */
  const usual=s.session.usualMinutes??s.goal.dailyMinutes;
  report+='<h3>Après avoir joué : où en es-tu vraiment ?</h3><p>Écris ce que tu as maintenant : le plan repart de là, sans compter deux fois ce que tu as déjà fait. Coche « C’est fait » sur un achat réalisé.</p><div class="calc-fields b-actual"><div class="calc-field"><label class="calc-label" for="plan-actual">J’ai maintenant ($)</label><input id="plan-actual" type="text" inputmode="decimal" maxlength="25" data-number="1" data-min="0" data-max="1000000000000" value="" placeholder="'+esc(nf.format(s.goal.capital))+'"><small>Ton argent en poche après ta partie.</small></div><div class="calc-field"><label class="calc-label" for="plan-actual-minutes">J’ai joué (minutes) depuis la dernière fois</label><input id="plan-actual-minutes" type="text" inputmode="decimal" maxlength="6" data-number="1" data-min="0" data-max="100000" value="'+(usual||'')+'"></div></div>'+btn('Mettre à jour mon plan','data-b-plan-log="1"',true)+(p.log.length?btn('Effacer l’historique','data-b-plan-clear="1"'):'')+'<p class="calc-note" id="plan-log-feedback" role="status"></p>';
  if(p.log.length){const rows=p.log.map(e=>{const gap=e.forecast===null?null:e.capital-e.forecast;return [new Date(e.at).toLocaleDateString('fr-FR',{day:'numeric',month:'short'}),hours(e.minutes/60),e.forecast===null?'—':money(e.forecast),money(e.capital),gap===null?'—':(gap>=0?'+':'−')+money(Math.abs(gap))];});
   report+=table([['Date','Joué en tout','Prévu','Réel','Écart'],...rows],'Réalisé contre prévu, partie après partie',true)+'<p class="calc-note">Prévu = ce que le plan attendait après ce temps de jeu, calculé avant ta mise à jour. Réel = ce que tu as écrit. Le plan actuel repart toujours du réel.</p>';}
  /* 5. Échéance */
  if(p.deadlineDays){report+='<h3>Ton échéance : '+p.deadlineDays+' jour'+(p.deadlineDays>1?'s':'')+'</h3>';
   if(!deadline||!deadline.valid)report+=warning(deadline?deadline.reason:'Échéance non calculable.');
   else if(deadline.feasible)report+='<p class="b-strategy-answer"><b>Oui</b>, c’est faisable avec ton rythme : '+hours(deadline.hoursAvailable)+' de jeu possibles d’ici là pour '+hours(deadline.totalHours)+' nécessaires. Marge : '+hours(deadline.spareHours)+'.</p>';
   else report+='<p class="b-strategy-answer"><b>Pas avec ton rythme actuel</b> : '+hours(deadline.hoursAvailable)+' de jeu possibles d’ici là, il en faut '+hours(deadline.totalHours)+'.</p><ul class="b-thresholds"><li>Soit jouer <b>'+(deadline.requiredDailyPossible?hours(deadline.requiredDailyMinutes/60)+' par jour</b> au lieu de '+daily:'plus de 24 h par jour</b> : impossible')+'.</li>'+(deadline.requiredHourly!==null?'<li>Soit gagner <b>'+money(deadline.requiredHourly)+' par heure</b> au lieu de '+money(input.hourly)+'.</li>':'')+'<li>Sinon, la date la plus proche avec ton rythme : <b>jour '+r.days+'</b> (vers le '+planDate(r.days)+').</li></ul>';}
  /* 6. Détails : et si, seuils, courbe, calendrier, formule */
  if(details&&!reached){
   const v=r.variants;report+='<h3>Et si… ?</h3>'+table([['Variante','Temps de jeu','Jours'],['Les prix sont 20 % plus chers',v.pricePlus20?hours(v.pricePlus20.totalHours):'—',v.pricePlus20?String(v.pricePlus20.days):'—'],['Je gagne 20 % de moins',v.hourlyMinus20?hours(v.hourlyMinus20.totalHours):'—',v.hourlyMinus20?String(v.hourlyMinus20.days):'—'],['Je touche à ma réserve',v.noReserve?hours(v.noReserve.totalHours):'sans objet',v.noReserve?String(v.noReserve.days):'—']],'Pour voir ce qui change si un chiffre bouge',true);
   const more=E.businessPlan({...input,dailyMinutes:s.goal.dailyMinutes+30,variants:false}),firstWait=r.steps.find(x=>x.waitHours>0);
   report+='<h3>Les seuils qui changent la donne</h3><ul class="b-thresholds">'+(more.valid?'<li>Avec <b>30 min de plus par jour</b> ('+hours((s.goal.dailyMinutes+30)/60)+'), tu finis en <b>'+more.days+' jour'+(more.days>1?'s':'')+'</b> au lieu de '+r.days+'.</li>':'')+(firstWait?'<li>Il te manque <b>'+money(firstWait.waitHours*Math.max(0,r.effectiveHourly))+'</b> pour passer « '+esc(firstWait.name)+' » tout de suite.</li>':'')+(input.goalIncomeHourly>0?'<li>Ton but rapporte '+money(input.goalIncomeHourly)+'/h : remboursé après <b>'+hours(r.payback)+'</b> de jeu.</li>':'')+'</ul>';
   if(curve.length>1)report+=visual.chart('c-plan-curve',{title:'Ton argent au fil du plan',question:'Quand chaque achat devient-il possible, et où en seras-tu ?',xTitle:'Temps de jeu (heures)',yTitle:'Argent en poche ($)',unit:'$',xUnit:'h',series:[{name:'Prévu avec tes chiffres',kind:'forecast',points:curve.map(pt=>({x:pt.hours,y:pt.cash,label:pt.label,key:pt.purchase}))},...(p.log.length?[{name:'Réel (ce que tu as écrit)',kind:'realized',points:p.log.map(e=>({x:e.minutes/60,y:e.capital,label:new Date(e.at).toLocaleDateString('fr-FR')}))}]:[])],thresholds:input.reserve>0?[{y:input.reserve,label:'Argent gardé de côté'}]:[],reading:'Chaque marche vers le bas est un achat payé ; entre deux, ton argent monte à '+money(r.effectiveHourly)+' par heure. Le plan finit à '+hours(r.totalHours)+' de jeu.',note:'Les points « réel » viennent de tes mises à jour ; ils ne sont pas lissés.'});
   report+='<h3>Ton calendrier</h3>'+table([['Étape','Temps de jeu','Parties','Jour','Date estimée'],...r.milestones.map(m=>[Math.round(m.fraction*100)+' %',hours(m.hours),String(m.sessions),'jour '+m.days,planDate(m.days)])],'Jalons si tu joues '+daily+' par jour, '+dpw+' jour(s) par semaine',true);
   report+='<details'+(expert?' open':'')+'><summary>Comment est-ce calculé ?</summary><p class="calc-note">Les achats se font dans l’ordre, un par un : à chaque étape, attente = (prix + argent de côté − ce que tu as) ÷ ce que tu gagnes par heure. Un achat qui rapporte augmente ton gain pour les étapes suivantes ; un achat n’est jamais payé avec l’argent qu’il rapportera lui-même. Parties = temps de jeu ÷ ton temps par jour, arrondi au-dessus ; jours = parties réparties sur tes jours de jeu par semaine. Les dates supposent que tu commences aujourd’hui. Le temps de jeu est du temps actif ; l’attente entre deux parties n’est pas comptée comme du jeu. Rien ne vient du vrai jeu.</p></details>';}
  else if(!reached&&mode!=='advanced')report+='<p class="calc-note">Coche « Afficher plus de détails » pour voir les chiffres de chaque étape, les seuils, la courbe, le calendrier et la formule.</p>';
  report+='<div class="b-plan-links">'+btn('Changer mes achats d’avant','data-open="order"')+btn('Comparer d’autres achats','data-open="compare"')+btn('Vérifier ce que ça rapporte','data-open="roi"')+btn('Préparer ma prochaine partie','data-open="session"')+'</div></div>';
  $('plan-report').innerHTML=report;
  $('expert-plan').innerHTML=expert?expertBlock(s,r,input,st):'';
 }
 function expertBlock(s,r,input,st){const rows=Object.entries(r).filter(([k,v])=>typeof v==='number'||v===null).map(([k,v])=>[k,v===null?'Non disponible':nf.format(v)]);
  return '<h3>Mes réglages avancés</h3><p class="calc-note">Le mode Expert affiche tout : stratégies comparées, chiffres de chaque étape, seuils, courbe, calendrier, et les résultats bruts du moteur ci-dessous. Les mêmes chiffres qu’en Simple, avec le détail.</p>'+table([['Entrée du moteur','Valeur'],['Argent',money(input.capital)],['Réserve',money(input.reserve)],['Gain par heure',money(input.hourly)],['Temps par jour',hours(input.dailyMinutes/60)],['Jours par semaine',String(input.daysPerWeek)],['Dépenses par partie',money(input.upkeepPerSession)],['But',input.goalPrice!==null?input.goalName+' : '+money(input.goalPrice):'Avoir '+money(input.target)],['Ce que rapporte le but',money(input.goalIncomeHourly)+'/h'],['Achats d’avant retenus',input.prerequisites.map(x=>x.name).join(', ')||'aucun'],['Stratégie',STRATEGY_LABEL[r.strategy||'asIs']]],'Valeurs effectivement utilisées')+'<details><summary>Résultats bruts du moteur</summary>'+table(rows,'Résultats numériques')+'</details>';}
 /* Événements propres au plan */
 function event(ev){const el=ev.target,s=state(),p=s.plan;
  if(ev.type==='change'){
   if(el.dataset.bPlanDoneBoost!==undefined){p.countDoneBoost=el.checked;api.changed();return true;}
   if(el.dataset.field==='plan.strategy'){p.strategy=B.STRATEGIES.includes(el.value)?el.value:'auto';api.changed();return true;}
  }
  if(ev.type==='click'){const button=el.closest('button');if(!button)return false;const d=button.dataset;
   if(d.bPlanDone){const a=lookup(d.bPlanDone);if(!a)return true;a.owned=true;if(!p.done.includes(a.key))p.done.push(a.key);api.notify('« '+a.name+' » marqué comme fait : il sort du plan, son argent n’est plus recompté.');api.changed();return true;}
   if(d.bPlanUndone){p.done.forEach(k=>{const a=lookup(k);if(a)a.owned=false;});p.done=[];api.changed();return true;}
   if(d.bPlanLog){const cap=parse($('plan-actual')?.value),mins=parse($('plan-actual-minutes')?.value),fb=$('plan-log-feedback');
    if(cap===null||cap<0||cap>1e12){if(fb)fb.textContent='Écris ce que tu as maintenant, avec un nombre (par exemple 350 000).';$('plan-actual')?.focus();return true;}
    if(mins===null||mins<0||mins>1e5){if(fb)fb.textContent='Écris le temps joué en minutes (par exemple 60).';$('plan-actual-minutes')?.focus();return true;}
    const before=B.evaluate('plan',s,sourceActivities),curve=before.valid?B.planCurve(s,sourceActivities,before):[];const cash=curve.length?E.planCashAt({points:curve,hours:mins/60}):null;const forecast=cash&&cash.valid?cash.cash:null;
    p.playedMinutes=(p.playedMinutes||0)+mins;p.log.push({at:new Date().toISOString(),capital:cap,minutes:p.playedMinutes,forecast,note:''});if(p.log.length>50)p.log=p.log.slice(-50);
    s.goal.capital=cap;document.querySelectorAll('[data-field="goal.capital"]').forEach(i=>{i.value=cap;});api.changed();
    const gap=forecast===null?null:cap-forecast;api.notify('Plan mis à jour : tu repars de '+money(cap)+'.'+(gap===null?'':gap>=0?' Tu as '+money(gap)+' de plus que prévu.':' Tu as '+money(-gap)+' de moins que prévu : le plan s’allonge.'));return true;}
   if(d.bPlanClear){p.log=[];p.playedMinutes=0;api.changed();api.notify('Historique effacé. Ton argent actuel est gardé.');return true;}
   if(d.bPlanExport){const r=B.evaluate('plan',s,sourceActivities);const text=exportText(s,r);const blob=new Blob([text],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mon-business-plan-leonidakit.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);api.notify('Plan exporté en texte lisible.');return true;}
  }
  return false;}
 function parse(v){const P=E.parseLocalizedNumber;if(v===undefined||v===null)return null;const r=P(String(v));return r.valid?r.value:null;}
 function exportText(s,r){const p=s.plan,input=B.planInput(s,sourceActivities);const lines=['MON BUSINESS PLAN — Leonidakit ('+new Date().toLocaleDateString('fr-FR')+')','But : '+(p.kind==='purchase'?(lookup(p.key)?.name||'achat')+' à '+money(input.goalPrice):'avoir '+money(input.target)),'Départ : '+money(s.goal.capital)+' en poche, '+money(input.reserve)+' de côté, '+money(input.hourly)+' par heure, '+hours(s.goal.dailyMinutes/60)+' par jour, '+input.daysPerWeek+' j/semaine',''];
  if(!r.valid){lines.push('Plan non calculable : '+r.reason);return lines.join('\n');}
  lines.push('Il manque '+money(r.missing)+' → '+hours(r.totalHours)+' de jeu, '+r.sessions+' parties, '+r.days+' jours (vers le '+planDate(r.days)+').','','ÉTAPES');
  r.steps.forEach((st,i)=>lines.push((i+1)+'. '+(st.kind==='goal'?'BUT : ':'')+st.name+' — '+(st.atHours===0?'dès maintenant':'après '+hours(st.atHours)+' de jeu (≈ jour '+st.days+')')+' · reste '+money(st.capitalAfter)+' · ensuite '+money(st.hourlyAfter)+'/h'));
  if(p.log.length){lines.push('','SUIVI');p.log.forEach(e=>lines.push(new Date(e.at).toLocaleDateString('fr-FR')+' · joué '+hours(e.minutes/60)+' · prévu '+(e.forecast===null?'—':money(e.forecast))+' · réel '+money(e.capital)));}
  lines.push('','Ce sont tes chiffres, pas ceux du jeu. Recalculé sur leonidakit.com/calculateurs.html?tool=plan');return lines.join('\n');}
 return {markup,render,event,STRATEGY_LABEL};
}
global.LKCalcPlan={create};
})(window);
