(function () {
'use strict';
const E=window.LKCalcEngine,D=window.LKCalcData,T=window.LKCalcTools,$=id=>document.getElementById(id),esc=window.LK.esc;
if(!E||!D||!T){$('calc-panels').innerHTML='<p class="calc-warning">Le calculateur n’a pas pu charger ses fichiers. Recharge la page.</p>';return;}
const clone=x=>JSON.parse(JSON.stringify(x)),nf=new Intl.NumberFormat('fr-FR',{maximumFractionDigits:2}),money=n=>Number.isFinite(n)?nf.format(n)+' $':'—';
function hours(n){if(!Number.isFinite(n))return '—';const mins=Math.ceil(n*60-1e-8);return mins<60?mins+' min':Math.floor(mins/60)+' h'+(mins%60?' '+String(mins%60).padStart(2,'0'):'');}
const warning=s=>'<p class="calc-warning">'+esc(s||'Complète les paramètres pour calculer le résultat.')+'</p>';
const stats=items=>'<div class="calc-stats">'+items.map(([label,value])=>'<div class="calc-stat"><strong>'+esc(value)+'</strong><span>'+esc(label)+'</span></div>').join('')+'</div>';
function field(path,label,value,opts={}){const id='f-'+path.replaceAll('.','-');return '<div class="calc-field'+(opts.wide?' wide':'')+'"><label class="calc-label" for="'+id+'">'+esc(label)+'</label><input id="'+id+'" data-field="'+path+'" type="'+(opts.type||'number')+'" '+((opts.type==='text')?'maxlength="100"':'min="'+(opts.min??0)+'" max="'+(opts.max??1000000000000)+'" step="'+(opts.step??'any')+'" inputmode="decimal"')+' value="'+esc(value??'')+'">'+(opts.hint?'<small>'+esc(opts.hint)+'</small>':'')+'</div>';}
const helpers={E,esc,money,hours,field,stats,warning};
const initial={version:1,tab:'goal',goal:{capital:200000,target:1000000,dailyMinutes:60,players:1,selected:'scenario-a'},activities:D.presets.map(a=>({id:a.id,name:a.name,reward:a.reward,cost:a.cost,duration:a.duration,prep:a.prep,cooldown:a.cooldown,share:a.share,investment:a.investment,players:a.players})),inverse:{minutes:60,selected:'scenario-a'},purchase:{itemId:'',price:100000,hourly:50000,boostHourly:0,capital:200000,target:1000000},...clone(T.defaults)};
const tabs=['goal','activities','roi','purchase','budget','order'];
let state=clone(initial),catalogue=D.catalogue(),sourceActivities=D.activities(),saved=[],recent=[],saveTimer,liveTimer,query='',typeFilter='all',catalogueLimit=6,compareIds=[],chartPercent=50;
const labels={vehicle:'Véhicule',weapon:'Équipement',property:'Demeure',business:'Entreprise',place:'Lieu',activity:'Activité'},statusLabels={unknown:'À compléter',unverified:'Non confirmé',manual:'Hypothèse utilisateur',official:'Confirmé',verified:'Vérifié',estimated:'Estimation',observed:'Repéré',community:'Identification communautaire','source-listed':'Source indiquée'};
function notify(message){$('calc-live').textContent=message;window.LK.status(message);}
function validConfig(raw){
 if(!raw||typeof raw!=='object'||Array.isArray(raw)||raw.version!==1)throw Error('Version de configuration non reconnue.');
 const walk=(template,value,key='')=>{if(typeof template==='number'){if(value===null)return null;if(typeof value!=='number'||!Number.isFinite(value)||value<0||value>1e12)throw Error('Valeur numérique invalide.');return value;}
 if(typeof template==='string'){if(typeof value!=='string'||value.length>200)throw Error('Texte invalide.');return value;}
 if(Array.isArray(template)){if(!Array.isArray(value)||value.length!==template.length)throw Error('Nombre de scénarios invalide.');return template.map((x,i)=>walk(x,value[i],key));}
 if(!value||typeof value!=='object'||Array.isArray(value))throw Error('Configuration incomplète.');const out={};for(const k of Object.keys(template)){if(!(k in value))throw Error('Champ manquant : '+k);out[k]=walk(template[k],value[k],k);}return out;};
 const out=walk(initial,raw);if(!tabs.includes(out.tab)||out.version!==1)throw Error('Onglet ou version invalide.');
 if(out.activities.some((a,i)=>a.id!==initial.activities[i].id))throw Error('Identifiant de scénario invalide.');return out;
}
function loadLocal(){try{const raw=localStorage.getItem('lk-calculator-v1');if(raw)state=validConfig(JSON.parse(raw));const list=JSON.parse(localStorage.getItem('lk-calculator-saved-v1')||'[]');if(Array.isArray(list))saved=list.slice(0,12).flatMap(x=>{try{return [{name:String(x.name||'Mon calcul').slice(0,100),config:validConfig(x.config)}];}catch{return [];}});const hist=JSON.parse(localStorage.getItem('lk-calculator-recent-v1')||'[]');if(Array.isArray(hist))recent=hist.slice(0,5).flatMap(x=>{try{return [{name:String(x.name||'Calcul récent').slice(0,100),config:validConfig(x.config)}];}catch{return [];}});}catch{notify('Une ancienne sauvegarde était invalide ; les paramètres d’exemple restent disponibles.');}}
function saveLocal(){if(location.hash.startsWith('#plan='))history.replaceState(null,'',location.pathname+location.search);try{localStorage.setItem('lk-calculator-v1',JSON.stringify(state));return true;}catch{notify('Sauvegarde locale indisponible. Exporte ta configuration pour la conserver.');return false;}}
function loadHash(){if(!location.hash.startsWith('#plan='))return;try{if(location.hash.length>24000)throw Error('Lien trop long.');state=validConfig(JSON.parse(decodeURIComponent(location.hash.slice(6))));notify('Configuration partagée chargée. Les hypothèses restent modifiables.');}catch{notify('Lien de calcul invalide. La configuration locale est conservée.');}}
loadLocal();loadHash();
const activityList=()=>[...state.activities.map(x=>({...x,status:'manual'})),...sourceActivities];
const findActivity=id=>activityList().find(a=>a.id===id);
function activityOptions(selected,includeMixed=false){return (!findActivity(selected)&&!(includeMixed&&selected==='mixed')?'<option value="'+esc(selected)+'" selected>Scénario indisponible — choisis une autre activité</option>':'')+activityList().map(a=>'<option value="'+esc(a.id)+'"'+(a.id===selected?' selected':'')+'>'+esc(a.name)+(a.status==='manual'?' · hypothèse':' · catalogue')+'</option>').join('')+(includeMixed?'<option value="mixed"'+(selected==='mixed'?' selected':'')+'>Alterner les scénarios accessibles au groupe</option>':'');}
function selectField(path,label,options){return '<div class="calc-field wide"><label class="calc-label" for="f-'+path.replaceAll('.','-')+'">'+label+'</label><select id="f-'+path.replaceAll('.','-')+'" data-field="'+path+'">'+options+'</select></div>';}
function mount(){
$('calc-panels').innerHTML=`<section class="calc-panel" id="panel-goal" role="tabpanel" aria-labelledby="tab-goal">
 <div class="calc-grid"><div class="calc-card"><h3>Où veux-tu aller ?</h3><p class="calc-card-desc">Renseigne ton capital et ton rythme. On s’occupe des calculs.</p><div class="calc-fields">${field('goal.capital','Mon capital actuel ($)',state.goal.capital)}${field('goal.target','Mon objectif ($)',state.goal.target)}<div class="wide calc-presets" aria-label="Objectifs populaires">${[100000,500000,1000000,5000000,10000000].map(n=>'<button class="calc-chip" data-target="'+n+'">'+(n>=1e6?n/1e6+' M':n/1000+' k')+' $</button>').join('')}</div>${field('goal.dailyMinutes','Temps par jour (min)',state.goal.dailyMinutes,{max:1440,min:1})}${field('goal.players','Joueurs disponibles',state.goal.players,{min:1,max:100,step:1})}${selectField('goal.selected','Mon scénario de revenus',activityOptions(state.goal.selected,true))}</div><button class="calc-text-button" data-open="activities">Ajuster mes récompenses, coûts et durées ↗</button><p class="calc-note">Les scénarios A, B et C sont des exemples fictifs. Change leurs valeurs pour simuler ta propre progression.</p></div><div class="calc-card calc-result" id="goal-results" aria-label="Résultat de l’objectif"></div></div>
 <div class="calc-route-head"><h3>Trois façons de voir la suite.</h3><p>Comparaison de tes hypothèses · mêmes capital et temps disponibles</p></div><div class="calc-routes" id="goal-routes"></div><ol class="calc-milestones" id="goal-milestones" aria-label="Étapes de progression"></ol></section>
 <section class="calc-panel" id="panel-activities" role="tabpanel" aria-labelledby="tab-activities" hidden><div class="calc-card"><h3>Construis tes scénarios.</h3><p class="calc-card-desc">Une ligne = une activité hypothétique. La récompense est celle du groupe ; les frais sont les tiens. Ta part s’applique une seule fois.</p><div class="calc-confirm-data">${sourceActivities.length?sourceActivities.length+' activité(s) disponible(s) dans la base, avec provenance propre.':'Aucune activité économique chiffrée n’est renseignée dans la base GTA VI.'} Les trois lignes ci-dessous restent des hypothèses personnelles.</div><div class="calc-table-wrap"><table class="calc-table"><caption class="calc-sr">Valeurs personnalisées des scénarios</caption><thead><tr><th scope="col">Hypothèse</th><th scope="col">Récompense ($)</th><th scope="col">Tes frais ($)</th><th scope="col">Durée (min)</th><th scope="col">Préparation (min)</th><th scope="col">Attente (min)</th><th scope="col">Ta part (%)</th><th scope="col">Mise initiale ($)</th><th scope="col">Joueurs requis</th></tr></thead><tbody>${state.activities.map((a,i)=>'<tr>'+['name','reward','cost','duration','prep','cooldown','share','investment','players'].map(k=>'<td><input aria-label="'+esc(({name:'Nom',reward:'Récompense',cost:'Frais',duration:'Durée',prep:'Préparation',cooldown:'Attente',share:'Part',investment:'Investissement',players:'Joueurs'})[k])+' scénario '+(i+1)+'" data-field="activities.'+i+'.'+k+'" type="'+(k==='name'?'text':'number')+'" value="'+esc(a[k])+'" '+(k==='name'?'maxlength="100"':'min="'+(['duration','players'].includes(k)?1:0)+'" max="'+(k==='share'?100:k==='players'?100:1e12)+'" step="'+(k==='players'?1:'any')+'"')+'></td>').join('')+'</tr>').join('')}</tbody></table></div><div class="calc-toolbar"><label class="calc-label" for="activity-filter">Comparer selon</label><select id="activity-filter"><option value="hourly">Meilleur gain net / h</option><option value="investment">Faible investissement</option><option value="solo">Solo</option><option value="short">Sessions ≤ 30 min</option><option value="accessible">Accessible à mon capital</option></select><span class="calc-tag">VALEURS PERSONNALISÉES</span></div><div id="activity-results"></div></div><div class="calc-card calc-subsection"><h3>J’ai du temps. Combien puis-je gagner ?</h3><p class="calc-card-desc">Projection d’une session continue : seules les missions terminées rapportent. La mise initiale est déduite une fois du capital.</p><div class="calc-fields">${field('inverse.minutes','Temps disponible (min)',state.inverse.minutes,{max:1000000})}${selectField('inverse.selected','Scénario à répéter',activityOptions(state.inverse.selected))}</div><div id="inverse-results"></div></div></section>
 <section class="calc-panel" id="panel-purchase" role="tabpanel" aria-labelledby="tab-purchase" hidden><div class="calc-grid"><div class="calc-card"><h3>Un achat. Quel impact ?</h3><p class="calc-card-desc">Choisis une fiche ci-dessous ou saisis un prix personnel. Les achats de lieux ne sont pas présumés possibles dans le jeu.</p><div id="purchase-selection"></div><div class="calc-fields">${field('purchase.price','Prix envisagé ($)',state.purchase.price)}${field('purchase.capital','Mon capital ($)',state.purchase.capital)}${field('purchase.hourly','Revenu net actuel ($ / h)',state.purchase.hourly)}${field('purchase.boostHourly','Gain supplémentaire après achat ($ / h)',state.purchase.boostHourly)}${field('purchase.target','Objectif après achat ($)',state.purchase.target)}</div><p class="calc-note">Le gain horaire supplémentaire est ton hypothèse. Un véhicule n’augmente pas automatiquement tes revenus.</p></div><div class="calc-card" id="purchase-results"></div></div><div class="calc-card calc-subsection"><h3>Trouve ton prochain achat.</h3><p class="calc-card-desc">Recherche dans les catalogues du site. Les valeurs inconnues ne sont jamais assimilées à zéro.</p><label class="calc-sr" for="catalogue-search">Rechercher dans le catalogue</label><input class="calc-search-input" id="catalogue-search" type="search" placeholder="Un véhicule, une arme, une entreprise…" maxlength="100"><div class="calc-toolbar"><label class="calc-label" for="catalogue-type">Catégorie</label><select id="catalogue-type"><option value="all">Tout le catalogue</option>${Object.entries(labels).map(([k,v])=>'<option value="'+k+'">'+v+'</option>').join('')}</select><span id="catalogue-count" class="calc-tag"></span></div><div id="catalogue-results" class="calc-catalogue"></div><button class="calc-button" id="catalogue-more">Afficher plus</button><div class="calc-subsection" id="vehicle-comparison"></div></div></section>`+T.markup(state,helpers);
renderAll();switchTab(state.tab,false);renderSaved();
}
function calculation(a,target=state.goal.target){if(!Number.isInteger(state.goal.players)||state.goal.players<1||state.goal.players>100)return {valid:false,reason:'Renseigne un nombre entier de joueurs entre 1 et 100.'};if(!a)return {valid:false,reason:'Choisis un scénario disponible.'};if(a.players>state.goal.players)return {valid:false,reason:'Ce scénario demande '+a.players+' joueurs.'};return E.goal({...state.goal,target,activity:a});}
function selectedGoal(target=state.goal.target){if(!Number.isInteger(state.goal.players)||state.goal.players<1||state.goal.players>100)return {valid:false,reason:'Renseigne un nombre entier de joueurs entre 1 et 100.'};if(state.goal.selected==='mixed'){const acts=state.activities.filter(a=>a.players<=state.goal.players);return E.goalMixed({...state.goal,target,activities:acts});}return calculation(findActivity(state.goal.selected),target);}
function chart(points,label,light=false){if(points.length<2)return '';const vals=points.map(p=>p[1]),lo=Math.min(0,...vals),hi=Math.max(...vals,1),range=hi-lo||1;const px=i=>32+i/(points.length-1)*436,py=v=>118-(v-lo)/range*95,path=points.map((p,i)=>(i?'L':'M')+px(i).toFixed(1)+' '+py(p[1]).toFixed(1)).join(' ');return '<div class="calc-chart"><svg viewBox="0 0 500 150" role="img" aria-label="'+esc(label)+'"><title>'+esc(label)+'</title>'+[0,0.5,1].map(t=>'<line class="gridline" x1="32" y1="'+(118-t*95)+'" x2="468" y2="'+(118-t*95)+'"/>').join('')+'<path class="area" d="'+path+' L468 118 L32 118 Z"/><path class="path" d="'+path+'"/>'+points.map((p,i)=>'<circle cx="'+px(i)+'" cy="'+py(p[1])+'" r="3.2" fill="#F5A524"><title>'+esc(p[0]+' : '+money(p[1]))+'</title></circle>').join('')+'<text x="32" y="142">'+esc(points[0][0])+'</text><text x="468" y="142" text-anchor="end">'+esc(points.at(-1)[0])+'</text></svg></div>';}
function renderGoal(){const r=selectedGoal();let html='<p class="calc-kicker">TON OBJECTIF, MIS EN CHIFFRES</p>';
 if(!r.valid)html+=warning(r.reason);else{const day=r.days??r.sessions;html+='<div class="calc-result-main">'+(r.runs===0?'Déjà atteint':day+' jour'+(day>1?'s':''))+'</div><p class="calc-result-sub">'+(r.runs===0?'Ton capital couvre déjà cet objectif.':'avec jusqu’à '+nf.format(state.goal.dailyMinutes)+' min de jeu par jour')+'</p><div class="calc-result-metrics"><div><strong>'+money(r.missing)+'</strong><span>à gagner, mise comprise</span></div><div><strong>'+hours(r.totalMinutes/60)+'</strong><span>de jeu estimées</span></div><div><strong>'+nf.format(r.runs)+'</strong><span>missions à terminer</span></div></div>';
 const start=state.goal.capital-(r.runs>0?r.investment:0),end=r.finalCapital,points=Array.from({length:6},(_,i)=>['J '+Math.round(day*i/5),start+(end-start)*i/5]);html+=chart(points,'Projection lissée du capital de '+money(start)+' à '+money(end));if(state.goal.selected==='mixed')html+='<p class="calc-note">Rotation : '+state.activities.filter(a=>a.players<=state.goal.players).map(a=>esc(a.name)).join(' → ')+'. Scénarios exclus si le groupe est insuffisant.</p>';html+='<div class="calc-chart-note"><span>Départ après mise : '+money(start)+'</span><span>Arrivée : '+money(end)+'</span></div><div class="calc-chart-controls"><label for="goal-chart-cursor">Explorer</label><input type="range" id="goal-chart-cursor" min="0" max="100" value="'+chartPercent+'"><output id="goal-chart-value">'+money(start+(end-start)*chartPercent/100)+'</output></div><p class="calc-note">'+(r.runs>0?'Rythme visé : '+money(r.missing/Math.max(1,day))+' nets / jour. Les résultats supposent des récompenses identiques à chaque réalisation.':'Tu peux choisir un cap supérieur pour poursuivre la projection.')+'</p>';}
 if(r.valid)html+='<label class="calc-progress-label" for="goal-progress">Objectif couvert par le capital actuel : '+nf.format(state.goal.target>0?Math.min(100,state.goal.capital/state.goal.target*100):100)+' %</label><progress id="goal-progress" class="calc-progress" max="100" value="'+(state.goal.target>0?Math.min(100,state.goal.capital/state.goal.target*100):100)+'"></progress>';$('goal-results').innerHTML=html;
 const routes=state.activities.map(a=>({a,r:calculation(a)})),eligible=routes.filter(x=>x.r.valid&&x.r.runs>0),fastest=eligible.length?eligible.reduce((a,b)=>a.r.totalMinutes<=b.r.totalMinutes?a:b).a.id:'';
 $('goal-routes').innerHTML=routes.map(({a,r},i)=>'<article class="calc-route '+(state.goal.selected===a.id?'is-selected':'')+'"><div class="calc-route-top"><h4>'+esc(a.name)+'</h4><span class="calc-tag">'+(a.id===fastest?'Moins de temps de jeu':'Hypothèse '+String.fromCharCode(65+i))+'</span></div><strong>'+(r.valid?hours(r.totalMinutes/60):'Non accessible')+'</strong><p>'+esc(r.valid?r.sessions+' session(s) · '+r.runs+' réalisation(s)':r.reason)+'</p><dl><dt>Mise initiale</dt><dd>'+money(a.investment)+'</dd><dt>Gain net / h, avec attente</dt><dd>'+money(E.activity(a).hourly)+'</dd></dl><button class="calc-text-button" data-scenario="'+a.id+'">Utiliser ce scénario ↗</button></article>').join('');
 const milestones=[50000,100000,500000,1000000,5000000,10000000].filter(n=>n<state.goal.target&&n>state.goal.capital);milestones.push(state.goal.target);$('goal-milestones').innerHTML=[state.goal.capital,...milestones.slice(-4)].map((n,i)=>{const g=i?selectedGoal(n):null;return '<li class="'+(!i?'done':'')+'"><b>'+money(n)+'</b><span>'+(!i?'Aujourd’hui':g.valid?'J '+g.days:'À recalculer')+'</span></li>';}).join('');
}
function renderActivities(){const mode=$('activity-filter')?.value||'hourly';let rows=activityList().map(a=>({a,r:E.activity(a)}));if(mode==='solo')rows=rows.filter(x=>x.a.players===1);if(mode==='short')rows=rows.filter(x=>x.r.valid&&x.r.activeMinutes<=30);if(mode==='accessible')rows=rows.filter(x=>x.a.investment<=state.goal.capital&&x.a.players<=state.goal.players);rows.sort((a,b)=>mode==='investment'?a.a.investment-b.a.investment:(b.r.hourly??-1e20)-(a.r.hourly??-1e20));
 $('activity-results').innerHTML=rows.length?'<div class="calc-table-wrap"><table class="calc-table"><caption class="calc-sr">Comparaison des gains nets</caption><thead><tr><th>Scénario</th><th>Net / mission</th><th>Net / heure</th><th>Temps actif</th><th>Amortissement</th><th>Statut</th></tr></thead><tbody>'+rows.map(({a,r})=>'<tr><td><strong>'+esc(a.name)+'</strong><small>'+a.players+' joueur(s) · '+money(a.investment)+' de mise</small></td><td>'+money(r.net)+'</td><td>'+money(r.hourly)+'</td><td>'+hours(r.valid?r.activeMinutes/60:null)+'</td><td>'+(r.valid&&r.paybackRuns!==null?r.paybackRuns+' mission(s)':'—')+'</td><td>'+esc(r.valid?(statusLabels[a.status]||'Non confirmé'):r.reason)+'</td></tr>').join('')+'</tbody></table></div>':'<p class="calc-empty">Aucun scénario ne correspond à ce filtre.</p>';
 const a=findActivity(state.inverse.selected),r=a&&a.players>state.goal.players?{valid:false,reason:'Ce scénario demande '+a.players+' joueurs ; ton groupe en compte '+state.goal.players+'.'}:a?E.inverse({minutes:state.inverse.minutes,activity:a,capital:state.goal.capital}):{valid:false,reason:'Scénario introuvable.'};$('inverse-results').innerHTML=r.valid?stats([['Missions terminées',nf.format(r.runs)],['Gain après mise initiale',money(r.profit)],['Capital final',money(r.finalCapital)]]):warning(r.reason);
}
function renderPurchase(){const item=catalogue.find(x=>x.id===state.purchase.itemId),known=item?.price!==null&&item?.price!==undefined,meta=item?.fieldMeta?.price;const input=$('f-purchase-price');if(input){input.readOnly=!!known;if(known){state.purchase.price=item.price;input.value=item.price;}}
 $('purchase-selection').innerHTML=item?'<div class="calc-provenance"><strong>'+esc(item.name)+'</strong> · '+(known?'Prix du catalogue : '+money(item.price)+' · '+esc(statusLabels[meta?.status]||'Non confirmé'):'Prix inconnu : saisis ton hypothèse ci-dessous.')+' <a href="'+esc(item.url)+'">Voir la fiche ↗</a><br>'+esc(meta?.source?'Source du prix : '+meta.source:'Aucune source de prix disponible.')+(meta?.verifiedAt?' · Vérifié le '+esc(meta.verifiedAt):'')+'<br><button class="calc-text-button" id="purchase-manual">Revenir à un achat libre</button></div>':'<span class="calc-tag">ACHAT LIBRE · HYPOTHÈSE UTILISATEUR</span>';
 const p=state.purchase,r=E.purchase(p),c=E.compareBuy(p);let html='<h3>La place de cet achat dans ton plan.</h3>';
 if(!r.valid)html+=warning(r.reason);else{html+=stats([['Capital après achat',money(r.remaining)],['Part de ton capital',r.capitalPercent===null?'—':nf.format(r.capitalPercent)+' %'],['Temps pour regagner le prix',hours(r.recoveryHours)]]);if(r.shortfall>0)html+=warning('Il manque '+money(r.shortfall)+' pour financer cet achat.');html+='<h4>Acheter maintenant ou économiser ?</h4><div class="calc-table-wrap"><table class="calc-table"><thead><tr><th>Vers '+money(p.target)+'</th><th>Temps estimé</th></tr></thead><tbody><tr><td>Continuer à économiser</td><td>'+hours(c.saveHours)+'</td></tr><tr><td>Acheter, puis viser l’objectif</td><td>'+(c.affordable?hours(c.buyHours):'Achat non finançable')+'</td></tr></tbody></table></div><p class="calc-note">'+(p.boostHourly>0?'Après achat : '+money(p.hourly+p.boostHourly)+' nets / h, selon ton hypothèse.':'Sans gain supplémentaire, cet achat réduit ton capital et peut retarder ton objectif.')+'</p>';if(!c.valid&&c.reason)html+=warning(c.reason);}
 $('purchase-results').innerHTML=html;
}
function normalize(s){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();}
function renderCatalogue(){const q=normalize(query);const searchable=[...catalogue,...activityList().map(a=>({...a,type:'activity',category:'activité',image:null,price:null}))];const matches=searchable.filter(x=>(typeFilter==='all'||x.type===typeFilter)&&normalize(x.name+' '+(x.brand||'')+' '+x.category).includes(q));$('catalogue-count').textContent=matches.length+' fiches';$('catalogue-results').innerHTML=matches.slice(0,catalogueLimit).map(x=>'<article class="calc-product">'+(x.image?'<img src="'+esc(x.image)+'" alt="'+esc(x.name)+'" width="480" height="270" loading="lazy" decoding="async">':'')+'<div><span class="calc-tag">'+esc(labels[x.type]||x.type)+'</span><h4>'+esc((x.brand?x.brand+' ':'')+x.name)+'</h4><p>'+(x.type==='activity'?(x.status==='manual'?'Scénario personnel · hypothèse':esc(statusLabels[x.status]||'Non confirmé')):x.price===null?'Prix à compléter':money(x.price)+' · '+esc(statusLabels[x.fieldMeta.price.status]||'Non confirmé'))+'</p>'+(x.type==='activity'?'<button class="calc-button" data-activity="'+esc(x.id)+'">Calculer mon objectif</button>':'<button class="calc-button" data-item="'+esc(x.id)+'">Simuler l’achat</button><a href="'+esc(x.url)+'">Fiche ↗</a>')+(x.type==='vehicle'?'<label class="calc-check"><input type="checkbox" data-compare="'+esc(x.id)+'" '+(compareIds.includes(x.id)?'checked':'')+'>Comparer</label>':'')+'</div></article>').join('')||'<p class="calc-empty">Aucun résultat. Essaie un autre nom ou une autre catégorie.</p>';$('catalogue-more').hidden=matches.length<=catalogueLimit;renderVehicleComparison();}
function renderVehicleComparison(){const items=compareIds.map(id=>catalogue.find(x=>x.id===id)).filter(Boolean);$('vehicle-comparison').innerHTML=items.length?'<h4>Comparaison véhicules ('+items.length+'/3)</h4><div class="calc-table-wrap"><table class="calc-table"><thead><tr><th>Critère</th>'+items.map(x=>'<th>'+esc(x.name)+' <button class="calc-text-button" data-remove-compare="'+x.id+'" aria-label="Retirer '+esc(x.name)+'">×</button></th>').join('')+'</tr></thead><tbody>'+[['Catégorie','category'],['Prix ($)','price'],['Vitesse','speed'],['Accélération','acceleration'],['Places','seats']].map(([label,k])=>'<tr><th>'+label+'</th>'+items.map(x=>'<td>'+(x[k]===null?'À compléter':esc(k==='price'?money(x[k]):x[k])+(['price','speed','acceleration','seats'].includes(k)?'<br><small>'+esc((x.fieldMeta[k]?.unit||'Unité non documentée')+' · '+(statusLabels[x.fieldMeta[k]?.status]||'Non confirmé'))+'</small>':''))+'</td>').join('')+'</tr>').join('')+'<tr><th>Prix / km/h</th>'+items.map(x=>'<td>'+(x.price!==null&&x.speed>0&&x.fieldMeta.speed.unit==='km/h'?money(x.price/x.speed):'Données insuffisantes')+'</td>').join('')+'</tr></tbody></table></div><p class="calc-note">Pas de classement qualité/prix sans prix et performances documentés. Le ratio prix/vitesse, lorsqu’il est calculable, ne mesure pas l’utilité globale d’un véhicule.</p>':'<p class="calc-empty">Coche jusqu’à trois véhicules pour comparer leurs données disponibles.</p>';}
function renderAll(){renderGoal();renderActivities();renderPurchase();renderCatalogue();T.render(state,helpers);}
function switchTab(tab,save=true){if(!tabs.includes(tab))return;state.tab=tab;if(tab==='purchase')renderCatalogue();document.querySelectorAll('[data-tab]').forEach(b=>{const active=b.dataset.tab===tab;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;});tabs.forEach(k=>$('panel-'+k).hidden=k!==tab);if(save)saveLocal();}
function renderSaved(){$('saved-list').innerHTML=(saved.length?'<h4>Favoris</h4>'+saved.map((x,i)=>'<div class="calc-saved-row"><span>☆ '+esc(x.name)+'</span><button class="calc-button" data-load="'+i+'">Ouvrir</button><button class="calc-button" data-delete="'+i+'">Retirer</button></div>').join(''):'<p class="calc-empty">Aucun favori. Enregistre un calcul pour le retrouver ici.</p>')+(recent.length?'<h4 class="calc-subsection">Calculs récents</h4>'+recent.map((x,i)=>'<div class="calc-saved-row"><span>'+esc(x.name)+'</span><button class="calc-button" data-recent="'+i+'">Reprendre</button></div>').join(''):'');}
function commitRecent(){const config=clone(state),name=money(state.goal.capital)+' → '+money(state.goal.target)+' · '+new Date().toLocaleDateString('fr-FR');recent=[{name,config},...recent.filter(x=>JSON.stringify(x.config)!==JSON.stringify(config))].slice(0,5);try{localStorage.setItem('lk-calculator-recent-v1',JSON.stringify(recent));}catch{}renderSaved();}
function changed(){for(const id of ['f-goal-selected','f-inverse-selected']){const select=$(id);for(const option of select.options){const a=findActivity(option.value);if(a)option.textContent=a.name+(a.status==='manual'?' · hypothèse':' · catalogue');}}renderGoal();renderActivities();renderPurchase();T.render(state,helpers);saveLocal();clearTimeout(saveTimer);saveTimer=setTimeout(commitRecent,1000);clearTimeout(liveTimer);liveTimer=setTimeout(()=>{$('calc-live').textContent='Résultats recalculés.';},700);}
function setPath(path,value){const keys=path.split('.');let obj=state;for(let i=0;i<keys.length-1;i++)obj=obj[keys[i]];obj[keys.at(-1)]=value;}
mount();
document.addEventListener('input',ev=>{const el=ev.target;if(el.matches('[data-field]')){const value=el.type==='number'?el.value===''?null:Number(el.value):el.value;setPath(el.dataset.field,value);changed();}if(el.id==='catalogue-search'){query=el.value;catalogueLimit=6;renderCatalogue();}if(el.id==='goal-chart-cursor'){chartPercent=Number(el.value);const r=selectedGoal();if(r.valid){const start=state.goal.capital-(r.runs?r.investment:0);$('goal-chart-value').textContent=money(start+(r.finalCapital-start)*chartPercent/100);}}});
document.addEventListener('change',ev=>{const el=ev.target;if(el.matches('select[data-field]')){setPath(el.dataset.field,el.value);changed();}if(el.id==='activity-filter')renderActivities();if(el.id==='catalogue-type'){typeFilter=el.value;catalogueLimit=6;renderCatalogue();}if(el.dataset.compare){if(el.checked){if(compareIds.length>=3){el.checked=false;notify('Compare jusqu’à trois véhicules à la fois.');return;}compareIds.push(el.dataset.compare);}else compareIds=compareIds.filter(id=>id!==el.dataset.compare);renderVehicleComparison();}});
document.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;const d=b.dataset;if(d.tab)switchTab(d.tab);if(d.open){switchTab(d.open);$('tab-'+d.open).focus();}if(d.target){state.goal.target=Number(d.target);$('f-goal-target').value=d.target;changed();}if(d.scenario){state.goal.selected=d.scenario;$('f-goal-selected').value=d.scenario;changed();}if(d.activity){state.goal.selected=d.activity;$('f-goal-selected').value=d.activity;changed();switchTab('goal');$('tab-goal').focus();}if(d.item){const item=catalogue.find(x=>x.id===d.item);state.purchase.itemId=item.id;state.purchase.price=item.price;state.purchase.capital=state.goal.capital;state.purchase.target=state.goal.target;$('f-purchase-price').value=item.price??'';$('f-purchase-capital').value=state.goal.capital;$('f-purchase-target').value=state.goal.target;renderPurchase();saveLocal();$('f-purchase-price').focus();$('panel-purchase').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}if(b.id==='purchase-manual'){state.purchase.itemId='';renderPurchase();saveLocal();}if(b.id==='catalogue-more'){catalogueLimit+=12;renderCatalogue();}if(d.removeCompare){compareIds=compareIds.filter(id=>id!==d.removeCompare);renderCatalogue();}if(d.load!==undefined){state=clone(saved[Number(d.load)].config);mount();saveLocal();notify('Favori restauré.');}if(d.recent!==undefined){state=clone(recent[Number(d.recent)].config);mount();saveLocal();notify('Calcul récent restauré.');}if(d.delete!==undefined){saved.splice(Number(d.delete),1);try{localStorage.setItem('lk-calculator-saved-v1',JSON.stringify(saved));}catch{}renderSaved();}});
document.querySelector('.calc-tabs').addEventListener('keydown',ev=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(ev.key))return;ev.preventDefault();const i=tabs.indexOf(state.tab),next=ev.key==='Home'?0:ev.key==='End'?tabs.length-1:(i+(ev.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;switchTab(tabs[next]);$('tab-'+tabs[next]).focus();});
$('calc-save').addEventListener('click',()=>{const name=money(state.goal.capital)+' → '+money(state.goal.target)+' · '+({goal:'Objectif',activities:'Activités',roi:'Rentabilité',purchase:'Achats',budget:'Budget',order:'Ordre d’achat'})[state.tab];saved.unshift({name,config:clone(state)});saved=saved.slice(0,12);try{localStorage.setItem('lk-calculator-saved-v1',JSON.stringify(saved));notify('Calcul ajouté aux favoris sur cet appareil.');}catch{notify('Le favori reste en mémoire. Exporte la configuration pour la conserver.');}renderSaved();});
$('calc-share').addEventListener('click',async()=>{const url=new URL(location.href);url.hash='plan='+encodeURIComponent(JSON.stringify(state));history.replaceState(null,'',url);await window.LK.copy(url.href,$('calc-share'),'Lien copié ✓');commitRecent();});
$('calc-export').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='leonidakit-calcul.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Configuration exportée.');});
$('calc-import').addEventListener('change',async ev=>{const file=ev.target.files?.[0];if(!file)return;try{if(file.size>40000)throw Error('Fichier trop volumineux.');const incoming=validConfig(JSON.parse(await file.text()));state=incoming;mount();saveLocal();notify('Configuration importée.');}catch(error){notify('Import refusé : '+error.message);}ev.target.value='';});
$('calc-reset').addEventListener('click',()=>{state=clone(initial);history.replaceState(null,'',location.pathname+location.search);mount();saveLocal();notify('Paramètres d’exemple restaurés. Tes favoris sont conservés.');});
window.addEventListener('hashchange',()=>{loadHash();mount();});
if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&document.querySelector('.calc-hero-image')){const image=document.querySelector('.calc-hero-image');let queued=false;window.addEventListener('scroll',()=>{if(queued||window.scrollY>650)return;queued=true;requestAnimationFrame(()=>{image.style.transform='translateY('+Math.min(90,window.scrollY*.15)+'px) scale(1.12)';queued=false;});},{passive:true});}
})();
