/* Leonidakit : interface du calculateur. Les calculs restent dans LKCalcEngine. */
(function () {
'use strict';
const E=window.LKCalcEngine,D=window.LKCalcData,B=window.LKCalcScenario,$=id=>document.getElementById(id),esc=window.LK.esc;
if(!E||!D||!B){$('calc-panels').innerHTML='<p class="calc-warning">Le calculateur n’a pas pu charger ses fichiers. Recharge la page.</p>';return;}
const clone=x=>JSON.parse(JSON.stringify(x)),nf=new Intl.NumberFormat('fr-FR',{maximumFractionDigits:2});
const money=n=>Number.isFinite(n)?nf.format(n)+'\u00a0$':'—';
const hours=n=>{if(!Number.isFinite(n))return '—';const m=Math.ceil(n*60-1e-8);return m<60?m+' min':Math.floor(m/60)+' h'+(m%60?' '+String(m%60).padStart(2,'0'):'');};
const warning=s=>'<p class="calc-warning">'+esc(s||'Remplis les cases pour voir ta réponse.')+'</p>';
const stats=items=>'<div class="calc-stats">'+items.map(([label,value])=>'<div class="calc-stat"><strong>'+esc(value)+'</strong><span>'+esc(label)+'</span></div>').join('')+'</div>';
const tabs=['goal','purchase','session','budget','order','roi','activities','plan'];
const tabNames=B.names;
const labels={vehicle:'Véhicule',weapon:'Équipement',property:'Demeure',business:'Entreprise',place:'Lieu',hideout:'Planque',style:'Vêtements et style',customization:'Personnalisation',consumable:'Consommable',ammo:'Munitions',housing:'Logement',activity:'Activité'};
const tutorialParams=new URLSearchParams(location.search),tutorialChapters=['demarrer','modes','objectif','activites','temps','achats','comparateur','ordre','rentabilite','budget','carnets','plan','sources','faq'];
const tutorialChapter=tutorialParams.get('from')==='tuto'&&tutorialChapters.includes(tutorialParams.get('chapter'))?tutorialParams.get('chapter'):null;
const statusLabels={unknown:'À compléter',unverified:'Non confirmé',manual:'Valeur personnelle',official:'Officiel',verified:'Mesuré et vérifié',estimated:'Estimation',observed:'Repéré',community:'Communautaire','source-listed':'Source indiquée'};
const catalogue=D.catalogue(),sourceActivities=D.activities();
let fingerprint=2166136261;for(const c of JSON.stringify([catalogue.map(({imageFallback,schemaImage,...entry})=>entry),sourceActivities])){fingerprint^=c.charCodeAt(0);fingerprint=Math.imul(fingerprint,16777619);}
const dataVersion='schema'+D.meta.schemaVersion+'-'+(fingerprint>>>0).toString(16);
const initial=B.initial(dataVersion,D.presets);
let state=clone(initial),saved=[],recent=[],reference=null,undo=null,saveTimer,liveTimer,catalogueLimit=6,firstResult=false,sessionCache={key:'',value:null},answerTimer,noticeTimer;
function notify(message){$('calc-live').textContent=message;window.LK.status(message);clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>{const box=$('lk-status');if(box&&box.textContent===message)box.textContent='';},4500);}
function emit(name){document.dispatchEvent(new CustomEvent('leonidakit:calculator',{detail:{event:name,tool:state.tab,mode:state.mode}}));}
function parseNumber(value){if(E.parseLocalizedNumber){const parsed=E.parseLocalizedNumber(value);return parsed.valid?parsed.value:null;}if(typeof value==='number')return Number.isFinite(value)?value:null;const s=String(value).trim().replace(/[\s\u00a0\u202f]/g,'');return /^-?\d+(?:[,.]\d+)?$/.test(s)?Number(s.replace(',','.')):null;}
function field(path,label,value,opts={}){const id=opts.id||'f-'+path.replaceAll('.','-'),text=opts.type==='text';return '<div class="calc-field'+(opts.wide?' wide':'')+'"><label class="calc-label" for="'+id+'">'+esc(label)+'</label><input id="'+id+'" data-field="'+path+'" type="text" '+(text?'maxlength="100"':'data-number="1" '+(opts.integer?'data-integer="1" inputmode="numeric"':'inputmode="decimal"')+' maxlength="25" data-min="'+(opts.min??0)+'" data-max="'+(opts.max??1e12)+'"')+' value="'+esc(value??'')+'"'+' aria-describedby="'+id+'-error'+(opts.hint?' '+id+'-hint':'')+'">'+(!text&&/\$/.test(label)?'<span class="lk-echo" data-echo="'+id+'" aria-hidden="true"></span>':'')+ (opts.hint?'<small id="'+id+'-hint">'+esc(opts.hint)+'</small>':'')+'<small id="'+id+'-error" class="b-field-error" hidden></small></div>';}
const helpers={E,esc,money,hours,field,stats,warning};
function step(n,q,inner){return '<div class="calc-step wide" data-step="'+n+'" data-question="'+esc(q)+'"><span class="calc-step-n" aria-hidden="true">'+n+'</span><div class="calc-step-body">'+inner+'</div></div>';}
function selectField(path,label,options){const id='f-'+path.replaceAll('.','-');return '<div class="calc-field wide"><label class="calc-label" for="'+id+'">'+esc(label)+'</label><select id="'+id+'" data-field="'+path+'">'+options+'</select></div>';}
const option=(v,label,selected)=>'<option value="'+esc(v)+'"'+(v===selected?' selected':'')+'>'+esc(label)+'</option>';
function validConfig(raw){return B.validate(raw,initial);}
function loadLocal(){try{const raw=localStorage.getItem('lk-calculator-v1');if(raw)state=validConfig(JSON.parse(raw));}catch{notify('Sauvegarde illisible : le calcul d’exemple reste disponible.');}}
function persist(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{notify('Sauvegarde sur cet appareil indisponible. Exporte le fichier JSON pour conserver ton plan.');return false;}}
function saveLocal(){state.dataVersion=dataVersion;try{validConfig(state);}catch{return false;}if(tutorialChapter){const q=new URLSearchParams({from:'tuto',chapter:tutorialChapter,tool:state.tab,mode:state.views[state.tab]==='advanced'?'expert':'simple'});if(tutorialParams.get('focus')==='carnets')q.set('focus','carnets');history.replaceState(null,'',location.pathname+'?'+q+'#atelier');}else if(location.search||location.hash.startsWith('#plan='))history.replaceState(null,'',location.pathname+(location.hash==='#atelier'?'#atelier':''));return persist('lk-calculator-v1',state);}
function loadHash(){if(!location.hash.startsWith('#plan='))return false;try{if(location.hash.length>24000)throw Error('Lien trop long : utilise un fichier JSON.');state=validConfig(JSON.parse(decodeURIComponent(location.hash.slice(6))));notify('Calcul partagé ouvert. Tu peux changer tous les chiffres.');return true;}catch(error){notify('Lien invalide : '+error.message);return false;}}
function importContext(){const q=new URLSearchParams(location.search);if(tabs.includes(q.get('tool')))state.tab=q.get('tool');
 for(const [param,key,max] of [['capital','capital',1e12],['target','target',1e12],['hourly','hourly',1e12],['minutes','dailyMinutes',1440]]){if(q.has(param)){const n=parseNumber(q.get(param));if(n!==null&&n>=0&&n<=max){state.goal[key]=n;if(param==='minutes'&&state.tab==='session')state.session.minutes=n;if(param==='hourly')state.model='continuous';}else notify('Un paramètre de lien invalide a été ignoré.');}}
 const id=q.get('id'),type=q.get('type'),map={vehicules:'vehicle',armes:'weapon',demeures:'property',entreprises:'business',lieux:'place',planques:'hideout',vehicle:'vehicle',weapon:'weapon',property:'property',business:'business',place:'place',hideout:'hideout',style:'style',customization:'customization'};
 if(q.has('mode')){const mode={simple:'quick',expert:'advanced'}[q.get('mode')];if(mode)state.views[state.tab]=mode;else notify('Mode de lien invalide ignoré.');}
 const match=(value)=>catalogue.find(x=>(x.id===value||x.id===(map[type]+':'+value)||x.id.endsWith(':'+value))&&(!map[type]||x.type===map[type]));
 if(id){const item=match(id);if(item){if(!selectItem(item,false))return;if(q.get('tool')==='roi'){state.tab='roi';state.roi.key=state.purchase.key;state.roi.mode='estimate';state.roi.activityIds=[...state.activities,...sourceActivities].filter(a=>item.activityIds.includes(a.id)||a.purchaseIds?.includes(item.id)).map(a=>a.id);}notify(item.name+' est choisi. Écris le prix que tu imagines.');}else notify('Cette fiche n’existe plus dans le catalogue. Recherche un autre élément ou saisis un achat libre.');}
 if(q.has('ids')){state.catalogue.compareIds=q.get('ids').split(',').slice(0,3).map(match).filter(Boolean).map(x=>x.id);state.tab='purchase';if(!state.catalogue.compareIds.length)notify('La sélection partagée ne contient aucune fiche disponible.');}
}
loadLocal();const shared=loadHash();if(!shared)importContext();
const activityList=()=>B.activities(state,sourceActivities);
const findActivity=id=>activityList().find(a=>a.id===id);
function activityOptions(selected,includeMixed=false){return (!findActivity(selected)&&!(includeMixed&&selected==='mixed')?option(selected,'Activité introuvable : choisis-en une autre',selected):'')+activityList().map(a=>option(a.id,a.name+(a.status==='manual'?' · à moi':' · du site'),selected)).join('')+(includeMixed?option('mixed','Faire mes activités chacune à leur tour',selected):'');}
function modeUI(){state.mode=state.views[state.tab]||'quick';workspace.mode();document.querySelectorAll('.calc-guidance').forEach(n=>n.hidden=true);document.querySelectorAll('details.calc-advanced').forEach(n=>n.open=state.mode==='advanced');}
function mount(){
 $('calc-panels').innerHTML=`<section class="calc-panel" id="panel-goal" role="tabpanel" aria-labelledby="tab-goal">
 <div class="calc-grid"><div class="calc-card calc-goal-card"><p class="calc-kicker">MON OBJECTIF</p><h3>Combien de temps pour avoir mon argent ?</h3><p class="calc-card-desc">Remplis les 4 cases. La réponse s’affiche tout de suite, sans compte.</p><div class="calc-fields calc-steps">
 <div class="calc-step wide" data-step="1" data-question="Combien d’argent as-tu maintenant ?"><span class="calc-step-n" aria-hidden="true">1</span><div class="calc-step-body">${field('goal.capital','J’ai déjà ($)',state.goal.capital,{hint:'L’argent que tu as maintenant dans le jeu.'})}</div></div>
 <div class="calc-step wide" data-step="2" data-question="Combien veux-tu avoir ?"><span class="calc-step-n" aria-hidden="true">2</span><div class="calc-step-body">${field('goal.target','Je veux avoir ($)',state.goal.target,{hint:'Choisis un bouton, bouge la réglette ou écris ta somme.'})}<div class="calc-presets">${[100000,500000,1000000,5000000,10000000].map(n=>'<button type="button" class="calc-chip" data-target="'+n+'">'+(n>=1e6?n/1e6+' M':n/1000+' k')+' $</button>').join('')}</div><div class="lk-goal-slider"><input type="range" id="lk-goal-range" min="0" max="1000" value="500" aria-label="Régler mon objectif avec la réglette"><span id="lk-goal-range-v" aria-hidden="true"></span></div></div></div>
 <div class="calc-step wide" data-step="3" data-question="Combien gagnes-tu en une heure de jeu ?"><span class="calc-step-n" aria-hidden="true">3</span><div class="calc-step-body">${selectField('model','Comment gagnes-tu ton argent ?',option('continuous','Petit à petit, par heure de jeu',state.model)+option('cycles','À la fin de chaque mission',state.model))}<div class="wide" id="goal-continuous-fields" ${state.model!=='continuous'?'hidden':''}>${field('goal.hourly','Je gagne à peu près ($ par heure de jeu)',state.goal.hourly,{hint:'Ce qu’il te reste une fois tes frais payés. C’est ton chiffre à toi, pas un chiffre officiel du jeu.'})}<details class="lk-helper"><summary>Je ne sais pas combien je gagne</summary><div class="lk-helper-body"><p>Pense à ta dernière mission.</p><div class="calc-fields"><div class="calc-field"><label class="calc-label" for="lk-help-reward">Elle m’a rapporté ($)</label><input id="lk-help-reward" type="text" inputmode="decimal" maxlength="25" autocomplete="off"></div><div class="calc-field"><label class="calc-label" for="lk-help-minutes">Elle a duré (minutes)</label><input id="lk-help-minutes" type="text" inputmode="decimal" maxlength="6" autocomplete="off"></div></div><p class="lk-helper-out" id="lk-help-out" role="status">Écris les deux nombres : on calcule ton gain par heure.</p><button type="button" class="calc-button" id="lk-help-apply" disabled>Utiliser ce chiffre</button></div></details></div><div class="wide" id="goal-cycle-fields" ${state.model!=='cycles'?'hidden':''}>${selectField('goal.selected','Mon activité',activityOptions(state.goal.selected,true))}<button type="button" class="calc-text-button" data-open="activities">Changer les gains et les durées de mes activités ↗</button></div></div></div>
 <div class="calc-step wide" data-step="4" data-question="Combien de temps joues-tu par jour ?"><span class="calc-step-n" aria-hidden="true">4</span><div class="calc-step-body">${field('goal.dailyMinutes','Je joue chaque jour (minutes)',state.goal.dailyMinutes,{min:1,max:1440,hint:'60 minutes = 1 heure.'})}<div class="calc-presets">${[30,60,120,180].map(m=>'<button type="button" class="calc-chip" data-daily="'+m+'">'+(m<60?m+' min':m/60+' h')+'</button>').join('')}</div></div></div>
 </div><details class="calc-advanced"><summary>Garder de l’argent de côté</summary><div class="calc-fields">${field('goal.reserve','Argent que je garde de côté, en plus de mon objectif ($)',state.goal.reserve,{hint:'Cet argent ne sera pas dépensé. On l’ajoute à ton objectif.'})}${field('goal.players','Nombre de joueurs dans mon équipe',state.goal.players,{min:1,max:100,hint:'Sert seulement pour tes activités à plusieurs. Laisse 1 si tu joues seul.'})}</div></details><p class="calc-note">Les nombres déjà écrits sont des exemples. Remplace-les par les tiens.</p></div><div class="calc-card calc-result" id="goal-results" tabindex="-1"></div></div>
 <div id="reference-results" class="calc-reference"></div><details class="calc-advanced"><summary>Comparer mes activités et tester d’autres chiffres</summary><div id="goal-sensitivity"></div><div class="calc-route-head"><h3>Trois chemins pour le même objectif.</h3><p>Même objectif, même argent de départ. Chaque activité a ses frais et ses durées.</p></div><div class="calc-routes" id="goal-routes"></div></details></section>
 <section class="calc-panel" id="panel-session" role="tabpanel" aria-labelledby="tab-session" hidden><div class="calc-guidance" hidden><b>Un programme qui tient dans ton temps de jeu</b><p>Dis combien de temps tu as et quelles activités tu veux bien faire. On te propose un ordre, sans toucher à l’argent que tu gardes de côté.</p></div><div class="calc-grid"><div class="calc-card"><p class="calc-kicker">MON TEMPS DE JEU</p><h3>Qu’est-ce que je fais ce soir ?</h3><p class="calc-card-desc">Dis combien de temps tu as. On te propose un programme avec tes activités, et on te dit ce que ça fait avancer sur ton objectif.</p><div class="calc-fields calc-steps">${step(1,'Combien de temps as-tu ?',field('session.minutes','J’ai combien de temps ? (minutes)',state.session.minutes,{max:1440})+'<div class="calc-presets">'+[15,30,45,60,90].map(m=>'<button type="button" class="calc-chip" data-session-minutes="'+m+'">'+m+' min</button>').join('')+'</div>')}${step(2,'Quelles activités veux-tu bien faire ?','<fieldset class="calc-play-mode"><legend>Je joue</legend><div class="calc-play-choices"><label><input type="radio" name="session-play-mode" value="solo" '+(state.goal.players===1?'checked':'')+'> Seul</label><label><input type="radio" name="session-play-mode" value="group" '+(state.goal.players!==1?'checked':'')+'> À plusieurs</label></div><div class="calc-group-size" '+(state.goal.players===1?'hidden':'')+'>'+field('goal.players','Nous sommes (moi compris)',state.goal.players,{id:'session-players',min:1,max:100,integer:true,hint:'Le même nombre que dans Mon objectif.'})+'</div></fieldset>'+'<fieldset class="calc-session-options"><legend>Les activités que je veux bien faire</legend>'+activityList().map(a=>'<label class="calc-check"><input type="checkbox" data-session-activity="'+esc(a.id)+'" '+(state.session.enabled.includes(a.id)?'checked':'')+'> '+esc(a.name)+'</label>').join('')+'</fieldset><button type="button" class="calc-text-button" data-open="activities">Écrire ou changer mes activités ↗</button>')}${field('session.maxRepeat','Même activité à la suite, au maximum',state.session.maxRepeat,{min:1,max:256,hint:'Mets 1 si tu veux changer d’activité à chaque fois.'})}</div><p class="calc-note" id="session-capital-summary"></p><button type="button" class="calc-text-button" data-open="goal">Changer mon argent et ce que je garde de côté ↗</button></div><div class="calc-card calc-result" id="session-results"></div></div><div id="session-timeline"></div></section>
 <section class="calc-panel" id="panel-activities" role="tabpanel" aria-labelledby="tab-activities" hidden>
 <div class="calc-grid"><div class="calc-card calc-activity-setup"><p class="calc-kicker">MES ACTIVITÉS / MON TEMPS DE JEU</p><h3>Combien puis-je gagner ?</h3><p class="calc-card-desc">Choisis ton scénario personnel et le temps dont tu disposes.</p>
 <fieldset class="calc-play-mode"><legend>Comment je joue</legend><div class="calc-play-choices"><label><input type="radio" name="activity-play-mode" value="solo" ${state.goal.players===1?'checked':''}> Je joue seul</label><label><input type="radio" name="activity-play-mode" value="group" ${state.goal.players!==1?'checked':''}> Je joue à plusieurs</label></div><div id="activity-group-size" ${state.goal.players===1?'hidden':''}>${field('goal.players','Nombre de joueurs, moi compris',state.goal.players,{id:'activity-players',min:1,max:100,integer:true,hint:'De 1 à 100. Même groupe que dans Mon objectif.'})}</div></fieldset>
 <div class="calc-presets calc-activity-presets" aria-label="Charger un exemple personnel">${D.presets.map((a,i)=>'<button type="button" class="calc-chip" data-activity-example="'+a.id+'">Exemple '+String.fromCharCode(65+i)+' · solo</button>').join('')}</div><p class="calc-note">Les exemples rétablissent leur scénario, le capital, la réserve et la durée. Ce sont des hypothèses personnelles.</p>
 <div class="calc-fields">${field('goal.capital','Capital actuel ($)',state.goal.capital,{id:'activity-capital'})}${field('goal.reserve','Réserve à conserver ($)',state.goal.reserve,{id:'activity-reserve'})}${field('inverse.minutes','J’ai combien de temps ? (minutes)',state.inverse.minutes,{max:1e6})}${selectField('inverse.selected','Activité à refaire',activityOptions(state.inverse.selected))}</div><button type="button" class="calc-button primary" id="activity-answer">Voir ma réponse <span aria-hidden="true">↗</span></button><p class="calc-note">Capital, réserve et groupe sont partagés avec Mon objectif.</p></div>
 <div class="calc-card calc-activity-answer" id="inverse-results" role="region" aria-label="Ma réponse"></div></div><p class="calc-sr" id="activity-live" role="status" aria-live="polite" aria-atomic="true"></p>
 <div class="calc-card calc-subsection"><p class="calc-kicker">MES ACTIVITÉS</p><h3>Écris ce que tes activités te rapportent.</h3><p class="calc-card-desc">Tu paies tes frais avant de commencer. Tu reçois ta récompense à la fin. La préparation est à refaire à chaque fois.</p><div class="calc-confirm-data">${sourceActivities.length?sourceActivities.length+' activité(s) avec de vrais chiffres vérifiés.':'Le jeu n’est pas encore sorti : aucun vrai chiffre n’existe.'} Les trois activités ci-dessous sont des exemples. Remplace-les par les tiennes.</div><div class="calc-activity-editors">${state.activities.map((a,i)=>'<details class="calc-activity-editor" '+(i===0?'open':'')+'><summary>Activité '+String.fromCharCode(65+i)+' · '+esc(a.name)+'</summary><div class="calc-fields">'+field('activities.'+i+'.name','Nom de mon activité',a.name,{type:'text',wide:true})+[['reward','Récompense de la mission ($)'],['cost','Ce que je paie à chaque fois ($)'],['duration','Durée de la mission (min)'],['prep','Préparation (min)'],['cooldown','Attente avant de recommencer (min)'],['share','Ma part de la récompense (%)'],['investment','À acheter une seule fois avant de commencer ($)'],['players','Joueurs qu’il faut']].map(([k,l])=>field('activities.'+i+'.'+k,l,a[k],{min:k==='players'?1:0,integer:k==='players',max:k==='share'||k==='players'?100:k==='duration'||k==='prep'||k==='cooldown'?1e6:1e12})).join('')+'</div><label class="calc-check"><input type="checkbox" data-owned="'+i+'" '+(a.owned?'checked':'')+'> Je l’ai déjà acheté : ne pas le compter une deuxième fois</label></details>').join('')}</div><div class="calc-toolbar"><label for="activity-filter">Afficher</label><select id="activity-filter"><option value="hourly">Ce qui rapporte le plus par heure</option><option value="investment">Le moins cher pour commencer</option><option value="solo">Faisable tout seul</option><option value="short">Moins de 30 minutes</option><option value="accessible">Que je peux payer maintenant</option></select></div><div id="activity-results"></div></div></section>
 <section class="calc-panel" id="panel-purchase" role="tabpanel" aria-labelledby="tab-purchase" hidden><div class="calc-grid"><div class="calc-card"><p class="calc-kicker">MES ACHATS</p><h3>Est-ce que je peux l’acheter ?</h3><div id="purchase-selection"></div><div class="calc-fields calc-steps">${workspace.purchaseFields()}</div><p class="calc-note">Une voiture ne rapporte pas d’argent toute seule. Si c’est un achat pour le plaisir, laisse 0 dans « me fait gagner en plus ».</p></div><div class="calc-card calc-result" id="purchase-results"></div></div><div class="calc-card calc-subsection"><h3>Trouve ton prochain achat.</h3><p class="calc-card-desc">Les prix du jeu ne sont pas encore connus. Choisis une fiche et écris le prix que tu imagines.</p><label class="calc-label" for="catalogue-search">Rechercher un nom, une marque ou une catégorie</label><input class="calc-search-input" id="catalogue-search" type="search" maxlength="100" value="${esc(state.catalogue.query)}" placeholder="Véhicule, arme, entreprise…"><div class="calc-fields"><div class="calc-field"><label for="catalogue-type">Catégorie</label><select id="catalogue-type">${option('all','Toutes les catégories',state.catalogue.type)+Object.entries(labels).map(([k,v])=>option(k,v,state.catalogue.type)).join('')}</select></div><div class="calc-field"><label for="catalogue-status">Prix connu ou pas</label><select id="catalogue-status">${[['all','Tous les statuts'],['known','Prix renseigné'],['unknown','Prix inconnu'],['manual','Valeur personnelle'],['official','Officiel'],['verified','Mesuré et vérifié'],['estimated','Estimation']].map(([k,v])=>option(k,v,state.catalogue.status)).join('')}</select></div><div class="calc-field"><label for="catalogue-budget">Prix maximum connu ($)</label><input id="catalogue-budget" type="text" inputmode="decimal" maxlength="25" value="${esc(state.catalogue.maxPrice??'')}" placeholder="Sans limite"></div><div class="calc-field"><label for="catalogue-sort">Trier</label><select id="catalogue-sort">${[['name','Nom : A → Z'],['price-up','Prix connu croissant'],['price-down','Prix connu décroissant']].map(([k,v])=>option(k,v,state.catalogue.sort)).join('')}</select></div></div><label class="calc-check"><input id="catalogue-favorites" type="checkbox" ${state.catalogue.favoritesOnly?'checked':''}> Mes fiches favorites</label><div id="catalogue-filter-chips" class="calc-filter-chips"></div><p id="catalogue-count" class="calc-tag" role="status"></p><div id="catalogue-results" class="calc-catalogue"></div><button class="calc-button" id="catalogue-more">Afficher plus</button><div class="calc-subsection" id="vehicle-comparison"></div></div></section>`+workspace.markup();
 workspace.decorate();modeUI();renderAll();switchTab(state.tab,false);renderSaved();
}
function calculation(a,target=state.goal.target,g=state.goal){if(!Number.isFinite(target)||target<0||!Number.isFinite(g.reserve)||g.reserve<0)return{valid:false,reason:'Écris un objectif et un argent de côté corrects.'};if(!Number.isInteger(g.players)||g.players<1||g.players>100)return{valid:false,reason:'Écris un nombre de joueurs entre 1 et 100, sans virgule.'};if(!a)return{valid:false,reason:'Choisis une activité dans la liste.'};if(a.players>g.players)return{valid:false,reason:'Cette activité se joue à '+a.players+' joueurs.'};return E.goal({...g,target:target+g.reserve,reserve:g.reserve,activity:a});}
function selectedGoal(config=state){return B.goal(config,sourceActivities);}
function chart(points,label){if(window.LKCalcVisuals)return window.LKCalcVisuals.create(helpers).plot('c-goal-curve',label,points.map(p=>({label:p[0],value:p[1]})),'$');if(points.length<2)return '';const vals=points.map(p=>p[1]),lo=Math.min(0,...vals),hi=Math.max(...vals,1),span=hi-lo||1,px=i=>60+i/(points.length-1)*400,py=v=>128-(v-lo)/span*100;const path=points.map((p,i)=>(i?'L':'M')+px(i).toFixed(1)+' '+py(p[1]).toFixed(1)).join(' ');return '<figure class="calc-chart"><svg viewBox="0 0 500 162" role="img" aria-label="'+esc(label)+'"><title>'+esc(label)+'</title>'+[0,.5,1].map(t=>'<line class="gridline" x1="60" y1="'+(128-t*100)+'" x2="460" y2="'+(128-t*100)+'"/>').join('')+'<text x="4" y="28">$</text><text x="4" y="130">'+nf.format(lo)+'</text><path class="area" d="'+path+' L460 128 L60 128 Z"/><path class="path" d="'+path+'"/><text x="60" y="155">'+esc(points[0][0])+'</text><text x="460" y="155" text-anchor="end">'+esc(points.at(-1)[0])+'</text></svg><figcaption>'+esc(label)+'</figcaption></figure>';}
function renderGoal(){
 const r=selectedGoal(),g=state.goal,continuous=state.model==='continuous';let html='<p class="calc-kicker">MA RÉPONSE</p><span class="calc-tag">CALCULÉ AVEC TES CHIFFRES</span>';
 if(!r.valid){html+=warning(r.reason)+'<p class="calc-note">Corrige la case signalée pour voir ta réponse.</p>';}else{
  const reached=r.missing===0,total=r.totalMinutes??0,days=r.days??r.sessions;
  html+='<p class="calc-answer b-answer" data-short="'+esc(reached?'C’est bon !':hours(total/60)+' de jeu · '+nf.format(days)+' jour'+(days>1?'s':''))+'">'+(reached?'Bravo, tu as déjà assez d’argent pour ton objectif.':'Il te manque <b>'+money(r.missing)+'</b>'+(continuous?'':' (achat de départ compris)')+'. En jouant <b>'+hours(g.dailyMinutes/60)+'</b> par jour, tu y arrives en <b><span data-c-number="goal-sessions">'+nf.format(days)+'</span> jour'+(days>1?'s':'')+'</b>.')+'</p>';
  html+='<div class="calc-result-main">'+(reached?'C’est bon !':hours(total/60))+'</div><p class="calc-result-sub">'+(reached?'Tu peux choisir un objectif plus grand.':'de jeu en tout')+'</p>';
  html+=stats([['Il te manque',money(r.missing)],['Tu auras à la fin',money(r.finalCapital)],['Tu gardes de côté',money(g.reserve)]]);
  const active=r.activeMinutes??(continuous?total:null),wait=r.waitMinutes??(active===null?null:total-active);
  if(!continuous)html+=stats([['Nombre de missions',nf.format(r.runs)],['Temps de jeu',hours(active===null?null:active/60)],['Temps d’attente',hours(wait===null?null:wait/60)]]);
  const start=g.capital-(r.investment||0);
  if(continuous&&!reached){const points=Array.from({length:5},(_,i)=>[hours(total*i/4/60),start+(r.finalCapital-start)*i/4]);html+=chart(points,'Ton argent : '+money(start)+' au départ, '+money(r.finalCapital)+' après '+hours(total/60)+' de jeu, si tu gagnes toujours pareil.');}
  if(!continuous&&!reached)html+='<p class="calc-note">Tu es payé à la fin de chaque mission. Une mission pas finie ne rapporte rien.</p>';
  html+='<div class="calc-next-action"><strong>'+ (reached?'Et maintenant ?':'Ta prochaine étape')+'</strong><p>'+esc(reached?'Choisis un nouvel objectif ou prépare ton prochain achat.':continuous?'Joue '+hours(Math.min(g.dailyMinutes,total)/60)+', puis reviens écrire combien tu as maintenant dans la case « J’ai déjà ».':'Commence par '+(g.selected==='mixed'?'la première activité de ta rotation':findActivity(g.selected)?.name||'ton activité')+'. Il te faut l’argent des frais avant de commencer.')+'</p></div>';
  html+='<label class="calc-progress-label" for="goal-progress">Tu as déjà '+nf.format(g.target>0?Math.max(0,Math.min(100,(g.capital-g.reserve)/g.target*100)):100)+' % de ton objectif</label><progress id="goal-progress" class="calc-progress" max="100" value="'+(g.target>0?Math.max(0,Math.min(100,(g.capital-g.reserve)/g.target*100)):100)+'"></progress>';
  html+='<details><summary>Comment est-ce calculé ?</summary><p class="calc-note">'+(continuous?'Ce qu’il te manque = ce que tu veux − ce que tu as (sans compter l’argent mis de côté). Temps de jeu = ce qu’il te manque ÷ ce que tu gagnes par heure. Nombre de jours = temps de jeu ÷ ton temps de jeu par jour, arrondi au-dessus.':'Objectif total = ce que tu veux + l’argent mis de côté. Ce qu’il faut acheter avant de commencer est payé au départ. Chaque mission rapporte sa récompense × ta part − tes frais, et les frais se paient avant. Si tu alternes, les activités se suivent dans l’ordre A, B, C. Une mission se fait en entier ou pas du tout, et les attentes sont comptées.')+' On compte une partie par jour : tu finis le jour '+days+' si tu joues tous les jours. Rien n’est relié à ton compte GTA.</p></details>';
  if(!firstResult){emit('first_valid_result');firstResult=true;}
 }
 $('goal-results').innerHTML=html;
 const scenarios=state.activities.map(a=>({...a,investment:a.owned?0:a.investment})).map(a=>({a,r:calculation(a)}));
 const valid=scenarios.filter(x=>x.r.valid&&x.r.missing>0),fastest=valid.slice().sort((a,b)=>a.r.totalMinutes-b.r.totalMinutes)[0]?.a.id,cheapest=valid.slice().sort((a,b)=>a.a.investment-b.a.investment)[0]?.a.id;
 $('goal-routes').innerHTML=scenarios.map(({a,r})=>'<article class="calc-route '+(state.model==='cycles'&&g.selected===a.id?'is-selected':'')+'"><h4>'+esc(a.name)+'</h4><span class="calc-tag">'+(a.id===fastest?'Le plus rapide des 3':a.id===cheapest?'Le moins cher pour commencer':'Entre les deux')+'</span><strong>'+(r.valid?hours(r.totalMinutes/60):'Pas possible')+'</strong><p>'+esc(r.valid?r.sessions+' jour(s) de jeu · '+r.runs+' mission(s)':r.reason)+'</p><dl><dt>À acheter avant de commencer</dt><dd>'+money(a.investment)+'</dd><dt>Durée d’une mission, préparation comprise</dt><dd>'+hours((a.duration+a.prep)/60)+'</dd></dl><button class="calc-text-button" data-scenario="'+a.id+'">Choisir cette activité ↗</button></article>').join('');
 $('goal-sensitivity').innerHTML=continuous&&r.valid?'<h3>Et si je gagne plus, ou moins ?</h3><div class="calc-routes">'+[.8,1,1.2].map(m=>{const v=E.goalContinuous({...g,hourly:g.hourly*m});return'<article class="calc-route"><span class="calc-tag">'+(m===1?'TON CHIFFRE':m<1?'20 % DE MOINS':'20 % DE PLUS')+'</span><strong>'+hours(v.valid?v.totalMinutes/60:null)+'</strong><p>'+money(g.hourly*m)+' par heure</p></article>';}).join('')+'</div><p class="calc-note">On refait le calcul avec 20 % de moins et 20 % de plus. Ce n’est pas une prévision.</p>':'';
 renderReference();
}
function renderReference(){$('reference-results').innerHTML='';}
function renderActivities(){let rows=activityList().map(a=>({a,r:E.activity(a)}));const mode=$('activity-filter')?.value||'hourly';if(mode==='solo')rows=rows.filter(x=>x.a.players===1);if(mode==='short')rows=rows.filter(x=>x.r.valid&&x.r.activeMinutes<=30);if(mode==='accessible')rows=rows.filter(x=>x.a.investment+x.a.cost<=state.goal.capital-state.goal.reserve&&x.a.players<=state.goal.players);rows.sort((a,b)=>(mode==='investment'?a.a.investment-b.a.investment:(b.r.hourly??-1e20)-(a.r.hourly??-1e20))||a.a.name.localeCompare(b.a.name,'fr'));
 $('activity-results').innerHTML=rows.length?'<div class="calc-table-wrap" tabindex="0"><table class="calc-table"><caption>Ce que rapportent tes activités</caption><thead><tr><th>Activité</th><th>Gain par mission</th><th>Gain par heure, attente comprise</th><th>Temps de jeu</th><th>Achat de départ remboursé après</th><th>Statut</th></tr></thead><tbody>'+rows.map(({a,r})=>'<tr><th>'+esc(a.name)+'</th><td>'+money(r.net)+'</td><td>'+money(r.hourly)+'</td><td>'+hours(r.valid?r.activeMinutes/60:null)+'</td><td>'+(r.paybackRuns!==null?r.paybackRuns+' mission(s)':'Jamais')+'</td><td>'+esc(r.valid?statusLabels[a.status]||'Non confirmé':r.reason)+'</td></tr>').join('')+'</tbody></table></div>':'<p class="calc-empty">Aucune activité ne correspond. Choisis un autre affichage ou change tes chiffres.</p>';
 const r=activityAnswerResult();
 $('inverse-results').innerHTML='<p class="calc-kicker">MA RÉPONSE</p><h3>'+esc(findActivity(state.inverse.selected)?.name||'Mon activité')+'</h3>'+(r.valid?'<p class="b-answer calc-answer">Avec '+nf.format(state.inverse.minutes)+' minutes, tu peux terminer '+r.runs+' activité(s) et gagner '+money(r.profit)+'.</p>'+stats([['Nombre de missions',nf.format(r.runs)],['Gagné en tout, achats de départ enlevés',money(r.profit)],['Tu auras à la fin',money(r.finalCapital)]]):warning(r.reason))+'<p class="calc-note">Une activité pas finie ne rapporte rien. Ce que tu achètes une seule fois n’est compté qu’une fois.</p>';
 syncActivityContext();
}
function activityAnswerResult(){return B.evaluate('activities',state,sourceActivities);}
function syncActivityContext(){
 document.querySelectorAll('[data-field^="goal."]').forEach(el=>{const key=el.dataset.field.slice(5);if(['capital','reserve','players'].includes(key)&&el!==document.activeElement){const cur=parseNumber(el.value);if(cur!==state.goal[key]&&!(state.goal[key]===null&&el.value.trim()===''))el.value=state.goal[key]??'';el.setAttribute('aria-invalid',String(!validField(el,state.goal[key])));}});
 const solo=state.goal.players===1&&document.activeElement?.id!=='activity-players';$('activity-group-size').hidden=solo;
 document.querySelectorAll('[name="activity-play-mode"]').forEach(el=>el.checked=el.value===(solo?'solo':'group'));
}
function validField(el,value){return value!==null&&Number.isFinite(value)&&value>=Number(el.dataset.min)&&value<=Number(el.dataset.max)&&(!el.dataset.integer||Number.isInteger(value));}
function activityAnnouncement(){const r=activityAnswerResult();return r.valid?nf.format(r.runs)+' activité(s) terminée(s), '+money(r.profit)+' de gain après mise initiale. Capital final : '+money(r.finalCapital)+'.':r.reason;}
function showActivityAnswer(){
 renderActivities();clearTimeout(liveTimer);clearTimeout(answerTimer);
 const answer=$('inverse-results');answer.classList.remove('is-highlighted');void answer.offsetWidth;answer.classList.add('is-highlighted');
 answerTimer=setTimeout(()=>answer.classList.remove('is-highlighted'),4000);
 const rect=answer.getBoundingClientRect(),top=(document.querySelector('header')?.getBoundingClientRect().bottom||0)+16;
 if(rect.top<top||rect.bottom>innerHeight-16)answer.scrollIntoView({block:rect.height>innerHeight-top-16?'start':'nearest',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
 $('activity-live').textContent='';requestAnimationFrame(()=>{$('activity-live').textContent='Réponse actualisée. '+activityAnnouncement();});
}
function loadActivityExample(id){
 const preset=D.presets.find(a=>a.id===id),index=state.activities.findIndex(a=>a.id===id);if(!preset||index<0)return;
 state.activities[index]=clone(initial.activities[index]);state.goal={...clone(initial.goal),capital:preset.example.capital,selected:id};state.inverse={selected:id,minutes:preset.example.minutes};state.model='cycles';
 document.querySelectorAll('[data-field]').forEach(el=>{const path=el.dataset.field;if(path==='model'||path.startsWith('goal.')||path.startsWith('inverse.')||path.startsWith('activities.'+index+'.')){let value=state;for(const part of path.split('.'))value=value[part];el.value=value??'';el.removeAttribute('aria-invalid');}});
 document.querySelector('[data-owned="'+index+'"]').checked=false;
 document.querySelectorAll('.calc-activity-editor>summary').forEach((el,i)=>el.textContent='Hypothèse '+String.fromCharCode(65+i)+' · '+state.activities[i].name);
 changed();showActivityAnswer();
}

function sessionResult(){return B.session(state,sourceActivities);}
function renderSession(){workspace.sessionRender();}
function selectItem(item,render=true){let a;try{a=B.addAsset(state,item);}catch(e){notify(e.message);return false;}state.purchase.key=a.key;state.tab='purchase';if(render){mount();saveLocal();$('f-purchase-price').focus();emit('catalogue_open');}return true;}
function renderPurchase(){const p=B.purchase(state,sourceActivities),item=catalogue.find(x=>x.id===p.itemId),meta=item?.fieldMeta?.price;
 $('purchase-selection').innerHTML=item?'<div class="calc-provenance"><strong>'+esc(item.name)+'</strong><p>'+(item.price===null?'Prix pas encore connu : écris celui que tu imagines.':'Prix de référence : '+money(item.price)+' · '+esc(statusLabels[meta?.status]||'Non confirmé'))+'</p><a href="'+esc(item.url)+'">Retour à la fiche ↗</a><p class="calc-note">'+esc(meta?.source?'Source : '+meta.source:'Aucune source de prix disponible.')+(meta?.verifiedAt?' · vérification : '+esc(meta.verifiedAt):'')+'</p><button class="calc-text-button" id="purchase-manual">Achat libre</button></div>':(p.itemId?warning('Cette fiche n’existe plus. Ton prix est gardé comme ton chiffre à toi.'):'<span class="calc-tag">MON PRIX À MOI</span>');
 const validExtras=Number.isFinite(p.extras)&&p.extras>=0,validReserve=Number.isFinite(p.capital)&&Number.isFinite(p.reserve)&&p.reserve>=0&&p.reserve<=p.capital;
 const q={...p,capital:p.capital-p.reserve,price:p.price===null||!validExtras?null:p.price+p.extras},r=validReserve?E.purchase(q):{valid:false,reason:'L’argent mis de côté doit être entre 0 et ce que tu as.'},c=E.compareBuy(q);
 let html='<p class="calc-kicker">MA RÉPONSE</p>';
 if(!r.valid)html+=warning(r.reason);else{html+='<p class="b-answer calc-answer">'+(r.shortfall?'Pas encore : il te manque '+money(r.shortfall)+'.':'Oui, tu peux l’acheter maintenant.')+'</p>'+stats([['Prix total',money(q.price)],['Il te restera',money(r.remaining+p.reserve)],['Sans l’argent mis de côté',money(r.remaining)]])+stats([['Temps de jeu pour regagner ce prix',hours(r.recoveryHours)],['Mon objectif si je n’achète pas',hours(c.saveHours)],['Mon objectif si j’achète',c.affordable?hours(c.buyHours):'Il faut d’abord l’argent']])+'<p class="calc-note">'+(p.boostHourly>0?'Après l’achat, tu gagnerais '+money(p.hourly+p.boostHourly)+' par heure de jeu.':'Achat pour le plaisir : il ne rapporte rien. Le temps affiché, c’est le temps de jeu pour regagner la même somme.')+'</p><details><summary>Comment est-ce calculé ?</summary><p class="calc-note">Argent utilisable = ce que tu as − ce que tu gardes de côté. Prix total = prix + options et frais. Temps pour l’objectif après l’achat = ce qu’il te manque ensuite ÷ ce que tu gagnes par heure. On suppose que tu gagnes toujours pareil. '+(item&&p.price!==item.price?'Ton prix personnel remplace la référence pour cette simulation seulement.':'')+'</p></details>';}
 if(r.valid&&!c.valid)html+=warning('On n’a pas encore ce que cet achat te rapporte. Le budget marche quand même ; remplis « Ça vaut le coup ? » pour comparer les temps.');
 $('purchase-results').innerHTML=html;
}
const normalize=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function near(a,b){if(Math.abs(a.length-b.length)>1)return false;let i=0,j=0,n=0;while(i<a.length&&j<b.length){if(a[i]===b[j]){i++;j++;continue;}if(++n>1)return false;if(a.length>=b.length)i++;if(b.length>=a.length)j++;}return n+(i<a.length||j<b.length?1:0)<=1;}
function searchMatch(item,q){let hay=normalize((item.brand||'')+' '+item.name+' '+item.category+' '+(labels[item.type]||'')+' '+(item.aliases||''));const aliases={voiture:'vehicule',bagnole:'vehicule',flingue:'equipement',arme:'equipement',maison:'demeure',mission:'activite'};return normalize(q).split(/\s+/).filter(Boolean).every(t=>{t=aliases[t]||t;return hay.includes(t)||(t.length>=5&&hay.split(/[^a-z0-9]+/).some(w=>near(t,w)));});}
function renderCatalogue(){const f=state.catalogue;let items=[...catalogue,...activityList().map(a=>({...a,type:'activity',category:'activité',image:null,price:null}))].filter(x=>(f.type==='all'||x.type===f.type)&&searchMatch(x,f.query)&&(!f.favoritesOnly||f.favorites.includes(x.id)));
 items=items.filter(x=>{const s=x.type==='activity'?x.status:x.fieldMeta?.price?.status||'unknown';return(f.status==='all'||f.status==='known'&&x.price!==null||f.status==='unknown'&&x.price===null&&x.type!=='activity'||s===f.status)&&(f.maxPrice===null||x.price!==null&&x.price<=f.maxPrice);});
 items.sort((a,b)=>f.sort==='name'?((a.brand||'')+' '+a.name).localeCompare((b.brand||'')+' '+b.name,'fr'):(a.price===null&&b.price===null?0:a.price===null?1:b.price===null?-1:(f.sort==='price-up'?a.price-b.price:b.price-a.price))||a.name.localeCompare(b.name,'fr'));
 $('catalogue-count').textContent=items.length+' résultat'+(items.length>1?'s':'')+(f.maxPrice!==null?' · prix inconnus exclus':'');
 const chips=[['query',f.query],['type',f.type!=='all'?labels[f.type]:null],['status',f.status!=='all'?$('catalogue-status').selectedOptions[0]?.textContent:null],['maxPrice',f.maxPrice!==null?'≤ '+money(f.maxPrice):null],['favoritesOnly',f.favoritesOnly?'Favoris':null]].filter(x=>x[1]);
 $('catalogue-filter-chips').innerHTML=chips.map(([k,v])=>'<button class="calc-chip" data-remove-filter="'+k+'">'+esc(v)+' ×</button>').join('')+(chips.length?'<button class="calc-text-button" data-reset-filters="1">Tout réinitialiser</button>':'');
 $('catalogue-results').innerHTML=items.slice(0,catalogueLimit).map(x=>({...x,image:x.image||x.schemaImage})).map(x=>'<article class="calc-product" data-product="'+esc(x.id)+'"><div class="calc-product-media">'+(x.image?'<img src="'+esc(x.image)+'" data-image-fallback="'+esc(x.imageFallback||'')+'" class="'+(/(\.svg$|^data:image\/svg)/i.test(x.image)?'is-schema':'')+'" alt="" width="480" height="270" loading="lazy" decoding="async">':'')+'<div class="calc-product-placeholder" '+(x.image?'hidden':'')+' aria-hidden="true"><span>'+esc(labels[x.type]||'Mon plan')+'</span><small>'+esc(x.category||'Visuel indisponible')+'</small></div></div><div><span class="calc-tag">'+esc(labels[x.type]||x.type)+'</span><h4>'+esc((x.brand?x.brand+' ':'')+x.name)+'</h4><p>'+(x.type==='activity'?'Activité · '+esc(statusLabels[x.status]||'Non confirmé'):x.price===null?'Prix pas encore connu':money(x.price)+' · '+esc(statusLabels[x.fieldMeta?.price?.status]||'Non confirmé'))+'</p>'+(x.type==='activity'?'<button class="calc-button" data-activity="'+esc(x.id)+'">Calculer mon objectif</button>':'<button class="calc-button" data-item="'+esc(x.id)+'">Je veux celui-là</button> <button class="calc-button" data-b-roi="'+esc(x.id)+'">Calculer si ça vaut le coup</button> <a href="'+esc(x.url)+'">Fiche ↗</a>')+'<button class="calc-text-button" data-favorite="'+esc(x.id)+'" aria-pressed="'+f.favorites.includes(x.id)+'">'+(f.favorites.includes(x.id)?'★ Retirer des favoris':'☆ Mettre en favori')+'</button>'+(x.type!=='activity'?'<label class="calc-check calc-compare-option"><input type="checkbox" data-compare="'+esc(x.id)+'" '+(f.compareIds.includes(x.id)?'checked':'')+'> '+(f.compareIds.includes(x.id)?'✓ Dans ma comparaison':'Comparer')+'</label>':'')+'</div></article>').join('')||'<div class="calc-empty"><h4>On n’a rien trouvé.</h4><p>Essaie un autre mot, enlève le prix maximum ou choisis « Toutes les catégories ».</p><button class="calc-button" data-reset-filters="1">Retirer tous les filtres</button></div>';
 $('catalogue-more').hidden=items.length<=catalogueLimit;renderComparison();
}
function comparisonItems(){return state.catalogue.compareIds.map(id=>catalogue.find(x=>x.id===id)).filter(Boolean);}
function comparisonTable(items,rows,caption){
 const value=(x,k)=>{
  if(x[k]===null||x[k]===undefined)return '<span class="calc-unknown">Pas encore connu</span>';
  if(k==='type')return esc(labels[x.type]||x.type);
  if(k==='category')return esc(x.category||'');
  const meta=x.fieldMeta?.[k]||{},unit=meta.unit||(k==='price'?'$':k==='seats'?'places':'');
  return esc(k==='price'?money(x[k]):nf.format(x[k])+(unit?' '+unit:''))+'<br><small>'+esc(statusLabels[meta.status]||'Non confirmé')+'</small>';
 };
 return '<div class="calc-table-wrap" tabindex="0" role="region" aria-label="'+esc(caption)+'"><table class="calc-table"><caption>'+esc(caption)+'</caption><thead><tr><th scope="col">Critère</th>'+items.map(x=>'<th scope="col">'+esc((x.brand?x.brand+' ':'')+x.name)+' <button type="button" class="calc-text-button" data-remove-compare="'+esc(x.id)+'" aria-label="Retirer '+esc(x.name)+' de la comparaison">×</button></th>').join('')+'</tr></thead><tbody>'+rows.map(([l,k])=>'<tr><th scope="row">'+esc(l)+'</th>'+items.map(x=>'<td>'+value(x,k)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
}
function renderComparison(){
 const items=comparisonItems();state.catalogue.compareIds=items.map(x=>x.id);const box=$('vehicle-comparison');
 document.querySelectorAll('[data-compare]').forEach(el=>{const on=state.catalogue.compareIds.includes(el.dataset.compare);el.checked=on;el.closest('.calc-product')?.classList.toggle('is-selected',on);const t=el.nextSibling;if(t&&t.nodeType===3)t.textContent=on?' ✓ Dans ma comparaison':' Comparer';});
 if(!items.length){box.innerHTML='<p class="calc-empty">Coche « Comparer » sur 2 ou 3 fiches pour les voir côte à côte.</p>';box.classList.remove('is-active');return;}
 box.classList.add('is-active');
 const head='<div class="calc-compare-bar"><p class="calc-kicker">MA COMPARAISON</p><p class="calc-compare-count" role="status">'+items.length+' fiche'+(items.length>1?'s':'')+' sur 3'+(items.length<2?' : coche encore une fiche pour comparer.':'')+'</p><div class="calc-compare-chips">'+items.map(x=>'<button type="button" class="calc-chip" data-remove-compare="'+esc(x.id)+'" aria-label="Retirer '+esc(x.name)+' de la comparaison">'+esc(x.name)+' ×</button>').join('')+'</div></div>';
 const vehicles=items.filter(x=>x.type==='vehicle');
 box.innerHTML=head+comparisonTable(items,[['Type','type'],['Catégorie','category'],['Prix','price']],(items.length>1?'Ce qu’on sait sur ces '+items.length+' fiches':'Ce qu’on sait sur cette fiche'))+(vehicles.length?'<h4>Pour les véhicules</h4>'+comparisonTable(vehicles,[['Vitesse','speed'],['Accélération','acceleration'],['Places','seats']],'Véhicules seulement'):'')+'<p class="calc-note">Une valeur pas encore connue reste vide. On ne donne pas de note ni de classement tant qu’il manque des informations.</p>';
}
function refreshCatalogueFilters(){
 $('catalogue-search').value=state.catalogue.query;$('catalogue-type').value=state.catalogue.type;$('catalogue-status').value=state.catalogue.status;$('catalogue-budget').value=state.catalogue.maxPrice??'';$('catalogue-budget').removeAttribute('aria-invalid');$('catalogue-sort').value=state.catalogue.sort;$('catalogue-favorites').checked=state.catalogue.favoritesOnly;catalogueLimit=6;renderCatalogue();saveLocal();
}
function renderAll(){renderGoal();renderActivities();renderPurchase();renderCatalogue();workspace.render();}
function switchTab(tab,save=true){if(!tabs.includes(tab))return;state.tab=tab;document.querySelectorAll('[data-tab]').forEach(b=>{const active=b.dataset.tab===tab;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;});tabs.forEach(k=>{if($('panel-'+k))$('panel-'+k).hidden=k!==tab;});state.mode=state.views[tab];modeUI();if(save){workspace.render();saveLocal();emit('tool_open');}}
function openTab(tab){switchTab(tab);$('tab-'+tab)?.focus();}
function renderSaved(){workspace.renderSaved();}
function commitRecent(){}
function changed(){
 $('goal-continuous-fields').hidden=state.model!=='continuous';$('goal-cycle-fields').hidden=state.model!=='cycles';
 for(const id of ['f-goal-selected','f-inverse-selected'])for(const o of $(id).options){const a=findActivity(o.value);if(a)o.textContent=a.name+(a.status==='manual'?' · à moi':' · du site');}
 renderGoal();renderActivities();renderPurchase();workspace.render();saveLocal();clearTimeout(liveTimer);liveTimer=setTimeout(()=>{if(state.tab==='activities'){$('activity-live').textContent=activityAnnouncement();return;}$('calc-live').textContent=state.tab==='plan'?'Plan actualisé.':workspace.summary(state.tab);},650);
}
function setPath(path,value){const parts=path.split('.');let o=state;for(let i=0;i<parts.length-1;i++){if(!Object.prototype.hasOwnProperty.call(o,parts[i]))return;o=o[parts[i]];}const k=parts.at(-1);if(Object.prototype.hasOwnProperty.call(o,k))o[k]=value;}
function resetFilters(){state.catalogue={...initial.catalogue,favorites:state.catalogue.favorites,compareIds:state.catalogue.compareIds};refreshCatalogueFilters();}
function restore(config,message){state=clone(config);if(state.dataVersion!==dataVersion)state.completed=[];workspace.resetRevision();mount();saveLocal();notify(message+(state.dataVersion!==dataVersion?' La base a changé : les valeurs personnelles sont conservées ; une activité de référence sélectionnée est recalculée avec la base actuelle.':''));}
const workspace=window.LKCalcWorkspace.create({state:()=>state,initial,catalogue,sourceActivities,helpers,$,validate:validConfig,notify,mount,changed,restore,saveLocal,setPath,openTab,searchMatch});
mount();
if(state.dataVersion!==dataVersion)notify('Les données du site ont changé : tes chiffres à toi sont gardés. Une activité du site est recalculée avec les nouvelles données.');
document.addEventListener('input',ev=>{if(workspace.event(ev))return;const el=ev.target;if(el.matches('input[data-field]')){const value=el.dataset.number?parseNumber(el.value):el.value;if(el.dataset.field==='session.minutes'&&state.session.usualMinutes===state.session.minutes)state.session.usualMinutes=value;setPath(el.dataset.field,value);if(el.dataset.number){const ok=validField(el,value);el.setAttribute('aria-invalid',String(!ok));const err=$(el.id+'-error');if(err){err.hidden=ok;err.textContent=ok?'':'Saisis '+(el.dataset.integer?'un entier':'un nombre')+' entre '+el.dataset.min+' et '+el.dataset.max+'.';}}changed();}if(el.id==='catalogue-search'){state.catalogue.query=el.value;catalogueLimit=6;renderCatalogue();saveLocal();}if(el.id==='catalogue-budget'){const val=el.value.trim()===''?null:parseNumber(el.value);el.setAttribute('aria-invalid',String(el.value.trim()!==''&&(val===null||val<0)));state.catalogue.maxPrice=val!==null&&val>=0&&val<=1e12?val:null;catalogueLimit=6;renderCatalogue();saveLocal();}if(el.id==='calc-name'){state.name=el.value.slice(0,100)||'Mon plan';saveLocal();}});
document.addEventListener('change',ev=>{if(workspace.event(ev))return;const el=ev.target;if(/-play-mode$/.test(el.name||'')){state.goal.players=el.value==='solo'?1:Math.max(2,state.goal.players||2);document.querySelectorAll('[data-field="goal.players"]').forEach(i=>{i.value=state.goal.players;});document.querySelectorAll('.calc-group-size,#activity-group-size').forEach(g=>{g.hidden=state.goal.players===1;});document.querySelectorAll('[name$="-play-mode"]').forEach(i=>{i.checked=i.value===(state.goal.players===1?'solo':'group');});changed();}if(el.matches('select[data-field]')){setPath(el.dataset.field,el.value);changed();}if(el.dataset.owned!==undefined){state.activities[Number(el.dataset.owned)].owned=el.checked;changed();}if(el.dataset.sessionActivity){const id=el.dataset.sessionActivity;state.session.enabled=el.checked?[...new Set([...state.session.enabled,id])]:state.session.enabled.filter(x=>x!==id);changed();}if(el.id==='activity-filter')renderActivities();const filters={'catalogue-type':'type','catalogue-status':'status','catalogue-sort':'sort'};if(filters[el.id]){state.catalogue[filters[el.id]]=el.value;catalogueLimit=6;renderCatalogue();saveLocal();}if(el.id==='catalogue-favorites'){state.catalogue.favoritesOnly=el.checked;renderCatalogue();saveLocal();}if(el.dataset.compare){const id=el.dataset.compare;if(el.checked&&state.catalogue.compareIds.length>=3){el.checked=false;notify('Compare jusqu’à trois fiches à la fois.');return;}state.catalogue.compareIds=el.checked?[...state.catalogue.compareIds,id]:state.catalogue.compareIds.filter(x=>x!==id);renderComparison();saveLocal();emit('compare');if(el.checked&&state.catalogue.compareIds.length>=2){const box=$('vehicle-comparison');box.classList.remove('is-highlighted');void box.offsetWidth;box.classList.add('is-highlighted');const r=box.getBoundingClientRect();if(r.top>innerHeight-120)box.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}}});
document.addEventListener('click',ev=>{if(workspace.event(ev))return;const b=ev.target.closest('button');if(!b)return;const d=b.dataset;
 if(b.id==='activity-answer')showActivityAnswer();
 if(d.activityExample)loadActivityExample(d.activityExample);
 if(d.guideFocus){$(d.guideFocus)?.focus();$(d.guideFocus)?.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}if(d.tab)switchTab(d.tab);if(d.open)openTab(d.open);
 if(d.bMode&&!d.mode)d.mode=d.bMode;
 if(d.mode&&['quick','guided','advanced'].includes(d.mode)){state.mode=d.mode;state.views[state.tab]=d.mode;modeUI();workspace.render();saveLocal();}
 if(d.target){state.goal.target=Number(d.target);$('f-goal-target').value=d.target;changed();}
 if(d.daily){state.goal.dailyMinutes=Number(d.daily);$('f-goal-dailyMinutes').value=d.daily;changed();}
 if(d.inverseMinutes){state.inverse.minutes=Number(d.inverseMinutes);$('f-inverse-minutes').value=d.inverseMinutes;changed();}
 if(d.sessionMinutes){if(state.session.usualMinutes===state.session.minutes)state.session.usualMinutes=Number(d.sessionMinutes);state.session.minutes=Number(d.sessionMinutes);$('f-session-minutes').value=d.sessionMinutes;changed();}
 if(d.scenario||d.activity){state.model='cycles';state.goal.selected=d.scenario||d.activity;$('f-model').value='cycles';$('f-goal-selected').value=state.goal.selected;changed();if(d.activity)openTab('goal');}
 if(d.item){const item=catalogue.find(x=>x.id===d.item);if(item)selectItem(item);}
 if(b.id==='purchase-manual'){let a=state.assets.find(a=>!a.itemId);if(!a){if(state.assets.length>=40){notify('40 achats maximum. Télécharge ton calcul avant d’en retirer.');return;}a={key:'free-'+Date.now().toString(36),itemId:'',name:'Mon achat libre',price:null,referencePrice:null,extras:0,fees:0,owned:false,incomeMode:'none',boostHourly:0};state.assets.push(a);}state.purchase.key=a.key;mount();saveLocal();$('f-purchase-price').focus();}
 if(b.id==='catalogue-more'){catalogueLimit+=12;renderCatalogue();}
 if(d.favorite){state.catalogue.favorites=state.catalogue.favorites.includes(d.favorite)?state.catalogue.favorites.filter(x=>x!==d.favorite):[...state.catalogue.favorites,d.favorite].slice(-100);renderCatalogue();saveLocal();}
 if(d.removeCompare){state.catalogue.compareIds=state.catalogue.compareIds.filter(x=>x!==d.removeCompare);renderComparison();saveLocal();}
 if(d.removeFilter){state.catalogue[d.removeFilter]=initial.catalogue[d.removeFilter];refreshCatalogueFilters();$('catalogue-search').focus({preventScroll:true});}
 if(d.resetFilters)resetFilters();

});
document.querySelector('.calc-tabs').addEventListener('keydown',ev=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(ev.key))return;ev.preventDefault();const i=tabs.indexOf(state.tab),next=ev.key==='Home'?0:ev.key==='End'?tabs.length-1:(i+(ev.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;openTab(tabs[next]);});
$('calc-share').addEventListener('click',async()=>{try{validConfig(state);}catch{notify('Corrige les valeurs hors limites avant de partager le plan.');return;}const url=new URL(location.pathname,location.origin);url.hash='plan='+encodeURIComponent(JSON.stringify(state));if(url.href.length>24000){notify('Ce plan est trop volumineux pour un lien. Exporte le fichier JSON.');return;}history.replaceState(null,'',url);const copied=await window.LK.copy(url.href,$('calc-share'),'Lien copié ✓');if(!copied)notify('Copie indisponible : le lien complet est dans la barre d’adresse. Sélectionne-la pour le copier.');commitRecent();emit('share');});
$('calc-export').addEventListener('click',()=>{try{validConfig(state);}catch{notify('Corrige les valeurs hors limites avant d’exporter le plan.');return;}const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='leonidakit-calcul.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Configuration exportée.');});
$('calc-import').addEventListener('change',async ev=>{const file=ev.target.files?.[0];if(!file)return;try{if(file.size>200000)throw Error('Fichier trop volumineux (200 ko maximum).');restore(validConfig(JSON.parse(await file.text())),'Configuration importée.');}catch(error){notify('Import refusé : '+error.message);}ev.target.value='';});
$('calc-reset').addEventListener('click',()=>{undo=clone(state);restore(initial,'Exemple restauré. Tu peux annuler cette remise à zéro.');if(!tutorialChapter)history.replaceState(null,'',location.pathname);if($('calc-undo'))$('calc-undo').hidden=false;});
$('calc-undo')?.addEventListener('click',()=>{if(undo){restore(undo,'Ton plan précédent est restauré.');undo=null;$('calc-undo').hidden=true;}});
$('calc-print')?.addEventListener('click',()=>{document.title=state.name+' · Leonidakit';window.print();});
let printDetails=[];window.addEventListener('beforeprint',()=>{printDetails=[...document.querySelectorAll('.calc-panel:not([hidden]) details')].map(el=>({el,open:el.open}));printDetails.forEach(({el})=>el.open=true);});window.addEventListener('afterprint',()=>printDetails.forEach(({el,open})=>el.open=open));
window.addEventListener('hashchange',()=>{if(loadHash()){workspace.resetRevision();mount();}});
document.addEventListener('error',ev=>{const img=ev.target;if(img.tagName!=='IMG'||!img.closest('.calc-product-media'))return;const fallback=img.dataset.imageFallback;img.dataset.imageFallback='';if(fallback){img.classList.add('is-schema');img.src=fallback;}else{img.hidden=true;img.closest('.calc-product-media').querySelector('.calc-product-placeholder').hidden=false;}},true);
document.addEventListener('focusout',ev=>{if(ev.target.id==='activity-players')syncActivityContext();});
window.LKCalculator={openTab,applyGoal(values){for(const k of ['capital','target','hourly','dailyMinutes'])if(Number.isFinite(values[k])){state.goal[k]=values[k];const f=$('f-goal-'+k);if(f)f.value=values[k];}if(values.hourly!==undefined){state.model='continuous';$('f-model').value='continuous';}changed();openTab('goal');},selectItem(id){const item=catalogue.find(x=>x.id===id);if(item)selectItem(item);}};
emit('open');
if(tutorialChapter){const link=$('calc-tuto-return');if(link){link.href='tuto.html#'+tutorialChapter;link.hidden=false;}}
if(tutorialParams.get('focus')==='carnets'){const section=document.querySelector('.calc-saved');if(section){section.open=true;requestAnimationFrame(()=>{section.scrollIntoView({block:'start',behavior:'auto'});section.querySelector('summary').focus({preventScroll:true});});}}
})();
