/* Mon business plan (v7.34) : un programme mission par mission, avec ses propres réponses.
   Le plan ne prend rien en silence dans les huit calculs : il pose ses questions (but, situation, missions, achats d'avant).
   Tout chiffre vient du moteur (LKCalcEngine.missionPlan) via le scénario partagé (LKCalcScenario) ; ce fichier ne fait
   que présenter : réponse, prochaine partie, programme dans l'ordre, plans de secours, suivi du réel avec recalcul complet,
   point de départ, stratégie, échéance, détails (partie par partie, et si, courbe, calendrier, formule), fiche enregistrée. */
(function(global){'use strict';
const B=global.LKCalcScenario;
function create(env){
 const {esc,money,hours,field,stats,warning,btn,select,table,state,sourceActivities,visual,api,problem,itemFor,selectedCard,combobox,step,refresh,fold}=env;
 const E=global.LKCalcEngine,nf=new Intl.NumberFormat('fr-FR',{maximumFractionDigits:2}),$=id=>document.getElementById(id);
 const STRATEGY_LABEL=B.STRATEGY_LABEL;
 const ORDINALS=['En premier','En deuxième','En troisième','En quatrième','En cinquième','En sixième','En septième','En huitième','En neuvième','En dixième'];
 const KIND_LABEL={purchase:'Acheter quelque chose',amount:'Avoir une somme d’argent',unlock:'Débloquer quelque chose avec de l’expérience (rang, XP, réputation…)'};
 function planDate(days,base){const d=base?new Date(base):new Date();if(!Number.isFinite(d.getTime()))return '—';d.setDate(d.getDate()+days);return d.toLocaleDateString('fr-FR',{day:'numeric',month:'long'});}
 const dayOf=(n,dpw)=>n<=0?0:Math.floor((n-1)/dpw)*7+((n-1)%dpw)+1;
 const pct=v=>v===null||!Number.isFinite(v)?'—':nf.format(Math.round(v*10)/10)+' %';
 const plural=(n,w)=>n+' '+w+(n>1?'s':'');
 const units=(s,n)=>(Number.isFinite(n)?nf.format(Math.round(n*100)/100):'—')+' '+esc(s.plan.goal.unitLabel||'points');
 const sessionLabel=s=>hours((s.plan.situation.dailyMinutes||0)/60);
 function goalName(s){const g=s.plan.goal;return g.kind==='amount'?'avoir '+money(g.target):g.kind==='unlock'?'débloquer '+(g.name||'mon but'):(g.name||'mon achat');}
 function goalShort(s){const g=s.plan.goal;return g.kind==='amount'?money(g.target):(g.name||(g.kind==='unlock'?'mon but':'mon achat'));}
 function parse(v){const P=E.parseLocalizedNumber;if(v===undefined||v===null)return null;if(String(v).trim()==='')return null;const r=P(String(v));return r.valid?r.value:null;}
 /* ---------- Formulaire : cinq questions, toutes propres au plan ---------- */
 function markup(){const s=state(),p=s.plan,g=p.goal,si=p.situation;
  const goalBlock=g.kind==='purchase'
   ?combobox('plan-search','Je veux acheter (cherche dans le site)','plan')+btn('Écrire un achat libre','data-b-plan-free="1"')+'<div id="plan-selection">'+(g.itemId?selectedCard({itemId:g.itemId,name:g.name}):'')+'<div class="calc-fields">'+field('plan.goal.name','Nom de mon achat',g.name,{type:'text',id:'plan-name'})+field('plan.goal.price',g.referencePrice!==null?'Ça coûte ($)':'Ça coûte, d’après ce que tu imagines ($)',g.price,{id:'plan-price',hint:g.referencePrice!==null?'Prix du site : '+money(g.referencePrice)+'. Tu peux écrire un autre prix.':'Le prix du jeu n’est pas encore connu : écris celui que tu imagines.'})+field('plan.goal.boostHourly','Une fois acheté, il me fera gagner en plus ($ par heure)',g.boostHourly,{id:'plan-boost',hint:'0 si c’est un achat plaisir. Compte seulement ce qu’il rapporte en plus.'})+'</div>'+(g.referencePrice!==null?btn('Remettre le prix du site','data-b-plan-price-reset="1"'):'')+'</div>'
   :g.kind==='amount'
   ?field('plan.goal.target','Je veux avoir ($)',g.target,{id:'plan-target',hint:'La somme que tu veux avoir en poche, en plus de ce que tu gardes de côté.'})
   :'<div class="calc-fields">'+field('plan.goal.name','Ce que je veux débloquer',g.name,{type:'text',id:'plan-name',hint:'Une voiture, une arme, un lieu… tout ce qui se gagne avec l’expérience.'})+field('plan.goal.unitLabel','Ça se gagne en',g.unitLabel,{type:'text',id:'plan-units-label',hint:'points d’XP, niveaux, réputation… le mot que tu veux.'})+field('plan.goal.targetUnits','Il faut atteindre ('+esc(g.unitLabel||'points')+')',g.targetUnits,{id:'plan-units-target'})+field('plan.goal.currentUnits','J’en ai déjà ('+esc(g.unitLabel||'points')+')',g.currentUnits,{id:'plan-units-current'})+field('plan.goal.alsoPrice','Et il coûte aussi, une fois débloqué ($)',g.alsoPrice,{id:'plan-also-price',hint:'Laisse 0 s’il est gratuit une fois débloqué.'})+'</div><p class="calc-note">Le jeu n’a pas encore dit comment se gagne l’expérience. Écris ce que tu sais, ou ce que tu imagines : le plan compte avec tes chiffres.</p>';
  const missionSources=[...s.activities.map(a=>['mine:'+a.id,a.name+' · mes activités']),...sourceActivities.map(a=>['site:'+a.id,a.name+' · du site'])];
  const missionsBlock=p.source==='missions'
   ?'<div id="plan-missions">'+(p.missions.length?p.missions.map((m,i)=>missionCard(s,m,i)).join(''):'<p class="calc-empty">Aucune mission pour l’instant. Ajoute celles que tu peux faire : le plan te dira lesquelles enchaîner et dans quel ordre.</p>')+'</div><div class="b-plan-add">'+btn('Ajouter une mission','data-b-plan-m-add="1"',true)+(missionSources.length?'<label class="calc-label" for="plan-m-source">Ou reprendre une mission déjà écrite</label><div class="b-plan-add-row"><select id="plan-m-source">'+missionSources.map(([k,l])=>'<option value="'+esc(k)+'">'+esc(l)+'</option>').join('')+'</select>'+btn('Ajouter cette mission','data-b-plan-m-import="1"')+'</div>':'')+'</div><p class="calc-note">Ce sont des copies : changer une mission ici ne change rien dans Mes activités, et inversement.</p>'
   :'<div class="calc-fields">'+field('plan.situation.hourly','Je gagne à peu près ($ par heure de jeu)',si.hourly,{id:'plan-hourly',hint:'Ce qu’il te reste une fois tes frais payés. Ton chiffre à toi.'})+(g.kind==='unlock'?field('plan.situation.unitsHourly','Je gagne à peu près ('+esc(g.unitLabel||'points')+' par heure)',si.unitsHourly,{id:'plan-units-hourly'}):'')+'</div>';
  const prereqBlock='<div id="plan-prereqs">'+(p.prerequisites.length?p.prerequisites.map((a,i)=>prereqCard(s,a,i)).join(''):'<p class="calc-empty">Aucun achat avant ton but. Ajoute ce qu’il te faut acheter d’abord (équipement, véhicule, local…), s’il y en a.</p>')+'</div>'+combobox('plan-prereq-search','Ajouter un achat d’avant (cherche dans le site)','plan-prereq')+btn('Ajouter un achat libre','data-b-plan-p-add="1"')+'<div class="calc-fields">'+select('plan.strategy','Dans quel ordre les acheter ?',Object.entries(STRATEGY_LABEL),p.strategy)+field('plan.situation.upkeepPerSession','Je dépense par partie ($) : consommables, munitions…',si.upkeepPerSession,{id:'plan-upkeep',hint:'Enlevé de ce que tu gagnes. Mets 0 si tu ne sais pas.'})+'</div>';
  const form='<div class="b-plan-import"><p class="calc-note">Le business plan a ses propres cases : rien n’est pris automatiquement dans les huit calculs. Si tu veux repartir de tes chiffres de Mes calculs, clique ici, puis change ce que tu veux.</p>'+btn('Reprendre mes chiffres de Mes calculs','data-b-plan-import-calcs="1"')+'</div><div class="calc-fields calc-steps">'
   +step(1,'Quel est ton but ?',select('plan.goal.kind','Mon but',Object.entries(KIND_LABEL),g.kind)+goalBlock,'Le but décide de tout le reste : un achat a un prix, une somme se gagne petit à petit, un déblocage se gagne avec des points.')
   +step(2,'Où en es-tu ?','<div class="calc-fields">'+field('plan.situation.capital','J’ai déjà ($)',si.capital,{id:'plan-capital'})+field('plan.situation.reserve','Argent que je garde de côté ($)',si.reserve,{id:'plan-reserve'})+field('plan.situation.dailyMinutes','Une partie dure (minutes)',si.dailyMinutes,{id:'plan-daily',min:1,max:1440,hint:'Le programme se fait partie par partie : dis combien de temps tu joues à chaque fois.'})+field('plan.situation.daysPerWeek','Je joue combien de jours par semaine ?',si.daysPerWeek,{id:'plan-days',min:1,max:7,integer:true})+'</div>','Avec ce que tu as et la durée de tes parties, le plan compte en parties, puis en jours.')
   +step(3,'Comment tu gagnes ton argent ?',select('plan.source','Je gagne mon argent',[['missions','Avec mes missions : le plan me dit lesquelles faire et dans quel ordre'],['hourly','Petit à petit : je gagne à peu près un chiffre par heure']],p.source)+missionsBlock,'Avec tes missions, le plan choisit à chaque partie celles qui rapportent le plus dans le temps que tu as. C’est le chemin le plus rapide qu’il trouve.')
   +step(4,'Avant ton but',prereqBlock,'Un achat qui débloque une mission ou qui rapporte accélère la suite ; le plan le place au bon moment, dès que tu peux le payer.')
   +step(5,'Ce qui compte pour toi','<div class="calc-fields">'+select('plan.priority','Je préfère',[['balanced','Un bon équilibre : je garde ma réserve'],['fast','Le plus vite possible : je peux toucher à ma réserve'],['safe','La sécurité : je ne touche jamais à ma réserve']],p.priority)+field('plan.deadlineDays','Je veux y arriver en (jours, si tu veux)',p.deadlineDays,{id:'plan-deadline',min:1,max:36500,integer:true,hint:'Laisse vide si tu n’as pas de date. On te dira si c’est faisable avec ton rythme.'})+'<div class="b-expert">'+field('plan.maxRepeat','Même mission à la suite, au maximum',p.maxRepeat,{id:'plan-max-repeat',min:1,max:256,integer:true})+'</div></div>','Ta priorité décide quel ordre d’achats on te conseille, et si la réserve peut servir.')
   +'</div><p class="calc-note">Le plan se refait tout seul à chaque chiffre changé. Enregistre-le pour le retrouver avec sa fiche complète, imprime-le, ou partage le lien.</p>';
  return '<section class="calc-panel" id="panel-plan" role="tabpanel" aria-labelledby="tab-plan" hidden><div class="calc-grid"><div class="calc-card"><p class="calc-kicker">MON BUSINESS PLAN</p><h3>Dis-moi ton but, je te fais le programme.</h3><p class="calc-card-desc">Réponds aux cinq questions : le plan te dit quoi faire en premier, en deuxième, en troisième, partie après partie, avec le chemin le plus rapide vers ton but, et ce que tu fais si ça ne se passe pas comme prévu.</p>'+form+'</div><div class="calc-card calc-result" id="plan-results"></div></div><div id="plan-report"></div><div class="b-stage-actions">'+btn('Enregistrer mon plan (avec sa fiche)','data-b-save="plan"',true)+btn('Imprimer mon plan','data-b-print="1"')+btn('Exporter mon plan (fichier texte)','data-b-plan-export="1"')+'</div><p class="calc-note">Retrouve tes versions et leur fiche complète dans « Mes plans enregistrés » ci-dessous.</p><div class="b-expert calc-card calc-subsection" id="expert-plan"></div></section>';}
 function missionSummary(s,m,i){const p=s.plan,r=E.activity({...m,units:m.units});return '<span>'+esc(m.name||'Mission '+(i+1))+'<i class="b-plan-mission-edit">modifier</i></span><small>'+(r.valid?money(r.net)+' par mission · '+money(r.hourly)+' par heure, attente comprise':'chiffres à compléter : '+esc(r.reason||''))+(m.requires.length?' · après '+esc(m.requires.map(id=>p.prerequisites.find(x=>x.id===id)?.name||id).join(', ')):'')+(m.owned?' · achat de départ déjà payé':'')+'</small>';}
 function prereqHead(s,a,i){return '<span class="calc-tag">'+(i+1)+'</span><strong>'+esc(a.name)+'</strong><small>'+(a.owned?'déjà possédé':a.price===null?'prix à écrire':money(a.price))+(a.boostHourly>0?' · +'+money(a.boostHourly)+'/h ensuite':'')+'</small>';}
 function syncForm(s){s.plan.missions.forEach((m,i)=>{const n=document.querySelector('[data-b-plan-m-summary="'+i+'"]');if(n){const h=missionSummary(s,m,i);if(n.innerHTML!==h)n.innerHTML=h;}});s.plan.prerequisites.forEach((a,i)=>{const n=document.querySelector('[data-b-plan-p-head="'+i+'"]');if(n){const h=prereqHead(s,a,i);if(n.innerHTML!==h)n.innerHTML=h;}});}
 function missionCard(s,m,i){const p=s.plan,g=p.goal,r=E.activity({...m,units:m.units}),pre='plan.missions.'+i+'.';
  return '<details class="b-plan-mission" '+(i===p.missions.length-1&&p.missions.length<=2?'open':'')+'><summary data-b-plan-m-summary="'+i+'">'+missionSummary(s,m,i)+'</summary><div class="calc-fields">'+field(pre+'name','Nom de la mission',m.name,{type:'text',id:'plan-m-'+i+'-name'})+field(pre+'reward','Récompense ($)',m.reward,{id:'plan-m-'+i+'-reward'})+field(pre+'duration','Durée (min)',m.duration,{id:'plan-m-'+i+'-duration',min:1,max:1e6})+field(pre+'cost','Frais à chaque fois ($)',m.cost,{id:'plan-m-'+i+'-cost'})+field(pre+'prep','Préparation (min)',m.prep,{id:'plan-m-'+i+'-prep',max:1e6})+field(pre+'cooldown','Attente avant de recommencer (min)',m.cooldown,{id:'plan-m-'+i+'-cooldown',max:1e6})+field(pre+'share','Ma part (%)',m.share,{id:'plan-m-'+i+'-share',max:100})+field(pre+'investment','À acheter une seule fois avant de commencer ($)',m.investment,{id:'plan-m-'+i+'-investment'})+(g.kind==='unlock'?field(pre+'units',esc(g.unitLabel||'Points')+' gagnés par mission',m.units,{id:'plan-m-'+i+'-units'}):'')+'</div><label class="calc-check"><input type="checkbox" data-b-plan-m-owned="'+i+'" '+(m.owned?'checked':'')+'> J’ai déjà payé ce qu’il faut pour commencer</label>'+(p.prerequisites.length?'<fieldset class="b-plan-requires"><legend>Il faut d’abord avoir acheté :</legend>'+p.prerequisites.map(a=>'<label class="calc-check"><input type="checkbox" data-b-plan-m-req="'+i+'|'+esc(a.id)+'" '+(m.requires.includes(a.id)?'checked':'')+'> '+esc(a.name)+'</label>').join('')+'</fieldset>':'')+'<div class="b-plan-card-actions">'+btn('Retirer cette mission','data-b-plan-m-remove="'+i+'"')+'</div></details>';}
 function prereqCard(s,a,i){const pre='plan.prerequisites.'+i+'.',item=itemFor({itemId:a.itemId});
  return '<article class="b-plan-prereq" data-b-plan-prereq="'+esc(a.id)+'"><div class="b-plan-prereq-head" data-b-plan-p-head="'+i+'">'+prereqHead(s,a,i)+'</div><div class="calc-fields">'+field(pre+'name','Nom',a.name,{type:'text',id:'plan-p-'+i+'-name'})+field(pre+'price',a.referencePrice!==null?'Prix ($)':'Prix, d’après ce que tu imagines ($)',a.price,{id:'plan-p-'+i+'-price',hint:a.referencePrice!==null?'Prix du site : '+money(a.referencePrice)+'.':(item?'':'')})+field(pre+'boostHourly','Il me fera gagner en plus ($ par heure)',a.boostHourly,{id:'plan-p-'+i+'-boost',hint:'Seulement ce que cet achat rapporte en plus. 0 sinon.'})+'</div><label class="calc-check"><input type="checkbox" data-b-plan-p-owned="'+i+'" '+(a.owned?'checked':'')+'> Je l’ai déjà</label><div class="b-plan-card-actions">'+btn('↑','data-b-plan-p-up="'+i+'" aria-label="Monter '+esc(a.name)+'" '+(i===0?'disabled':''))+btn('↓','data-b-plan-p-down="'+i+'" aria-label="Descendre '+esc(a.name)+'" '+(i===s.plan.prerequisites.length-1?'disabled':''))+btn('Retirer','data-b-plan-p-remove="'+i+'"')+'</div></article>';}
 /* ---------- Phases : « en premier, en deuxième… », le cœur du programme ---------- */
 function stepsText(steps){return steps.map((st,i)=>(i?(i===steps.length-1?' puis ':', '):'')+'« '+esc(st.name)+' » ×'+st.runs).join('');}
 function phaseCards(s,r,base){const p=s.plan,g=p.goal,dpw=r.input.daysPerWeek,D=sessionLabel(s),byName=n=>r.purchases.find(x=>x.name===n),cards=[];
  if(r.totalSessions===0)return '<ol class="b-timeline"><li class="b-phase is-goal"><span class="b-phase-n">✓</span><div><p class="b-phase-k">Dès maintenant</p><h4>'+esc(g.kind==='purchase'?'Achète '+goalShort(s):g.kind==='unlock'?'Tu peux déjà débloquer '+goalShort(s):'Tu as déjà '+goalShort(s))+'</h4><p>'+esc(g.kind==='purchase'?'Il te restera '+money(r.finalCash-(r.input.goalPrice||0))+(r.input.reserve?', dont '+money(r.input.reserve)+' gardés de côté':'')+'.':'Choisis un but plus grand, ou un nouvel achat.')+'</p></div></li></ol>';
  r.phases.forEach((ph,i)=>{const range=ph.count===1?'Partie '+ph.from:'Parties '+ph.from+' à '+ph.to+' · '+plural(ph.count,'partie');
   const doText=ph.steps.length?'Fais '+stepsText(ph.steps)+(ph.count>1?' à chaque partie':'')+'.':'Joue '+D+' : tu gagnes à peu près '+money(ph.gain)+' par partie'+(r.input.hourly>0?' avec ton chiffre par heure':'')+'.';
   const boosters=r.purchases.filter(x=>x.boostHourly>0&&((x.atSession!==null&&x.atSession<ph.from)||(x.owned&&x.atSession===null))),passive=boosters.reduce((a,x)=>a+x.boostHourly,0)*r.input.sessionMinutes/60,extras=[];
   if(passive>0)extras.push('+'+money(passive)+' par partie grâce à '+boosters.map(x=>'« '+esc(x.name)+' »').join(', '));if(r.input.hourly>0&&ph.steps.length)extras.push('+'+money(r.input.hourly*r.input.sessionMinutes/60)+' avec ton gain par heure');if(r.input.upkeepPerSession>0)extras.push('−'+money(r.input.upkeepPerSession)+' de dépenses par partie');
   const extra=extras.join(' · ');
   const figures=[['Par partie','+'+money(ph.gain)+(g.kind==='unlock'&&ph.unitsGain>0?' · +'+units(s,ph.unitsGain):'')],['Tu passes de',money(ph.cashBefore)+' à '+money(ph.cashAfter)],['Quand',ph.from===ph.to?'jour '+dayOf(ph.from,dpw)+' (vers le '+planDate(dayOf(ph.from,dpw),base)+')':'du jour '+dayOf(ph.from,dpw)+' au jour '+dayOf(ph.to,dpw)+' (vers le '+planDate(dayOf(ph.to,dpw),base)+')']];
   const after=ph.purchasesAfter.length?'<p class="b-phase-after"><b>Après la partie '+ph.to+' :</b> achète '+ph.purchasesAfter.map(n=>{const x=byName(n);return '« '+esc(n)+' »'+(x?' ('+money(x.price)+(x.boostHourly>0?', +'+money(x.boostHourly)+'/h ensuite':'')+')':'');}).join(', ')+'.</p>':'';
   cards.push('<li class="b-phase"><span class="b-phase-n">'+(i+1)+'</span><div><p class="b-phase-k">'+esc(ORDINALS[i]||'Étape '+(i+1))+' · '+esc(range)+'</p><h4>'+doText+'</h4>'+(extra?'<p class="calc-note">Compté aussi dans le total : '+extra+'.</p>':'')+'<div class="b-tiles">'+figures.map(([l,v])=>'<span><small>'+esc(l)+'</small><b>'+v+'</b></span>').join('')+'</div>'+after+'</div></li>');});
  const N=r.totalSessions,dayN=dayOf(N,dpw);
  cards.push('<li class="b-phase is-goal"><span class="b-phase-n">★</span><div><p class="b-phase-k">Objectif atteint · après la partie '+N+' · jour '+dayN+' (vers le '+planDate(dayN,base)+')</p><h4>'+esc(g.kind==='purchase'?'Achète '+goalShort(s)+' ('+money(r.input.goalPrice)+')':g.kind==='unlock'?'Tu débloques '+goalShort(s)+(r.input.goalPrice>0?' et tu le paies ('+money(r.input.goalPrice)+')':''):'Tu as '+money(g.target)+' en poche')+'</h4><p>'+esc((g.kind==='purchase'||(g.kind==='unlock'&&r.input.goalPrice>0)?'Il te reste '+money(r.finalCash-(r.input.goalPrice||0))+(r.input.reserve?', dont '+money(r.input.reserve)+' gardés de côté':'')+'.':'Tu gardes '+money(r.input.reserve)+' de côté.')+(g.kind==='purchase'&&g.boostHourly>0?' Ensuite, cet achat te rapporte '+money(g.boostHourly)+' de plus par heure : remboursé après '+hours(r.input.goalPrice/g.boostHourly)+' de jeu.':'')+(g.kind==='purchase'&&!(g.boostHourly>0)?' C’est un achat plaisir : il ne se rembourse pas tout seul, et ce n’est pas grave.':''))+'</p></div></li>');
  return '<ol class="b-timeline">'+cards.join('')+'</ol>';}
 function programSummary(r){if(!r||!r.valid)return '';return r.phases.map(ph=>(ph.count===1?'Partie '+ph.from:'Parties '+ph.from+'–'+ph.to)+' : '+(ph.steps.length?ph.steps.map(st=>st.name+' ×'+st.runs).join(', '):'ton gain par heure')+(ph.purchasesAfter.length?' → puis achète '+ph.purchasesAfter.join(', '):'')).join(' · ');}
 /* ---------- Rendu principal ---------- */
 function render(){const s=state(),p=s.plan,g=p.goal,si=p.situation,r=B.evaluate('plan',s),mode=s.views.plan||'quick',expert=mode==='advanced',details=expert||p.details;syncForm(s);
  let head='<p class="calc-kicker">MA RÉPONSE</p><span class="calc-tag">AVEC TES CHIFFRES</span>';
  if(!r.valid){head+=warning(r.reason)+problem(r.reason,'plan')+'<div class="calc-next-action"><strong>Pour avoir ton programme</strong><p>Il manque un chiffre ou un choix à gauche. Corrige la case indiquée : le plan se calcule tout seul, partie par partie.</p></div>';$('plan-results').innerHTML=head;$('plan-report').innerHTML='';$('expert-plan').innerHTML='';markSkips(s);return;}
  const D=sessionLabel(s),dpw=r.input.daysPerWeek,reached=r.totalSessions===0,next=B.planNextSession(r),first=r.phases[0];
  const needMoney=Math.max(0,r.goalMoney+r.input.reserve-r.startCash),parts=[];if(g.kind==='unlock'&&r.startUnits<r.input.targetUnits)parts.push(units(s,r.input.targetUnits-r.startUnits));if(needMoney>0||g.kind!=='unlock')parts.push(money(needMoney));
  const missingText='il te manque <b>'+parts.join(' et ')+'</b>';
  const how=p.source==='missions'?'avec tes missions':'en gagnant '+money(si.hourly)+' par heure';
  const phrase=reached?'Bonne nouvelle : tu peux déjà '+esc(g.kind==='purchase'?'acheter '+goalShort(s):g.kind==='unlock'?'débloquer '+goalShort(s):'avoir '+goalShort(s))+' avec ce que tu as, sans toucher à ce que tu gardes de côté.'
   :'Pour '+esc(goalName(s))+', '+missingText+'. '+how.charAt(0).toUpperCase()+how.slice(1)+', tu y arrives en <b>'+plural(r.totalSessions,'partie')+'</b> de '+D+', soit <b>'+plural(r.days,'jour')+'</b> (vers le '+planDate(r.days)+').'+(first&&first.steps.length?' En premier : '+stepsText(first.steps)+'.':'');
  head+='<p class="b-answer calc-answer" data-short="'+esc(reached?'C’est bon !':plural(r.totalSessions,'partie')+' · '+plural(r.days,'jour'))+'">'+phrase+'</p>'+stats([['Parties de '+D,String(r.totalSessions)],['Jours',String(r.days)],['Tu auras à la fin',money(r.finalCash)]]);
  if(g.kind==='unlock'&&r.input.targetUnits>0)head+=visual.progress('plan-progress',esc(g.unitLabel||'Points')+' déjà gagnés',Math.min(r.startUnits,r.input.targetUnits),r.input.targetUnits,'Départ : '+units(s,r.startUnits)+'. Cible : '+units(s,r.input.targetUnits)+'. 100 % = débloqué.');
  else{const need=r.goalMoney+r.input.reserve+r.purchases.filter(x=>!x.owned||x.atSession).reduce((a,x)=>a+(x.atSession?x.price:0),0);head+=visual.progress('plan-progress','Ce que tu as déjà',Math.min(r.startCash,need),need,'Départ : '+money(r.startCash)+'. Cible : '+money(need)+' (tout ce qu’il faut avoir eu, achats d’avant compris). 100 % = tu peux payer ton but.');}
  if(r.variant!=='auto')head+='<p class="b-variant-note"><span class="calc-tag">PLAN DE SECOURS</span> Tu suis « '+esc(variantLabel(s,r))+' ». '+btn('Revenir au meilleur plan','data-b-plan-variant="auto"')+'</p>';
  if(reached)head+='<div class="calc-next-action"><strong>Ta prochaine étape</strong><p>'+esc(g.kind==='purchase'?'Achète '+goalShort(s)+' quand tu veux : il te restera '+money(r.finalCash-(r.input.goalPrice||0))+'. Ensuite, choisis un nouveau but.':'Ton but est atteint. Choisis-en un plus grand, ou un achat.')+'</p></div>';
  else if(next)head+='<div class="calc-next-action"><strong>Ta prochaine partie ('+D+')</strong>'+(next.steps.length?'<ol class="b-next-steps">'+next.steps.map(st=>'<li>« '+esc(st.name)+' » ×'+st.runs+' <span>+'+money(st.net)+'</span></li>').join('')+'</ol>':'<p>Joue '+D+' : +'+money(next.gain)+' environ.</p>')+'<p>'+esc('Tu passes de '+money(r.startCash)+' à '+money(next.cashAfter+next.purchases.reduce((a,n)=>{const x=r.purchases.find(y=>y.name===n);return a+(x?x.price:0);},0))+'.')+(next.purchases.length?' <b>Puis achète : '+esc(next.purchases.join(', '))+'</b> → il te reste '+money(next.cashAfter)+'.':'')+(g.kind==='unlock'&&next.unitsGain>0?' +'+units(s,next.unitsGain)+'.':'')+'</p>'+btn('Après avoir joué, écrire ce que j’ai vraiment','data-b-focus="plan-actual"')+'</div>';
  if(mode!=='advanced')head+='<label class="calc-check"><input type="checkbox" data-b-plan-details="1" '+(p.details?'checked':'')+'> Afficher plus de détails (partie par partie, et si, courbe, calendrier)</label>';
  $('plan-results').innerHTML=head;markSkips(s);
  /* ---- Le document : des « gros points » repliables. La réponse est au-dessus ; ici, chaque point s'ouvre d'un geste. ---- */
  const obs=B.planObserved(s),deadline=B.planDeadline(s,r),curve=B.planCurve(r);
  let doc='<div class="calc-card calc-subsection b-doc"><div class="b-doc-head"><div><p class="calc-kicker">MON BUSINESS PLAN · '+esc(new Date().toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'}))+'</p><h3>'+esc(goalName(s).charAt(0).toUpperCase()+goalName(s).slice(1))+'</h3><p class="b-doc-meta">'+esc(reached?'Déjà possible avec ce que tu as.':plural(r.totalSessions,'partie')+' de '+D+' · '+plural(r.days,'jour')+' · '+(p.source==='missions'?plural(p.missions.length,'mission')+' au choix':money(si.hourly)+' par heure')+(r.purchases.some(x=>!x.owned||x.atSession)?' · '+plural(r.purchases.filter(x=>x.atSession).length,'achat')+' d’avant':'')+' · tes chiffres, pas ceux du jeu')+'</p></div><div class="b-doc-tools">'+btn('Tout déplier','data-b-fold-all="open"')+btn('Tout replier','data-b-fold-all="close"')+'</div></div><p class="b-doc-hint">Appuie sur un point pour l’ouvrir. Les chiffres importants sont déjà dans chaque titre.</p>';
  let n=0;const section=(id,title,teaser,lead,body,tone)=>fold('plan-'+id,{n:++n,title,teaser,tone,body:()=>(lead?'<p class="b-doc-lead">'+lead+'</p>':'')+(typeof body==='function'?body():body)});
  /* 1. Programme */
  doc+=section('program','Ton programme, dans l’ordre',reached?'Déjà possible : rien à faire avant ton but':(first&&first.steps.length?'En premier : '+stepsText(first.steps)+' · <b>'+plural(r.totalSessions,'partie')+'</b>, '+plural(r.phases.length,'étape'):'<b>'+plural(r.totalSessions,'partie')+'</b> de '+D+' · '+plural(r.days,'jour')),reached?'':'Ce qu’il faut faire en premier, en deuxième, en troisième… C’est le chemin le plus rapide trouvé avec tes missions et ton temps.',()=>phaseCards(s,r)+(reached?'':'<p class="calc-note">Comment l’ordre est choisi : à chaque partie, on prend les missions qui rapportent le plus dans le temps de la partie, avec l’argent que tu as à ce moment-là. Un achat d’avant se fait dès que tu peux le payer sans toucher à ta réserve ; s’il débloque une mission ou rapporte de l’argent, la suite va plus vite.'+(r.limited?' Le programme vient des enchaînements comparés à chaque partie : il peut en exister un plus rapide.':'')+'</p>'),'main');
  /* 2. Plans de secours (calculés seulement quand on ouvre le point) */
  if(!reached){const late=obs&&obs.last&&obs.last.gap!==null&&obs.last.gap<-1e-9;
   const intro=late?'Ta dernière partie a rapporté <b>'+money(obs.last.gain)+'</b> au lieu de <b>'+money(obs.last.plannedGain)+'</b> prévus. Le plan ci-dessus repart déjà de ce que tu as ; voici quand même d’autres façons d’y arriver, avec leur temps.':'Si une mission ne rentre pas, si tu gagnes moins que prévu, ou si tu préfères faire autrement : chaque plan est calculé avec la même situation. Choisis-en un, le programme suit.';
   doc+=section('alternatives','Si ça ne se passe pas comme prévu',late?'<b>'+money(obs.last.gain)+'</b> gagnés au lieu de '+money(obs.last.plannedGain)+' prévus · plans A, B, C…':(r.variant!=='auto'?'Tu suis un plan de secours · les autres sont là':'Plans A, B, C… calculés sur ta situation, prêts si tu gagnes moins que prévu'),intro,()=>{const alt=B.planAlternatives(s,r),plans=alt.valid?alt.plans:[],curId=r.variant==='auto'?'all':r.variant,ok=plans.filter(x=>x.valid).sort((a,b)=>(a.id===curId?-1:b.id===curId?1:0)),ko=plans.filter(x=>!x.valid);
    return (ok.length?'<ol class="b-alts">'+ok.slice(0,5).map((x,i)=>'<li class="b-alt'+(x.id===curId?' is-current':'')+'"><span class="b-alt-letter">'+String.fromCharCode(65+i)+'</span><div><h4>Plan '+String.fromCharCode(65+i)+' · '+esc(x.label)+(x.id===curId?' <span class="calc-tag">TON PLAN ACTUEL</span>':'')+'</h4><div class="b-tiles"><span><small>Parties</small><b>'+x.totalSessions+'</b></span><span><small>Jours</small><b>'+x.days+'</b></span><span><small>À la fin</small><b>'+money(x.finalCash)+'</b></span></div><p class="b-alt-program">'+esc(programSummary(alt.results[x.id]))+'</p>'+(x.note?'<p class="calc-note">'+esc(x.note)+'</p>':'')+(x.id!==curId?btn('Suivre ce plan','data-b-plan-variant="'+esc(x.id)+'"'):'')+'</div></li>').join('')+'</ol>':'<p>'+esc(alt.valid?'Aucun autre plan ne marche avec ces chiffres.':alt.reason)+'</p>')+(ko.length?'<p class="calc-note"><b>Impossible avec ces chiffres :</b> '+ko.map(x=>esc(x.label)+' ('+esc(x.reason||'pas atteint')+')').join(' · ')+'</p>':'');},late?'alert':'');}
  /* 3. Suivi du réel */
  doc+=section('actual','Après avoir joué : où en es-tu vraiment ?',obs?'<b>'+plural(obs.sessions,'partie')+'</b> notée'+(obs.sessions>1?'s':'')+' · dernière : '+(obs.last.gain>=0?'+':'−')+money(Math.abs(obs.last.gain))+(obs.last.gap===null?'':' ('+(obs.last.gap>=0?'+':'−')+money(Math.abs(obs.last.gap))+' par rapport au prévu)'):'Écris ce que tu as après ta partie : tout le plan se recalcule','Écris ce que tu as maintenant et ce que tu as fait. Tout le plan se recalcule à partir de là : missions, achats, parties, jours. Rien n’est compté deux fois.',()=>actualForm(s,r,obs));
  /* 4. Point de départ */
  const start=[['Argent en poche',money(si.capital),'plan-capital'],['Gardé de côté',money(r.input.reserve)+(r.input.reserve!==(si.reserve??0)?' (ta priorité « vite » l’utilise)':''),'plan-reserve'],['Une partie',D+' · '+dpw+' j/semaine','plan-daily'],['Dépenses par partie',money(si.upkeepPerSession||0),'plan-upkeep'],
   p.source==='missions'?['Missions au choix',p.missions.map(m=>m.name).join(', ')||'aucune',p.missions.length?'plan-m-0-reward':'plan-m-source']:['Gain par heure (ton chiffre)',money(si.hourly),'plan-hourly'],
   g.kind==='purchase'?['Ton but',esc(g.name||'mon achat')+' · '+money(g.price)+(g.boostHourly>0?' · +'+money(g.boostHourly)+'/h ensuite':''),'plan-price']:g.kind==='amount'?['Ton but','avoir '+money(g.target),'plan-target']:['Ton but','débloquer '+esc(g.name||'mon but')+' · '+units(s,g.targetUnits)+(g.alsoPrice>0?' · puis '+money(g.alsoPrice):''),'plan-units-target'],
   ['Achats d’avant',p.prerequisites.length?p.prerequisites.map(a=>a.name+(a.owned?' (déjà possédé)':' ('+money(a.price)+(a.boostHourly>0?', +'+money(a.boostHourly)+'/h':'')+')')).join(' · '):'aucun','plan-prereq-search']];
  doc+=section('start','Ton point de départ',esc(money(si.capital)+' en poche · '+D+' · '+dpw+' j/sem · '+(p.source==='missions'?plural(p.missions.length,'mission'):money(si.hourly)+'/h')),'Les chiffres qui font ce plan. Change-en un : tout se recalcule.','<ul class="b-assumptions">'+start.map(([l,v,f])=>'<li><span>'+esc(l)+'</span><b>'+v+'</b>'+btn('Modifier','data-b-focus="'+f+'"')+'</li>').join('')+'</ul><p class="calc-note">Rien ne vient du vrai jeu : prix, gains et temps sont tes chiffres, ou ceux que le site indique comme repères.</p>');
  /* 5. Stratégie */
  const st=r.strategies;
  if(st&&st.valid&&st.candidates.filter(c=>c.valid).length>1){const rec=st.candidates.find(c=>c.id===st.recommended),asIs=st.candidates.find(c=>c.id==='asIs');
   const why=rec&&asIs&&rec.id!=='asIs'&&rec.valid&&asIs.valid?(rec.totalSessions<asIs.totalSessions?'tu gagnes '+plural(asIs.totalSessions-rec.totalSessions,'partie')+' par rapport à ton ordre':'même nombre de parties que ton ordre, avec '+(rec.reserveKept?'ta réserve gardée':'plus d’argent à la fin')):'c’est la façon la plus rapide parmi celles qui '+(p.priority==='fast'?'ont été comparées':'gardent ton argent de côté');
   doc+=section('strategy','L’ordre des achats d’avant','Conseillé : <b>'+esc(rec?rec.label:'')+'</b> · '+st.candidates.filter(c=>c.valid).length+' façons comparées','Même but, mêmes chiffres : seul l’ordre des achats, ou la réserve, change.','<p class="b-strategy-answer"><b>'+esc(rec?rec.label:'')+'</b> : '+esc(why)+'.</p>'+table([['Façon de faire','Parties','Jours','Argent à la fin','Réserve gardée'],...st.candidates.map(c=>[(c.id===st.recommended?'★ ':'')+c.label+(c.note?' — '+c.note:''),c.valid?String(c.totalSessions):'Impossible : '+c.reason,c.valid?String(c.days):'—',c.valid?money(c.finalCash):'—',c.reserveKept?'Oui':'Non'])],'Ordres comparés par recalcul complet',true)+'<p class="calc-note">On compare '+st.explored+' façons de faire ; il peut en exister une meilleure. Celles qui retirent un achat demandé ne sont jamais conseillées.</p>');}
  /* 6. Échéance */
  if(p.deadlineDays){let body='';if(!deadline||!deadline.valid)body=warning(deadline?deadline.reason:'Échéance non calculable.');
   else if(deadline.feasible)body='<p class="b-strategy-answer"><b>Oui</b>, c’est faisable : tu finis au jour '+deadline.days+', avec '+plural(deadline.spareDays,'jour')+' d’avance.</p>';
   else body='<p class="b-strategy-answer"><b>Pas avec ton rythme actuel</b> : tu finirais au jour '+deadline.days+', soit '+plural(deadline.spareDays,'jour')+' trop tard.</p><ul class="b-thresholds">'+(deadline.everydayDays!==null?'<li>Joue <b>tous les jours</b> : tu finis au jour '+deadline.everydayDays+'.</li>':'')+(deadline.requiredSessionMinutes!==null?'<li>Ou des parties de <b>'+hours(deadline.requiredSessionMinutes/60)+'</b> au lieu de '+D+'.</li>':'')+(deadline.requiredHourly!==null?'<li>Ou gagner <b>'+money(deadline.requiredHourly)+' par heure</b> au lieu de '+money(si.hourly)+'.</li>':'')+(deadline.everydayDays===null&&deadline.requiredSessionMinutes===null&&deadline.requiredHourly===null?'<li>Aucun réglage simple ne suffit : réduis le but ou change de missions.</li>':'')+'<li>Sinon, la date la plus proche : <b>jour '+r.days+'</b> (vers le '+planDate(r.days)+').</li></ul>';
   doc+=section('deadline','Ton échéance : '+plural(p.deadlineDays,'jour'),deadline&&deadline.valid?(deadline.feasible?'<b>Faisable</b> · '+plural(deadline.spareDays,'jour')+' d’avance':'<b>Pas avec ton rythme</b> · jour '+deadline.days+' au lieu de '+p.deadlineDays):'À vérifier','',body,deadline&&deadline.valid&&!deadline.feasible?'alert':'');}
  /* 7+. Détails */
  if(details&&!reached){
   const rows=r.sessions.slice(0,60).map(se=>['Partie '+se.index+' · jour '+dayOf(se.index,dpw),se.steps.length?se.steps.map(st=>st.name+' ×'+st.runs).join(', '):'ton gain par heure','+'+money(se.gain)+(g.kind==='unlock'&&se.unitsGain>0?' · +'+nf.format(Math.round(se.unitsGain*100)/100):''),money(se.cashAfter),se.purchases.length?se.purchases.join(', '):'—']);
   doc+=section('sessions','Partie par partie',plural(r.totalSessions,'partie')+' · de '+money(r.startCash)+' à '+money(r.finalCash),'Chaque partie avec ses missions, ce qu’elle rapporte, ce que tu as ensuite et ce que tu achètes.',()=>table([['Partie','Missions','Gagné','Tu as ensuite','Achat'],...rows],'Le programme complet'+(r.sessions.length>60?' (60 premières parties sur '+r.sessions.length+')':''),true));
   doc+=section('variants','Et si… ?','Parties plus longues, un jour de plus, prix plus chers, missions qui rapportent moins…','Le même plan, recalculé en entier avec un chiffre qui change.',()=>{const v=variants(s,r);return table([['Variante','Parties','Jours','Argent à la fin'],...v.map(x=>[x.label,x.r.valid&&x.r.reached?String(x.r.totalSessions):'Impossible',x.r.valid&&x.r.reached?String(x.r.days):'—',x.r.valid?money(x.r.finalCash):'—'])],'Pour voir ce qui pèse le plus',true);});
   doc+=section('thresholds','Les seuils qui changent la donne','30 min de plus par partie, l’achat d’avant tout de suite…','',()=>{const v=variants(s,r),thresholds=[];const longer=v.find(x=>x.id==='longer');if(longer&&longer.r.valid&&longer.r.reached)thresholds.push(longer.r.totalSessions<r.totalSessions?'Avec <b>30 min de plus par partie</b>, tu finis en <b>'+plural(longer.r.totalSessions,'partie')+'</b> au lieu de '+r.totalSessions+'.':'<b>30 min de plus par partie</b> ne changent pas le nombre de parties ('+r.totalSessions+') : le temps n’est pas ce qui bloque.');
    const firstBuy=r.purchases.find(x=>x.atSession);if(firstBuy&&firstBuy.atSession>1)thresholds.push('Il te manque <b>'+money(Math.max(0,firstBuy.price+r.input.reserve-r.startCash))+'</b> pour acheter « '+esc(firstBuy.name)+' » dès maintenant.');
    if(g.kind==='unlock'&&r.missingUnits===0&&r.startUnits<r.input.targetUnits)thresholds.push('Il te manque <b>'+units(s,r.input.targetUnits-r.startUnits)+'</b> pour débloquer '+esc(goalShort(s))+'.');
    return thresholds.length?'<ul class="b-thresholds">'+thresholds.map(t=>'<li>'+t+'</li>').join('')+'</ul>':'<p class="calc-note">Aucun seuil simple à signaler avec ces chiffres.</p>';});
   if(curve.length>1)doc+=section('curve','Ton argent au fil du plan','La courbe prévue'+(p.log.length?' et tes points réels (cliquables)':'')+' · '+money(r.startCash)+' → '+money(r.finalCash),'',()=>visual.chart('c-plan-curve',{title:'Ton argent, partie après partie',question:'Quand chaque achat devient-il possible, et où en seras-tu ?',xTitle:'Temps de jeu (heures)',yTitle:'Argent en poche ($)',unit:'$',xUnit:'h',area:true,series:[{name:'Prévu avec tes chiffres',kind:'forecast',points:curve.map(pt=>({x:pt.hours,y:pt.cash,label:pt.label,key:pt.purchase}))},...(p.log.length?[{name:'Réel (ce que tu as écrit)',kind:'realized',points:p.log.map((e,i)=>({x:e.minutes/60,y:e.capital,label:new Date(e.at).toLocaleDateString('fr-FR'),edit:'log:'+i}))}]:[])],thresholds:r.input.reserve>0?[{y:r.input.reserve,label:'Argent gardé de côté'}]:[],reading:'Chaque marche vers le bas est un achat payé ; entre deux, ton argent monte partie après partie. Le plan finit après '+plural(r.totalSessions,'partie')+'.',note:'Les points « réel » viennent de tes mises à jour ; ils ne sont pas lissés. Clique sur un point réel pour le corriger ou le retirer.'}));
   const cal=[...r.purchases.filter(x=>x.atSession).map(x=>['Achète « '+x.name+' »','après la partie '+x.atSession,'jour '+dayOf(x.atSession,dpw),planDate(dayOf(x.atSession,dpw))]),[g.kind==='purchase'?'Achète '+goalShort(s):g.kind==='unlock'?'Débloque '+goalShort(s):'Tu as '+goalShort(s),'après la partie '+r.totalSessions,'jour '+r.days,planDate(r.days)]];
   doc+=section('calendar','Ton calendrier','But vers le <b>'+esc(planDate(r.days))+'</b>'+(cal.length>1?' · '+plural(cal.length-1,'achat')+' avant':''),'Si tu joues '+D+' par partie, '+dpw+' jour'+(dpw>1?'s':'')+' par semaine, en commençant aujourd’hui.',table([['Étape','Quand','Jour','Date estimée'],...cal],'Les moments qui comptent',true));
   doc+=section('method','Comment est-ce calculé ?','Partie après partie, avec tes chiffres, sans rien inventer','','<p class="calc-note">Partie après partie : avec l’argent que tu as à ce moment-là, on cherche les missions qui rapportent le plus dans le temps de la partie (frais payés avant, récompense à la fin, préparation et attente comptées, une mission se fait en entier ou pas du tout). On enlève tes dépenses par partie, on ajoute ce que rapportent tes achats déjà faits. Puis on paie les achats d’avant, dans l’ordre, dès que l’argent dépasse le prix sans toucher à la réserve ; un achat peut débloquer une mission. On s’arrête quand tu peux payer ton but (et que tu as les points, s’il en faut). Jours = parties réparties sur tes jours de jeu par semaine, en commençant aujourd’hui. Rien ne vient du vrai jeu.</p>');}
  else if(!reached&&mode!=='advanced')doc+='<p class="calc-note b-doc-more">Coche « Afficher plus de détails » pour voir chaque partie, les « et si », la courbe et le calendrier.</p>';
  doc+='<div class="b-plan-links">'+btn('Préparer ma prochaine partie','data-open="session"')+btn('Vérifier ce qu’un achat rapporte','data-open="roi"')+btn('Comparer des achats','data-open="compare"')+'</div></div>';
  $('plan-report').innerHTML=doc;
  $('expert-plan').innerHTML=expert?expertBlock(s,r):'';
 }
 function markSkips(s){document.querySelectorAll('#panel-plan .calc-step[data-step="4"]').forEach(n=>{if(!s.plan.prerequisites.length&&s.plan.goal.kind==='amount')n.dataset.skip='1';else delete n.dataset.skip;});}
 function variantLabel(s,r){if(r.variant==='auto')return '';const alt=B.planAlternatives(s,r);const x=alt.valid?alt.plans.find(y=>y.id===r.variant):null;return x?x.label:r.variant;}
 function variants(s,r){const i=r.input,out=[];const run=(id,label,changes)=>out.push({id,label,r:E.missionPlan({...i,...changes})});
  run('longer','Des parties de 30 min de plus',{sessionMinutes:i.sessionMinutes+30});
  if(i.daysPerWeek<7)run('everyday','Un jour de jeu de plus par semaine',{daysPerWeek:i.daysPerWeek+1});
  run('prices','Les prix sont 20 % plus chers',{goalPrice:i.goalPrice===null?null:i.goalPrice*1.2,target:i.target===null?null:i.target*1.2,purchases:i.purchases.map(x=>({...x,price:x.price*1.2}))});
  run('less',s.plan.source==='missions'?'Mes missions rapportent 20 % de moins':'Je gagne 20 % de moins',s.plan.source==='missions'?{activities:i.activities.map(a=>({...a,reward:a.reward===null?null:a.reward*0.8}))}:{hourly:i.hourly*0.8});
  if(i.reserve>0)run('reserve','Je touche à ma réserve',{reserve:0});
  return out;}
 function actualForm(s,r,obs){const p=s.plan,g=p.goal,si=p.situation,next=B.planNextSession(r);
  let html='<div class="calc-fields b-actual"><div class="calc-field"><label class="calc-label" for="plan-actual">J’ai maintenant ($)</label><input id="plan-actual" type="text" inputmode="decimal" maxlength="25" data-number="1" data-min="0" data-max="1000000000000" value="" placeholder="'+esc(nf.format(si.capital??0))+'"><small>Ton argent en poche après ta partie.</small></div><div class="calc-field"><label class="calc-label" for="plan-actual-minutes">J’ai joué (minutes)</label><input id="plan-actual-minutes" type="text" inputmode="decimal" maxlength="6" data-number="1" data-min="0" data-max="100000" value="'+esc(si.dailyMinutes??'')+'"></div>';
  if(g.kind==='unlock')html+='<div class="calc-field"><label class="calc-label" for="plan-actual-units">J’ai maintenant ('+esc(g.unitLabel||'points')+')</label><input id="plan-actual-units" type="text" inputmode="decimal" maxlength="25" data-number="1" data-min="0" data-max="1000000000000" value="" placeholder="'+esc(nf.format(g.currentUnits??0))+'"></div>';
  if(p.source==='missions')html+=p.missions.map(m=>{const planned=next?next.steps.find(st=>st.id===m.id):null;return '<div class="calc-field"><label class="calc-label" for="plan-actual-runs-'+esc(m.id)+'">« '+esc(m.name)+' » faite combien de fois ?</label><input id="plan-actual-runs-'+esc(m.id)+'" data-b-plan-actual-runs="'+esc(m.id)+'" type="text" inputmode="numeric" maxlength="6" data-number="1" data-min="0" data-max="100000" value="" placeholder="'+(planned?'prévu : '+planned.runs:'0')+'"></div>';}).join('');
  html+='<div class="calc-field wide"><label class="calc-label" for="plan-actual-note">Une note, si tu veux</label><input id="plan-actual-note" type="text" maxlength="300" value="" placeholder="Ce qui s’est passé pendant la partie"></div></div>';
  const buyable=p.prerequisites.filter(a=>!a.owned);if(buyable.length)html+='<fieldset class="b-plan-requires"><legend>Pendant cette partie, j’ai acheté :</legend>'+buyable.map(a=>'<label class="calc-check"><input type="checkbox" data-b-plan-actual-bought="'+esc(a.id)+'"> '+esc(a.name)+(a.price!==null?' ('+money(a.price)+')':'')+'</label>').join('')+'</fieldset>';
  html+='<div class="b-plan-card-actions">'+btn('Mettre à jour mon plan','data-b-plan-log="1"',true)+(p.log.length?btn('Effacer l’historique','data-b-plan-clear="1"'):'')+'</div><p class="calc-note" id="plan-log-feedback" role="status"></p>';
  if(obs&&obs.last){const L=obs.last,gap=L.gap;
   html+='<div class="b-bilan"><p class="calc-kicker">BILAN DE TA DERNIÈRE PARTIE</p><div class="b-tiles">'+[['Prévu',L.plannedGain===null?'—':'+'+money(L.plannedGain)],['Réel','+'+money(L.gain)],['Écart',gap===null?'—':(gap>=0?'+':'−')+money(Math.abs(gap))],['Ton rythme réel',obs.hourly===null?'—':money(Math.round(obs.hourly))+' par heure']].map(([l,v])=>'<span><small>'+esc(l)+'</small><b>'+v+'</b></span>').join('')+'</div><p>'+esc(gap===null?'Le plan repart de ce que tu as maintenant.':gap>=0?'Tu es en avance : le plan repart de ce que tu as, et il est plus court.':'Tu as gagné moins que prévu : le plan repart de ce que tu as, et la section « Si ça ne se passe pas comme prévu » propose d’autres chemins.')+(obs.sessions>1?' Sur tes '+obs.sessions+' parties notées, tu gagnes en moyenne '+money(obs.perSession)+' par partie.':'')+'</p>'+(p.source==='hourly'&&obs.hourly!==null&&Math.abs(obs.hourly-(si.hourly||0))>1?btn('Adopter mon vrai rythme ('+money(obs.hourly)+' par heure)','data-b-plan-adopt="1"'):'')+'</div>';}
  if(p.log.length){const rows=p.log.slice().reverse().map(e=>{const d=new Date(e.at),date=Number.isFinite(d.getTime())?d.toLocaleDateString('fr-FR',{day:'numeric',month:'short'}):'—';return [date,hours(e.minutes/60),e.plannedGain===null?'—':'+'+money(e.plannedGain),e.gain===null?'—':'+'+money(e.gain),money(e.capital),e.forecast===null?'—':money(e.forecast),Object.keys(e.runs).length?Object.entries(e.runs).filter(([,n])=>n>0).map(([id,n])=>(p.missions.find(m=>m.id===id)?.name||id)+' ×'+n).join(', ')+(e.purchases.length?' · acheté : '+e.purchases.map(id=>p.prerequisites.find(a=>a.id===id)?.name||id).join(', '):''):(e.purchases.length?'acheté : '+e.purchases.map(id=>p.prerequisites.find(a=>a.id===id)?.name||id).join(', '):'—'),e.note||'—'];});
   html+=table([['Date','Joué en tout','Prévu (partie)','Réel (partie)','J’avais','Le plan prévoyait','Fait','Note'],...rows],'Réalisé contre prévu, partie après partie',true)+'<p class="calc-note">« Le plan prévoyait » = l’argent attendu après ce temps de jeu, d’après le plan d’avant la mise à jour. Le plan actuel repart toujours du réel.</p>';}
  return html;}
 function expertBlock(s,r){const rows=Object.entries(r).filter(([k,v])=>typeof v==='number'||v===null).map(([k,v])=>[k,v===null?'Non disponible':nf.format(v)]);const i=r.input;
  return '<div class="b-doc b-doc--light"><div class="b-doc-title b-doc-title--plain"><span class="b-doc-num">★</span><div><h3>Mes réglages avancés</h3><p class="b-doc-lead">Le mode Expert affiche tout : chaque partie, les « et si », la courbe, le calendrier, et les entrées et résultats bruts du moteur. Les mêmes chiffres qu’en Simple, avec le détail.</p></div></div>'+fold('plan-x-inputs',{n:1,title:'Valeurs effectivement utilisées',teaser:esc(money(i.capital)+' · réserve '+money(i.reserve)+' · '+hours(i.sessionMinutes/60)+' · stratégie '+STRATEGY_LABEL[r.strategy||'asIs']),body:()=>table([['Entrée du moteur','Valeur'],['Argent',money(i.capital)],['Réserve',money(i.reserve)],['Durée d’une partie',hours(i.sessionMinutes/60)],['Jours par semaine',String(i.daysPerWeek)],['Dépenses par partie',money(i.upkeepPerSession)],['Gain continu par heure',money(i.hourly)],['Missions',i.activities.map(a=>a.name).join(', ')||'aucune'],['But',i.goalPrice!==null?i.goalName+' : '+money(i.goalPrice):i.target!==null?'Avoir '+money(i.target):'Débloquer '+i.goalName],['Points à atteindre',i.targetUnits===null?'—':nf.format(i.targetUnits)+' (déjà '+nf.format(i.currentUnits)+')'],['Achats d’avant retenus',i.purchases.map(x=>x.name).join(', ')||'aucun'],['Stratégie',STRATEGY_LABEL[r.strategy||'asIs']],['Plan suivi',r.variant]],'Valeurs effectivement utilisées')})+fold('plan-x-raw',{n:2,title:'Résultats bruts du moteur',teaser:esc(rows.length+' valeurs'),body:()=>table(rows,'Résultats numériques')})+'</div>';}
 /* ---------- Événements propres au plan ---------- */
 function event(ev){const el=ev.target,s=state(),p=s.plan;
  if(ev.type==='change'){
   if(el.dataset.field==='plan.goal.kind'){if(B.PLAN_KINDS.includes(el.value))p.goal.kind=el.value;p.variant='auto';refresh(el.id);return true;}
   if(el.dataset.field==='plan.source'){if(B.PLAN_SOURCES.includes(el.value))p.source=el.value;p.variant='auto';refresh(el.id);return true;}
   if(el.dataset.field==='plan.strategy'){p.strategy=B.STRATEGIES.includes(el.value)?el.value:'auto';api.changed();return true;}
   if(el.dataset.bPlanMOwned!==undefined){const m=p.missions[Number(el.dataset.bPlanMOwned)];if(m)m.owned=el.checked;api.changed();return true;}
   if(el.dataset.bPlanMReq!==undefined){const [i,id]=el.dataset.bPlanMReq.split('|'),m=p.missions[Number(i)];if(m){m.requires=el.checked?[...new Set([...m.requires,id])]:m.requires.filter(x=>x!==id);}api.changed();return true;}
   if(el.dataset.bPlanPOwned!==undefined){const a=p.prerequisites[Number(el.dataset.bPlanPOwned)];if(a)a.owned=el.checked;p.variant='auto';api.changed();return true;}
   if(el.dataset.bPlanDetails!==undefined){p.details=el.checked;render();api.saveLocal();return true;}
   if(el.dataset.bPlanActualBought!==undefined||el.dataset.bPlanActualRuns!==undefined)return true;
  }
  if(ev.type==='input'&&(el.id==='plan-actual'||el.id==='plan-actual-minutes'||el.id==='plan-actual-units'||el.id==='plan-actual-note'||el.dataset.bPlanActualRuns!==undefined))return true;
  if(ev.type==='click'){const button=el.closest('button');if(!button)return false;const d=button.dataset;
   if(d.bPlanImportCalcs){importFromCalcs(s);p.variant='auto';refresh('plan-capital');api.notify('Tes chiffres de Mes calculs ont été copiés dans le plan. Tu peux les changer ici sans rien changer là-bas.');return true;}
   if(d.bPlanFree){p.goal.kind='purchase';p.goal.itemId='';p.goal.referencePrice=null;if(!p.goal.name)p.goal.name='Mon but';refresh('plan-name');return true;}
   if(d.bPlanPriceReset){p.goal.price=p.goal.referencePrice;refresh('plan-price');return true;}
   if(d.bPlanMAdd){if(p.missions.length>=12){api.notify('Douze missions au maximum dans le plan.');return true;}const id='m-'+Date.now().toString(36)+'-'+p.missions.length;p.missions.push({...B.copy(B.planMissionTemplate),id,name:'Mission '+(p.missions.length+1)});p.source='missions';p.variant='auto';refresh('plan-m-'+(p.missions.length-1)+'-name');return true;}
   if(d.bPlanMImport){const sel=$('plan-m-source');if(!sel)return true;const [kind,id]=sel.value.split(':'),a=(kind==='mine'?s.activities:sourceActivities).find(x=>x.id===id);if(!a)return true;if(p.missions.length>=12){api.notify('Douze missions au maximum dans le plan.');return true;}
    p.missions.push({...B.copy(B.planMissionTemplate),id:'m-'+Date.now().toString(36)+'-'+p.missions.length,name:a.name,reward:a.reward??null,cost:a.cost??0,duration:a.duration??null,prep:a.prep??0,cooldown:a.cooldown??0,share:a.share??100,investment:a.investment??0,owned:a.owned===true});p.source='missions';p.variant='auto';refresh('plan-m-'+(p.missions.length-1)+'-name');api.notify('« '+a.name+' » copiée dans le plan.');return true;}
   if(d.bPlanMRemove!==undefined){p.missions.splice(Number(d.bPlanMRemove),1);p.variant='auto';refresh('plan-m-source');return true;}
   if(d.bPlanPAdd){if(p.prerequisites.length>=20){api.notify('Vingt achats d’avant au maximum.');return true;}p.prerequisites.push({...B.copy(B.planPrereqTemplate),id:'p-'+Date.now().toString(36)+'-'+p.prerequisites.length,name:'Mon achat d’avant'});p.variant='auto';refresh('plan-p-'+(p.prerequisites.length-1)+'-name');return true;}
   if(d.bPlanPRemove!==undefined){const [a]=p.prerequisites.splice(Number(d.bPlanPRemove),1);if(a)p.missions.forEach(m=>{m.requires=m.requires.filter(x=>x!==a.id);});p.variant='auto';refresh('plan-prereq-search');return true;}
   if(d.bPlanPUp!==undefined||d.bPlanPDown!==undefined){const i=Number(d.bPlanPUp??d.bPlanPDown),j=i+(d.bPlanPUp!==undefined?-1:1);if(j>=0&&j<p.prerequisites.length)[p.prerequisites[i],p.prerequisites[j]]=[p.prerequisites[j],p.prerequisites[i]];refresh();return true;}
   if(d.bPlanVariant!==undefined){p.variant=d.bPlanVariant||'auto';api.changed();api.notify(p.variant==='auto'?'Retour au meilleur plan trouvé.':'Le programme suit maintenant ce plan de secours.');return true;}
   if(d.bPlanAdopt){const obs=B.planObserved(s);if(obs&&obs.hourly!==null){p.situation.hourly=Math.round(obs.hourly);document.querySelectorAll('[data-field="plan.situation.hourly"]').forEach(i=>{i.value=p.situation.hourly;});api.changed();api.notify('Ton gain par heure est maintenant celui que tu as vraiment eu : '+money(p.situation.hourly)+'.');}return true;}
   if(d.bPlanLog){return logSession(s);}
   if(d.bPlanClear){p.log=[];p.playedMinutes=0;p.sessionsPlayed=0;api.changed();api.notify('Historique effacé. Ton argent actuel est gardé.');return true;}
   if(d.bPlanExport){const r=B.evaluate('plan',s);const text=exportText(s,r);const blob=new Blob([text],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mon-business-plan-leonidakit.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);api.notify('Plan exporté en texte lisible.');return true;}
  }
  return false;}
 function importFromCalcs(s){const p=s.plan,g=s.goal;p.situation.capital=g.capital;p.situation.reserve=g.reserve??0;p.situation.hourly=g.hourly;p.situation.dailyMinutes=g.dailyMinutes??s.session.usualMinutes??s.session.minutes;p.situation.daysPerWeek=s.session.daysPerWeek??7;
  if(p.goal.kind==='amount'&&p.goal.target===null)p.goal.target=g.target;
  const total=a=>a.price===null?null:a.price+(a.extras||0)+(a.fees||0),boost=a=>a.incomeMode==='personal'&&Number.isFinite(a.boostHourly)?a.boostHourly:0;
  const existing=new Set(p.prerequisites.map(a=>a.itemId||a.name));s.order.keys.forEach(k=>{const a=B.asset(s,k);if(!a||existing.has(a.itemId||a.name)||p.prerequisites.length>=20)return;p.prerequisites.push({id:'p-'+Date.now().toString(36)+'-'+p.prerequisites.length,name:a.name,itemId:a.itemId||'',referencePrice:a.referencePrice??null,price:total(a),boostHourly:boost(a),owned:a.owned===true});});
  const names=new Set(p.missions.map(m=>m.name));s.activities.filter(a=>Number.isFinite(a.reward)&&Number.isFinite(a.duration)&&s.session.enabled.includes(a.id)).forEach(a=>{if(names.has(a.name)||p.missions.length>=12)return;p.missions.push({...B.copy(B.planMissionTemplate),id:'m-'+Date.now().toString(36)+'-'+p.missions.length,name:a.name,reward:a.reward,cost:a.cost??0,duration:a.duration,prep:a.prep??0,cooldown:a.cooldown??0,share:a.share??100,investment:a.investment??0,owned:a.owned===true});});
  if(s.model==='cycles'&&p.missions.length)p.source='missions';}
 function logSession(s){const p=s.plan,g=s.plan.goal,fb=$('plan-log-feedback');
  const cap=parse($('plan-actual')?.value),mins=parse($('plan-actual-minutes')?.value);
  if(cap===null||cap<0||cap>1e12){if(fb)fb.textContent='Écris ce que tu as maintenant, avec un nombre (par exemple 350 000).';$('plan-actual')?.focus();return true;}
  if(mins===null||mins<0||mins>1e5){if(fb)fb.textContent='Écris le temps joué en minutes (par exemple 60).';$('plan-actual-minutes')?.focus();return true;}
  let unitsNow=null;if(g.kind==='unlock'){const v=parse($('plan-actual-units')?.value);if(v!==null){if(v<0||v>1e12){if(fb)fb.textContent='Écris tes '+g.unitLabel+' avec un nombre.';$('plan-actual-units')?.focus();return true;}unitsNow=v;}}
  const runs={};document.querySelectorAll('[data-b-plan-actual-runs]').forEach(el=>{const v=parse(el.value);if(v!==null&&v>=0)runs[el.dataset.bPlanActualRuns]=Math.round(v);});
  const bought=[...document.querySelectorAll('[data-b-plan-actual-bought]:checked')].map(el=>el.dataset.bPlanActualBought).filter(id=>p.prerequisites.some(a=>a.id===id));
  const note=String($('plan-actual-note')?.value||'').slice(0,300);
  const before=B.evaluate('plan',s),curve=before.valid?B.planCurve(before):[],next=B.planNextSession(before);
  const at=E.planCashAt({points:curve.map(pt=>({hours:pt.hours,cash:pt.cash})),hours:((p.playedMinutes||0)+mins)/60}),forecast=at&&at.valid?at.cash:null;
  const spent=bought.reduce((a,id)=>a+(p.prerequisites.find(x=>x.id===id)?.price||0),0),gain=Number.isFinite(p.situation.capital)?cap-p.situation.capital+spent:null,plannedGain=next?next.gain:null;
  const unitsGain=unitsNow!==null&&Number.isFinite(g.currentUnits)?unitsNow-g.currentUnits:null;
  p.situation.capital=cap;if(unitsNow!==null)g.currentUnits=unitsNow;bought.forEach(id=>{const a=p.prerequisites.find(x=>x.id===id);if(a)a.owned=true;});
  p.playedMinutes=(p.playedMinutes||0)+mins;p.sessionsPlayed=(p.sessionsPlayed||0)+1;
  p.log.push({at:new Date().toISOString(),capital:cap,minutes:p.playedMinutes,forecast,note,units:unitsNow,unitsGain,gain,plannedGain,sessionMinutes:mins,runs,purchases:bought});if(p.log.length>60)p.log=p.log.slice(-60);
  document.querySelectorAll('[data-field="plan.situation.capital"]').forEach(i=>{i.value=cap;});if(unitsNow!==null)document.querySelectorAll('[data-field="plan.goal.currentUnits"]').forEach(i=>{i.value=unitsNow;});
  if(bought.length)refresh('plan-actual');else api.changed();
  const gap=plannedGain===null||gain===null?null:gain-plannedGain;
  api.notify('Plan refait à partir de '+money(cap)+'.'+(gap===null?'':gap>=0?' Tu as gagné '+money(gap)+' de plus que prévu.':' Tu as gagné '+money(-gap)+' de moins que prévu : regarde les plans de secours.'));return true;}
 /* ---------- Fiche complète (enregistrement) : le plan entier, lisible comme un document ---------- */
 function sheet(cfg,at){const s=cfg,p=s.plan,g=p.goal,si=p.situation,r=B.evaluate('plan',s),base=at||new Date().toISOString(),date=new Date(base),dateText=Number.isFinite(date.getTime())?date.toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'}):'—';
  let html='<article class="b-sheet"><div class="b-sheet-head"><p class="calc-kicker">LEONIDAKIT · FICHE DE BUSINESS PLAN</p><h2 id="calc-sheet-title">'+esc(s.name||'Mon plan')+'</h2><p class="b-doc-meta">'+esc('But : '+goalName(s)+' · enregistré le '+dateText)+'</p></div>';
  if(!r.valid){html+='<p class="calc-warning">'+esc('Plan non calculable au moment de l’enregistrement : '+r.reason)+'</p></article>';return html;}
  const D=sessionLabel(s),dpw=r.input.daysPerWeek,reached=r.totalSessions===0;
  html+='<section><h3>En bref</h3><div class="b-tiles">'+[['Parties de '+D,String(r.totalSessions)],['Jours',String(r.days)],['Départ',money(r.startCash)],['À la fin',money(r.finalCash)]].map(([l,v])=>'<span><small>'+esc(l)+'</small><b>'+v+'</b></span>').join('')+'</div><p>'+esc(reached?'Le but est déjà possible avec ce que tu as.':'Il faut '+plural(r.totalSessions,'partie')+' de '+D+', '+dpw+' jour'+(dpw>1?'s':'')+' par semaine : vers le '+planDate(r.days,base)+' si tu commences le '+dateText+'.')+'</p></section>';
  html+='<section><h3>Le but</h3><p>'+esc(g.kind==='purchase'?(g.name||'Mon achat')+' — '+money(g.price)+(g.boostHourly>0?', il rapportera '+money(g.boostHourly)+' de plus par heure une fois acheté':', achat plaisir'):g.kind==='amount'?'Avoir '+money(g.target)+' en poche, en plus de la réserve':'Débloquer '+(g.name||'mon but')+' : atteindre '+nf.format(g.targetUnits)+' '+g.unitLabel+' (déjà '+nf.format(g.currentUnits||0)+')'+(g.alsoPrice>0?', puis le payer '+money(g.alsoPrice):''))+'.</p></section>';
  html+='<section><h3>Où j’en suis</h3><ul class="b-sheet-list"><li>Argent en poche : <b>'+money(si.capital)+'</b></li><li>Gardé de côté : <b>'+money(si.reserve)+'</b>'+(r.input.reserve!==(si.reserve??0)?' (la priorité « vite » l’utilise)':'')+'</li><li>Une partie : <b>'+D+'</b>, '+dpw+' jour'+(dpw>1?'s':'')+' par semaine</li>'+(si.upkeepPerSession>0?'<li>Dépenses par partie : <b>'+money(si.upkeepPerSession)+'</b></li>':'')+(p.source==='hourly'?'<li>Je gagne à peu près <b>'+money(si.hourly)+' par heure</b></li>':'')+'</ul></section>';
  if(p.source==='missions'&&p.missions.length)html+='<section><h3>Mes missions</h3>'+table([['Mission','Récompense','Frais','Durée','Attente','Par mission','Par heure'+(g.kind==='unlock'?'':'')].concat(g.kind==='unlock'?[g.unitLabel]:[]),...p.missions.map(m=>{const a=E.activity(m);return [m.name+(m.requires.length?' (après : '+m.requires.map(id=>p.prerequisites.find(x=>x.id===id)?.name||id).join(', ')+')':''),money(m.reward),money(m.cost),hours(((m.duration||0)+(m.prep||0))/60),m.cooldown?hours(m.cooldown/60):'—',a.valid?money(a.net):'—',a.valid?money(a.hourly):'—'].concat(g.kind==='unlock'?[nf.format(m.units||0)]:[]);})],'Tes chiffres, frais payés avant, récompense à la fin',true)+'</section>';
  html+='<section><h3>Le programme, dans l’ordre</h3>'+phaseCards(s,r,base)+'</section>';
  if(r.purchases.length)html+='<section><h3>Mes achats et investissements</h3>'+table([['Achat','Prix','Quand','Ce qu’il rapporte ensuite'],...r.purchases.map(x=>[x.name,money(x.price),x.owned&&!x.atSession?'déjà possédé':x.atSession?'après la partie '+x.atSession+' · jour '+dayOf(x.atSession,dpw)+' (vers le '+planDate(dayOf(x.atSession,dpw),base)+')':'pas dans ce plan',x.boostHourly>0?'+'+money(x.boostHourly)+' par heure'+(x.price>0?' · remboursé après '+hours(x.price/x.boostHourly)+' de jeu':''):'rien de plus'])],'Chaque achat se paie quand l’argent le permet, sans toucher à la réserve',true)+'</section>';
  if(!reached){const alt=B.planAlternatives(s,r),curId=r.variant==='auto'?'all':r.variant,ok=alt.valid?alt.plans.filter(x=>x.valid).sort((a,b)=>(a.id===curId?-1:b.id===curId?1:0)):[];if(ok.length>1)html+='<section><h3>Si ça ne se passe pas comme prévu</h3><ol class="b-sheet-alts">'+ok.slice(0,4).map((x,i)=>'<li><b>Plan '+String.fromCharCode(65+i)+' · '+esc(x.label)+'</b> : '+plural(x.totalSessions,'partie')+', '+plural(x.days,'jour')+', '+money(x.finalCash)+' à la fin. '+esc(programSummary(alt.results[x.id]))+'</li>').join('')+'</ol></section>';}
  if(p.log.length)html+='<section><h3>Ce que j’ai vraiment fait</h3>'+table([['Date','Joué en tout','Prévu (partie)','Réel (partie)','J’avais','Note'],...p.log.slice().reverse().map(e=>{const d=new Date(e.at);return [Number.isFinite(d.getTime())?d.toLocaleDateString('fr-FR'):'—',hours(e.minutes/60),e.plannedGain===null?'—':'+'+money(e.plannedGain),e.gain===null?'—':'+'+money(e.gain),money(e.capital),e.note||'—'];})],'Mes mises à jour',true)+'</section>';
  html+='<div class="b-sheet-foot"><p>Ce sont tes chiffres, pas ceux du jeu : aucun prix, gain ou mécanique de GTA VI n’est promis. Recalcule sur leonidakit.com/calculateurs.html?tool=plan.</p></div></article>';return html;}
 function shortSummary(s){const r=B.evaluate('plan',s);const name=goalName(s);if(!r.valid)return 'But : '+name+' · plan à compléter ('+r.reason+')';return 'But : '+name+' · '+(r.totalSessions===0?'déjà possible':plural(r.totalSessions,'partie')+' de '+sessionLabel(s)+' · '+plural(r.days,'jour'))+' · '+(s.plan.source==='missions'?plural(s.plan.missions.length,'mission'):money(s.plan.situation.hourly)+'/h')+(r.purchases.some(x=>x.atSession)?' · '+plural(r.purchases.filter(x=>x.atSession).length,'achat')+' d’avant':'');}
 function exportText(s,r){const p=s.plan,g=p.goal,si=p.situation;const lines=['MON BUSINESS PLAN — Leonidakit ('+new Date().toLocaleDateString('fr-FR')+')','But : '+goalName(s),'Départ : '+money(si.capital)+' en poche, '+money(si.reserve)+' de côté, parties de '+sessionLabel(s)+', '+(si.daysPerWeek??7)+' j/semaine'+(p.source==='hourly'?', '+money(si.hourly)+' par heure':', '+p.missions.length+' mission(s)'),''];
  if(!r.valid){lines.push('Plan non calculable : '+r.reason);return lines.join('\n');}
  lines.push(r.totalSessions===0?'Le but est déjà possible.':r.totalSessions+' parties, '+r.days+' jours (vers le '+planDate(r.days)+'). À la fin : '+money(r.finalCash)+'.','','PROGRAMME, DANS L’ORDRE');
  r.phases.forEach((ph,i)=>lines.push((i+1)+'. '+(ph.count===1?'Partie '+ph.from:'Parties '+ph.from+' à '+ph.to)+' : '+(ph.steps.length?ph.steps.map(st=>st.name+' ×'+st.runs).join(', '):'ton gain par heure')+' — +'+money(ph.gain)+' par partie, de '+money(ph.cashBefore)+' à '+money(ph.cashAfter)+(ph.purchasesAfter.length?' — puis achète '+ph.purchasesAfter.join(', '):'')));
  if(r.totalSessions>0)lines.push((r.phases.length+1)+'. Après la partie '+r.totalSessions+' : '+(g.kind==='purchase'?'achète '+(g.name||'ton but'):g.kind==='unlock'?'tu débloques '+(g.name||'ton but'):'tu as '+money(g.target))+'.');
  if(p.log.length){lines.push('','SUIVI');p.log.forEach(e=>lines.push(new Date(e.at).toLocaleDateString('fr-FR')+' · joué '+hours(e.minutes/60)+' · prévu '+(e.plannedGain===null?'—':'+'+money(e.plannedGain))+' · réel '+(e.gain===null?'—':'+'+money(e.gain))+' · j’avais '+money(e.capital)));}
  lines.push('','Ce sont tes chiffres, pas ceux du jeu. Recalculé sur leonidakit.com/calculateurs.html?tool=plan');return lines.join('\n');}
 return {markup,render,event,sheet,shortSummary,exportText,goalName,STRATEGY_LABEL};
}
global.LKCalcPlan={create};
})(window);
