/* v7.61 : pluriel selon la langue de la page : français n > 1 (« 0 coché », « 1,5 million ») ; anglais, espagnol n ≠ 1 (« 0 marcados ») */
var lkPluriel=function(n){return ((typeof document!=='undefined'&&document.documentElement&&document.documentElement.lang)||'fr').slice(0,2)==='fr'?n>1:n!==1;};
/* Mon business plan (v7.34) : un programme mission par mission, avec ses propres réponses.
   Le plan ne prend rien en silence dans les huit calculs : il pose ses questions (but, situation, missions, achats d'avant).
   Tout chiffre vient du moteur (LKCalcEngine.missionPlan) via le scénario partagé (LKCalcScenario) ; ce fichier ne fait
   que présenter : réponse, prochaine partie, programme dans l'ordre, plans de secours, suivi du réel avec recalcul complet,
   point de départ, stratégie, échéance, détails (partie par partie, et si, courbe, calendrier, formule), fiche enregistrée. */
(function(global){'use strict';
const B=global.LKCalcScenario;
function create(env){
 const {esc,money,hours,field,stats,warning,btn,select,table,state,sourceActivities,visual,api,problem,itemFor,selectedCard,combobox,step,refresh,fold,explainBlock,analysisOf}=env;
 const E=global.LKCalcEngine,nf=new Intl.NumberFormat('fr-FR',{maximumFractionDigits:2}),$=id=>document.getElementById(id);
 /* correctif lot 2 (REG6-1) : le gain d’une partie peut être négatif (achat de départ payé dans la partie, obtention avec coût d’usage) : un seul signe
    devant le montant (« −100 000 $ »), jamais « +-100 000 $ » (le « + » codé en dur précédait le signe moins du format). Même forme que la cellule « Écart ». */
 const signed=v=>(Number.isFinite(v)&&v<0?'−':'+')+money(Math.abs(v));
 const STRATEGY_LABEL=B.STRATEGY_LABEL;
 const ORDINALS=['En premier','En deuxième','En troisième','En quatrième','En cinquième','En sixième','En septième','En huitième','En neuvième','En dixième'];
 const KIND_LABEL={purchase:'Acheter quelque chose',amount:'Avoir une somme d’argent',unlock:'Débloquer quelque chose avec de l’expérience (rang, XP, réputation…)'};
 function planDate(days,base){const d=base?new Date(base):new Date();if(!Number.isFinite(d.getTime()))return '—';d.setDate(d.getDate()+days);return d.toLocaleDateString('fr-FR',{day:'numeric',month:'long'});}
 const dayOf=(n,dpw)=>E.calendarDays(n,dpw); /* lot 2 : un seul calendrier, celui du moteur (même valeur qu’avant) */
 const pct=v=>v===null||!Number.isFinite(v)?'—':nf.format(Math.round(v*10)/10)+' %';
 const plural=(n,w,ws)=>n+(E.plural(n)?ws:w); /* v7.62 : singulier et pluriel écrits en entier, espace devant (« 3 jours », allemand « 3 Tage ») */
 const units=(s,n)=>(Number.isFinite(n)?nf.format(Math.round(n*100)/100):'—')+' '+esc(s.plan.goal.unitLabel||'points');
 const sessionLabel=s=>s.plan.situation.dailyMinutes?hours(s.plan.situation.dailyMinutes/60):'durée libre';
 function goalName(s){const g=s.plan.goal;return g.kind==='amount'?'avoir '+money(g.target):g.kind==='unlock'?'débloquer '+(g.name||'mon but'):(g.name||'mon achat');}
 function goalShort(s){const g=s.plan.goal;return g.kind==='amount'?money(g.target):(g.name||(g.kind==='unlock'?'mon but':'mon achat'));}
 function parse(v){const P=E.parseLocalizedNumber;if(v===undefined||v===null)return null;if(String(v).trim()==='')return null;const r=P(String(v));return r.valid?r.value:null;}
 /* ---------- Formulaire : cinq questions, toutes propres au plan ---------- */
 function markup(){const s=state(),p=s.plan,g=p.goal,si=p.situation;
  const goalBlock=g.kind==='purchase'
   ?combobox('plan-search','Je veux acheter (cherche dans le site)','plan')+btn('Écrire un achat libre','data-b-plan-free="1"')+'<div id="plan-selection">'+(g.itemId?selectedCard({itemId:g.itemId,name:g.name}):'')+'<div class="calc-fields">'+field('plan.goal.name','Nom de mon achat',g.name,{type:'text',id:'plan-name'})+field('plan.goal.price',g.referencePrice!==null?'Ça coûte ($)':'Ça coûte, d’après ce que tu imagines ($)',g.price,{id:'plan-price',hint:g.referencePrice!==null?'Prix du site : '+money(g.referencePrice)+'. Tu peux écrire un autre prix.':'Le prix du jeu n’est pas encore connu : écris celui que tu imagines.'})+field('plan.goal.boostHourly','Une fois acheté, il me fera gagner en plus ($ par heure)',g.boostHourly,{id:'plan-boost',hint:'0 si c’est un achat plaisir. Compte seulement ce qu’il rapporte en plus.'})+'</div>'+(g.referencePrice!==null?btn('Remettre le prix du site','data-b-plan-price-reset="1"'):'')+'</div>'
   :g.kind==='amount'
   ?'<div class="calc-fields">'+field('plan.goal.target','Je veux avoir ($)',g.target,{id:'plan-target',hint:'Choisis juste en dessous ce que « avoir » veut dire pour toi.'})+select('plan.goal.meaning','« Avoir », pour moi, c’est',[['available','De l’argent disponible, en plus de ce que je garde de côté'],['held','De l’argent en tout, argent gardé de côté compris'],['cumulative','De l’argent gagné à partir de maintenant, sans compter ce que j’ai déjà']],g.meaning||'available')+'</div>'
   :'<div class="calc-fields">'+field('plan.goal.name','Ce que je veux débloquer',g.name,{type:'text',id:'plan-name',hint:'Une voiture, une arme, un lieu… tout ce qui se gagne avec l’expérience.'})+field('plan.goal.unitLabel','Ça se gagne en',g.unitLabel,{type:'text',id:'plan-units-label',hint:'points d’XP, niveaux, réputation… le mot que tu veux.'})+field('plan.goal.targetUnits','Il faut atteindre ('+esc(g.unitLabel||'points')+')',g.targetUnits,{id:'plan-units-target'})+field('plan.goal.currentUnits','J’en ai déjà ('+esc(g.unitLabel||'points')+')',g.currentUnits,{id:'plan-units-current'})+field('plan.goal.alsoPrice','Et il coûte aussi, une fois débloqué ($)',g.alsoPrice,{id:'plan-also-price',hint:'Laisse 0 s’il est gratuit une fois débloqué.'})+'</div><p class="calc-note">Le jeu n’a pas encore dit comment se gagne l’expérience. Écris ce que tu sais, ou ce que tu imagines : le plan compte avec tes chiffres.</p>';
  const missionSources=[...s.activities.map(a=>['mine:'+a.id,a.name+' · mes activités']),...sourceActivities.map(a=>['site:'+a.id,a.name+' · du site'])];
  const missionsBlock=p.source==='missions'
   ?'<div id="plan-missions">'+(p.missions.length?p.missions.map((m,i)=>missionCard(s,m,i)).join(''):'<p class="calc-empty">Aucune mission pour l’instant. Ajoute celles que tu peux faire : le plan te dira lesquelles enchaîner et dans quel ordre.</p>')+'</div><div class="b-plan-add">'+btn('Ajouter une mission','data-b-plan-m-add="1"',true)+(missionSources.length?'<label class="calc-label" for="plan-m-source">Ou reprendre une mission déjà écrite</label><div class="b-plan-add-row"><select id="plan-m-source">'+missionSources.map(([k,l])=>'<option value="'+esc(k)+'">'+esc(l)+'</option>').join('')+'</select>'+btn('Ajouter cette mission','data-b-plan-m-import="1"')+'</div>':'')+'</div><p class="calc-note">Ce sont des copies : changer une mission ici ne change rien dans Mes activités, et inversement.</p>'
   :'<div class="calc-fields">'+field('plan.situation.hourly','Je gagne à peu près ($ par heure de jeu)',si.hourly,{id:'plan-hourly',hint:'Ce qu’il te reste une fois tes frais payés. Ton chiffre à toi.'})+(g.kind==='unlock'?field('plan.situation.unitsHourly','Je gagne à peu près ('+esc(g.unitLabel||'points')+' par heure)',si.unitsHourly,{id:'plan-units-hourly'}):'')+'</div>';
  const prereqBlock='<div id="plan-prereqs">'+(p.prerequisites.length?p.prerequisites.map((a,i)=>prereqCard(s,a,i)).join(''):'<p class="calc-empty">Aucun achat avant ton but. Ajoute ce qu’il te faut acheter d’abord (équipement, véhicule, local…), s’il y en a.</p>')+'</div>'+combobox('plan-prereq-search','Ajouter un achat d’avant (cherche dans le site)','plan-prereq')+btn('Ajouter un achat libre','data-b-plan-p-add="1"')+'<div class="calc-fields">'+select('plan.strategy','Dans quel ordre les acheter ?',Object.entries(STRATEGY_LABEL),p.strategy)+field('plan.situation.upkeepPerSession','Je dépense par partie ($) : consommables, munitions…',si.upkeepPerSession,{id:'plan-upkeep',hint:'Enlevé de ce que tu gagnes. Mets 0 si tu ne sais pas.'})+'</div>';
  const form='<div class="b-plan-import"><p class="calc-note">Le business plan a ses propres cases : rien n’est pris automatiquement dans les huit calculs. Si tu veux repartir de tes chiffres de Mes calculs, clique ici, puis change ce que tu veux.</p>'+btn('Reprendre mes chiffres de Mes calculs','data-b-plan-import-calcs="1"')+'</div><div class="calc-fields calc-steps">'
   +step(1,'Quel est ton but ?',select('plan.goal.kind','Mon but',Object.entries(KIND_LABEL),g.kind)+goalBlock,'Le but décide de tout le reste : un achat a un prix, une somme se gagne petit à petit, un déblocage se gagne avec des points.')
   +step(2,'Où en es-tu ?','<div class="calc-fields">'+field('plan.situation.capital','J’ai déjà ($)',si.capital,{id:'plan-capital'})+field('plan.situation.reserve','Argent que je garde de côté ($)',si.reserve,{id:'plan-reserve'})+field('plan.situation.dailyMinutes','Une partie dure (minutes)',si.dailyMinutes,{id:'plan-daily',min:1,max:1440,hint:'Le programme se fait partie par partie. Laisse vide si tu ne comptes pas en parties : tu auras un parcours en temps de jeu, sans calendrier.'})+field('plan.situation.daysPerWeek','Je joue combien de jours par semaine ?',si.daysPerWeek,{id:'plan-days',min:1,max:7,integer:true})+field('plan.situation.players','Nous jouons à (joueurs)',si.players??1,{id:'plan-players',min:1,max:100,integer:true,hint:'Une mission qui demande plus de joueurs que ton groupe est écartée du plan, et c’est dit.'})+'</div>','Avec ce que tu as et la durée de tes parties, le plan compte en parties, puis en jours.')
   +step(3,'Comment tu gagnes ton argent ?',select('plan.source','Je gagne mon argent',[['missions','Avec mes missions : le plan me dit lesquelles faire et dans quel ordre'],['hourly','Petit à petit : je gagne à peu près un chiffre par heure']],p.source)+missionsBlock,'Avec tes missions, le plan choisit à chaque partie celles qui rapportent le plus dans le temps que tu as. C’est le chemin le plus rapide qu’il trouve.')
   +step(4,'Avant ton but',prereqBlock,'Un achat qui débloque une mission ou qui rapporte accélère la suite ; le plan le place au bon moment, dès que tu peux le payer.')
   +step(5,'Ce qui compte pour toi','<div class="calc-fields">'+select('plan.priority','Je préfère',[['balanced','Un bon équilibre : je garde mon argent de côté'],['fast','Le plus vite possible : je peux toucher à mon argent de côté'],['safe','La sécurité : je ne touche jamais à mon argent de côté'],['cheap','Le moins coûteux sur tout le parcours : je garde mon argent de côté']],p.priority)+field('plan.deadlineDays','Je veux y arriver en (jours, si tu veux)',p.deadlineDays,{id:'plan-deadline',min:1,max:36500,integer:true,hint:'Laisse vide si tu n’as pas de date. On te dira si c’est faisable avec ton rythme.'})+'<div class="b-expert">'+field('plan.maxRepeat','Même mission à la suite, au maximum',p.maxRepeat,{id:'plan-max-repeat',min:1,max:256,integer:true})+'</div></div>','Ce que tu préfères décide de l’ordre des achats, et si ton argent de côté peut servir.')
   +'</div><p class="calc-note">Le plan se refait tout seul à chaque chiffre changé. Enregistre-le pour le retrouver avec sa fiche complète, imprime-le, ou partage le lien.</p>';
  return '<section class="calc-panel" id="panel-plan" role="tabpanel" aria-labelledby="tab-plan" hidden><div class="calc-grid"><div class="calc-card"><p class="calc-kicker">MON BUSINESS PLAN</p><h3>Dis-moi ton but, je te fais le programme.</h3><p class="calc-card-desc">Réponds aux cinq questions : le plan te dit quoi faire en premier, en deuxième, en troisième, partie après partie, avec le chemin le plus rapide vers ton but, et ce que tu fais si ça ne se passe pas comme prévu.</p>'+form+'</div><div class="calc-card calc-result" id="plan-results"></div></div><div id="plan-report"></div><div class="b-stage-actions"><span class="b-expert-only">'+btn('Enregistrer mon plan (avec sa fiche)','data-b-save="plan"',true)+btn('Imprimer mon plan','data-b-print="1"')+'</span>'+btn('Télécharger mon plan en texte (à lire ou à envoyer)','data-b-plan-export="1"')+'</div><p class="calc-note">Pour garder ce plan avec sa fiche : « ☆ Enregistrer le plan », en haut ou en bas de l’atelier. Tu le retrouves ensuite dans « Mes calculs ».</p><div class="b-expert calc-card calc-subsection" id="expert-plan"></div></section>';}
 /* Revue de conformité (v7.53) : prévu, commencé et réalisé sont trois états distincts. « Commencé » se voit partout mais
    ne crédite rien (ni argent ni déblocage) ; seul « fait » (ou un relevé réel) compte dans le calcul. */
 function stateRadios(kind,i,st,labels){const name='plan-'+kind+'-state-'+i;return '<fieldset class="b-plan-state"><legend>Où j’en suis</legend>'+[['planned',labels[0]],['started',labels[1]],['done',labels[2]]].map(([v,l])=>'<label class="calc-check"><input type="radio" name="'+name+'" value="'+v+'" data-b-plan-'+kind+'-state="'+i+'" '+(st===v?'checked':'')+'> '+esc(l)+'</label>').join('')+'</fieldset>';}
 const mState=m=>m.once&&m.done?'done':m.started?'started':'planned',pState=a=>a.owned?'done':a.started?'started':'planned';
 function planStatus(s,r){const p=s.plan,once=p.missions.filter(m=>m.once),buy=p.prerequisites;const n={planned:0,started:0,done:0};once.forEach(m=>n[mState(m)]++);buy.forEach(a=>n[pState(a)]++);
  const real=p.log.length,label=real||n.started||n.done?(r&&r.valid&&(r.continuous?r.totalMinutes===0:r.totalSessions===0)&&real?'Réalisé':'Commencé'):'Prévu';
  const steps=n.planned+n.started+n.done,detail=steps?'Étapes : '+plural(n.planned,' prévue',' prévues')+', '+plural(n.started,' commencée',' commencées')+(n.started?(lkPluriel(n.started)?' (pas encore comptées)':' (pas encore comptée)'):'')+', '+plural(n.done,' faite',' faites')+(real?' · '+plural(real,' partie',' parties')+(lkPluriel(real)?' relevées':' relevée')+' pour de vrai':'')+'.':real?plural(real,' partie',' parties')+(lkPluriel(real)?' relevées':' relevée')+' pour de vrai.':'Rien de commencé : c’est une prévision. Après une partie, « écrire ce que j’ai vraiment » la fait passer à « commencé ».';
  return '<p class="b-plan-status" data-plan-status="'+label.toLowerCase()+'"><span class="calc-tag">'+esc(label.toUpperCase())+'</span> '+esc(detail)+'</p>';}
 function missionSummary(s,m,i){const p=s.plan,r=E.activity({...m,units:m.units});return '<span>'+esc(m.name||'Mission '+(i+1))+'<i class="b-plan-mission-edit">modifier</i></span><small>'+(m.once&&m.done?'faite · ':m.started?'commencée · ':'')+(r.valid?money(r.net)+' par mission · '+money(r.hourly)+' par heure, attente comprise':'chiffres à compléter : '+esc(r.reason||''))+(m.requires.length?' · après '+esc(m.requires.map(id=>p.prerequisites.find(x=>x.id===id)?.name||id).join(', ')):'')+(m.owned?' · achat de départ déjà payé':'')+(m.once?(m.done?' · déjà faite':' · une seule fois'):'')+((m.requiresMissions||[]).length?' · après la mission '+esc(m.requiresMissions.map(id=>p.missions.find(x=>x.id===id)?.name||id).join(', ')):'')+'</small>';}
 function prereqHead(s,a,i){return '<span class="calc-tag">'+(i+1)+'</span><strong>'+esc(a.name)+'</strong><small>'+(a.owned?'déjà possédé':a.price===null?'prix à écrire':money(a.price))+(a.boostHourly>0?' · +'+money(a.boostHourly)+'/h ensuite':'')+(a.minutes>0?' · '+hours(a.minutes/60)+' pour l’obtenir':'')+((s.plan.locked||[]).includes(a.id)?' · indispensable':'')+'</small>';}
 function syncForm(s){s.plan.missions.forEach((m,i)=>{const n=document.querySelector('[data-b-plan-m-summary="'+i+'"]');if(n){const h=missionSummary(s,m,i);if(n.innerHTML!==h)n.innerHTML=h;}});s.plan.prerequisites.forEach((a,i)=>{const n=document.querySelector('[data-b-plan-p-head="'+i+'"]');if(n){const h=prereqHead(s,a,i);if(n.innerHTML!==h)n.innerHTML=h;}});}
 function missionCard(s,m,i){const p=s.plan,g=p.goal,r=E.activity({...m,units:m.units}),pre='plan.missions.'+i+'.';
  return '<details class="b-plan-mission" '+(i===p.missions.length-1&&p.missions.length<=2?'open':'')+'><summary data-b-plan-m-summary="'+i+'">'+missionSummary(s,m,i)+'</summary><div class="calc-fields">'+field(pre+'name','Nom de la mission',m.name,{type:'text',id:'plan-m-'+i+'-name'})+field(pre+'reward','Récompense ($)',m.reward,{id:'plan-m-'+i+'-reward'})+field(pre+'duration','Durée (min)',m.duration,{id:'plan-m-'+i+'-duration',min:1,max:1e6})+field(pre+'cost','Frais à chaque fois ($)',m.cost,{id:'plan-m-'+i+'-cost'})+field(pre+'prep','Préparation (min)',m.prep,{id:'plan-m-'+i+'-prep',max:1e6})+field(pre+'cooldown','Attente avant de recommencer (min)',m.cooldown,{id:'plan-m-'+i+'-cooldown',max:1e6})+field(pre+'share','Ma part (%)',m.share,{id:'plan-m-'+i+'-share',max:100})+field(pre+'players','Se joue à (joueurs)',m.players??1,{id:'plan-m-'+i+'-players',min:1,max:100,integer:true})+field(pre+'investment','À acheter une seule fois avant de commencer ($)',m.investment,{id:'plan-m-'+i+'-investment'})+(g.kind==='unlock'?field(pre+'units',esc(g.unitLabel||'Points')+' gagnés par mission',m.units,{id:'plan-m-'+i+'-units'}):'')+'</div><label class="calc-check"><input type="checkbox" data-b-plan-m-owned="'+i+'" '+(m.owned?'checked':'')+'> J’ai déjà payé ce qu’il faut pour commencer</label><label class="calc-check"><input type="checkbox" data-b-plan-m-once="'+i+'" '+(m.once?'checked':'')+'> Mission à faire une seule fois (elle débloque la suite)</label>'+(m.once?stateRadios('m',i,mState(m),['Prévue','Commencée (pas encore comptée)','Déjà faite']):'')+(p.prerequisites.length?'<fieldset class="b-plan-requires"><legend>Il faut d’abord avoir acheté :</legend>'+p.prerequisites.map(a=>'<label class="calc-check"><input type="checkbox" data-b-plan-m-req="'+i+'|'+esc(a.id)+'" '+(m.requires.includes(a.id)?'checked':'')+'> '+esc(a.name)+'</label>').join('')+'</fieldset>':'')+(p.missions.length>1?'<fieldset class="b-plan-requires"><legend>Il faut d’abord avoir fait la mission :</legend>'+p.missions.filter(o=>o.id!==m.id).map(o=>'<label class="calc-check"><input type="checkbox" data-b-plan-m-reqm="'+i+'|'+esc(o.id)+'" '+((m.requiresMissions||[]).includes(o.id)?'checked':'')+'> '+esc(o.name)+(o.once?' (une seule fois)':'')+'</label>').join('')+'</fieldset>':'')+'<div class="b-plan-card-actions">'+btn('Retirer cette mission','data-b-plan-m-remove="'+i+'"')+'</div></details>';}
 function prereqCard(s,a,i){const pre='plan.prerequisites.'+i+'.',item=itemFor({itemId:a.itemId});
  return '<article class="b-plan-prereq" data-b-plan-prereq="'+esc(a.id)+'"><div class="b-plan-prereq-head" data-b-plan-p-head="'+i+'">'+prereqHead(s,a,i)+'</div><div class="calc-fields">'+field(pre+'name','Nom',a.name,{type:'text',id:'plan-p-'+i+'-name'})+field(pre+'price',a.referencePrice!==null?'Prix ($)':'Prix, d’après ce que tu imagines ($)',a.price,{id:'plan-p-'+i+'-price',hint:a.referencePrice!==null?'Prix du site : '+money(a.referencePrice)+'.':(item?'':'')})+field(pre+'boostHourly','Il me fera gagner en plus ($ par heure)',a.boostHourly,{id:'plan-p-'+i+'-boost',hint:'Seulement ce que cet achat rapporte en plus. 0 sinon.'})+field(pre+'minutes','Temps pour l’obtenir (min)',a.minutes,{id:'plan-p-'+i+'-minutes',max:1e6,hint:'Trajet, mission d’achat… Laisse vide si c’est immédiat.'})+field(pre+'usagePerSession','Ce qu’il coûte à chaque partie ($)',a.usagePerSession,{id:'plan-p-'+i+'-usage',hint:'Carburant, entretien… ton chiffre. Vide = rien de compté (aucun coût confirmé dans GTA VI).'})+'</div>'+stateRadios('p',i,pState(a),['Prévu','Commencé (pas encore à moi)','Déjà à moi'])+'<label class="calc-check"><input type="checkbox" data-b-plan-p-lock="'+esc(a.id)+'" '+((s.plan.locked||[]).includes(a.id)?'checked':'')+'> Indispensable : aucune façon de faire ne le retire du plan</label>'+prereqRequires(s,a,i)+'<div class="b-plan-card-actions">'+btn('↑','data-b-plan-p-up="'+i+'" aria-label="Monter '+esc(a.name)+'" '+(i===0?'disabled':''))+btn('↓','data-b-plan-p-down="'+i+'" aria-label="Descendre '+esc(a.name)+'" '+(i===s.plan.prerequisites.length-1?'disabled':''))+btn('Retirer','data-b-plan-p-remove="'+i+'"')+'</div></article>';}
 /* ---------- Phases : « en premier, en deuxième… », le cœur du programme ---------- */
 function stepsText(steps){return steps.map((st,i)=>(i?(i===steps.length-1?' puis ':', '):'')+'« '+esc(st.name)+' » ×'+st.runs).join('');}
 /* correctif lot 2 (revue 7) : une partie prise par l’obtention d’un achat le dit (morceaux lus du moteur : se.acquisitions / ph.acquisitions) */
 /* même chose en texte simple (tableaux, résumé, fiche) : obtention, missions, ou gain par heure seul */
 function whatText(x){const a=(x.acquisitions||[]).map(q=>'obtenir « '+q.name+' » ('+hours(q.minutes/60)+')'),st=(x.steps||[]).map(t=>t.name+' ×'+t.runs);return a.concat(st.length?st:a.length&&!(((x.hourlyPart||0)+(x.boostPart||0))>0)?[]:['ton gain par heure']).join(', ');}
 function acqText(list){return (list||[]).map(a=>'« '+esc(a.name)+' » ('+hours(a.minutes/60)+')').join(', ');}
 function phaseCards(s,r,base){const p=s.plan,g=p.goal,dpw=r.input.daysPerWeek,D=sessionLabel(s),byName=n=>r.purchases.find(x=>x.name===n),cards=[];
  if(r.totalSessions===0)return '<ol class="b-timeline"><li class="b-phase is-goal"><span class="b-phase-n">✓</span><div><p class="b-phase-k">Dès maintenant</p><h4>'+esc(g.kind==='purchase'?'Achète '+goalShort(s):g.kind==='unlock'?'Tu peux déjà débloquer '+goalShort(s):'Tu as déjà '+goalShort(s))+'</h4><p>'+esc(g.kind==='purchase'?'Il te restera '+money(r.finalCash-(r.input.goalPrice||0))+(r.input.reserve?', dont '+money(r.input.reserve)+' gardés de côté':'')+'.':'Choisis un but plus grand, ou un nouvel achat.')+'</p></div></li></ol>';
  r.phases.forEach((ph,i)=>{const range=ph.count===1?'Partie '+ph.from:'Parties '+ph.from+' à '+ph.to+' · '+plural(ph.count,' partie',' parties');
   const acq=acqText(ph.acquisitions),free=r.input.sessionMinutes-(ph.acquisitionMinutes||0),freeGain=(ph.hourlyPart||0)+(ph.boostPart||0);
   const doText=acq?'Obtiens '+acq+(ph.steps.length?', puis fais '+stepsText(ph.steps):free>1e-9&&freeGain>0?', puis joue '+hours(free/60)+' : tu gagnes à peu près '+money(freeGain)+(r.input.hourly>0?' avec ton chiffre par heure':''):'')+(ph.count>1?' à chaque partie':'')+'.':ph.steps.length?'Fais '+stepsText(ph.steps)+(ph.count>1?' à chaque partie':'')+'.':'Joue '+D+' : tu gagnes à peu près '+money(ph.gain)+' par partie'+(r.input.hourly>0?' avec ton chiffre par heure':'')+'.';
   /* correctif lot 2 (revue 7) : parts lues du moteur (gain par heure et achats qui rapportent, hors temps d’obtention ; dépenses de la partie, coût d’usage compris), plus recalculées ici */
   const boosters=ph.boosters||[],extras=[];
   if((ph.boostPart||0)>0&&boosters.length)extras.push('+'+money(ph.boostPart)+' par partie grâce à '+boosters.map(x=>'« '+esc(x.name)+' »').join(', '));if((ph.hourlyPart||0)>0&&ph.steps.length)extras.push('+'+money(ph.hourlyPart)+' avec ton gain par heure');if((ph.upkeep||0)>0)extras.push('−'+money(ph.upkeep)+' de dépenses par partie');
   const extra=extras.join(' · ');
   const figures=[['Par partie',signed(ph.gain)+(g.kind==='unlock'&&ph.unitsGain>0?' · +'+units(s,ph.unitsGain):'')],['Tu passes de',money(ph.cashBefore)+' à '+money(ph.cashAfter)],['Quand',ph.from===ph.to?'jour '+dayOf(ph.from,dpw)+' (vers le '+planDate(dayOf(ph.from,dpw),base)+')':'du jour '+dayOf(ph.from,dpw)+' au jour '+dayOf(ph.to,dpw)+' (vers le '+planDate(dayOf(ph.to,dpw),base)+')']];
   const after=ph.purchasesAfter.length?'<p class="b-phase-after"><b>Après la partie '+ph.to+' :</b> achète '+ph.purchasesAfter.map(n=>{const x=byName(n);return '« '+esc(n)+' »'+(x?' ('+money(x.price)+(x.boostHourly>0?', +'+money(x.boostHourly)+'/h ensuite':'')+')':'');}).join(', ')+'.</p>':'';
   cards.push('<li class="b-phase"><span class="b-phase-n">'+(i+1)+'</span><div><p class="b-phase-k">'+esc(ORDINALS[i]||'Étape '+(i+1))+' · '+esc(range)+'</p><h4>'+doText+'</h4>'+(extra?'<p class="calc-note">Compté aussi dans le total : '+extra+'.</p>':'')+'<div class="b-tiles">'+figures.map(([l,v])=>'<span><small>'+esc(l)+'</small><b>'+v+'</b></span>').join('')+'</div>'+after+'</div></li>');});
  const N=r.totalSessions,dayN=dayOf(N,dpw);
  cards.push('<li class="b-phase is-goal"><span class="b-phase-n">★</span><div><p class="b-phase-k">Objectif atteint · après la partie '+N+' · jour '+dayN+' (vers le '+planDate(dayN,base)+')</p><h4>'+esc(g.kind==='purchase'?'Achète '+goalShort(s)+' ('+money(r.input.goalPrice)+')':g.kind==='unlock'?'Tu débloques '+goalShort(s)+(r.input.goalPrice>0?' et tu le paies ('+money(r.input.goalPrice)+')':''):g.meaning==='held'?'Tu as '+money(g.target)+' en tout':g.meaning==='cumulative'?'Tu as gagné '+money(g.target)+' depuis le départ':'Tu as '+money(g.target)+' en poche')+'</h4><p>'+esc((g.kind==='purchase'||(g.kind==='unlock'&&r.input.goalPrice>0)?'Il te reste '+money(r.finalCash-(r.input.goalPrice||0))+(r.input.reserve?', dont '+money(r.input.reserve)+' gardés de côté':'')+'.':'Tu gardes '+money(r.input.reserve)+' de côté.')+(g.kind==='purchase'&&g.boostHourly>0?' Ensuite, cet achat te rapporte '+money(g.boostHourly)+(Number.isFinite(r.goalPaybackHours)?' de plus par heure : remboursé après '+hours(r.goalPaybackHours)+' de jeu.':' de plus par heure.')/* lot 2 (C6) : remboursement lu du moteur seulement ; sans délai fini (prix 0), aucun remboursement annoncé */:'')+(g.kind==='purchase'&&!(g.boostHourly>0)?' C’est un achat plaisir : il ne se rembourse pas tout seul, et ce n’est pas grave.':''))+'</p></div></li>');
  return '<ol class="b-timeline">'+cards.join('')+'</ol>';}
 function programSummary(r){if(!r||!r.valid)return '';if(r.continuous){const l=(r.route||[]).slice(0,8).map(x=>x.type==='acquire'?'achète '+x.name:x.type==='unlock'?x.name+' (une fois)':x.name+' ×'+x.runs);return l.join(' → ')+((r.route||[]).length>8?' → …':'');}return r.phases.map(ph=>(ph.count===1?'Partie '+ph.from:'Parties '+ph.from+'–'+ph.to)+' : '+whatText(ph)+(ph.purchasesAfter.length?' → puis achète '+ph.purchasesAfter.join(', '):'')).join(' · ');}
 function prereqRequires(s,a,i){const others=[...s.plan.prerequisites.filter(o=>o.id!==a.id).map(o=>[o.id,o.name]),...s.plan.missions.filter(m=>m.once).map(m=>[m.id,'la mission « '+m.name+' »'])];
  return others.length?'<fieldset class="b-plan-requires"><legend>Il faut d’abord avoir :</legend>'+others.map(([id,n])=>'<label class="calc-check"><input type="checkbox" data-b-plan-p-req="'+i+'|'+esc(id)+'" '+((a.requires||[]).includes(id)?'checked':'')+'> '+esc(n)+'</label>').join('')+'</fieldset>':'';}
 /* ---------- v7.49 : parcours sans durée de partie, chaîne des étapes, point bas, variantes gardées ---------- */
 const isFlow=r=>!!(r&&r.continuous);
 const timeText=r=>hours((r.totalMinutes||0)/60)+' de jeu';
 function goalStep(s){const g=s.plan.goal;return g.kind==='purchase'?'Acheter '+goalShort(s):g.kind==='unlock'?'Débloquer '+goalShort(s):'Avoir '+goalShort(s);}
 function routeSteps(s,r,o={}){const p=s.plan,max=o.max||40,steps=[{type:'start',name:'Départ',detail:money(r.startCash)+' en poche'+(r.input.reserve?' · '+money(r.input.reserve)+' gardés de côté':''),cash:r.startCash}];
  p.prerequisites.filter(a=>a.owned).forEach(a=>steps.push({type:'start',name:a.name,detail:'Déjà possédé'}));
  p.missions.filter(m=>m.once&&m.done).forEach(m=>steps.push({type:'start',name:m.name,detail:'Déjà faite'}));
  p.prerequisites.filter(a=>!a.owned&&a.started).concat(p.missions.filter(m=>!(m.once&&m.done)&&m.started)).forEach(x=>steps.push({type:'start',name:x.name,detail:'Commencé : pas encore compté (coche « fait » quand c’est fini)'}));
  const list=(r.route||[]).filter(x=>o.all||x.type!=='run');
  list.slice(0,max).forEach(x=>{const when=isFlow(r)?(x.start>0?'après '+hours(x.start/60)+' de jeu':'dès le départ'):x.where==='before'?'avant ta première partie':x.where==='after'?'après la partie '+x.session:'pendant la partie '+x.session;
   /* v7.54 : un achat d’avant qui vient d’une fiche du site est cliquable (fiche) ; sinon, aucun lien inventé. */
   if(x.type==='acquire'){const pr=p.prerequisites.find(a=>a.id===x.id||a.name===x.name),item=pr&&pr.itemId?itemFor({itemId:pr.itemId}):null;steps.push({type:'acquire',name:x.name,url:item&&item.url?item.url:undefined,detail:'−'+money(x.spend)+' · '+when+(x.minutes>0?' · '+hours(x.minutes/60)+' pour l’obtenir':''),cash:x.cashAfter});}
   else if(x.type==='unlock')steps.push({type:'unlock',name:x.name,detail:['une seule fois',x.spend?'−'+money(x.spend):'',x.receive?'+'+money(x.receive):'',when].filter(Boolean).join(' · '),cash:x.cashAfter});
   else steps.push({type:'run',name:x.name+(x.runs>1?' ×'+x.runs:''),detail:'+'+money(x.receive-x.spend)+' net · '+hours(x.minutes/60),cash:x.cashAfter});});
  /* correctif lot 2 (REG4-2) : la ligne de suite n’est pas une étape à faire : étiquette « … » au lieu de « Faire » (chain lit st.label avant la nature). */
  if(list.length>max)steps.push({type:'run',label:'…',name:'… et '+plural(list.length-max,' étape',' étapes')+' de plus',detail:'Toutes les étapes sont dans « Étape par étape », en mode Expert.'});
  steps.push({type:'goal',name:goalStep(s),detail:isFlow(r)?'après '+timeText(r):r.totalSessions===0?'dès maintenant':'après la partie '+r.totalSessions,cash:r.finalCash});
  return steps;}
 function lowText(r){const L=r&&r.lowPoint;if(!L||!Number.isFinite(L.cash)||L.cash>=r.startCash-1e-9)return '';return ' Au plus bas : '+money(L.cash)+(L.at?' — '+L.at.charAt(0).toLowerCase()+L.at.slice(1):'')+(r.input.reserve>0&&L.cash>=r.input.reserve-1e-9?', jamais sous l’argent gardé de côté.':r.input.reserve===0&&L.cash<((r.keptReserve??0))?', sous ce que tu voulais garder de côté.':'.');}
 function lowLine(r){const t=lowText(r);return t?'<p class="b-lowpoint">'+esc(t.trim())+'</p>':'';}
 function routeBlock(s,r){if(!(r.route||[]).some(x=>x.type==='acquire'||x.type==='unlock'))return '';return visual.chain(routeSteps(s,r),{title:'Le parcours, dans l’ordre',question:'Ce que tu achètes ou débloques, et quand : chaque étape ouvre la suivante.',note:'Un achat se paie seulement quand ce qu’il demande est fait et que l’argent le permet, sans toucher à l’argent gardé de côté.'});}
 function flowNext(s,r){const first=(r.route||[]).slice(0,4);if(!first.length)return '';return '<div class="calc-next-action"><strong>Pour commencer</strong><ol class="b-next-steps">'+first.map(x=>'<li>'+(x.type==='acquire'?'Achète « '+esc(x.name)+' » <span>−'+money(x.spend)+'</span>':x.type==='unlock'?'Fais « '+esc(x.name)+' » (une seule fois) <span>'+(x.receive-x.spend>=0?'+':'−')+money(Math.abs(x.receive-x.spend))+'</span>':'« '+esc(x.name)+' » ×'+x.runs+' <span>+'+money(x.receive-x.spend)+'</span>')+'</li>').join('')+'</ol>'+btn('Après avoir joué, écrire ce que j’ai vraiment','data-b-focus="plan-actual"')+'</div>';}
 function incompleteBlock(s){const x=analysisOf?analysisOf('plan',s):null;if(!x||!x.incomplete||!x.incomplete.length)return '';const p=s.plan;
  const steps=p.prerequisites.map(a=>({type:a.owned?'start':a.price===null?'missing':'acquire',name:a.name,detail:a.owned?'Déjà possédé':a.price===null?'Prix à venir : écris le prix que tu imagines pour compléter le parcours':money(a.price)}));steps.push({type:'goal',label:'Ton but',name:goalStep(s),detail:'Calculé dès que le parcours est complet'});
  return visual.chain(steps,{title:'Parcours à compléter',question:'Un prix inconnu n’est jamais compté comme gratuit : écris-le pour avoir le plan.'})+'<div class="b-plan-card-actions">'+x.incomplete.map(z=>btn('Écrire le prix de « '+z.name+' »','data-b-focus="'+esc(z.field)+'"')).join('')+'</div>';}
 const VARIANT_KEYS=['goal','situation','source','missions','prerequisites','priority','strategy','maxRepeat','deadlineDays'];
 function variantOf(s){const p=s.plan,v={id:'v-'+Date.now().toString(36)+'-'+(p.variants||[]).length,label:(goalName(s)+' · '+(p.source==='missions'?plural(p.missions.length,' mission',' missions'):money(p.situation.hourly)+'/h')).slice(0,120),at:new Date().toISOString().slice(0,10)};VARIANT_KEYS.forEach(k=>{v[k]=B.copy(p[k]);});return v;}
 function variantState(s,v){const c=B.copy(s);VARIANT_KEYS.forEach(k=>{if(v[k]!==undefined)c.plan[k]=B.copy(v[k]);});c.plan.variant='auto';return c;}
 function variantResult(s,v){try{return B.evaluate('plan',variantState(s,v));}catch(e){return {valid:false,reason:e.message};}}
 function variantCell(r){return !r||!r.valid?'À compléter':r.continuous?timeText(r):(r.totalSessions===0?'Déjà possible':plural(r.totalSessions,' partie',' parties')+' · '+plural(r.days,' jour',' jours'));}
 function savedVariants(s,r){const list=s.plan.variants||[];
  let html='<p class="calc-note">Une variante garde une copie complète du plan (but, situation, missions, achats d’avant). Rien n’est écrasé : reprendre une variante range le plan actuel à sa place.</p><div class="b-plan-card-actions">'+btn('Garder ce plan comme variante','data-b-plan-vsave="1"'+(list.length>=5?' disabled':''))+'</div>';
  if(list.length)html+=table([['Variante','Gardée le','Résultat','Argent à la fin'],['Plan actuel','—',variantCell(r),r&&r.valid?money(r.finalCash):'—'],...list.map(v=>{const x=variantResult(s,v);return [v.label,v.at||'—',variantCell(x),x&&x.valid?money(x.finalCash):'—'];})],'Le plan actuel et tes variantes, recalculés avec les mêmes règles',true)+'<ul class="b-variant-list">'+list.map(v=>'<li><span>'+esc(v.label)+'</span>'+btn('Reprendre cette variante','data-b-plan-vload="'+esc(v.id)+'"')+btn('Retirer','data-b-plan-vdel="'+esc(v.id)+'"')+'</li>').join('')+'</ul>';
  else html+='<p class="calc-empty">Aucune variante gardée. Garde celle-ci avant d’essayer autre chose : tu pourras comparer et revenir en arrière.</p>';
  if(list.length>=5)html+='<p class="calc-note">Cinq variantes au plus : retire-en une pour en garder une autre.</p>';
  return html;}
 /* ---------- Rendu principal ---------- */
 function render(){const s=state(),p=s.plan,g=p.goal,si=p.situation,r=B.evaluate('plan',s),mode=s.views.plan||'quick',expert=mode==='advanced',details=expert;syncForm(s);
  let head='<p class="calc-kicker">MA RÉPONSE</p><span class="calc-tag">AVEC TES CHIFFRES</span>';
  if(!r.valid){/* v7.54 : bloqué par l’argent de côté (aucun chiffre ne manque) : deux sorties proposées, sans parler d’une case à corriger. */
   if(r.blockedByReserve)head+=warning(r.reason)+'<p class="b-problem">'+btn('Choisir « Le plus vite possible »','data-b-focus="f-plan-priority"')+' '+btn('Changer l’argent gardé de côté','data-b-focus="plan-reserve"')+'</p>'+incompleteBlock(s)+'<div class="calc-next-action"><strong>Pour avoir ton programme</strong><p>Rien ne manque : c’est ton argent de côté qui bloque. Soit tu choisis « Le plus vite possible » dans « Je préfère » (le plan puise alors dans l’argent de côté, et il te le dit à chaque étape), soit tu baisses l’argent gardé de côté ou tu ajoutes une mission moins chère à lancer.</p></div>';
   else{const pb=problem(r.reason,'plan');/* correctif lot 2 (PER3-1) : refus du moteur sans case à corriger (but non atteint en 400 parties, J, dépenses par partie, attente > pause) : l’action dit de changer un chiffre, jamais « la case indiquée » ; titre fixe inchangé */
    head+=warning(r.reason)+pb+incompleteBlock(s)+'<div class="calc-next-action"><strong>Pour avoir ton programme</strong><p>'+(pb===''&&!B.planMissing(s)?'Change un chiffre du plan (but, durée des parties, missions ou achats d’avant) : il se recalcule tout seul, partie par partie.':'Il manque un chiffre ou un choix dans les questions du plan. Corrige la case indiquée : le plan se calcule tout seul, partie par partie.')+'</p></div>';}
   $('plan-results').innerHTML=head;$('plan-report').innerHTML='';$('expert-plan').innerHTML='';markSkips(s);return;}
  const D=sessionLabel(s),dpw=r.input.daysPerWeek,reached=r.continuous?r.totalMinutes===0:r.totalSessions===0,next=B.planNextSession(r),first=r.phases[0];
  /* correctif lot 2 (REG2-1) : « il te manque » compte les achats d’avant non possédés au départ (U, lus du moteur : rules.after et
     purchases[].price), comme la cible « tout ce qu’il faut avoir eu, achats d’avant compris » et comme le moteur qui les exige (C2) ;
     avant, 0 $ à gagner s’affichait à côté de 7 parties. */
  /* correctif lot 2 (PER5-1) : la somme est lue du moteur (needAtStart : même formule que « missing » sur l’état de départ, pour les trois sens du but)
     au lieu d’être recalculée ici ; la copie de la vue oubliait les achats d’avant pour « gagné à partir de maintenant » (« il te manque 10 000 $ » à côté de 8 parties). */
  const meaning=g.kind==='amount'?(g.meaning||'available'):'available',needMoney=Number.isFinite(r.needAtStart)?r.needAtStart:0,parts=[];if(g.kind==='unlock'&&r.startUnits<r.input.targetUnits)parts.push(units(s,r.input.targetUnits-r.startUnits));if(needMoney>0||g.kind!=='unlock')parts.push(money(needMoney));
  const missingText=', il te manque <b>'+parts.join(' et ')+'</b>';
  const how=p.source==='missions'?'avec tes missions':'en gagnant '+money(si.hourly)+' par heure',flow=isFlow(r);
  /* v7.54 : un but venu d’une fiche dont l’achat n’est pas confirmé garde sa condition jusque dans la réponse du plan (revue v7.53). */
  const goalItem=g.kind!=='amount'&&g.itemId?itemFor({itemId:g.itemId}):null,toConfirm=goalItem&&goalItem.purchasable!==true?' <i>Achat à confirmer dans GTA VI : le plan suppose qu’il s’achète.</i>':'';
  const phrase=reached?'Bonne nouvelle : tu peux déjà '+esc(g.kind==='purchase'?'acheter '+goalShort(s):g.kind==='unlock'?'débloquer '+goalShort(s):'avoir '+goalShort(s))+' avec ce que tu as, sans toucher à ce que tu gardes de côté.'+toConfirm
   :flow?'Pour {but}'.replace('{but}',esc(goalName(s)))+missingText+'. '+how.charAt(0).toUpperCase()+how.slice(1)+', tu y arrives en <b>'+timeText(r)+'</b>, étape après étape. Sans durée de partie, il n’y a pas de calendrier : écris-la pour avoir tes parties et tes jours.'+toConfirm
   :'Pour {but}'.replace('{but}',esc(goalName(s)))+missingText+'. '+how.charAt(0).toUpperCase()+how.slice(1)+', tu y arrives en <b>'+plural(r.totalSessions,' partie',' parties')+'</b> de '+D+', soit <b>'+plural(r.days,' jour',' jours')+'</b> (vers le '+planDate(r.days)+').'+(first&&first.steps.length?' En premier : '+stepsText(first.steps)+'.':'')+toConfirm;
  head+='<p class="b-answer calc-answer" data-short="'+esc(reached?'C’est bon !':flow?timeText(r):plural(r.totalSessions,' partie',' parties')+' · '+plural(r.days,' jour',' jours'))+'">'+phrase+'</p>'+stats((()=>{const fin=g.kind==='purchase'&&Number.isFinite(r.input.goalPrice)?['Il te restera, but acheté',money(r.finalCash-r.input.goalPrice)]:['Tu auras à la fin',money(r.finalCash)];return flow?[['Temps de jeu',hours(r.totalMinutes/60)],['Étapes',String((r.route||[]).length)],fin]:[['Parties de '+D,String(r.totalSessions)],['Jours',String(r.days)],fin];})())+lowLine(r);
  if(g.kind==='unlock'&&r.input.targetUnits>0)head+=visual.progress('plan-progress',esc(g.unitLabel||'Points')+' déjà gagnés',Math.min(r.startUnits,r.input.targetUnits),r.input.targetUnits,'Départ : '+units(s,r.startUnits)+'. Cible : '+units(s,r.input.targetUnits)+'. 100 % = débloqué.');
  else if(meaning==='cumulative')head+=visual.progress('plan-progress','Déjà gagné à partir de maintenant',0,r.goalMoney,'Tu vises '+money(r.goalMoney)+' gagnés à partir de maintenant : ce que tu as déjà ne compte pas. 100 % = but atteint.');
  else{const need=r.goalMoney+(meaning==='held'?0:r.input.reserve)+r.purchases.filter(x=>!x.owned||x.atSession).reduce((a,x)=>a+(x.atSession?x.price:0),0);head+=visual.progress('plan-progress','Ce que tu as déjà',Math.min(r.startCash,need),need,'Départ : '+money(r.startCash)+'. Cible : '+money(need)+' (tout ce qu’il faut avoir eu, achats d’avant compris). 100 % = tu peux payer ton but.');}
  head+=planStatus(s,r);
  /* v7.52 (lot 5) : le plan choisi touche à l’argent mis de côté (seul chemin trouvé, ou « le plus vite » demandé) : c’est dit
     tout de suite, avec la raison et le point bas, jamais seulement dans le détail des stratégies. */
  {const kept=si.reserve??0;if(kept>0&&r.input.reserve<kept){const why=((r.strategies&&r.strategies.candidates)||[]).find(c=>c.id==='asIs');head+=warning('Ce plan touche à tes '+money(kept)+' gardés de côté'+(p.priority==='fast'?' : tu as demandé d’aller le plus vite.':p.strategy==='useReserve'?' : c’est l’ordre que tu as choisi.':(why&&!why.valid&&why.reason?'. En les gardant : '+why.reason:' : c’est le chemin le plus rapide trouvé.'))+(r.lowPoint&&Number.isFinite(r.lowPoint.cash)?' Au plus bas, tu auras '+money(r.lowPoint.cash)+'.':''));}}
  if(r.variant!=='auto')head+='<p class="b-variant-note"><span class="calc-tag">PLAN DE SECOURS</span> Tu suis « '+esc(variantLabel(s,r))+' ». '+btn('Revenir au meilleur plan','data-b-plan-variant="auto"')+'</p>';
  if(reached)head+='<div class="calc-next-action"><strong>Ta prochaine étape</strong><p>'+esc(g.kind==='purchase'?'Achète '+goalShort(s)+' quand tu veux : il te restera '+money(r.finalCash-(r.input.goalPrice||0))+'. Ensuite, choisis un nouveau but.':'Ton but est atteint. Choisis-en un plus grand, ou un achat.')+'</p></div>';
  else if(flow)head+=flowNext(s,r);
  else if(next)head+='<div class="calc-next-action"><strong>Ta prochaine partie ('+D+')</strong>'+((next.acquisitions||[]).length?'<p>'+esc('Commence par obtenir ')+acqText(next.acquisitions)+'.</p>':'')+(next.steps.length?'<ol class="b-next-steps">'+next.steps.map(st=>'<li>« '+esc(st.name)+' » ×'+st.runs+' <span>+'+money(st.net)+'</span></li>').join('')+'</ol>':(next.acquisitions||[]).length?(r.input.sessionMinutes-(next.acquisitionMinutes||0)>1e-9&&(next.hourlyPart||0)+(next.boostPart||0)>0?'<p>Puis joue '+hours((r.input.sessionMinutes-next.acquisitionMinutes)/60)+' : environ '+signed(next.gain)+'.</p>':''):'<p>Joue '+D+' : environ '+signed(next.gain)+'.</p>')+'<p>'+/* correctif lot 2 (PER2-1) : la partie part de l’argent qu’il reste après les achats d’avant-partie (cashBefore, comme le journal), et seuls les achats d’après-partie viennent « puis » ; avant, un solde qui n’existe à aucun instant du journal (argent de départ + gain) */(next.purchasesBefore&&next.purchasesBefore.length?'<b>Achète d’abord : '+esc(next.purchasesBefore.join(', '))+'</b> → il te reste '+money(next.cashBefore)+'. ':'')+esc('Tu passes de '+money(next.cashBefore)+' à '+money(next.cashAfter+next.purchasesAfterOnly.reduce((a,n)=>{const x=r.purchases.find(y=>y.name===n);return a+(x?x.price:0);},0))+'.')+(next.purchasesAfterOnly.length?' <b>Puis achète : '+esc(next.purchasesAfterOnly.join(', '))+'</b> → il te reste '+money(next.cashAfter)+'.':'')+(g.kind==='unlock'&&next.unitsGain>0?' +'+units(s,next.unitsGain)+'.':'')+'</p>'+btn('Après avoir joué, écrire ce que j’ai vraiment','data-b-focus="plan-actual"')+'</div>';
  /* v7.66 : case « Afficher plus de détails » rendue au mode Expert (elle ouvre ou ferme d’un geste tous les points du plan) */
  if(expert)head+='<label class="calc-check"><input type="checkbox" data-b-plan-details="1" '+(p.details?'checked':'')+'> Afficher plus de détails (partie par partie, et si, courbe, calendrier)</label>';
  if(explainBlock&&analysisOf)head+=explainBlock(analysisOf('plan',s),'plan');
  $('plan-results').innerHTML=head;markSkips(s);
  /* ---- Le document : des « gros points » repliables. La réponse est au-dessus ; ici, chaque point s'ouvre d'un geste. ---- */
  const obs=B.planObserved(s),deadline=B.planDeadline(s,r),curve=B.planCurve(r);
  let doc='<div class="calc-card calc-subsection b-doc"><div class="b-doc-head"><div><p class="calc-kicker">MON BUSINESS PLAN · '+esc(new Date().toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'}))+'</p><h3>'+esc(goalName(s).charAt(0).toUpperCase()+goalName(s).slice(1))+'</h3><p class="b-doc-meta">'+esc(reached?'Déjà possible avec ce que tu as.':(flow?timeText(r):plural(r.totalSessions,' partie',' parties')+' de '+D+' · '+plural(r.days,' jour',' jours'))+' · '+(p.source==='missions'?plural(p.missions.length,' mission',' missions')+' au choix':money(si.hourly)+' par heure')+(r.purchases.some(x=>!x.owned||x.atSession)?' · '+plural(r.purchases.filter(x=>x.atSession).length,' achat',' achats')+' d’avant':'')+' · tes chiffres, pas ceux du jeu')+'</p></div><div class="b-doc-tools">'+btn('Tout déplier','data-b-fold-all="open"')+btn('Tout replier','data-b-fold-all="close"')+'</div></div><p class="b-doc-hint">Appuie sur un point pour l’ouvrir. Les chiffres importants sont déjà dans chaque titre.</p>';
  let n=0;const section=(id,title,teaser,lead,body,tone)=>fold('plan-'+id,{n:++n,title,teaser,tone,body:()=>(lead?'<p class="b-doc-lead">'+lead+'</p>':'')+(typeof body==='function'?body():body)});
  /* 1. Programme */
  if(flow)doc+=section('program','Ton parcours, dans l’ordre',reached?'Déjà possible : rien à faire avant ton but':'<b>'+timeText(r)+'</b> · '+plural((r.route||[]).length,' étape',' étapes')+' · sans calendrier','Ce qu’il faut faire, dans l’ordre, sans pause entre deux parties. Écris la durée d’une partie pour avoir le programme partie par partie et tes dates.',()=>visual.chain(routeSteps(s,r,{all:true,max:24}),{title:'Le parcours, dans l’ordre',question:'Se lit de haut en bas : chaque étape ouvre la suivante.',note:'À chaque moment, on prend la mission qui rapporte le plus par minute parmi celles possibles ; un achat d’avant se paie dès qu’il le peut sans toucher à l’argent gardé de côté.'})+lowLine(r),'main');
  else doc+=section('program','Ton programme, dans l’ordre',reached?'Déjà possible : rien à faire avant ton but':(first&&first.steps.length?'En premier : '+stepsText(first.steps)+' · <b>'+plural(r.totalSessions,' partie',' parties')+'</b>, '+plural(r.phases.length,' étape',' étapes'):'<b>'+plural(r.totalSessions,' partie',' parties')+'</b> de '+D+' · '+plural(r.days,' jour',' jours')),reached?'':'Ce qu’il faut faire en premier, en deuxième, en troisième… C’est le chemin le plus rapide trouvé avec tes missions et ton temps.',()=>phaseCards(s,r)+routeBlock(s,r)+lowLine(r)+(reached?'':'<p class="calc-note">Comment l’ordre est choisi : à chaque partie, on prend les missions qui rapportent le plus dans le temps de la partie, avec l’argent que tu as à ce moment-là. Un achat d’avant se fait dès que tu peux le payer sans toucher à l’argent que tu gardes de côté ; s’il débloque une mission ou rapporte de l’argent, la suite va plus vite.'+(r.limited?' Le programme vient des enchaînements comparés à chaque partie : il peut en exister un plus rapide.':'')+'</p>'),'main');
  /* 2. Plans de secours (calculés seulement quand on ouvre le point) */
  if(!reached){const late=obs&&obs.last&&obs.last.gap!==null&&obs.last.gap<-1e-9;
   const intro=late?'Ta dernière partie a rapporté <b>'+money(obs.last.gain)+'</b> au lieu de <b>'+money(obs.last.plannedGain)+'</b> prévus. Le plan ci-dessus repart déjà de ce que tu as ; voici quand même d’autres façons d’y arriver, avec leur temps.':'Si une mission ne rentre pas, si tu gagnes moins que prévu, ou si tu préfères faire autrement : chaque plan est calculé avec la même situation. Choisis-en un, le programme suit.';
   doc+=section('alternatives','Si ça ne se passe pas comme prévu',late?'<b>'+money(obs.last.gain)+'</b> gagnés au lieu de '+money(obs.last.plannedGain)+' prévus · plans A, B, C…':(r.variant!=='auto'?'Tu suis un plan de secours · les autres sont là':'Plans A, B, C… calculés sur ta situation, prêts si tu gagnes moins que prévu'),intro,()=>{const alt=B.planAlternatives(s,r),plans=alt.valid?alt.plans:[],curId=r.variant==='auto'?'all':r.variant,ok=plans.filter(x=>x.valid).sort((a,b)=>(a.id===curId?-1:b.id===curId?1:0)),ko=plans.filter(x=>!x.valid);
    return (ok.length?'<ol class="b-alts">'+ok.slice(0,5).map((x,i)=>'<li class="b-alt'+(x.id===curId?' is-current':'')+'"><span class="b-alt-letter">'+String.fromCharCode(65+i)+'</span><div><h4>Plan '+String.fromCharCode(65+i)+' · '+esc(x.label)+(x.id===curId?' <span class="calc-tag">TON PLAN ACTUEL</span>':'')+'</h4><div class="b-tiles">'+(flow?'<span><small>Temps de jeu</small><b>'+hours((x.totalMinutes||0)/60)+'</b></span>':'<span><small>Parties</small><b>'+x.totalSessions+'</b></span><span><small>Jours</small><b>'+x.days+'</b></span>')+'<span><small>À la fin</small><b>'+money(x.finalCash)+'</b></span></div><p class="b-alt-program">'+esc(programSummary(alt.results[x.id]))+'</p>'+(x.note?'<p class="calc-note">'+esc(x.note)+'</p>':'')+(x.id!==curId?btn('Suivre ce plan','data-b-plan-variant="'+esc(x.id)+'"'):'')+'</div></li>').join('')+'</ol>':'<p>'+esc(alt.valid?'Aucun autre plan ne marche avec ces chiffres.':alt.reason)+'</p>')+(ko.length?'<p class="calc-note"><b>Impossible avec ces chiffres :</b> '+ko.map(x=>esc(x.label)+' ('+esc(x.reason||'pas atteint')+')').join(' · ')+'</p>':'');},late?'alert':'');}
  /* 3. Suivi du réel */
  doc+=section('actual','Après avoir joué : où en es-tu vraiment ?',obs?'<b>'+plural(obs.sessions,' partie',' parties')+(lkPluriel(obs.sessions)?'</b> notées':'</b> notée')+' · dernière : '+(obs.last.gain>=0?'+':'−')+money(Math.abs(obs.last.gain))+(obs.last.gap===null?'':' ('+(obs.last.gap>=0?'+':'−')+money(Math.abs(obs.last.gap))+' par rapport au prévu)'):'Écris ce que tu as après ta partie : tout le plan se recalcule','Écris ce que tu as maintenant et ce que tu as fait. Tout le plan se recalcule à partir de là : missions, achats, parties, jours. Rien n’est compté deux fois.',()=>actualForm(s,r,obs));
  /* 4. Point de départ */
  const start=[['Argent en poche',money(si.capital),'plan-capital'],['Gardé de côté',money(r.input.reserve)+(r.input.reserve!==(si.reserve??0)?' (tu as choisi « le plus vite »)':''),'plan-reserve'],['Une partie',flow?'durée libre : parcours sans calendrier':D+' · '+dpw+' j/semaine','plan-daily'],['Dépenses par partie',money(si.upkeepPerSession||0),'plan-upkeep'],
   p.source==='missions'?['Missions au choix',p.missions.map(m=>m.name).join(', ')||'aucune',p.missions.length?'plan-m-0-reward':'plan-m-source']:['Gain par heure (ton chiffre)',money(si.hourly),'plan-hourly'],
   g.kind==='purchase'?['Ton but',esc(g.name||'mon achat')+' · '+money(g.price)+(g.boostHourly>0?' · +'+money(g.boostHourly)+'/h ensuite':''),'plan-price']:g.kind==='amount'?['Ton but','avoir '+money(g.target),'plan-target']:['Ton but','débloquer '+esc(g.name||'mon but')+' · '+units(s,g.targetUnits)+(g.alsoPrice>0?' · puis '+money(g.alsoPrice):''),'plan-units-target'],
   ['Achats d’avant',p.prerequisites.length?p.prerequisites.map(a=>a.name+(a.owned?' (déjà possédé)':' ('+money(a.price)+(a.boostHourly>0?', +'+money(a.boostHourly)+'/h':'')+')')).join(' · '):'aucun','plan-prereq-search']];
  doc+=section('start','Ton point de départ',esc(money(si.capital)+' en poche · '+D+' · '+dpw+' j/sem · '+(p.source==='missions'?plural(p.missions.length,' mission',' missions'):money(si.hourly)+'/h')),'Les chiffres qui font ce plan. Change-en un : tout se recalcule.','<ul class="b-assumptions">'+start.map(([l,v,f])=>'<li><span>'+esc(l)+'</span><b>'+v+'</b>'+btn('Modifier','data-b-focus="'+f+'"')+'</li>').join('')+'</ul><p class="calc-note">Rien ne vient du vrai jeu : prix, gains et temps sont tes chiffres, ou ceux que le site indique comme repères.</p>');
  /* 5. Stratégie */
  const st=r.strategies;
  if(st&&st.valid&&st.candidates.filter(c=>c.valid).length>1){const rec=st.candidates.find(c=>c.id===st.recommended),asIs=st.candidates.find(c=>c.id==='asIs');
   const why=rec&&asIs&&rec.id!=='asIs'&&rec.valid&&asIs.valid?((flow?rec.totalMinutes<asIs.totalMinutes-1e-9:rec.totalSessions<asIs.totalSessions)?'tu gagnes '+(flow?hours((asIs.totalMinutes-rec.totalMinutes)/60)+' de jeu':plural(asIs.totalSessions-rec.totalSessions,' partie',' parties'))+' par rapport à ton ordre':'même '+(flow?'temps de jeu':'nombre de parties')+' que ton ordre, avec '+(rec.reserveKept?'ton argent de côté gardé':'plus d’argent à la fin')):p.priority==='cheap'?'c’est la façon qui laisse le plus d’argent à la fin parmi celles qui gardent ton argent de côté':p.priority==='safe'?'c’est la façon dont le point bas est le plus haut parmi celles qui gardent ton argent de côté':'c’est la façon la plus rapide parmi celles qui '+(p.priority==='fast'?'ont été comparées':'gardent ton argent de côté');
   doc+=section('strategy','L’ordre des achats d’avant','Conseillé : <b>'+esc(rec?rec.label:'')+'</b> · '+st.candidates.filter(c=>c.valid).length+' façons comparées','Même but, mêmes chiffres : seul l’ordre des achats, ou l’argent gardé de côté, change.','<p class="b-strategy-answer"><b>'+esc(rec?rec.label:'')+'</b> : '+esc(why)+'.</p>'+table([['Façon de faire',flow?'Temps de jeu':'Parties','Jours','Argent à la fin','Au plus bas','Réserve gardée'],...st.candidates.map(c=>[(c.id===st.recommended?'★ ':'')+c.label+(c.note?' — '+c.note:''),c.valid?(flow?hours((c.totalMinutes||0)/60):String(c.totalSessions)):'Impossible : '+c.reason,c.valid&&!flow?String(c.days):'—',c.valid?money(c.finalCash):'—',c.valid&&c.lowCash!==null&&c.lowCash!==undefined?money(c.lowCash):'—',c.reserveKept?'Oui':'Non'])],'Ordres comparés par recalcul complet',true)+'<p class="calc-note">On compare '+st.explored+' façons de faire ; il peut en exister une meilleure. Celles qui retirent un achat demandé ne sont jamais conseillées.</p>');}
  /* 6. Échéance */
  if(p.deadlineDays){let body='';if(!deadline||!deadline.valid)body=warning(deadline?deadline.reason:'Échéance non calculable.');
   else if(deadline.feasible)body='<p class="b-strategy-answer"><b>Oui</b>, c’est faisable : tu finis au jour '+deadline.days+', avec '+plural(deadline.spareDays,' jour',' jours')+' d’avance.</p>';
   else body='<p class="b-strategy-answer"><b>Pas avec ton rythme actuel</b> : tu finirais au jour '+deadline.days+', soit '+plural(deadline.spareDays,' jour',' jours')+' trop tard.</p><ul class="b-thresholds">'+(deadline.everydayDays!==null?'<li>Joue <b>tous les jours</b> : tu finis au jour '+deadline.everydayDays+'.</li>':'')+(deadline.requiredSessionMinutes!==null?'<li>Ou des parties de <b>'+hours(deadline.requiredSessionMinutes/60)+'</b> au lieu de '+D+'.</li>':'')+(deadline.requiredHourly!==null?'<li>Ou gagner <b>'+money(deadline.requiredHourly)+' par heure</b> au lieu de '+money(si.hourly)+'.</li>':'')+(deadline.everydayDays===null&&deadline.requiredSessionMinutes===null&&deadline.requiredHourly===null?'<li>Aucun réglage simple ne suffit : réduis le but ou change de missions.</li>':'')+'<li>Sinon, la date la plus proche : <b>jour '+r.days+'</b> (vers le '+planDate(r.days)+').</li></ul>';
   doc+=section('deadline','Ton échéance : '+plural(p.deadlineDays,' jour',' jours'),deadline&&deadline.valid?(deadline.feasible?'<b>Faisable</b> · '+plural(deadline.spareDays,' jour',' jours')+' d’avance':'<b>Pas avec ton rythme</b> · jour '+deadline.days+' au lieu de '+p.deadlineDays):'À vérifier','',body,deadline&&deadline.valid&&!deadline.feasible?'alert':'');}
  /* 7+. Détails */
  if(details&&!reached){
   const rows=r.sessions.slice(0,60).map(se=>['Partie '+se.index+' · jour '+dayOf(se.index,dpw),whatText(se),signed(se.gain)+(g.kind==='unlock'&&se.unitsGain>0?' · +'+nf.format(Math.round(se.unitsGain*100)/100):''),money(se.cashAfter),se.purchases.length?se.purchases.join(', '):'—']);
   if(flow)doc+=section('route-table','Étape par étape',plural((r.route||[]).length,' étape',' étapes')+' · de '+money(r.startCash)+' à '+money(r.finalCash),'Chaque étape du parcours, avec ce qu’elle coûte, ce qu’elle rapporte et ce que tu as ensuite.',()=>table([['Quand','Étape','Payé','Reçu','Tu as ensuite'],...(r.route||[]).slice(0,120).map(x=>[hours(x.start/60),x.type==='acquire'?'Achète « '+x.name+' »':x.type==='unlock'?'« '+x.name+' » (une seule fois)':'« '+x.name+' » ×'+x.runs,x.spend?'−'+money(x.spend):'—',x.receive?'+'+money(x.receive):'—',money(x.cashAfter)])],'Le parcours complet'+((r.route||[]).length>120?' (120 premières étapes sur '+r.route.length+')':''),true));
   else doc+=section('sessions','Partie par partie',plural(r.totalSessions,' partie',' parties')+' · de '+money(r.startCash)+' à '+money(r.finalCash),'Chaque partie avec ses missions, ce qu’elle rapporte, ce que tu as ensuite et ce que tu achètes.',()=>table([['Partie','Missions','Gagné','Tu as ensuite','Achat'],...rows],'Le programme complet'+(r.sessions.length>60?' (60 premières parties sur '+r.sessions.length+')':''),true));
   doc+=section('variants','Et si… ?','Parties plus longues, un jour de plus, prix plus chers, missions qui rapportent moins…','Le même plan, recalculé en entier avec un chiffre qui change.',()=>{const v=variants(s,r);return table([['Et si…',flow?'Temps de jeu':'Parties','Jours','Argent à la fin'],...v.map(x=>[x.label,x.r.valid&&x.r.reached?(flow?hours(x.r.totalMinutes/60):String(x.r.totalSessions)):'Impossible',x.r.valid&&x.r.reached&&!flow?String(x.r.days):'—',x.r.valid?money(x.r.finalCash):'—'])],'Pour voir ce qui pèse le plus',true);});
   doc+=section('thresholds','Ce qui change tout','30 min de plus par partie, l’achat d’avant tout de suite…','',()=>{const v=variants(s,r),thresholds=[];const longer=v.find(x=>x.id==='longer');if(longer&&longer.r.valid&&longer.r.reached)thresholds.push(longer.r.totalSessions<r.totalSessions?'Avec <b>30 min de plus par partie</b>, tu finis en <b>'+plural(longer.r.totalSessions,' partie',' parties')+'</b> au lieu de '+r.totalSessions+'.':'<b>30 min de plus par partie</b> ne changent pas le nombre de parties ('+r.totalSessions+') : le temps n’est pas ce qui bloque.');
    const firstBuy=r.purchases.find(x=>x.atSession);if(firstBuy&&firstBuy.atSession>1)thresholds.push('Il te manque <b>'+money(Math.max(0,firstBuy.price+r.input.reserve-r.startCash))+'</b> pour acheter « '+esc(firstBuy.name)+' » dès maintenant.');
    if(g.kind==='unlock'&&r.missingUnits===0&&r.startUnits<r.input.targetUnits)thresholds.push('Il te manque <b>'+units(s,r.input.targetUnits-r.startUnits)+'</b> pour débloquer '+esc(goalShort(s))+'.');
    return thresholds.length?'<ul class="b-thresholds">'+thresholds.map(t=>'<li>'+t+'</li>').join('')+'</ul>':'<p class="calc-note">Avec ces chiffres, aucun petit changement ne change beaucoup le plan.</p>';});
   if(curve.length>1)doc+=section('curve','Ton argent au fil du plan','La courbe prévue'+(p.log.length?' et tes points réels (cliquables)':'')+' · '+money(r.startCash)+' → '+money(r.finalCash),'',()=>visual.chart('c-plan-curve',{title:'Ton argent, partie après partie',question:'Quand chaque achat devient-il possible, et où en seras-tu ?',xTitle:'Temps de jeu (heures)',yTitle:'Argent en poche ($)',unit:'$',xUnit:'h',area:false,series:[{name:'Prévu avec tes chiffres',kind:'forecast',step:true,points:curve.map(pt=>({x:(p.log.length?(p.playedMinutes||0)/60:0)+pt.hours/* lot 4 : le plan repart du dernier point réel (même axe de temps joué) */,y:pt.cash,label:pt.label,key:pt.purchase}))},...(p.log.length?[{name:'Réel (ce que tu as écrit)',kind:'realized',dots:true,points:p.log.map((e,i)=>({x:e.minutes/60,y:e.capital,label:new Date(e.at).toLocaleDateString('fr-FR'),edit:'log:'+i}))}]:[])],thresholds:r.input.reserve>0?[{y:r.input.reserve,label:'Argent gardé de côté'}]:[],reading:(flow?'L’argent saute d’un coup à chaque récompense et descend à chaque frais ou achat : rien n’est lissé.':'Chaque marche est une partie : son argent est compté à la fin de la partie, achats d’après compris. Le plan finit après '+plural(r.totalSessions,' partie',' parties')+'.')+lowText(r),note:'Les points « réel » viennent de tes mises à jour ; ils ne sont pas lissés. Clique sur un point réel pour le corriger ou le retirer.'}));
   const cal=[...r.purchases.filter(x=>x.atSession).map(x=>['Achète « '+x.name+' »','après la partie '+x.atSession,'jour '+dayOf(x.atSession,dpw),planDate(dayOf(x.atSession,dpw))]),[g.kind==='purchase'?'Achète '+goalShort(s):g.kind==='unlock'?'Débloque '+goalShort(s):'Tu as '+goalShort(s),'après la partie '+r.totalSessions,'jour '+r.days,planDate(r.days)]];
   if(!flow)doc+=section('calendar','Ton calendrier','But vers le <b>'+esc(planDate(r.days))+'</b>'+(cal.length>1?' · '+plural(cal.length-1,' achat',' achats')+' avant':''),'Si tu joues '+D+' par partie, '+dpw+(E.plural(dpw)?' jours':' jour')+' par semaine, en commençant aujourd’hui.',table([['Étape','Quand','Jour','Date estimée'],...cal],'Les moments qui comptent',true));
   doc+=section('method','Comment est-ce calculé ?','Partie après partie, avec tes chiffres, sans rien inventer','','<p class="calc-note">Partie après partie : avec l’argent que tu as à ce moment-là, on cherche les missions qui rapportent le plus dans le temps de la partie (frais payés avant, récompense à la fin, préparation et attente comptées, une mission se fait en entier ou pas du tout). On enlève tes dépenses par partie, on ajoute ce que rapportent tes achats déjà faits. Puis on paie les achats d’avant, dans l’ordre, dès que l’argent dépasse le prix sans toucher à l’argent gardé de côté ; un achat peut débloquer une mission. On s’arrête quand tu peux payer ton but (et que tu as les points, s’il en faut). Jours = parties réparties sur tes jours de jeu par semaine, en commençant aujourd’hui. Rien ne vient du vrai jeu.</p>'+(flow?'<p class="calc-note">Sans durée de partie, le parcours enchaîne les étapes sans pause : à chaque moment, la mission qui rapporte le plus par minute parmi celles possibles, les achats d’avant dès qu’ils se paient, les attentes quand il le faut. Il n’y a donc pas de jours, seulement du temps de jeu.</p>':''));}
  else if(!reached&&mode!=='advanced')doc+='<div class="b-doc-more"><p class="calc-note">Chaque partie, les « et si », la courbe et le calendrier sont dans le mode Expert.</p>'+btn('Voir en mode Expert','data-b-mode="advanced"')+'</div>';
  doc+=section('saved','Mes variantes du plan',(p.variants||[]).length?'<b>'+plural(p.variants.length,' variante',' variantes')+(lkPluriel(p.variants.length)?'</b> gardées':'</b> gardée')+' · compare-les au plan actuel':'Garde ce plan avant d’essayer autre chose','',()=>savedVariants(s,r));
  doc+='<div class="b-plan-links">'+btn('Préparer ma prochaine partie','data-open="session"')+btn('Vérifier ce qu’un achat rapporte','data-open="roi"')+btn('Comparer des achats','data-open="compare"')+'</div></div>';
  $('plan-report').innerHTML=doc;
  $('expert-plan').innerHTML=expert?expertBlock(s,r):'';
 }
 function markSkips(s){document.querySelectorAll('#panel-plan .calc-step[data-step="4"]').forEach(n=>{if(!s.plan.prerequisites.length&&s.plan.goal.kind==='amount')n.dataset.skip='1';else delete n.dataset.skip;});}
 function variantLabel(s,r){if(r.variant==='auto')return '';const alt=B.planAlternatives(s,r);const x=alt.valid?alt.plans.find(y=>y.id===r.variant):null;return x?x.label:r.variant;}
 function variants(s,r){const i=r.input,out=[];const run=(id,label,changes)=>out.push({id,label,r:E.missionPlan({...i,...changes,journal:false})});/* lot 2 (C7) : « Et si… » calculé sans journal */
  if(i.sessionMinutes)run('longer','Des parties de 30 min de plus',{sessionMinutes:i.sessionMinutes+30});
  if(i.sessionMinutes&&i.daysPerWeek<7)run('everyday','Un jour de jeu de plus par semaine',{daysPerWeek:i.daysPerWeek+1});
  run('prices','Les prix sont 20 % plus chers',{goalPrice:i.goalPrice===null?null:i.goalPrice*1.2,target:i.target===null?null:i.target*1.2,purchases:i.purchases.map(x=>({...x,price:x.price*1.2}))});
  run('less',s.plan.source==='missions'?'Mes missions rapportent 20 % de moins':'Je gagne 20 % de moins',s.plan.source==='missions'?{activities:i.activities.map(a=>({...a,reward:a.reward===null?null:a.reward*0.8}))}:{hourly:i.hourly*0.8});
  if(i.reserve>0)run('reserve','Je dépense aussi mon argent de côté',{reserve:0});
  return out;}
 function actualForm(s,r,obs){const p=s.plan,g=p.goal,si=p.situation,next=B.planNextSession(r);
  let html='<div class="calc-fields b-actual"><div class="calc-field"><label class="calc-label" for="plan-actual">J’ai maintenant ($)</label><input id="plan-actual" type="text" inputmode="decimal" maxlength="25" data-number="1" data-min="0" data-max="1000000000000" value="" placeholder="'+esc(nf.format(si.capital??0))+'"><small>Ton argent en poche après ta partie.</small></div><div class="calc-field"><label class="calc-label" for="plan-actual-minutes">J’ai joué (minutes)</label><input id="plan-actual-minutes" type="text" inputmode="decimal" maxlength="6" data-number="1" data-min="0" data-max="100000" value="'+esc(si.dailyMinutes??'')+'"></div>';
  if(g.kind==='unlock')html+='<div class="calc-field"><label class="calc-label" for="plan-actual-units">J’ai maintenant ('+esc(g.unitLabel||'points')+')</label><input id="plan-actual-units" type="text" inputmode="decimal" maxlength="25" data-number="1" data-min="0" data-max="1000000000000" value="" placeholder="'+esc(nf.format(g.currentUnits??0))+'"></div>';
  if(p.source==='missions')html+=p.missions.map(m=>{const planned=next?next.steps.find(st=>st.id===m.id):null;return '<div class="calc-field"><label class="calc-label" for="plan-actual-runs-'+esc(m.id)+'">« '+esc(m.name)+' » faite combien de fois ?</label><input id="plan-actual-runs-'+esc(m.id)+'" data-b-plan-actual-runs="'+esc(m.id)+'" type="text" inputmode="numeric" maxlength="6" data-number="1" data-min="0" data-max="100000" value="" placeholder="'+(planned?'prévu : '+planned.runs:'0')+'"></div>';}).join('');
  html+='<div class="calc-field wide"><label class="calc-label" for="plan-actual-note">Une note, si tu veux</label><input id="plan-actual-note" type="text" maxlength="300" value="" placeholder="Ce qui s’est passé pendant la partie"></div></div>';
  const buyable=p.prerequisites.filter(a=>!a.owned);if(buyable.length)html+='<fieldset class="b-plan-requires"><legend>Pendant cette partie, j’ai acheté :</legend>'+buyable.map(a=>'<label class="calc-check"><input type="checkbox" data-b-plan-actual-bought="'+esc(a.id)+'"> '+esc(a.name)+(a.price!==null?' ('+money(a.price)+')':'')+'</label>').join('')+'</fieldset>';
  html+='<div class="b-plan-card-actions">'+btn('Mettre à jour mon plan','data-b-plan-log="1"',true)+(p.log.length?btn('Effacer l’historique','data-b-plan-clear="1"'):'')+'</div><p class="calc-note" id="plan-log-feedback" role="status"></p>';
  if(obs&&obs.last){const L=obs.last,gap=L.gap;
   html+='<div class="b-bilan"><p class="calc-kicker">BILAN DE TA DERNIÈRE PARTIE</p><div class="b-tiles">'+[['Prévu',L.plannedGain===null?'—':signed(L.plannedGain)],['Réel',signed(L.gain)],['Écart',gap===null?'—':(gap>=0.5?'+':gap<=-0.5?'−':'')+money(Math.abs(gap))],['Ton rythme réel',obs.hourly===null?'—':money(Math.round(obs.hourly))+' par heure']].map(([l,v])=>'<span><small>'+esc(l)+'</small><b>'+v+'</b></span>').join('')+'</div><p>'+esc(gap===null?'Le plan repart de ce que tu as maintenant.':Math.abs(gap)<0.5/* lot 5 : un écart nul n’est pas « en avance » */?'Pile comme prévu : le plan repart de ce que tu as.':gap>0?'Tu es en avance : le plan repart de ce que tu as, et il est plus court.':'Tu as gagné moins que prévu : le plan repart de ce que tu as, et la section « Si ça ne se passe pas comme prévu » propose d’autres chemins.')+(obs.sessions>1?' Sur tes '+obs.sessions+' parties notées, tu gagnes en moyenne '+money(obs.perSession)+' par partie.':'')+'</p>'+(p.source==='hourly'&&obs.hourly!==null&&Math.abs(obs.hourly-(si.hourly||0))>1?btn('Adopter mon vrai rythme ('+money(obs.hourly)+' par heure)','data-b-plan-adopt="1"'):'')+'</div>';}
  if(p.log.length){const rows=p.log.slice().reverse().map(e=>{const d=new Date(e.at),date=Number.isFinite(d.getTime())?d.toLocaleDateString('fr-FR',{day:'numeric',month:'short'}):'—';return [date,hours(e.minutes/60),e.plannedGain===null?'—':signed(e.plannedGain),e.gain===null?'—':signed(e.gain),money(e.capital),e.forecast===null?'—':money(e.forecast),Object.keys(e.runs).length?Object.entries(e.runs).filter(([,n])=>n>0).map(([id,n])=>(p.missions.find(m=>m.id===id)?.name||id)+' ×'+n).join(', ')+(e.purchases.length?' · acheté : '+e.purchases.map(id=>p.prerequisites.find(a=>a.id===id)?.name||id).join(', '):''):(e.purchases.length?'acheté : '+e.purchases.map(id=>p.prerequisites.find(a=>a.id===id)?.name||id).join(', '):'—'),e.note||'—'];});
   html+=table([['Date','Joué en tout','Prévu (partie)','Réel (partie)','J’avais','Le plan prévoyait','Fait','Note'],...rows],'Réalisé contre prévu, partie après partie',true)+'<p class="calc-note">« Le plan prévoyait » = l’argent attendu après ce temps de jeu, d’après le plan d’avant la mise à jour. Le plan actuel repart toujours du réel.</p>';}
  return html;}
 function expertBlock(s,r){const RAW={totalSessions:'Parties',totalMinutes:'Temps de jeu (min)',activeMinutes:'Temps en mission (min)',days:'Jours',weeks:'Semaines',finalCash:'Argent à la fin ($)',finalUnits:'Points à la fin',missing:'Il manque ($)',missingUnits:'Points qui manquent',averagePerSession:'Gagné par partie, en moyenne ($)',goalMoney:'Argent à avoir ($)',startCash:'Argent au départ ($)',startUnits:'Points au départ'};const rows=Object.entries(r).filter(([k,v])=>RAW[k]&&(typeof v==='number'||v===null)).map(([k,v])=>[RAW[k],v===null?'Pas encore calculable':nf.format(v)]);const i=r.input;
  return '<div class="b-doc b-doc--light"><div class="b-doc-title b-doc-title--plain"><span class="b-doc-num">★</span><div><h3>Mode Expert : tout le détail</h3><p class="b-doc-lead">Le mode Expert montre tout : chaque partie, les « et si », la courbe, le calendrier et tous les chiffres du calcul. Ce sont les mêmes chiffres qu’en Simple, avec le détail.</p></div></div>'+fold('plan-x-inputs',{n:1,title:'Les chiffres utilisés',teaser:esc(money(i.capital)+' · gardé de côté '+money(i.reserve)+' · '+(i.sessionMinutes?hours(i.sessionMinutes/60):'durée libre')+' · ordre des achats : '+STRATEGY_LABEL[r.strategy||'asIs']),body:()=>table([['Chiffre','Valeur'],['Argent',money(i.capital)],['Gardé de côté',money(i.reserve)],['Durée d’une partie',(i.sessionMinutes?hours(i.sessionMinutes/60):'durée libre')],['Jours par semaine',String(i.daysPerWeek)],['Dépenses par partie',money(i.upkeepPerSession)],['Je gagne par heure',money(i.hourly)],['Missions',i.activities.map(a=>a.name).join(', ')||'aucune'],['But',i.goalPrice!==null?i.goalName+' : '+money(i.goalPrice):i.target!==null?'Avoir '+money(i.target):'Débloquer '+i.goalName],['Points à atteindre',i.targetUnits===null?'—':nf.format(i.targetUnits)+' (déjà '+nf.format(i.currentUnits)+')'],['Achats d’avant retenus',i.purchases.map(x=>x.name).join(', ')||'aucun'],['Ordre des achats',STRATEGY_LABEL[r.strategy||'asIs']],['Plan suivi',!r.variant||r.variant==='auto'?'le calculateur choisit':String(r.variant)]],'Les chiffres utilisés')})+fold('plan-x-raw',{n:2,title:'Tous les chiffres du calcul',teaser:esc(rows.length+' chiffres'),body:()=>table(rows,'Tous les chiffres du calcul')})+'</div>';}
 /* ---------- Événements propres au plan ---------- */
 function event(ev){const el=ev.target,s=state(),p=s.plan;
  if(ev.type==='change'){
   if(el.dataset.field==='plan.goal.kind'){if(B.PLAN_KINDS.includes(el.value))p.goal.kind=el.value;p.variant='auto';refresh(el.id);return true;}
   if(el.dataset.field==='plan.source'){if(B.PLAN_SOURCES.includes(el.value))p.source=el.value;p.variant='auto';refresh(el.id);return true;}
   if(el.dataset.field==='plan.strategy'){p.strategy=B.STRATEGIES.includes(el.value)?el.value:'auto';api.changed();return true;}
   if(el.dataset.bPlanMOwned!==undefined){const m=p.missions[Number(el.dataset.bPlanMOwned)];if(m)m.owned=el.checked;api.changed();return true;}
   if(el.dataset.bPlanMReq!==undefined){const [i,id]=el.dataset.bPlanMReq.split('|'),m=p.missions[Number(i)];if(m){m.requires=el.checked?[...new Set([...m.requires,id])]:m.requires.filter(x=>x!==id);}api.changed();return true;}
   if(el.dataset.bPlanMOnce!==undefined){const m=p.missions[Number(el.dataset.bPlanMOnce)];if(m){m.once=el.checked;if(!m.once)m.done=false;}p.variant='auto';refresh(el.id);return true;}
   if(el.dataset.bPlanMState!==undefined){const m=p.missions[Number(el.dataset.bPlanMState)];if(m&&el.checked){m.done=el.value==='done'&&m.once;m.started=el.value==='started';}p.variant='auto';api.changed();return true;}
   if(el.dataset.bPlanPState!==undefined){const a=p.prerequisites[Number(el.dataset.bPlanPState)];if(a&&el.checked){a.owned=el.value==='done';a.started=el.value==='started';}p.variant='auto';api.changed();return true;}
   if(el.dataset.bPlanMDone!==undefined){const m=p.missions[Number(el.dataset.bPlanMDone)];if(m)m.done=el.checked&&m.once;p.variant='auto';api.changed();return true;}
   if(el.dataset.bPlanMReqm!==undefined){const [i,id]=el.dataset.bPlanMReqm.split('|'),m=p.missions[Number(i)];if(m&&id!==m.id){m.requiresMissions=el.checked?[...new Set([...(m.requiresMissions||[]),id])]:(m.requiresMissions||[]).filter(x=>x!==id);}p.variant='auto';api.changed();return true;}
   if(el.dataset.bPlanPReq!==undefined){const [i,id]=el.dataset.bPlanPReq.split('|'),a=p.prerequisites[Number(i)];if(a&&id!==a.id){a.requires=el.checked?[...new Set([...(a.requires||[]),id])]:(a.requires||[]).filter(x=>x!==id);}p.variant='auto';api.changed();return true;}
   if(el.dataset.bPlanPLock!==undefined){const id=el.dataset.bPlanPLock;p.locked=el.checked?[...new Set([...(p.locked||[]),id])]:(p.locked||[]).filter(x=>x!==id);p.variant='auto';api.changed();return true;}
   if(el.dataset.bPlanPOwned!==undefined){const a=p.prerequisites[Number(el.dataset.bPlanPOwned)];if(a)a.owned=el.checked;p.variant='auto';api.changed();return true;}
   if(el.dataset.bPlanActualBought!==undefined||el.dataset.bPlanActualRuns!==undefined)return true;
  }
  if(ev.type==='input'&&(el.id==='plan-actual'||el.id==='plan-actual-minutes'||el.id==='plan-actual-units'||el.id==='plan-actual-note'||el.dataset.bPlanActualRuns!==undefined))return true;
  if(ev.type==='click'){const button=el.closest('button');if(!button)return false;const d=button.dataset;
   if(d.bPlanImportCalcs){importFromCalcs(s);p.variant='auto';refresh('plan-capital');api.notify('Tes chiffres de Mes calculs ont été copiés dans le plan. Tu peux les changer ici sans rien changer là-bas.');return true;}
   if(d.bPlanFree){p.goal.kind='purchase';p.goal.itemId='';p.goal.referencePrice=null;if(!p.goal.name)p.goal.name='Mon but';refresh('plan-name');return true;}
   if(d.bPlanPriceReset){p.goal.price=p.goal.referencePrice;refresh('plan-price');return true;}
   if(d.bPlanMAdd){if(p.missions.length>=12){api.notify('Douze missions au maximum dans le plan.');return true;}const id='m-'+Date.now().toString(36)+'-'+p.missions.length;p.missions.push({...B.copy(B.planMissionTemplate),id,name:'Mission '+(p.missions.length+1)});p.source='missions';p.variant='auto';refresh('plan-m-'+(p.missions.length-1)+'-name');return true;}
   if(d.bPlanMImport){const sel=$('plan-m-source');if(!sel)return true;const [kind,id]=sel.value.split(':'),a=(kind==='mine'?s.activities:sourceActivities).find(x=>x.id===id);if(!a)return true;if(p.missions.length>=12){api.notify('Douze missions au maximum dans le plan.');return true;}
    p.missions.push({...B.copy(B.planMissionTemplate),id:'m-'+Date.now().toString(36)+'-'+p.missions.length,name:a.name,reward:a.reward??null,cost:a.cost??0,duration:a.duration??null,prep:a.prep??0,cooldown:a.cooldown??0,share:a.share??100,investment:a.investment??0,owned:a.owned===true});p.source='missions';p.variant='auto';refresh('plan-m-'+(p.missions.length-1)+'-name');api.notify('« '+a.name+' » copiée dans le plan.');return true;}
   if(d.bPlanMRemove!==undefined){const [gone]=p.missions.splice(Number(d.bPlanMRemove),1);if(gone){p.missions.forEach(m=>{m.requiresMissions=(m.requiresMissions||[]).filter(x=>x!==gone.id);});p.prerequisites.forEach(a=>{a.requires=(a.requires||[]).filter(x=>x!==gone.id);});p.locked=(p.locked||[]).filter(x=>x!==gone.id);}p.variant='auto';refresh('plan-m-source');return true;}
   if(d.bPlanPAdd){if(p.prerequisites.length>=20){api.notify('Vingt achats d’avant au maximum.');return true;}p.prerequisites.push({...B.copy(B.planPrereqTemplate),id:'p-'+Date.now().toString(36)+'-'+p.prerequisites.length,name:'Mon achat d’avant'});p.variant='auto';refresh('plan-p-'+(p.prerequisites.length-1)+'-name');return true;}
   if(d.bPlanPRemove!==undefined){const [a]=p.prerequisites.splice(Number(d.bPlanPRemove),1);if(a){p.missions.forEach(m=>{m.requires=m.requires.filter(x=>x!==a.id);});p.prerequisites.forEach(o=>{o.requires=(o.requires||[]).filter(x=>x!==a.id);});p.locked=(p.locked||[]).filter(x=>x!==a.id);}p.variant='auto';refresh('plan-prereq-search');return true;}
   if(d.bPlanPUp!==undefined||d.bPlanPDown!==undefined){const i=Number(d.bPlanPUp??d.bPlanPDown),j=i+(d.bPlanPUp!==undefined?-1:1);if(j>=0&&j<p.prerequisites.length)[p.prerequisites[i],p.prerequisites[j]]=[p.prerequisites[j],p.prerequisites[i]];refresh();return true;}
   if(d.bPlanVariant!==undefined){p.variant=d.bPlanVariant||'auto';api.changed();api.notify(p.variant==='auto'?'Retour au meilleur plan trouvé.':'Le programme suit maintenant ce plan de secours.');return true;}
   if(d.bPlanAdopt){const obs=B.planObserved(s);if(obs&&obs.hourly!==null){p.situation.hourly=Math.round(obs.hourly);document.querySelectorAll('[data-field="plan.situation.hourly"]').forEach(i=>{i.value=p.situation.hourly;});api.changed();api.notify('Ton gain par heure est maintenant celui que tu as vraiment eu : '+money(p.situation.hourly)+'.');}return true;}
   if(d.bPlanVsave){p.variants=p.variants||[];if(p.variants.length>=5){api.notify('Cinq variantes au plus : retire-en une pour en garder une autre.');return true;}p.variants.push(variantOf(s));api.changed();api.notify('Plan gardé comme variante. Tu peux maintenant essayer autre chose.');return true;}
   if(d.bPlanVload){const k=(p.variants||[]).findIndex(v=>v.id===d.bPlanVload);if(k<0)return true;const v=p.variants[k],current=variantOf(s);VARIANT_KEYS.forEach(key=>{if(v[key]!==undefined)p[key]=B.copy(v[key]);});p.variants.splice(k,1,current);p.variant='auto';refresh('plan-capital');api.notify('Variante reprise. Le plan d’avant est gardé à sa place dans tes variantes : rien n’est perdu.');return true;}
   if(d.bPlanVdel){p.variants=(p.variants||[]).filter(v=>v.id!==d.bPlanVdel);api.changed();api.notify('Variante retirée.');return true;}
   if(d.bPlanLog){return logSession(s);}
   if(d.bPlanClear){p.log=[];p.playedMinutes=0;p.sessionsPlayed=0;api.changed();api.notify('Historique effacé. Ton argent actuel est gardé.');return true;}
   if(d.bPlanExport){const r=B.evaluate('plan',s);const text=exportText(s,r);const blob=new Blob([text],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mon-business-plan-leonidakit.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);api.notify('Plan exporté en texte lisible.');return true;}
  }
  return false;}
 /* v7.54 : « Reprendre mes chiffres » copie tout ce que les huit calculs ont pris en compte (revue v7.53, écart B1) : le sens du but,
    les dépenses par partie, le groupe, et pour chaque achat d’avant son coût d’usage par partie, son gain (écrit ou venu de
    « Ça vaut le coup ? »), ses dépendances et ce qu’il a de « déjà à moi ». Une option ou un frais inconnu reste inconnu : le prix
    de l’achat devient « à écrire », jamais 0. Chaque mission garde son nombre de joueurs. */
 function importFromCalcs(s){const p=s.plan,g=s.goal;p.situation.capital=g.capital;p.situation.reserve=g.reserve??0;p.situation.hourly=g.hourly;p.situation.dailyMinutes=g.dailyMinutes??s.session.usualMinutes??s.session.minutes;p.situation.daysPerWeek=s.session.daysPerWeek??7;
  p.situation.players=Number.isInteger(g.players)&&g.players>0?g.players:1;if(Number.isFinite(g.upkeepPerSession))p.situation.upkeepPerSession=g.upkeepPerSession;
  if(p.goal.kind==='amount'&&p.goal.target===null)p.goal.target=g.target;if(p.goal.kind==='amount'&&g.meaning&&B.GOAL_MEANINGS.includes(g.meaning))p.goal.meaning=g.meaning;
  const total=a=>a.price===null||a.extras===null||a.fees===null?null:a.price+(a.extras||0)+(a.fees||0);
  const boost=a=>{if(a.owned)return 0;if(a.incomeMode==='personal'&&Number.isFinite(a.boostHourly))return a.boostHourly;if(a.incomeMode==='roi'&&s.roi.key===a.key){const r=B.roi(s,sourceActivities);return ['new','improve'].includes(B.roiMode(s))&&r.valid&&Number.isFinite(r.netHourly)?Math.max(0,r.netHourly):0;}return 0;};
  const usage=a=>{const u=B.usageOf(s,a,itemFor(a));return u&&u.perSession&&typeof u.perSession.v==='number'&&Number.isFinite(u.perSession.v)&&u.perSession.s!=='unconfirmed'?u.perSession.v:null;};
  const byKey={},existing=new Map(p.prerequisites.map(a=>[a.itemId||a.name,a]));
  s.order.keys.forEach(k=>{const a=B.asset(s,k);if(!a)return;const found=existing.get(a.itemId||a.name);if(found){byKey[k]=found.id;return;}if(p.prerequisites.length>=20)return;const id='p-'+Date.now().toString(36)+'-'+p.prerequisites.length;byKey[k]=id;p.prerequisites.push({...B.copy(B.planPrereqTemplate),id,name:a.name,itemId:a.itemId||'',referencePrice:a.referencePrice??null,price:total(a),boostHourly:boost(a),owned:a.owned===true,usagePerSession:usage(a),requires:[]});});
  s.order.keys.forEach(k=>{const a=B.asset(s,k),pr=p.prerequisites.find(x=>x.id===byKey[k]);if(!a||!pr)return;pr.requires=[...new Set([...(pr.requires||[]),...(a.requires||[]).map(r=>byKey[r]).filter(Boolean)])];});
  const names=new Set(p.missions.map(m=>m.name));s.activities.filter(a=>Number.isFinite(a.reward)&&Number.isFinite(a.duration)&&s.session.enabled.includes(a.id)).forEach(a=>{if(names.has(a.name)||p.missions.length>=12)return;p.missions.push({...B.copy(B.planMissionTemplate),id:'m-'+Date.now().toString(36)+'-'+p.missions.length,name:a.name,reward:a.reward,cost:a.cost??0,duration:a.duration,prep:a.prep??0,cooldown:a.cooldown??0,share:a.share??100,investment:a.investment??0,owned:a.owned===true,players:Number.isInteger(a.players)&&a.players>0?a.players:1,requires:(a.requiresPurchaseIds||[]).map(id=>{const k=s.assets.find(x=>x.itemId===id)?.key;return k?byKey[k]:null;}).filter(Boolean)});});
  if(s.model==='cycles'&&p.missions.length)p.source='missions';}
 /* lot 5 (seconde relecture) : argent prévu par le journal du plan à « played » minutes. Avec un gain par heure, l’argent arrive en continu :
    chaque gain du journal couvre le temps depuis l’événement d’avant et compte au prorata (avant : tout le gain arrivait à la fin, d’où
    « Prévu +0 $ » pour 45 min jouées) ; avec des missions, il arrive à la fin de chacune, comme le journal le dit. */
 function journalCash(r,played,continuousGain){let cash=r.startCash,prevAt=0;for(const e of r.events){if(!Number.isFinite(e.at))continue;if(e.at<=played+1e-9){cash=e.cash;prevAt=e.at;continue;}if(continuousGain&&e.type==='receive'&&e.at>prevAt&&Number.isFinite(e.amount))cash+=e.amount*(played-prevAt)/(e.at-prevAt);break;}return cash;}
 function logSession(s){const p=s.plan,g=s.plan.goal,fb=$('plan-log-feedback');
  const cap=parse($('plan-actual')?.value),mins=parse($('plan-actual-minutes')?.value);
  if(cap===null||cap<0||cap>1e12){if(fb)fb.textContent='Écris ce que tu as maintenant, avec un nombre (par exemple 350 000).';$('plan-actual')?.focus();return true;}
  if(mins===null||mins<0||mins>1e5){if(fb)fb.textContent='Écris le temps joué en minutes (par exemple 60).';$('plan-actual-minutes')?.focus();return true;}
  let unitsNow=null;if(g.kind==='unlock'){const v=parse($('plan-actual-units')?.value);if(v!==null){if(v<0||v>1e12){if(fb)fb.textContent='Écris tes '+g.unitLabel+' avec un nombre.';$('plan-actual-units')?.focus();return true;}unitsNow=v;}}
  const runs={};document.querySelectorAll('[data-b-plan-actual-runs]').forEach(el=>{const v=parse(el.value);if(v!==null&&v>=0)runs[el.dataset.bPlanActualRuns]=Math.round(v);});
  const bought=[...document.querySelectorAll('[data-b-plan-actual-bought]:checked')].map(el=>el.dataset.bPlanActualBought).filter(id=>p.prerequisites.some(a=>a.id===id));
  const note=String($('plan-actual-note')?.value||'').slice(0,300);
  // v7.49 : une même mise à jour envoyée deux fois n’est comptée qu’une fois (identifiant tiré de son contenu et du point de départ).
  const logId=B.planLogId({prev:p.situation.capital,cap,mins,runs,bought,units:unitsNow,count:p.log.length?p.log[p.log.length-1].id||p.log.length:0});
  if(p.log.some(e=>e.id===logId)){if(fb)fb.textContent='Cette partie est déjà enregistrée : rien n’est compté deux fois.';return true;}
  const before=B.evaluate('plan',s),curve=before.valid?B.planCurve(before):[],next=B.planNextSession(before),played=mins/* lot 4 : le plan repart de l’argent écrit à chaque mise à jour : la prévision de cette partie se lit à « mins » du plan d’avant, pas au temps joué depuis le début (dérive à partir de la 2e mise à jour) */;
  /* correctif lot 2 (ARI5-6) : en parcours avec journal complet, la prévision est l’argent du journal après le dernier événement daté ≤ temps joué (exact) ;
     la courbe échantillonnée (un événement sur k au-delà de 600) pouvait s’en écarter de 3 % sans le dire. Parties et parcours sans journal complet : courbe. */
  const S0=before.valid&&before.input&&before.input.sessionMinutes>0?before.input.sessionMinutes:null,absMin=x=>before.continuous||S0===null?x.atMinute:(x.atSession-1)*S0+x.atMinute/* en parties, la minute d’achat est comptée dans sa partie */;
  /* lot 5 (relecture, P1) : en parties, la prévision à « mins » part de l’argent après les achats d’avant-partie (cashBefore) et ajoute le gain de la
     partie au prorata des minutes jouées ; avant, la courbe était interpolée depuis l’argent d’AVANT ces achats (+90 000 $ prévus au lieu de
     +50 000 $ pour 30 min à 100 000 $/h avec un achat de 80 000 $ payé au départ). Dans une partie, le gain est réparti sur ses minutes. */
  const sessCash=(()=>{if(!before.valid||before.continuous||S0===null||!Array.isArray(before.sessions))return null;const ss=before.sessions,q=Math.floor(played/S0+1e-9),f=played/S0-q;if(q>ss.length||(q===ss.length&&f>1e-9))return null;const cash=f>1e-9?ss[q].cashBefore+ss[q].gain*f:q>=1?ss[q-1].cashAfter:before.startCash;return Number.isFinite(cash)?cash:null;})();
  const at=sessCash!==null?{valid:true,cash:sessCash}:before.valid&&before.continuous&&before.journalComplete&&Array.isArray(before.events)?{valid:true,cash:journalCash(before,played,p.source==='hourly')}:E.planCashAt({points:curve.map(pt=>({hours:pt.hours,cash:pt.cash})),hours:played/60}),forecast=at&&at.valid?at.cash:null;
  const spent=bought.reduce((a,id)=>a+(p.prerequisites.find(x=>x.id===id)?.price||0),0),gain=Number.isFinite(p.situation.capital)?cap-p.situation.capital+spent:null;
  /* lot 4 : le « prévu » de la partie couvre le même temps que le « réel » (les minutes jouées, pas une partie entière) : argent prévu à
     « mins » − argent de départ + achats d’avant que le plan payait pendant ce temps (le réel ajoute de même les achats cochés). */
  const plannedSpent=before.valid&&Array.isArray(before.purchases)?before.purchases.filter(x=>Number.isFinite(x.atMinute)&&Number.isFinite(absMin(x))&&absMin(x)<=mins+1e-9&&!(p.prerequisites.find(a=>a.id===x.id)||{}).owned).reduce((t,x)=>t+(x.price||0),0):0;
  const plannedGain=forecast!==null&&before.valid&&Number.isFinite(before.startCash)?forecast-before.startCash+plannedSpent:next?next.gain:null;
  const unitsGain=unitsNow!==null&&Number.isFinite(g.currentUnits)?unitsNow-g.currentUnits:null;
  p.situation.capital=cap;if(unitsNow!==null)g.currentUnits=unitsNow;bought.forEach(id=>{const a=p.prerequisites.find(x=>x.id===id);if(a){a.owned=true;a.started=false;}});
  /* lot 4 : une mission faite pendant la partie est comptée comme dans un plan neuf : « une fois » → faite ; son achat de départ → payé */
  p.missions.forEach(m=>{if(!(runs[m.id]>0))return;if(m.once){m.done=true;m.started=false;}if(m.investment>0&&!m.owned)m.owned=true;});
  p.playedMinutes=(p.playedMinutes||0)+mins;p.sessionsPlayed=(p.sessionsPlayed||0)+1;
  p.log.push({id:logId,at:new Date().toISOString(),capital:cap,minutes:p.playedMinutes,forecast,note,units:unitsNow,unitsGain,gain,plannedGain,sessionMinutes:mins,runs,purchases:bought});if(p.log.length>60)p.log=p.log.slice(-60);
  document.querySelectorAll('[data-field="plan.situation.capital"]').forEach(i=>{i.value=cap;});if(unitsNow!==null)document.querySelectorAll('[data-field="plan.goal.currentUnits"]').forEach(i=>{i.value=unitsNow;});
  if(bought.length)refresh('plan-actual');else api.changed();
  const gap=plannedGain===null||gain===null?null:gain-plannedGain;
  /* v7.51 (lot 4) : un achat déclaré fait range le véhicule ou l’arme de la fiche dans son carnet (garage, arsenal). Le
     journal des réalisations (carnets-core.js) tient l’identifiant de la partie : enregistrer deux fois ne range rien deux
     fois. Une prévision du plan, elle, ne coche jamais rien et ne retire jamais rien. */
  const ranged=[];if(bought.length&&global.LKCarnets){try{const K=global.LKCarnets.create({storage:global.localStorage});bought.forEach(id=>{const a=p.prerequisites.find(x=>x.id===id),item=a&&a.itemId?itemFor({itemId:a.itemId}):null,fam=item?({vehicle:'vehicules',weapon:'armes'})[item.type]:null;if(!fam||!/^[a-z0-9][a-z0-9-]{0,99}$/.test(item.id))return;const r=K.applyEvent('plan:'+logId+':'+id,[{type:'own',famille:fam,id:item.id}]);if(r&&r.applied)ranged.push(item.name+(fam==='armes'?' (Mon arsenal)':' (Mon garage)'));});}catch(e){/* stockage indisponible : le plan reste juste, rien n’est annoncé */}}
  api.notify('Plan refait à partir de '+money(cap)+'.'+(gap===null?'':Math.abs(gap)<0.5?' Pile comme prévu.':gap>0?' Tu as gagné '+money(gap)+' de plus que prévu.':' Tu as gagné '+money(-gap)+' de moins que prévu : regarde les plans de secours.')+(ranged.length?' Rangé dans tes carnets : '+ranged.join(', ')+'.':''));return true;}
 /* ---------- Fiche complète (enregistrement) : le plan entier, lisible comme un document ---------- */
 function sheet(cfg,at){const s=cfg,p=s.plan,g=p.goal,si=p.situation,r=B.evaluate('plan',s),base=at||new Date().toISOString(),date=new Date(base),dateText=Number.isFinite(date.getTime())?date.toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'}):'—';
  let html='<article class="b-sheet"><div class="b-sheet-head"><p class="calc-kicker">LEONIDAKIT · FICHE DE BUSINESS PLAN</p><h2 id="calc-sheet-title">'+esc(s.name||'Mon plan')+'</h2><p class="b-doc-meta">'+esc('But : '+goalName(s)+' · enregistré le '+dateText)+'</p></div>';
  if(!r.valid){html+='<p class="calc-warning">'+esc('Plan non calculable au moment de l’enregistrement : '+r.reason)+'</p></article>';return html;}
  const D=sessionLabel(s),dpw=r.input.daysPerWeek,reached=r.continuous?r.totalMinutes===0:r.totalSessions===0;
  html+='<section><h3>En bref</h3><div class="b-tiles">'+(isFlow(r)?[['Temps de jeu',hours(r.totalMinutes/60)]]:[['Parties de '+D,String(r.totalSessions)],['Jours',String(r.days)]]).concat([['Départ',money(r.startCash)],['À la fin',money(r.finalCash)]]).map(([l,v])=>'<span><small>'+esc(l)+'</small><b>'+v+'</b></span>').join('')+'</div><p>'+esc(reached?'Le but est déjà possible avec ce que tu as.':isFlow(r)?'Il faut '+timeText(r)+', étape après étape (sans calendrier).'+lowText(r):'Il faut '+plural(r.totalSessions,' partie',' parties')+' de '+D+', '+dpw+(E.plural(dpw)?' jours':' jour')+' par semaine : vers le '+planDate(r.days,base)+' si tu commences le '+dateText+'.')+'</p></section>';
  html+='<section><h3>Le but</h3><p>'+esc(g.kind==='purchase'?(g.name||'Mon achat')+' — '+money(g.price)+(g.boostHourly>0?', il rapportera '+money(g.boostHourly)+' de plus par heure une fois acheté':', achat plaisir'):g.kind==='amount'?(g.meaning==='held'?'Avoir '+money(g.target)+' en tout, argent gardé de côté compris':g.meaning==='cumulative'?'Gagner '+money(g.target)+' à partir de maintenant':'Avoir '+money(g.target)+' en poche, en plus de l’argent gardé de côté'):'Débloquer '+(g.name||'mon but')+' : atteindre '+nf.format(g.targetUnits)+' '+g.unitLabel+' (déjà '+nf.format(g.currentUnits||0)+')'+(g.alsoPrice>0?', puis le payer '+money(g.alsoPrice):''))+'.</p></section>';
  html+='<section><h3>Où j’en suis</h3><ul class="b-sheet-list"><li>Argent en poche : <b>'+money(si.capital)+'</b></li><li>Gardé de côté : <b>'+money(si.reserve)+'</b>'+(r.input.reserve!==(si.reserve??0)?' (tu as choisi « le plus vite »)':'')+'</li><li>Une partie : <b>'+D+'</b>, '+dpw+(E.plural(dpw)?' jours':' jour')+' par semaine</li>'+(si.upkeepPerSession>0?'<li>Dépenses par partie : <b>'+money(si.upkeepPerSession)+'</b></li>':'')+(p.source==='hourly'?'<li>Je gagne à peu près <b>'+money(si.hourly)+' par heure</b></li>':'')+'</ul></section>';
  if(p.source==='missions'&&p.missions.length)html+='<section><h3>Mes missions</h3>'+table([['Mission','Récompense','Frais','Durée','Attente','Par mission','Par heure'+(g.kind==='unlock'?'':'')].concat(g.kind==='unlock'?[g.unitLabel]:[]),...p.missions.map(m=>{const a=E.activity(m);return [m.name+(m.requires.length?' (après : '+m.requires.map(id=>p.prerequisites.find(x=>x.id===id)?.name||id).join(', ')+')':''),money(m.reward),money(m.cost),hours(((m.duration||0)+(m.prep||0))/60),m.cooldown?hours(m.cooldown/60):'—',a.valid?money(a.net):'—',a.valid?money(a.hourly):'—'].concat(g.kind==='unlock'?[nf.format(m.units||0)]:[]);})],'Tes chiffres, frais payés avant, récompense à la fin',true)+'</section>';
  html+='<section><h3>Le programme, dans l’ordre</h3>'+(isFlow(r)?visual.chain(routeSteps(s,r,{all:true,max:30}),{title:'Le parcours, dans l’ordre'}):phaseCards(s,r,base)+routeBlock(s,r))+'</section>';
  if(r.purchases.length)html+='<section><h3>Mes achats et investissements</h3>'+table([['Achat','Prix','Quand','Ce qu’il rapporte ensuite'],...r.purchases.map(x=>[x.name,money(x.price),x.owned&&!x.atSession?'déjà possédé':x.atSession&&isFlow(r)?'pendant le parcours':x.atSession?'après la partie '+x.atSession+' · jour '+dayOf(x.atSession,dpw)+' (vers le '+planDate(dayOf(x.atSession,dpw),base)+')':'pas dans ce plan',x.boostHourly>0?'+'+money(x.boostHourly)+' par heure'+(Number.isFinite(x.paybackHours)?' · remboursé après '+hours(x.paybackHours)+' de jeu':''):'rien de plus'/* lot 2 (C6) : remboursement lu du moteur (null = aucun délai fini) */])],'Chaque achat se paie quand l’argent le permet, sans toucher à l’argent gardé de côté',true)+'</section>';
  if(!reached){const alt=B.planAlternatives(s,r),curId=r.variant==='auto'?'all':r.variant,ok=alt.valid?alt.plans.filter(x=>x.valid).sort((a,b)=>(a.id===curId?-1:b.id===curId?1:0)):[];if(ok.length>1)html+='<section><h3>Si ça ne se passe pas comme prévu</h3><ol class="b-sheet-alts">'+ok.slice(0,4).map((x,i)=>'<li><b>Plan '+String.fromCharCode(65+i)+' · '+esc(x.label)+'</b> : '+(isFlow(r)?hours((x.totalMinutes||0)/60)+' de jeu':plural(x.totalSessions,' partie',' parties')+', '+plural(x.days,' jour',' jours'))+', '+money(x.finalCash)+' à la fin. '+esc(programSummary(alt.results[x.id]))+'</li>').join('')+'</ol></section>';}
  if(p.log.length)html+='<section><h3>Ce que j’ai vraiment fait</h3>'+table([['Date','Joué en tout','Prévu (partie)','Réel (partie)','J’avais','Note'],...p.log.slice().reverse().map(e=>{const d=new Date(e.at);return [Number.isFinite(d.getTime())?d.toLocaleDateString('fr-FR'):'—',hours(e.minutes/60),e.plannedGain===null?'—':signed(e.plannedGain),e.gain===null?'—':signed(e.gain),money(e.capital),e.note||'—'];})],'Mes mises à jour',true)+'</section>';
  html+='<div class="b-sheet-foot"><p>Ce sont tes chiffres, pas ceux du jeu : aucun prix, gain ou mécanique de GTA VI n’est promis. Recalcule sur leonidakit.com/calculateurs.html?tool=plan.</p></div></article>';return html;}
 function shortSummary(s){const r=B.evaluate('plan',s);const name=goalName(s);if(!r.valid)return 'But : '+name+' · plan à compléter ('+r.reason+')';return 'But : '+name+' · '+(r.totalSessions===0||(r.continuous&&r.totalMinutes===0)?'déjà possible':r.continuous?timeText(r):plural(r.totalSessions,' partie',' parties')+' de '+sessionLabel(s)+' · '+plural(r.days,' jour',' jours'))+' · '+(s.plan.source==='missions'?plural(s.plan.missions.length,' mission',' missions'):money(s.plan.situation.hourly)+'/h')+(r.purchases.some(x=>x.atSession)?' · '+plural(r.purchases.filter(x=>x.atSession).length,' achat',' achats')+' d’avant':'');}
 function exportText(s,r){const p=s.plan,g=p.goal,si=p.situation;const lines=['MON BUSINESS PLAN — Leonidakit ('+new Date().toLocaleDateString('fr-FR')+')','But : '+goalName(s),'Départ : '+money(si.capital)+' en poche, '+money(si.reserve)+' de côté, parties de '+sessionLabel(s)+', '+(si.daysPerWeek??7)+' j/semaine'+(p.source==='hourly'?', '+money(si.hourly)+' par heure':', '+p.missions.length+(E.plural(p.missions.length)?' missions':' mission')),''];
  if(!r.valid){lines.push('Plan non calculable : '+r.reason);return lines.join('\n');}
  lines.push(r.totalSessions===0||(r.continuous&&r.totalMinutes===0)?'Le but est déjà possible.':r.continuous?'Parcours de '+timeText(r)+', sans calendrier. À la fin : '+money(r.finalCash)+'.'+lowText(r):r.totalSessions+' parties, '+r.days+' jours (vers le '+planDate(r.days)+'). À la fin : '+money(r.finalCash)+'.','','PROGRAMME, DANS L’ORDRE');
  if(r.continuous)(r.route||[]).slice(0,80).forEach((x,i)=>lines.push((i+1)+'. '+hours(x.start/60)+' : '+(x.type==='acquire'?'achète « '+x.name+' » (−'+money(x.spend)+')':x.type==='unlock'?'« '+x.name+' », une seule fois':'« '+x.name+' » ×'+x.runs+' (+'+money(x.receive-x.spend)+' net)')+' — tu as '+money(x.cashAfter)));
  else r.phases.forEach((ph,i)=>lines.push((i+1)+'. '+(ph.count===1?'Partie '+ph.from:'Parties '+ph.from+' à '+ph.to)+' : '+whatText(ph)+' — '+signed(ph.gain)+' par partie, de '+money(ph.cashBefore)+' à '+money(ph.cashAfter)+(ph.purchasesAfter.length?' — puis achète '+ph.purchasesAfter.join(', '):'')));
  if(r.totalSessions>0||(r.continuous&&r.totalMinutes>0))lines.push((r.continuous?'★ Après '+timeText(r):(r.phases.length+1)+'. Après la partie '+r.totalSessions)+' : '+(g.kind==='purchase'?'achète '+(g.name||'ton but'):g.kind==='unlock'?'tu débloques '+(g.name||'ton but'):'tu as '+money(g.target))+'.');
  if(p.log.length){lines.push('','SUIVI');p.log.forEach(e=>lines.push(new Date(e.at).toLocaleDateString('fr-FR')+' · joué '+hours(e.minutes/60)+' · prévu '+(e.plannedGain===null?'—':signed(e.plannedGain))+' · réel '+(e.gain===null?'—':signed(e.gain))+' · j’avais '+money(e.capital)));}
  /* v7.54 : les hypothèses du plan sont écrites dans l’export (sens du but, groupe, dépenses par partie, simulations, priorité). */
  const MEAN={held:'la somme détenue en tout',available:'la somme disponible après l’argent gardé de côté',cumulative:'la somme gagnée depuis maintenant'},PRIO={balanced:'un bon équilibre, argent de côté gardé',fast:'le plus vite possible, argent de côté utilisable',safe:'la sécurité, argent de côté jamais touché',cheap:'le moins coûteux sur tout le parcours, argent de côté gardé'};
  const hyp=['HYPOTHÈSES',g.kind==='amount'?'Avoir '+money(g.target)+', c’est : '+(MEAN[g.meaning]||MEAN.available)+'.':'But : '+(g.name||'un achat')+(g.price!==null&&g.price!==undefined?' à '+money(g.price)+' (ton prix)':''),'Priorité : '+(PRIO[p.priority]||PRIO.balanced)+'.','Nous jouons à '+(si.players??1)+(E.plural(si.players??1)?' joueurs':' joueur')+'.',(si.upkeepPerSession||0)>0?'Dépenses par partie : '+money(si.upkeepPerSession)+'.':'Aucune dépense par partie écrite.',(r.input&&r.input.ammoPerAttempt)?'Munitions simulées : '+money(r.input.ammoPerAttempt)+' par tentative (simulation, pas une donnée du jeu).':'Aucune mécanique simulée.'];
  p.prerequisites.filter(a=>!a.owned&&(a.usagePerSession||0)>0).forEach(a=>hyp.push('« '+a.name+' » coûte '+money(a.usagePerSession)+' à chaque partie (ton chiffre).'));
  if(r.input&&r.input.excludedMissions&&r.input.excludedMissions.length)hyp.push('Écartées (trop de joueurs) : '+r.input.excludedMissions.map(m=>'« '+m.name+' »').join(', ')+'.');
  if(r.note)hyp.push(r.note);
  lines.push('',...hyp,'','Ce sont tes chiffres, pas ceux du jeu. Recalculé sur leonidakit.com/calculateurs.html?tool=plan');return lines.join('\n');}
 return {markup,render,event,sheet,shortSummary,exportText,goalName,STRATEGY_LABEL};
}
global.LKCalcPlan={create};
})(window);
