/* Panneau Léo : rendu par nœuds de texte, conversation limitée à cet onglet. */
(function(){'use strict';
const C=window.LKLeoCore,L=window.LKLeoLink,launch=document.getElementById('leo-launch'),KEY='lk_leo_session_v1',TTL=30*60*1000,MAX_MESSAGES=32;
const names={capital:'J’ai déjà ($)',target:'Je veux avoir ($)',hourly:'Gain net estimé ($ / h)',price:'Prix que j’imagine ($)',reserve:'Réserve à garder ($)',minutes:'Session (min)',dailyMinutes:'Temps par jour (min)',players:'Joueurs, moi compris'};
const preferred={goal:['capital','target','hourly'],session:['minutes','capital','players'],activities:['capital','minutes','players'],purchase:['price','capital'],roi:['price','capital'],order:['capital','hourly'],budget:['capital','reserve'],plan:['capital','target','minutes']};
const el=(tag,text,cls)=>{const node=document.createElement(tag);if(text!==undefined&&text!==null)node.textContent=text;if(cls)node.className=cls;return node;};
const button=(text,cls,fn)=>{const b=el('button',text,cls);b.type='button';if(fn)b.addEventListener('click',fn);return b;};
const panel=el('dialog',null,'leo-panel');panel.id='leo-panel';panel.setAttribute('aria-labelledby','leo-title');panel.setAttribute('aria-describedby','leo-capacity');
const header=el('header',null,'leo-header'),symbol=el('span',null,'leo-symbol');symbol.setAttribute('aria-hidden','true');symbol.append(el('span','L'));const heading=el('div');const title=el('h2','Léo');title.id='leo-title';const subtitle=el('p','GTA VI, les fiches du site, tes calculs : demande-moi.');subtitle.id='leo-capacity';heading.append(title,subtitle);const closeButton=button('×','leo-close',()=>close());closeButton.setAttribute('aria-label','Fermer Léo');header.append(symbol,heading,closeButton);
const notice=el('div',null,'leo-notice'),privacy=el('p','Léo répond avec les données du site, avec des règles simples : ce n’est pas une intelligence artificielle générale, et rien n’est envoyé nulle part. La discussion reste dans cet onglet et s’efface toute seule après 30 min.');notice.append(privacy,button('Effacer','leo-clear',clear));
const log=el('div',null,'leo-log');log.setAttribute('role','region');log.setAttribute('aria-label','Échange avec Léo');log.tabIndex=0;
const live=el('p',null,'leo-sr');live.setAttribute('role','status');live.setAttribute('aria-live','polite');live.setAttribute('aria-atomic','true');
const form=el('form',null,'leo-compose'),label=el('label','Ta question pour Léo','leo-sr'),input=el('input'),send=el('button','↑','leo-send');input.id='leo-question';input.type='text';input.maxLength=C.MAX_INPUT;input.autocomplete='off';input.placeholder='Écris un nom, une question ou tes chiffres…';label.htmlFor=input.id;send.type='submit';send.setAttribute('aria-label','Envoyer la question');form.append(label,input,send);panel.append(header,notice,log,live,form);document.body.append(panel);launch.setAttribute('aria-controls',panel.id);
let core=null,dataPromise=null,messages=[],context={},resumeTo=null,draftTimer,revision=null,lastText='',lastAt=0,modal=false,scrollBefore=null,oldOverflow='',restored=false,touchedAt=Date.now(),expiryTimer;
const media=matchMedia('(max-width:600px)'),motion=matchMedia('(prefers-reduced-motion:reduce)');
function animate(node){if(motion.matches||!node.animate)return;const style=getComputedStyle(document.documentElement);node.animate([{opacity:.4,transform:media.matches||innerHeight<=480?'none':'translateY(6px)'},{opacity:1,transform:'none'}],{duration:parseFloat(style.getPropertyValue('--c-fast'))||190,easing:style.getPropertyValue('--c-ease-control').trim()||'ease-out'});}
function stop(){panel.getAnimations({subtree:true}).forEach(a=>a.cancel());}motion.addEventListener('change',stop);
const currentRoute=()=>L.safeReturn(location.pathname+(location.hash.length<160?location.hash:''))||L.safeReturn(location.pathname)||'/index.html';
function expire(){if(Date.now()-touchedAt<TTL)return;messages=[];context={};resumeTo=null;input.value='';try{sessionStorage.removeItem(KEY);}catch{}if(core&&panel.open){renderAll();live.textContent='Échange effacé après 30 minutes sans activité.';}}
function save(){if(!core)return;clearTimeout(expiryTimer);try{if(Date.now()-touchedAt>=TTL||(!messages.length&&!input.value)){expire();sessionStorage.removeItem(KEY);return;}const record={v:1,revision,at:touchedAt,messages:messages.slice(-MAX_MESSAGES),context,draft:input.value.slice(0,C.MAX_INPUT),resumeTo};sessionStorage.setItem(KEY,JSON.stringify(record));expiryTimer=setTimeout(expire,Math.max(1,TTL-(Date.now()-touchedAt)));}catch{privacy.textContent='Léo répond avec les données du site, avec des règles simples : ce n’est pas une intelligence artificielle générale, et rien n’est envoyé nulle part. Le navigateur ne peut pas garder cette discussion : elle reste sur cette page.';}}
function restore(){if(restored)return;restored=true;try{const raw=sessionStorage.getItem(KEY);if(!raw||raw.length>100000)return;const r=JSON.parse(raw);if(r.v!==1||r.revision!==revision||typeof r.at!=='number'||Date.now()-r.at<0||Date.now()-r.at>TTL||!Array.isArray(r.messages)){sessionStorage.removeItem(KEY);return;}touchedAt=r.at;messages=r.messages.slice(-MAX_MESSAGES).filter(m=>m&&((m.role==='user'&&typeof m.text==='string'&&m.text.length<=C.MAX_INPUT)||(m.role==='bot'&&m.answer&&typeof m.answer.text==='string'&&m.answer.text.length<2000)));context=r.context&&typeof r.context==='object'?r.context:{};try{context.values=L.values(context.values||{});}catch{context={};}context.selected=Array.isArray(context.selected)?context.selected.filter(k=>core.byKey.has(k)).slice(0,8):[];if(context.pending&&!['role','amount','invalid'].includes(context.pending.kind))delete context.pending;input.value=typeof r.draft==='string'?r.draft.slice(0,C.MAX_INPUT):'';resumeTo=L.safeReturn(r.resumeTo);}catch{messages=[];context={};}}
function serialize(answer){const a={...answer};if(a.results)a.results=a.results.map(x=>({key:x.key,fuzzy:x.fuzzy===true}));return a;}
function hydrate(a){const list=(key,max=8)=>Array.isArray(a[key])?a[key].slice(0,max):[];return {...a,note:typeof a.note==='string'?a.note.slice(0,1500):'',results:list('results').map(x=>x&&core.byKey.has(x.key)?{...core.byKey.get(x.key),fuzzy:x.fuzzy===true}:null).filter(Boolean),links:list('links').filter(x=>x&&typeof x.label==='string'&&x.label.length<200&&C.safeURL(x.url)),choices:list('choices').filter(x=>typeof x==='string'&&x.length<200),selected:list('selected').filter(k=>core.byKey.has(k)),following:list('following',2).filter(x=>x&&L.tools.includes(x.tool)),query:typeof a.query==='string'?a.query.slice(0,600):null,total:Number.isInteger(a.total)?Math.min(5000,a.total):0};}
function link(label,url,tool){const safe=C.safeURL(url);if(!safe)return null;const a=el('a',label);a.href=safe;a.addEventListener('click',event=>{save();if(tool&&window.LKCalculator&&location.pathname==='/calculateurs.html'&&!event.metaKey&&!event.ctrlKey){event.preventDefault();close();window.LKCalculator.openTab(tool);}});return a;}
function official(box,source,verifiedAt,status){if(status)box.append(el('p',status,'leo-proof'));const safe=C.safeSource(source);if(safe){const a=el('a','Consulter la source');a.href=safe;a.target='_blank';a.rel='noopener';a.className='leo-card-link';box.append(a);}if(typeof verifiedAt==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(verifiedAt))box.append(el('p','Vérification : '+verifiedAt.split('-').reverse().join('/'),'leo-proof'));}
function presentResult(item,parent,answer){const card=el('article',null,'leo-result'),top=el('div',null,'leo-result-top');if(typeof item.image==='string'&&/^\/(?:img|photos)\/[a-z0-9/_,.-]+\.(?:webp|svg|png)$/i.test(item.image)){const img=el('img');img.src=item.image;img.width=80;img.height=52;img.alt='';img.loading='lazy';img.addEventListener('error',()=>img.remove(),{once:true});top.append(img);}const info=el('div'),h=el('h3'),a=link(item.name,item.url);if(a)h.append(a);else h.textContent=item.name;info.append(h,el('p',item.category));top.append(info);card.append(top,el('p',item.proof,'leo-proof'));if(item.inspiration)card.append(el('p','Inspiration réelle indiquée sur la fiche : '+item.inspiration+'.','leo-proof'));if(item.fuzzy)card.append(el('p','Nom proche : vérifie que c’est bien ça.','leo-proof'));if(item.calcId)card.append(el('p',typeof item.price==='number'?'Prix connu sur la fiche : '+new Intl.NumberFormat('fr-FR').format(item.price)+' $.':'Prix pas encore connu : écris celui que tu imagines pour faire le calcul.','leo-price'));const more=el('div',null,'leo-links');const dest=link('Ouvrir la fiche',item.url);if(dest)more.append(dest);if(item.mapUrl){const map=link('Voir le repère recensé',item.mapUrl);if(map)more.append(map);}card.append(more);if(item.calcId)card.append(button(answer.forCalculation?'Choisir cette fiche':'Préparer un calcul','',()=>{const r=core.choose(item.key,answer.context||{});appendAnswer(r);input.focus({preventScroll:true});}));official(card,item.source,item.verifiedAt);parent.append(card);}
function requestBox(answer,parent,stored){let req;try{req=L.validate(answer.request);}catch{return;}const box=el('form',null,'leo-params');box.noValidate=true;const selected=el('p'),refs=(answer.selected||[]).map(k=>core.byKey.get(k)).filter(Boolean);selected.textContent=refs.length?refs.map(x=>x.name).join(' · '):'Aucune fiche du site choisie.';box.append(el('h3','Les chiffres que tu peux corriger'),selected);
 const toolLabel=el('label','Outil à ouvrir','leo-proof'),select=el('select');select.setAttribute('aria-label','Outil à ouvrir');for(const t of core.tools){const o=el('option',t.label);o.value=t.id;o.selected=t.id===req.tool;select.append(o);}box.append(toolLabel,select);
 const fields=el('div',null,'leo-fields'),extra=el('details',null,'leo-extra');extra.append(el('summary','Autres paramètres facultatifs'));const extraFields=el('div',null,'leo-fields'),preferredKeys=new Set([...(preferred[req.tool]||[]),...Object.keys(req.values)]),inputs={};
 for(const [key,name] of Object.entries(names)){const f=el('div',null,'leo-field'),lab=el('label',name),i=el('input');i.type='text';i.inputMode=key==='players'?'numeric':'decimal';i.maxLength=32;i.value=req.values[key]===undefined?'':String(req.values[key]);i.placeholder='À renseigner';i.setAttribute('aria-label',name);i.dataset.leoField=key;lab.append(i);f.append(lab);inputs[key]=i;(preferredKeys.has(key)?fields:extraFields).append(f);}extra.append(extraFields);box.append(fields,extra);const info=el('p','Une case vide n’est pas envoyée. Les nombres écrits ici sont tes chiffres à toi.','leo-proof'),error=el('p',null,'leo-error');error.setAttribute('role','status');box.append(info,error);
 const action=el('a','Ouvrir le calculateur ↗','leo-action');action.href=L.toURL({...req,back:currentRoute()});
 function collect(quiet=false){const values={},invalid=[];for(const [k,i] of Object.entries(inputs)){i.removeAttribute('aria-invalid');if(!i.value.trim())continue;const parsed=C.number(i.value);try{if(!parsed.valid)throw Error(parsed.reason);L.values({[k]:parsed.value});values[k]=parsed.value;}catch{invalid.push(i);i.setAttribute('aria-invalid','true');}}if(invalid.length){if(!quiet)error.textContent='Corrige les champs signalés. Les montants doivent être valides et la session comprise entre 1 et 1 440 min.';if(!quiet)invalid[0].focus();return null;}try{const next=L.validate({...req,tool:select.value,values,back:currentRoute()});answer.request=next;if(stored)stored.request=next;context={tool:next.tool,values,selected:answer.selected||[]};error.textContent='';return next;}catch(e){error.textContent=e.message;return null;}}
 function go(event,tool){const next=collect();if(!next){event.preventDefault();return;}if(tool)next.tool=tool;const href=L.toURL(next);event.currentTarget.href=href;resumeTo=next.back;save();if(!event.ctrlKey&&!event.metaKey&&!event.shiftKey&&event.button===0&&window.LKLeoTransfer&&location.pathname==='/calculateurs.html'){event.preventDefault();close({preserveResume:true});window.LKLeoTransfer.open(next);}}
 const actions=[action];action.addEventListener('click',event=>go(event));action.addEventListener('auxclick',event=>go(event));box.addEventListener('submit',event=>{event.preventDefault();action.click();});box.append(action);
 for(const f of answer.following||[]){if(!L.tools.includes(f.tool))continue;const a=el('a','Préparer mon temps de jeu avec ces chiffres','leo-action secondary');a.href=L.toURL({...req,tool:f.tool,back:currentRoute()});a.dataset.leoTool=f.tool;a.addEventListener('click',event=>go(event,f.tool));a.addEventListener('auxclick',event=>go(event,f.tool));actions.push(a);box.append(a);}
 function sync(){touchedAt=Date.now();const next=collect(true);for(const a of actions){if(next){a.href=L.toURL({...next,tool:a.dataset.leoTool||next.tool});a.removeAttribute('aria-disabled');}else{a.removeAttribute('href');a.setAttribute('aria-disabled','true');}}save();}box.addEventListener('input',sync);select.addEventListener('change',sync);parent.append(box);
}
function renderAnswer(a,parent,stored){parent.append(el('span','Léo','leo-role'),el('p',a.text));if(a.note)parent.append(el('p',a.note,'leo-proof'));official(parent,a.source,a.verifiedAt,a.status);if(a.links?.length){const list=el('div',null,'leo-links');for(const x of a.links){const node=link(x.label,x.url,x.tool);if(node)list.append(node);}parent.append(list);}for(const choice of a.choices||[])if(typeof choice==='string')parent.append(button(choice,'leo-choice',()=>ask(choice)));
 for(const item of a.results||[])presentResult(item,parent,a);
 if(a.total>(a.results?.length||0)&&a.query){let offset=a.results?.length||0;const more=button('Voir d’autres correspondances','leo-choice',()=>{const result=core.search(a.query,a.category,offset);for(const item of result.items)presentResult(item,parent,a);offset+=result.items.length;if(offset>=result.total||offset>=20)more.remove();else parent.append(more);});parent.append(more);}
 if(a.request)requestBox(a,parent,stored);
}
function suggestions(parent){const wrap=el('div',null,'leo-suggestions');for(const q of ['Quand sort GTA 6 ?','Sur quelles consoles ?','C’est quoi l’Édition Ultime ?','Qui sont Jason et Lucia ?','J’ai 200 000 $ et je veux 1 million','Est-ce que je peux acheter un Kamacho ?'])wrap.append(button(q,'',()=>ask(q)));parent.append(wrap);}
function renderAll(){log.replaceChildren();if(!messages.length){const intro=el('div',null,'leo-message bot');intro.append(el('span','Salut, je suis Léo','leo-role'),el('p','Pose-moi une question sur GTA VI, demande une fiche du site ou donne-moi tes chiffres pour un calcul. Essaie :'));suggestions(intro);log.append(intro);}for(const m of messages){const node=el('div',null,'leo-message '+m.role);if(m.role==='user')node.append(el('p',m.text));else renderAnswer(hydrate(m.answer),node,m.answer);log.append(node);}}
function appendAnswer(answer){touchedAt=Date.now();context=answer.context||{values:{},selected:[]};messages.push({role:'bot',answer:serialize(answer)});messages=messages.slice(-MAX_MESSAGES);renderAll();const last=log.lastElementChild;if(last){log.scrollTop=last.offsetTop-log.offsetTop;animate(last);}live.textContent=answer.text.slice(0,230)+(answer.results?.length?' '+answer.results.length+' fiches proposées.':'');save();}
function ask(text){if(!core)return;const value=String(text).trim();if(!value)return;const now=Date.now();if(lastText===value&&now-lastAt<500){live.textContent='Cette question vient déjà d’être affichée.';return;}lastText=value;lastAt=now;input.value='';messages.push({role:'user',text:value.slice(0,C.MAX_INPUT)});const pageKey=core.items.find(x=>x.url===currentRoute())?.key;const answer=core.answer(value,context,{pageKey});appendAnswer(answer);input.focus({preventScroll:true});}
form.addEventListener('submit',event=>{event.preventDefault();ask(input.value);});input.addEventListener('input',()=>{touchedAt=Date.now();clearTimeout(draftTimer);draftTimer=setTimeout(save,180);});
async function load(){if(core)return;if(dataPromise)return dataPromise;send.disabled=true;log.textContent='Chargement des réponses locales…';dataPromise=(async()=>{const response=await fetch('/leo-index.json?v=b4e2771e16e9',{credentials:'same-origin'});if(!response.ok)throw Error('Fichier local indisponible.');if(+response.headers.get('content-length')>1500000)throw Error('Index local trop volumineux.');const text=await response.text();if(text.length>1500000)throw Error('Index local trop volumineux.');const data=JSON.parse(text);core=C.create(data);revision=data.revision;restore();renderAll();})();try{await dataPromise;}catch{log.replaceChildren(el('p','Les réponses locales de Léo n’ont pas pu être chargées. Le site et le calculateur restent utilisables.'),button('Réessayer','leo-choice',()=>{dataPromise=null;load();}));const a=link('Ouvrir le calculateur','/calculateurs.html');if(a)log.append(a);live.textContent='Réponses locales indisponibles.';}finally{send.disabled=!core;}}
function viewport(){if(!panel.open)return;const v=window.visualViewport;panel.style.setProperty('--leo-vtop',(v?.offsetTop||0)+'px');panel.style.setProperty('--leo-vheight',(v?.height||innerHeight)+'px');}
function open(){if(panel.open)return;expire();modal=media.matches;if(modal){scrollBefore={x:scrollX,y:scrollY};oldOverflow=document.documentElement.style.overflow;document.documentElement.style.overflow='hidden';panel.showModal();panel.setAttribute('aria-modal','true');launch.hidden=true;}else{panel.show();panel.setAttribute('aria-modal','false');}launch.setAttribute('aria-expanded','true');viewport();load();input.focus({preventScroll:true});animate(panel);}
function close(options={}){if(!panel.open)return;stop();panel.close();if(modal){document.documentElement.style.overflow=oldOverflow;if(scrollBefore)scrollTo({left:scrollBefore.x,top:scrollBefore.y,behavior:'instant'});}if(!options.preserveResume)resumeTo=null;launch.hidden=false;launch.setAttribute('aria-expanded','false');save();launch.focus({preventScroll:true});window.LKLeoLoader.place();}
function clear(){clearTimeout(expiryTimer);messages=[];context={};resumeTo=null;input.value='';try{sessionStorage.removeItem(KEY);}catch{}if(core)renderAll();live.textContent='Conversation effacée dans cet onglet.';input.focus();}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&panel.open&&!modal&&!document.querySelector('dialog:modal')){e.preventDefault();close();}});
panel.addEventListener('cancel',e=>{e.preventDefault();close();});panel.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal){e.preventDefault();close();}});media.addEventListener('change',()=>{if(panel.open){close({preserveResume:true});open();}});window.visualViewport?.addEventListener('resize',viewport);window.visualViewport?.addEventListener('scroll',viewport);window.addEventListener('resize',viewport);window.addEventListener('pagehide',save);
window.LKLeoUI={open,close,isOpen:()=>panel.open,clear};
})();
