/* Petit amorçage : aucun index, moteur ou média de Léo avant une ouverture. */
(function(){'use strict';if(document.getElementById('leo-launch')||!document.querySelector('main'))return;
const button=document.createElement('button');button.id='leo-launch';button.type='button';button.setAttribute('aria-label','Ouvrir Léo, assistant LeonidaKit');button.setAttribute('aria-haspopup','dialog');button.setAttribute('aria-expanded','false');button.innerHTML='<span class="leo-symbol" aria-hidden="true"><span>L</span></span><span>Léo</span>';document.body.append(button);
const href=name=>'/'+name+'?v=4b29a8531a70';let loading=null,frame=0;
function script(name,global){if(window[global])return Promise.resolve();return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=href(name);s.onload=()=>window[global]?resolve():reject(Error('Module local indisponible.'));s.onerror=()=>{s.remove();reject(Error('Un fichier local de Léo n’a pas pu être chargé.'));};document.head.append(s);});}
async function open(){if(window.LKLeoUI){window.LKLeoUI.open();return;}if(loading)return;button.disabled=true;button.setAttribute('aria-busy','true');const label=button.lastElementChild;label.textContent='Ouverture';loading=(async()=>{await Promise.all([script('calculateurs-engine.js','LKCalcEngine'),script('leo-link.js','LKLeoLink')]);await script('leo-core.js','LKLeoCore');await script('leo-ui.js','LKLeoUI');window.LKLeoUI.open();})();try{await loading;}catch(e){window.LK?.status(e.message+' Tu peux continuer à utiliser le site et réessayer.');}finally{loading=null;button.disabled=false;button.removeAttribute('aria-busy');label.textContent='Léo';}}
button.addEventListener('click',()=>window.LKLeoUI?.isOpen()?window.LKLeoUI.close():open());
function place(){frame=0;if(window.LKLeoUI?.isOpen())return;const modal=document.querySelector('dialog[open]'),burger=document.getElementById('burger');button.hidden=!!modal||burger?.getAttribute('aria-expanded')==='true';if(button.hidden||document.activeElement===button)return;const w=button.offsetWidth,h=button.offsetHeight,small=innerWidth<600,edge=small?12:18,originalBottom=edge+(parseFloat(getComputedStyle(button).getPropertyValue('--leo-safe'))||0);let chosen=null;
 const blocked=(left,top)=>[[left+5,top+5],[left+w-5,top+5],[left+5,top+h-5],[left+w-5,top+h-5],[left+w/2,top+h/2]].some(([x,y])=>document.elementsFromPoint(x,y).some(el=>!button.contains(el)&&el!==button&&el.closest('button,input,select,textarea,a,summary,.cmp-tray.on,#lk-status:not(:empty),[role="slider"]')));
 search:for(const bottom of [originalBottom,originalBottom+70,originalBottom+140])for(const side of ['right','left']){const left=side==='right'?innerWidth-edge-w:edge,top=innerHeight-bottom-h;if(top>120&&!blocked(left,top)){chosen={side,bottom};break search;}}
 button.style.left=chosen?.side==='left'?edge+'px':'auto';button.style.right=chosen?.side==='left'?'auto':edge+'px';button.style.bottom='calc('+(chosen?.bottom??originalBottom)+'px + env(safe-area-inset-bottom,0px))';}
const schedule=()=>{if(!frame)frame=requestAnimationFrame(place);};window.addEventListener('scroll',schedule,{passive:true});window.addEventListener('resize',schedule);document.addEventListener('click',schedule);document.addEventListener('keydown',schedule);const menu=document.getElementById('burger');if(menu)new MutationObserver(schedule).observe(menu,{attributes:true,attributeFilter:['aria-expanded']});document.addEventListener('close',schedule,true);window.addEventListener('pageshow',schedule);schedule();
window.LKLeoLoader={open,place:schedule};
try{const raw=sessionStorage.getItem('lk_leo_session_v1');if(raw&&raw.length<100000){const r=JSON.parse(raw);if(r.resumeTo===location.pathname+location.hash&&r.at<=Date.now()&&Date.now()-r.at<1800000)open();}}catch{}
})();
