/* Panneau Léo v2 (v7.45, lot 8) : rendu par nœuds de texte, conversation limitée à cet onglet, réponse qui s'affiche
   progressivement (lisible, ≤ 320 ms, rien en mouvement réduit), suggestions selon la page, puces « Tu voulais dire… ? »,
   sources cliquables, « Signaler une mauvaise réponse » (page Contact préremplie), mention locale. Le noyau leo-index.json
   est chargé à l'ouverture ; les morceaux leo/*.json seulement quand une question les vise. */
(function(){'use strict';
/* v7.61 : l'index est celui de la langue de la page (/es/leo-index.json sur une page espagnole) : dossier de ce script */
const LEO_BASE=(document.currentScript&&document.currentScript.src||'').replace(/^https?:\/\/[^/]+/,'').replace(/[^/]*$/,'')||'/';
const LANG_UI=(document.documentElement.lang||'fr').slice(0,2).toLowerCase(),C=window.LKLeoCore,L=window.LKLeoLink,launch=document.getElementById('leo-launch'),KEY='lk_leo_session_v2',TTL=30*60*1000,MAX_MESSAGES=32,V='?v=9d8394d2ec4c',MAX_BYTES=1500000;
const names={capital:'J’ai déjà ($)',target:'Je veux avoir ($)',hourly:'Gain net estimé ($ / h)',price:'Prix que j’imagine ($)',reserve:'Réserve à garder ($)',minutes:'Session (min)',dailyMinutes:'Temps par jour (min)',players:'Joueurs, moi compris'};
const preferred={goal:['capital','target','hourly'],session:['minutes','capital','players'],activities:['capital','minutes','players'],purchase:['price','capital'],roi:['price','capital'],order:['capital','hourly'],budget:['capital','reserve'],plan:['capital','target','minutes']};
const el=(tag,text,cls)=>{const node=document.createElement(tag);if(text!==undefined&&text!==null)node.textContent=text;if(cls)node.className=cls;return node;};
const button=(text,cls,fn)=>{const b=el('button',text,cls);b.type='button';if(fn)b.addEventListener('click',fn);return b;};
/* v7.45 : les morceaux de l'index que vise une question sont préparés pendant la frappe, au survol ou au focus d'une suggestion : la réponse est prête à l'envoi. Ce sont des fichiers du site ; rien ne part du navigateur. */
/* famille de la page ouverte → morceau de l'index à préparer à l'ouverture */
function pageShard(path){if(/^\/(?:calculateurs|tuto)\.html$/.test(path))return 'calculateur';if(/^\/(?:vehicules\/|vehicules\.html|vehicules-rares\.html|classement-vehicules\.html|comparateur\.html|bateaux\.html)/.test(path))return 'vehicules';if(/^\/(?:armes\/|armes\.html|munitions\.html)/.test(path))return 'armes';if(/^\/(?:lieux|personnages|entreprises|demeures|planques|gangs)(?:\/|\.html)/.test(path))return 'monde';if(/^\/carte\.html/.test(path))return 'lieux';if(/^\/(?:nourriture|style|personnalisations|tatouages|vetements|accessoires)\.html/.test(path))return 'catalogues';if(/^\/missions(?:\/|\.html)/.test(path))return 'missions';/* section missions */if(/^\/activites(?:\/|\.html)/.test(path))return 'activites';/* section activites */if(/^\/radios(?:\/|\.html)/.test(path))return 'radios';/* section radios */if(/^\/animaux(?:\/|\.html)/.test(path))return 'animaux';/* section animaux */if(/^\/codes-de-triche(?:\/|\.html)/.test(path))return 'codes';/* section codes */if(/^\/trophees(?:\/|\.html)/.test(path))return 'trophees';/* section trophees */if(/^\/online(?:\/|\.html)/.test(path))return 'online';/* section online */return null;}
let pageReady=null;
function preload(text){if(!core)return;let list=[];try{list=core.needs(String(text).slice(0,C.MAX_INPUT));}catch{list=[];}for(const n of list)core.loadShard(n).catch(()=>{});}
const questionButton=(q,cls)=>{const b=button(q,cls,()=>ask(q));const warm=()=>preload(q);for(const ev of ['pointerenter','focus','touchstart'])b.addEventListener(ev,warm,{once:true,passive:true});return b;};
const panel=el('dialog',null,'leo-panel');panel.id='leo-panel';panel.setAttribute('aria-labelledby','leo-title');panel.setAttribute('aria-describedby','leo-capacity');
const header=el('header',null,'leo-header'),symbol=el('span',null,'leo-symbol');symbol.setAttribute('aria-hidden','true');symbol.append(el('span','L'));const heading=el('div');const title=el('h2','Léo');title.id='leo-title';const subtitle=el('p','GTA VI, les fiches du site, tes calculs : demande-moi.');subtitle.id='leo-capacity';heading.append(title,subtitle);const closeButton=button('×','leo-close',()=>close());closeButton.setAttribute('aria-label','Fermer Léo');header.append(symbol,heading,closeButton);
const notice=el('div',null,'leo-notice'),privacy=el('p');const privacyText=el('span','Léo répond depuis ton navigateur, rien n’est envoyé. La discussion reste dans cet onglet et s’efface après 30 min. ');const privacyLink=el('a','Mentions et confidentialité');privacyLink.href='/mentions-legales.html#confidentialite';privacy.append(privacyText,privacyLink);notice.append(privacy,button('Effacer','leo-clear',clear));
const log=el('div',null,'leo-log');log.setAttribute('role','region');log.setAttribute('aria-label','Échange avec Léo');log.tabIndex=0;
const live=el('p',null,'leo-sr');live.setAttribute('role','status');live.setAttribute('aria-live','polite');live.setAttribute('aria-atomic','true');
const form=el('form',null,'leo-compose'),label=el('label','Ta question pour Léo','leo-sr'),input=el('input'),send=el('button','↑','leo-send');input.id='leo-question';input.type='text';input.maxLength=C.MAX_INPUT;input.autocomplete='off';input.placeholder='Écris un nom, une question ou tes chiffres…';label.htmlFor=input.id;send.type='submit';send.setAttribute('aria-label','Envoyer la question');form.append(label,input,send);panel.append(header,notice,log,live,form);document.body.append(panel);
/* v7.69 : « Qui répond ? » (IA Claude ou local) et la phrase de confidentialité qui suit ce choix */
const PRIV_LOCAL='Léo répond depuis ton navigateur, rien n’est envoyé. La discussion reste dans cet onglet et s’efface après 30 min. ',PRIV_IA='Avec l’IA Claude, ta question et des extraits du site partent vers Anthropic pour la réponse ; le site ne les garde pas. La discussion reste dans cet onglet et s’efface après 30 min. ';
function privacyPaint(){const v=window.LKIA&&window.LKIA.usable()?PRIV_IA:PRIV_LOCAL;if(privacyText.textContent!==v)privacyText.textContent=v;}
if(window.LKIA){notice.after(window.LKIA.control('leo'));window.LKIA.subscribe(privacyPaint);}privacyPaint();launch.setAttribute('aria-controls',panel.id);
let core=null,dataPromise=null,messages=[],context={},resumeTo=null,draftTimer,revision=null,lastText='',lastAt=0,modal=false,scrollBefore=null,oldOverflow='',restored=false,touchedAt=Date.now(),expiryTimer,busy=false,typing=null;
const media=matchMedia('(max-width:600px)'),motion=matchMedia('(prefers-reduced-motion:reduce)');
function animate(node){if(motion.matches||!node.animate)return;const style=getComputedStyle(document.documentElement);node.animate([{opacity:.4,transform:media.matches||innerHeight<=480?'none':'translateY(6px)'},{opacity:1,transform:'none'}],{duration:parseFloat(style.getPropertyValue('--c-fast'))||190,easing:style.getPropertyValue('--c-ease-control').trim()||'ease-out'});}
function stop(){panel.getAnimations({subtree:true}).forEach(a=>a.cancel());if(typing){cancelAnimationFrame(typing.frame);typing.finish();typing=null;}}motion.addEventListener('change',stop);
const currentRoute=()=>L.safeReturn(location.pathname+(location.hash.length<160?location.hash:''))||L.safeReturn(location.pathname)||'/index.html';
const pageName=()=>{const h=document.querySelector('main h1');return h?h.textContent.replace(/\s+/g,' ').trim().slice(0,80):null;};
/* Réponse qui se compose mot à mot : ≤ 320 ms au total, texte complet tout de suite pour le lecteur d'écran et en mouvement réduit. */
function typeInto(p,text){p.textContent='';if(motion.matches||!text||text.length<40){p.textContent=text;return;}const words=text.split(/(\s+)/),total=Math.min(320,Math.max(120,words.length*14)),start=performance.now();let i=0;const finish=()=>{p.textContent=text;p.classList.remove('is-typing');typing=null;};p.classList.add('is-typing');
 const step=now=>{const share=Math.min(1,(now-start)/total),target=Math.floor(share*words.length);while(i<target){p.append(document.createTextNode(words[i]));i++;}if(share>=1)finish();else typing.frame=requestAnimationFrame(step);};typing={frame:requestAnimationFrame(step),finish};}
function expire(){if(Date.now()-touchedAt<TTL)return;messages=[];context={};resumeTo=null;input.value='';try{sessionStorage.removeItem(KEY);}catch{}if(core&&panel.open){renderAll();live.textContent='Échange effacé après 30 minutes sans activité.';}}
function save(){if(!core)return;clearTimeout(expiryTimer);try{if(Date.now()-touchedAt>=TTL||(!messages.length&&!input.value)){expire();sessionStorage.removeItem(KEY);return;}const record={v:2,lang:LANG_UI,revision,at:touchedAt,messages:messages.slice(-MAX_MESSAGES),context,draft:input.value.slice(0,C.MAX_INPUT),resumeTo};sessionStorage.setItem(KEY,JSON.stringify(record));expiryTimer=setTimeout(expire,Math.max(1,TTL-(Date.now()-touchedAt)));}catch{privacyText.textContent='Léo répond depuis ton navigateur, rien n’est envoyé. Le navigateur ne peut pas garder cette discussion : elle reste sur cette page. ';}}
function restore(){if(restored)return;restored=true;try{const raw=sessionStorage.getItem(KEY);if(!raw||raw.length>100000)return;const r=JSON.parse(raw);if(r.v!==2||(r.lang||'fr')!==LANG_UI||r.revision!==revision||typeof r.at!=='number'||Date.now()-r.at<0||Date.now()-r.at>TTL||!Array.isArray(r.messages)){sessionStorage.removeItem(KEY);return;}touchedAt=r.at;messages=r.messages.slice(-MAX_MESSAGES).filter(m=>m&&((m.role==='user'&&typeof m.text==='string'&&m.text.length<=C.MAX_INPUT)||(m.role==='bot'&&m.answer&&typeof m.answer.text==='string'&&m.answer.text.length<2000)));context=r.context&&typeof r.context==='object'?r.context:{};try{context.values=L.values(context.values||{});}catch{context={};}context.selected=Array.isArray(context.selected)?context.selected.filter(k=>core.byKey.has(k)).slice(0,8):[];if(context.pending&&!['role','amount','invalid'].includes(context.pending.kind))delete context.pending;if(!Array.isArray(context.recent))context.recent=[];input.value=typeof r.draft==='string'?r.draft.slice(0,C.MAX_INPUT):'';resumeTo=L.safeReturn(r.resumeTo);}catch{messages=[];context={};}}
function serialize(answer){const a={...answer};if(a.results)a.results=a.results.map(x=>({key:x.key,fuzzy:x.fuzzy===true}));delete a.context;return a;}
function hydrate(a){const list=(key,max=8)=>Array.isArray(a[key])?a[key].slice(0,max):[];const ext=list('external',3).filter(x=>x&&typeof x.label==='string'&&x.label.length<200&&C.safeSource(x.url));return {...a,note:typeof a.note==='string'?a.note.slice(0,1500):'',results:list('results').map(x=>x&&core.byKey.has(x.key)?{...core.byKey.get(x.key),fuzzy:x.fuzzy===true}:null).filter(Boolean),links:list('links').filter(x=>x&&typeof x.label==='string'&&x.label.length<200&&C.safeURL(x.url)),external:ext,choices:list('choices').filter(x=>typeof x==='string'&&x.length<200),selected:list('selected').filter(k=>core.byKey.has(k)),following:list('following',2).filter(x=>x&&L.tools.includes(x.tool)),query:typeof a.query==='string'?a.query.slice(0,600):null,total:Number.isInteger(a.total)?Math.min(5000,a.total):0,passage:a.passage&&typeof a.passage.text==='string'&&C.safeURL(a.passage.url)?{title:String(a.passage.title||'').slice(0,160),heading:String(a.passage.heading||'').slice(0,160),text:a.passage.text.slice(0,700),url:a.passage.url}:null,action:a.action&&C.safeURL(a.action.url)?a.action:null,report:typeof a.report==='string'&&/^\/contact\.html#motif=leo&/.test(a.report)&&a.report.length<1600?a.report:null};}
function link(label,url,tool){const safe=C.safeURL(url);if(!safe)return null;const a=el('a',label);a.href=safe;a.addEventListener('click',event=>{save();if(tool&&window.LKCalculator&&location.pathname==='/calculateurs.html'&&!event.metaKey&&!event.ctrlKey){event.preventDefault();close();window.LKCalculator.openTab(tool);}});return a;}
function official(box,source,verifiedAt,status){if(status)box.append(el('p',status,'leo-proof'));const safe=C.safeSource(source);if(safe){const a=el('a','Consulter la source');a.href=safe;a.target='_blank';a.rel='noopener';a.className='leo-card-link';box.append(a);}if(typeof verifiedAt==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(verifiedAt))box.append(el('p','Vérification : '+(LANG_UI==='fr'?verifiedAt.split('-').reverse().join('/'):new Intl.DateTimeFormat(document.documentElement.lang||LANG_UI,{dateStyle:'long',timeZone:'UTC'}).format(new Date(verifiedAt+'T00:00:00Z'))),'leo-proof'));}
function externalLinks(parent,list){if(!list?.length)return;const wrap=el('div',null,'leo-links leo-external');for(const x of list){const safe=C.safeSource(x.url);if(!safe)continue;const a=el('a',x.label+' ↗');a.href=safe;a.target='_blank';a.rel='noopener';wrap.append(a);}if(wrap.children.length)parent.append(wrap);}
function presentResult(item,parent,answer){const card=el('article',null,'leo-result'),top=el('div',null,'leo-result-top');if(typeof item.image==='string'&&/^\/(?:img|photos)\/[a-z0-9/_,.-]+\.(?:webp|svg|png)$/i.test(item.image)){const img=el('img');img.src=item.image;img.width=80;img.height=52;img.alt='';img.loading='lazy';img.addEventListener('error',()=>img.remove(),{once:true});top.append(img);}const info=el('div'),h=el('h3'),a=link(item.name,item.url);if(a)h.append(a);else h.textContent=item.name;info.append(h,el('p',item.category));top.append(info);card.append(top,el('p',item.proof,'leo-proof'));if(item.inspiration)card.append(el('p','Inspiration réelle indiquée sur la fiche : '+item.inspiration+'.','leo-proof'));if(item.fuzzy)card.append(el('p','Nom proche : vérifie que c’est bien ça.','leo-proof'));if(item.calcId)card.append(el('p',typeof item.price==='number'?'Prix connu sur la fiche : '+window.LKCalcEngine.dollars(new Intl.NumberFormat('fr-FR').format(item.price))+'.':'Prix pas encore connu : écris celui que tu imagines pour faire le calcul.','leo-price'));const more=el('div',null,'leo-links');const dest=link('Ouvrir la fiche',item.url);if(dest)more.append(dest);if(item.mapUrl){const map=link('Voir le repère recensé',item.mapUrl);if(map)more.append(map);}card.append(more);if(item.calcId)card.append(button(answer.forCalculation?'Choisir cette fiche':'Préparer un calcul','',()=>{const r=core.choose(item.key,answer.context||context||{});appendAnswer(r,'');input.focus({preventScroll:true});}));official(card,item.source,item.verifiedAt);parent.append(card);}
function requestBox(answer,parent,stored){let req;try{req=L.validate(answer.request);}catch{return;}const box=el('form',null,'leo-params');box.noValidate=true;const selected=el('p'),refs=(answer.selected||[]).map(k=>core.byKey.get(k)).filter(Boolean);selected.textContent=refs.length?refs.map(x=>x.name).join(' · '):'Aucune fiche du site choisie.';box.append(el('h3','Les chiffres que tu peux corriger'),selected);
 const toolLabel=el('label','Outil à ouvrir','leo-proof'),select=el('select');select.setAttribute('aria-label','Outil à ouvrir');for(const t of core.tools){const o=el('option',t.label);o.value=t.id;o.selected=t.id===req.tool;select.append(o);}box.append(toolLabel,select);
 const fields=el('div',null,'leo-fields'),extra=el('details',null,'leo-extra');extra.append(el('summary','Autres paramètres facultatifs'));const extraFields=el('div',null,'leo-fields'),preferredKeys=new Set([...(preferred[req.tool]||[]),...Object.keys(req.values)]),inputs={};
 for(const [key,name] of Object.entries(names)){const f=el('div',null,'leo-field'),lab=el('label',name),i=el('input');i.type='text';i.inputMode=key==='players'?'numeric':'decimal';i.maxLength=32;i.value=req.values[key]===undefined?'':String(req.values[key]);i.placeholder='À renseigner';i.setAttribute('aria-label',name);i.dataset.leoField=key;lab.append(i);f.append(lab);inputs[key]=i;(preferredKeys.has(key)?fields:extraFields).append(f);}extra.append(extraFields);box.append(fields,extra);const info=el('p','Une case vide n’est pas envoyée. Les nombres écrits ici sont tes chiffres à toi.','leo-proof'),error=el('p',null,'leo-error');error.setAttribute('role','status');box.append(info,error);
 const action=el('a','Ouvrir le calculateur ↗','leo-action');action.href=L.toURL({...req,back:currentRoute()});
 function collect(quiet=false){const values={},invalid=[];for(const [k,i] of Object.entries(inputs)){i.removeAttribute('aria-invalid');if(!i.value.trim())continue;const parsed=C.number(i.value);try{if(!parsed.valid)throw Error(parsed.reason);L.values({[k]:parsed.value});values[k]=parsed.value;}catch{invalid.push(i);i.setAttribute('aria-invalid','true');}}if(invalid.length){if(!quiet)error.textContent='Corrige les champs signalés. Les montants doivent être valides et la session comprise entre 1 et 1 440 min.';if(!quiet)invalid[0].focus();return null;}try{const next=L.validate({...req,tool:select.value,values,back:currentRoute()});answer.request=next;if(stored)stored.request=next;context={...context,tool:next.tool,values,selected:answer.selected||[]};error.textContent='';return next;}catch(e){error.textContent=e.message;return null;}}
 function go(event,tool){const next=collect();if(!next){event.preventDefault();return;}if(tool)next.tool=tool;const href=L.toURL(next);event.currentTarget.href=href;resumeTo=next.back;save();if(!event.ctrlKey&&!event.metaKey&&!event.shiftKey&&event.button===0&&window.LKLeoTransfer&&location.pathname==='/calculateurs.html'){event.preventDefault();close({preserveResume:true});window.LKLeoTransfer.open(next);}}
 const actions=[action];action.addEventListener('click',event=>go(event));action.addEventListener('auxclick',event=>go(event));box.addEventListener('submit',event=>{event.preventDefault();action.click();});box.append(action);
 for(const f of answer.following||[]){if(!L.tools.includes(f.tool))continue;const a=el('a','Préparer mon temps de jeu avec ces chiffres','leo-action secondary');a.href=L.toURL({...req,tool:f.tool,back:currentRoute()});a.dataset.leoTool=f.tool;a.addEventListener('click',event=>go(event,f.tool));a.addEventListener('auxclick',event=>go(event,f.tool));actions.push(a);box.append(a);}
 function sync(){touchedAt=Date.now();const next=collect(true);for(const a of actions){if(next){a.href=L.toURL({...next,tool:a.dataset.leoTool||next.tool});a.removeAttribute('aria-disabled');}else{a.removeAttribute('href');a.setAttribute('aria-disabled','true');}}save();}box.addEventListener('input',sync);select.addEventListener('change',sync);parent.append(box);
}
function renderAnswer(a,parent,stored,fresh){parent.append(el('span','Léo','leo-role'));const p=el('p');if(fresh)typeInto(p,a.text);else p.textContent=a.text;parent.append(p);
 if(a.passage){const quote=el('blockquote',null,'leo-passage');if(a.passage.heading&&a.passage.heading!==a.passage.title)quote.append(el('strong',a.passage.heading));quote.append(el('p',a.passage.text));parent.append(quote);}
 if(a.note)parent.append(el('p',a.note,'leo-proof'));if(a.by==='local')parent.append(el('p',typeof a.byNote==='string'&&a.byNote?a.byNote.slice(0,240):'Réponse locale de Léo, sans IA.','leo-proof leo-by'));official(parent,a.source,a.verifiedAt,a.status);
 if(a.action&&a.action.url&&!(a.links||[]).some(x=>x.url===a.action.url)){const act=link(a.action.type==='map'?'Ouvrir la carte sur ce repère ↗':a.action.type==='tool'?'Ouvrir l’outil ↗':'Ouvrir la page ↗',a.action.url,a.action.tool);if(act){act.className='leo-action secondary';parent.append(act);}}
 if(a.links?.length){const list=el('div',null,'leo-links');for(const x of a.links){const node=link(x.label,x.url,x.tool);if(node)list.append(node);}parent.append(list);}
 externalLinks(parent,a.external);
 for(const choice of a.choices||[])if(typeof choice==='string')parent.append(questionButton(choice,'leo-choice'));
 for(const item of a.results||[])presentResult(item,parent,a);
 if(a.total>(a.results?.length||0)&&a.query){let offset=a.results?.length||0;const more=button('Voir d’autres correspondances','leo-choice',()=>{const result=core.search(a.query,a.category,offset);for(const item of result.items)presentResult(item,parent,a);offset+=result.items.length;if(offset>=result.total||offset>=20)more.remove();else parent.append(more);});parent.append(more);}
 if(a.request)requestBox(a,parent,stored);
 if(['answer','results','unknown','calc','choices'].includes(a.kind)&&a.text){const foot=el('div',null,'leo-foot');
  /* v7.58 (LEO-02h) : copier la réponse (texte, statut, liens absolus, source) ; presse-papiers moderne, sinon sélection + execCommand */
  const copyText=()=>{const lines=[a.text];if(a.status)lines.push('Statut : '+a.status);for(const x of a.links||[])if(x.url)lines.push(x.label+' : '+new URL(x.url,location.origin).href);if(a.source)lines.push('Source : '+a.source);for(const x of a.external||[])if(x.url)lines.push(x.label+' : '+x.url);lines.push('— Léo, '+location.origin.replace(/^https?:\/\//,''));return lines.join('\n');};
  const copy=button('Copier la réponse','leo-copy',async()=>{const text=copyText();let ok=false;try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text);ok=true;}}catch{ok=false;}
   if(!ok){try{const ta=document.createElement('textarea');ta.value=text;ta.setAttribute('readonly','');ta.style.cssText='position:fixed;left:-9999px;top:0;opacity:0';document.body.append(ta);ta.select();ok=document.execCommand('copy');ta.remove();}catch{ok=false;}}
   copy.textContent=ok?'Réponse copiée ✓':'Copie impossible ici';copy.classList.toggle('is-done',ok);live.textContent=ok?'Réponse copiée dans le presse-papiers.':'La copie n’est pas disponible dans ce navigateur : sélectionne le texte.';setTimeout(()=>{copy.textContent='Copier la réponse';copy.classList.remove('is-done');},1800);});
  copy.setAttribute('aria-label','Copier cette réponse de Léo');foot.append(copy);
  if(a.report&&['answer','results','unknown','refusal','calc','choices'].includes(a.kind)){const r=el('a','Signaler une mauvaise réponse','leo-report');r.href=a.report;foot.append(r);}
  parent.append(foot);}
 else if(a.report&&['answer','results','unknown','refusal','calc','choices'].includes(a.kind)){const r=el('a','Signaler une mauvaise réponse','leo-report');r.href=a.report;parent.append(r);}
}
function suggestions(parent){const wrap=el('div',null,'leo-suggestions');let list=[];try{list=core.suggest({path:location.pathname,name:pageName()});}catch{list=[];}for(const q of list.slice(0,6))wrap.append(questionButton(q,''));parent.append(wrap);}
function renderAll(fresh=false){stop();log.replaceChildren();if(!messages.length){const intro=el('div',null,'leo-message bot');intro.append(el('span','Salut, je suis Léo','leo-role'),el('p','Pose-moi une question sur GTA VI, demande une fiche du site ou donne-moi tes chiffres pour un calcul. Essaie :'));suggestions(intro);log.append(intro);}messages.forEach((m,i)=>{const node=el('div',null,'leo-message '+m.role);if(m.role==='user')node.append(el('p',m.text));else renderAnswer(hydrate(m.answer),node,m.answer,fresh&&i===messages.length-1);log.append(node);});}
function appendAnswer(answer,question){touchedAt=Date.now();const ctx=answer.context||{values:{},selected:[]};if(!Array.isArray(ctx.recent))ctx.recent=Array.isArray(context.recent)?context.recent:[];context=ctx;const stored=serialize(answer);if(!stored.report&&question)stored.report=core.reportLink(question,answer.text,currentRoute());messages.push({role:'bot',answer:stored});messages=messages.slice(-MAX_MESSAGES);renderAll(true);const last=log.lastElementChild;if(last){log.scrollTop=last.offsetTop-log.offsetTop;animate(last);}live.textContent=answer.text.slice(0,230)+(answer.results?.length?' '+answer.results.length+' fiches proposées.':'')+(answer.choices?.length&&answer.kind==='choices'?' '+answer.choices.join(' ; '):'');save();}
/* v7.67 : IA de Léo (API Claude, par la fonction /api/ia du site). Elle rédige la réponse à partir de la réponse locale et
   des extraits des pages les plus proches ; elle ne cite que leurs liens ou le site officiel de Rockstar. Sans clé, hors
   ligne, trop lente (15 s) ou en cas d’erreur : la réponse locale reste, comme avant. Navigation, calculs et listes restent
   locaux (actions immédiates, aucun coût). */
const IA_OFF='lk_ia_off',IA_KINDS=['answer','unknown','place','character'];
function iaOn(){try{return sessionStorage.getItem(IA_OFF)!=='1';}catch{return true;}}
/* v7.69 : le visiteur choisit qui répond (lk-ia.js : « IA Claude » ou « Local ») et voit toujours lequel a répondu ;
   30 questions IA gratuites par 9 heures, puis mode local (ou crédit, si la vente est ouverte). */
function localNote(){const A=window.LKIA;if(!A)return 'Réponse locale de Léo, sans IA.';const st=A.status();return st.kind==='quota'||st.kind==='off'?st.text:A.mode()==='local'?'Réponse locale de Léo, sans IA (mode local choisi).':'Réponse locale de Léo, sans IA.';}
async function withAI(question,local){if(!local||!IA_KINDS.includes(local.kind)||typeof fetch!=='function'||typeof core.evidence!=='function')return local;
 const A=window.LKIA;if(A?!A.usable():!iaOn())return {...local,by:'local',byNote:localNote()};
 let passages=[];try{passages=await core.evidence(question,5);}catch{passages=[];}
 const history=[];for(let i=messages.length-2;i>=0&&history.length<2;i--){const m=messages[i];if(m&&m.role==='user'){const b=messages[i+1];history.unshift({q:m.text,r:(b&&b.answer&&b.answer.text)||''});}}
 const pending={role:'bot',answer:{kind:'pending',text:'Léo rédige sa réponse…'}};messages.push(pending);renderAll();live.textContent='Léo rédige sa réponse…';
 const ctl=typeof AbortController==='function'?new AbortController():null,timer=setTimeout(()=>ctl&&ctl.abort(),15000);
 const payload={mode:'leo',question,lang:(document.documentElement.lang||'fr').slice(0,2),page:currentRoute(),local:{text:local.text||'',links:(local.links||[]).slice(0,6)},passages,history};
 try{const r=await fetch('/api/ia',{method:'POST',headers:{'Content-Type':'application/json'},signal:ctl?ctl.signal:undefined,body:JSON.stringify(A?A.body(payload):payload)});
  let j=null;try{j=await r.json();}catch{j=null;}
  if(A)A.learn(r.status,j);
  if(r.status===503||r.status===404||r.status===405){try{sessionStorage.setItem(IA_OFF,'1');}catch{}return {...local,by:'local',byNote:localNote()};}
  if(!r.ok)return {...local,by:'local',byNote:localNote()};if(!j||!j.ok||!j.trouve||typeof j.reponse!=='string'||!j.reponse.trim())return {...local,by:'local',byNote:localNote()};
  const inside=(j.liens||[]).filter(l=>l&&typeof l.url==='string'&&l.url.startsWith('/')).map(l=>({label:l.titre,url:l.url})),outside=(j.liens||[]).filter(l=>l&&typeof l.url==='string'&&/^https:\/\/www\.rockstargames\.com\//.test(l.url)).map(l=>({label:l.titre,url:l.url}));
  return {...local,kind:'answer',by:'ia',text:j.reponse.trim(),links:inside,external:[...outside,...(local.external||[])].slice(0,3),passage:null,note:'Réponse rédigée par une IA (Claude) à partir des pages de Leonidakit.',choices:[],request:null,results:[],total:0,status:null,source:null,verifiedAt:null};
 }catch{return {...local,by:'local',byNote:localNote()};}finally{clearTimeout(timer);const i=messages.indexOf(pending);if(i>=0)messages.splice(i,1);}}
async function ask(text){if(!core||busy)return;const value=String(text).trim();if(!value)return;const now=Date.now();if(lastText===value&&now-lastAt<500){live.textContent='Cette question vient déjà d’être affichée.';return;}lastText=value;lastAt=now;input.value='';messages.push({role:'user',text:value.slice(0,C.MAX_INPUT)});renderAll();busy=true;send.disabled=true;const started=performance.now();if(pageReady)await pageReady;const pageKey=core.items.find(x=>x.url===currentRoute())?.key;let answer;try{answer=await core.ask(value,context,{pageKey,page:currentRoute()});answer=await withAI(value,answer);}catch(e){/* v7.58 (LEO-02g) : une suite utile — relancer la même question, chercher sur le site */answer={kind:'error',text:'Un fichier local de Léo n’a pas pu être chargé (connexion coupée ou fichier manquant). Le site reste utilisable : tu peux relancer la question ou chercher directement.',links:[{label:'Chercher sur le site',url:'/index.html#q'}],choices:[value],context};}finally{busy=false;send.disabled=false;}try{performance.measure('leo-answer',{start:started});}catch{}appendAnswer(answer,value);input.focus({preventScroll:true});}
form.addEventListener('submit',event=>{event.preventDefault();ask(input.value);});let preloadTimer=0;input.addEventListener('input',()=>{touchedAt=Date.now();clearTimeout(draftTimer);draftTimer=setTimeout(save,180);/* au plus une fois toutes les 150 ms pendant la frappe (pas d'attente de la fin de la frappe) */if(!preloadTimer)preloadTimer=setTimeout(()=>{preloadTimer=0;preload(input.value);},150);});
async function fetchJSON(url){const response=await fetch(url,{credentials:'same-origin'});if(!response.ok)throw Error('Fichier local indisponible.');if(+response.headers.get('content-length')>MAX_BYTES)throw Error('Fichier local trop volumineux.');const text=await response.text();if(text.length>MAX_BYTES)throw Error('Fichier local trop volumineux.');return JSON.parse(text);}
async function load(){if(core)return;if(dataPromise)return dataPromise;send.disabled=true;log.textContent='Chargement des réponses locales…';dataPromise=(async()=>{const data=await fetchJSON(LEO_BASE+'leo-index.json'+V);core=C.create(data,{load:(name,file)=>fetchJSON(file+V)});revision=data.revision;restore();renderAll();
  /* le morceau de la page est préparé tout de suite (sans bloquer) : calculateur sur le calculateur et le Tuto ; sur une fiche ou une section, sa famille, pour que « ça vaut le coup ? » ou « et son prix ? » visent la fiche ouverte */
  const shard=pageShard(location.pathname);if(shard)pageReady=core.loadShard(shard).catch(()=>{});})();try{await dataPromise;}catch{log.replaceChildren(el('p','Les réponses locales de Léo n’ont pas pu être chargées. Le site et le calculateur restent utilisables.'),button('Réessayer','leo-choice',()=>{dataPromise=null;load();}));const a=link('Ouvrir le calculateur','/calculateurs.html');if(a)log.append(a);live.textContent='Réponses locales indisponibles.';}finally{send.disabled=!core;}}
function viewport(){if(!panel.open)return;const v=window.visualViewport;panel.style.setProperty('--leo-vtop',(v?.offsetTop||0)+'px');panel.style.setProperty('--leo-vheight',(v?.height||innerHeight)+'px');}
function open(){if(panel.open)return;expire();modal=media.matches;if(modal){scrollBefore={x:scrollX,y:scrollY};oldOverflow=document.documentElement.style.overflow;document.documentElement.style.overflow='hidden';panel.showModal();panel.setAttribute('aria-modal','true');launch.hidden=true;}else{panel.show();panel.setAttribute('aria-modal','false');}launch.setAttribute('aria-expanded','true');viewport();load();input.focus({preventScroll:true});animate(panel);}
function close(options={}){if(!panel.open)return;stop();panel.close();if(modal){document.documentElement.style.overflow=oldOverflow;if(scrollBefore)scrollTo({left:scrollBefore.x,top:scrollBefore.y,behavior:'instant'});}if(!options.preserveResume)resumeTo=null;launch.hidden=false;launch.setAttribute('aria-expanded','false');save();launch.focus({preventScroll:true});window.LKLeoLoader.place();}
function clear(){clearTimeout(expiryTimer);messages=[];context={};resumeTo=null;input.value='';try{sessionStorage.removeItem(KEY);}catch{}if(core)renderAll();live.textContent='Conversation effacée dans cet onglet.';input.focus();}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&panel.open&&!modal&&!document.querySelector('dialog:modal')){e.preventDefault();close();}});
panel.addEventListener('cancel',e=>{e.preventDefault();close();});panel.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal){e.preventDefault();close();}});media.addEventListener('change',()=>{if(panel.open){close({preserveResume:true});open();}});window.visualViewport?.addEventListener('resize',viewport);window.visualViewport?.addEventListener('scroll',viewport);window.addEventListener('resize',viewport);window.addEventListener('pagehide',save);
window.LKLeoUI={open,close,isOpen:()=>panel.open,clear,ask,core:()=>core};
})();
