/* Léo : intentions, recherche et paramètres déterministes. Aucune génération distante. */
(function(root,factory){'use strict';if(typeof module==='object'&&module.exports)module.exports=factory(require('./calculateurs-engine.js'),require('./leo-link.js'));else root.LKLeoCore=factory(root.LKCalcEngine,root.LKLeoLink);})(typeof globalThis!=='undefined'?globalThis:this,function(E,L){
'use strict';
const MAX_INPUT=600,norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[’‘`]/g,"'").replace(/[‐‑–—]/g,'-').replace(/\s+/g,' ').trim();
const clean=s=>norm(s).replace(/[^a-z0-9]+/g,' ').trim(),escape=s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),own=(o,k)=>Object.prototype.hasOwnProperty.call(o,k);
function number(raw){let s=String(raw).trim();if(/^[+-]?\d{1,3}(?:,\d{3})+\.\d+$/.test(s))s=s.replaceAll(',','');else if(/^[+-]?\d{1,3}(?:\.\d{3})+,\d+$/.test(s))s=s.replaceAll('.','');else if(/^[+-]?\d{1,3}(?:([.,])\d{3})(?:\1\d{3})+$/.test(s))s=s.replace(/[.,]/g,'');else if(/^[+-]?\d{1,3}[.,]\d{3}$/.test(s))return {valid:false,ambiguous:true,reason:'Séparateur ambigu : utilise des espaces pour les milliers.'};const r=E.parseLocalizedNumber(s);return {valid:r.valid,value:r.value,reason:r.reason};}
function near(a,b){if(a.length<5||b.length<5||Math.abs(a.length-b.length)>1)return false;let i=0,j=0,d=0;while(i<a.length&&j<b.length){if(a[i]===b[j]){i++;j++;continue;}if(++d>1)return false;if(a.length>=b.length)i++;if(b.length>=a.length)j++;}return d+(i<a.length||j<b.length?1:0)<=1;}
function safeURL(value){if(typeof value==='string'&&/^\/calculateurs\.html\?tool=(?:goal|session|activities|purchase|roi|order|budget|plan)#atelier$/.test(value))return value;return typeof value==='string'&&value.length<230&&/^\/(?:[a-z0-9-]+\/)?[a-z0-9-]+\.html(?:#[a-z0-9][a-z0-9=_-]*)?$/i.test(value)?value:null;}
function safeSource(value){try{const u=new URL(value);return u.protocol==='https:'&&['rockstargames.com','www.rockstargames.com','map.gtadb.org','gtadb.org'].includes(u.hostname)?u.href:null;}catch{return null;}}
function extract(input){
 const q=norm(input),values={},issues=[],spans=[],money=[];const mark=(i,n)=>spans.push([i,i+n]),covered=i=>spans.some(([a,b])=>i>=a&&i<b);
 for(const m of q.matchAll(/([+-]?\d+(?:[.,]\d+)?)\s*(?:heures?|h)(?![a-z])(?:\s*(\d{1,4})(?:\s*min(?:utes?)?)?)?/g)){const n=number(m[1]),extra=m[2]?+m[2]:0;mark(m.index,m[0].length);const v=n.value*60+extra;if(!n.valid||extra>=60||v<=0||v>1440)issues.push({kind:'invalid',field:'minutes',text:'Écris une durée entre 1 et 1 440 minutes ; après les heures, les minutes vont de 0 à 59.'});else{values.minutes=v;if(/par jour|chaque jour|quotidien/.test(q))values.dailyMinutes=v;}}
 for(const m of q.matchAll(/([+-]?\d+(?:[.,]\d+)?)\s*min(?:utes?)?\b/g)){if(covered(m.index))continue;mark(m.index,m[0].length);const n=number(m[1]);if(!n.valid||n.value<1||n.value>1440)issues.push({kind:'invalid',field:'minutes',text:'Écris une durée entre 1 et 1 440 minutes.'});else{values.minutes=n.value;if(/par jour|chaque jour|quotidien/.test(q))values.dailyMinutes=n.value;}}
 if(/\bseul\b|\bsolo\b/.test(q))values.players=1;
 for(const m of q.matchAll(/(?:groupe de|nous sommes|on est|a|avec)\s+([+-]?\d{1,3})(?:\s+(?:joueurs?|personnes?|amis?))?/g)){if(!/(?:jou|groupe|nous sommes|on est|amis|personnes)/.test(q)||(!m[0].includes('jou')&&!/groupe de|nous sommes|on est/.test(m[0])&&!/joue/.test(q.slice(Math.max(0,m.index-25),m.index))))continue;const i=m.index+m[0].indexOf(m[1]);if(covered(i))continue;mark(i,m[1].length);const v=+m[1];if(v<1||v>100)issues.push({kind:'invalid',field:'players',text:'Le groupe doit compter de 1 à 100 joueurs, toi compris.'});else values.players=v;}
 let end=0;
 for(const m of q.matchAll(/[+-]?(?:\d{1,3}(?:[ \u00a0\u202f]\d{3})+|\d+)(?:[.,]\d+)*(?:\s*(?:millions?|mille|k(?![a-z])|m(?![a-z])|\$|dollars?|euros?|€))?/g)){
  if(covered(m.index))continue;const token=m[0].trim(),unit=token.match(/(?:millions?|mille|k|m|\$|dollars?|euros?|€)$/)?.[0],raw=unit?token.slice(0,-unit.length).trim():token,before=q.slice(end,m.index),after=q.slice(m.index+token.length,m.index+token.length+22);end=m.index+token.length;
  const roles=[['capital',/capital|argent actuel|budget actuel|mon budget|j'ai|je dispose|j ai/g],['target',/vise|objectif|atteindre|je veux|economiser|epargner/g],['price',/prix|coute|cout de|achat de|acheter|achete|pour|au prix de/g],['reserve',/reserve|garder|de cote/g],['hourly',/gain net|revenu|gagne|par heure/g]];
  let role=null,last=-1;for(const [k,re] of roles)for(const hit of before.matchAll(re))if(hit.index>last){last=hit.index;role=k;}
  if(/^(?:\s*(?:\/\s*h\b|par heure|de l'heure))/.test(after))role='hourly';
  if(!unit&&role&&(/^[a-z]/.test(after)||/^\s+\d/.test(after))){issues.push({kind:'amount',field:role,text:'Ce format est ambigu. Écris un montant avec son unité, par exemple « 200 000 $ » ou « 1 million ». '});continue;}
  if(!unit&&!role&&!/^\s*[+-]?\d[\d\s.,]*\s*$/.test(q))continue;
  if(unit==='€'||/euros?/.test(unit||'')){issues.push({kind:'invalid',field:role,text:'Je ne transforme pas les euros en dollars du jeu. Écris un montant en dollars pour le calculateur.'});continue;}
  const n=number(raw);if(!n.valid){issues.push({kind:'amount',field:role,text:n.ambiguous?'Ce nombre est ambigu. Écris par exemple « 1 500 $ » ou « 1,5 million ».':'Ce montant n’est pas lisible. Écris un nombre avec son unité.'});continue;}
  if(!unit&&/[.,]/.test(raw)){issues.push({kind:'amount',field:role,text:'Dis-moi l’unité : des dollars, des milliers ou des millions ? Par exemple « 1,5 million ».'});continue;}
  const value=n.value*(/^(m|millions?)$/.test(unit||'')?1e6:/^(k|mille)$/.test(unit||'')?1e3:1);
  if(value<0||value>1e12||!Number.isFinite(value)){issues.push({kind:'invalid',field:role,text:'Le montant doit être entre 0 et 1 000 milliards de dollars.'});continue;}
  money.push({value,role});if(role){if(own(values,role)&&values[role]!==value)issues.push({kind:'role',value,text:'Deux nombres semblent dire la même chose. Dis-moi lequel est quoi.'});else values[role]=value;}else issues.push({kind:'role',value,text:new Intl.NumberFormat('fr-FR').format(value)+' $, c’est ce que tu as déjà ou ce que tu veux avoir ?'});
 }
 if(money.length&&/€|\beuros?\b/.test(q)&&!issues.some(x=>x.text.includes('euros')))issues.push({kind:'invalid',text:'Je ne transforme pas les euros en dollars du jeu. Écris un montant en dollars pour le calculateur.'});
 if(!own(values,'target')&&/(?:vise|atteindre|veux|objectif)[^.!?]{0,28}\b(?:le|un) million\b/.test(q))values.target=1000000;
 return {values,issues,money};
}
function create(data){
 if(!data||data.schemaVersion!==1||!Array.isArray(data.items)||data.items.length>5000||!Array.isArray(data.proofs)||!Array.isArray(data.categories)||!Array.isArray(data.definitions)||!Array.isArray(data.faq))throw Error('Les réponses locales sont indisponibles.');
 const items=data.items.filter(x=>x&&L.safeId(x.key)&&typeof x.name==='string'&&x.name.length<220&&safeURL(x.url)).map(x=>({...x,proof:typeof data.proofs[x.proof]==='string'?data.proofs[x.proof]:'Information à vérifier dans la fiche.',n:clean(x.name),a:(x.aliases||[]).filter(a=>typeof a==='string'&&a.length<500).map(clean)}));
 const byKey=new Map(items.map(x=>[x.key,x])),categories=data.categories.filter(x=>safeURL(x.route)),tools=data.tools;
 const category=q=>categories.find(c=>c.terms.some(t=>new RegExp('(?:^| )'+escape(clean(t))+'(?: |$)').test(clean(q))));
 // Base de connaissances GTA VI : correspondance par mots-clés, tolérante aux pluriels et aux petites fautes.
 const STOP=new Set(['le','la','les','un','une','des','de','du','d','l','et','ou','a','au','aux','en','y','il','elle','on','je','tu','nous','vous','ils','ce','cet','cette','ces','est','sont','sera','ete','etre','pour','par','sur','dans','avec','sans','pas','ne','plus','mon','ma','mes','ton','ta','tes','son','sa','ses','se','me','te','moi','toi','lui','leur','c','s','n','qu','t','j','m','va','vais','veux','peut','peux','faire','dis','dire']);
 const stem=w=>w.length>3&&/s$/.test(w)&&!/ss$/.test(w)?w.slice(0,-1):w;
 const same=(a,b)=>a===b||stem(a)===stem(b)||(a.length>=6&&b.length>=6&&near(stem(a),stem(b)));
 const knowledge=(data.knowledge||[]).map(x=>({...x,phrases:x.k.map(p=>clean(p).split(' ').filter(Boolean))}));
 function knowledgeMatch(q){const all=clean(q).split(' ').filter(Boolean),toks=all.filter(w=>!STOP.has(w));if(!all.length)return null;let best=null;
  for(const k of knowledge){let score=0;for(const parts of k.phrases){if(!parts.length)continue;if(parts.length===1){const p=parts[0];if(STOP.has(p)?all.includes(p):toks.some(t=>same(t,p)))score+=p.length>=7?2:1;}else{const sig=parts.filter(p=>!STOP.has(p));const need=sig.length?sig:parts;if(need.every(p=>all.some(t=>same(t,p))))score+=need.length===1?(need[0].length>=7?2:1):need.length+1;}}
   const min=k.min||2;if(score>=min&&(!best||score>best.score||(score===best.score&&k.priority&&!best.k.priority)))best={k,score};}
  return best;}
 const questionLike=q=>/\?|^(?:qui|quand|ou|comment|pourquoi|combien|quel|quelle|quels|quelles|est ce|c est quoi|c'est quoi|y a t il|y a t'il|peut on|on peut|est il|est elle|sont ils|a t on|dis moi|explique|parle moi|raconte|il y a|existe)\b/.test(q);
 const knowledgeAnswer=m=>({kind:'answer',text:m.k.text,links:m.k.links||[],status:m.k.status||undefined,source:m.k.source||undefined,verifiedAt:m.k.verifiedAt||undefined,context:{selected:[],values:{}}});
 function search(query,kind,offset=0){const n=clean(query);if(!n)return {items:[],total:0};const words=n.split(' '),r=[];for(const x of items){if(kind&&kind!==x.kind&&!(kind==='boats'&&/bateau|kayak/.test(clean(x.category+' '+x.name)))&&!(kind==='aircraft'&&/avion/.test(x.category))&&!(kind==='helicopter'&&/helico/.test(x.category)))continue;let score=x.n===n?100:x.a.includes(n)?94:x.n.startsWith(n+' ')?90:x.a.some(a=>a.startsWith(n))?78:x.n.includes(n)?75:words.every(w=>(x.n+' '+x.a.join(' ')).includes(w))?65:0;let fuzzy=false;if(!score&&words.length===1&&n.length>=5&&x.n.split(' ').some(w=>near(n,w))){score=35;fuzzy=true;}if(score)r.push({item:x,score,fuzzy});}r.sort((a,b)=>b.score-a.score||a.item.name.localeCompare(b.item.name,'fr'));return {items:r.slice(offset,offset+4).map(x=>({...x.item,fuzzy:x.fuzzy})),total:r.length};}
 function entityMatches(q,includeAll=false){const n=' '+clean(q)+' ',found=items.filter(x=>(includeAll||x.calcId)&&[x.n,...x.a.filter(a=>a.length>=5&&!/\d{4}/.test(a))].some(name=>name.length>=4&&n.includes(' '+name+' ')));const longest=found.filter(x=>!found.some(y=>y!==x&&y.n.includes(x.n)&&y.n.length>x.n.length));return [...new Map(longest.map(x=>[x.calcId||x.key,x])).values()];}
 const toolURL=t=>'/calculateurs.html?tool='+t+'#atelier';
 const calcResponse=(tool,values,selected=[],note='')=>({kind:'calc',text:'Vérifie les chiffres que j’ai compris, puis ouvre '+(tools.find(x=>x.id===tool)?.label||'le calculateur')+'. Le reste est à remplir ou à vérifier dans l’outil.',request:{v:1,tool,values,items:selected.map(x=>x.calcId).filter(Boolean)},selected:selected.map(x=>x.key),note,context:{tool,values,selected:selected.map(x=>x.key)}});
 function choose(key,context={}){const item=byKey.get(key);if(!item||!item.calcId)return {kind:'unknown',text:'Cette fiche ne fournit pas un achat utilisable dans le calculateur.',links:item?[{label:'Ouvrir la fiche',url:item.url}]:[]};const values={...(context.values||{})};if(context.selected?.length&&!context.selected.includes(key))delete values.price;return calcResponse(context.tool||'purchase',values,[item],'Élément choisi : '+item.name+'. '+item.proof);}
 function answer(query,context={},options={}){
  if(typeof query!=='string'||query.length>MAX_INPUT)return {kind:'error',text:'600 lettres maximum par question. Garde les noms et les chiffres utiles.'};const raw=query.trim(),q=norm(raw),n=clean(raw);if(!n)return {kind:'intro',text:'Je peux t’aider à trouver une fiche, comprendre un terme et préparer un calcul.'};
  const empty={selected:[],values:{}};
  if(/^(bonjour|salut|hello|bonsoir|aide|merci|yo|coucou|hey)$/.test(n))return {kind:'intro',text:'Salut ! Pose-moi une question sur GTA VI (sortie, consoles, prix, personnages, régions…), demande une fiche du site, ou donne-moi tes chiffres pour un calcul.',context:empty};
  if(/(?:sort|sortie|date|disponib)/.test(q)&&(/gta\s*(?:vi|6)|jeu/.test(q)||/^date de sortie/.test(q))){const r=data.release,today=options.now?new Date(options.now):new Date(),at=r?.verifiedAt&&Date.parse(r.verifiedAt+'T00:00:00Z'),date=r?.date&&Date.parse(r.date+'T00:00:00Z'),age=(today-at)/86400000,fresh=Number.isFinite(at)&&Number.isFinite(date)&&age>=0&&age<=(r.maxAgeDays||30)&&today.getTime()<date&&safeSource(r.source);return {kind:'answer',text:fresh?'Rockstar annonce GTA VI pour le '+new Intl.DateTimeFormat('fr-FR',{dateStyle:'long',timeZone:'UTC'}).format(new Date(date))+'.':'La date de sortie doit être revérifiée : ma donnée locale est absente ou trop ancienne. Je ne peux pas confirmer la disponibilité du jeu.',source:fresh?r.source:safeSource(r?.source),verifiedAt:r?.verifiedAt||null,status:fresh?'Date annoncée · source officielle':'À vérifier',context:empty};}
  const def=data.definitions.find(x=>x.terms.some(t=>new RegExp('(?:^| )'+escape(clean(t))+'(?: |$)').test(n)));if(def&&(/c'est quoi|c est quoi|quoi un|qu'est|qu est|veut dire|signifi|defini|explique/.test(q)||def.terms.some(t=>n===clean(t))))return {kind:'answer',text:def.text,links:[{label:'Lire dans le Tuto',url:def.url}],status:'Définition du calculateur',context:empty};
  let faq;if(/pourquoi.*prix|pas.*prix|prix.*(?:manqu|inconnu|absen)/.test(q))faq=data.faq.find(x=>x.id==='prix');else faq=data.faq.find(x=>x.terms.some(t=>n.includes(clean(t))));if(faq&&!/je veux acheter|je souhaite acheter/.test(q))return {kind:'answer',text:faq.text,links:[{label:'Voir l’explication',url:faq.url}],context:empty};
  const nav=/^(?:ouvre|ouvrir|aller|va |montre|ou est mon|ou sont mes|acces|emmene)/.test(q),ct=category(q),nt=tools.find(t=>t.terms.some(x=>n.includes(clean(x))));
  if(nav&&(ct||nt)){if(nt&&/mon plan|mes plans|mon objectif|mes activites|mon temps|mes achats|mon budget|calculateur|rentabilite/.test(q))return {kind:'answer',text:nt.label+' est disponible dans le calculateur.',links:[{label:'Ouvrir '+nt.label,url:toolURL(nt.id),tool:nt.id}],context:empty};if(ct)return {kind:'answer',text:'Voici la section '+ct.label+'.',links:[{label:'Ouvrir '+ct.label,url:ct.route}],context:empty};}
  const mentioned=entityMatches(raw,true),buyIntent=/acheter|achete|achat|vaut le coup|rentab/.test(q),locateIntent=/^(?:ou trouver|ou est|ou se trouve|trouve|cherche|je cherche|montre|localise)/.test(n);
  const destinations=mentioned.filter(x=>!x.calcId);
  if(buyIntent&&(destinations.length||ct?.id==='place')&&!mentioned.some(x=>x.calcId))return {kind:'answer',text:'Un lieu ou une région, c’est une destination : ça se visite, et rien ne dit qu’on peut l’acheter. Tu peux ouvrir sa fiche ou la carte.',links:destinations.slice(0,3).flatMap(x=>[{label:'Voir '+x.name,url:x.url},...(x.mapUrl?[{label:'Ouvrir le repère sur la carte',url:x.mapUrl}]:[])]).concat(destinations.length?[]:[{label:'Explorer les lieux',url:'/lieux.html'}]),context:empty};
  if(locateIntent&&mentioned.length)return {kind:'results',text:'Voici les fiches qui correspondent. La catégorie et les sources disent ce qu’on sait vraiment.',results:mentioned.slice(0,4),total:mentioned.length,forCalculation:false,context:{values:{},selected:mentioned.length===1?[mentioned[0].key]:[]}};
  const parsedRaw=extract(norm(raw)),kb=knowledgeMatch(raw),givesFigures=parsedRaw.money.length>0||parsedRaw.issues.length>0;
  const calcEntity=mentioned.some(x=>x.calcId);
  const priceIntent=/prix|coute|cout|vaut|combien/.test(q);
  if(kb&&!givesFigures&&!(buyIntent&&(mentioned.length||!(kb.k.priority||kb.score>=4)))&&!(calcEntity&&(priceIntent||kb.score<4))&&((kb.k.priority&&!calcEntity)||!mentioned.length||questionLike(q)||kb.score>=4))return knowledgeAnswer(kb);
  let numericText=norm(raw);for(const item of entityMatches(raw))for(const name of [item.n,...item.a])if(/\d/.test(name)){const re=new RegExp(name.split(' ').map(escape).join("[\\s'_-]+"),'g');numericText=numericText.replace(re,m=>' '.repeat(m.length));}
  let parsed=extract(numericText),values=parsed.values,selected=[],reuse=false;
  if(context.pending&&/mon capital|argent actuel|mon objectif|c'est le prix|c est le prix/.test(q)&&context.pending.kind==='role'){const role=/capital|argent/.test(q)?'capital':/objectif/.test(q)?'target':'price';values={...(context.values||{}),[role]:context.pending.value};parsed.issues=[];reuse=true;}
  else if(context.pending&&context.pending.field&&parsed.money.length===1&&!parsed.money[0].role){values={...(context.values||{}),[context.pending.field]:parsed.money[0].value};parsed.issues=[];reuse=true;}
  else if(/^(?:et |avec |non[ ,]|plutot |corrige |en fait )/.test(q)&&Object.keys(context.values||{}).length){values={...context.values,...values};reuse=true;}
  const intent=/ordre|d'abord|en premier|priorit|plusieurs achats/.test(q)?'order':/vaut le coup|rentab|amorti|\broi\b/.test(q)?'roi':/mon plan|plan complet|plusieurs decisions/.test(q)?'plan':/repart|enveloppe|budget/.test(q)&&!ct?.id?.includes('property')?'budget':/acheter|achete|achat|permettre|cout/.test(q)?'purchase':/vise|objectif|atteindre|million|epargn/.test(q)?'goal':/activit|mission|comparer.*gains/.test(q)?'activities':own(values,'minutes')?'session':nt?.id|| (Object.keys(values).length?'goal':null);
  const namedPurchase=/(?:acheter|achat de|achete)\s+(?!(?:pour|ce|cet|cette|celui|celle)\b)[a-z]/.test(q);
  let tool=(reuse||context.pending)&&context.tool&&!intent?context.tool:intent;
  if(parsed.issues.length){const issue=parsed.issues[0];return {kind:'clarify',text:issue.text,context:{values,tool:tool||'goal',selected:context.selected||[],pending:issue},choices:issue.kind==='role'?['C’est mon capital','C’est mon objectif']:[]};}
  if(tool){
   if(['purchase','roi','order','plan'].includes(tool)){
    selected=entityMatches(raw);if(reuse&&context.selected?.length&&(selected.length||namedPurchase)&&!selected.some(x=>context.selected.includes(x.key))&&!own(parsed.values,'price'))delete values.price;if(!selected.length&&/cette |ce vehicule|ce bateau|cet |ca vaut|celui|celle/.test(q)){const keys=context.selected?.length?context.selected:[options.pageKey];selected=keys.map(k=>byKey.get(k)).filter(x=>x?.calcId);reuse=selected.length>0;}
    if(selected.length>1&&tool!=='order'&&tool!=='plan'){const candidates=selected.slice(0,4);return {kind:'results',text:'Plusieurs fiches correspondent. Choisis celle que tu veux utiliser.',results:candidates,total:selected.length,context:{tool,values,selected:[]},forCalculation:true};}
    if(!selected.length&&/acheter|achat|rentab|vaut le coup/.test(q)){
     const query=n.replace(/je veux|je souhaite|acheter|un |une |le |la |les |cet |cette |entreprise|vehicule|voiture|arme|est ce|que|ca vaut le coup|rentable|pour|\d+/g,' ').replace(/\s+/g,' ').trim();
     if(query.length>=2){const result=search(query,ct?.id);if(result.total&&!result.items.some(x=>x.calcId))return {kind:'answer',text:'Ces résultats sont des lieux ou des contenus qu’on ne sait pas acheter. Ouvre leur fiche ; je ne prépare pas d’achat.',links:result.items.map(x=>({label:'Voir '+x.name,url:x.url})),context:empty};if(result.total)return {kind:'results',text:'Choisis une fiche. Si on ne sait pas encore si ça s’achète, le calcul reste ton essai à toi.',results:result.items,total:result.total,query,category:ct?.id,context:{tool,values,selected:[]},forCalculation:true};}
    }
   }
   if(reuse&&!namedPurchase&&!selected.length&&context.selected?.length)selected=context.selected.map(k=>byKey.get(k)).filter(x=>x?.calcId);
   if(own(values,'price')&&selected.length>1)return {kind:'clarify',text:'Ce prix concerne quel achat ? Choisis une fiche ou saisis les prix séparément dans l’ordre d’achat.',results:selected,context:{tool:'purchase',values,selected:[]}};
   const response=calcResponse(tool,values,selected,reuse?'Contexte repris de cet échange, affiché ci-dessous.':'');
   if(!selected.length&&['purchase','roi'].includes(tool))response.note+=(response.note?' ':'')+'Je ne trouve pas cette fiche : écris un nom plus précis, ou fais un achat sans fiche avec ton prix à toi.';
   if(selected.length)response.note+=(response.note?' ':'')+selected.map(x=>x.name+' : '+x.proof).join(' ');
   if(own(values,'minutes')&&tool!=='session')response.following=[{...response.request,tool:'session'}];return response;
  }
  const queryText=n.replace(/^(?:trouve moi|trouve|cherche moi|cherche|je cherche|je recherche|ou trouver|ou se trouve|ou est|ou sont|montre moi|recherche)\s*/,'').replace(/^(?:le|la|les|un|une|des|ce|cette|cet)\s+/,'').trim();
  const stripped=ct?queryText.replace(new RegExp('^(?:'+ct.terms.map(x=>escape(clean(x))).join('|')+')\\s+'),''):queryText;
  if(ct&&ct.terms.some(x=>clean(x)===stripped||clean(x)===queryText))return {kind:'answer',text:'Voici la section '+ct.label+'.',links:[{label:'Consulter '+ct.label,url:ct.route}],context:empty};
  const found=search(stripped,ct&&['vehicle','weapon','place','character','business','property','hideout'].includes(ct.id)?ct.id:null);
  if(found.total){return {kind:'results',text:found.items.some(x=>x.fuzzy)?'Je n’ai pas de correspondance exacte. Ces noms sont proches :':found.total>1?'Plusieurs fiches correspondent : regarde la catégorie pour choisir.':'Voici la fiche du site. Je ne devine pas où c’est exactement à partir du nom.',results:found.items,total:found.total,query:stripped,category:ct?.id,context:{values:{},selected:found.total===1?[found.items[0].key]:[]}};}
  return {kind:'unknown',text:'Je n’ai pas ça. Je connais la sortie, les consoles, le prix, les éditions, les trailers, les personnages, les régions, ce que montre l’Extended Look, et toutes les fiches du site. Essaie une question plus courte ou un nom précis.',links:[{label:ct?'Ouvrir '+ct.label:'Parcourir les véhicules',url:ct?.route||'/vehicules.html'},{label:'Aide du calculateur',url:'/tuto.html'}],context:empty};
 }
 return Object.freeze({answer,search,choose,items,byKey,categories,tools,data});
}
return Object.freeze({MAX_INPUT,norm,number,extract,near,safeURL,safeSource,create});
});
