/* ============================================================
   LEONIDAKIT — armes : source de vérité
   Chaque arme porte son niveau de certitude :
     st: 'officiel'  nom publié par Rockstar dans un support officiel
     st: 'vu'        visible dans un média officiel, nom non communiqué
   Aucune donnée issue de fuites.
   Images : visuels officiels Rockstar listés dans outils/armes-medias.json (registre outils/medias-officiels.json).
   Fiches et hub régénérés par node outils/gen-armes.cjs ; les textes sont écrits ici, pas dans les fiches.
   ============================================================ */
window.LK_ARMES = [
{"id":"girardi-es9","nom":"Girardi ES9","fr":"Pistola di Jason","cat":"pistolet","slot":"poing","st":"officiel","src":"Materiale del preordine dell’Ultimate Edition","insp":"Beretta 92FS","mun":"Munizioni per pistola","portee":"Da corta a media","ctx":"La pistola personale di Jason, nominata da Rockstar nella presentazione dell’Ultimate Edition, che ne offre una versione incisa. È l’arma corta più visibile nei media ufficiali.","perso":"jason","ue":true},
{"id":"klose-k17","nom":"Klose K17","fr":"Pistola di Lucia","cat":"pistolet","slot":"poing","st":"officiel","src":"Materiale del preordine dell’Ultimate Edition","insp":"Glock 17 / SIG P320","mun":"Munizioni per pistola","portee":"Da corta a media","ctx":"La pistola personale di Lucia, nominata da Rockstar con una versione incisa a rose nell’Ultimate Edition. Pistola moderna con fusto in polimero e slitta per accessori.","perso":"lucia","ue":true},
{"id":"nipper-38","nom":"Nipper .38","fr":"Pistola compatta","cat":"pistolet","slot":"poing","st":"officiel","src":"Nome inciso sull’arma, copertina ufficiale","insp":"Bersa Thunder 380","mun":"Munizioni per pistola","portee":"Corta","ctx":"La piccola pistola che Lucia tiene in mano sulla copertina ufficiale. Il suo nome si legge sul carrello: è una delle poche armi il cui nome viene direttamente da un’immagine di Rockstar.","perso":"lucia"},
{"id":"hawk-little-morgan","nom":"Hawk & Little Morgan","fr":"Revolver incisi","cat":"pistolet","slot":"poing","st":"officiel","src":"Materiale del preordine dell’Ultimate Edition","insp":"Smith & Wesson 629","mun":"Munizioni per pistola","portee":"Media","ctx":"Una coppia di revolver incisi, uno per Jason e l’altro per Lucia, che Rockstar descrive come ispirati alla tenuta Vercetti di Vice City. Impugnature con palme, incisioni con il nome e mirino ad alte prestazioni.","ue":true},
{"id":"pistolet-custom","nom":"Pistola personalizzata","fr":null,"cat":"pistolet","slot":"poing","st":"vu","src":"Trailer 2","insp":"Colt 1911","mun":"Munizioni per pistola","portee":"Da corta a media","ctx":"Pistola con finitura personalizzata, visibile in una scena in interni. Le finiture in vista fanno pensare che la personalizzazione delle armi sia tornata."},
{"id":"pistolet-auto","nom":"Pistola con selettore","fr":null,"cat":"pistolet","slot":"poing","st":"vu","src":"Extended Look del 27 agosto 2026","insp":"Glock con switch","mun":"Munizioni per pistola","portee":"Corta","ctx":"Pistola dotata di un selettore di tiro sul retro del carrello, un dettaglio visibile nelle sequenze di gameplay. Trasformerebbe una pistola semiautomatica in un’arma a raffica."},
{"id":"mustang-357","nom":"Mustang .357","fr":"Revolver dei biker","cat":"pistolet","slot":"poing","st":"officiel","src":"Nome inciso sull’arma, screenshot ufficiale di Ambrosia","insp":"Colt Python","mun":"Munizioni per pistola","portee":"Media","ctx":"Il grosso revolver che una motociclista brandisce nel terzo screenshot di Ambrosia, appesa al collo di un membro della gang con la toppa Enforcer. Il nome Mustang .357 è inciso sull’arma: è la quinta arma il cui nome viene direttamente da un’immagine di Rockstar. Canna ventilata e grosso tamburo da Colt Python, la magnum del cinema, qui nelle mani dei biker dell’entroterra."},
{"id":"fusil-double","nom":"Fucile a doppia canna","fr":null,"cat":"pompe","slot":"longue","st":"vu","src":"Trailer 2","insp":"Fucile da caccia a canne affiancate","mun":"Cartucce","portee":"Molto corta","ctx":"Fucile a due canne affiancate, associato alle zone rurali e alle paludi nei media ufficiali. L’uomo con la barba in primo piano nel sesto screenshot di Grassrivers ne porta uno in spalla, con finiture incise e calcio in legno, davanti all’alligatore appeso nella sua officina."},
{"id":"fusil-pompe","nom":"Fucile a pompa","fr":null,"cat":"pompe","slot":"longue","st":"vu","src":"Trailer 1","insp":"Mossberg 590","mun":"Cartucce","portee":"Molto corta","ctx":"Fucile a pompa classico, avvistato in scene di scontro a fuoco. Arma a corto raggio tipica della serie."},
{"id":"micro-smg","nom":"Mitraglietta a motivo tropicale","fr":null,"cat":"pm","slot":"poing","st":"vu","src":"Immagine dell’Ultimate Edition","insp":"Mini Uzi","mun":"Munizioni per pistola","portee":"Corta","ctx":"Mitraglietta compatta a motivo tropicale, mostrata nell’immagine dell’Ultimate Edition senza che Rockstar ne abbia pubblicato il nome. Si usa con una mano, nella tradizione delle armi da drive-by.","ue":true},
{"id":"smg-compact","nom":"Mitraglietta compatta","fr":null,"cat":"pm","slot":"poing","st":"vu","src":"Extended Look del 27 agosto 2026","insp":"Škorpion","mun":"Munizioni per pistola","portee":"Corta","ctx":"Arma automatica cortissima, avvistata in una scena d’azione ravvicinata."},
{"id":"smg","nom":"Mitraglietta","fr":null,"cat":"pm","slot":"longue","st":"vu","src":"Trailer 2","insp":"H&K MP5","mun":"Munizioni per pistola","portee":"Da corta a media","ctx":"Mitraglietta tenuta a due mani da Jason e Lucia durante il colpo del Trailer 2. La versione di Jason ha un mirino a punto rosso."},
{"id":"pm-tactique","nom":"Mitraglietta a calcio pieghevole","fr":null,"cat":"pm","slot":"longue","st":"vu","src":"Immagine dell’Ultimate Edition","insp":null,"mun":"Munizioni per pistola","portee":"Da corta a media","ctx":"Appoggiata sul sedile di un’auto tra le mazzette di banconote, con una pistola abbinata, nell’immagine Weapon Pattern del Vintage Vice City Pack. Calcio ripiegato, caricatore dritto davanti all’impugnatura, finitura turchese con palme: una mitraglietta moderna e compatta, diversa dalla piccola mitraglietta a motivo tropicale che Jason tiene in mano nelle immagini degli outfit. Il suo nome non è stato comunicato.","ue":true,"fam":"Mitraglietta moderna con calcio pieghevole"},
{"id":"carabine","nom":"Carabina","fr":null,"cat":"assaut","slot":"longue","st":"vu","src":"Trailer 2","insp":"AR-15 / M4","mun":"Munizioni per fucile","portee":"Da media a lunga","ctx":"Carabina moderna con calcio telescopico, visibile in diverse sequenze d’azione."},
{"id":"fusil-assaut","nom":"Fucile d’assalto","fr":null,"cat":"assaut","slot":"longue","st":"vu","src":"Trailer 1","insp":"AK","mun":"Munizioni per fucile","portee":"Da media a lunga","ctx":"Fucile d’assalto con il caratteristico caricatore curvo, avvistato nelle mani degli antagonisti."},
{"id":"fusil-precision","nom":"Fucile a otturatore","fr":null,"cat":"precision","slot":"longue","st":"vu","src":"Extended Look del 27 agosto 2026","insp":"Remington 700","mun":"Munizioni per fucile","portee":"Lunga","ctx":"Fucile a otturatore con mirino telescopico, avvistato in un contesto di tiro a distanza."},
{"id":"fusil-semi-auto","nom":"Fucile semiautomatico","fr":null,"cat":"precision","slot":"longue","st":"vu","src":"Screenshot ufficiali","insp":"Springfield M1A","mun":"Munizioni per fucile","portee":"Lunga","ctx":"Il lungo fucile con calcio in legno e mirino che tiene in mano uno dei tre uomini in posa davanti al loro idroscivolante, nel primo screenshot di Grassrivers. Il castello allungato e il calcio tradizionale ricordano l’M1A, la versione civile dell’M14: un’arma da caccia e da tiro a lunga distanza, più rustica del fucile a otturatore e perfettamente a suo agio nelle paludi."},
{"id":"mitrailleuse","nom":"Mitragliatrice da combattimento","fr":null,"cat":"mitrailleuse","slot":"longue","st":"vu","src":"Extended Look del 27 agosto 2026","insp":"M249 SAW","mun":"Munizioni pesanti","portee":"Media","ctx":"Arma di supporto alimentata a nastro, la più pesante avvistata finora."},
{"id":"batte","nom":"Mazza da baseball","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Trailer 1","insp":null,"mun":null,"portee":"Corpo a corpo","ctx":"Mazza da baseball, arma da mischia ricorrente della serie. Le animazioni del corpo a corpo sono state rifatte in motion capture.","fam":"Mazza da baseball in alluminio"},
{"id":"couteau-cran","nom":"Coltello a scatto","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Immagine dell’Ultimate Edition","insp":null,"mun":null,"portee":"Corpo a corpo","ctx":"Coltello a lama retrattile, visibile nell’immagine dell’Ultimate Edition accanto ai revolver incisi.","ue":true,"fam":"Coltello a serramanico"},
{"id":"club-golf","nom":"Mazza da golf","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Trailer 2","insp":null,"mun":null,"portee":"Corpo a corpo","ctx":"Mazza da golf usabile come arma da mischia, sulla scia degli oggetti di uso quotidiano trasformati in armi.","fam":"Ferro da golf"},
{"id":"marteau","nom":"Martello","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Extended Look del 27 agosto 2026","insp":null,"mun":null,"portee":"Corpo a corpo","ctx":"Martello da cantiere, avvistato come arma improvvisata.","fam":"Martello da carpentiere"},
{"id":"queue-billard","nom":"Stecca da biliardo","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Extended Look del 27 agosto 2026","insp":null,"mun":null,"portee":"Corpo a corpo","ctx":"Stecca da biliardo, arma da mischia legata ai luoghi di svago di Leonida.","fam":"Stecca da biliardo americano"},
{"id":"molotov","nom":"Molotov","fr":null,"cat":"projectile","slot":"poing","st":"vu","src":"Trailer 2","insp":null,"mun":null,"portee":"Jet","ctx":"Molotov, classica arma da lancio incendiaria della serie.","fam":"Bottiglia incendiaria improvvisata"},
{"id":"fumigene","nom":"Granata fumogena","fr":null,"cat":"projectile","slot":"poing","st":"vu","src":"Extended Look del 27 agosto 2026","insp":null,"mun":null,"portee":"Jet","ctx":"Granata fumogena, arma da lancio non letale che serve a nascondere uno spostamento.","fam":"Granata fumogena a mano"},
{"id":"harpon","nom":"Fucile ad arpione","fr":null,"cat":"speciale","slot":"longue","st":"vu","src":"Extended Look del 27 agosto 2026","insp":null,"mun":"Arpioni","portee":"Corta, sott’acqua","ctx":"Fucile ad arpione, arma subacquea. È una novità per la serie: accompagna le zone sommerse esplorabili.","fam":"Fucile subacqueo a elastici"},
{"id":"lance-grenades","nom":"Lanciagranate","fr":null,"cat":"speciale","slot":"longue","st":"vu","src":"Trailer 2","insp":"Milkor MGL","mun":"Granate","portee":"Media","ctx":"Lucia lo tiene in mano durante l’inseguimento con la polizia del Trailer 2, nel momento in cui un veicolo esplode dietro di lei. Il grosso tamburo che sporge sotto la canna non lascia dubbi: un lanciagranate a tamburo tipo Milkor MGL, il ritorno dell’arma pesante più spettacolare della serie."}
];
window.LK_ARMES_CATS = {
  pistolet:'Pistole', pompe:'Fucili a pompa', pm:'Mitragliette', assaut:"Fucili d’assalto",
  precision:'Fucili di precisione', mitrailleuse:'Mitragliatrici', melee:'Mischia', projectile:'Da lancio', speciale:'Speciali'
};
