/* Léo v2 (v7.45, lot 8) : intentions, recherche et paramètres déterministes, sans aucune génération distante.
   Trois couches de réponse : questions rédigées (leo-index.json), gabarits par famille de fiche (morceaux leo/*.json chargés
   quand une question les vise), passages des pages (leo/passages.json). Quand rien ne répond, Léo le dit et renvoie vers le
   site officiel de Rockstar. Le flux de calcul de la v1 (chiffres → outil du calculateur) est conservé tel quel. */
(function(root,factory){'use strict';if(typeof module==='object'&&module.exports)module.exports=factory(require('./calculateurs-engine.js'),require('./leo-link.js'),require('./leo-nlp.js'));else root.LKLeoCore=factory(root.LKCalcEngine,root.LKLeoLink,root.LKLeoNLP);})(typeof globalThis!=='undefined'?globalThis:this,function(E,L,N){
'use strict';
const MAX_INPUT=600,norm=s=>String(s||'').replace(/ß/g,'ss').normalize('NFD').replace(/[̀-ͯ]/g,'').toLowerCase().replace(/[’‘`]/g,"'").replace(/[‐‑–—]/g,'-').replace(/\s+/g,' ').trim();
const clean=s=>norm(s).replace(/[^a-z0-9]+/g,' ').trim(),escape=s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),own=(o,k)=>Object.prototype.hasOwnProperty.call(o,k);
const HIGH=0.78,MID=0.6,MARGIN=0.08,PASSAGE_MIN=0.5;
function number(raw){let s=String(raw).trim();if(/^[+-]?\d{1,3}(?:,\d{3})+\.\d+$/.test(s))s=s.replaceAll(',','');else if(/^[+-]?\d{1,3}(?:\.\d{3})+,\d+$/.test(s))s=s.replaceAll('.','');else if(/^[+-]?\d{1,3}(?:([.,])\d{3})(?:\1\d{3})+$/.test(s))s=s.replace(/[.,]/g,'');else if(/^[+-]?\d{1,3}[.,]\d{3}$/.test(s))return {valid:false,ambiguous:true,reason:'Separatore ambiguo: usa gli spazi per le migliaia.'};const r=E.parseLocalizedNumber(s);return {valid:r.valid,value:r.value,reason:r.reason};}
function near(a,b){if(a.length<5||b.length<5||Math.abs(a.length-b.length)>1)return false;let i=0,j=0,d=0;while(i<a.length&&j<b.length){if(a[i]===b[j]){i++;j++;continue;}if(++d>1)return false;if(a.length>=b.length)i++;if(b.length>=a.length)j++;}return d+(i<a.length||j<b.length?1:0)<=1;}
/* v7.61 : une adresse peut porter le dossier de sa langue (/es/…) */
function safeURL(value){if(typeof value==='string'&&/^\/(?:[a-z]{2}\/)?calculateurs\.html\?tool=(?:goal|session|activities|purchase|roi|order|budget|compare|plan)#atelier$/.test(value))return value;if(typeof value==='string'&&/^\/(?:[a-z]{2}\/)?comparateur\.html\?type=(?:vehicules|armes)&ids=[a-z0-9-]+(?:,[a-z0-9-]+){0,2}$/.test(value))return value;return typeof value==='string'&&value.length<230&&/^\/(?:[a-z]{2}\/)?(?:[a-z0-9-]+\/)?[a-z0-9-]+\.html(?:#[a-z0-9][a-z0-9=_-]*)?$/i.test(value)?value:null;}
function safeSource(value){try{const u=new URL(value);return u.protocol==='https:'&&['rockstargames.com','www.rockstargames.com','map.gtadb.org','gtadb.org'].includes(u.hostname)?u.href:null;}catch{return null;}}
const SMS={g:'j ai',jai:'j ai',jve:'je veux',jveux:'je veux',jvx:'je veux',cb:'combien',cmb:'combien',pr:'pour',ds:'dans',mtn:'maintenant',jsp:'je sais pas',thune:'argent',fric:'argent',tune:'argent',pognon:'argent',cash:'argent',ble:'argent',oseille:'argent',moula:'argent',ptet:'peut etre'};
/* Les nombres qui ne sont pas des montants (gta 6, ps5, trailer 2, 60 fps, 4k, années, dates) sont retirés avant la lecture des chiffres. */
const prepare=input=>norm(input).replace(/\b(?:gta|ps|xbox|trailer|serie|series|mk|episode)\s*\d+\b/g,' ').replace(/\b\d+\s*fps\b/g,' ').replace(/\b4k\b/g,' ').replace(/\b\d{1,2}\s+(?:janvier|fevrier|mars|avril|mai|juin|juillet|aout|septembre|octobre|novembre|decembre)(?:\s+\d{4})?\b/g,' ').replace(/\b(?:19|20)\d{2}\b(?!\s*(?:\$|k|m|mille|million|dollars))/g,' ').replace(/(^|[^a-z])([a-z]{1,7})(?=[^a-z]|$)/g,(m,pre,w)=>pre+(own(SMS,w)?SMS[w]:w));
function extract(input){
 const q=prepare(input),values={},issues=[],spans=[],money=[];const mark=(i,n)=>spans.push([i,i+n]),covered=i=>spans.some(([a,b])=>i>=a&&i<b);
 for(const m of q.matchAll(/([+-]?\d+(?:[.,]\d+)?)\s*(?:heures?|h)(?![a-z])(?:\s*(\d{1,4})(?:\s*min(?:utes?)?)?)?/g)){const n=number(m[1]),extra=m[2]?+m[2]:0;mark(m.index,m[0].length);const v=n.value*60+extra;if(!n.valid||extra>=60||v<=0||v>1440)issues.push({kind:'invalid',field:'minutes',text:'Scrivi una durata tra 1 e 1.440 minuti; dopo le ore, i minuti vanno da 0 a 59.'});else{values.minutes=v;if(/par jour|chaque jour|quotidien/.test(q))values.dailyMinutes=v;}}
 for(const m of q.matchAll(/([+-]?\d+(?:[.,]\d+)?)\s*min(?:utes?)?\b/g)){if(covered(m.index))continue;mark(m.index,m[0].length);const n=number(m[1]);if(!n.valid||n.value<1||n.value>1440)issues.push({kind:'invalid',field:'minutes',text:'Scrivi una durata tra 1 e 1.440 minuti.'});else{values.minutes=n.value;if(/par jour|chaque jour|quotidien/.test(q))values.dailyMinutes=n.value;}}
 if(/\bseul\b|\bsolo\b/.test(q))values.players=1;
 for(const m of q.matchAll(/(?:groupe de|nous sommes|on est|a|avec)\s+([+-]?\d{1,3})(?:\s+(?:joueurs?|personnes?|amis?))?/g)){if(!/(?:jou|groupe|nous sommes|on est|amis|personnes)/.test(q)||(!m[0].includes('jou')&&!/groupe de|nous sommes|on est/.test(m[0])&&!/joue/.test(q.slice(Math.max(0,m.index-25),m.index))))continue;const i=m.index+m[0].indexOf(m[1]);if(covered(i))continue;mark(i,m[1].length);const v=+m[1];if(v<1||v>100)issues.push({kind:'invalid',field:'players',text:'Il gruppo deve avere da 1 a 100 giocatori, te compreso.'});else values.players=v;}
 let end=0;
 for(const m of q.matchAll(/[+-]?(?:\d{1,3}(?:[   ]\d{3})+|\d+)(?:[.,]\d+)*(?:\s*(?:millions?|mille|k(?![a-z])|m(?![a-z])|\$|dollars?|euros?|€))?/g)){
  if(covered(m.index))continue;/* v7.59 (check ultime, CALC-11) : un chiffre collé à un mot (« ES9 », « K17 », « F-150 », « gta6 ») fait partie du nom, ce n’est pas un montant */if(m.index>0&&/[a-z]/i.test(q[m.index-1]))continue;const token=m[0].trim(),unit=token.match(/(?:millions?|mille|k|m|\$|dollars?|euros?|€)$/)?.[0],raw=unit?token.slice(0,-unit.length).trim():token,before=q.slice(end,m.index),after=q.slice(m.index+token.length,m.index+token.length+22);end=m.index+token.length;
  const roles=[['capital',/capital|argent actuel|budget actuel|mon budget|j'ai|je dispose|j ai/g],['target',/vise|objectif|atteindre|je veux|economiser|epargner|(?<=temps )pour|pour avoir|pour atteindre|arriver a/g],['price',/prix|coute|cout de|achat de|acheter|achete|pour|au prix de/g],['reserve',/reserve|garder|de cote/g],['hourly',/gain net|revenu|gagne|par heure/g]];
  let role=null,last=-1;for(const [k,re] of roles)for(const hit of before.matchAll(re))if(hit.index>last){last=hit.index;role=k;}
  if(/^(?:\s*(?:\/\s*h\b|par heure|de l'heure))/.test(after))role='hourly';
  if(!unit&&role&&(/^[a-z]/.test(after)||/^\s+\d/.test(after))){issues.push({kind:'amount',field:role,text:'Questo formato è ambiguo. Scrivi un importo con la sua unità, per esempio “200.000 $” o “1 milione”. '});continue;}
  if(!unit&&!role&&!/^\s*[+-]?\d[\d\s.,]*\s*$/.test(q))continue;
  if(unit==='€'||/euros?/.test(unit||'')){issues.push({kind:'invalid',field:role,text:'Non converto gli euro in dollari del gioco. Scrivi un importo in dollari per il calcolatore.'});continue;}
  const n=number(raw);if(!n.valid){issues.push({kind:'amount',field:role,text:n.ambiguous?'Questo numero è ambiguo. Scrivi per esempio “1.500 $” o “1,5 milioni”.':'Questo importo non è leggibile. Scrivi un numero con la sua unità.'});continue;}
  if(!unit&&/[.,]/.test(raw)){issues.push({kind:'amount',field:role,text:'Dimmi l’unità: dollari, migliaia o milioni? Per esempio “1,5 milioni”.'});continue;}
  const value=n.value*(/^(m|millions?)$/.test(unit||'')?1e6:/^(k|mille)$/.test(unit||'')?1e3:1);
  if(value<0||value>1e12||!Number.isFinite(value)){issues.push({kind:'invalid',field:role,text:'L’importo deve essere tra 0 e 1.000 miliardi di dollari.'});continue;}
  money.push({value,role});if(role){if(own(values,role)&&values[role]!==value)issues.push({kind:'role',value,text:'Due numeri sembrano dire la stessa cosa. Dimmi cosa indica ciascuno.'});else values[role]=value;}else issues.push({kind:'role',value,text:E.dollars(new Intl.NumberFormat('it-IT').format(value))+', è quello che hai già o quello che vuoi avere?'});
 }
 if(money.length&&/€|\beuros?\b/.test(q)&&!issues.some(x=>x.text.includes('euros')))issues.push({kind:'invalid',text:'Non converto gli euro in dollari del gioco. Scrivi un importo in dollari per il calcolatore.'});
 if(!own(values,'target')&&/(?:vise|atteindre|veux|objectif)[^.!?]{0,28}\b(?:le|un) million\b/.test(q))values.target=1000000;
 return {values,issues,money};
}
/* v7.61 (Léo en espagnol) : pont vers le français. Léo comprend une autre langue en ramenant la question, mot à mot et
   expression par expression (la plus longue d'abord), au français que connaissent ses intentions et sa base ; les nombres
   à la manière de la langue (« 200.000 », « $200.000 ») sont réécrits à la française. Les réponses, elles, sont déjà dans la
   langue de la page (index généré par outils/leo-langues.cjs). */
function bridgeFrom(list,lang){if(!Array.isArray(list)||!list.length)return null;
 const fold=s=>String(s||'').normalize('NFD').replace(/[̀-ͯ]/g,'').toLowerCase().replace(/[’‘`´]/g,"'");
 /* v7.63 : en italien, l'élision (« l'auto », « dov'è ») se lit comme deux mots, dans le pont comme dans la question */
 const foldL=lang==='it'?(x=>fold(x).replace(/'/g,' ')):fold;
 const words=s=>foldL(s).split(/[^a-z0-9']+/).map(w=>w.replace(/^'+|'+$/g,'')).filter(Boolean);
 const map=new Map(),first=new Map();
 for(const pair of list){if(!Array.isArray(pair)||typeof pair[0]!=='string'||typeof pair[1]!=='string')continue;const k=words(pair[0]);if(!k.length||k.length>6)continue;const key=k.join(' ');if(!map.has(key))map.set(key,pair[1]);first.set(k[0],Math.max(first.get(k[0])||0,k.length));}
 return function(text){let t=foldL(text).replace(/[¿¡]/g,' ');
  if(lang==='es'||lang==='it'){t=t.replace(/\$\s*(\d[\d.,]*\d|\d)/g,'$1 $').replace(/\b(\d{1,3})((?:\.\d{3})+)(?![\d]|[.,]\d)/g,(m,a,b)=>a+b.replace(/\./g,' '));}
  const re=/[a-z0-9']+/g,toks=[];let m;while((m=re.exec(t)))toks.push({w:m[0].replace(/^'+|'+$/g,''),a:m.index,b:m.index+m[0].length});
  let out='',pos=0;
  for(let i=0;i<toks.length;){let hit=null;const max=Math.min(first.get(toks[i].w)||0,toks.length-i);
   for(let n=max;n>=1;n--){let ok=true;for(let j=1;j<n;j++)if(/[^\s]/.test(t.slice(toks[i+j-1].b,toks[i+j].a))){ok=false;break;}if(!ok)continue;const key=toks.slice(i,i+n).map(x=>x.w).join(' ');if(map.has(key)){hit={n,to:map.get(key)};break;}}
   if(hit){out+=t.slice(pos,toks[i].a)+hit.to;pos=toks[i+hit.n-1].b;i+=hit.n;}else i++;}
  return (out+t.slice(pos)).replace(/\s+/g,' ').trim();};}
const fill=(tpl,vars)=>String(tpl||'').replace(/\{(\w+)\}/g,(m,k)=>vars[k]===undefined||vars[k]===null?'':String(vars[k]));
const KIND_PRIORITY={character:.32,business:.3,property:.3,hideout:.3,place:.28,vehicle:.22,weapon:.22,boats:.18,style:.18,customizations:.18,garages:.18,collectible:.1};
function create(data,options={}){
 if(!data||data.schemaVersion!==2||!Array.isArray(data.knowledge)||!Array.isArray(data.names)||!data.shards||!data.lexique||!Array.isArray(data.categories)||!Array.isArray(data.definitions)||!Array.isArray(data.faq)||!data.texts||!data.templates)throw Error('Le risposte locali non sono disponibili.');
 /* v7.61 (langues) : noyau d'une autre langue (en/leo-index.json) : la question est d'abord réécrite en français (N.pivot), les textes affichés viennent déjà traduits */
 const PIV=data.lang&&data.lang!=='fr'&&Array.isArray(data.pivot)&&N.pivotTable?N.pivotTable(data.pivot,data.lang):null,piv=q=>PIV&&typeof q==='string'?N.pivot(q,PIV):q;let said=null;
 const load=typeof options.load==='function'?options.load:null,texts=data.texts,tpl=data.templates,common=tpl.common||{},official=data.official||{};
 /* v7.61 : langue de l'index (« lang », « prefix » : /es), pont de la question vers le français, mots vides de la langue */
 const LANG=typeof data.lang==='string'?data.lang:'fr',PFX=typeof data.prefix==='string'?data.prefix:'',unprefix=p=>PFX&&typeof p==='string'&&p.startsWith(PFX+'/')?p.slice(PFX.length):p,bridge=LANG==='fr'?null:bridgeFrom(data.bridge,LANG);let lastOriginal='';
 const analyzer=N.createAnalyzer({abbreviations:data.lexique.abbreviations.map(([f,to])=>({f,to})),english:data.lexique.english.map(([f,to])=>({f,to})),concepts:data.lexique.concepts,stop:Array.isArray(data.lexique.stop)?data.lexique.stop:[]});
 const categories=data.categories.filter(x=>safeURL(x.route)),tools=data.tools;
 /* v7.58 : la catégorie dont le terme reconnu est le plus long l'emporte (« voiture de sport » → Voitures de sport, pas Véhicules) */
 const catTerms=categories.map(c=>({c,terms:c.terms.map(t=>{const ct=clean(t);return {len:ct.length,re:new RegExp('(?:^| )'+escape(ct)+'(?: |$)')};})}));/* expressions compilées une fois */
 const category=q=>{const cq=clean(q);let best=null,len=0;for(const {c,terms} of catTerms)for(const t of terms){if(t.len>len&&t.re.test(cq)){best=c;len=t.len;}}return best;};
 const questionLike=q=>/\?|^(?:qui|quand|ou|comment|pourquoi|combien|quel|quelle|quels|quelles|est ce|c est quoi|c'est quoi|y a t il|y a t'il|peut on|on peut|est il|est elle|sont ils|a t on|dis moi|explique|parle moi|raconte|il y a|existe)\b/.test(q);
 /* ---------- état : fiches chargées, base de questions, index ---------- */
 const items=[],byKey=new Map(),loaded=new Set(),knowledge=[...data.knowledge];let kIndex=null,pIndex=null,passages=[];
 const nameIndex=new Map(),entities=[],seqEntities=[];/* entités connues par leur nom (petites familles dans le noyau, grandes familles dès leur chargement) */
 const prefixSets={},prefixLists={};for(const [name,s] of Object.entries(data.shards))if(Array.isArray(s.vocab)){prefixSets[name]=new Set(s.vocab);prefixLists[name]=[...prefixSets[name]];}
 const sig=N.SIG;
 /* Nom d'une fiche → entité reconnue dans les questions. Les jetons viennent de N.nameTokens (déjà calculés par gen-leo.cjs pour les grandes familles : pre = « jetons|repères »). */
 /* v7.61 : nameFr = nom français d'une fiche dont le nom affiché est traduit (en/leo-index.json) : c'est lui qui est reconnu, comme sur le site français */
 function registerEntity(key,label,kind,aliases,shard,pre,nameFr){let nt=null;if(typeof pre==='string'&&pre.includes('|')){const [a,b]=pre.split('|');nt={toks:a.split(' ').filter(Boolean),minor:b.split(' ').filter(Boolean),seqs:null};if(!nt.toks.length)nt=null;}if(!nt)nt=N.nameTokens(analyzer,nameFr||label);if(!nt)return;
  if(nt.seqs){const e={key,name:label,kind,shard,toks:nt.toks,alts:[],minor:[],seqs:nt.seqs,idx:entities.length};entities.push(e);seqEntities.push(e);return;}
  /* v7.58 : un alias d'un seul mot ne vaut pas pour une ligne de catalogue (« sport », « course », « peintures » détournaient les questions) */
  const alts=(aliases||[]).map(a=>analyzer.analyze(a).terms.filter(sig)).filter(a=>a.length&&!(a.length===1&&a[0].length<5&&kind!=='character')&&!(a.length===1&&/^catalogue-/.test(kind)));const e={key,name:label,kind,shard,toks:nt.toks,alts,minor:nt.minor,idx:entities.length};entities.push(e);for(const t of new Set([...nt.toks,...alts.flat()])){if(!nameIndex.has(t))nameIndex.set(t,[]);nameIndex.get(t).push(e.idx);}}
 for(const [key,name,kind,aliases,nameFr] of data.names)registerEntity(key,name,kind,aliases,kind==='weapon'?'armes':'monde',undefined,nameFr);
 /* documents d'un sujet : livrés déjà analysés par gen-leo.cjs (d, dq, dk) ; sinon analysés ici une seule fois (données de test) */
 const docsOf=new WeakMap();function topicDocs(t){if(!docsOf.has(t)){const split=x=>String(x).split(' ').filter(Boolean);let d;if(Array.isArray(t.d)){d=t.d.map((x,i)=>[split(x),{i}]);d.push([split(t.dq||''),{q:true}]);if(t.dk)d.push([split(t.dk),{k:true}]);}else{d=(t.f||[]).map((f,i)=>[analyzer.analyze(f).terms,{i}]);d.push([analyzer.analyze(t.q).terms,{q:true}]);if(t.k&&t.k.length)d.push([[...new Set(t.k.flatMap(k=>analyzer.analyze(k).terms))],{k:true}]);}docsOf.set(t,d);}return docsOf.get(t);}
 function buildKnowledgeIndex(){kIndex=N.createIndex();for(const t of knowledge)for(const [terms,meta] of topicDocs(t))kIndex.add(t.id,terms,meta);kIndex.finish();}
 buildKnowledgeIndex();
 const knowledgeById=()=>new Map(knowledge.map(t=>[t.id,t]));let kById=knowledgeById();
 function addShard(name,json){if(!json||json.schemaVersion!==2||json.shard!==name)throw Error('Frammento locale non valido: '+name);if(json.revision!==data.revision)throw Error('Frammento locale scaduto: '+name);
  if(name==='passages'){passages=(json.items||[]).filter(p=>p&&typeof p.x==='string'&&safeURL(p.p));pIndex=N.createIndex();passages.forEach((p,i)=>pIndex.add(i,typeof p.s==='string'?p.s.split(' ').filter(Boolean):analyzer.analyze(p.h+' '+p.x).terms));pIndex.finish();return;}
  if(json.knowledge){for(const t of json.knowledge)if(!kById.has(t.id))knowledge.push(t);kById=knowledgeById();buildKnowledgeIndex();return;}
  const proofs=json.proofs||[],sources=json.sources||[],labels=json.labels||[];
  const list=json.packed?json.items.map(a=>{const o={};json.packed.forEach((k,i)=>o[k]=a[i]);return {key:'map:'+o.id,id:o.id,kind:'place',shard:'lieux',name:o.name,aliases:[],region:o.region||null,category:'Luogo censito'+(o.region?' · '+o.region:''),url:'/it/carte.html#lieu='+o.id,image:o.image===1?'/photos/'+String(o.id).replace(/^g-/,'')+',ig.webp':(o.image||null),calcId:null,price:null,proof:o.proof,real:o.real||null,st:o.st||null,nt:o.nt||null};}):json.items.map(x=>({...x,shard:name}));
  for(const x of list){if(!x||!L.safeId(x.key)||typeof x.name!=='string'||x.name.length>220||!safeURL(x.url)||byKey.has(x.key))continue;const it={...x,proof:typeof proofs[x.proof]==='string'?proofs[x.proof]:'Informazione da verificare nella scheda.',source:typeof x.source==='number'?sources[x.source]||null:(x.source||null),famLabel:typeof x.famLabel==='number'?labels[x.famLabel]||null:x.famLabel||null,catLabel:typeof x.catLabel==='number'?labels[x.catLabel]||null:x.catLabel||null,aliases:(x.aliases||[]).filter(a=>typeof a==='string'&&a.length<500),n:clean(x.name)};it.a=it.aliases.map(clean);items.push(it);byKey.set(it.key,it);if(name==='lieux'||name==='vehicules'||name==='catalogues')registerEntity(it.key,it.name,it.kind,it.aliases,name,x.nt,typeof x.nameFr==='string'?x.nameFr:undefined);}}
 const shardOfKey=key=>({vehicle:'vehicules',weapon:'armes',map:'lieux',catalogue:'catalogues'})[String(key).split(':')[0]]||'monde';
 /* un morceau déjà en route n'est pas demandé deux fois (préchargement pendant la frappe + question envoyée) */
 const inflight=new Map();
 async function loadShard(name){if(loaded.has(name)||!data.shards[name])return false;if(!load)throw Error('Caricamento locale non disponibile.');if(inflight.has(name))return inflight.get(name);const p=(async()=>{const json=await load(name,data.shards[name].file);if(!loaded.has(name)){addShard(name,json);loaded.add(name);}return true;})();inflight.set(name,p);try{return await p;}finally{inflight.delete(name);}}
 async function loadAll(){for(const name of Object.keys(data.shards))await loadShard(name);}
 /* Quels morceaux une question vise-t-elle ? Un jeton de la question (ou son rapprochement) présent dans le vocabulaire d'un morceau le désigne ; un nom du noyau désigne son morceau.
    Un mot de six lettres ou plus à une faute près d'un mot du vocabulaire (« emperr », « kamasho ») désigne aussi le morceau : une fiche mal orthographiée en première question est retrouvée. */
 function needs(query){const A=analyzer.analyze(piv(query)),out=new Set();const terms=A.terms.filter(t=>t.length>=3);
  for(const t of terms){const p=t.slice(0,6);for(const [name,set] of Object.entries(prefixSets))if(!loaded.has(name)&&set.has(p))out.add(name);
   const alt=kIndex.nearest(t)?.term;if(alt&&alt!==t){const ap=alt.slice(0,6);for(const [name,set] of Object.entries(prefixSets))if(!loaded.has(name)&&set.has(ap))out.add(name);}
   if(t.length>=6&&!/\d/.test(t)&&!N.STOP.has(t))for(const [name,list] of Object.entries(prefixLists)){if(loaded.has(name)||out.has(name)||prefixSets[name].has(p))continue;if(list.some(v=>v.length>=5&&N.distance(p,v,1)<=1))out.add(name);}
   for(const e of entityHits(t))if(!loaded.has(e.shard))out.add(e.shard);}
  for(const [q,shard] of data.seqNames||[])if(!loaded.has(shard)&&seqHit(A,[q]).length)out.add(shard);
  return [...out];}
 const entityHits=t=>(nameIndex.get(t)||[]).map(i=>entities[i]);
 const seqHit=(A,list)=>{const j=' '+A.raw.join(' ')+' ';return list.filter(x=>j.includes(' '+x+' '));};
 async function prepare(query){await Promise.all(needs(query).map(loadShard));}
 /* ---------- entités nommées dans la question ---------- */
 function nearestName(t){if(nameIndex.has(t)||t.length<5||/\d/.test(t)||kIndex.has(t))return null;let best=null;const max=t.length<=6?1:2;for(const c of nameIndex.keys()){if(Math.abs(c.length-t.length)>max)continue;const d=N.distance(t,c,max);if(d<=max&&(!best||d<best.d))best={term:c,d};}if(!best)return null;/* « animaus » est plus près d'« animaux » (questions rédigées) que de « Nimbus » : un mot que la base corrige aussi bien n'est pas un nom de fiche */const k=kIndex.nearest(t);if(k&&k.term!==t&&k.distance<=best.d)return nameIndex.has(k.term)?k.term:null;return best.term;}
 const rare=t=>(nameIndex.get(t)||[]).length<=2&&!kIndex.has(t);
 function detectEntities(A){const exactSet=new Set(A.terms.filter(sig)),present=new Set(exactSet),rawSet=new Set(A.raw);for(const t of [...exactSet]){const alt=nearestName(t);if(alt)present.add(alt);}
  const seen=new Map();for(const t of present)for(const e of entityHits(t)){if(seen.has(e.idx))continue;const full=(toks)=>toks.length&&toks.every(x=>present.has(x));const partial=(toks)=>toks.filter(x=>present.has(x)).length;
   let matched=partial(e.toks);const strict=full(e.toks),rareHit=e.toks.some(x=>present.has(x)&&rare(x)&&x.length>=6);let isFull=strict||(matched>=2&&matched>=e.toks.length-1&&rareHit)||(e.toks.length===2&&matched===1&&rareHit);let via='name';if(!isFull)for(const a of e.alts)if(full(a)){isFull=true;matched=Math.max(matched,a.length);via='alias';break;}
   /* v7.54 : un mot (6 lettres au moins) qui ne désigne qu’une seule fiche du site suffit à la reconnaître (« la cheetah »). */
   if(!isFull&&matched===1&&!/^catalogue-/.test(e.kind)){const only=e.toks.find(x=>exactSet.has(x)&&x.length>=6&&entityHits(x).length===1&&(e.shard!=='lieux'||!kIndex.has(x)));/* un lieu de la carte au nom courant (« Gallery of Legends ») ne se reconnaît pas sur un mot des questions rédigées ; une fiche (« la cheetah ») si */if(only){isFull=true;via='single';}}
   if(!matched)continue;if(!isFull&&e.toks.length===1)continue;if(!isFull&&matched<2)continue;const exact=via!=='alias'?e.toks.filter(x=>present.has(x)).every(x=>exactSet.has(x)):e.alts.some(a=>a.every(x=>exactSet.has(x)));const item=byKey.get(e.key)||null;seen.set(e.idx,{e,item,key:e.key,kind:e.kind,name:e.name,full:isFull,strict:strict||via==='alias',exact,matched,via,score:(isFull?2:1)*matched+(e.shard==='lieux'?.2:(KIND_PRIORITY[e.kind]||.1))+(exact?.02:0)+(isFull&&e.minor.length?0.3*(e.minor.filter(m=>rawSet.has(m)).length*2-e.minor.length):0)});}
  for(const e of seqEntities){if(seen.has(e.idx)||!seqHit(A,e.seqs).length)continue;const item=byKey.get(e.key)||null;seen.set(e.idx,{e,item,key:e.key,kind:e.kind,name:e.name,full:true,strict:true,exact:true,matched:e.toks.length,via:'name',score:2*e.toks.length+(KIND_PRIORITY[e.kind]||.1)+.02});}
  let list=[...seen.values()];list=list.filter(x=>!list.some(y=>y!==x&&y.strict&&y.via==='name'&&x.full&&y.e.toks.length>x.e.toks.length&&x.e.toks.every(t=>y.e.toks.includes(t))));list.sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name,'fr'));return list;}
 /* ---------- intentions ---------- */
 function intentsOf(A,q){const s=' '+A.expanded.join(' ')+' ',set=new Set();const has=re=>re.test(s);
  if(has(/ (?:prix|cher|gratuit|gratuite|tarif) /)||/combien (?:ca |ça )?(?:coute|vaut)|cb coute|vaut combien|combien pour/.test(q))set.add('price');
  if(has(/ ou (?:est|sont|se trouve|se trouvent|c est|trouver|se situe|situe|aller|habite|vit|la trouver|le trouver|les trouver|l acheter|acheter|manger|boire) |^ ou /)||has(/ (?:localiser|localise|emplacement|position|centrer|centre la carte|montre moi|montre|sur la carte|situe) /)||/\bou\b.*\?$/.test(q)&&!/\bou bien\b/.test(q))set.add('where');
  if(has(/ (?:comment aller|comment y aller|se rendre|trajet|itineraire|chemin) /)||/aller a |aller au |aller aux /.test(s))set.add('go');
  if(has(/ (?:c est quoi|c est qui|qu est ce|qui est|qui sont|explique|definition|presente|parle moi|raconte|decris|ca veut dire|signifie|kesako) /)||/^ (?:c est|qui|quoi) /.test(s))set.add('what');
  if(has(/ (?:inspiration|inspire|inspiree|ressemble|ressemblent|dans la vraie vie|vraie voiture|vrai modele|equivalent|modele reel|copie|reel|reelle|base sur|basee sur) /)||/quelle vraie|c est quelle voiture|en vrai/.test(q))set.add('insp');
  if(has(/ (?:edition ultimate|edition standard|pack vintage|precommande|bonus|exclusif|exclusive|exclusifs|reserve|reservee|reserves|edition) /))set.add('ultimate');
  if(has(/ (?:vitesse|rapide|rapides|acceleration|performance|performances|stats|statistiques|statistique|puissance|puissante|degats|cadence) /))set.add('speed');
  if(has(/ (?:munitions|munition|calibre|portee|cartouche|cartouches) /))set.add('ammo');
  if(has(/ (?:personnalisation|personnalisations|personnaliser|personnalise|amelioration|ameliorations|ameliorer|accessoire|accessoires|modifier|modif|modifs|jantes|peinture|silencieux|viseur|chargeur|turbo|blindage) /))set.add('custom');
  if(has(/ (?:effet|effets|sert a quoi|ca fait quoi|redonne|rend de la vie|utilite|utile) /))set.add('effect');
  if(has(/ (?:a qui|de qui|qui porte|qui a cette|quel personnage|arme de) /))set.add('owner');
  if(has(/ (?:habite|habitent|vit|vivent|maison|appartement|domicile|adresse|chez|planque de|loge) /))set.add('home');
  if(has(/ (?:vehicule|vehicules|voiture|voitures|moto|motos|caisse|pickup|conduit|roule|bateau|kayak) /))set.add('vehicles');
  if(has(/ (?:arme|armes|pistolet|pistolets|revolver|fusil|flingue) /))set.add('weapon');
  return set;}
 const priorityIntent=set=>['price','go','where','insp','ultimate','speed','ammo','custom','effect','owner','home','vehicles','weapon','what'].find(i=>set.has(i))||null;
 /* intention de la question canonique d'un sujet (« Combien coûte un soda… ? » → prix), calculée une fois */
 const topicIntentCache=new Map();const topicIntent=t=>{if(!topicIntentCache.has(t.id)){const q=norm(t.q);topicIntentCache.set(t.id,priorityIntent(intentsOf(analyzer.analyze(t.q),q)));}return topicIntentCache.get(t.id);};
 /* ---------- hors sujet ---------- */
 const offWords=new Set((data.offtopic?.words||[]).map(w=>analyzer.analyze(w).expanded.filter(t=>!N.STOP.has(t)).join(' ')).filter(Boolean)),offPhrases=(data.offtopic?.phrases||[]).map(p=>N.raw(p).join(' '));
 function offTopicMarker(A){const joined=' '+A.expanded.filter(t=>!N.STOP.has(t)).join(' ')+' ',rawJoined=' '+A.raw.join(' ')+' ';for(const p of offPhrases)if(rawJoined.includes(' '+p+' '))return {word:p,phrase:true};for(const w of offWords)if(joined.includes(' '+w+' '))return {word:w,phrase:false};return null;}
 /* ---------- liens et réponses cadres ---------- */
 const externalFor=kind=>{const pick=k=>official[k]?[{label:official[k].label,url:official[k].url}]:[];const map={character:'personnages',place:'lieux',edition:'ultimate',media:'videos',news:'newswire'};const l=[...pick(map[kind]||'site')];if(!l.some(x=>x.url===official.site?.url)&&official.site)l.push({label:official.site.label,url:official.site.url});return l;};
 const officialFor=entity=>{if(!entity)return null;const id=entity.key.split(':')[1];if(official[id])return [{label:official[id].label,url:official[id].url},...(official.site?[{label:official.site.label,url:official.site.url}]:[])];return null;};
 const empty=()=>({selected:[],values:{}});
 const remember=(context,patch)=>{const recent=Array.isArray(context.recent)?context.recent.slice(-5):[];recent.push(patch);return recent;};
 const reportLink=(query,answerText,page)=>{const p=new URLSearchParams({motif:'leo',question:String(bridge&&lastOriginal?lastOriginal:query).slice(0,300),reponse:String(answerText||'').slice(0,300),...(page?{page}:{})});/* après #, jamais après ? : la question et la réponse ne sont pas envoyées au serveur en ouvrant Contact, elles restent dans le navigateur */return '/it/contact.html#'+p.toString();};
 function knowledgeAnswer(t,context,extra={}){const links=[...t.links];for(const l of extra.links||[])if(!links.some(x=>x.url===l.url))links.push(l);/* la source officielle la plus précise : celle de la fiche citée quand le sujet n'a que l'accueil Rockstar */const source=(t.source&&t.source!==data.official?.site?.url)?t.source:(safeSource(extra.source)||t.source||undefined);return {kind:'answer',topic:t.id,question:t.q,text:t.text,links,status:t.status||undefined,source,verifiedAt:t.verifiedAt||data.checkedAt||undefined,action:t.action||undefined,context:{...empty(),recent:remember(context,{topic:t.id,entity:extra.entityKey||null,intent:extra.intent||null})}};}
 function notFound(query,context,hints={}){const links=[];if(hints.route)links.push({label:hints.routeLabel||common.hub||'Vedi la sezione',url:hints.route});if(hints.topic){const t=kById.get(hints.topic);if(t&&t.links[0]&&!links.some(x=>x.url===t.links[0].url))links.push({label:t.links[0].label,url:t.links[0].url});}links.push({label:common.search||'Cerca nel sito',url:'/it/index.html#q'});
  return {kind:'unknown',text:texts.notFound,links,external:hints.external||externalFor(hints.kind||'site'),report:reportLink(PIV&&said?said:query,texts.notFoundShort,hints.page),context:{...empty(),recent:context.recent||[]}};}
 function refusal(query,context,page){const sug=(data.suggestions?.default||[]).slice(0,2);return {kind:'refusal',text:texts.offTopic,choices:sug,links:[{label:common.search||'Cerca nel sito',url:'/it/index.html#q'}],external:externalFor('site'),report:reportLink(query,texts.offTopic,page),context:{...empty(),recent:context.recent||[]}};}
 /* ---------- gabarits par famille ---------- */
 const label=x=>x.category?x.category.replace(/^(?:Véhicule|Arme|Lieu recensé|Vehículo|Arma|Lugar registrado|Veicolo|Luogo censito) · /,''):'';
 const fmtMoney=n=>Number.isFinite(n)?E.dollars(new Intl.NumberFormat('it-IT',{maximumFractionDigits:0}).format(n),' '):'—',fmtHours=n=>{if(!Number.isFinite(n))return '—';const m=Math.ceil(n*60-1e-8);return m<60?m+' min':Math.floor(m/60)+' h'+(m%60?' '+String(m%60).padStart(2,'0')+(data.lang==='de'?' min':''):'');};
 /* v7.59 (check ultime, CALC-13) : un prix publié se dit avec son statut en français, sa source et sa date (champs posés par
    outils/gen-leo.cjs depuis le schéma unique) ; même phrase pour un véhicule, une arme, une entreprise, une demeure ou une planque. */
 const dayText=d=>{if(!/^\d{4}-\d{2}-\d{2}/.test(d||''))return '';const [y,m,j]=d.split('-').map(Number);const M=['janvier','febbraio','mars','avril','mai','juin','juillet','agosto','septembre','octobre','novembre','dicembre'];return (j===1?'1er':j)+' '+M[m-1]+' '+y;};
 const knownPrice=(it,T)=>typeof it.price==='number'&&T.priceKnown?fill(T.priceKnown,{name:it.name,price:new Intl.NumberFormat('it-IT').format(it.price),priceStatus:it.priceStatus||'stato della scheda',priceSource:it.priceSource?fill(T.priceSourceLine||' · fonte: {source}',{source:it.priceSource}):'',priceDate:it.priceVerifiedAt?fill(T.priceDateLine||' · verificato il {date}',{date:dayText(it.priceVerifiedAt)}):''}):null;
 function templateAnswer(hit,intent,query,context,options){const it=hit.item;if(!it)return null;const fam=it.kind==='vehicle'?'vehicle':it.kind==='weapon'?'weapon':it.kind==='place'&&it.shard==='lieux'?'place':it.shard==='catalogues'?'catalogue':['boats','style','customizations','garages','vetements','accessoires','tatouages','nourriture','munitions','logements'].includes(it.kind)?'acquisition':'world';const T=tpl[fam]||{},name=it.name;const links=[{label:common.fiche||'Apri la scheda',url:it.url}];if(it.mapUrl&&safeURL(it.mapUrl))links.push({label:common.map||'Apri il segnaposto sulla mappa',url:it.mapUrl});
  const base=(text,more={})=>({kind:'answer',text,links,status:more.status||it.proof,source:it.source||undefined,verifiedAt:it.verifiedAt||undefined,entity:it.key,...more,context:{...empty(),selected:[it.key],recent:remember(context,{entity:it.key,intent})}});
  if(fam==='vehicle'){const cat=it.cat||'';
   if(intent==='price'){const kp=knownPrice(it,T);if(kp)return base(kp,{selected:[it.key],request:it.calcId?{v:1,tool:'purchase',values:{},items:[it.calcId]}:undefined});return base(fill(T.price,{name}),{selected:[it.key],request:it.calcId?{v:1,tool:'purchase',values:{},items:[it.calcId]}:undefined,links:[...links,{label:common.tool||'Prova un acquisto con il mio prezzo',url:'/it/calculateurs.html?tool=purchase#atelier',tool:'purchase'}]});}
   if(intent==='insp')return base(it.inspiration?fill(T.insp,{name,inspiration:it.inspiration}):fill(T.noInsp,{name}));
   if(intent==='where'||intent==='go')return base(fill(T.where,{name,seen:it.seen||'media ufficiali'}),{links:[...links,{label:common.where||'Dove trovarli sulla mappa',url:'/it/vehicules.html#carte'}]});
   if(intent==='ultimate')return base(it.edition?fill(T.ultimateYes,{name,condition:it.edition}):fill(T.ultimateNo,{name}),{links:[...links,{label:common.rare||'Veicoli rari ed esclusivi',url:'/it/vehicules-rares.html'}]});
   if(intent==='speed')return base(fill(T.speed,{name}),{links:[...links,{label:common.ranking||'La classifica dei veicoli',url:'/it/classement-vehicules.html'}]});
   if(intent==='custom')return base(fill(T.custom,{name}),{links:[...links,{label:common.custom||'Personalizza questo veicolo',url:'/it/personnalisations.html#perso-vehicules='+cat}]});
   return base(fill(T.what,{name,category:label(it),proof:it.proof,insp:it.inspiration?fill(T.inspLine,{inspiration:it.inspiration}):''}),{results:[it],links:[...links,{label:common.custom||'Personalizza questo veicolo',url:'/it/personnalisations.html#perso-vehicules='+cat}]});}
  if(fam==='weapon'){const cat=it.cat||'';
   if(intent==='price'){const kp=knownPrice(it,T);return base(kp||fill(T.price,{name}),{selected:[it.key],request:it.calcId?{v:1,tool:'purchase',values:{},items:[it.calcId]}:undefined});}
   if(intent==='insp')return base(it.inspiration?fill(T.insp,{name,inspiration:it.inspiration}):fill(T.noInsp,{name}));
   if(intent==='where'||intent==='go')return base(fill(T.where,{name,seen:it.seen||'media ufficiali'}),{links:[...links,{label:common.hub||'Vedi la sezione',url:'/it/armes.html'}]});
   if(intent==='ultimate')return base(it.ultimate?fill(T.ultimateYes,{name}):fill(T.ultimateNo,{name}),{links:[...links,{label:'Personalizzazione delle armi',url:'/it/personnalisations.html#perso-armes'}]});
   if(intent==='ammo'||intent==='speed')return base(fill(T.ammo,{name,ammo:it.ammo||'munizione non specificata',range:it.range||'non specificata'}),{links:[...links,{label:'Le munizioni',url:'/it/armes.html#munitions'}]});
   if(intent==='custom')return base(fill(T.custom,{name}),{links:[...links,{label:common.customWeapon||'Accessori compatibili',url:'/it/personnalisations.html#perso-armes='+cat}]});
   if(intent==='owner')return base(it.owner?fill(T.owner,{name,owner:it.owner}):fill(T.what,{name,category:label(it),proof:it.proof,context:'',insp:''}));
   return base(fill(T.what,{name,category:label(it),proof:it.proof,context:it.context?fill(T.contextLine,{context:it.context}):'',insp:it.inspiration?fill(T.inspLine,{inspiration:it.inspiration}):''}),{results:[it],links:[...links,{label:common.customWeapon||'Accessori compatibili',url:'/it/personnalisations.html#perso-armes='+cat}]});}
  if(fam==='place'){const region=it.region?fill(T.regionLine,{region:it.region}):'';const mapLinks=[{label:common.map||'Apri il segnaposto sulla mappa',url:it.url}];
   if(intent==='price')return base(fill(T.price,{name}),{links:mapLinks,action:{type:'map',id:it.id,url:it.url}});
   if(intent==='go')return base(fill(T.go,{name,region}),{links:[...mapLinks,{label:common.distance||'Misura una distanza sulla mappa',url:'/it/carte.html'}],action:{type:'map',id:it.id,url:it.url}});
   if(intent==='where'||intent==='home')return base(fill(T.where,{name,region,proof:it.proof}),{links:mapLinks,action:{type:'map',id:it.id,url:it.url}});
   return base(fill(T.what,{name,category:label(it),region,proof:it.proof,real:it.real?fill(T.real,{real:it.real}):''}),{results:[it],links:mapLinks,action:{type:'map',id:it.id,url:it.url}});}
  if(fam==='catalogue'){const cat=(it.famLabel?it.famLabel+' · ':'')+(it.catLabel||'');
   if(intent==='price'){const kp=knownPrice(it,T);if(kp)return base(kp.replace('{repere}',it.repere?fill(T.repere,{value:it.repere}):''),{status:'Prezzo GTA VI pubblicato: '+(it.priceStatus||'')+' · '+(it.statut||'')});return base(fill(T.price,{name,repere:it.repere?fill(T.repere,{value:it.repere}):T.noRepere}),{status:'Colonna GTA VI: da confermare · '+(it.statut||'')});}
   if(intent==='where'||intent==='go'||intent==='home'){const places=(it.places||[]);if(!places.length)return base(fill(T.noWhere,{name}));const mapL=places.filter(p=>p.id).slice(0,3).map(p=>({label:'Mappa: '+p.name,url:'/it/carte.html#lieu='+p.id}));return base(fill(T.placeList,{name,places:places.map(p=>p.name||p.type).join('; ')}),{links:[...links,...mapL]});}
   if(intent==='effect')return base(fill(T.effect,{name,effect:it.effect||'effetto non pubblicato'}));
   if(intent==='ultimate')return base(it.edition?fill(T.ultimateYes,{name,source:it.edition}):fill(T.ultimateNo,{name}));
   return base(fill(T.what,{name,category:cat,description:it.description||it.proof})+(it.effect?' '+fill(T.effect,{name:'Effetto',effect:it.effect}):''),{results:[it]});}
  if(fam==='acquisition'){if(intent==='price')return base(fill(T.price,{name,condition:it.edition||it.proof}));if(intent==='ultimate')return base(fill(T.ultimateYes,{name,condition:it.edition||it.proof}));return base(fill(T.what,{name,description:it.description||it.proof,condition:it.edition||''}),{results:[it]});}
  /* monde : régions, personnages, entreprises, demeures, planques */
  const rel=it.related||{};
  if(intent==='price'){const kp=knownPrice(it,T);if(kp)return base(kp,{selected:[it.key],request:it.calcId?{v:1,tool:'purchase',values:{},items:[it.calcId]}:undefined});if(it.calcId)return null;return base(fill(T.price,{name,proof:it.proof}),{links:[...links,{label:common.tool||'Prova un acquisto con il mio prezzo',url:'/it/calculateurs.html?tool=purchase#atelier',tool:'purchase'}]});}
  if(intent==='where'||intent==='go'){if(it.mapUrl&&safeURL(it.mapUrl))return base(fill(T.where,{name}),{action:{type:'map',id:it.mapId,url:it.mapUrl}});if(it.kind==='character'&&rel.home){const home=byKey.get('property:'+rel.home);if(home)return base(fill(T.home,{name,home:home.name}),{links:[{label:common.fiche||'Apri la scheda',url:home.url},...(home.mapUrl?[{label:common.map,url:home.mapUrl}]:[])],action:home.mapUrl?{type:'map',id:home.mapId,url:home.mapUrl}:undefined});}return base(fill(T.noWhere,{name}));}
  if(intent==='home'){if(it.kind==='character'){const home=rel.home?byKey.get('property:'+rel.home):null;if(home)return base(fill(T.home,{name,home:home.name}),{links:[{label:common.fiche||'Apri la scheda',url:home.url},...(home.mapUrl?[{label:common.map,url:home.mapUrl}]:[])],action:home.mapUrl?{type:'map',id:home.mapId,url:home.mapUrl}:undefined});return base(fill(T.noHome,{name}));}if(it.mapUrl)return base(fill(T.where,{name}),{action:{type:'map',id:it.mapId,url:it.mapUrl}});}
  if(intent==='vehicles'&&it.kind==='character'){const vs=(rel.vehicles||[]).map(id=>byKey.get('vehicle:'+id)).filter(Boolean);if(vs.length)return base(fill(T.vehicles,{name,vehicles:vs.map(v=>v.name).join(', ')}),{links:[...links,...vs.map(v=>({label:v.name,url:v.url}))]});if((rel.vehicles||[]).length)return {kind:'needs',shards:['vehicules']};return base(fill(T.noVehicles,{name}));}
  if(intent==='weapon'&&it.kind==='character'){if(!loaded.has('armes'))return {kind:'needs',shards:['armes']};const ws=items.filter(w=>w.kind==='weapon'&&w.owner===it.name);if(ws.length)return base(fill(T.weapon,{name,weapons:ws.map(w=>w.name).join(', ')}),{links:[...links,...ws.map(w=>({label:w.name,url:w.url}))]});return base(fill(T.noWeapon,{name}));}
  if(intent==='ultimate')return base(it.ultimate?fill(T.ultimateYes,{name,description:it.ultimate}):it.edition?fill(T.ultimateYes,{name,description:it.edition}):fill(T.ultimateNo,{name}));
  const desc=it.description||it.proof;return base((it.tagline&&!desc.startsWith(it.tagline.slice(0,30))?fill(T.tagline,{tagline:it.tagline}):'')+fill(T.what,{description:desc}),{results:[it]});}
 /* ---------- recherche v1 (conservée) ---------- */
 function search(query,kind,offset=0){const n=clean(query);if(!n)return {items:[],total:0};const words=n.split(' ').filter(w=>w.length>=3&&!N.STOP.has(w));if(!words.length)return {items:[],total:0};const r=[];for(const x of items){if(kind&&kind!==x.kind&&!(kind==='boats'&&/bateau|kayak/.test(clean(x.category+' '+x.name)))&&!(kind==='aircraft'&&/avion/.test(x.category))&&!(kind==='helicopter'&&/helico/.test(x.category)))continue;let score=x.n===n?100:x.a.includes(n)?94:x.n.startsWith(n+' ')?90:x.a.some(a=>a.startsWith(n))?78:x.n.includes(n)?75:words.every(w=>(x.n+' '+x.a.join(' ')).includes(w))?65:0;let fuzzy=false;if(!score&&words.length===1&&n.length>=5&&x.n.split(' ').some(w=>near(n,w))){score=35;fuzzy=true;}if(score)r.push({item:x,score,fuzzy});}r.sort((a,b)=>b.score-a.score||a.item.name.localeCompare(b.item.name,'fr'));return {items:r.slice(offset,offset+4).map(x=>({...x.item,fuzzy:x.fuzzy})),total:r.length};}
 function entityMatches(q,includeAll=false){const n=' '+clean(q)+' ',found=items.filter(x=>(includeAll||x.calcId)&&[x.n,...x.a.filter(a=>a.length>=5&&!/\d{4}/.test(a))].some(name=>name.length>=4&&n.includes(' '+name+' ')));const longest=found.filter(x=>!found.some(y=>y!==x&&y.n.includes(x.n)&&y.n.length>x.n.length));return [...new Map(longest.map(x=>[x.calcId||x.key,x])).values()];}
 const toolURL=t=>'/it/calculateurs.html?tool='+t+'#atelier';
 function ownedInCarnet(item){try{const fam=item&&({vehicle:'vehicules',weapon:'armes'})[item.kind];if(!fam||!item.calcId||typeof localStorage==='undefined')return false;const raw=localStorage.getItem('lk_own_'+fam);if(!raw)return false;const o=JSON.parse(raw);return !!(o&&typeof o==='object'&&o[item.calcId]);}catch(e){return false;}}
 function preview(tool,values,selected){if(!E)return '';const v=values||{};const has=k=>Number.isFinite(v[k]);try{
  if((tool==='goal'||tool==='plan')&&has('capital')&&has('target')&&has('hourly')){const r=E.goalContinuous({capital:v.capital,target:v.target,hourly:v.hourly,reserve:v.reserve||0,dailyMinutes:has('dailyMinutes')?v.dailyMinutes:undefined});if(!r.valid)return '';if(r.missing===0)return 'Con questi numeri, hai già abbastanza per arrivare a questa somma.';return 'Con questi numeri, il calcolatore dice: ti mancano '+fmtMoney(r.missing)+', cioè '+fmtHours(r.hours)+' di gioco'+(r.days!==null?' ('+r.days+(r.days>1?' partite':' partita')+' da '+fmtHours(v.dailyMinutes/60)+')':'')+', se guadagni sempre la stessa cifra.';}
  /* v7.51 : l’aperçu « Mon temps de jeu » passe par le moteur du calculateur (inverse : ton gain par heure réparti minute par minute), plus par une formule à part. */
  if(tool==='session'&&has('minutes')&&has('hourly')){const r=E.inverse({minutes:v.minutes,capital:has('capital')?v.capital:0,reserve:0,activity:{reward:v.hourly/60,duration:1}});if(!r.valid)return '';return 'Con questi numeri: circa '+fmtMoney(r.profit)+' en '+fmtHours(r.totalMinutes/60)+', se guadagni sempre la stessa cifra. Lo strumento ti farà un vero programma con le tue attività.';}
  /* Revue de conformité (v7.53) : même règle que le calculateur (LKCalcOwned) : un véhicule ou une arme déjà coché dans
     « Mon garage » / « Mon arsenal » n’est pas à payer ; le calcul d’achat est la même fonction du moteur (E.worth), et Léo
     dit ce qu’il ne compte pas encore (options, frais, coût d’usage : à écrire dans l’outil). */
  if((tool==='purchase'||tool==='roi')&&selected[0]&&ownedInCarnet(selected[0]))return 'Hai già spuntato '+selected[0].name+' in '+(selected[0].kind==='weapon'?'“Il mio arsenale”':'“Il mio garage”')+': il calcolatore lo conta come già posseduto, niente da pagare (potrai togliere la spunta per ricomprarne uno).';
  if((tool==='purchase'||tool==='roi')&&has('capital')&&has('price')){const r=E.worth({capital:v.capital,reserve:v.reserve||0,price:v.price,hourly:has('hourly')?v.hourly:null});if(!r.valid)return '';return (r.shortfall>0?'Con questi numeri: ti mancano '+fmtMoney(r.shortfall)+(r.waitHours!==null?', cioè '+fmtHours(r.waitHours)+' di gioco':'')+'.':'Con questi numeri: puoi comprarlo, ti resteranno '+fmtMoney(r.cashRemaining)+'.')+' Senza contare opzioni, spese obbligatorie e costo d’uso: se ce ne sono, scrivili nello strumento.';}
  if(tool==='order'&&has('capital')&&has('price')){const r=E.order({capital:v.capital,reserve:v.reserve||0,hourly:has('hourly')?v.hourly:null,items:[{name:selected[0]?.name||'questo acquisto',price:v.price,boostHourly:0}]});if(r.valid)return 'Con questi numeri: '+(r.totalHours===0?'puoi comprarlo subito.':'ancora '+fmtHours(r.totalHours)+' di gioco prima di questo acquisto.');}
 }catch(e){}return '';}
 const calcResponse=(tool,values,selected=[],note='',context={})=>{const p=preview(tool,values,selected);return {kind:'calc',text:'Controlla i numeri che ho capito, poi apri “{l}”'.replace('{l}',tools.find(x=>x.id===tool)?.label||'il calcolatore')+(/[?!]$/.test(tools.find(x=>x.id===tool)?.label||'')?' ':'. ')+'Il resto è da compilare o da verificare nello strumento.',request:{v:1,tool,values,items:selected.map(x=>x.calcId).filter(Boolean)},selected:selected.map(x=>x.key),note:[p,note].filter(Boolean).join(' '),links:[{label:'Apri {l}'.replace('{l}',tools.find(x=>x.id===tool)?.label||'il calcolatore'),url:toolURL(tool),tool}],context:{tool,values,selected:selected.map(x=>x.key),recent:remember(context,{entity:selected[0]?.key||null,intent:'calc',tool})}};};
 function choose(key,context={}){const item=byKey.get(key);if(!item||!item.calcId)return {kind:'unknown',text:'Questa scheda non fornisce un acquisto utilizzabile nel calcolatore.',links:item?[{label:'Apri la scheda',url:item.url}]:[],context:{...empty(),recent:context.recent||[]}};const values={...(context.values||{})};if(context.selected?.length&&!context.selected.includes(key))delete values.price;return calcResponse(context.tool||'purchase',values,[item],'Elemento scelto: '+item.name+'. '+item.proof,context);}
 /* ---------- la réponse ---------- */
 function answer(query,context={},options={}){
  said=typeof query==='string'?query:null;if(PIV&&typeof query==='string'&&query.length<=MAX_INPUT)query=piv(query);
  if(typeof query!=='string'||query.length>MAX_INPUT)return {kind:'error',text:'Massimo 600 caratteri per domanda. Tieni solo i nomi e i numeri utili.'};lastOriginal=query.trim();if(bridge)query=bridge(query);let raw=query.trim();{/* « bjr, la map elle fait cb ? » : la salutation en tête est mise de côté quand une vraie question suit */const m=raw.match(/^(?:bonjour|salut|hello|bonsoir|yo|coucou|hey|slt|bjr|bsr|cc|wesh)\b[ ,!:.-]*(?:l[ée]o\b[ ,!:.-]*)?/i);if(m&&raw.length-m[0].length>=4)raw=raw.slice(m[0].length);}const q=norm(raw),n=clean(raw);if(!n)return {kind:'intro',text:'Posso aiutarti a trovare una scheda, capire un termine e preparare un calcolo.'};
  const page=options.page||null,A=analyzer.analyze(raw),recent=Array.isArray(context.recent)?context.recent:[],last=recent.length?recent[recent.length-1]:null;
  if(/^(?:(?:bonjour|salut|hello|bonsoir|yo|coucou|hey|slt|bjr|bsr|cc|wesh|hi)(?: leo| lolo)?|merci(?: beaucoup| bcp| leo| bien)?|mrc|thx|thanks|au revoir|a plus|bye|ciao|a bientot|bonne journee|bonne soiree)$/.test(n)){const t=kById.get(/merci|mrc|thx|thanks/.test(n)?'merci':/au revoir|a plus|bye|ciao|a bientot|bonne/.test(n)?'au-revoir':'bonjour');if(t)return knowledgeAnswer(t,context);return {kind:'intro',text:'Ciao! Fammi una domanda su GTA VI (uscita, console, prezzo, personaggi, regioni…), chiedimi una scheda del sito, o dammi i tuoi numeri per un calcolo.',context:empty()};}
  if(/(?:sort|sortie|date|disponib)/.test(q)&&(/gta\s*(?:vi|6)|jeu/.test(q)||/^date de sortie/.test(q))&&!/pc|ordinateur|steam|ps4|ps6|switch|xbox one|physique|boite|precommande|preco|heure|minuit|precharg|report|repouss|definitive|fiable|trailer|prevenu|alerte|mail|inscri|newsletter|prix|combien|cb |console|plateforme|contenu|edition|apres la sortie|a la sortie|changera|site/.test(q)){const r=data.release,today=options.now?new Date(options.now):new Date(),at=r?.verifiedAt&&Date.parse(r.verifiedAt+'T00:00:00Z'),date=r?.date&&Date.parse(r.date+'T00:00:00Z'),age=(today-at)/86400000,fresh=Number.isFinite(at)&&Number.isFinite(date)&&age>=0&&age<=(r.maxAgeDays||30)&&today.getTime()<date&&safeSource(r.source);return {kind:'answer',topic:'sortie',text:fresh?'Rockstar annuncia GTA VI per il '+new Intl.DateTimeFormat('it-IT',{dateStyle:'long',timeZone:'UTC'}).format(new Date(date))+'.':'La data di uscita va ricontrollata: il mio dato locale manca o è troppo vecchio. Non posso confermare la disponibilità del gioco.',source:fresh?r.source:safeSource(r?.source),verifiedAt:r?.verifiedAt||null,status:fresh?'Data annunciata · fonte ufficiale':'Da verificare',links:[{label:'Il calendario',url:'/it/a-propos.html#calendrier'},{label:'Conta i giorni nella home',url:'/it/index.html'}],context:{...empty(),recent:remember(context,{topic:'sortie'})}};}
  const def=data.definitions.find(x=>x.terms.some(t=>new RegExp('(?:^| )'+escape(clean(t))+'(?: |$)').test(n)));if(def&&(/c'est quoi|c est quoi|quoi un|qu'est|qu est|veut dire|signifi|defini|explique|c koi|ckoi/.test(q)||def.terms.some(t=>n===clean(t))))return {kind:'answer',topic:'def-'+def.id,text:def.text,links:[{label:'Leggi nel Tutorial',url:def.url}],status:'Definizione del calcolatore',context:{...empty(),recent:remember(context,{topic:'def-'+def.id})}};
  let faq;if(/pourquoi.*prix|pas.*prix|prix.*(?:manqu|inconnu|absen)/.test(q))faq=data.faq.find(x=>x.id==='prix');else faq=data.faq.find(x=>x.terms.some(t=>n.includes(clean(t))));if(faq&&!/je veux acheter|je souhaite acheter/.test(q))return {kind:'answer',topic:'faq-'+faq.id,text:faq.text,links:[{label:'Vedi la spiegazione',url:faq.url}],status:'Risposta del Tutorial',context:{...empty(),recent:remember(context,{topic:'faq-'+faq.id})}};
  const nav=/^(?:ouvre|ouvrir|aller|va |montre|ou est mon|ou sont mes|acces|emmene)/.test(q),ct=category(q),nt=tools.find(t=>t.terms.some(x=>n.includes(clean(x))));
  if(nav&&(ct||nt)&&A.terms.length<=3&&!/\b(?:mon garage|mon arsenal|mon suivi|ma progression|mes calculs|mes plans|mon equipement|mes lieux|ma collection|mon carnet)\b/.test(q)){if(nt&&/mon plan|mes plans|business plan|mon objectif|mes activites|mon temps|mes achats|mon budget|quel achat|calculateur|rentabilite/.test(q))return {kind:'answer',text:nt.label+' è disponibile nel calcolatore.',links:[{label:'Apri {l}'.replace('{l}',nt.label),url:toolURL(nt.id),tool:nt.id}],context:empty()};if(ct)return {kind:'answer',text:'Ecco la sezione '+ct.label+'.',links:[{label:'Apri '+ct.label,url:ct.route}],context:empty()};}
  /* v7.58 (LEO-02g) : « c’est qui <nom inconnu du site> » : introuvable (vers Personnages), jamais la présentation de Léo */
  {const m=n.match(/^(?:c est qui|qui est|qui c est|c est ki|ki est|cest qui|qui est ce)\s+(?:le |la |les |l |un |une )?([a-z0-9 -]{2,40}?)\s*$/);if(m){const toks=m[1].split(' ').filter(t=>t.length>=2&&!N.STOP.has(t));const known=toks.some(t=>kIndex.has(t)||nameIndex.has(t)||nearestName(t)||/^(?:toi|tu|vous|leo|lolo|moi|je)$/.test(t)||/\d/.test(t));
   if(toks.length&&!known&&!detectEntities(A).length)return notFound(raw,context,{route:'/it/personnages.html',routeLabel:'Apri Personaggi',kind:'character',page});}}
  /* v7.58 (LEO-02c) : aide liée à la page ouverte — « aide », « que faire ici ? », et les mots de l'interface (badges, légende, filtres, tri, fiche complète, « Je l'ai ») renvoient au sujet de la page */
  {const H=(data.help&&data.help.pages)||{};const path=String(unprefix(page)||'').split(/[?#]/)[0];const key=Object.keys(H).find(k=>k.endsWith('/')?path.startsWith(k):path===k);
   if(key){const spec=H[key];const helpAsk=/^(?:aide|help|sos|a l aide|aide moi|au secours|je suis perdu|je suis perdue|je comprends pas|je comprends rien|j y comprends rien|comment ca marche|comment ca marche ici|ca marche comment|ca marche comment ici|que faire ici|quoi faire ici|que peut on faire ici|que peut on faire sur cette page|qu est ce qu on peut faire ici|qu est ce que je peux faire ici|que puis je faire ici|comment utiliser cette page|comment utiliser la page|comment marche cette page|c est quoi cette page|a quoi sert cette page|explique moi cette page|explique cette page|presente la page|presente moi la page|cette page sert a quoi|comment ca marche cette page)\s*\??$/.test(n);
    if(helpAsk&&kById.get(spec.topic))return knowledgeAnswer(kById.get(spec.topic),context);
    if(!/\d/.test(n)&&A.terms.length<=7)for(const r of spec.rules||[]){if(!r._re){try{r._re=new RegExp(r.re);}catch{r._re=/$^/;}}if(r._re.test(n)&&kById.get(r.topic))return knowledgeAnswer(kById.get(r.topic),context);}}}
  /* couches : questions rédigées (BM25), entités nommées, intentions */
  const kb=kIndex.search(A.terms,12);{const seenT=new Map();for(const r of kb.results){const n=seenT.get(r.id)||0;if(n>0&&r.confidence>=0.5)kb.results.find(x=>x.id===r.id).confidence+=Math.min(0.015*n,0.04);seenT.set(r.id,n+1);}kb.results.sort((a,b)=>b.confidence-a.confidence||b.score-a.score);}
  const best=kb.results[0]||null,second=kb.results.find(r=>best&&r.id!==best.id)||null;const bestTopic=best?kById.get(best.id):null;
  const ents=detectEntities(A),intents=intentsOf(A,q),intent=priorityIntent(intents);let strong=ents.find(e=>e.full)||null;
  /* v7.58 : dans une suite (« et sa voiture ? », « et en munitions ? »), une fiche reconnue par un seul mot générique ne passe pas devant la fiche en cours ou la fiche ouverte */
  {const followShape=/^(?:et |mais |aussi |pareil )/.test(q)||/\b(?:son|sa|ses|lui|la sienne|le sien|celui la|celle la)\b/.test(q);if(strong&&strong.via==='single'&&followShape&&(last?.entity||options.pageKey))strong=null;}
  const parsedRaw=extract(norm(raw)),givesFigures=parsedRaw.money.length>0||parsedRaw.issues.length>0||own(parsedRaw.values,'minutes');
  const buyIntent=/acheter|achete|achat|vaut le coup|rentab/.test(q),locateIntent=/^(?:ou trouver|ou est|ou se trouve|trouve|cherche|je cherche|montre|localise)/.test(n);
  const marker=offTopicMarker(A);
  if(options.debug)options.debug({q,terms:A.terms,kb:kb.results.slice(0,3).map(r=>[r.id,+r.confidence.toFixed(2),r.matched]),unknown:kb.unknown,strong:strong?.key||null,strict:strong?.strict||false,intent,intents:[...intents],marker:marker?.word||null,givesFigures,buyIntent,locateIntent,nt:nt?.id||null,ct:ct?.id||null});
  /* v7.58 (LEO-02b) : « ouvre la fiche du Dinka Enduro », « fiche du Girardi » → la fiche, directement */
  if(strong?.item&&strong.strict&&!givesFigures&&!intents.has('where')&&!/carte|map\b/.test(q)&&(/\bfiche\b/.test(q)||(nav&&!ct&&!nt))&&A.terms.length<=8){const it=strong.item;return {kind:'answer',text:'Ecco la scheda di '+it.name+'.',links:[{label:it.name,url:it.url}],status:it.proof||undefined,source:it.source||undefined,verifiedAt:it.verifiedAt||null,context:{...empty(),recent:remember(context,{entity:strong.key,intent:'what'})}};}
  /* v7.58 (LEO-02a) : une section nommée seule (« les suv », « une voiture de sport », « les tatouages ») ouvre sa vue, à moins qu'une question rédigée sûre ne mène déjà à cette page */
  {const qt=n.replace(/^(?:trouve moi|trouve|cherche moi|cherche|je cherche|je recherche|montre moi|montre|liste des|liste de|la liste des|toutes les|tous les|voir les|voir la|voir le)\s*/,'').replace(/^(?:le|la|les|l|un|une|des|ce|cette|cet|mes|ma|mon)\s+/,'').replace(/\s*\?$/,'').trim();
   if(ct&&!strong&&!givesFigures&&!nt&&ct.terms.some(t=>clean(t)===qt)){const route=ct.route.split('#')[0];const kbTop=kb.results[0];const kbSame=kbTop&&kbTop.confidence>=HIGH&&kById.get(kbTop.id)&&kById.get(kbTop.id).links.some(l=>l.url===ct.route||l.url.split('#')[0]===route&&ct.route.indexOf('#')<0);
    if(!kbSame)return {kind:'answer',text:'Ecco la sezione '+ct.label+'.',links:[{label:'Apri '+ct.label,url:ct.route}],context:empty()};}}
  const kbConf=best?best.confidence:0,kbPriority=bestTopic?.priority&&kbConf>=MID&&!(strong?.strict&&intent&&intent!=='what');/* un sujet prioritaire (prix du jeu) ne passe pas devant une fiche nommée avec une intention précise (« combien coûte le Kamacho ») */
  /* morceaux à la demande : les salutations, la date de sortie, les définitions et la FAQ du Tuto répondent depuis le noyau seul ; à partir d'ici, les morceaux dont le vocabulaire (noms de fiches) touche la question sont chargés avant de décider */
  {const pending=needs(raw);if(pending.length)return {kind:'needs',shards:pending};}
  /* suite de conversation : « et son prix ? », « et à Vice City ? » */
  const followUp=/^(?:et |mais |aussi |pareil )/.test(q)||(A.terms.length<=3&&!strong&&intent&&last?.entity&&/\b(?:son|sa|ses|il|elle|lui|ca|celui|celle|meme|ici|la bas|y|le sien|la sienne)\b/.test(q));
  let followEntity=null;if(followUp&&!strong&&last?.entity&&!byKey.has(last.entity)&&data.shards[shardOfKey(last.entity)]&&!loaded.has(shardOfKey(last.entity)))return {kind:'needs',shards:[shardOfKey(last.entity)]};
  if(followUp&&!strong&&last?.entity&&byKey.has(last.entity)){followEntity={item:byKey.get(last.entity),key:last.entity,kind:byKey.get(last.entity).kind,name:byKey.get(last.entity).name,full:true,score:1};}
  /* sur une fiche, « et son prix ? », « et son arme ? », « combien ça coûte ? », « il est rapide ? » visent la fiche ouverte quand rien d’autre n’est nommé ni en cours (v7.44 : « ça vaut le coup ? » sur une fiche prépare déjà son calcul) */
  const pageItem=options.pageKey&&byKey.get(options.pageKey)||null;
  if(!followEntity&&!strong&&pageItem&&intent&&intent!=='what'&&!last?.entity&&A.terms.length<=3&&(/^(?:et |mais |aussi )/.test(q)||/\b(?:son|sa|ses|ca|il|elle|cette|ce|cet|celui|celle|lui|c est)\b/.test(q)))followEntity={item:pageItem,key:pageItem.key,kind:pageItem.kind,name:pageItem.name,full:true,score:1};
  const followIntent=(!intent&&strong&&/^(?:et |mais |aussi )/.test(q)&&last?.intent&&last.intent!=='calc')?last.intent:null;
  /* 0. rien à lire (chiffres seuls, symboles) ou marqueur hors sujet sans rien du site qui réponde nettement */
  const hasLetters=A.terms.some(t=>/[a-z]/.test(t));
  if(!hasLetters&&!givesFigures)return refusal(raw,context,page);
  const anchored=A.terms.some(t=>/^(?:gta6|gta5|gta4|gtaplus|leonidakit|leo|leonida|rockstar|vice|city)$/.test(t))||(strong?.exact&&strong?.strict&&strong.e.toks.length>=2);
  if(marker&&!anchored)return refusal(raw,context,page);
  /* 0 bis. suite de conversation sur une fiche : « et son prix ? », « et sa maison ? » */
  const target=strong||followEntity;const useIntent=intent||followIntent;
  if(followEntity&&useIntent&&!strong&&!givesFigures&&!(buyIntent&&followEntity.item?.calcId)){const t=templateAnswer(followEntity,useIntent,raw,context,options);if(t)return t;}
  /* v7.58 (LEO-02e) : « le plus rapide entre X et Y », « X ou Y ? », « compare X et Y » sans chiffres : ce que le site sait de chacun, côte à côte, sans vainqueur inventé ; avec des chiffres, le calculateur compare (ci-dessous) */
  {const cmpWords=/\bou\b|\bvs\b|versus|compar|choisir|lequel|laquelle|entre|le mieux|meilleur|meilleure|plus rapide|plus puissant|plus puissante|plus fort|plus forte|difference|différence/.test(q);
   let same=ents.filter(e=>e.full&&e.item&&(e.item.kind==='vehicle'||e.item.kind==='weapon'));{const sure=same.filter(e=>e.strict);if(sure.length>=2)same=sure;}const fam=same.length>=2&&same.every(e=>e.item.kind===same[0].item.kind)?same[0].item.kind:null;
   if(fam&&(cmpWords||intents.has('speed'))&&!givesFigures&&!buyIntent){const picked=[];for(const e of same){if(!picked.some(p=>p.key===e.key))picked.push(e);if(picked.length===3)break;}
    const what=picked.map(e=>{const it=e.item;const bits=[String(it.category||'').replace(/^(?:Véhicule|Arme|Vehículo|Arma|Veicolo)\s*·\s*/,''),it.st==='officiel'?'nome confermato da Rockstar':it.st==='comm'?'identificazione della community':'visto nei media ufficiali'];if(it.inspiration)bits.push('ispirazione reale: '+it.inspiration);if(fam==='weapon'&&it.ammo)bits.push(it.ammo.toLowerCase());if(fam==='weapon'&&it.range)bits.push('portata '+it.range.toLowerCase());return it.name+' — '+bits.filter(Boolean).join(', ');}).join(' · ');
    const none=fam==='vehicle'?'Rockstar non ha pubblicato né velocità, né accelerazione, né prezzo per nessun veicolo: non posso dire quale sia il più veloce o il migliore.':'Rockstar non ha pubblicato né danni, né cadenza di fuoco, né prezzo per nessuna arma: non posso dire quale sia la più potente.';
    const links=picked.map(e=>({label:e.item.name,url:e.item.url}));const ids=picked.map(e=>e.item.calcId||e.item.id).filter(Boolean);const cmpURL=safeURL('/it/comparateur.html?type='+(fam==='vehicle'?'vehicules':'armes')+'&ids='+ids.join(','));if(cmpURL&&ids.length===picked.length)links.push({label:'Confronta nel comparatore',url:cmpURL});links.push({label:'Quale acquisto scelgo? (con i tuoi prezzi)',url:toolURL('compare'),tool:'compare'});
    /* les fiches achetables gardent le contrat du lot B : la demande « Quel achat choisir ? » est préparée avec les deux fiches (request), sans prix inventé */
    const sel=picked.filter(e=>e.item.calcId).map(e=>e.item);const request=sel.length>=2?{v:1,tool:'compare',values:{},items:sel.map(x=>x.calcId)}:undefined;
    return {kind:'answer',topic:'comparaison',text:none+' Quello che il sito sa: '+what+'. Le schede danno le fonti e la loro data; il comparatore le mette fianco a fianco, e il calcolatore confronta con i prezzi che immagini.',links,...(request?{request,selected:sel.map(x=>x.key),note:''}:{}),status:'Confronto basato sui fatti · nessuna statistica pubblicata',context:{...empty(),tool:request?'compare':undefined,values:{},selected:sel.map(x=>x.key),recent:remember(context,{entity:picked[0].key,intent:request?'calc':'compare',tool:request?'compare':undefined})}};}}
  /* 0 ter. deux fiches achetables à comparer : le calculateur (v1) avant les questions rédigées */
  const calcEnts=ents.filter(e=>e.full&&e.item?.calcId);const twoCalcEarly=calcEnts.length>=2&&/\bou\b|\bvs\b|compar|choisir|lequel|laquelle|entre|le mieux|meilleur|ordre|d'abord|en premier/.test(q);
  /* 0 quater. « trouve », « cherche », « où trouver » sans fiche nommée : la recherche par nom et inspiration (v1) avant les questions rédigées */
  if(locateIntent&&!strong&&!(bestTopic&&kbConf>=HIGH)){const found0=entityMatches(raw,true);if(found0.length)return {kind:'results',text:'Ecco le schede che corrispondono. La categoria e le fonti dicono cosa si sa davvero.',results:found0.slice(0,4),total:found0.length,forCalculation:false,context:{values:{},selected:found0.length===1?[found0[0].key]:[],recent:remember(context,{entity:found0[0].key})}};
   const q0=n.replace(/^(?:trouve moi|trouve|cherche moi|cherche|je cherche|je recherche|ou trouver|ou se trouve|ou est|ou sont|montre moi|montre|localise|recherche)\s*/,'').replace(/^(?:le|la|les|un|une|des|ce|cette|cet)\s+/,'').trim();const s0=q0.length>=3?search(q0,ct?.id):{total:0};if(s0.total)return {kind:'results',text:s0.items.some(x=>x.fuzzy)?'Non trovo una corrispondenza esatta. Questi nomi sono simili:':s0.total>1?'Più schede corrispondono: guarda la categoria per scegliere.':'Ecco la scheda del sito. Dal solo nome non posso indovinare dove si trova esattamente.',results:s0.items,total:s0.total,query:q0,category:ct?.id,context:{values:{},selected:s0.total===1?[s0.items[0].key]:[],recent:remember(context,{entity:s0.items[0].key})}};}
  /* « je veux acheter Leonida Keys » : un lieu ou une région n'est pas un achat, la réponse « destination » (couche 4) passe avant les questions rédigées ; « trouve sprunk » : une fiche nommée exactement est rendue telle quelle */
  const buyPlace=buyIntent&&strong?.item&&!strong.item.calcId&&['place','region'].includes(strong.kind);
  if(locateIntent&&(!intent||A.terms.length<=2)&&!buyIntent&&!givesFigures&&strong?.item&&strong.strict&&strong.exact){const found=ents.filter(e=>e.full&&e.item&&e.strict).map(e=>e.item);return {kind:'results',text:found.length>1?'Più schede corrispondono: guarda la categoria per scegliere.':'Ecco la scheda del sito. La categoria e le fonti dicono cosa si sa davvero.',results:found.slice(0,4),total:found.length,forCalculation:false,context:{values:{},selected:found.length===1?[found[0].key]:[],recent:remember(context,{entity:found[0].key})}};}
  /* garde-fous : un achat nommé (ou déjà choisi) va au calculateur ; un déclencheur d'outil court aussi ; un nom inconnu du site n'est pas rapproché d'une question au hasard */
  const explain=/a quoi (?:ca |ça )?sert|c est quoi|c koi|ckoi|qu est ce|veut dire|ca marche comment|comment (?:ca |ça )?marche|comment fonctionne|explique|sert a quoi|fait quoi|definition|les \d+ questions|montre quoi|montrent quoi|est il le|c est pour quoi/.test(q);
  const calcFirst=!!context.pending||(buyIntent&&!explain&&(strong?.item?.calcId||(context.selected||[]).length||(last?.entity&&byKey.get(last.entity)?.calcId)||(!strong&&pageItem?.calcId&&A.terms.length<=4&&!/\b(?:gta|jeu|edition|ultimate|standard|precommande)\b/.test(q))))||(nt&&!explain&&!questionLike(q)&&A.terms.length<=3&&!strong&&kbConf<0.9);
  const unknownLong=kb.unknown.filter(t=>/^[a-z]{6,}$/.test(t)&&!nameIndex.has(t)&&!nearestName(t));
  if(unknownLong.length&&!strong&&!givesFigures&&!buyIntent&&kbConf<HIGH&&!nt)return notFound(raw,context,{route:ct?.route||null,routeLabel:ct?'Apri {l}'.replace('{l}',ct.label):null,topic:best&&best.confidence>=0.35?best.id:null,kind:ct?.id==='place'||intents.has('where')?'place':ct?.id==='character'?'character':null,page});
  const inEntity=t=>strong.e.toks.includes(t)||strong.e.alts.some(a=>a.includes(t));
  /* 0 quinquies. un nom de fiche seul (« marteau », « lucia ») : la question rédigée dont la page source est cette fiche, sinon une question rédigée qui cite tout le nom (sans rapprochement) ou la fiche, sinon le gabarit de la fiche — jamais un sujet qui partage seulement un mot du nom ou un mot voisin (« marteau » ≠ « bateau ») */
  const nameOnly=!!strong?.item&&strong.strict&&strong.exact&&!useIntent&&!buyIntent&&!givesFigures&&!locateIntent&&!twoCalcEarly&&!calcFirst&&A.terms.every(inEntity);
  if(nameOnly){const own=kb.results.find(r=>r.confidence>=MID&&kById.get(r.id)?.links[0]?.url===strong.item.url);if(own)return knowledgeAnswer(kById.get(own.id),context,{entityKey:strong.key,source:strong.item.source||null});
   const coversName=!!best&&strong.e.toks.every(t=>(best.exact||[]).includes(t))||!!best&&strong.e.alts.some(a=>a.every(t=>(best.exact||[]).includes(t)));
   if(!(bestTopic&&kbConf>=MID&&(coversName||bestTopic.links.some(l=>l.url===strong.item.url)))){const t=templateAnswer(strong,'what',raw,context,options);if(t)return t;}}
  /* 1. question rédigée sûre */
  /* une fiche nommée avec une intention précise : le gabarit de la fiche passe avant une question rédigée qui ne parle que du nom (entityOnly) ou qui ne le cite pas du tout (« le Kamacho est dans l’Ultimate ? » ≠ « Quelles sont les éditions ? ») */
  /* « c’est quoi les P’s & Q’s » : une question rédigée trouvée par le seul mot interrogatif (« quoi ») ne passe pas devant la fiche nommée */
  /* « c’est quoi le Sprunk » : un sujet sur un prix ne répond pas à « c’est quoi » sur une fiche nommée ; le gabarit de la fiche le fait */
  const offIntentKB=!!(strong?.strict&&strong.exact&&strong.item&&bestTopic&&!bestTopic.links.some(l=>l.url===strong.item.url)&&(()=>{const ti=topicIntent(bestTopic);return useIntent==='what'&&ti==='price';})());
  const QW=new Set(['quoi','qui','ou','quand','combien','pourquoi','comment','quel','quelle','quels','quelles','lequel','laquelle'].map(N.stem));const trivialKB=!!(strong?.strict&&strong.exact&&strong.item&&best&&best.matched.every(t=>QW.has(t)));
  const entityOnly=strong&&best?(best.matched.every(inEntity)||(strong.strict&&!best.matched.some(inEntity))):false;
  /* v7.59 (check ultime, CALC-11) : une fiche nommée dont le prix est publié répond elle-même à « combien coûte » : plus précis qu'une question rédigée */
  const pricedEntity=!!(strong?.item&&useIntent==='price'&&typeof strong.item.price==='number');
  if(!twoCalcEarly&&!calcFirst&&!buyPlace&&!trivialKB&&!offIntentKB&&bestTopic&&(kbConf>=HIGH||kbPriority)&&(!givesFigures||questionLike(q))&&!pricedEntity&&!(strong&&useIntent&&['price','insp','ultimate','speed','ammo','custom','effect','owner','home','vehicles','weapon','where','go'].includes(useIntent)&&entityOnly)){
   const entLinks=strong&&strong.item?[{label:strong.item.name,url:strong.item.url}]:[];return knowledgeAnswer(bestTopic,context,{links:entLinks,entityKey:strong?.key||null,intent,source:strong?.item?.source||null});}
  /* 2. entité + intention → gabarit */
  if(!twoCalcEarly&&target&&useIntent&&useIntent!=='what'&&!(buyIntent&&target.item?.calcId&&useIntent!=='price')&&!(target.item?.calcId&&/vaut le coup|rentab/.test(q))){if(!target.item)return {kind:'needs',shards:[target.e?.shard||'monde']};if(!(useIntent==='price'&&target.item.calcId&&givesFigures)){const t=templateAnswer(target,useIntent,raw,context,options);if(t)return t;}}
  /* 3. question rédigée probable, ou deux réponses proches */
  if(!twoCalcEarly&&!calcFirst&&!trivialKB&&!offIntentKB&&bestTopic&&kbConf>=MID&&!(strong&&buyIntent)&&!(givesFigures&&!questionLike(q))){
   if(second&&second.confidence>=MID&&second.confidence>=best.confidence-MARGIN&&kbConf<0.9&&kById.get(second.id)){const t2=kById.get(second.id);return {kind:'choices',text:texts.didYouMean,choices:[bestTopic.q,t2.q],topics:[bestTopic.id,t2.id],links:[{label:bestTopic.links[0].label,url:bestTopic.links[0].url}],context:{...empty(),recent:recent.slice(-6)}};}
   const entLinks=strong&&strong.item?[{label:strong.item.name,url:strong.item.url}]:[];return knowledgeAnswer(bestTopic,context,{links:entLinks,entityKey:strong?.key||null,intent,source:strong?.item?.source||null});}
  /* 4. destinations et fiches (v1) */
  const mentioned=entityMatches(raw,true),destinations=mentioned.filter(x=>!x.calcId);
  if(buyIntent&&(destinations.length||ct?.id==='place')&&!mentioned.some(x=>x.calcId))return {kind:'answer',text:'Un luogo o una regione è una destinazione: si visita, e niente dice che si possa comprare. Puoi aprire la sua scheda o la mappa.',links:destinations.slice(0,3).flatMap(x=>[{label:'Vedi '+x.name,url:x.url},...(x.mapUrl?[{label:'Apri il segnaposto sulla mappa',url:x.mapUrl}]:[])]).concat(destinations.length?[]:[{label:'Esplora i luoghi',url:'/it/lieux.html'}]),context:{...empty(),recent:recent.slice(-6)}};
  if(locateIntent&&mentioned.length)return {kind:'results',text:'Ecco le schede che corrispondono. La categoria e le fonti dicono cosa si sa davvero.',results:mentioned.slice(0,4),total:mentioned.length,forCalculation:false,context:{values:{},selected:mentioned.length===1?[mentioned[0].key]:[],recent:remember(context,{entity:mentioned[0].key})}};
  /* 5. chiffres → outil du calculateur (v1) */
  let numericText=norm(raw);for(const item of entityMatches(raw))for(const name of [item.n,...item.a])if(/\d/.test(name)){const re=new RegExp(name.split(' ').map(escape).join("[\\s'_-]+"),'g');numericText=numericText.replace(re,m=>' '.repeat(m.length));}
  let parsed=extract(numericText),values=parsed.values,selected=[],reuse=false;
  if(context.pending&&/mon capital|argent actuel|mon objectif|c'est le prix|c est le prix/.test(q)&&context.pending.kind==='role'){const role=/capital|argent/.test(q)?'capital':/objectif/.test(q)?'target':'price';values={...(context.values||{}),[role]:context.pending.value};parsed.issues=[];reuse=true;}
  else if(context.pending&&context.pending.field&&parsed.money.length===1&&!parsed.money[0].role){values={...(context.values||{}),[context.pending.field]:parsed.money[0].value};parsed.issues=[];reuse=true;}
  else if(/^(?:et |avec |non[ ,]|plutot |corrige |en fait )/.test(q)&&Object.keys(context.values||{}).length){values={...context.values,...values};reuse=true;}
  const twoCalc=mentioned.filter(x=>x.calcId).length>=2;
  const calcIntent=/business plan|plan complet|etape par etape/.test(q)?'plan':(/lequel choisir|laquelle choisir|quel achat choisir|choisir entre|comparer .*achats|le mieux a acheter|meilleur rapport|compar(?:er|e|aison)? (?:le |la |les |un |une |ces |deux |mes )?(?:achats|fiches|prix)/.test(q)||(twoCalc&&/\bou\b|compar|choisir|lequel|laquelle|entre|le mieux|meilleur/.test(q)))?'compare':/ordre|d'abord|en premier|priorit|plusieurs achats/.test(q)?'order':/vaut le coup|rentab|amorti|\broi\b/.test(q)?'roi':/mon plan|plan complet|plusieurs decisions/.test(q)?'plan':/repart|enveloppe|budget/.test(q)&&!ct?.id?.includes('property')?'budget':/acheter|achete|achat|permettre|cout/.test(q)?'purchase':/vise|objectif|atteindre|million|epargn/.test(q)?'goal':/activit|mission|comparer.*gains/.test(q)?'activities':own(values,'minutes')?'session':nt?.id||(Object.keys(values).length?'goal':null);
  const namedPurchase=/(?:acheter|achat de|achete)\s+(?!(?:pour|ce|cet|cette|celui|celle)\b)[a-z]/.test(q);
  let tool=(reuse||context.pending)&&context.tool&&!calcIntent?context.tool:calcIntent;
  if(parsed.issues.length){const issue=parsed.issues[0];return {kind:'clarify',text:issue.text,context:{values,tool:tool||'goal',selected:context.selected||[],pending:issue,recent:recent.slice(-6)},choices:issue.kind==='role'?['È il mio capitale','È il mio obiettivo']:[]};}
  if(tool&&(givesFigures||buyIntent||reuse||context.pending||['plan','compare','order','roi','activities','session','budget'].includes(tool)&&(calcIntent||nt))){
   if(['purchase','roi','order','plan','compare'].includes(tool)){
    selected=entityMatches(raw);
    /* v7.54 : une fiche reconnue par un seul mot de son nom (« la cheetah ») compte aussi ; deux achats nommés partent tous les deux dans l’outil (revue v7.53, écart E7). */
    {const used=new Set();selected.forEach(x=>String((x.n||x.name||'')+' '+(x.a||[]).join(' ')).toLowerCase().split(/[^a-z0-9]+/).forEach(t=>{if(A.terms.includes(t))used.add(t);}));
     const extra=(typeof calcEnts!=='undefined'?calcEnts:[]).filter(e=>e.exact&&e.e&&e.e.toks&&e.e.toks.some(t=>A.terms.includes(t)&&!used.has(t))).map(e=>e.item).filter(x=>x&&x.calcId&&!selected.some(y=>(y.calcId||y.key)===(x.calcId||x.key)));if(extra.length)selected=selected.concat(extra);}
    if(reuse&&context.selected?.length&&(selected.length||namedPurchase)&&!selected.some(x=>context.selected.includes(x.key))&&!own(parsed.values,'price'))delete values.price;if(!selected.length&&/cette |ce vehicule|ce bateau|cet |ca vaut|celui|celle|l[' ]acheter|me l[' ]offrir|le prendre|la prendre/.test(q)){const keys=context.selected?.length?context.selected:[options.pageKey];selected=keys.map(k=>byKey.get(k)).filter(x=>x?.calcId);reuse=selected.length>0;}
    if(selected.length>1&&!['order','plan','compare'].includes(tool)){const candidates=selected.slice(0,4);return {kind:'results',text:'Più schede corrispondono. Scegli quella che vuoi usare.',results:candidates,total:selected.length,context:{tool,values,selected:[],recent:recent.slice(-6)},forCalculation:true};}
    if(!selected.length&&/acheter|achat|rentab|vaut le coup/.test(q)){
     const query=n.replace(/je veux|je souhaite|acheter|un |une |le |la |les |cet |cette |entreprise|vehicule|voiture|arme|est ce|que|ca vaut le coup|rentable|pour|\d+/g,' ').replace(/\s+/g,' ').trim();
     if(query.length>=2){const result=search(query,ct?.id);if(result.total&&!result.items.some(x=>x.calcId))return {kind:'answer',text:'Questi risultati sono luoghi o contenuti che non risultano acquistabili. Apri la loro scheda; non preparo nessun acquisto.',links:result.items.map(x=>({label:'Vedi '+x.name,url:x.url})),context:{...empty(),recent:recent.slice(-6)}};if(result.total)return {kind:'results',text:'Scegli una scheda. Se non si sa ancora se si può comprare, il calcolo resta solo una tua prova.',results:result.items,total:result.total,query,category:ct?.id,context:{tool,values,selected:[],recent:recent.slice(-6)},forCalculation:true};}
    }
   }
   if(reuse&&!namedPurchase&&!selected.length&&context.selected?.length)selected=context.selected.map(k=>byKey.get(k)).filter(x=>x?.calcId);
   if(own(values,'price')&&selected.length>1)return {kind:'clarify',text:'Questo prezzo è per quale acquisto? Scegli una scheda o inserisci i prezzi separatamente, nell’ordine d’acquisto.',results:selected,context:{tool:'purchase',values,selected:[],recent:recent.slice(-6)}};
   const response=calcResponse(tool,values,selected,reuse?'Contesto ripreso da questa conversazione, mostrato qui sotto.':'',context);
   if(!selected.length&&['purchase','roi'].includes(tool))response.note+=(response.note?' ':'')+'Non trovo questa scheda: scrivi un nome più preciso, o fai un acquisto senza scheda con il tuo prezzo.';
   if(selected.length)response.note+=(response.note?' ':'')+selected.map(x=>x.name+': '+x.proof).join(' ');
   if(own(values,'minutes')&&tool!=='session')response.following=[{...response.request,tool:'session'}];return response;
  }
  /* 6. entité sans intention : la fiche */
  if(strong&&strong.item){const t=templateAnswer(strong,questionLike(q)?'what':null,raw,context,options);if(t)return t;}
  if(strong&&!strong.item)return {kind:'needs',shards:[strong.e.shard]};
  const partials=ents.filter(e=>!e.full);if(partials.length>=2&&partials.every(e=>e.item)){return {kind:'results',text:'Più schede corrispondono: guarda la categoria per scegliere.',results:partials.slice(0,4).map(e=>e.item),total:partials.length,context:{values:{},selected:[],recent:recent.slice(-6)}};}
  const queryText=n.replace(/^(?:trouve moi|trouve|cherche moi|cherche|je cherche|je recherche|ou trouver|ou se trouve|ou est|ou sont|montre moi|recherche)\s*/,'').replace(/^(?:le|la|les|un|une|des|ce|cette|cet)\s+/,'').trim();
  const stripped=ct?queryText.replace(new RegExp('^(?:'+ct.terms.map(x=>escape(clean(x))).join('|')+')\\s+'),''):queryText;
  if(ct&&ct.terms.some(x=>clean(x)===stripped||clean(x)===queryText))return {kind:'answer',text:'Ecco la sezione '+ct.label+'.',links:[{label:'Consulta '+ct.label,url:ct.route}],context:{...empty(),recent:recent.slice(-6)}};
  const found=search(stripped,ct&&['vehicle','weapon','place','character','business','property','hideout'].includes(ct.id)?ct.id:null);
  if(found.total&&(A.terms.length<=3||found.items[0].score>=75)){return {kind:'results',text:found.items.some(x=>x.fuzzy)?'Non trovo una corrispondenza esatta. Questi nomi sono simili:':found.total>1?'Più schede corrispondono: guarda la categoria per scegliere.':'Ecco la scheda del sito. Dal solo nome non posso indovinare dove si trova esattamente.',results:found.items,total:found.total,query:stripped,category:ct?.id,context:{values:{},selected:found.total===1?[found.items[0].key]:[],recent:remember(context,{entity:found.items[0].key})}};}
  /* 7. hors sujet (marqueur présent, rien du site n'a répondu) */
  if(marker&&kbConf<MID&&!strong)return refusal(raw,context,page);
  /* 8. passages des pages */
  if(!loaded.has('passages'))return {kind:'needs',shards:['passages']};
  const ph=pIndex.search(bridge?analyzer.analyze(lastOriginal).terms:A.terms,3),pb=ph.results[0];
  if(pb&&(pb.recall>=PASSAGE_MIN&&pb.matched.length>=2||pb.matched.length>=1&&pb.recall>=0.85&&A.terms.length<=2)){const p=passages[pb.id],url=p.p+(p.a?'#'+p.a:'');return {kind:'answer',passage:{title:p.t,heading:p.h,text:p.x,url},text:fill(texts.passage,{title:p.t})+(p.h&&p.h!==p.t?', in “'+p.h+'”':'')+':',links:[{label:'Leggi sulla pagina “'+p.t+'”',url}],status:'Estratto della pagina',context:{...empty(),recent:remember(context,{topic:'page:'+p.p})}};}
  /* 9. rien : Léo le dit, renvoie vers Rockstar et la page la plus proche */
  const kind=ct?.id==='character'?'character':ct?.id==='place'||intents.has('where')?'place':intents.has('ultimate')?'edition':null;
  return notFound(raw,context,{route:ct?.route||null,routeLabel:ct?'Apri {l}'.replace('{l}',ct.label):null,topic:best&&best.confidence>=0.35?best.id:null,kind,page,external:kind==='character'&&ents[0]?officialFor(ents[0]):null});
 }
 async function ask(query,context={},options={}){let a=answer(query,context,options);let guard=0;while(a&&a.kind==='needs'&&guard++<4){await Promise.all((a.shards||[]).map(loadShard));a=answer(query,context,options);}if(a&&a.kind==='needs')a=notFound(query,context,{page:options.page||null});return a;}
 /* ---------- suggestions selon la page ---------- */
 function suggest(info={}){const S=data.suggestions||{},path=String(unprefix(info.path)||'/'),name=info.name||null;const pick=k=>(S[k]||S.default||[]).slice(0,6);
  if(/^\/(?:vehicules|armes)\/[a-z0-9-]+\.html$/.test(path)&&name)return pick('fiche').map(s=>fill(s,{name}));
  if(/^\/(?:lieux)\/[a-z0-9-]+\.html$/.test(path)&&name)return pick('lieu').map(s=>fill(s,{name}));
  if(/^\/(?:personnages|entreprises|demeures|planques|gangs)\/[a-z0-9-]+\.html$/.test(path)&&name)return [fill('Cos’è {name}?',{name}),fill('Dov’è {name}?',{name}),...pick('monde').slice(0,4)];
  if(path==='/'||path==='/it/index.html')return pick('home');if(path==='/it/calculateurs.html')return pick('calculateurs');if(path==='/it/tuto.html')return pick('tuto');if(path==='/it/carte.html')return pick('carte');
  if(/^\/(?:vehicules|classement-vehicules|vehicules-rares|comparateur|bateaux)\.html$/.test(path))return pick('vehicules');if(path==='/it/armes.html')return pick('armes');if(path==='/it/progression.html')return pick('progression');
  if(/^\/(?:lieux|personnages|demeures|planques|entreprises|gangs|collectibles)\.html$/.test(path))return pick('monde');if(/^\/(?:nourriture|style|personnalisations)\.html$/.test(path))return pick('listes');if(/^\/(?:achats|logements)\.html$/.test(path))return pick('achats');if(/^\/(?:a-propos|contact|mentions-legales|medias)\.html$/.test(path))return pick('info');return pick('default');}
 function attach(name,json){if(loaded.has(name))return false;addShard(name,json);loaded.add(name);return true;}
 return Object.freeze({answer,ask,prepare,needs,loadShard,loadAll,attach,search,choose,suggest,items,byKey,categories,tools,data,knowledge:()=>knowledge,loaded:()=>[...loaded],analyze:q=>analyzer.analyze(q),detectEntities:q=>detectEntities(analyzer.analyze(q)),intents:q=>[...intentsOf(analyzer.analyze(q),norm(q))],reportLink});
}
return Object.freeze({MAX_INPUT,norm,number,extract,near,safeURL,safeSource,create,HIGH,MID,bridgeFrom});
});
