#!/usr/bin/env node
'use strict';
/* Léo v2 (v7.45, lot 8) : projection de la base de Léo à partir des données réellement livrées. Aucun catalogue maintenu à la main.
   Sorties :
   - leo-index.json (le noyau, ≤ 300 ko, chargé à l'ouverture de Léo) : questions rédigées (outils/leo-knowledge.json + FAQ des hubs et
     des listes), définitions, FAQ du Tuto, catégories, outils, textes, gabarits, suggestions, hors sujet, lexique, liens officiels,
     noms des petites familles (armes, monde) et vocabulaire des grandes familles (véhicules, catalogues, lieux) pour savoir quel
     morceau charger ;
   - leo/<famille>.json : les fiches (vehicules, armes, monde, lieux, catalogues) et les passages des pages (passages), chargés
     seulement quand une question les vise ;
   - outils/leo-index-manifest.json : empreintes des sources et poids des sorties.
   « --check » recompare toutes les sorties à l'octet près sans les écrire. */
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const {JSDOM}=require('jsdom');const root=path.resolve(__dirname,'..');const T=require('./typographie.cjs');
const CORE_MAX=320*1024,PASSAGE_MIN=300,PASSAGE_MAX=600; /* v7.58 : 300 → 320 Kio (72 vues de section, aide par page, 5 sujets) ; servi compressé par Vercel (≈ 80 Kio), chargé une fois à la première ouverture */
function generate(options={}){
 const r=options.root||root,read=f=>fs.readFileSync(path.join(r,f),'utf8'),json=f=>JSON.parse(read(f)),exists=f=>fs.existsSync(path.join(r,f));
 const defs=json('outils/leo-editorial.json'),ed=json('outils/editorial.json'),med=json('outils/medias-officiels.json'),lex=json('outils/leo-lexique.json'),c={window:{}};const N=require(path.join(r,'leo-nlp.js'));const DEFAULT_DATE=(()=>{const k=json('outils/leo-knowledge.json'),m={};for(const t of k.topics||[]){const dt=t.checkedAt||k.checkedAt;m[dt]=(m[dt]||0)+1;}return Object.entries(m).sort((a,b)=>b[1]-a[1])[0]?.[0]||null;})();
 const inputFiles=['vehicules-data.js','armes-data.js','carte-gtadb.js','carte.js','outils/editorial.json','outils/editorial-hubs.json','outils/medias-officiels.json','outils/leo-editorial.json','outils/leo-knowledge.json','outils/leo-lexique.json','tuto.html','outils/tuto.json','calculateurs-data.js','calculateurs-catalogue.js','acquisitions-data.js','collectibles-data.js','assets-manifest.js','outils/acquisitions.json'];
 for(const f of ['vehicules-data.js','armes-data.js','calculateurs-catalogue.js','acquisitions-data.js','assets-manifest.js','calculateurs-data.js','carte-gtadb.js','collectibles-data.js'])vm.runInNewContext(read(f),c);
 const catalog=c.window.LKCalcData.catalogue(),acq=c.window.LK_ACQUISITIONS,acqSrc=json('outils/acquisitions.json'),rows=new Map(),docs=new Map(),linked=new Set();
 const doc=file=>{if(!docs.has(file))docs.set(file,new JSDOM(read(file)));return docs.get(file).window.document;};
 const routeOK=url=>{if(typeof url!=='string'||!/^\/(?!\/)[a-z0-9/_-]+\.html(?:\?[a-z0-9=&_-]+)?(?:#[a-z0-9=_-]+)?$/i.test(url))throw Error('Route invalide : '+url);const [file,rest]=url.slice(1).split(/[?#]/,2);const hash=url.includes('#')?url.split('#')[1]:null;if(!exists(file))throw Error('Page absente : '+file);if(hash&&!hash.includes('=')&&!doc(file).getElementById(hash))throw Error('Ancre absente : '+url);
  /* v7.58 : une vue filtrée doit exister — #cat=<puce> sur Véhicules/Armurerie, #<famille>=<catégorie|statut|tag> sur les listes, #lieu= et #pins= sur la carte */
  if(hash&&hash.includes('=')){const [k,v]=hash.split('=');const d=doc(file);
   if(k==='cat'){if(!d.querySelector('[data-filter="'+v+'"]'))throw Error('Filtre absent : '+url);}
   else if(k==='lieu'||k==='pins'||k==='q'||k==='own'||k==='st'||k==='slot'||k==='ed'||k==='vue'){/* vérifié ailleurs (lieux de la carte, état partagé) */}
   else{const box=d.getElementById('box-'+k);if(box){const ok=box.querySelector('[data-cat-f="cat"] option[value="'+v+'"]')||box.querySelector('[data-cat-f="st"] option[value="'+v+'"]')||(()=>{try{return Object.prototype.hasOwnProperty.call(JSON.parse(box.getAttribute('data-cat-tags')||'{}'),v);}catch{return false;}})();if(!ok)throw Error('Catégorie, statut ou filtre absent de la liste : '+url);}}}
  linked.add(file);return url;};
 const image=url=>typeof url==='string'&&/^\/(?:img|photos)\/[a-z0-9/_,.-]+\.(?:webp|svg|png)$/i.test(url)&&exists(url.slice(1))?url:null;
 const imageFor=ids=>(ids||[]).flatMap(id=>med[id]?.variants||[]).map(x=>x.src).map(image).find(Boolean)||null;
 const calcFor=(id,type)=>catalog.find(x=>x.type===type&&(x.id===id||x.id===type+':'+id));
 const tx=s=>typeof s==='string'?T.texte(s):s;
 /* ---------- liens officiels : chaque URL Rockstar utilisée par Léo doit déjà exister dans les données du site ---------- */
 const corpus=new Set();{const files=['outils/acquisitions.json','outils/editorial.json','outils/editorial-hubs.json','outils/medias-officiels.json','outils/collectibles.json','outils/catalogues/sources.json','outils/leo-knowledge.json','outils/leo-lexique.json'].filter(exists);for(const f of files)for(const m of read(f).matchAll(/https:\/\/www\.rockstargames\.com\/[A-Za-z0-9/._~-]*/g))corpus.add(m[0].replace(/[.,;)]+$/,''));}
 const official=url=>{if(typeof url!=='string')return null;let u;try{u=new URL(url);}catch{throw Error('Lien officiel invalide : '+url);}if(u.protocol!=='https:'||u.hostname!=='www.rockstargames.com')throw Error('Lien non officiel : '+url);if(!corpus.has(url))throw Error('Lien officiel absent des données du site : '+url);return url;};
 const officialLinks={};for(const [k,v] of Object.entries(lex.official)){officialLinks[k]={label:tx(v.label),url:official(v.url)};}
 /* ---------- fiches ---------- */
 const levels={officiel:'Nom confirmé par Rockstar. On ne sait pas encore si ça s’achète à part.',comm:'Identification communautaire, non confirmée par Rockstar ; achat séparé inconnu.',vu:'Recensé sur le site : vu dans les médias officiels. On ne sait pas encore si ça s’achète.',probable:'On pense que c’est ça, sans certitude.',spec:'Info venant de joueurs, à vérifier.',possible:'À vérifier.'};
 function add(x){if(rows.has(x.key))throw Error('Clé en double : '+x.key);routeOK(x.url);if(x.mapUrl)routeOK(x.mapUrl);rows.set(x.key,{...x,aliases:[...new Set((x.aliases||[]).filter(Boolean))],image:image(x.image),price:typeof x.price==='number'&&Number.isFinite(x.price)?x.price:null});}
 const acqByRef=new Map();for(const x of acq.items)if(x.ref)acqByRef.set(x.ref.type+':'+x.ref.id,x);
 const VEH_CATS={berline:'Berlines',sport:'Voitures de sport',supercar:'Supercars',muscle:'Muscle cars',suv:'SUV et 4x4',pickup:'Pick-ups et tout-terrain',van:'Vans et cargos',moto:'Deux-roues et quads',helicoptere:'Hélicoptères',avion:'Avions',bateau:'Bateaux et jet-skis',service:'Service et urgence',divers:'Divers'};
 for(const v of c.window.LK_VEHICULES){const item=calcFor(v.id,'vehicle'),bonus=acqByRef.get('vehicle:'+v.id);add({key:'vehicle:'+v.id,id:v.id,kind:'vehicle',shard:'vehicules',name:((v.marque&&v.marque!=='Marque inconnue'?v.marque+' ':'')+v.nom).trim(),aliases:[v.nom,v.insp],category:'Véhicule · '+(VEH_CATS[v.cat]||v.cat),cat:v.cat,url:'/vehicules/'+v.id+'.html',image:item?.image||v.thumb,calcId:item?.id||null,price:item?.price,priceStatus:item?.fieldMeta?.price?.status||null,proof:bonus?bonus.condition+' · obtention annoncée ; achat séparé non confirmé.':levels[v.st]||levels.vu,source:bonus?.source||null,verifiedAt:bonus?.verifiedAt||null,inspiration:v.insp||null,seen:v.src||null,st:v.st,edition:bonus?bonus.condition:null});}
 const ARM_CATS={pistolet:'Pistolets',pompe:'Fusils à pompe',pm:'Pistolets-mitrailleurs',assaut:'Fusils d’assaut',precision:'Fusils de précision',mitrailleuse:'Mitrailleuses',melee:'Corps à corps',projectile:'Projectiles',speciale:'Armes spéciales'};
 const characterName=id=>ed.characters.find(x=>x.id===id)?.name||null;
 for(const a of c.window.LK_ARMES){const item=calcFor(a.id,'weapon');add({key:'weapon:'+a.id,id:a.id,kind:'weapon',shard:'armes',name:a.nom,aliases:[a.fr,a.insp],category:'Arme · '+(ARM_CATS[a.cat]||a.cat),cat:a.cat,url:'/armes/'+a.id+'.html',image:item?.image,calcId:item?.id||null,price:item?.price,proof:levels[a.st]||levels.vu,source:null,verifiedAt:null,inspiration:a.insp||null,seen:a.src||null,st:a.st,ammo:a.mun||null,range:a.portee||null,context:a.ctx||null,owner:a.perso?characterName(a.perso):null,ultimate:!!a.ue});}
 const services=new Map((acqSrc.services||[]).map(s=>[s.ref,s]));
 for(const [group,kind,folder,label] of [['regions','place','lieux','Région'],['characters','character','personnages','Personnage'],['businesses','business','entreprises','Entreprise'],['residences','property','demeures','Demeure'],['hideouts','hideout','planques','Planque']])for(const x of ed[group]){const item=calcFor(x.id,kind),svc=services.get(x.id);const aliases=Array.isArray(x.aliases)?[...x.aliases]:[];if(kind==='character')aliases.push(x.name.split(/\s+/)[0]);
  add({key:kind+':'+x.id,id:x.id,kind,shard:'monde',name:x.name,aliases,category:label,url:'/'+folder+'/'+x.id+'.html',mapUrl:x.mapId?'/carte.html#lieu='+x.mapId:null,mapId:x.mapId||null,image:imageFor(x.media),calcId:kind==='place'?null:item?.id||null,price:item?.price,proof:kind==='place'?'Région présentée par Rockstar ; les endroits précis sont parfois à vérifier.':kind==='character'?'Personnage présenté dans les sources du site.':'Contenu recensé ; achat ou propriété du joueur non confirmé.',source:x.source||null,verifiedAt:x.verifiedAt||null,description:x.description||null,tagline:x.tagline||null,related:{places:x.places||x.relatedPlaces||[],characters:x.characters||[],vehicles:x.vehicles||[],home:x.home||null},ultimate:svc?svc.description:null});}
 const m=read('carte.js').match(/const POINTS\s*=\s*(\[[\s\S]*?\n\s*\]);/);if(!m)throw Error('Source des points de carte introuvable.');const points=vm.runInNewContext('('+m[1]+')');points.push(...c.window.LK_GTADB.groupes,...c.window.LK_GTADB.lieux);
 const REGION={'vice-city':'Vice City','leonida-keys':'Leonida Keys',grassrivers:'Grassrivers','port-gellhorn':'Port Gellhorn',ambrosia:'Ambrosia','mount-kalaga':'Mount Kalaga'};
 for(const p of points){if(rows.has('place:'+p.id))continue;add({key:'map:'+p.id,id:p.id,kind:'place',shard:'lieux',name:p.n,aliases:[],category:'Lieu recensé'+(p.p?' · '+p.p.replaceAll('-',' '):''),region:REGION[p.p]||(p.p?p.p.replaceAll('-',' '):null),url:'/carte.html#lieu='+p.id,image:p.img?'/'+p.img:null,calcId:null,price:null,proof:p.s==='officiel'?'Lieu montré dans les sources de la carte ; sa position exacte est à vérifier.':p.s==='spec'?'Position reconstituée par des joueurs, pas confirmée.':'Lieu recensé sur la carte ; position non confirmée par cette réponse.',source:null,verifiedAt:null,real:p.r?String(p.r).split(',')[0].trim():null,st:p.s||null});}
 for(const x of acq.items.filter(x=>!x.ref)){const item=catalog.find(a=>a.id===x.id||a.id===x.type+':'+x.id);add({key:x.type+':'+x.id,id:x.id,kind:x.type,shard:'monde',name:x.name,aliases:[],category:acq.categories.find(c=>c.id===x.category).label,url:x.hubUrl,image:x.images?.[0]?.variants?.[0]?.src,calcId:x.calculatorCompatible?item?.id||null:null,price:item?.price,proof:x.condition+' · '+(x.trackable?'obtention annoncée ; achat séparé non confirmé.':'collection annoncée ; pièces individuelles non listées.'),source:x.source,verifiedAt:x.verifiedAt,description:x.description||null,edition:x.condition||null});}
 /* lignes des catalogues (lots 5 et 6) : nom, catégorie, statut, effet, repère de la série, lieux, édition */
 {const C=require('./catalogues.cjs');const loaded=C.load();for(const f of C.FAMILIES){const fam=loaded.families[f],cats=new Map(fam.categories.map(x=>[x.id,x]));const byId=new Map(fam.items.map(it=>[it.id,it]));
   for(const row of C.leoRows(f)){const it=byId.get(row.id);const rep=it.prix_repere_serie;let repere=null;if(rep&&typeof rep==='object'){const val=rep.valeur!=null?rep.valeur+' $':(rep.min!=null?rep.min+' à '+rep.max+' $':null);repere=[val,rep.jeu,rep.note].filter(Boolean).join(' · ')||null;}
    const places=(it.ou_le_trouver||[]).map(o=>o.lieu?{id:o.lieu,name:(rows.get('map:'+o.lieu)||rows.get('place:'+o.lieu))?.name||null}:{type:o.type}).filter(o=>o.type||o.name);
    const src=(it.sources||[]).join(' ');const edition=/ultimate/i.test(src)?'Édition Ultimate':/vintage/i.test(src)?'Pack Vintage Vice City':it.acq?String(it.acq):null;
    add({...row,shard:'catalogues',family:f,famLabel:fam.label,cat:it.categorie,catLabel:cats.get(it.categorie)?.label||null,statut:it.statut,description:it.description||null,effect:it.effet&&it.effet.texte||null,repere,places,edition,compat:it.compat||null});}
   inputFiles.push('outils/catalogues/'+f+'.json');}inputFiles.push('outils/catalogues/sources.json','outils/catalogues/editorial.json');}
 for(const x of c.window.LK_COLLECTIBLES.items.filter(x=>x.published!==false&&!['placeholder','draft'].includes(x.status))){add({key:'collectible:'+x.id,id:x.id,kind:'collectible',shard:'catalogues',name:x.name,aliases:[],category:'Collectible',url:'/collectibles/'+x.slug+'.html',image:x.image,calcId:null,proof:'Statut et sources à consulter dans la fiche.',source:x.sources?.[0]?.url||null,verifiedAt:x.verifiedAt||null});}
 /* ---------- définitions, FAQ du Tuto, catégories ---------- */
 const d=doc('tuto.html'),flat=s=>String(s??'').replace(/\s+/g,' ').trim(),text=el=>el?flat(el.textContent):undefined;
 const definitions=defs.definitions.map(x=>{const url='/tuto.html#terme-'+x.id;routeOK(url);if(text(d.querySelector('#terme-'+x.id+' dd'))!==flat(x.text))throw Error('Glossaire divergent : '+x.id);return {...x,url};});
 const faq=defs.faq.map(x=>{routeOK(x.source);const section=d.getElementById(x.source.split('#')[1]);const answer=x.selector?d.querySelector(x.selector):[...section.querySelectorAll('details')].find(e=>text(e.querySelector('summary'))===flat(x.question))?.querySelector('p');if(!answer||!text(answer))throw Error('Réponse FAQ absente : '+x.id);return {id:x.id,terms:x.terms,text:text(answer),url:x.source};});
 const categories=defs.categories.filter(x=>exists(x.route.split('#')[0].slice(1))).map(x=>({...x,route:routeOK(x.route)}));

 /* ---------- questions rédigées ---------- */
 const kb=json('outils/leo-knowledge.json');if(kb.schemaVersion!==2||!Array.isArray(kb.topics))throw Error('Base de connaissances invalide (schéma 2 attendu).');
 const ids=new Set();const knowledge=kb.topics.map(x=>{if(!/^[a-z0-9-]+$/.test(x.id)||ids.has(x.id))throw Error('Identifiant de sujet invalide ou en double : '+x.id);ids.add(x.id);
  if(typeof x.q!=='string'||!x.q||!Array.isArray(x.f)||x.f.length<5||x.f.length>15||x.f.some(s=>typeof s!=='string'||!s))throw Error('Sujet sans question ou sans 5 à 15 formulations : '+x.id);
  if(typeof x.text!=='string'||!x.text||x.text.length>900)throw Error('Réponse absente ou trop longue : '+x.id);if(!Array.isArray(x.links)||!x.links.length)throw Error('Sujet sans page source : '+x.id);
  const links=x.links.map(l=>({label:tx(l.label),url:routeOK(l.url),...(l.tool?{tool:l.tool}:{})}));
  const action=x.action?{...x.action}:null;if(action){if(action.type==='map'){if(!rows.has('map:'+action.id)&&!rows.has('place:'+action.id))throw Error('Action carte vers un lieu absent : '+x.id+' → '+action.id);action.url='/carte.html#lieu='+action.id;}else if(action.type==='tool'){if(!defs.tools.some(t=>t.id===action.tool))throw Error('Action outil inconnue : '+x.id);action.url='/calculateurs.html?tool='+action.tool+'#atelier';}else if(action.type==='page')action.url=routeOK(action.url);else throw Error('Type d’action inconnu : '+x.id);}
  /* mots-clés hérités : gardés seulement s'ils apportent un radical absent des formulations et de la question canonique */const fset=new Set(x.f.map(s=>N.raw(s).join(' '))),fstems=new Set([...x.f,x.q].flatMap(s=>N.raw(s).map(N.stem)));const k=(x.k||[]).filter(w=>!fset.has(N.raw(w).join(' '))&&N.raw(w).map(N.stem).some(t=>t.length>=3&&!fstems.has(t)));
  return {id:x.id,q:tx(x.q),f:x.f,...(k.length?{k}:{}),text:tx(x.text),status:tx(x.status||''),links,...(x.source?{source:official(x.source)}:{}),...((x.checkedAt||kb.checkedAt)!==DEFAULT_DATE?{verifiedAt:x.checkedAt||kb.checkedAt}:{}),...(x.priority?{priority:true}:{}),...(x.min?{min:x.min}:{}),...(action?{action}:{}),_theme:x.theme||null};});
 /* v7.58 : aide liée à la page (LEO-02c) : chaque page citée existe (ou est un dossier de fiches), chaque sujet existe, chaque règle est une expression valide */
 const helpMap={pages:{}};{const H=defs.help&&defs.help.pages||{};const topicIds=ids;for(const [page,spec] of Object.entries(H)){if(!(page.endsWith('/')?fs.existsSync(path.join(root,page.slice(1))):exists(page.slice(1))))throw Error('Aide : page absente '+page);if(!topicIds.has(spec.topic))throw Error('Aide : sujet absent '+spec.topic+' ('+page+')');for(const r of spec.rules||[]){new RegExp(r.re);if(!topicIds.has(r.topic))throw Error('Aide : sujet absent '+r.topic+' ('+page+')');}helpMap.pages[page]={topic:spec.topic,rules:(spec.rules||[]).map(r=>({re:r.re,topic:r.topic}))};}}
 const written=knowledge.length;
 /* FAQ des cinq hubs du monde (v7.41) et des pages Consommables, Vêtements et style, Personnalisations (v7.42-43) : questions rédigées dans leurs JSON éditoriaux */
 {const hubsEd=json('outils/editorial-hubs.json');const HUB_LABEL={lieux:'Les lieux',personnages:'Les personnages',demeures:'Les demeures',planques:'Les planques',entreprises:'Les entreprises'};
  for(const hub of ['lieux','personnages','demeures','planques','entreprises'])(hubsEd[hub]?.faq||[]).forEach((x,i)=>{if(!Array.isArray(x.k)||!x.k.length||typeof x.a!=='string'||x.a.length>900)throw Error('FAQ du hub '+hub+' sans mots-clés ou trop longue : '+x.q);
   knowledge.push({id:'hub-'+hub+'-'+(i+1),q:tx(x.q),f:[x.q],k:x.k,text:tx(x.a),status:tx('Réponse de la FAQ « '+HUB_LABEL[hub]+' », sources en bas de la page'),links:[{label:'La FAQ et ses sources',url:routeOK('/'+hub+'.html#faq')}],verifiedAt:hubsEd.sources['rs-vi'].consultedAt,min:Number.isInteger(x.min)?x.min:2});});
  const acqEd=json('outils/catalogues/editorial.json');const acqVer=Object.values(require('./catalogues.cjs').load().sources).map(s=>s.consultedAt).sort().pop();const PAGES={nourriture:['Consommables','/nourriture.html'],style:['Vêtements et style','/style.html'],customizations:['Personnalisations','/personnalisations.html']};
  for(const [key,[label,page]] of Object.entries(PAGES))(acqEd[key]?.faq||[]).forEach((x,i)=>{if(!Array.isArray(x.k)||!x.k.length||typeof x.a!=='string'||x.a.length>900)throw Error('FAQ de '+key+' sans mots-clés ou trop longue : '+x.q);
   knowledge.push({id:'acq-'+key+'-'+(i+1),q:tx(x.q),f:[x.q],k:x.k,text:tx(x.a),status:tx('Réponse de la FAQ « '+label+' », sources en bas de la page'),links:[{label:'La FAQ et ses sources',url:routeOK(page+'#faq')}],verifiedAt:acqVer,min:Number.isInteger(x.min)?x.min:2});});}
 /* ---------- passages des pages ---------- */
 const passages=[];{const pages=[...fs.readdirSync(r).filter(f=>f.endsWith('.html')&&!f.startsWith('google')&&f!=='404.html'),...['lieux','personnages','entreprises','demeures','planques'].flatMap(dir=>fs.readdirSync(path.join(r,dir)).filter(f=>f.endsWith('.html')).map(f=>dir+'/'+f))].sort();
  for(const file of pages){const html=read(file);if(/http-equiv=["']refresh/i.test(html)||/name=["']robots["'][^>]*noindex/i.test(html))continue;const dd=doc(file),main=dd.querySelector('main');if(!main)continue;const title=flat(dd.querySelector('title')?.textContent||'').replace(/\s*\|\s*Leonidakit$/,'');
   for(const s of main.querySelectorAll('script,style,noscript,form,nav,table,figure,.lk-stack,.veh-grid,.arm-grid,.cmp-tray,.own-bar,#suggest,.leo-panel,[aria-hidden="true"],#sources,#sources-calc,[id^="src-"],[class*="ed-src"],.ed-sources'))s.remove();
   const textOf=node=>{let out='';const visit=n=>{for(const ch of n.childNodes){if(ch.nodeType===3)out+=ch.nodeValue;else if(ch.nodeType===1){if(ch.tagName==='BR')out+=' ';else{out+=' ';visit(ch);out+=' ';}}}};visit(node);return flat(out);};
   let heading='',anchor='',buffer=[],len=0;const flush=()=>{if(len>=Math.min(PASSAGE_MIN,120)){const t=buffer.join(' ');passages.push({p:'/'+file,a:anchor,t:title,h:heading,x:t});}buffer=[];len=0;};
   const walk=el=>{for(const node of el.children){const tag=node.tagName.toLowerCase();if(/^h[1-3]$/.test(tag)){flush();heading=textOf(node).replace(/^\d{2}\s*\/\s*[A-ZÉÈ' ]+\s*/,'');const anc=node.id||node.closest('[id]')?.id||'';if(anc&&anc!=='main')anchor=anc;continue;}
     if(['p','li','dd','dt','summary','blockquote'].includes(tag)){const t=textOf(node);if(t.length<25||/^(Voir la fiche|Retour au sommaire|Agrandir la capture|Essayer|Ouvrir)/.test(t))continue;const anc=node.closest('[id]')?.id||'';if(anc&&anc!=='main'&&!node.closest('section')?.id)anchor=anc;
      for(const sentence of t.split(/(?<=[.!?…])\s+(?=[A-ZÀ-Ý«0-9])/)){if(len+sentence.length>PASSAGE_MAX&&len>=PASSAGE_MIN)flush();buffer.push(sentence);len+=sentence.length+1;}if(len>=PASSAGE_MAX)flush();continue;}
     if(node.children.length)walk(node);}};
   walk(main);flush();}}
 for(const p of passages)if(p.a){const file=p.p.slice(1);if(!doc(file).getElementById(p.a))p.a='';}
 /* ---------- lexique et vocabulaire ---------- */
 /* Les noms de fiches ne sont jamais réécrits par le lexique : une entrée d'un seul mot qui réécrit un nom d'un seul mot (Sprunk → boisson) est refusée ;
    un nom de plusieurs mots que le lexique changerait (« Ocean Beach » → « ocean plage ») reçoit une entrée identité, ajoutée au lexique du noyau. */
 const baseAnalyzer=N.createAnalyzer(lex),protectedNames=new Map();
 for(const it of rows.values())for(const n of [it.name,...(it.aliases||[])]){const r=N.raw(n);if(!r.length)continue;const e=baseAnalyzer.expand(r).tokens;if(e.join(' ')===r.join(' '))continue;if(r.length===1)throw Error('Le lexique réécrit le nom de fiche « '+n+' » ('+it.key+') en « '+e.join(' ')+'» : retire cette entrée de outils/leo-lexique.json.');protectedNames.set(r.join(' '),r.join(' '));}
 const lexFinal={...lex,abbreviations:[...lex.abbreviations,...[...protectedNames.keys()].sort().map(f=>({f,to:f,c:'nom'}))]};
 const analyzer=N.createAnalyzer(lexFinal),vocabOf=list=>{const v=new Set();for(const s of list)for(const t of analyzer.analyze(s).terms)if(t.length>=3&&!/^\d+$/.test(t))v.add(t.slice(0,6));return [...v].sort();};
 const items=[...rows.values()];const byShard={};for(const it of items){(byShard[it.shard]=byShard[it.shard]||[]).push(it);}
 const nameEntry=x=>[x.key,x.name,x.kind,x.aliases];
 const names=[...(byShard.armes||[]),...(byShard.monde||[])].map(nameEntry);
 /* noms sans mot de deux lettres ou plus (« P’s & Q’s ») : reconnus par leur suite de lettres ; le noyau garde cette suite et le morceau qui porte la fiche */
 const seqOf=n=>{const r=N.raw(n);return r.length>=2&&r.join('').length>=3&&r.every(t=>t.length===1)&&!r.every(t=>/^\d$/.test(t))?r.join(' '):null;};const seqNames=items.filter(x=>seqOf(x.name)&&x.shard!=='armes'&&x.shard!=='monde').flatMap(x=>[...new Set([seqOf(x.name),N.raw(x.name.replace(/[’']/g,'')).join(' ')])].map(q=>[q,x.shard])).sort((a,b)=>a[0].localeCompare(b[0]));
 const vocab={vehicules:vocabOf((byShard.vehicules||[]).flatMap(x=>[x.name,...x.aliases])),catalogues:vocabOf((byShard.catalogues||[]).flatMap(x=>[x.name,...x.aliases])),lieux:vocabOf((byShard.lieux||[]).map(x=>x.name))};
 /* ---------- sorties ---------- */
 const release={date:acq.game.releaseDate,verifiedAt:acq.game.checkedAt,status:acq.game.status,source:official(acq.sources.ultimate.url),maxAgeDays:30};
 const compactLex={abbreviations:lexFinal.abbreviations.map(x=>[x.f,x.to]),english:lex.english.map(x=>[x.f,x.to]),concepts:lex.concepts};
 const deepTx=o=>Array.isArray(o)?o.map(deepTx):o&&typeof o==='object'?Object.fromEntries(Object.entries(o).map(([k,v])=>[k,deepTx(v)])):tx(o);
 /* Le thème « calculateur » (une soixantaine de questions) est un morceau à part, chargé dès qu'une question en parle ou dès l'ouverture sur le calculateur et le Tuto : il allège le noyau. */
 const calcTopics=knowledge.filter(t=>t._theme==='calculateur'),coreTopics=knowledge.filter(t=>t._theme!=='calculateur'),stripTheme=t=>{/* les formulations sont livrées déjà analysées (d, dq, dk : jetons séparés par des espaces, même analyseur que dans le navigateur) : le navigateur n'a rien à réanalyser à l'ouverture */const o={...t},terms=x=>analyzer.analyze(x).terms.join(' ');delete o._theme;o.d=t.f.map(terms);o.dq=terms(t.q);if(t.k&&t.k.length)o.dk=[...new Set(t.k.flatMap(k=>analyzer.analyze(k).terms))].join(' ');delete o.f;delete o.k;return o;};
 const shards={calculateur:{file:'/leo/calculateur.json',knowledge:true,vocab:vocabOf(calcTopics.flatMap(t=>[t.q,...t.f,...(t.k||[])]))},vehicules:{file:'/leo/vehicules.json',vocab:vocab.vehicules},armes:{file:'/leo/armes.json'},monde:{file:'/leo/monde.json'},lieux:{file:'/leo/lieux.json',vocab:vocab.lieux,packed:['id','name','region','st','image','real','proof','nt']},catalogues:{file:'/leo/catalogues.json',vocab:vocab.catalogues},passages:{file:'/leo/passages.json'}};
 const core={schemaVersion:2,checkedAt:DEFAULT_DATE,release,categories,tools:defs.tools,definitions,faq,texts:deepTx(defs.texts),templates:deepTx(defs.templates),suggestions:deepTx(defs.suggestions),help:helpMap,offtopic:defs.offtopic,lexique:compactLex,seqNames,official:officialLinks,knowledge:coreTopics.map(stripTheme),names,shards};
 core.revision=crypto.createHash('sha256').update(JSON.stringify(core)).digest('hex').slice(0,12);
 const outputs=new Map();outputs.set('leo-index.json',JSON.stringify(core));
 const strip=x=>Object.fromEntries(Object.entries(x).filter(([k,v])=>k!=='id'&&k!=='shard'&&v!==null&&v!==undefined&&!(Array.isArray(v)&&!v.length)));
 /* jetons des noms calculés d'avance (« jetons|repères », voir N.nameTokens) : le navigateur n'analyse pas 2 500 noms au chargement d'un morceau */
 const ntOf=x=>{const t=N.nameTokens(analyzer,x.name);return t&&!t.seqs?t.toks.join(' ')+'|'+t.minor.join(' '):null;};
 for(const [name,list] of Object.entries(byShard)){const proofs=[...new Set(list.map(x=>x.proof))];
  if(name==='lieux'){/* forme compacte : [id, nom, région, statut, image (1 = photo dérivée de l'identifiant, sinon le chemin), équivalent réel, indice de preuve, jetons du nom] */
   const packed=list.map(x=>{const derived='/photos/'+x.id.replace(/^g-/,'')+',ig.webp';return [x.id,x.name,x.region||'',x.st||'',x.image?(x.image===derived?1:x.image):0,x.real||'',proofs.indexOf(x.proof),ntOf(x)||0];});
   outputs.set('leo/lieux.json',JSON.stringify({schemaVersion:2,shard:name,revision:core.revision,proofs,packed:shards.lieux.packed,items:packed}));continue;}
  /* sources (URL longues), libellés de famille et de catégorie mis en table : chaque fiche ne garde qu'un indice */
  const sources=[...new Set(list.map(x=>x.source).filter(Boolean))],labels=[...new Set(list.flatMap(x=>[x.famLabel,x.catLabel]).filter(Boolean))];
  const packed=list.map(x=>strip({...x,proof:proofs.indexOf(x.proof),source:x.source?sources.indexOf(x.source):null,famLabel:x.famLabel?labels.indexOf(x.famLabel):null,catLabel:x.catLabel?labels.indexOf(x.catLabel):null,nt:name==='vehicules'||name==='catalogues'?ntOf(x):null}));
  outputs.set('leo/'+name+'.json',JSON.stringify({schemaVersion:2,shard:name,revision:core.revision,proofs,sources,labels,items:packed}));}
 outputs.set('leo/calculateur.json',JSON.stringify({schemaVersion:2,shard:'calculateur',revision:core.revision,knowledge:calcTopics.map(stripTheme)}));
 /* passages : jetons calculés d'avance (s), même analyseur que dans le navigateur */
 outputs.set('leo/passages.json',JSON.stringify({schemaVersion:2,shard:'passages',revision:core.revision,items:passages.map(p=>({...p,s:analyzer.analyze(p.h+' '+p.x).terms.join(' ')}))}));
 const coreBytes=Buffer.byteLength(outputs.get('leo-index.json'));if(coreBytes>CORE_MAX)throw Error('Noyau de Léo trop lourd : '+coreBytes+' octets (maximum '+CORE_MAX+').');
 const inputs=Object.fromEntries([...new Set([...inputFiles,...linked])].sort().map(f=>[f,crypto.createHash('sha256').update(read(f).replace(/\?v=[a-f0-9]+/g,'')).digest('hex')]));
 const sizes=Object.fromEntries([...outputs].map(([f,s])=>[f,Buffer.byteLength(s)]));
 const generated=Object.entries(byShard).reduce((n,[k,list])=>n+list.length*({vehicules:7,armes:8,monde:6,lieux:5,catalogues:5}[k]||0),0);
 const meta=JSON.stringify({schemaVersion:2,inputs,outputs:sizes,counts:{questionsRedigees:written,questionsFaq:knowledge.length-written,questionsGenerees:generated,fiches:items.length,passages:passages.length,lexique:lex.abbreviations.length,nomsProteges:protectedNames.size,anglais:lex.english.length,concepts:Object.keys(lex.concepts).length}},null,2)+'\n';outputs.set('outils/leo-index-manifest.json',meta);
 if(!options.check)fs.mkdirSync(path.join(r,'leo'),{recursive:true});
 for(const [file,content] of outputs){if(options.check){if(!exists(file)||read(file)!==content)throw Error('Index Léo à régénérer : '+file);}else fs.writeFileSync(path.join(r,file),content);}
 docs.forEach(x=>x.window.close());return {questions:written,faq:knowledge.length-written,generated,items:items.length,passages:passages.length,bytes:coreBytes,outputs:sizes};
}
if(require.main===module)console.log(JSON.stringify(generate({check:process.argv.includes('--check')})));module.exports={generate};
