#!/usr/bin/env node
'use strict';
// Projection compacte des sources réellement livrées. Aucun catalogue maintenu à la main.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const {JSDOM}=require('jsdom');const root=path.resolve(__dirname,'..');
function generate(options={}){
 const r=options.root||root,read=f=>fs.readFileSync(path.join(r,f),'utf8'),json=f=>JSON.parse(read(f)),exists=f=>fs.existsSync(path.join(r,f));
 const defs=json('outils/leo-editorial.json'),ed=json('outils/editorial.json'),med=json('outils/medias-officiels.json'),c={window:{}};
 const inputFiles=['vehicules-data.js','armes-data.js','carte-gtadb.js','carte.js','outils/editorial.json','outils/medias-officiels.json','outils/leo-editorial.json','tuto.html','outils/tuto.json','calculateurs-data.js','calculateurs-catalogue.js','acquisitions-data.js','collectibles-data.js','assets-manifest.js'];
 for(const f of ['vehicules-data.js','armes-data.js','calculateurs-catalogue.js','acquisitions-data.js','assets-manifest.js','calculateurs-data.js','carte-gtadb.js','collectibles-data.js'])vm.runInNewContext(read(f),c);
 const catalog=c.window.LKCalcData.catalogue(),acq=c.window.LK_ACQUISITIONS,rows=new Map(),docs=new Map(),linked=new Set();
 const doc=file=>{if(!docs.has(file))docs.set(file,new JSDOM(read(file)));return docs.get(file).window.document;};
 const routeOK=url=>{if(typeof url!=='string'||!/^\/(?!\/)[a-z0-9/_-]+\.html(?:#[a-z0-9=_-]+)?$/i.test(url))throw Error('Route invalide : '+url);const [file,hash]=url.slice(1).split('#');if(!exists(file))throw Error('Page absente : '+file);if(hash&&!hash.includes('=')&&!doc(file).getElementById(hash))throw Error('Ancre absente : '+url);linked.add(file);return url;};
 const image=url=>typeof url==='string'&&/^\/(?:img|photos)\/[a-z0-9/_,.-]+\.(?:webp|svg|png)$/i.test(url)&&exists(url.slice(1))?url:null;
 const imageFor=ids=>(ids||[]).flatMap(id=>med[id]?.variants||[]).map(x=>x.src).map(image).find(Boolean)||null;
 const calcFor=(id,type)=>catalog.find(x=>x.type===type&&(x.id===id||x.id===type+':'+id));
 function add(x){if(rows.has(x.key))return;routeOK(x.url);if(x.mapUrl)routeOK(x.mapUrl);rows.set(x.key,{...x,aliases:[...new Set((x.aliases||[]).filter(Boolean))],image:image(x.image),price:typeof x.price==='number'&&Number.isFinite(x.price)?x.price:null});}
 const levels={officiel:'Nom confirmé par Rockstar. On ne sait pas encore si ça s’achète à part.',comm:'Identification communautaire, non confirmée par Rockstar ; achat séparé inconnu.',vu:'Recensé sur le site : vu dans les médias officiels. On ne sait pas encore si ça s’achète.',probable:'On pense que c’est ça, sans certitude.',spec:'Info venant de joueurs, à vérifier.',possible:'À vérifier.'};
 for(const v of c.window.LK_VEHICULES){const item=calcFor(v.id,'vehicle'),bonus=acq.items.find(x=>x.ref?.type==='vehicle'&&x.ref.id===v.id);add({key:'vehicle:'+v.id,id:v.id,kind:'vehicle',name:((v.marque||'')+' '+v.nom).trim(),aliases:[v.nom,v.insp],category:'Véhicule · '+v.cat,url:'/vehicules/'+v.id+'.html',image:item?.image||v.thumb,calcId:item?.id||null,price:item?.price,proof:bonus?bonus.condition+' · obtention annoncée ; achat séparé non confirmé.':levels[v.st]||levels.vu,source:bonus?.source||null,verifiedAt:bonus?.verifiedAt||null,inspiration:v.insp||null});}
 for(const a of c.window.LK_ARMES){const item=calcFor(a.id,'weapon');add({key:'weapon:'+a.id,id:a.id,kind:'weapon',name:a.nom,aliases:[a.fr,a.insp],category:'Arme · '+a.cat,url:'/armes/'+a.id+'.html',image:item?.image,calcId:item?.id||null,price:item?.price,proof:levels[a.st]||levels.vu,source:null,verifiedAt:null,inspiration:a.insp||null});}
 for(const [group,kind,folder,label] of [['regions','place','lieux','Région'],['characters','character','personnages','Personnage'],['businesses','business','entreprises','Entreprise'],['residences','property','demeures','Demeure'],['hideouts','hideout','planques','Planque']])for(const x of ed[group]){const item=calcFor(x.id,kind);add({key:kind+':'+x.id,id:x.id,kind,name:x.name,aliases:Array.isArray(x.aliases)?x.aliases:[],category:label,url:'/'+folder+'/'+x.id+'.html',mapUrl:x.mapId?'/carte.html#lieu='+x.mapId:null,image:imageFor(x.media),calcId:kind==='place'?null:item?.id||null,price:item?.price,proof:kind==='place'?'Région présentée par Rockstar ; les endroits précis sont parfois à vérifier.':kind==='character'?'Personnage présenté dans les sources du site.':'Contenu recensé ; achat ou propriété du joueur non confirmé.',source:x.source||null,verifiedAt:x.verifiedAt||null});}
 const m=read('carte.js').match(/const POINTS\s*=\s*(\[[\s\S]*?\n\s*\]);/);if(!m)throw Error('Source des points de carte introuvable.');const points=vm.runInNewContext('('+m[1]+')');points.push(...c.window.LK_GTADB.groupes,...c.window.LK_GTADB.lieux);
 for(const p of points){if(rows.has('place:'+p.id))continue;add({key:'map:'+p.id,id:p.id,kind:'place',name:p.n,aliases:[],category:'Lieu recensé'+(p.p?' · '+p.p.replaceAll('-',' '):''),url:'/carte.html#lieu='+p.id,image:p.img?'/'+p.img:null,calcId:null,price:null,proof:p.s==='officiel'?'Lieu montré dans les sources de la carte ; sa position exacte est à vérifier.':p.s==='spec'?'Position reconstituée par des joueurs, pas confirmée.':'Lieu recensé sur la carte ; position non confirmée par cette réponse.',source:null,verifiedAt:null});}
 for(const x of acq.items.filter(x=>!x.ref)){const item=catalog.find(a=>a.id===x.id||a.id===x.type+':'+x.id);add({key:x.type+':'+x.id,id:x.id,kind:x.type,name:x.name,aliases:[],category:acq.categories.find(c=>c.id===x.category).label,url:x.hubUrl,image:x.images?.[0]?.variants?.[0]?.src,calcId:x.calculatorCompatible?item?.id||null:null,price:item?.price,proof:x.condition+' · '+(x.trackable?'obtention annoncée ; achat séparé non confirmé.':'collection annoncée ; pièces individuelles non listées.'),source:x.source,verifiedAt:x.verifiedAt});}
 for(const x of c.window.LK_COLLECTIBLES.items.filter(x=>x.published!==false&&!['placeholder','draft'].includes(x.status))){add({key:'collectible:'+x.id,id:x.id,kind:'collectible',name:x.name,aliases:[],category:'Collectible',url:'/collectibles/'+x.slug+'.html',image:x.image,calcId:null,proof:'Statut et sources à consulter dans la fiche.',source:x.sources?.[0]?.url||null,verifiedAt:x.verifiedAt||null});}
 const d=doc('tuto.html'),text=el=>el?.textContent.replace(/\s+/g,' ').trim();
 const definitions=defs.definitions.map(x=>{const url='/tuto.html#terme-'+x.id;routeOK(url);if(text(d.querySelector('#terme-'+x.id+' dd'))!==x.text)throw Error('Glossaire divergent : '+x.id);return {...x,url};});
 const faq=defs.faq.map(x=>{routeOK(x.source);const section=d.getElementById(x.source.split('#')[1]);const answer=x.selector?d.querySelector(x.selector):[...section.querySelectorAll('details')].find(e=>text(e.querySelector('summary'))===x.question)?.querySelector('p');if(!answer||!text(answer))throw Error('Réponse FAQ absente : '+x.id);return {id:x.id,terms:x.terms,text:text(answer),url:x.source};});
 const categories=defs.categories.filter(x=>exists(x.route.split('#')[0].slice(1))).map(x=>({...x,route:routeOK(x.route)}));
 const release={date:acq.game.releaseDate,verifiedAt:acq.game.checkedAt,status:acq.game.status,source:acq.sources.ultimate.url,maxAgeDays:30};
 const inputs=Object.fromEntries([...new Set([...inputFiles,...linked])].sort().map(f=>[f,crypto.createHash('sha256').update(read(f).replace(/\?v=[a-f0-9]+/g,'')).digest('hex')]));
 const proofs=[...new Set([...rows.values()].map(x=>x.proof))],items=[...rows.values()].map(x=>Object.fromEntries(Object.entries({...x,proof:proofs.indexOf(x.proof)}).filter(([k,v])=>k!=='id'&&v!==null&&v!==undefined&&!(Array.isArray(v)&&!v.length))));
 const data={schemaVersion:1,release,categories,tools:defs.tools,definitions,faq,proofs,items};data.revision=crypto.createHash('sha256').update(JSON.stringify(data)).digest('hex').slice(0,12);const encoded=JSON.stringify(data),meta=JSON.stringify({schemaVersion:1,inputs,items:data.items.length,bytes:Buffer.byteLength(encoded)},null,2)+'\n';
 for(const [file,content] of [['leo-index.json',encoded],['outils/leo-index-manifest.json',meta]]){if(options.check){if(!exists(file)||read(file)!==content)throw Error('Index Léo à régénérer : '+file);}else fs.writeFileSync(path.join(r,file),content);}
 docs.forEach(x=>x.window.close());return {items:data.items.length,bytes:Buffer.byteLength(encoded),categories:categories.length};
}
if(require.main===module)console.log(JSON.stringify(generate({check:process.argv.includes('--check')})));module.exports={generate};
