/* ============================================================
   LEONIDAKIT — armes : source de vérité
   Chaque arme porte son niveau de certitude :
     st: 'officiel'  nom publié par Rockstar dans un support officiel
     st: 'vu'        visible dans un média officiel, nom non communiqué
   Aucune donnée issue de fuites.
   Images : visuels officiels Rockstar listés dans outils/armes-medias.json (registre outils/medias-officiels.json).
   Fiches et hub régénérés par node outils/gen-armes.cjs ; les textes sont écrits ici, pas dans les fiches.
   ============================================================ */
window.LK_ARMES = [
{"id":"girardi-es9","nom":"Girardi ES9","fr":"Pistola de Jason","cat":"pistolet","slot":"poing","st":"officiel","src":"Material de la reserva de la edición Ultimate","insp":"Beretta 92FS","mun":"Munición de pistola","portee":"Corto a medio","ctx":"La pistola personal de Jason, nombrada por Rockstar en la presentación de la edición Ultimate, que incluye una versión grabada. Es el arma corta que más se ve en el material oficial.","perso":"jason","ue":true},
{"id":"klose-k17","nom":"Klose K17","fr":"Pistola de Lucia","cat":"pistolet","slot":"poing","st":"officiel","src":"Material de la reserva de la edición Ultimate","insp":"Glock 17 / SIG P320","mun":"Munición de pistola","portee":"Corto a medio","ctx":"La pistola personal de Lucia, nombrada por Rockstar, con una versión grabada con rosas en la edición Ultimate. Pistola moderna con armazón de polímero y raíl para accesorios.","perso":"lucia","ue":true},
{"id":"nipper-38","nom":"Nipper .38","fr":"Pistola compacta","cat":"pistolet","slot":"poing","st":"officiel","src":"Nombre grabado en el arma, portada oficial","insp":"Bersa Thunder 380","mun":"Munición de pistola","portee":"Corto","ctx":"La pequeña pistola que Lucia sostiene en la portada oficial. Su nombre se lee en la corredera: es una de las pocas armas cuyo nombre sale directamente de una imagen de Rockstar.","perso":"lucia"},
{"id":"hawk-little-morgan","nom":"Hawk & Little Morgan","fr":"Revólveres grabados","cat":"pistolet","slot":"poing","st":"officiel","src":"Material de la reserva de la edición Ultimate","insp":"Smith & Wesson 629","mun":"Munición de pistola","portee":"Medio","ctx":"Una pareja de revólveres grabados, uno para Jason y otro para Lucia, que Rockstar describe como inspirados en la mansión Vercetti de Vice City. Cachas con palmeras, grabados con el nombre y mira de alto rendimiento.","ue":true},
{"id":"pistolet-custom","nom":"Pistola personalizada","fr":null,"cat":"pistolet","slot":"poing","st":"vu","src":"Segundo tráiler","insp":"Colt 1911","mun":"Munición de pistola","portee":"Corto a medio","ctx":"Pistola con acabado personalizado, visible en una escena de interior. Los acabados que se ven hacen pensar que la personalización de armas vuelve."},
{"id":"pistolet-auto","nom":"Pistola con selector","fr":null,"cat":"pistolet","slot":"poing","st":"vu","src":"Extended Look del 27 de agosto de 2026","insp":"Glock con switch","mun":"Munición de pistola","portee":"Corto","ctx":"Pistola equipada con un selector de tiro en la parte trasera de la corredera, un detalle visible en las secuencias de gameplay. Convertiría una pistola semiautomática en un arma de ráfagas."},
{"id":"mustang-357","nom":"Mustang .357","fr":"Revólver de los moteros","cat":"pistolet","slot":"poing","st":"officiel","src":"Nombre grabado en el arma, captura oficial de Ambrosia","insp":"Colt Python","mun":"Munición de pistola","portee":"Medio","ctx":"El gran revólver que empuña una motera en la tercera captura de Ambrosia, colgada del cuello de un miembro de la banda del parche Enforcer. El nombre Mustang .357 está grabado en el arma: es la quinta arma cuyo nombre sale directamente de una imagen de Rockstar. Cañón ventilado y tambor grande de Colt Python, el mágnum de película, aquí en manos de los moteros del interior."},
{"id":"fusil-double","nom":"Escopeta de doble cañón","fr":null,"cat":"pompe","slot":"longue","st":"vu","src":"Segundo tráiler","insp":"Escopeta de caza paralela","mun":"Cartuchos","portee":"Muy corto","ctx":"Escopeta de dos cañones yuxtapuestos, asociada a las zonas rurales y a los pantanos en el material oficial. El barbudo en primer plano de la sexta captura de Grassrivers lleva una al hombro, con guarniciones grabadas y culata de madera, delante del aligátor colgado en su taller."},
{"id":"fusil-pompe","nom":"Escopeta de corredera","fr":null,"cat":"pompe","slot":"longue","st":"vu","src":"Primer tráiler","insp":"Mossberg 590","mun":"Cartuchos","portee":"Muy corto","ctx":"Escopeta de corredera clásica, vista en escenas de enfrentamiento. Arma de corto alcance típica de la saga."},
{"id":"micro-smg","nom":"Subfusil con motivo tropical","fr":null,"cat":"pm","slot":"poing","st":"vu","src":"Imagen de la edición Ultimate","insp":"Mini Uzi","mun":"Munición de pistola","portee":"Corto","ctx":"Subfusil compacto con motivo tropical, mostrado en la imagen de la edición Ultimate sin que Rockstar haya publicado su nombre. Se puede usar con una mano, en la línea de las armas para disparar desde el coche.","ue":true},
{"id":"smg-compact","nom":"Subfusil compacto","fr":null,"cat":"pm","slot":"poing","st":"vu","src":"Extended Look del 27 de agosto de 2026","insp":"Škorpion","mun":"Munición de pistola","portee":"Corto","ctx":"Arma automática muy corta, vista en una escena de acción a corta distancia."},
{"id":"smg","nom":"Subfusil","fr":null,"cat":"pm","slot":"longue","st":"vu","src":"Segundo tráiler","insp":"H&K MP5","mun":"Munición de pistola","portee":"Corto a medio","ctx":"Subfusil sostenido con las dos manos por Jason y Lucia durante el golpe del segundo tráiler. La versión de Jason lleva un visor de punto rojo."},
{"id":"pm-tactique","nom":"Subfusil de culata plegable","fr":null,"cat":"pm","slot":"longue","st":"vu","src":"Imagen de la edición Ultimate","insp":null,"mun":"Munición de pistola","portee":"Corto a medio","ctx":"Colocado en el asiento de un coche entre los fajos de billetes, con una pistola a juego, en la imagen Weapon Pattern del Vintage Vice City Pack. Culata plegada, cargador recto delante de la empuñadura, acabado turquesa con palmeras: un subfusil moderno y compacto, distinto del pequeño subfusil con motivo tropical que Jason sostiene en las imágenes de atuendos. Su nombre no se ha comunicado.","ue":true,"fam":"Subfusil moderno con culata plegable"},
{"id":"carabine","nom":"Carabina","fr":null,"cat":"assaut","slot":"longue","st":"vu","src":"Segundo tráiler","insp":"AR-15 / M4","mun":"Munición de fusil","portee":"Medio a largo","ctx":"Carabina moderna con culata telescópica, visible en varias secuencias de acción."},
{"id":"fusil-assaut","nom":"Fusil de asalto","fr":null,"cat":"assaut","slot":"longue","st":"vu","src":"Primer tráiler","insp":"AK","mun":"Munición de fusil","portee":"Medio a largo","ctx":"Fusil de asalto con el característico cargador curvo, visto en manos de antagonistas."},
{"id":"fusil-precision","nom":"Fusil de cerrojo","fr":null,"cat":"precision","slot":"longue","st":"vu","src":"Extended Look del 27 de agosto de 2026","insp":"Remington 700","mun":"Munición de fusil","portee":"Larga","ctx":"Fusil de cerrojo con mira telescópica, visto en un contexto de tiro a distancia."},
{"id":"fusil-semi-auto","nom":"Fusil semiautomático","fr":null,"cat":"precision","slot":"longue","st":"vu","src":"Capturas oficiales","insp":"Springfield M1A","mun":"Munición de fusil","portee":"Larga","ctx":"El largo fusil con culata de madera y mira que sostiene uno de los tres hombres que posan delante de su hidrodeslizador, en la primera captura de Grassrivers. El cajón alargado y la culata tradicional recuerdan al M1A, la versión civil del M14: un arma de caza y de tiro a larga distancia, más rústica que el fusil de cerrojo y perfecta para los pantanos."},
{"id":"mitrailleuse","nom":"Ametralladora de combate","fr":null,"cat":"mitrailleuse","slot":"longue","st":"vu","src":"Extended Look del 27 de agosto de 2026","insp":"M249 SAW","mun":"Munición pesada","portee":"Medio","ctx":"Arma de apoyo alimentada por cinta, la más pesada vista hasta ahora."},
{"id":"batte","nom":"Bate de béisbol","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Primer tráiler","insp":null,"mun":null,"portee":"Cuerpo a cuerpo","ctx":"Bate de béisbol, arma cuerpo a cuerpo habitual en la saga. Las animaciones cuerpo a cuerpo se han rehecho con captura de movimiento.","fam":"Batte de baseball en aluminium"},
{"id":"couteau-cran","nom":"Navaja automática","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Imagen de la edición Ultimate","insp":null,"mun":null,"portee":"Cuerpo a cuerpo","ctx":"Navaja de hoja retráctil, visible en la imagen de la edición Ultimate junto a los revólveres grabados.","ue":true,"fam":"Navaja automática"},
{"id":"club-golf","nom":"Palo de golf","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Segundo tráiler","insp":null,"mun":null,"portee":"Cuerpo a cuerpo","ctx":"Palo de golf que se puede usar como arma cuerpo a cuerpo, en la línea de los objetos cotidianos convertidos en armas.","fam":"Fer de golf"},
{"id":"marteau","nom":"Martillo","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Extended Look del 27 de agosto de 2026","insp":null,"mun":null,"portee":"Cuerpo a cuerpo","ctx":"Martillo de obra, visto como arma improvisada.","fam":"Marteau de charpentier"},
{"id":"queue-billard","nom":"Taco de billar","fr":null,"cat":"melee","slot":"poing","st":"vu","src":"Extended Look del 27 de agosto de 2026","insp":null,"mun":null,"portee":"Cuerpo a cuerpo","ctx":"Taco de billar, arma cuerpo a cuerpo ligada a los lugares de ocio de Leonida.","fam":"Queue de billard américain"},
{"id":"molotov","nom":"Cóctel molotov","fr":null,"cat":"projectile","slot":"poing","st":"vu","src":"Segundo tráiler","insp":null,"mun":null,"portee":"Jet","ctx":"Cóctel molotov, proyectil incendiario clásico de la saga.","fam":"Botella incendiaria improvisada"},
{"id":"fumigene","nom":"Granada de humo","fr":null,"cat":"projectile","slot":"poing","st":"vu","src":"Extended Look del 27 de agosto de 2026","insp":null,"mun":null,"portee":"Jet","ctx":"Granada de humo, proyectil no letal que sirve para ocultar un movimiento.","fam":"Granada de humo de mano"},
{"id":"harpon","nom":"Fusil de arpón","fr":null,"cat":"speciale","slot":"longue","st":"vu","src":"Extended Look del 27 de agosto de 2026","insp":null,"mun":"Arpones","portee":"Corto, bajo el agua","ctx":"Fusil de arpón, arma submarina. Es una novedad en la saga: acompaña a las zonas sumergidas que se pueden explorar.","fam":"Fusil de pesca submarina de gomas"},
{"id":"lance-grenades","nom":"Lanzagranadas","fr":null,"cat":"speciale","slot":"longue","st":"vu","src":"Segundo tráiler","insp":"Milkor MGL","mun":"Granadas","portee":"Medio","ctx":"Lucia lo lleva durante la persecución con la policía del segundo tráiler, justo cuando un vehículo explota detrás de ella. El gran tambor que asoma bajo el cañón no deja lugar a dudas: un lanzagranadas de tambor del tipo Milkor MGL, el regreso del arma pesada más espectacular de la saga."}
];
window.LK_ARMES_CATS = {
  pistolet:'Pistolas', pompe:'Escopetas', pm:'Subfusiles', assaut:"Fusiles de asalto",
  precision:'Fusiles de precisión', mitrailleuse:'Ametralladoras', melee:'Cuerpo a cuerpo', projectile:'Arrojadizas', speciale:'Especiales'
};
