const fs=require('fs'),path=require('path'),crypto=require('crypto'),vm=require('vm');
const {JSDOM}=require('jsdom'),postcss=require('postcss');
const root=path.resolve(process.argv[2]||path.join(__dirname,'..')),out=path.resolve(process.argv[3]||path.join(root,'audit/scans'));fs.mkdirSync(out,{recursive:true});
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>['node_modules','dist','.git','audit'].includes(e.name)?[]:e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);
const files=walk(root),known=new Set(files.map(f=>path.relative(root,f).replaceAll('\\','/'))),issues=[],pages=[],inventory=[];const add=(kind,file,detail)=>issues.push({kind,file,detail});
const data={window:{}};for(const f of ['vehicules-data.js','armes-data.js','search-index.js','carte-gtadb.js'])vm.runInNewContext(fs.readFileSync(path.join(root,f),'utf8'),data);
const cs=fs.readFileSync(path.join(root,'carte.js'),'utf8');const localPoints=vm.runInNewContext('('+cs.match(/const POINTS = (\[[\s\S]*?\n  \]);/)[1]+')');const points=[...localPoints,...data.window.LK_GTADB.groupes,...data.window.LK_GTADB.lieux];const pointIds=new Set(points.map(p=>p.id));
const check=(file,url,kind)=>{if(!url||/^(data:|mailto:|tel:|javascript:)/.test(url))return;let u;try{u=new URL(url,'https://www.leonidakit.com/'+file)}catch(e){add('invalid-url',file,url);return}if(u.origin!=='https://www.leonidakit.com')return;let rel=decodeURIComponent(u.pathname).slice(1)||'index.html';if(!known.has(rel)){add('missing-'+kind,file,rel);return;}if(kind==='link'&&u.hash.startsWith('#lieu=')&&!pointIds.has(u.hash.slice(6)))add('missing-map-id',file,u.hash);return rel;};
for(const f of files){const rel=path.relative(root,f);let b=fs.readFileSync(f);inventory.push({file:rel,bytes:b.length,sha256:crypto.createHash('sha256').update(b).digest('hex')});if(f.endsWith('.js')||f.endsWith('.cjs')){try{new vm.Script(b.toString(),{filename:rel})}catch(e){add('syntax-js',rel,e.message)}}
 if(f.endsWith('.css'))try{postcss.parse(b.toString(),{from:rel})}catch(e){add('syntax-css',rel,e.reason)}
 if(f.endsWith('.json'))try{JSON.parse(b.toString())}catch(e){add('syntax-json',rel,e.message)}
 if(!f.endsWith('.html'))continue;const dom=new JSDOM(b.toString()),d=dom.window.document;const page={file:rel,title:d.title,description:d.querySelector('meta[name=description]')?.content,canonical:d.querySelector('link[rel=canonical]')?.getAttribute('href'),robots:d.querySelector('meta[name=robots]')?.content,h1:[...d.querySelectorAll('h1')].map(x=>x.textContent),scripts:[],links:[],assets:[],ids:[]};
 const ids=new Set();for(const e of d.querySelectorAll('[id]')){if(ids.has(e.id))add('duplicate-dom-id',rel,e.id);ids.add(e.id)}page.ids=[...ids];
 for(const s of d.querySelectorAll('script')){if(s.src){page.scripts.push(s.getAttribute('src'));check(rel,s.getAttribute('src'),'script')}else if(s.type==='application/ld+json'){try{JSON.parse(s.textContent)}catch(e){add('syntax-jsonld',rel,e.message)}}else{try{new vm.Script(s.textContent,{filename:rel})}catch(e){add('syntax-inline-js',rel,e.message)}}}
 for(const s of d.querySelectorAll('style'))try{postcss.parse(s.textContent)}catch(e){add('syntax-inline-css',rel,e.reason)}
 for(const e of d.querySelectorAll('*'))for(const a of e.attributes){if(a.name.startsWith('on'))try{new Function(a.value)}catch(er){add('syntax-handler',rel,er.message)}}
 for(const a of d.querySelectorAll('a[href]')){let u=a.getAttribute('href');page.links.push(u);check(rel,u,'link');if(u==='#')add('empty-link',rel,a.textContent.trim());if(a.querySelector('button,a,input,select'))add('nested-interactive',rel,a.textContent.slice(0,65));}
 for(const e of d.querySelectorAll('img[src],link[rel=stylesheet],meta[property="og:image"]')){const u=e.getAttribute('src')||e.getAttribute('href')||e.getAttribute('content');page.assets.push(u);check(rel,u,'asset');if(e.tagName==='IMG'&&!e.hasAttribute('alt'))add('missing-alt',rel,u);}
 for(const g of d.querySelectorAll('.gal')){if(g.dataset.vide==='1')continue;for(const v of (g.dataset.vues||'face,profil').split(',')){check(rel,g.dataset.base+'-'+v+'.jpg','gallery');}}
 if(!/^google/.test(rel)&&!d.querySelector('meta[http-equiv=refresh]')){if(page.h1.length!==1)add('h1-count',rel,page.h1.length);if(!page.description)add('missing-description',rel,'');if(!page.canonical)add('missing-canonical',rel,'');if(!d.querySelector('meta[name=viewport]'))add('missing-viewport',rel,'');}
 pages.push(page);dom.window.close();}
for(const [type,list] of [['vehicle',data.window.LK_VEHICULES],['weapon',data.window.LK_ARMES],['map',points]]){const ids=new Set();for(const x of list){if(ids.has(x.id))add('duplicate-data-id',type,x.id);ids.add(x.id);if(type==='map'){if(x.p&&!pointIds.has(x.p))add('orphan-map-parent',x.id,x.p);if(!Number.isFinite(x.x)||!Number.isFinite(x.y)||x.x<0||x.x>5200||x.y<0||x.y>6000)add('bad-coordinate',x.id,[x.x,x.y]);for(const k of ['img','img2'])if(x[k])check('carte.html',x[k],'map-image');}}}
for(const x of data.window.LK_INDEX)check('index.html',x.u,'search');
for(const f of files.filter(f=>f.endsWith('.xml'))){const rel=path.relative(root,f);for(const m of fs.readFileSync(f,'utf8').matchAll(/<loc>([^<]+)<\/loc>/g))check(rel,m[1],'sitemap');}
const reachable=new Set(['index.html']),queue=['index.html'];while(queue.length){let f=queue.pop(),p=pages.find(x=>x.file===f);if(!p)continue;for(const l of p.links){let u;try{u=new URL(l,'https://www.leonidakit.com/'+f)}catch{continue}if(u.origin!=='https://www.leonidakit.com')continue;const rel=u.pathname.slice(1)||'index.html';if(!reachable.has(rel)){reachable.add(rel);queue.push(rel);}}}
for(const p of pages)if(!reachable.has(p.file))add('orphan-page',p.file,p.title);
const hashes={};for(const f of inventory)(hashes[f.sha256]??=[]).push(f.file);const duplicates=Object.values(hashes).filter(a=>a.length>1);
const summary={files:files.length,pages:pages.length,bytes:inventory.reduce((n,f)=>n+f.bytes,0),sourceVehicles:fs.existsSync(path.join(root,'v-corrige.json'))?JSON.parse(fs.readFileSync(path.join(root,'v-corrige.json'))).length:data.window.LK_VEHICULES.length,vehicles:data.window.LK_VEHICULES.length,weapons:data.window.LK_ARMES.length,mapPoints:points.length,search:data.window.LK_INDEX.length,issues:issues.reduce((m,x)=>(m[x.kind]=(m[x.kind]||0)+1,m),{}),duplicateGroups:duplicates.length};
for(const [n,x]of Object.entries({summary,issues,pages,inventory,duplicates,points,data:data.window}))fs.writeFileSync(path.join(out,n+'.json'),JSON.stringify(x,null,2));console.log(JSON.stringify(summary,null,2));
