'use strict';
// Scénarios reproductibles issus de l’audit : vrais moteurs, DOM et liens livrés.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'../..'),{load}=require('./runtime-helper.cjs');
const E=require(root+'/calculateurs-engine.js'),B=require(root+'/calculateurs-scenario.js'),L=require(root+'/leo-link.js'),core=require(root+'/leo-core.js').create(require(root+'/leo-index.json'));
const ctx={window:{}};vm.createContext(ctx);for(const f of ['vehicules-data.js','armes-data.js','acquisitions-data.js','calculateurs-catalogue.js','calculateurs-activites.js','calculateurs-data.js'])vm.runInContext(fs.readFileSync(root+'/'+f,'utf8'),ctx);
const initial=B.initial('audit',JSON.parse(JSON.stringify(ctx.window.LKCalcData.presets))),blank=()=>B.blank(initial),catalogue=JSON.parse(JSON.stringify(ctx.window.LKCalcData.catalogue()));
const state=p=>JSON.parse(p.w.localStorage.getItem('lk-calculator-v1'));
const fire=(p,node,type='input')=>node.dispatchEvent(new p.w.Event(type,{bubbles:true,cancelable:true}));
const edit=(p,id,value,type='input')=>{const n=p.d.getElementById(id);assert.ok(n,id);n.value=value===null?'':String(value);fire(p,n,type);};
const click=(p,id)=>{const n=p.d.getElementById(id);assert.ok(n,id);fire(p,n,'click');};
async function page(tool,s=blank(),extra={}){return load(root,'calculateurs.html?tool='+tool,{storage:{'lk-calculator-v1':JSON.stringify(s)},...extra});}
const clean=p=>{assert.deepEqual(p.errors,[]);assert.doesNotMatch(p.d.querySelector('.calc-panel:not([hidden])')?.textContent||'',/NaN|Infinity|undefined|\bnull\b/);p.close();};

test('Audit : achat autonome, réserve protégée et aucun objectif/revenu requis',()=>{
 const s=blank();s.goal.capital=200000;s.goal.reserve=30000;s.assets[0].price=100000;
 const purchase=B.evaluate('purchase',s),r=B.decision(s);assert.equal(purchase.valid,true);assert.equal(purchase.remaining,70000);assert.equal(r.remaining,70000);assert.equal(r.cashRemaining,100000);assert.equal(r.recoveryHours,null);assert.equal(r.buyNowCash,null);assert.equal(B.roi(s).paybackHours,undefined);
});
test('Audit : comparaison acheter/attendre avec mêmes budget, revenu et horizon',()=>{const r=E.worth({capital:200000,reserve:30000,price:100000,hourly:50000,hours:2});assert.equal(r.recoveryHours,2);assert.equal(r.buyNowCash,200000);assert.equal(r.waitCash,300000);assert.equal(r.capitalPercent,50);});
test('Audit : un achat hors budget et une réserve excessive restent explicites',()=>{const r=E.worth({capital:50000,reserve:10000,price:100000,hourly:null,hours:null});assert.equal(r.valid,true);assert.equal(r.shortfall,60000);assert.equal(r.buyNowCash,null);assert.equal(E.worth({capital:50000,reserve:60000,price:0}).valid,false);});
test('Audit : prix absent et prix gratuit ne se confondent jamais',()=>{assert.equal(E.worth({capital:0,price:null}).valid,false);const r=E.worth({capital:0,price:0});assert.equal(r.valid,true);assert.equal(r.remaining,0);});
test('Audit : objectif minimal, montant manquant puis durée sans calendrier',()=>{const s=blank();s.goal.capital=200000;s.goal.target=500000;assert.equal(B.goal(s).missing,300000);assert.equal(B.goal(s).valid,false);s.goal.hourly=100000;assert.equal(B.goal(s).totalMinutes,180);assert.equal(B.goal(s).days,null);s.goal.capital=500000;s.goal.hourly=null;assert.equal(B.goal(s).totalMinutes,0);});
test('Audit : ordre sans revenu connu réalisable seulement avec le capital disponible',()=>{const s=blank();s.goal.capital=200000;s.assets[0].price=100000;s.order.keys=[s.assets[0].key];assert.equal(B.evaluate('order',s).totalHours,0);s.goal.capital=50000;assert.equal(B.evaluate('order',s).valid,false);});
test('Audit : revenu net nul ou négatif ne rembourse pas un investissement',()=>{const s=blank();s.goal.capital=200000;s.assets[0].price=100000;s.roi.mode='continuous';s.roi.hours=4;s.roi.revenueHourly=100;s.roi.costHourly=100;assert.equal(B.roi(s).paybackHours,null);s.roi.costHourly=200;assert.equal(B.roi(s).paybackHours,null);assert.ok(B.roi(s).netProfit<0);});
test('Audit : repartir de zéro enlève les anciens chiffres sans perdre les favoris',()=>{const s=B.copy(initial);s.catalogue.favorites=['brian-keys'];const b=B.blank(s);assert.deepEqual(b.catalogue.favorites,['brian-keys']);for(const k of ['capital','target','hourly','dailyMinutes'])assert.equal(b.goal[k],null);assert.equal(b.roi.hours,null);assert.equal(b.session.daysPerWeek,null);assert.ok(b.activities.every(a=>a.reward===null&&a.duration===null));assert.equal(b.order.keys.length,0);assert.doesNotThrow(()=>B.validate(b,initial));});
for(const type of ['consumable','ammo','housing'])test('Audit : le filtre '+type+' survit à un export/import',()=>{const s=blank();s.catalogue.type=type;assert.equal(B.validate(JSON.parse(JSON.stringify(s)),initial).catalogue.type,type);});

test('Audit DOM : Mes achats répond seul en mode Simple',async()=>{const p=await page('purchase');edit(p,'f-purchase-capital',200000);edit(p,'f-purchase-price',100000);assert.match(p.d.getElementById('purchase-results').textContent,/100\s000/);assert.equal(state(p).goal.target,null);assert.equal(state(p).goal.hourly,null);clean(p);});
test('Audit DOM : Ça vaut le coup répond sans activité et peut comparer un autre achat',async()=>{const p=await page('roi');edit(p,'roi-capital',200000);edit(p,'roi-reserve',30000);edit(p,'f-roi-purchase',100000);let text=p.d.getElementById('roi-results').textContent;assert.match(text,/70\s000/);assert.match(text,/ne se rembourse pas|aucun|pas.*rentab/i);assert.doesNotMatch(text,/remboursé en|remboursé après/);fire(p,p.d.querySelector('[data-b-roi-alternative]'),'click');edit(p,'roi-alternative-price',50000);text=p.d.getElementById('roi-results').textContent;assert.match(text,/120\s000/);clean(p);});
test('Audit DOM : objectif depuis zéro produit une durée sans jours inventés',async()=>{const p=await page('goal');edit(p,'f-goal-capital',200000);edit(p,'f-goal-target',500000);edit(p,'f-goal-hourly',100000);const text=p.d.getElementById('goal-results').textContent;assert.match(text,/3 h/);assert.match(text,/nombre de jours/);assert.doesNotMatch(text,/0 jour|null/);clean(p);});
test('Audit DOM : session autonome, éditeurs et budget dans son propre panneau',async()=>{const p=await page('session');for(const k of ['capital','reserve']){const n=p.d.querySelector('#panel-session [data-field="goal.'+k+'"]');assert.ok(n);n.value=k==='capital'?'0':'0';fire(p,n);}edit(p,'f-session-minutes',45);for(const [k,v] of [['reward',50000],['duration',15]]){const n=p.d.querySelector('#panel-session [data-field="activities.0.'+k+'"]');assert.ok(n);assert.equal(n.closest('.b-expert'),null);n.value=v;fire(p,n);}assert.match(p.d.getElementById('session-results').textContent,/150\s000/);assert.equal(state(p).goal.target,null);clean(p);});
test('Audit DOM : activités accessibles en Simple sans objectif',async()=>{const p=await page('activities');edit(p,'activity-capital',0);edit(p,'f-inverse-minutes',45);edit(p,'f-activities-0-reward',50000);edit(p,'f-activities-0-duration',15);assert.equal(p.d.getElementById('f-activities-0-reward').closest('.b-expert'),null);assert.match(p.d.getElementById('inverse-results').textContent,/150\s000/);clean(p);});
test('Audit DOM : budget autonome avec catégories éditables',async()=>{const p=await page('budget');edit(p,'budget-capital',200000);edit(p,'budget-reserve',30000);edit(p,'f-budget-allocations-0',100000);assert.match(p.d.getElementById('budget-results').textContent,/70\s000/);clean(p);});
test('Audit DOM : ordre autonome, achat personnel payé immédiatement',async()=>{const p=await page('order');edit(p,'order-capital',200000);fire(p,p.d.querySelector('[data-b-add-free]'),'click');edit(p,'order-price-0',100000);assert.equal(B.evaluate('order',state(p)).totalHours,0);assert.match(p.d.getElementById('order-results').textContent,/100\s000/);clean(p);});
test('Audit DOM : ancre directe, remise à zéro annulable, carnet conservé',async()=>{const p=await load(root,'calculateurs.html#roi');assert.equal(p.d.getElementById('panel-roi').hidden,false);click(p,'calc-zero');assert.equal(state(p).goal.capital,null);click(p,'calc-undo');assert.equal(state(p).goal.capital,200000);clean(p);});
test('Audit DOM : sauvegarde illisible préservée avant le premier nouveau calcul',async()=>{const raw='{données illisibles';const p=await page('goal',blank(),{storage:{'lk-calculator-v1':raw}});assert.ok(p.d.getElementById('calc-recover-original'));edit(p,'f-goal-capital',123);const backups=Object.keys(p.w.localStorage).filter(k=>k.startsWith('lk-calculator-v1-backup-'));assert.ok(backups.length);assert.equal(p.w.localStorage.getItem(backups[0]),raw);clean(p);});
test('Audit DOM : sauvegarde future ne peut pas être écrasée',async()=>{const raw=JSON.stringify({...initial,version:99});const p=await page('goal',blank(),{storage:{'lk-calculator-v1':raw}});edit(p,'f-goal-capital',123);assert.equal(p.w.localStorage.getItem('lk-calculator-v1'),raw);clean(p);});
for(const q of ['achète la région Leonida Keys','je veux acheter Leonida Keys'])test('Audit Léo : '+q,()=>{const a=core.answer(q);assert.equal(a.kind,'answer');assert.equal(a.request,undefined);assert.match(a.text,/destination/);assert.ok(a.links.some(l=>l.url==='/lieux/leonida-keys.html'));assert.ok(a.links.every(l=>!l.url.includes('calculateurs')));});
test('Audit Léo : trouver une région et simuler une demeure sont deux actions distinctes',()=>{const a=core.answer('où trouver Vice City');assert.equal(a.forCalculation,false);assert.equal(a.results[0].url,'/lieux/vice-city.html');const b=core.answer('je veux acheter la maison de Brian');assert.equal(b.request.items[0],'brian-keys');assert.match(b.note,/non confirmé/);const s=L.apply(b.request,initial,initial,B,catalogue,'new',[]);assert.equal(B.asset(s,s.purchase.key).price,null);assert.equal(catalogue.find(x=>x.type==='place').purchaseCandidate,false);});
test('Audit : carnet revient avec comparaison personnelle et calcul inchangé',()=>{const s=blank();s.goal.capital=200000;s.assets[0].price=100000;s.roi.hours=2;s.goal.hourly=50000;s.assets.push({...s.assets[0],key:'alternative',price:50000});s.roi.compareKey='alternative';const data=new Map(),storage={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)},N=require(root+'/calculateurs-notebooks.js');const n=N.create(storage,x=>B.validate(x,initial),()=>{}),saved=n.save('roi',s,'Achat plaisir','budget');assert.equal(saved.persisted,true);const restored=N.create(storage,x=>B.validate(x,initial),()=>{}).open(saved.entry.id);assert.equal(restored.roi.compareKey,'alternative');assert.equal(B.decision(restored).remaining,100000);});
test('Audit recherche : index versionné, carte différée, accents, faute mineure et clavier',async()=>{const p=await load(root,'index.html'),q=p.d.querySelector('.searchwrap input[type="search"]'),box=p.d.querySelector('.searchwrap .suggest');q.focus();const script=p.d.getElementById('lk-lieux-js');assert.ok(script);assert.match(script.src,/search-lieux\.js\?v=/);p.w.eval(fs.readFileSync(root+'/search-lieux.js','utf8'));fire(p,p.d,'lk-lieux');for(const [query,route]of [['Tuto','tuto.html'],['vêhicules','vehicules.html'],['personnalisatons','personnalisations.html'],['Contact','contact.html'],['munitions','armes.html#munitions'],['tatouages','style.html#tatouages'],['consommables','nourriture.html']]){q.value=query;fire(p,q);assert.ok([...box.querySelectorAll('a')].some(a=>a.getAttribute('href').includes(route)),query);}q.dispatchEvent(new p.w.KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));assert.ok(q.getAttribute('aria-activedescendant'));q.dispatchEvent(new p.w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(q.getAttribute('aria-expanded'),'false');assert.deepEqual(p.errors,[]);p.close();});
test('Audit Contact : prépare un texte, ne transmet ni HTML ni données réseau',async()=>{const p=await load(root,'contact.html');const form=p.d.getElementById('contact-draft');p.d.getElementById('contact-details').value='<img src=x onerror=alert(1)> correction';p.d.getElementById('contact-page').value='https://www.leonidakit.com/achats.html';fire(p,form,'submit');assert.match(p.d.getElementById('contact-preview').value,/<img src=x/);assert.match(p.d.getElementById('contact-status').textContent,/Aucun message envoyé/);assert.equal(p.d.querySelector('#contact-preview img'),null);assert.equal(p.d.getElementById('contact-copy').disabled,false);assert.equal(p.requests.length,0);assert.deepEqual(p.errors,[]);p.close();});
test('Audit DOM : Mon plan reconnaît un achat plaisir calculable et recharge l’expert au changement de mode',async()=>{const s=blank();s.goal.capital=200000;s.assets[0].price=100000;const p=await page('plan',s);assert.match(p.d.getElementById('plan-results').textContent,/Choisis ce que tu veux acheter/);p.w.LKCalculator.openTab('roi');assert.equal(p.d.getElementById('expert-roi').textContent,'');fire(p,p.d.querySelector('.calc-mode-switch [data-mode="advanced"]'),'click');assert.match(p.d.getElementById('expert-roi').textContent,/Sensibilité/);clean(p);});
test('Audit DOM : un lien de région ne devient pas un achat sélectionné',async()=>{const p=await load(root,'calculateurs.html?tool=roi&type=place&id=leonida-keys');assert.doesNotMatch(p.d.getElementById('roi-selection').textContent,/Leonida Keys/);assert.match(p.d.getElementById('calc-live').textContent,/lieu|destination|achat/i);clean(p);});
test('Audit : les six catégories vides restent accessibles sans promesse d’achat ni indexation externe',()=>{const ctx={window:{}};vm.runInNewContext(fs.readFileSync(root+'/search-index.js','utf8'),ctx);const sitemap=fs.readFileSync(root+'/sitemap.xml','utf8');for(const slug of ['logements']){const html=fs.readFileSync(root+'/'+slug+'.html','utf8');assert.match(html,/name="robots" content="noindex, follow"/);assert.doesNotMatch(html,/pourra acheter|pourront porter et acheter/);assert.ok(ctx.window.LK_INDEX.some(e=>e.u==='/'+slug+'.html'));assert.ok(!sitemap.includes('/'+slug+'.html'));}
 // Pages doublons devenues des renvois : hors index interne, hors sitemap, avec redirection vers la section qui les a absorbées.
 for(const [slug,target] of [['vetements','/style.html#tenues'],['accessoires','/style.html#accessoires'],['tatouages','/style.html#tatouages'],['munitions','/armes.html#munitions']]){const html=fs.readFileSync(root+'/'+slug+'.html','utf8');assert.match(html,/name="robots" content="noindex, follow"/);assert.ok(html.includes('http-equiv="refresh" content="0; url='+target+'"'));assert.ok(!ctx.window.LK_INDEX.some(e=>e.u==='/'+slug+'.html'));assert.ok(!sitemap.includes('/'+slug+'.html'));}
 // Consommables est une vraie page : indexée, avec ses volets, sans promesse d’achat.
 const food=fs.readFileSync(root+'/nourriture.html','utf8');assert.doesNotMatch(food,/name="robots" content="noindex/);assert.ok(sitemap.includes('/nourriture.html'));for(const id of ['a-quoi-ca-sert','ce-qui-est-montre','ou-en-trouver','et-le-calculateur'])assert.ok(food.includes('id="'+id+'"'),id);assert.doesNotMatch(food,/pourra acheter|pourront porter et acheter/);
 const style=fs.readFileSync(root+'/style.html','utf8');for(const id of ['tenues','accessoires','tatouages','coiffures'])assert.ok(style.includes('id="'+id+'"'),id);
 const nav=fs.readFileSync(root+'/index.html','utf8').match(/<nav id="nav"[\s\S]*?<\/nav>/)[0];assert.ok(nav.includes('>Armurerie<')&&nav.includes('>Consommables<')&&nav.includes('>Vêtements et style<'));for(const bad of ['6 catégories','>Bateaux<','>Garages documentés<','>Tout ce qui s’achète<'])assert.ok(!nav.includes(bad),bad);});
test('Audit Léo : base de connaissances GTA VI, avec statut, sans écraser les fiches ni les calculs',()=>{const kb=[['gta 6 sur pc ?',/PC/],['sur quelles consoles ?',/PlayStation 5/],['ça coûte combien le jeu ?',/79,99/],['qui sont jason et lucia ?',/Lucia Caminos/],['combien de régions ?',/Six régions/],['il y aura gta online ?',/rien annoncé/],['on peut grossir ?',/poids/],['c est quoi leonida',/Floride/],['budget du jeu',/estimations/]];for(const [q,re] of kb){const a=core.answer(q);assert.equal(a.kind,'answer',q);assert.match(a.text,re,q);assert.ok(a.status,q);}
 assert.equal(core.answer('combien coûte un Kamacho').request?.tool,'purchase');assert.equal(core.answer('J’ai 200 euros').kind,'clarify');assert.equal(core.answer('où trouver Vice City').forCalculation,false);assert.equal(core.answer('lucia').kind,'results');assert.match(core.answer('achète la région Leonida Keys').text,/destination/);});
test('Lot B : Quel achat choisir ? et Mon business plan répondent seuls, se sauvegardent et se rechargent',async()=>{const p=await page('compare');
 edit(p,'compare-capital',200000);edit(p,'compare-hourly',100000);fire(p,p.d.querySelector('[data-b-compare-free]'),'click');fire(p,p.d.querySelector('[data-b-compare-free]'),'click');edit(p,'compare-price-0',150000);edit(p,'compare-price-1',50000);
 let text=p.d.getElementById('compare-results').textContent;assert.match(text,/Pour toi, c’est/);assert.match(text,/rapport envie/);
 const crit=p.d.getElementById('f-compare-criterion');crit.value='cheapest';fire(p,crit,'change');assert.match(p.d.getElementById('compare-results').textContent,/le moins cher/);
 const saved=JSON.parse(p.w.localStorage.getItem('lk-calculator-v1'));assert.equal(saved.compare.keys.length,2);assert.equal(saved.compare.criterion,'cheapest');
 p.d.getElementById('tab-plan').click();fire(p,p.d.querySelector('[data-b-plan-free]'),'click');edit(p,'plan-price',1000000);edit(p,'plan-capital',200000);edit(p,'plan-hourly',100000);edit(p,'plan-daily',60);
 text=p.d.getElementById('plan-results').textContent;assert.match(text,/il te manque 800\s000/);assert.match(text,/8 h/);assert.match(text,/8 jours/);
 const report=p.d.getElementById('plan-report').textContent;assert.match(report,/étape par étape/);assert.match(report,/Achète Mon but/);assert.doesNotMatch(report,/Ton calendrier/);
 const details=p.d.querySelector('[data-b-plan-details]');details.checked=true;fire(p,details,'change');assert.match(p.d.getElementById('plan-report').textContent,/Ton calendrier/);assert.match(p.d.getElementById('plan-report').textContent,/Et si/);
 const kind=p.d.getElementById('f-plan-kind');kind.value='amount';fire(p,kind,'change');edit(p,'plan-target',1000000);assert.match(p.d.getElementById('plan-results').textContent,/8 h/);
 assert.equal(JSON.parse(p.w.localStorage.getItem('lk-calculator-v1')).plan.kind,'amount');clean(p);});
