'use strict';
/* v7.66 : contrôle du calculateur. Scénarios fictifs A–J du prompt « Intelligence avancée » (références écrites à la main,
   jamais recalculées par la fonction testée) et deux corrections : un achat déclaré « plaisir » ou « confort » n’est jamais
   jugé sur une rentabilité dans « Ça vaut le coup ? » ; un rôle « je ne sais pas encore » n’est plus présenté comme un plaisir.
   Aucun chiffre ici n’est un prix ou un gain de GTA VI. */
const test=require('node:test'),assert=require('node:assert/strict');
const H=require('./check-ultime-helper.cjs'),B=require('../../calculateurs-scenario.js');
const {D,catalogue,sourceActivities,presets}=H.siteData(),DV=H.dataVersion(D,catalogue,sourceActivities),initial=B.initial(DV,presets);
const base=()=>{const s=H.baseState(B,initial,catalogue);s.dataVersion=DV;return s;};
const ev=(t,s)=>B.evaluate(t,s,sourceActivities,{catalogue});
const act=(i,o)=>Object.assign(B.copy(initial.activities[i]),{cost:0,prep:0,cooldown:0,share:100,investment:0,players:1,requiresPurchaseIds:[]},o);
const asset=(key,price,o={})=>({...B.copy(B.assetTemplate),key,name:key,price,...o});
test('A : 200 000 → 1 000 000 à 100 000 par heure = 480 min, 16 parties de 30 min',()=>{const s=base();s.model='continuous';Object.assign(s.goal,{capital:200000,target:1000000,hourly:100000,reserve:0,dailyMinutes:30,plannedSpend:null,upkeepPerSession:null,meaning:'held'});const r=ev('goal',s);assert.equal(Math.round(r.totalMinutes),480);assert.equal(r.sessions,16);});
test('B et B bis : une action trop longue est infaisable ; deux B (60 000) battent une A au meilleur taux',()=>{for(const [dur,rew] of [[40,100000],[20,50000]]){const s=base();s.activities[0]=act(0,{name:'A',reward:rew,duration:dur});s.activities[1]=act(1,{name:'B',reward:30000,duration:15});s.session={...s.session,minutes:30,enabled:[s.activities[0].id,s.activities[1].id],maxRepeat:10};s.goal.reserve=0;const r=ev('session',s);assert.equal(r.profit,60000);assert.equal(r.runs,2);assert.ok(r.timeline.filter(x=>x.type==='activity').every(x=>x.name==='B'));}});
test('C : un bien acheté n’est pas de l’argent disponible (il manque 700 000)',()=>{const s=base();s.model='continuous';Object.assign(s.goal,{capital:500000,target:1000000,hourly:100000,reserve:0,dailyMinutes:60,plannedSpend:200000,upkeepPerSession:null,meaning:'available'});const r=ev('goal',s);assert.equal(r.missing,700000);assert.equal(Math.round(r.totalMinutes),420);});
test('D et E : 120 000 pour 30 000 de plus par heure → remboursé en 4 h ; −60 000 à 2 h, +60 000 à 6 h ; gain nul → jamais',()=>{const s=base();s.assets=[asset('U',120000)];s.purchase={key:'U'};s.order.keys=['U'];s.compare.keys=['U'];s.goal.capital=500000;s.goal.reserve=0;s.goal.hourly=50000;s.roi={...s.roi,key:'U',mode:'continuous',revenueHourly:30000,costHourly:0,hours:2,compareKey:''};
 assert.equal(ev('roi',s).paybackHours,4);assert.match(JSON.stringify(B.investment(s,sourceActivities)),/-60000/);s.roi.hours=6;assert.match(JSON.stringify(B.investment(s,sourceActivities)),/[^-]60000/);s.roi.revenueHourly=0;assert.equal(ev('roi',s).paybackHours,null);});
test('F : 40 000 à avancer avec 30 000 : impossible malgré un bénéfice positif',()=>{const s=base();s.activities[0]=act(0,{name:'F',reward:100000,cost:40000,duration:10});s.inverse={minutes:60,selected:s.activities[0].id};s.goal.capital=30000;s.goal.reserve=0;assert.equal(ev('activities',s).valid,false);});
test('J : A (30 000) avant B (70 000), 10 000 gardés de 90 000 : bloqué, il manque 20 000',()=>{const s=base();s.goal.capital=90000;s.goal.reserve=10000;s.goal.hourly=0;s.assets=[asset('A',30000),asset('B',70000,{incomeMode:'personal',boostHourly:50000,requires:['A']})];s.purchase={key:'A'};s.roi={...s.roi,key:'A',compareKey:''};s.order={keys:['B','A'],objective:'all'};s.compare.keys=['A','B'];const r=ev('order',s);assert.equal(r.valid,false);assert.match(r.reason,/20\D?000/);});
test('L : mission de 10 min, 15 min d’attente, partie de 60 min : 3 missions (fin à 60 comprise), 60 000',()=>{const s=base();s.activities[0]=act(0,{name:'L',reward:20000,duration:10,cooldown:15});s.session={...s.session,minutes:60,enabled:[s.activities[0].id],maxRepeat:10};s.goal.capital=0;s.goal.reserve=0;const r=ev('session',s);assert.equal(r.profit,60000);assert.equal(r.runs,3);assert.deepEqual(r.timeline.filter(x=>x.type==='activity').map(x=>x.start),[0,25,50]);});
test('Achat plaisir ou confort : « Ça vaut le coup ? » ne calcule aucune rentabilité, même resté sur un mode à gain',()=>{const s=base();s.assets=[asset('Yacht',300000,{role:'pleasure'})];s.purchase={key:'Yacht'};s.order.keys=['Yacht'];s.compare.keys=['Yacht'];s.roi={...s.roi,key:'Yacht',mode:'continuous',revenueHourly:20000,costHourly:0,compareKey:''};
 assert.equal(B.roiMode(s),'estimate');const a=B.analysis('roi',s,sourceActivities,{catalogue});assert.ok(!a.explain.used.includes('gain-en-plus'));s.assets[0].role='comfort';assert.equal(B.roiMode(s),'estimate');s.assets[0].role='income';assert.equal(B.roiMode(s),'continuous');});
test('Rôle « je ne sais pas encore » sans gain : jamais présenté comme un achat plaisir',()=>{const s=base();s.assets=[asset('X',40000)];s.purchase={key:'X'};s.order.keys=['X'];s.compare.keys=['X'];s.roi={...s.roi,key:'X',compareKey:''};const a=B.analysis('purchase',s,sourceActivities,{catalogue});assert.notEqual(a.role,'pleasure');assert.doesNotMatch(JSON.stringify(a.explain),/Achat plaisir/);});
/* v7.67 : scénarios I et M du prompt, exprimés avec les cases existantes (aucune case ajoutée) ; K et N passent par la barre IA
   (intervalle → variantes calculées par le moteur ; taux de réussite → tentatives ratées simulées). */
test('I : préparation de 30 min sans revenu, puis 40 000 par heure au lieu de 20 000 : à 4 h, égalité (80 000 de chaque côté)',()=>{const s=base();s.assets=[asset('I',60000)];s.purchase={key:'I'};s.order.keys=['I'];s.compare.keys=['I'];
 s.activities[0]=act(0,{name:'Nouvelle',reward:20000,duration:30,prep:30,prepOnce:true,requiresPurchaseIds:['I']});s.goal.capital=500000;s.goal.reserve=0;s.goal.hourly=20000;s.roi={...s.roi,key:'I',mode:'new',activityIds:[s.activities[0].id],hours:4,compareKey:''};
 const r=ev('roi',s);assert.equal(r.runs,7);assert.equal(r.netProfit,80000);assert.equal(r.opportunityCost,80000);assert.equal(r.marginalNetProfit,0);});
test('M : équipement commun de 40 000 payé une fois, deux activités (30 000 et 25 000, 5 000 chacune) : solde final 55 000',()=>{const s=base(),p=s.plan;
 p.goal={...p.goal,kind:'amount',target:55000,meaning:'held'};p.source='missions';p.situation={...p.situation,capital:50000,reserve:0,hourly:0,dailyMinutes:120,daysPerWeek:7,upkeepPerSession:0,players:1};
 p.prerequisites=[{...B.copy(B.planPrereqTemplate),id:'p-eq',name:'Équipement',price:40000,minutes:null,boostHourly:0,usagePerSession:null}];
 p.missions=[{...B.copy(B.planMissionTemplate),id:'m-1',name:'A1',reward:30000,cost:5000,duration:10,once:true,requires:['p-eq']},{...B.copy(B.planMissionTemplate),id:'m-2',name:'A2',reward:25000,cost:5000,duration:10,once:true,requires:['p-eq']}];
 const r=ev('plan',B.validate(s,initial));assert.equal(r.valid,true);assert.equal(r.sessions[0].cashBefore,10000);assert.equal(r.sessions[0].cashAfter,55000);assert.deepEqual(r.sessions[0].purchases,['Équipement']);});
