'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'../..'),E=require(root+'/calculateurs-engine.js'),B=require(root+'/calculateurs-scenario.js'),N=require(root+'/calculateurs-notebooks.js');
const context={window:{}};vm.createContext(context);vm.runInContext(fs.readFileSync(root+'/calculateurs-data.js','utf8'),context);const presets=JSON.parse(JSON.stringify(context.window.LKCalcData.presets));
const legacy={version:2,dataVersion:'test-data',mode:'quick',model:'continuous',name:'Essai',tab:'goal',goal:{capital:200000,target:1000000,hourly:100000,reserve:0,dailyMinutes:60,players:1,selected:'scenario-a'},activities:presets.map(a=>({...a,owned:false})),session:{minutes:60,maxRepeat:100,enabled:presets.map(a=>a.id)},inverse:{minutes:60,selected:'scenario-a'},purchase:{itemId:'',price:100000,extras:0,boostHourly:0},catalogue:{query:'',type:'all',status:'all',sort:'name',maxPrice:null,favorites:[],compareIds:[],favoritesOnly:false},roi:{purchase:500000,upgrades:0,fees:0,revenueHourly:90000,costHourly:15000,hours:10},budget:{capital:200000,reserve:30000,allocations:[50000,60000,20000,10000,0]},order:{capital:200000,hourly:50000,items:[{name:'A',price:150000,boostHourly:0}]}};
const initial=B.defaults(legacy),fresh=()=>B.copy(initial),a=(extra={})=>({id:'a',name:'Activité pédagogique',reward:50000,cost:0,duration:15,prep:0,cooldown:0,share:100,investment:0,players:1,...extra});
const session=activities=>E.sessionPlan({capital:100000,reserve:0,minutes:45,activities});
test('Lot B: 45 minutes terminent trois cycles de 50 000, sans reward fractionnaire',()=>{const r=session([a()]);assert.equal(r.runs,3);assert.equal(r.profit,150000);assert.equal(r.totalMinutes,45);assert.equal(r.unusedMinutes,0);assert.deepEqual(r.timeline.map(x=>[x.start,x.end]),[[0,15],[15,30],[30,45]]);});
test('Lot B: une activité de 60 min est exclue du programme de 45 min',()=>{const r=session([a({duration:60})]);assert.equal(r.runs,0);assert.equal(r.profit,0);assert.equal(r.unusedMinutes,45);});
test('Lot B: préparation unique et préparation répétée utilisent les vraies durées',()=>{const r=session([a({duration:20,prep:10,prepOnce:true,reward:40000})]);assert.equal(r.runs,1);assert.equal(r.totalMinutes,30);assert.equal(r.unusedMinutes,15);for(const once of [true,false]){const input={capital:0,reserve:0,minutes:60,activity:a({duration:20,prep:10,prepOnce:once})};const inv=E.inverse(input),plan=E.sessionPlan({...input,activities:[input.activity]});assert.equal(inv.runs,plan.runs);assert.equal(inv.totalMinutes,plan.totalMinutes);}const once=E.inverse({capital:0,minutes:70,activity:a({duration:20,prep:10,prepOnce:true})});assert.equal(once.runs,3);});
test('Lot B: cooldown entre deux cycles, aucun après le dernier',()=>{const r=session([a({duration:15,cooldown:15})]);assert.equal(r.runs,2);assert.equal(r.profit,100000);assert.equal(r.totalMinutes,45);});
test('Lot B: objectif déjà atteint, progression et calendrier sans division par zéro',()=>{const r=E.goalContinuous({capital:1000000,target:1000000,reserve:0,hourly:0,dailyMinutes:60});assert.equal(r.missing,0);assert.equal(r.totalMinutes,0);const p=E.sessionProjection({capital:1000000,target:1000000,reserve:0,session:session([a()]),daysPerWeek:5});assert.equal(p.missingBefore,0);assert.ok(Number.isFinite(p.progressPercent));});
test('Lot B: projection partage objectif et réserve et évite de repayer une mise',()=>{const p=E.sessionProjection({capital:100000,target:1000000,reserve:0,session:{valid:true,profit:100000,investment:50000,finalCapital:200000},daysPerWeek:5});assert.equal(p.missingBefore,900000);assert.equal(p.missingAfter,800000);assert.equal(p.sessionsLeft,6);assert.equal(p.calendarDays,9);const zero=E.sessionProjection({capital:0,target:100000,session:{valid:true,profit:0,investment:0,finalCapital:0}});assert.equal(zero.sessionsLeft,null);});
test('Lot B: amortissement continu de 500 000 / 75 000 = 6 h 40',()=>{const r=E.roi({purchase:500000,revenueHourly:90000,costHourly:15000,hours:10});assert.equal(r.paybackHours*60,400);assert.equal(r.netProfit,250000);});
test('Lot B: amortissement discret au premier versement couvrant la mise',()=>{const r=E.investmentActivities({purchase:100000,hours:1,mode:'new',activities:[a({reward:60000,cost:10000})]});assert.equal(r.paybackHours,.5);assert.equal(r.paybackCycles,2);assert.equal(r.operatingProfit,200000);assert.equal(r.netProfit,100000);assert.equal(r.grossProfit,240000);assert.equal(r.costs,40000);});
test('Lot B: amélioration compare les recettes avant et après sans inventer un gain partiel',()=>{const r=E.investmentActivities({purchase:10000,hours:1,mode:'improve',gainPercent:20,durationReduction:0,activities:[a()]});assert.equal(r.beforeNet,200000);assert.equal(r.afterNet,240000);assert.equal(r.operatingProfit,40000);assert.equal(r.paybackHours,.25);const none=E.investmentActivities({purchase:10000,hours:1,mode:'improve',gainPercent:0,durationReduction:0,activities:[a()]});assert.equal(none.paybackHours,null);assert.equal(none.netProfit,-10000);});
test('Lot B: aucun lien économique ne se déduit de la catégorie ou du prix',()=>{const s=fresh();s.roi.activityIds=[];assert.equal(B.roi(s).valid,true);assert.equal(B.roi(s).paybackHours,undefined);assert.equal(B.roi(s).netProfit,undefined);s.roi.activityIds=['scenario-a'];s.assets[0].price=null;assert.equal(B.roi(s).valid,false);});
test('Lot B: ordre impossible identifie étape et manque, sans utiliser revenu futur',()=>{const r=E.order({capital:100000,hourly:0,items:[{name:'Premier achat',price:150000,boostHourly:75000}]});assert.equal(r.valid,false);assert.equal(r.blockedIndex,0);assert.equal(r.shortfall,50000);assert.equal(r.steps.length,0);});
test('Lot B: ordre protège la réserve et crédite le revenu après paiement',()=>{const r=E.order({capital:100000,reserve:30000,hourly:10000,items:[{name:'A',price:100000,boostHourly:20000},{name:'B',price:60000,boostHourly:0}]});assert.equal(r.totalHours,5);assert.deepEqual(r.steps.map(x=>x.timeHours),[3,5]);assert.equal(r.finalCapital,30000);});
test('Lot B: même achat et prix pour achat, ROI, ordre et budget, sans mutation du catalogue',()=>{const s=fresh(),item={id:'known',name:'Catalogue pédagogique',price:50000},ref=B.copy(item),a=B.addAsset(s,item);s.purchase.key=a.key;s.roi.key=a.key;s.order.keys=[a.key];a.price=60000;assert.equal(B.purchase(s).price,60000);assert.equal(B.orderInput(s).items[0].price,60000);assert.equal(B.budgetInput(s).allocations[0],60000);assert.deepEqual(item,ref);a.owned=true;assert.equal(B.orderInput(s).items[0].price,0);assert.equal(B.budgetInput(s).allocations[0],0);});
test('Lot B: disponibilité impose joueurs et achats possédés',()=>{const s=fresh();s.activities[0].requiresPurchaseIds=['known'];s.session.enabled=['scenario-a'];assert.equal(B.session(s).valid,false);B.addAsset(s,{id:'known',name:'Achat',price:null}).owned=true;assert.equal(B.session(s).valid,true);s.activities[0].players=4;assert.equal(B.session(s).valid,false);});
test('Lot B: changement de mode conserve mêmes paramètres et résultat central',()=>{const s=fresh(),before=B.evaluate('goal',s);s.views.goal='advanced';s.mode='advanced';assert.deepEqual(B.evaluate('goal',s),before);s.goal.reserve=30000;s.views.goal='quick';assert.equal(B.evaluate('goal',s).missing,830000);});
test('Lot B: sensibilité recalcule les durées au lieu de multiplier le résultat',()=>{const s=fresh(),sens=B.sensitivity('goal',s);assert.equal(sens.rows[0].result.totalMinutes,600);assert.equal(sens.rows[1].result.totalMinutes,480);assert.equal(sens.rows[2].result.totalMinutes,400);});
test('Lot B: migration v2 et v1 conserve inconnus, activités et anciens investissements',()=>{for(const version of [1,2]){const raw=B.copy(legacy);raw.version=version;raw.purchase.price=null;const s=B.validate(raw,initial);assert.equal(s.version,4);assert.equal(B.purchase(s).price,null);assert.equal(s.roi.mode,'continuous');assert.equal(B.roi(s).paybackHours*60,400);assert.equal(s.order.keys.length,1);}const s=fresh();s.surprise={attack:true};assert.equal(B.validate(s,initial).surprise,undefined);assert.throws(()=>B.validate({...s,goal:{...s.goal,capital:'200000'}},initial));});
test('Lot B: références supprimées restent explicites et aucune valeur inconnue ne devient zéro',()=>{const s=fresh(),a=B.addAsset(s,{id:'removed',name:'Achat supprimé',price:null});s.order.keys=[a.key];assert.equal(B.evaluate('order',s).valid,false);assert.match(B.referenceWarnings(s,[])[0],/n’existe plus/);assert.equal(B.validate(s,initial).assets[1].price,null);});
function storage(initial={}){const map=new Map(Object.entries(initial));return{getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),map};}
test('Lot B: carnets isolés, mise à jour stable, copie, référence, suppression annulable',()=>{const store=storage(),n=N.create(store,s=>B.validate(s,initial),()=>{}),s=fresh();const a=n.save('goal',s,'But','Résumé').entry;assert.equal(n.save('goal',s,'But édité','Résumé 2').entry.id,a.id);assert.equal(n.list('goal').length,1);assert.equal(n.list('session').length,0);n.setReference('session',a.id);assert.equal(n.reference('session'),undefined);n.setReference('goal',a.id);assert.equal(n.reference('goal').id,a.id);n.duplicate(a.id);assert.equal(n.list('goal').length,2);n.remove(a.id);assert.equal(n.list('goal').length,1);n.undo();assert.equal(n.list('goal').length,2);n.rename(a.id,'Nouveau nom');assert.equal(n.get(a.id).name,'Nouveau nom');});
test('Lot B: plan complet et partiel restaurent des paramètres éditables après rechargement',()=>{const store=storage(),n=N.create(store,s=>B.validate(s,initial),()=>{}),s=fresh();s.goal.target=450000;s.session.minutes=45;const e=n.save('plan',s,'Plan partiel','Résumé').entry;const again=N.create(store,s=>B.validate(s,initial),()=>{}),opened=again.open(e.id);assert.equal(opened.goal.target,450000);assert.equal(opened.session.minutes,45);opened.goal.target=900000;assert.equal(again.get(e.id).config.goal.target,450000);});
test('Lot B: anciennes sauvegardes migrées sans effacer leur stockage d’origine',()=>{const raw=JSON.stringify([{name:'Historique',config:legacy}]),store=storage({'lk-calculator-saved-v1':raw}),n=N.create(store,s=>B.validate(s,initial),()=>{});assert.equal(n.list('goal').length,1);assert.equal(n.list('plan').length,1);assert.equal(store.getItem('lk-calculator-saved-v1'),raw);});
test('Lot B: entrée corrompue et quota plein ne bloquent ni les autres entrées ni le moteur',()=>{const notices=[],store=storage(),n=N.create(store,s=>B.validate(s,initial),m=>notices.push(m));n.save('goal',fresh(),'Valide','OK');const raw=JSON.parse(store.getItem(N.KEY));raw.entries.push({id:'bad',tool:'goal',config:{version:77}});store.setItem(N.KEY,JSON.stringify(raw));const again=N.create(store,s=>B.validate(s,initial),m=>notices.push(m));assert.equal(again.list('goal').length,1);assert.ok(notices.some(x=>x.includes('illisible')));const blocked=N.create({getItem:()=>null,setItem:()=>{throw Error('quota');}},s=>B.validate(s,initial),m=>notices.push(m));assert.equal(blocked.save('goal',fresh(),'Calcul','OK').persisted,false);assert.equal(B.evaluate('goal',fresh()).valid,true);});
test('Lot B: champ de prix manquant à l’import reste inconnu et une activité incomplète ne bloque pas les autres',()=>{const s=fresh();delete s.assets[0].price;assert.equal(B.validate(s,initial).assets[0].price,null);s.activities[1].reward=null;s.session.enabled=['scenario-a','scenario-b'];assert.equal(B.session(s).valid,true);assert.ok(B.session(s).runs>0);});
test('Lot B: références internes corrompues et filtres inconnus sont refusés avant le rendu',()=>{const missing=fresh();missing.purchase.key='absent';assert.throws(()=>B.validate(missing,initial),/Référence interne/);const filter=fresh();filter.catalogue.type='invented';assert.throws(()=>B.validate(filter,initial),/Filtre/);});
test('Lot B: frais initiaux sont partagés entre achat, ROI, panier et budget',()=>{const s=fresh(),a=s.assets[0];a.fees=10000;s.order.keys=[a.key];s.roi.mode='continuous';s.roi.revenueHourly=75000;assert.equal(B.purchase(s).extras,10000);assert.equal(B.orderInput(s).items[0].price,110000);assert.equal(B.budgetInput(s).allocations[0],110000);assert.equal(B.roi(s).investment,110000);});

test('Relecture B: calendrier incomplet conserve le gain et la progression calculables',()=>{
 const input={capital:100000,target:1000000,reserve:0,session:{valid:true,profit:100000,investment:0,finalCapital:200000}};
 const days=E.sessionProjection({...input,daysPerWeek:null});
 assert.equal(days.valid,true);assert.equal(days.missingAfter,800000);assert.equal(days.sessionsLeft,8);assert.equal(days.calendarDays,null);assert.match(days.calendarReason,/jours/);
 const repeat=E.sessionProjection({...input,repeatProfit:null});
 assert.equal(repeat.valid,true);assert.equal(repeat.missingAfter,800000);assert.equal(repeat.sessionsLeft,null);assert.match(repeat.calendarReason,/session/);
 const reached=E.sessionProjection({...input,target:100000,daysPerWeek:null,repeatProfit:null});
 assert.equal(reached.valid,true);assert.equal(reached.sessionsLeft,0);assert.equal(reached.calendarDays,0);
});
test('Relecture B: les variables d’amélioration ne bloquent pas les autres modèles de rentabilité',()=>{
 for(const mode of ['new','estimate'])assert.equal(E.investmentActivities({purchase:100000,hours:1,mode,gainPercent:null,durationReduction:null,activities:[a()]}).valid,true);
 assert.equal(E.investmentActivities({purchase:100000,hours:1,mode:'improve',gainPercent:null,activities:[a()]}).valid,false);
});
test('Relecture B: dupliquer une sauvegarde ne change pas le calcul actif',()=>{
 const n=N.create(storage(),s=>B.validate(s,initial),()=>{}),s=fresh(),original=n.save('goal',s,'Original','OK').entry;
 const duplicate=n.duplicate(original.id).entry;
 assert.equal(n.active('goal').id,original.id);assert.equal(duplicate.config.name,duplicate.name);
 s.goal.target=2300000;n.save('goal',s,'Original modifié','OK');
 assert.equal(n.get(original.id).config.goal.target,2300000);assert.equal(n.get(duplicate.id).config.goal.target,initial.goal.target);
});
test('Relecture B: annuler une suppression rétablit les liens actifs et de comparaison',()=>{
 const n=N.create(storage(),s=>B.validate(s,initial),()=>{}),entry=n.save('goal',fresh(),'Original','OK').entry;
 n.setReference('goal',entry.id);n.remove(entry.id);n.undo();
 assert.equal(n.active('goal')?.id,entry.id);assert.equal(n.reference('goal')?.id,entry.id);
 n.remove(entry.id);const other=n.save('goal',fresh(),'Autre','OK').entry;n.setReference('goal',other.id);n.undo();
 assert.equal(n.active('goal').id,other.id);assert.equal(n.reference('goal').id,other.id);
});
test('Relecture B: un carnet de version future reste intact et ne prétend pas avoir enregistré',()=>{
 const raw=JSON.stringify({version:99,entries:[{future:'conservé'}]}),store=storage({[N.KEY]:raw}),notices=[];
 const n=N.create(store,s=>B.validate(s,initial),m=>notices.push(m));
 assert.equal(n.save('goal',fresh(),'Calcul','OK').persisted,false);assert.equal(n.lastWriteOk(),false);
 assert.equal(store.getItem(N.KEY),raw);assert.ok(notices.some(x=>/version/i.test(x)));
});
test('Relecture B: la sensibilité varie l’activité effectivement retenue, y compris une source du catalogue',()=>{
 const s=fresh();s.model='cycles';s.goal.selected='catalogue-a';const source=[a({id:'catalogue-a',name:'Source témoin'})];
 const sens=B.sensitivity('goal',s,source);assert.match(sens.label,/Source témoin/);
 assert.ok(sens.rows[0].result.totalMinutes>sens.rows[2].result.totalMinutes);assert.equal(source[0].reward,50000);
 s.session.enabled=['scenario-a','scenario-b'];s.activities[0].players=4;s.goal.players=1;
 assert.match(B.sensitivity('session',s).label,new RegExp(s.activities[1].name));
});
