'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');
const {load}=require('./runtime-helper.cjs');
const root=process.env.SITE_ROOT||path.resolve(__dirname,'../..');
const clone=v=>JSON.parse(JSON.stringify(v));
const empty=()=>({version:1,found:{},favorites:{},notes:{}});
// Synthetic data is scoped to tests. No test collectible is published in the site dataset.
const item=(id,extra={})=>({id,slug:id,name:'Test '+id,description:'Fixture de test locale',category:'test-category',status:'confirmed',trackable:true,published:true,coordinates:null,image:null,...extra});
const fixture=()=>({schemaVersion:1,updatedAt:'2026-09-18',sources:[],categories:[{id:'test-category',slug:'test-category',name:'Catégorie de test',status:'confirmed',published:true}],items:[item('test-alpha'),item('test-beta',{status:'established'}),item('test-rumor',{status:'unconfirmed',trackable:false}),item('test-hidden',{published:false}),item('test-placeholder',{status:'placeholder',trackable:false}),item('test-mapped',{coordinates:{x:1200,y:2300,system:'leonidakit-v1',verified:true,sourceUrl:'https://example.com/test-proof'}})]});
function core(setup){const dom=new JSDOM('<!doctype html><html lang="fr"><body></body></html>',{url:'https://www.leonidakit.com/collectibles.html',runScripts:'outside-only'});const w=dom.window;w.LK_COLLECTIBLES=fixture();setup?.(w);w.eval(fs.readFileSync(path.join(root,'collectibles-core.js'),'utf8'));return {dom,w,api:w.LKCollectibles,close:()=>w.close()};}
const coreTest=fn=>()=>{const a=core();try{fn(a);}finally{a.close();}};

test('Collectibles: found, favorites and notes persist and export as a versioned backup',coreTest(a=>{const k=a.api;assert.equal(k.setFound('test-alpha',true),true);assert.equal(k.setFavorite('test-alpha',true),true);assert.equal(k.setNote('test-alpha','Note personnelle <svg onload="alert(1)">'),true);const stored=JSON.parse(a.w.localStorage.getItem(k.key));assert.deepEqual(stored.found,{'test-alpha':true});assert.deepEqual(stored.favorites,{'test-alpha':true});assert.match(stored.notes['test-alpha'],/<svg/);assert.equal(k.exportData().version,1);assert.ok(k.exportData().exportedAt);const second=core(w=>w.localStorage.setItem(k.key,JSON.stringify(stored)));try{assert.deepEqual(clone(second.api.getState()),stored);}finally{second.close();}}));
test('Collectibles: only published confirmed or established items count as trackable',coreTest(a=>{const k=a.api;assert.equal(k.setFound('test-beta',true),true);for(const id of ['test-rumor','test-placeholder','test-hidden','missing','constructor','__proto__'])assert.equal(k.setFound(id,true),false,id);assert.equal(k.setFavorite('test-rumor',true),true);assert.equal(k.setFavorite('test-hidden',true),false);assert.equal(k.setNote('test-placeholder','invalid'),false);}));
test('Collectibles: snapshots cannot mutate saved progress and unsubscribe stops notifications',coreTest(a=>{let calls=0;const unsub=a.api.subscribe(()=>calls++);a.api.setFound('test-alpha',true);assert.equal(calls,1);const snapshot=a.api.getState();snapshot.found['test-alpha']=false;assert.equal(a.api.getState().found['test-alpha'],true);unsub();a.api.setFound('test-alpha',false);assert.equal(calls,1);assert.equal(Object.hasOwn(a.api.getState().found,'test-alpha'),false);}));
test('Collectibles: invalid imports are atomic and cannot pollute prototypes',coreTest(a=>{const k=a.api;k.setFound('test-alpha',true);k.setNote('test-alpha','Avant import');const before=a.w.localStorage.getItem(k.key);for(const value of ['{bad json',JSON.stringify({...empty(),version:99}),JSON.stringify({...empty(),found:{'test-beta':'yes'}}),JSON.stringify({...empty(),notes:{'test-beta':'x'.repeat(2001)}}),'{"version":1,"found":{"__proto__":true},"favorites":{},"notes":{}}',JSON.stringify({...empty(),found:{constructor:true}}),JSON.stringify({...empty(),notes:[]})]){assert.throws(()=>k.importData(value,'replace'));assert.equal(a.w.localStorage.getItem(k.key),before);assert.deepEqual(clone(k.getState()),JSON.parse(before));}assert.throws(()=>k.importData(empty(),'unknown'));assert.equal({}.polluted,undefined);}));
test('Collectibles: merge keeps existing progress, replacement replaces it, empty notes clear',coreTest(a=>{const k=a.api;k.setFound('test-alpha',true);k.setNote('test-alpha','Note conservée');k.importData({...empty(),found:{'test-beta':true},favorites:{'test-beta':true}},'merge');assert.deepEqual(clone(k.getState().found),{'test-alpha':true,'test-beta':true});k.importData({...empty(),found:{'test-beta':true}},'replace');assert.deepEqual(clone(k.getState()),{...empty(),found:{'test-beta':true}});k.setNote('test-beta','Brouillon');k.setNote('test-beta','   ');assert.equal(Object.hasOwn(k.getState().notes,'test-beta'),false);assert.equal(k.setNote('test-beta','x'.repeat(2001)),false);}));
test('Collectibles: storage denial preserves in-memory progress and reports it',()=>{const a=core(w=>{w.Storage.prototype.getItem=()=>{throw new Error('Storage denied')};w.Storage.prototype.setItem=()=>{throw new Error('Storage denied')};});try{assert.equal(a.api.getStorageStatus().status,'unavailable');assert.equal(a.api.setFound('test-alpha',true),true);assert.equal(a.api.getState().found['test-alpha'],true);assert.match(a.api.getStorageStatus().message,/export/i);assert.equal(a.api.exportData().found['test-alpha'],true);}finally{a.close();}});
test('Collectibles: corrupted storage does not crash and valid writes recover',()=>{const a=core(w=>w.localStorage.setItem('lk_collectibles_v1','null'));try{assert.equal(a.api.getStorageStatus().status,'unavailable');assert.deepEqual(clone(a.api.getState()),empty());a.api.setFound('test-alpha',true);assert.equal(a.api.getStorageStatus().status,'available');}finally{a.close();}});
test('Collectibles: map links require verified, in-bounds project coordinates and a source',coreTest(a=>{const k=a.api;assert.equal(k.mapUrl(k.getItem('test-mapped')),'/carte.html#collectible=test-mapped');assert.equal(k.mapUrl(k.getItem('test-alpha')),null);const good=k.getItem('test-mapped');assert.equal(k.mapUrl({...good,status:'unconfirmed'}),'/carte.html#collectible=test-mapped');for(const patch of [{coordinates:null},{coordinates:{...good.coordinates,verified:false}},{coordinates:{...good.coordinates,x:Infinity}},{coordinates:{...good.coordinates,x:-1}},{coordinates:{...good.coordinates,x:5201}},{coordinates:{...good.coordinates,y:6001}},{coordinates:{...good.coordinates,system:'unknown'}},{coordinates:{...good.coordinates,sourceUrl:null}},{coordinates:{...good.coordinates,sourceUrl:'javascript:alert(1)'}},{status:'placeholder'},{published:false}])assert.equal(k.mapUrl({...good,...patch}),null,JSON.stringify(patch));assert.equal(k.itemUrl(k.getItem('test-alpha')),'/collectibles/test-alpha.html');assert.equal(k.itemUrl({slug:'../../index'}),null);}));
test('Collectibles: storage events synchronize progress and reject malformed incoming state',coreTest(a=>{const value={...empty(),found:{'test-alpha':true}};a.w.dispatchEvent(new a.w.StorageEvent('storage',{key:a.api.key,newValue:JSON.stringify(value)}));assert.equal(a.api.getState().found['test-alpha'],true);a.w.dispatchEvent(new a.w.StorageEvent('storage',{key:a.api.key,newValue:'null'}));assert.equal(a.api.getState().found['test-alpha'],true);a.w.dispatchEvent(new a.w.StorageEvent('storage',{key:a.api.key,newValue:null}));assert.deepEqual(clone(a.api.getState()),empty());}));
test('Collectibles: reset clears collectibles only',coreTest(a=>{a.w.localStorage.setItem('lk_own_vehicules','{"test-car":1}');a.api.setFound('test-alpha',true);a.api.setFavorite('test-alpha',true);a.api.setNote('test-alpha','Note');a.api.resetProgress();assert.deepEqual(clone(a.api.getState()),empty());assert.equal(a.w.localStorage.getItem('lk_own_vehicules'),'{"test-car":1}');}));

test('Collectibles generator: publication gates, static HTML, null media, indexing and idempotence',()=>{
  const os=require('node:os'),vm=require('node:vm');
  const {generate,validateCatalog}=require('../gen-collectibles.cjs');
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lk-collectibles-qa-'));
  try{
    fs.mkdirSync(path.join(dir,'outils'));
    for(const file of ['collectibles.html','search-index.js','sitemap.xml','sitemap-fiches.xml'])fs.copyFileSync(path.join(root,file),path.join(dir,file));
    const source={label:'Source de test uniquement',url:'https://example.org/test-source',kind:'official',checkedAt:'2026-09-18'};
    const base={status:'confirmed',published:true,trackable:true,verifiedAt:'2026-09-18',sources:[source]};
    const data={schemaVersion:1,updatedAt:'2026-09-18',sources:[source],categories:[{id:'test-category',name:'Catégorie QA'}],items:[
      {...base,id:'test-rich',slug:'test-rich',name:'Fiche complète QA',category:'test-category',description:Array(130).fill('documenté').join(' '),place:'Emplacement de test, seulement dans ce dossier temporaire.',seo:{indexable:true},coordinates:{x:100,y:200,system:'leonidakit-v1',verified:true,sourceUrl:'https://example.org/test-source'}},
      {...base,id:'test-sparse',slug:'test-sparse',name:'Fiche sparse <svg data-audit="xss">',image:null,coordinates:null,seo:{indexable:true}},
      {...base,id:'test-rumor',slug:'test-rumor',name:'Hypothèse de test',status:'unconfirmed',trackable:false},
      {id:'test-draft',slug:'test-draft',name:'Brouillon local',status:'placeholder'},
      {...base,id:'test-hidden',slug:'test-hidden',name:'Publication inactive',published:false,trackable:false}
    ]};
    assert.throws(()=>validateCatalog({...data,items:[{...base,id:'test-bad',slug:'test-bad',name:'Invalid',sources:[]}]}));
    assert.throws(()=>validateCatalog({...data,items:[{...data.items[2],trackable:true}]}));
    assert.throws(()=>validateCatalog({...data,items:[{...data.items[0],coordinates:{...data.items[0].coordinates,x:-1}}]}));
    fs.writeFileSync(path.join(dir,'outils/collectibles.json'),JSON.stringify(data));
    const first=generate({root:dir});assert.equal(first.published,3);assert.equal(first.indexable,1);
    const baseline={window:{}};vm.runInNewContext(fs.readFileSync(path.join(dir,'collectibles-data.js'),'utf8'),baseline);
    assert.equal(baseline.window.LK_COLLECTIBLES.items.length,3);assert.ok(!baseline.window.LK_COLLECTIBLES.items.some(i=>i.status==='placeholder'||!i.published));
    const sparse=baseline.window.LK_COLLECTIBLES.items.find(i=>i.id==='test-sparse');assert.equal(sparse.image,null);assert.equal(sparse.coordinates,null);assert.deepEqual(clone(sparse.gallery),[]);
    const dom=new JSDOM(fs.readFileSync(path.join(dir,'collectibles/test-sparse.html'),'utf8'));try{
      const d=dom.window.document;assert.match(d.querySelector('h1').textContent,/<svg/);assert.equal(d.querySelector('[data-audit]'),null);assert.match(d.querySelector('meta[name="robots"]').content,/noindex/);assert.equal(d.querySelector('a[href*="#collectible="]'),null);assert.ok(d.querySelector('a[href="https://example.org/test-source"]'));assert.equal(d.querySelectorAll('img[src="null"], img[src="undefined"]').length,0);assert.ok(d.querySelector('link[rel="canonical"]').href.endsWith('/collectibles/test-sparse.html'));for(const s of d.querySelectorAll('script[type="application/ld+json"]'))assert.doesNotThrow(()=>JSON.parse(s.textContent));
    }finally{dom.window.close();}
    const hub=new JSDOM(fs.readFileSync(path.join(dir,'collectibles.html'),'utf8'));try{assert.equal(hub.window.document.querySelectorAll('.col-card[data-col-item]').length,3);}finally{hub.window.close();}
    const sitemap=fs.readFileSync(path.join(dir,'sitemap-collectibles.xml'),'utf8');assert.match(sitemap,/test-rich\.html/);assert.doesNotMatch(sitemap,/test-sparse|test-rumor|test-draft|test-hidden/);
    assert.equal(fs.existsSync(path.join(dir,'collectibles/test-draft.html')),false);
    assert.equal(generate({root:dir,check:true}).current,true);
    fs.writeFileSync(path.join(dir,'collectibles/handwritten.html'),'<h1>Do not delete</h1>');
    data.items=data.items.filter(i=>i.id!=='test-sparse');fs.writeFileSync(path.join(dir,'outils/collectibles.json'),JSON.stringify(data));
    assert.deepEqual(generate({root:dir}).removed,['collectibles/test-sparse.html']);assert.ok(fs.existsSync(path.join(dir,'collectibles/handwritten.html')));
  }finally{fs.rmSync(dir,{recursive:true,force:true});}
});

const withPage=(file,fn,opts={})=>async()=>{const a=await load(root,file,opts);try{await fn(a);assert.deepEqual(a.errors.filter(x=>!x.includes('Not implemented: navigation')),[]);}finally{a.close();}};
const fixtureOptions=(extra={})=>({...extra,beforeScript(w,s){if((s.getAttribute('src')||'').split('?')[0].endsWith('collectibles-core.js'))w.LK_COLLECTIBLES=fixture();extra.beforeScript?.(w,s);}});
test('Collectibles map: exact deep link opens verified marker and shares found and favorite states',withPage('carte.html#collectible=test-mapped',a=>{const marker=a.d.querySelector('.mk[data-id="collectible-test-mapped"]');assert.ok(marker);assert.match(a.d.getElementById('map-panel-in').textContent,/Test test-mapped/);assert.equal(a.d.getElementById('mp-collectible-found').getAttribute('aria-pressed'),'false');a.d.getElementById('mp-collectible-found').click();assert.equal(a.w.LKCollectibles.getState().found['test-mapped'],true);assert.ok(marker.classList.contains('is-found'));assert.equal(a.d.getElementById('mp-collectible-found').getAttribute('aria-pressed'),'true');a.d.getElementById('mp-collectible-favorite').click();assert.equal(a.w.LKCollectibles.getState().favorites['test-mapped'],true);a.w.LKCollectibles.importData(empty(),'replace');assert.equal(marker.classList.contains('is-found'),false);assert.equal(a.d.getElementById('mp-collectible-found').getAttribute('aria-pressed'),'false');assert.equal(Object.hasOwn(a.w.LK_MAP.getFound(),'collectible-test-mapped'),false);assert.deepEqual(clone(a.w.LK_MAP.cleanFound({'collectible-test-mapped':true,'vice-city':true})),{'vice-city':true});assert.equal(a.w.location.hash,'#collectible=test-mapped');},fixtureOptions()));
test('Collectibles map: missing or invalid coordinates never create a pin',withPage('carte.html#collectible=test-alpha',a=>{assert.equal(a.d.querySelector('.mk[data-id="collectible-test-alpha"]'),null);assert.equal(a.d.querySelector('.mk[data-id="collectible-test-bad-location"]'),null);assert.match(a.d.getElementById('map-panel-in').textContent,/Aucun emplacement précis et vérifié/);assert.equal(a.d.getElementById('mp-collectible-found'),null);assert.ok(a.d.querySelector('#map-panel-in a[href="/collectibles/test-alpha.html"]'));},fixtureOptions({beforeScript(w,s){if((s.getAttribute('src')||'').split('?')[0].endsWith('collectibles-core.js'))w.LK_COLLECTIBLES.items.push(item('test-bad-location',{coordinates:{x:-1,y:2,system:'leonidakit-v1',verified:true,sourceUrl:'https://example.org/source'}}));}})));
test('Collectibles progression: only documented trackable items are counted and updates stay synchronized',withPage('progression.html',a=>{const row=a.d.getElementById('progress-collectibles');assert.equal(row.querySelector('strong').textContent,'1 / 3 documentés');assert.equal(row.querySelector('progress').hidden,false);a.w.LKCollectibles.setFound('test-beta',true);assert.equal(row.querySelector('strong').textContent,'2 / 3 documentés');a.w.LKCollectibles.resetProgress();assert.equal(row.querySelector('progress').value,0);},fixtureOptions({storage:{lk_collectibles_v1:JSON.stringify({...empty(),found:{'test-alpha':true,'test-rumor':true,unknown:true}})}})));
test('Collectibles map: sourced unconfirmed locations stay visibly unconfirmed and cannot be found',withPage('carte.html#collectible=test-rumor',a=>{assert.ok(a.d.querySelector('.mk[data-id="collectible-test-rumor"]'));assert.match(a.d.getElementById('map-panel-in').textContent,/non confirmée/i);assert.equal(a.d.getElementById('mp-collectible-found'),null);assert.ok(a.d.getElementById('mp-collectible-favorite'));assert.equal(a.w.LKCollectibles.setFound('test-rumor',true),false);},fixtureOptions({beforeScript(w,s){if((s.getAttribute('src')||'').split('?')[0].endsWith('collectibles-core.js'))w.LK_COLLECTIBLES.items.find(i=>i.id==='test-rumor').coordinates={x:500,y:600,system:'leonidakit-v1',verified:true,sourceUrl:'https://example.org/source'};}})));
const submitSearch=(a,value)=>{const input=a.d.getElementById('col-search');input.value=value;input.dispatchEvent(new a.w.Event('input',{bubbles:true}));a.d.getElementById('col-filters').dispatchEvent(new a.w.Event('submit',{bubbles:true,cancelable:true}));};
const select=(a,id,value)=>{const el=a.d.getElementById(id);el.value=value;el.dispatchEvent(new a.w.Event('change',{bubbles:true}));};
const visibleCards=a=>[...a.d.querySelectorAll('#collectibles-results .col-card')];
test('Collectibles hub: shipped records never publish drafts, examples or incomplete evidence',withPage('collectibles.html',a=>{for(const i of a.w.LK_COLLECTIBLES.items){assert.notEqual(i.status,'placeholder');assert.notEqual(i.published,false);assert.doesNotMatch(i.id,/^(?:test-|qa-|exemple-ne-pas-publier)/);assert.ok(i.sources.length);assert.ok(i.verifiedAt);}assert.doesNotMatch(a.d.getElementById('col-percent').textContent,/NaN|Infinity/);assert.equal(a.d.querySelector('img[src="null"],img[src="undefined"]'),null);}));
test('Collectibles hub: filters combine, tracking filters exclude rumors and URL state restores',withPage('collectibles.html?progress=missing&view=list',a=>{assert.equal(visibleCards(a).length,3);assert.ok(a.d.getElementById('collectibles-results').classList.contains('is-list'));select(a,'col-status','confirmed');assert.equal(visibleCards(a).length,2);submitSearch(a,'mapped');assert.equal(visibleCards(a).length,1);assert.equal(visibleCards(a)[0].dataset.colItem,'test-mapped');assert.equal(new URLSearchParams(a.w.location.search).get('q'),'mapped');a.d.getElementById('col-reset').click();assert.equal(visibleCards(a).length,4);a.d.querySelector('[data-col-found="test-alpha"]').click();assert.equal(a.d.getElementById('col-percent').textContent,'33 %');select(a,'col-progress','found');assert.equal(visibleCards(a).length,1);assert.equal(visibleCards(a)[0].dataset.colItem,'test-alpha');},fixtureOptions()));
test('Collectibles hub: imported hostile notes are literal and typing retains the focused editor',withPage('collectibles.html',a=>{const hostile='</textarea><svg data-audit="injected" onload="alert(1)">';a.w.LKCollectibles.importData({...empty(),notes:{'test-alpha':hostile}},'merge');const textarea=a.d.querySelector('[data-col-note="test-alpha"]');assert.equal(textarea.value,hostile);assert.equal(a.d.querySelector('[data-audit]'),null);textarea.focus();textarea.value='Nouvelle note';textarea.dispatchEvent(new a.w.Event('input',{bubbles:true}));assert.equal(a.d.activeElement,textarea);assert.equal(a.w.LKCollectibles.getState().notes['test-alpha'],'Nouvelle note');},fixtureOptions()));
test('Collectibles hub: malformed file import is atomic and gives an accessible error',withPage('collectibles.html',async a=>{a.w.LKCollectibles.setFound('test-alpha',true);const before=a.w.localStorage.getItem(a.w.LKCollectibles.key),input=a.d.getElementById('col-import-file');Object.defineProperty(input,'files',{value:[{size:20,text:async()=>'{bad json'}],configurable:true});input.dispatchEvent(new a.w.Event('change',{bubbles:true}));await new Promise(r=>setImmediate(r));assert.equal(a.w.localStorage.getItem(a.w.LKCollectibles.key),before);assert.match(a.d.querySelector('[data-col-feedback]').textContent,/Import refusé/);Object.defineProperty(input,'files',{value:[{size:100,text:async()=>JSON.stringify({...empty(),favorites:{'test-beta':true}})}],configurable:true});input.dispatchEvent(new a.w.Event('change',{bubbles:true}));await new Promise(r=>setImmediate(r));assert.equal(a.w.LKCollectibles.getState().found['test-alpha'],true);assert.equal(a.w.LKCollectibles.getState().favorites['test-beta'],true);assert.match(a.d.querySelector('[data-col-feedback]').textContent,/Import fusionné/);},fixtureOptions()));
test('Collectibles hub: pagination bounds visible cards and clamps stale page URLs',withPage('collectibles.html?page=999999',a=>{assert.equal(visibleCards(a).length,1);assert.match(a.d.getElementById('col-pagination').textContent,/Page 3 \/ 3/);a.d.querySelector('[data-col-page="2"]').click();assert.equal(visibleCards(a).length,12);assert.equal(new URLSearchParams(a.w.location.search).get('page'),'2');submitSearch(a,'test-01');assert.equal(visibleCards(a).length,1);assert.equal(a.d.getElementById('col-pagination').hidden,true);},fixtureOptions({beforeScript(w,s){if((s.getAttribute('src')||'').split('?')[0].endsWith('collectibles-core.js'))w.LK_COLLECTIBLES.items=Array.from({length:25},(_,i)=>item('test-'+String(i).padStart(2,'0')));}})));
