'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM}=require('jsdom');
const {load}=require('./runtime-helper.cjs');
const root=process.env.SITE_ROOT||path.resolve(__dirname,'../..');
const plain=x=>JSON.parse(JSON.stringify(x));
const progress=()=>({version:1,found:{},favorites:{},notes:{}});
const tools=()=>({version:1,savedViews:[],plan:[]});
const saved=(id='test-view',query='category=documents')=>({id,name:'Recherche QA',query,createdAt:'2026-09-18T12:00:00.000Z'});
const data=()=>({schemaVersion:1,updatedAt:'2026-09-18',sources:[],categories:[{id:'documents',name:'Documents QA'}],items:[{id:'test-alpha',slug:'test-alpha',name:'Alpha QA',published:true,trackable:true,status:'confirmed',category:'documents',region:'Vice City',summary:'Fixture locale de test',coordinates:null,image:null},{id:'test-beta',slug:'test-beta',name:'Beta QA',published:true,trackable:true,status:'established',category:'documents',region:'Leonida Keys',summary:'Fixture locale de test',coordinates:null,image:null}]});
function boot(setup){const dom=new JSDOM('<!doctype html><html lang="fr"><body></body></html>',{url:'https://www.leonidakit.com/collectibles.html',runScripts:'outside-only'});const w=dom.window;w.LK_COLLECTIBLES=data();setup?.(w);w.eval(fs.readFileSync(path.join(root,'collectibles-core.js'),'utf8'));return {w,core:w.LKCollectibles,close:()=>w.close()};}
const run=fn=>()=>{const a=boot();try{return fn(a);}finally{a.close();}};
const toolsKey='lk_collectibles_tools_v1';

test('Collectibles tools: views and ordered plan persist separately without mutating progress',run(a=>{a.core.setFound('test-alpha',true);const original=a.w.localStorage.getItem(a.core.key);const next={...tools(),savedViews:[saved()],plan:['test-beta','test-alpha']};a.core.setToolsState(next);assert.deepEqual(plain(a.core.getToolsState()),next);assert.equal(a.w.localStorage.getItem(a.core.key),original);assert.deepEqual(JSON.parse(a.w.localStorage.getItem(toolsKey)),next);const snapshot=a.core.getToolsState();snapshot.plan.push('test-new');assert.deepEqual(plain(a.core.getToolsState().plan),['test-beta','test-alpha']);const second=boot(w=>{w.localStorage.setItem(toolsKey,JSON.stringify(next));w.localStorage.setItem(a.core.key,original)});try{assert.deepEqual(plain(second.core.getToolsState()),next);assert.equal(second.core.getState().found['test-alpha'],true);}finally{second.close();}}));
test('Collectibles tools: old backups remain compatible and merge preserves saved tools',run(a=>{const state={...tools(),savedViews:[saved()],plan:['test-alpha']};a.core.setToolsState(state);a.core.importData({...progress(),found:{'test-beta':true}},'merge');assert.equal(a.core.getState().found['test-beta'],true);assert.deepEqual(plain(a.core.getToolsState()),state);const backup=a.core.exportData();assert.equal(backup.version,1);assert.deepEqual(plain(backup.tools),state);}));
test('Collectibles tools: malformed optional tools reject the whole backup before mutation',run(a=>{a.core.setFound('test-alpha',true);a.core.setToolsState({...tools(),plan:['test-alpha']});const beforeProgress=a.w.localStorage.getItem(a.core.key),beforeTools=a.w.localStorage.getItem(toolsKey);for(const bad of [null,[],{...tools(),version:2},{...tools(),plan:'test-beta'},{...tools(),plan:[{id:'test-beta'}]},{...tools(),plan:['__proto__']},{...tools(),savedViews:[{...saved(),query:{category:'documents'}}]},{...tools(),savedViews:[{...saved(),name:'x'.repeat(10000)}]}]){assert.throws(()=>a.core.importData({...progress(),found:{'test-beta':true},tools:bad},'replace'));assert.equal(a.w.localStorage.getItem(a.core.key),beforeProgress);assert.equal(a.w.localStorage.getItem(toolsKey),beforeTools);assert.equal(a.core.getState().found['test-alpha'],true);assert.deepEqual(plain(a.core.getToolsState().plan),['test-alpha']);}}));
test('Collectibles tools: second storage write failure rolls back both backup areas and in-memory state',run(a=>{a.core.setFound('test-alpha',true);a.core.setNote('test-alpha','Note avant import');a.core.setToolsState({...tools(),plan:['test-alpha'],savedViews:[saved()]});const beforeProgress=a.w.localStorage.getItem(a.core.key),beforeTools=a.w.localStorage.getItem(toolsKey),beforeState=plain(a.core.getState()),beforeToolsState=plain(a.core.getToolsState());const original=a.w.Storage.prototype.setItem;let denied=false;a.w.Storage.prototype.setItem=function(key,value){if(key===toolsKey&&!denied){denied=true;throw new Error('Simulated quota on second key');}return original.call(this,key,value);};assert.throws(()=>a.core.importData({...progress(),found:{'test-beta':true},tools:{...tools(),plan:['test-beta']}},'replace'));assert.equal(denied,true);assert.equal(a.w.localStorage.getItem(a.core.key),beforeProgress);assert.equal(a.w.localStorage.getItem(toolsKey),beforeTools);assert.deepEqual(plain(a.core.getState()),beforeState);assert.deepEqual(plain(a.core.getToolsState()),beforeToolsState);}));
test('Collectibles tools: unknown future IDs survive backup without fabricated catalogue records',run(a=>{a.core.importData({...progress(),tools:{...tools(),plan:['future-not-documented'],savedViews:[saved('future-view','region=Future')]}},'merge');assert.ok(a.core.getToolsState().plan.includes('future-not-documented'));assert.equal(a.core.getItem('future-not-documented'),undefined);assert.equal(a.core.setFound('future-not-documented',true),false);}));
test('Collectibles tools: storage events synchronize tools independently of progress',run(a=>{a.core.setFound('test-alpha',true);let notified=0;const unsubscribe=a.core.subscribeTools(()=>notified++),next={...tools(),plan:['test-beta']};a.w.dispatchEvent(new a.w.StorageEvent('storage',{key:toolsKey,newValue:JSON.stringify(next)}));assert.deepEqual(plain(a.core.getToolsState()),next);assert.equal(a.core.getState().found['test-alpha'],true);assert.equal(notified,1);unsubscribe();a.w.dispatchEvent(new a.w.StorageEvent('storage',{key:toolsKey,newValue:'null'}));assert.deepEqual(plain(a.core.getToolsState()),next);assert.equal(notified,1);}));
test('Collectibles tools: merged capacities and saved-query validation reject without partial progress writes',run(a=>{a.core.setToolsState({...tools(),savedViews:Array.from({length:12},(_,i)=>saved('view-'+i)),plan:Array.from({length:30},(_,i)=>'item-'+i)});const previous=JSON.stringify(a.core.exportData());for(const addition of [{...tools(),savedViews:[saved('view-extra')]},{...tools(),plan:['item-extra']}]){assert.throws(()=>a.core.importData({...progress(),found:{'test-alpha':true},tools:addition},'merge'));assert.deepEqual(plain(a.core.getState()),progress());assert.equal(a.core.getToolsState().savedViews.length,12);assert.equal(a.core.getToolsState().plan.length,30);}for(const query of ['url=javascript%3Aalert(1)','q=one&q=two','status=placeholder','page=-1','view=unknown'])assert.throws(()=>a.core.setToolsState({...tools(),savedViews:[saved('bad-query',query)]}));assert.ok(previous);assert.equal(a.core.getToolsState().savedViews.length,12);}));
test('Collectibles tools: replacement from legacy backup preserves tools and reset preserves display preferences',run(a=>{a.core.setToolsState({...tools(),plan:['test-alpha']});a.w.localStorage.setItem('lk_collectibles_prefs_v1','{"view":"list","spoilers":true}');a.w.localStorage.setItem('lk_collectibles_motion_v1','off');a.core.importData({...progress(),found:{'test-beta':true}},'replace');assert.deepEqual(plain(a.core.getToolsState().plan),['test-alpha']);a.core.resetProgress();assert.equal(a.w.localStorage.getItem('lk_collectibles_prefs_v1'),'{"view":"list","spoilers":true}');assert.equal(a.w.localStorage.getItem('lk_collectibles_motion_v1'),'off');}));
test('Collectibles tools: public view API restores validated filters and notifies consumers',()=>{const dom=new JSDOM(fs.readFileSync(path.join(root,'collectibles.html'),'utf8'),{url:'https://www.leonidakit.com/collectibles.html',runScripts:'outside-only'});const w=dom.window;try{w.LK_COLLECTIBLES=data();for(const file of ['collectibles-core.js','collectibles.js'])w.eval(fs.readFileSync(path.join(root,file),'utf8'));const view=w.LKCollectiblesView;assert.ok(view);let updates=0;const unsubscribe=view.subscribe(()=>updates++);view.applyFilters('q=alpha&category=documents&view=list');assert.equal(view.getFilteredItems().length,1);assert.equal(view.getFilteredItems()[0].id,'test-alpha');assert.equal(view.getFilters().q,'alpha');assert.ok(updates>0);const snapshot=view.getFilters();snapshot.q='changed externally';assert.equal(view.getFilters().q,'alpha');assert.throws(()=>view.applyFilters('url=javascript%3Aalert(1)'));assert.equal(view.getFilters().q,'alpha');assert.equal(w.document.querySelectorAll('#collectibles-results .col-card').length,1);unsubscribe();}finally{w.close();}});
function bootTools(change){const dom=new JSDOM(fs.readFileSync(path.join(root,'collectibles.html'),'utf8'),{url:'https://www.leonidakit.com/collectibles.html',runScripts:'outside-only'});const w=dom.window;w.LK_COLLECTIBLES=data();w.HTMLElement.prototype.scrollIntoView=function(){};change?.(w);for(const file of ['collectibles-core.js','collectibles.js','collectibles-tools.js'])w.eval(fs.readFileSync(path.join(root,file),'utf8'));return {w,dom,core:w.LKCollectibles,view:w.LKCollectiblesView,tools:w.LKCollectiblesTools,close:()=>w.close()};}
test('Collectibles tools: CSV neutralizes formulas and escapes quotes/newlines while private notes are opt-in',()=>{const a=bootTools(w=>{w.LK_COLLECTIBLES.items[0].name='=HYPERLINK("https://example.org","QA")';});try{for(const cell of ['=SUM(1,2)','+SUM(1,2)','-SUM(1,2)','@SUM(1,2)','  =SUM(1,2)','\tcommand','\n=SUM(1,2)'])assert.ok(a.tools.csvCell(cell).startsWith('"\''),JSON.stringify(cell));assert.equal(a.tools.csvCell('A "citation"\nsecond line'),'"A ""citation""\nsecond line"');a.core.setNote('test-alpha','@SECRET_PRIVATE_NOTE\n"quote"');const list=a.view.getFilteredItems(),basic=a.tools.makeCSV(list),privateCSV=a.tools.makeCSV(list,{notes:true});assert.equal(basic.charCodeAt(0),0xfeff);assert.doesNotMatch(basic,/SECRET_PRIVATE_NOTE|Note personnelle/);assert.match(privateCSV,/Note personnelle/);assert.ok(privateCSV.includes('"\'@SECRET_PRIVATE_NOTE\n""quote"""'));assert.ok(basic.includes('"\'=HYPERLINK(""https:\/\/example.org"",""QA"")"'));assert.ok(basic.endsWith('\r\n'));}finally{a.close();}});
test('Collectibles tools: saved view restores filters, displays names as text and does not copy notes',()=>{const a=bootTools();try{a.view.applyFilters('q=Alpha&category=documents');a.core.setNote('test-alpha','Private note');const id=a.tools.saveView('<svg data-audit="injected">');const savedView=a.core.getToolsState().savedViews[0];assert.equal(savedView.id,id);assert.equal(savedView.query.includes('Alpha'),true);assert.equal(JSON.stringify(savedView).includes('Private note'),false);assert.equal(a.w.document.querySelector('[data-audit]'),null);a.view.applyFilters('q=Beta');a.w.document.querySelector('[data-col-view-recall="'+id+'"]').click();assert.equal(a.view.getFilters().q,'Alpha');assert.equal(a.view.getFilteredItems()[0].id,'test-alpha');assert.throws(()=>a.tools.saveView('Same filters'));}finally{a.close();}});
test('Collectibles tools: plan keeps manual order and unknown locations do not yield a map route',()=>{const a=bootTools();try{assert.equal(a.tools.addToPlan('test-beta'),true);assert.equal(a.tools.addToPlan('test-alpha'),true);assert.equal(a.tools.addToPlan('test-alpha'),false);assert.deepEqual(plain(a.core.getToolsState().plan),['test-beta','test-alpha']);assert.equal(a.tools.movePlan('test-alpha',-1),true);assert.deepEqual(plain(a.core.getToolsState().plan),['test-alpha','test-beta']);assert.equal(a.tools.movePlan('test-alpha',-1),false);assert.equal(a.w.document.querySelector('#col-plan-next a[href*="carte.html"]'),null);assert.match(a.w.document.getElementById('col-plan-next').textContent,/Aucun emplacement vérifié/);assert.match(a.w.document.querySelector('.col-plan-panel').textContent,/ne calcule ni trajet optimal ni temps/);assert.throws(()=>a.tools.addToPlan('future-unpublished'));a.core.importData({...progress(),tools:{...tools(),plan:['future-unpublished']}},'merge');const future=a.w.document.querySelector('[data-col-plan-row="future-unpublished"]');assert.match(future.textContent,/Fiche indisponible/);assert.equal(future.querySelector('a'),null);}finally{a.close();}});
for(const scenario of [
  {name:'merged found count exceeds 20,000',field:'found',count:11000,value:()=>true},
  {name:'merged serialized notes exceed 2 MiB',field:'notes',count:700,value:()=>'x'.repeat(1600)}
])test('Collectibles tools: '+scenario.name+' is refused before storage changes',run(a=>{
  const makeEntries=prefix=>Object.fromEntries(Array.from({length:scenario.count},(_,i)=>[prefix+'-'+String(i).padStart(5,'0'),scenario.value()]));
  a.core.importData({...progress(),[scenario.field]:makeEntries('prior')},'replace');
  const before=a.w.localStorage.getItem(a.core.key),original=a.w.Storage.prototype.setItem;let writes=0;
  a.w.Storage.prototype.setItem=function(key,value){writes++;return original.call(this,key,value);};
  assert.throws(()=>a.core.importData({...progress(),[scenario.field]:makeEntries('incoming')},'merge'));
  assert.equal(writes,0,'candidate must be validated before the first write');
  assert.equal(a.w.localStorage.getItem(a.core.key),before);
  assert.equal(Object.keys(a.core.getState()[scenario.field]).length,scenario.count);
  const reloaded=boot(w=>w.localStorage.setItem(a.core.key,before));
  try{assert.equal(Object.keys(reloaded.core.getState()[scenario.field]).length,scenario.count);assert.equal(reloaded.core.getStorageStatus().status,'available');}finally{reloaded.close();}
}));
test('Collectibles tools: normal edits near the backup size limit preserve stored data and show a warning',()=>{
  const a=bootTools();try{
    const incoming=progress();for(let i=0;i<1030;i++)incoming.notes['prior-'+String(i).padStart(4,'0')]='x'.repeat(2000);
    const size=()=>Buffer.byteLength(JSON.stringify({...incoming,tools:tools(),app:'Leonidakit Collectibles',exportedAt:'2026-09-18T12:00:00.000Z'}),'utf8');
    const target=a.core.maxImportBytes-512;
    for(let i=0;size()<target;i++){const key='padding-'+i;incoming.notes[key]='';const available=target-size();if(available<=0){delete incoming.notes[key];break;}incoming.notes[key]='p'.repeat(Math.min(2000,available));}
    a.core.importData(incoming,'replace');const before=a.w.localStorage.getItem(a.core.key),count=Object.keys(a.core.getState().notes).length;
    const original=a.w.Storage.prototype.setItem;let writes=0;a.w.Storage.prototype.setItem=function(key,value){writes++;return original.call(this,key,value);};
    let result;assert.doesNotThrow(()=>{result=a.core.setNote('test-alpha','n'.repeat(2000));});assert.equal(result,false);assert.equal(writes,0);assert.equal(a.w.localStorage.getItem(a.core.key),before);assert.equal(a.core.getState().notes['test-alpha'],undefined);
    assert.match(a.core.getStorageStatus().message,/2 Mo/);const warning=a.w.document.getElementById('col-storage-warning');assert.equal(warning.hidden,false);assert.match(warning.textContent,/2 Mo/);
    assert.throws(()=>a.core.setToolsState({...tools(),savedViews:Array.from({length:3},(_,i)=>saved('large-view-'+i,'q='+'v'.repeat(200)))}));assert.equal(writes,0);assert.deepEqual(plain(a.core.getToolsState()),tools());
    const reloaded=boot(w=>w.localStorage.setItem(a.core.key,before));try{assert.equal(Object.keys(reloaded.core.getState().notes).length,count);assert.equal(reloaded.core.getStorageStatus().status,'available');}finally{reloaded.close();}
  }finally{a.close();}
});
