'use strict';
/* v7.45 (lot 8) : contrôle navigateur de Léo (Chromium headless via Playwright, site servi en local, rien d'autre sur le réseau).
   Pages : accueil, fiche véhicule, fiche personnage, carte, calculateur, catalogue Style ; largeurs 320, 390, 768, 1024, 1280,
   1440, 1920 (ouverture, une question, capture, débordement) ; clavier à 1 280 (panneau latéral non modal) et 390 px (fenêtre
   modale : Tab reste dedans) ; mouvement réduit ; 0 erreur console ; performance à 390 px avec le processeur ralenti ×4
   (ouverture, question tapée, suggestion cliquée après survol, pire cas « question envoyée d'un coup sans rien de préparé ») ;
   lien « Signaler » → Contact prérempli. Écrit les captures et rapport.json dans le dossier donné (hors dépôt).
   v7.69 : les parties 1 à 5 mesurent le moteur de Léo en mode « Local » (choix du visiteur gardé sur l'appareil) : aucune
   requête vers /api/ia ne doit partir. La partie 6 vérifie l'IA Claude avec la fonction serveur /api/ia simulée comme en
   production (état, réponse de l'IA et sa mention, compteur, quota épuisé → réponse locale avec la raison, choix « Local »
   → plus rien ne part, même après rechargement ; retour à « IA Claude » → l'état est relu une fois).
   Usage : NODE_PATH=<dépendances>/node_modules node outils/tests/leo-browser.cjs <dossier de sortie> [--sans-largeurs]
   (LK_CHROMIUM=<chemin> pour un Chromium déjà installé ; sinon celui de Playwright). */
const fs=require('fs'),path=require('path'),http=require('http');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../..'),out=process.argv[2];if(!out||out.startsWith('--')){console.error('Usage : node outils/tests/leo-browser.cjs <dossier de sortie> [--sans-largeurs]');process.exit(2);}fs.mkdirSync(out,{recursive:true});
const skipWidths=process.argv.includes('--sans-largeurs');
const MIME={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.json':'application/json','.webp':'image/webp','.png':'image/png','.svg':'image/svg+xml','.jpg':'image/jpeg','.ico':'image/x-icon','.webmanifest':'application/manifest+json','.txt':'text/plain','.xml':'application/xml','.woff2':'font/woff2'};
const server=http.createServer((req,res)=>{let p=decodeURIComponent(req.url.split('?')[0]);if(p.endsWith('/'))p+='index.html';const f=path.join(root,p);if(!f.startsWith(root)||!fs.existsSync(f)||fs.statSync(f).isDirectory()){res.writeHead(404);res.end('404');return;}res.writeHead(200,{'content-type':MIME[path.extname(f)]||'application/octet-stream','cache-control':'no-store'});fs.createReadStream(f).pipe(res);});
const widths=[320,390,768,1024,1280,1440,1920];
const pages=[['accueil','/index.html'],['fiche-vehicule','/vehicules/canis-kamacho.html'],['fiche-personnage','/personnages/jason.html'],['carte','/carte.html'],['calculateur','/calculateurs.html'],['catalogue-style','/style.html']];
const questions=['Quand sort GTA 6 ?','cb coute la baraque de jason','ou est vice city','capitale de la france'];
const report={date:new Date().toISOString(),widths:{},keyboard:{},reducedMotion:{},perf:[],sizes:{},consoleErrors:[],pageErrors:[],requests:{},iaLocal:[]};
(async()=>{
 await new Promise(r=>server.listen(0,r));const port=server.address().port,base='http://127.0.0.1:'+port;
 const browser=await chromium.launch({...(process.env.LK_CHROMIUM?{executablePath:process.env.LK_CHROMIUM}:{}),args:['--no-sandbox']});
 const sizes={};for(const f of ['leo-index.json',...fs.readdirSync(path.join(root,'leo')).map(x=>'leo/'+x),'leo-core.js','leo-nlp.js','leo-ui.js','leo-loader.js','leo-link.js','calculateurs-engine.js','leo.css'])sizes[f]=fs.statSync(path.join(root,f)).size;report.sizes=sizes;
 const attach=(page,label)=>{page.on('console',m=>{if(m.type()==='error'||m.type()==='warning')report.consoleErrors.push({label,type:m.type(),text:m.text()});});page.on('pageerror',e=>report.pageErrors.push({label,text:String(e)}));page.on('requestfailed',r=>{const err=r.failure()?.errorText||'';/* v7.58 : une image interrompue par une navigation (ERR_ABORTED) n'est pas une erreur du site */if(err==='net::ERR_ABORTED')return;report.consoleErrors.push({label,type:'requestfailed',text:r.url()+' '+err});});};
 /* v7.69 : moteur local mesuré en mode « Local » ; toute requête vers /api/ia y serait une erreur */
 const localMode=async ctx=>{await ctx.addInitScript(()=>{try{localStorage.setItem('lk_ia_mode','local');}catch(e){}});ctx.on('request',r=>{if(/\/api\/ia(?:-achat)?(?:[?#]|$)/.test(new URL(r.url()).pathname))report.iaLocal.push(r.url());});};
 const openLeo=async page=>{await page.click('#leo-launch');await page.waitForSelector('#leo-panel[open]',{timeout:15000});await page.waitForFunction(()=>window.LKLeoUI&&window.LKLeoUI.core&&document.querySelectorAll('#leo-panel .leo-suggestions button').length>0,null,{timeout:15000});};
 const askAndTime=async(page,q)=>page.evaluate(async q=>{const t0=performance.now();await window.LKLeoUI.ask(q);const ms=performance.now()-t0;/* ask() rend la réponse avant de se terminer (l'affichage mot à mot continue ≤ 320 ms) */const last=document.querySelectorAll('#leo-panel .leo-message');const node=last[last.length-1];return {ms:+ms.toFixed(1),text:(node.querySelector('p')?.textContent||'').slice(0,160),links:[...node.querySelectorAll('a')].map(a=>a.getAttribute('href')),hasExternal:!!node.querySelector('.leo-external'),hasReport:!!node.querySelector('.leo-report'),hasAction:!!node.querySelector('.leo-action')};},q);
 /* 1. largeurs × pages : ouverture de Léo, une question, capture ; pas de débordement horizontal */
 for(const w of (skipWidths?[]:widths)){report.widths[w]={};for(const [name,url] of pages){const ctx=await browser.newContext({viewport:{width:w,height:w<600?760:900},deviceScaleFactor:1,locale:'fr-FR'});await localMode(ctx);const page=await ctx.newPage();page.setDefaultTimeout(20000);attach(page,name+'@'+w);await page.goto(base+url,{waitUntil:'load'});
   const overflowBefore=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);await openLeo(page);const r=await askAndTime(page,name==='carte'?'ou est vice city':name==='fiche-vehicule'?'et son prix ?':name==='fiche-personnage'?'et son arme ?':'Quand sort GTA 6 ?');
   await page.waitForTimeout(450);/* fin de la composition mot à mot avant la capture */
   const overflow=await page.evaluate(()=>Math.max(document.documentElement.scrollWidth-document.documentElement.clientWidth,document.querySelector('#leo-panel').scrollWidth-document.querySelector('#leo-panel').clientWidth));
   const panelBox=await page.evaluate(()=>{const b=document.querySelector('#leo-panel').getBoundingClientRect();return {left:Math.round(b.left),right:Math.round(b.right),top:Math.round(b.top),bottom:Math.round(b.bottom),vw:innerWidth,vh:innerHeight};});
   await page.screenshot({path:path.join(out,name+'-'+w+'.png'),fullPage:false});report.widths[w][name]={overflowBefore,overflow,panel:panelBox,answer:r};await ctx.close();}}
 /* 2. clavier : Entrée ouvre, le focus entre dans le panneau, Escape ferme et rend le focus au bouton ; à 390 px (fenêtre modale) Tab ne sort pas vers la page */
 report.keyboard={};for(const w of [1280,390]){const ctx=await browser.newContext({viewport:{width:w,height:w<600?760:900},locale:'fr-FR'});await localMode(ctx);const page=await ctx.newPage();attach(page,'clavier@'+w);await page.goto(base+'/index.html',{waitUntil:'load'});
  await page.focus('#leo-launch');await page.keyboard.press('Enter');await page.waitForSelector('#leo-panel[open]',{timeout:15000});await page.waitForFunction(()=>document.querySelectorAll('#leo-panel .leo-suggestions button').length>0);
  const modal=await page.evaluate(()=>document.querySelector('#leo-panel').matches(':modal'));const focusIn=await page.evaluate(()=>document.querySelector('#leo-panel').contains(document.activeElement)&&document.activeElement.id);const stops=[];for(let i=0;i<24;i++){await page.keyboard.press('Tab');stops.push(await page.evaluate(()=>{const a=document.activeElement;return {inPanel:document.querySelector('#leo-panel').contains(a),page:!!a&&a!==document.body&&!document.querySelector('#leo-panel').contains(a),tag:a?a.tagName:null,text:((a&&(a.textContent||a.getAttribute('aria-label')))||'').trim().slice(0,30)};}));}
  await page.focus('#leo-question');await page.keyboard.type('ou est vice city');await page.keyboard.press('Enter');await page.waitForFunction(()=>{const m=[...document.querySelectorAll('#leo-panel .leo-message')];return document.querySelectorAll('#leo-panel .leo-message.user').length>=1&&m.length&&m[m.length-1].classList.contains('bot');});await page.waitForTimeout(450);const typed=await page.evaluate(()=>{const m=[...document.querySelectorAll('#leo-panel .leo-message')].pop();return {text:m.querySelector('p')?.textContent.slice(0,120),action:m.querySelector('.leo-action')?.textContent||null};});
  await page.screenshot({path:path.join(out,'clavier-'+w+'.png')});await page.keyboard.press('Escape');await page.waitForTimeout(400);const closed=await page.evaluate(()=>!document.querySelector('#leo-panel').open);const focusBack=await page.evaluate(()=>document.activeElement.id);
  report.keyboard[w]={modal,focusIn,closed,focusBack,typed,tabLeavesToPage:stops.some(s=>s.page),stops};await ctx.close();}
 /* 3. mouvement réduit : texte complet immédiat, aucune animation en cours */
 {const ctx=await browser.newContext({viewport:{width:390,height:760},reducedMotion:'reduce',locale:'fr-FR'});await localMode(ctx);const page=await ctx.newPage();attach(page,'mouvement-reduit');await page.goto(base+'/index.html',{waitUntil:'load'});await openLeo(page);
  const r=await page.evaluate(async()=>{const log=document.querySelector('#leo-panel .leo-log');await window.LKLeoUI.ask('c est quoi leonidakit');const m=[...log.querySelectorAll('.leo-message')].pop();const p=m.querySelector('p');return {immediate:!p.classList.contains('is-typing')&&p.textContent.length>40,animations:document.querySelector('#leo-panel').getAnimations({subtree:true}).length,text:p.textContent.slice(0,100)};});
  report.reducedMotion=r;await page.screenshot({path:path.join(out,'mouvement-reduit-390.png')});await ctx.close();}
 /* 4. performance, CPU ×4 à 390 px (téléphone moyen) : ouverture (noyau chargé et prêt) ; question tapée au clavier (morceaux préparés pendant la frappe) : Entrée → réponse affichée ;
    suggestion cliquée après survol ; pire cas : question envoyée d'un coup sans rien de préparé (morceaux téléchargés, lus et indexés compris) */
 {const ctx=await browser.newContext({viewport:{width:390,height:760},locale:'fr-FR'});await localMode(ctx);const reqs=[];
  const fresh=async(url)=>{const page=await ctx.newPage();attach(page,'perf');const cdp=await ctx.newCDPSession(page);await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});page.on('response',async r=>{const u=r.url();if(/leo/.test(u)){let n=0;try{n=(await r.body()).length;}catch{}reqs.push({url:u.replace(/^http:\/\/[^/]+/,''),bytes:n});}});await page.goto(base+url,{waitUntil:'load'});const t0=Date.now();await openLeo(page);return {page,openMs:Date.now()-t0};};
  const armWait=page=>page.evaluate(()=>{const log=document.querySelector('#leo-panel .leo-log');const before=log.querySelectorAll('.leo-message.user').length;const done=()=>{const m=log.querySelectorAll('.leo-message');return log.querySelectorAll('.leo-message.user').length>before&&m.length&&m[m.length-1].classList.contains('bot');};window.__t0=null;const input=document.getElementById('leo-question');input.addEventListener('keydown',e=>{if(e.key==='Enter')window.__t0=performance.now();},{capture:true,once:true});document.querySelector('#leo-panel').addEventListener('click',()=>{if(window.__t0===null)window.__t0=performance.now();},{capture:true,once:true});window.__wait=new Promise(res=>{const mo=new MutationObserver(()=>{if(done()){mo.disconnect();res(performance.now()-window.__t0);}});mo.observe(log,{childList:true,subtree:true});});});
  const typedQ=async(page,q)=>{await page.focus('#leo-question');await page.keyboard.type(q,{delay:70});await armWait(page);await page.keyboard.press('Enter');const ms=await page.evaluate(()=>window.__wait);await page.waitForTimeout(400);const text=await page.evaluate(()=>[...document.querySelectorAll('#leo-panel .leo-message.bot p')].pop()?.textContent.slice(0,120));return {q,ms:+ms.toFixed(1),text};};
  const opened=[];let p=await fresh('/index.html');opened.push(p.openMs);const typed=[];for(const q of questions)typed.push(await typedQ(p.page,q));
  p=await fresh('/vehicules/canis-kamacho.html');opened.push(p.openMs);typed.push(await typedQ(p.page,'kamasho ca vaut le coup ?'));
  p=await fresh('/carte.html');opened.push(p.openMs);const chip=await p.page.evaluate(()=>[...document.querySelectorAll('#leo-panel .leo-suggestions button')].map(b=>b.textContent));const b0=p.page.locator('#leo-panel .leo-suggestions button').first();await b0.hover();await p.page.waitForTimeout(150);await armWait(p.page);await b0.click();const chipMs=await p.page.evaluate(()=>window.__wait);
  const cold=[];for(const q of questions.concat(['kamasho ca vaut le coup ?','c est quoi le zorglub de gta 6'])){const f=await fresh('/index.html');opened.push(f.openMs);const r=await askAndTime(f.page,q);cold.push({q,ms:r.ms});await f.page.close();}
  const again=await askAndTime(p.page,'qui est jason');
  report.perf={cpuThrottle:4,viewport:390,openMs:opened,typed,chip:{q:chip[0],ms:+chipMs.toFixed(1)},cold,warmAfterLoad:again.ms,requests:reqs};await p.page.screenshot({path:path.join(out,'perf-390.png')});await ctx.close();}
 /* 5. Contact prérempli depuis « Signaler une mauvaise réponse » */
 {const ctx=await browser.newContext({viewport:{width:768,height:900},locale:'fr-FR'});await localMode(ctx);const page=await ctx.newPage();attach(page,'contact');await page.goto(base+'/index.html',{waitUntil:'load'});await openLeo(page);await askAndTime(page,'capitale de la france');const href=await page.evaluate(()=>[...document.querySelectorAll('#leo-panel .leo-report')].pop()?.getAttribute('href'));
  await page.goto(base+href,{waitUntil:'load'});const form=await page.evaluate(()=>({topic:document.querySelector('#contact-topic')?.value,details:(document.querySelector('#contact-details')?.value||'').slice(0,240),page:document.querySelector('#contact-page')?.value,status:document.querySelector('#lk-status')?.textContent||document.querySelector('[role=status]')?.textContent||''}));report.contact={href,form};await page.waitForTimeout(1200);await page.evaluate(()=>document.getElementById('contact-details').scrollIntoView({block:'center'}));await page.waitForTimeout(900);await page.screenshot({path:path.join(out,'contact-768.png'),fullPage:false});await ctx.close();}
 /* 6. v7.69 : IA Claude avec la fonction serveur /api/ia simulée comme en production (clé posée) */
 {const ctx=await browser.newContext({viewport:{width:390,height:760},locale:'fr-FR',reducedMotion:'reduce'});const calls=[];let left=30;const reset=Date.now()+9*3600e3;
  await ctx.route('**/api/ia',async route=>{let b={};try{b=JSON.parse(route.request().postData()||'{}');}catch{}calls.push(b.mode||'?');const json=(status,obj)=>route.fulfill({status,contentType:'application/json; charset=utf-8',body:JSON.stringify(obj)});
   if(b.mode==='etat')return json(200,{ok:true,mode:'etat',modele:'claude-sonnet-5-5',gratuit:30,heures:9,restant:left,reset:left<30?reset:null,achat:false,solde:0,marge:20});
   if(left<=0)return json(402,{ok:false,code:'quota',gratuit:30,heures:9,restant:0,reset,achat:false,solde:0});
   left--;return json(200,{ok:true,trouve:true,reponse:'Vice City est la grande ville du sud-est de Leonida (réponse simulée pour le contrôle).',liens:[{titre:'La carte de Leonida',url:'/carte.html'}],acces:{type:'gratuit',gratuit:30,heures:9,restant:left,reset}});});
  const errs=[];const watch=page=>{page.on('console',m=>{/* le quota épuisé répond 402 : le navigateur l'écrit en console, c'est attendu */if(m.type()==='error'&&!/status of 402/.test(m.text()))errs.push(m.text());});page.on('pageerror',e=>errs.push(String(e)));};
  const line=page=>page.evaluate(()=>{const b=document.querySelector('#leo-panel .lkia');return b?{kind:b.dataset.kind,text:b.querySelector('.lkia-st').textContent,pressed:[...b.querySelectorAll('[data-lkia-mode]')].filter(x=>x.getAttribute('aria-pressed')==='true').map(x=>x.dataset.lkiaMode)}:null;});
  const last=page=>page.evaluate(()=>{const m=[...document.querySelectorAll('#leo-panel .leo-message.bot')].pop();return {text:(m.querySelector('p')?.textContent||'').slice(0,140),proof:[...m.querySelectorAll('.leo-proof')].map(p=>p.textContent)};});
  const sur30=page=>page.waitForFunction(()=>/sur 30/.test(document.querySelector('#leo-panel .lkia-st')?.textContent||''));
  const page=await ctx.newPage();page.setDefaultTimeout(20000);watch(page);await page.goto(base+'/index.html',{waitUntil:'load'});await openLeo(page);await sur30(page);const start=await line(page);
  await page.evaluate(()=>window.LKLeoUI.ask('ou est vice city'));const ia=await last(page);const after=await line(page);
  left=0;await page.evaluate(()=>window.LKLeoUI.ask('qui est jason'));const quota=await last(page);const quotaLine=await line(page);
  await page.click('#leo-panel [data-lkia-mode="local"]');const n0=calls.length;await page.evaluate(()=>window.LKLeoUI.ask('quand sort gta 6'));const localAns=await last(page);const localLine=await line(page);const privacy=await page.evaluate(()=>document.querySelector('#leo-panel .leo-notice')?.textContent||'');
  await page.screenshot({path:path.join(out,'ia-390.png')});await page.reload({waitUntil:'load'});/* la discussion de l’onglet revient : pas de suggestions à attendre */await page.click('#leo-launch');await page.waitForSelector('#leo-panel[open]',{timeout:15000});await page.waitForFunction(()=>window.LKLeoUI&&window.LKLeoUI.core&&document.querySelector('#leo-panel .lkia'),null,{timeout:15000});await page.waitForTimeout(700);const reloadLine=await line(page);const nReload=calls.length-n0;await ctx.close();
  /* visiteur qui a choisi « Local » : rien ne part à l'ouverture ; « IA Claude » → l'état est lu une fois */
  const ctx2=await browser.newContext({viewport:{width:1280,height:900},locale:'fr-FR',reducedMotion:'reduce'});await ctx2.addInitScript(()=>{try{localStorage.setItem('lk_ia_mode','local');}catch(e){}});
  await ctx2.route('**/api/ia',route=>{calls.push('b:'+((()=>{try{return JSON.parse(route.request().postData()||'{}').mode;}catch{return '?';}})()));return route.fulfill({status:200,contentType:'application/json; charset=utf-8',body:JSON.stringify({ok:true,mode:'etat',modele:'claude-sonnet-5-5',gratuit:30,heures:9,restant:30,reset:null,achat:false,solde:0,marge:20})});});
  const p2=await ctx2.newPage();p2.setDefaultTimeout(20000);watch(p2);await p2.goto(base+'/calculateurs.html',{waitUntil:'load'});await p2.focus('#calc-ask-input');await openLeo(p2);await p2.waitForTimeout(700);const b0=calls.filter(c=>c.startsWith('b:')).length;const localStart=await line(p2);
  await p2.click('#leo-panel [data-lkia-mode="ia"]');await sur30(p2);const back=await line(p2);const b1=calls.filter(c=>c.startsWith('b:')).length;await ctx2.close();
  report.ia={start,ia,after,quota,quotaLine,localAns,localLine,privacy:privacy.slice(0,160),afterReload:nReload,reloadLine,localStart,back,openedLocal:b0,switchedToIA:b1-b0,modes:calls,errors:errs};
  report.ia.ok=!!start&&start.kind==='ia'&&/IA\s:\s30 questions gratuites sur 30/.test(start.text)&&/réponse simulée/.test(ia.text)&&ia.proof.some(t=>/rédigée par l’IA/.test(t))&&/29 questions gratuites sur 30/.test(after.text)
   &&quotaLine.kind==='quota'&&quota.proof.some(t=>/épuisées/.test(t))&&localLine.kind==='local'&&localAns.proof.some(t=>/mode local choisi/.test(t))&&/rien n’est envoyé/.test(privacy)&&calls.length>=3&&nReload===0&&reloadLine&&reloadLine.kind==='local'
   &&localStart.kind==='local'&&b0===0&&b1-b0===1&&back.kind==='ia'&&/30 questions gratuites sur 30/.test(back.text)&&!errs.length;}
 await browser.close();server.close();
 report.summary={consoleErrors:report.consoleErrors.length,pageErrors:report.pageErrors.length,overflow:Object.values(report.widths).flatMap(w=>Object.values(w)).filter(x=>x.overflow>0).length,typedMax:Math.max(...report.perf.typed.map(x=>x.ms)),chipMs:report.perf.chip.ms,coldMax:Math.max(...report.perf.cold.map(x=>x.ms)),openMax:Math.max(...report.perf.openMs),perfOK:report.perf.typed.every(x=>x.ms<300)&&report.perf.chip.ms<300};
 fs.writeFileSync(path.join(out,'rapport.json'),JSON.stringify(report,null,1));console.log(JSON.stringify(report.summary));console.log('tapées',JSON.stringify(report.perf.typed.map(x=>[x.q,x.ms])));console.log('suggestion',JSON.stringify(report.perf.chip),'à froid',JSON.stringify(report.perf.cold.map(x=>[x.q,x.ms])),'ouvertures',JSON.stringify(report.perf.openMs),'chaud',report.perf.warmAfterLoad);for(const w of Object.keys(report.keyboard))console.log('clavier',w,JSON.stringify({modal:report.keyboard[w].modal,focusIn:report.keyboard[w].focusIn,tabLeavesToPage:report.keyboard[w].tabLeavesToPage,closed:report.keyboard[w].closed,focusBack:report.keyboard[w].focusBack,typed:report.keyboard[w].typed.text}));console.log('mouvement réduit',JSON.stringify(report.reducedMotion));console.log('contact',JSON.stringify(report.contact.form));if(report.consoleErrors.length)console.log('console',JSON.stringify(report.consoleErrors.slice(0,10)));if(report.pageErrors.length)console.log('pageErrors',JSON.stringify(report.pageErrors.slice(0,10)));
 console.log('ia',JSON.stringify({ok:report.ia.ok,start:report.ia.start&&report.ia.start.text,after:report.ia.after&&report.ia.after.text,quota:report.ia.quotaLine&&report.ia.quotaLine.text,local:report.ia.localLine&&report.ia.localLine.text,afterReload:report.ia.afterReload,openedLocal:report.ia.openedLocal,switchedToIA:report.ia.switchedToIA,errors:report.ia.errors}));if(report.iaLocal.length)console.log('requêtes /api/ia en mode local',JSON.stringify(report.iaLocal.slice(0,5)));
 const kb390=report.keyboard[390]||{},ok=report.ia.ok&&!report.iaLocal.length&&report.summary.consoleErrors===0&&report.summary.pageErrors===0&&report.summary.overflow===0&&report.summary.perfOK&&!kb390.tabLeavesToPage&&Object.values(report.keyboard).every(k=>k.closed&&k.focusBack==='leo-launch')&&report.reducedMotion.immediate&&report.reducedMotion.animations===0;
 console.log(ok?'Contrôle tenu.':'Contrôle non tenu.');process.exitCode=ok?0:1;
})().catch(e=>{console.error(e);process.exit(1);});
