'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'../..'),C=require(root+'/leo-core.js'),L=require(root+'/leo-link.js'),B=require(root+'/calculateurs-scenario.js'),data=JSON.parse(fs.readFileSync(root+'/leo-index.json')),core=C.create(data);
const ctx={window:{}};vm.createContext(ctx);for(const f of ['vehicules-data.js','armes-data.js','calculateurs-catalogue.js','calculateurs-activites.js','acquisitions-data.js','calculateurs-data.js'])vm.runInContext(fs.readFileSync(root+'/'+f,'utf8'),ctx);const D=ctx.window.LKCalcData,initial=B.initial('test',JSON.parse(JSON.stringify(D.presets))),catalogue=JSON.parse(JSON.stringify(D.catalogue())),activities=JSON.parse(JSON.stringify(D.activities()));
const ask=(q,c={})=>core.answer(q,c,{now:'2026-09-24T12:00:00Z'}),req=(tool='goal',values={},items=[])=>({v:1,tool,values,items});
for(const [q,tool,values] of [
 ["J’ai 200k et je vise 1M",'goal',{capital:200000,target:1000000}],
 ["J'ai 200 000 et je veux atteindre 1 million",'goal',{capital:200000,target:1000000}],
 ["Je joue seul, j’ai 45 min et je veux le million",'goal',{minutes:45,players:1,target:1000000}],
 ["J'ai 45 min ce soir",'session',{minutes:45}],['1 h 30','session',{minutes:90}],['1h30','session',{minutes:90}],
 ['Je joue à 4, 45 min ce soir','session',{players:4,minutes:45}],
 ["J’ai 1,5 million et je vise 2M",'goal',{capital:1500000,target:2000000}],
 ["J’ai 1,234.56 dollars et je vise 20k",'goal',{capital:1234.56,target:20000}],
 ["J’ai 1.234,56 dollars et je vise 20k",'goal',{capital:1234.56,target:20000}],
 ["Je gagne 30k par heure",'goal',{hourly:30000}],
 ['Je veux comparer les gains de mes activités','activities',{}],
 ['Quels achats en premier ?','order',{}],['Préparer mon plan complet','plan',{}],
 ['Répartir mon budget de 200k','budget',{capital:200000}],
])test('Léo comprend : '+q,()=>{const a=ask(q);assert.equal(a.kind,'calc',JSON.stringify(a));assert.equal(a.request.tool,tool);for(const [k,v] of Object.entries(values))assert.equal(a.request.values[k],v,k);assert.doesNotThrow(()=>L.validate(a.request));});
for(const q of ["J’ai 1,5",'200k',"J’ai -20k",'0 min','1 h 90','25 h',"J’ai 1,500 dollars",'Je joue à 101 joueurs',"J’ai 200 euros",'J’ai 2 000 000 000 000 $'])test('Léo demande une précision : '+q,()=>assert.equal(ask(q).kind,'clarify',JSON.stringify(ask(q))));
test('Léo résout les deux clarifications sans perdre l’objectif',()=>{let a=ask("J’ai 1,5 et je vise 2M");a=ask('1,5 million',a.context);assert.equal(a.request.values.capital,1500000);assert.equal(a.request.values.target,2000000);a=ask('200k');a=ask('C’est mon capital',a.context);assert.equal(a.request.values.capital,200000);});
test('Léo recherche une inspiration sans la présenter comme nom officiel',()=>{const a=ask('Trouve-moi la Ferrari');assert.equal(a.kind,'results');assert.ok(a.results.every(x=>/ferrari/i.test(x.inspiration)));assert.ok(a.results.length<=4);assert.ok(a.results.every(x=>!x.name.includes('Ferrari')));});
test('Nom canonique exact et fragment d’arme conservent les liens réels',()=>{const vehicle=core.items.find(x=>x.kind==='vehicle');assert.equal(core.search(vehicle.name).items[0].key,vehicle.key);const a=ask('Où est Girardi ?');assert.equal(a.kind,'results');assert.ok(a.results.some(x=>x.kind==='weapon'));});
test('Recherche multi catégorie désambiguïsée et faute explicitement qualifiée',()=>{const a=ask('Emperor');assert.equal(a.kind,'results');assert.ok(core.search('Emperr').items.some(x=>x.fuzzy));});
test('Un lieu absent reste absent',()=>{const a=ask('Je cherche le lieu Trucmuchopolis');assert.equal(a.kind,'unknown');assert.ok(a.links.some(x=>x.url==='/lieux.html'));});
test('Toutes les définitions et FAQ viennent des contenus visibles',()=>{for(const d of data.definitions){const a=ask('C’est quoi '+d.terms[0]+' ?');assert.equal(a.text,d.text);assert.ok(C.safeURL(a.links[0].url));}assert.equal(ask('Pourquoi le prix manque ?').text,data.faq.find(x=>x.id==='prix').text);});
test('Navigation outil et hubs D produit des liens utilisables',()=>{for(const q of ['Ouvre mon plan','Ouvre les demeures','Ouvre les bateaux','Ouvre le Tuto']){const a=ask(q);assert.ok(a.links?.length,JSON.stringify(a));assert.ok(a.links.every(x=>C.safeURL(x.url)));}});
test('Achat nommé, prix inconnu et contexte pertinent',()=>{let a=ask('Je veux acheter Rideout Customs');assert.equal(a.request.tool,'purchase');assert.deepEqual(a.request.items,['rideout-customs']);assert.equal(a.request.values.price,undefined);a=ask('Est-ce que ça vaut le coup ?',a.context);assert.equal(a.request.tool,'roi');assert.deepEqual(a.request.items,['rideout-customs']);});
test('Requête mixte liée à la vraie entreprise sans rentabilité inventée',()=>{const a=ask('Je veux acheter Rideout Customs, j’ai 200k, est-ce que ça vaut le coup ?');assert.equal(a.request.tool,'roi');assert.deepEqual(a.request.values,{capital:200000});assert.deepEqual(a.request.items,['rideout-customs']);});
test('Année d’un modèle non convertie en montant',()=>{const x=core.items.find(x=>x.calcId&&/\b19\d{2}\b/.test(x.name));if(x){const a=ask('Je veux acheter '+x.name);assert.equal(a.kind,'calc');assert.deepEqual(a.request.values,{});assert.equal(a.request.items[0],x.calcId);}});
test('Changer d’achat ne reprend pas le prix précédent',()=>{const xs=core.items.filter(x=>x.calcId).slice(0,2),a=core.choose(xs[1].key,{tool:'purchase',values:{capital:200000,price:444},selected:[xs[0].key]});assert.equal(a.request.values.price,undefined);assert.equal(a.request.values.capital,200000);const next=ask('C’est quoi le ROI ?',a.context);assert.equal(next.context.values.price,undefined);});
test('Date fraîche sourcée, date ancienne et donnée absente',()=>{const a=ask('Quand sort GTA VI ?');assert.match(a.text,/19 novembre 2026/);assert.match(a.source,/rockstargames/);const stale=core.answer('Quand sort GTA VI ?',{}, {now:'2026-11-20T12:00Z'});assert.match(stale.text,/revérifiée/);assert.match(C.create({...data,release:null}).answer('Quand sort GTA VI ?').text,/revérifiée/);});
test('Longueur limitée et contenu inconnu jamais exécuté',()=>{assert.equal(ask('a'.repeat(601)).kind,'error');assert.equal(ask('<img src=x onerror=alert(1)>').kind,'unknown');assert.equal(C.safeURL('javascript:alert(1)'),null);assert.equal(C.safeURL('//evil.test/foo.html'),null);assert.equal(C.safeReturn,undefined);});
test('Contrat Léo aller-retour sans historique',()=>{const r={...req('session',{minutes:45,capital:200000}),back:'/vehicules.html#cat=avion'};assert.deepEqual(L.fromURL(new URL(L.toURL(r),'https://site.test').search),r);assert.equal(L.fromURL('?tool=goal'),null);assert.equal(L.safeReturn('/'),'/');assert.equal(L.safeReturn('https://evil.test'),null);assert.equal(L.safeReturn('/../index.html'),null);});
for(const bad of [{v:2,tool:'goal',values:{}},{v:1,tool:'evil',values:{}},req('goal',{capital:'3'}),req('goal',{capital:NaN}),req('session',{minutes:0}),req('session',{minutes:1441}),req('goal',{players:1.5}),req('goal',{price:-1}),req('goal',{attack:1}),{...req(),history:['private']},{...req(),back:'javascript:alert(1)'},req('purchase',{},['../bad'])])test('Contrat refuse '+JSON.stringify(bad),()=>assert.throws(()=>L.validate(bad)));
test('Paramètres répétés ou surdimensionnés refusés',()=>{assert.throws(()=>L.fromURL('?leo={}&leo={}'));assert.throws(()=>L.fromURL('?leo='+encodeURIComponent('x'.repeat(2601))));});
test('Fusion modifie uniquement valeurs explicites et conserve capital, prix et scénarios non fournis',()=>{const base=B.copy(initial);base.goal.capital=987;const before=JSON.stringify(base),s=L.apply(req('goal',{target:900000}),base,initial,B,catalogue,'merge',activities);assert.equal(s.goal.capital,987);assert.equal(s.goal.target,900000);assert.deepEqual(s.activities,base.activities);assert.deepEqual(s.assets,base.assets);assert.equal(JSON.stringify(base),before);});
test('Nouveau scénario garde les inconnus et n’invente aucune activité de session',()=>{const s=L.apply(req('session',{minutes:45}),initial,initial,B,catalogue,'new',activities);assert.equal(s.goal.capital,null);assert.equal(s.goal.hourly,null);assert.equal(s.goal.target,null);assert.equal(s.session.minutes,45);assert.deepEqual(s.session.enabled,[]);assert.equal(B.session(s,activities).valid,false);});
test('Prix canonique inconnu et prix personnel conservés dans un seul achat partagé',()=>{const id='rideout-customs',s=L.apply(req('roi',{price:250000},[id]),initial,initial,B,catalogue,'new',activities);assert.equal(B.asset(s,s.roi.key).price,250000);assert.equal(B.asset(s,s.roi.key).referencePrice,null);const u=L.apply(req('purchase',{},[id]),initial,initial,B,catalogue,'new',activities);assert.equal(B.purchase(u).price,null);assert.equal(B.evaluate('purchase',u,activities).valid,false);});
test('Fiche supprimée et conflit réserve refusés avant mutation',()=>{const base=B.copy(initial);base.goal.reserve=50000;const before=JSON.stringify(base);assert.throws(()=>L.apply(req('purchase',{},['removed']),base,initial,B,catalogue,'merge',activities));assert.throws(()=>L.apply(req('goal',{capital:100}),base,initial,B,catalogue,'merge',activities));assert.equal(JSON.stringify(base),before);});

for(const q of ["J’ai 1e6", "J’ai 200kb", "J’ai 1 50 dollars", "J’ai €200k"])test('Format non pris en charge, aucune conversion partielle : '+q,()=>assert.equal(ask(q).kind,'clarify'));
test('Nouvelle demande d’achat explicite ne reprend pas le prix de la fiche précédente',()=>{const prior=ask('Je veux acheter Rideout Customs pour 500k');const next=ask('Et je veux acheter le Garage de Paradise',prior.context);assert.equal(next.kind,'calc');assert.equal(next.request.values.price,undefined);});

test('Nouvel achat introuvable ne réutilise pas une ancienne fiche',()=>{const prior=ask('Je veux acheter Rideout Customs pour 500k'),next=ask('Et je veux acheter Trucmuchopolis',prior.context);assert.equal(next.request.values.price,undefined);assert.deepEqual(next.request.items,[]);assert.match(next.note,/Je ne trouve pas cette fiche|Aucune fiche/);});

for(const value of [null,false,0,''])test('Le contrat refuse values de type '+JSON.stringify(value),()=>assert.throws(()=>L.validate({...req(),values:value})));
test('Un synonyme éditorial d’intention fonctionne sans changer le moteur',()=>{const edited=structuredClone(data);edited.tools.find(x=>x.id==='session').terms.push('petite pause');assert.equal(C.create(edited).answer('Préparer ma petite pause').request.tool,'session');});
test('La projection Léo est à jour avec ses sources canoniques',()=>{const crypto=require('crypto'),manifest=JSON.parse(fs.readFileSync(root+'/outils/leo-index-manifest.json'));for(const [file,expected] of Object.entries(manifest.inputs)){const actual=crypto.createHash('sha256').update(fs.readFileSync(root+'/'+file,'utf8').replace(/\?v=[a-f0-9]+/g,'')).digest('hex');assert.equal(actual,expected,'Régénérer l’index après modification de '+file);}assert.equal(manifest.items,data.items.length);});
test('Les fiches de Léo référencent des achats et routes réellement livrés',()=>{assert.equal(new Set(data.items.map(x=>x.key)).size,data.items.length);for(const x of data.items){assert.ok(fs.existsSync(root+x.url.split('#')[0]),x.url);if(x.calcId)assert.ok(catalogue.some(a=>a.id===x.calcId),x.calcId);if(x.image)assert.ok(fs.existsSync(root+x.image),x.image);}});
test('Lot B : deux fiches nommées vont dans Quel achat choisir ?, une fiche et « business plan » vont dans Mon business plan',()=>{
 const xs=core.items.filter(x=>x.calcId).slice(0,2);
 const a=ask(xs[0].name+' ou '+xs[1].name+' ?');assert.equal(a.kind,'calc');assert.equal(a.request.tool,'compare');assert.deepEqual(a.request.items,[xs[0].calcId,xs[1].calcId]);
 const b=ask('Fais-moi un business plan pour acheter '+xs[0].name);assert.equal(b.kind,'calc');assert.equal(b.request.tool,'plan');assert.deepEqual(b.request.items,[xs[0].calcId]);
 assert.equal(ask('Dans quel ordre acheter '+xs[0].name+' et '+xs[1].name+' ?').request.tool,'order');
 assert.equal(ask('comparer mes activités').request.tool,'activities');
 const s=L.apply(a.request,initial,initial,B,catalogue,'new',activities);assert.equal(s.tab,'compare');assert.equal(s.compare.keys.length,2);
 const t=L.apply(b.request,initial,initial,B,catalogue,'new',activities);assert.equal(t.tab,'plan');assert.equal(t.plan.goal.kind,'purchase');assert.equal(t.plan.goal.itemId,xs[0].calcId);assert.equal(t.plan.goal.name,catalogue.find(x=>x.id===xs[0].calcId).name);
});
test('v7.33 : Léo explique un calcul avec le moteur du calculateur, mêmes chiffres, sans inventer quand il en manque',()=>{
 const a=ask('J’ai 200 000 $ et je veux 1 million, je gagne 100 000 par heure');assert.equal(a.kind,'calc');assert.match(a.note,/il te manque 800\s000 \$, soit 8 h de jeu/);assert.match(a.note,/si tu gagnes toujours pareil/);
 const b=ask('J’ai 200k et je vise 1M');assert.equal(b.kind,'calc');assert.doesNotMatch(b.note||'',/de jeu/);
 const c=ask('Je veux acheter Rideout Customs pour 500k, j’ai 200k');assert.equal(c.kind,'calc');assert.match(c.note,/il te manque 300\s000/);
 assert.equal(require(root+'/calculateurs-engine.js').goalContinuous({capital:200000,target:1000000,hourly:100000,reserve:0}).hours,8);
});
