const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'../..'),P=require(root+'/progression-core.js');
const c={window:{}};for(const f of ['acquisitions-data.js','progression-data.js','collectibles-data.js','vehicules-data.js','armes-data.js','calculateurs-catalogue.js','assets-manifest.js','calculateurs-data.js'])vm.runInNewContext(fs.readFileSync(root+'/'+f,'utf8'),c);
const plain=x=>JSON.parse(JSON.stringify(x)),acquisitions=plain(c.window.LK_ACQUISITIONS),ids=plain(c.window.LK_PROGRESS_IDS),collectibles=plain(c.window.LK_COLLECTIBLES.items);
function memory(initial={}){const map=new Map(Object.entries(initial));return {get length(){return map.size;},key:i=>[...map.keys()][i],getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k),map};}
function setup(initial={},data=acquisitions){const storage=memory(initial),messages=[],store=P.create({storage,acquisitions:data,ids,collectibles,notice:m=>messages.push(m)});return {storage,messages,store};}
const legacy={lk_own_vehicules:JSON.stringify({'crest-kayak':1,'karin-sultan':true}),lk_own_armes:JSON.stringify({'girardi-es9':1}),lk_map_found:JSON.stringify({[ids.lieux[0]]:1,[ids.lieux[1]]:true})};
test('migration preserves legacy bytes and every existing known check',()=>{const {storage,store}=setup(legacy);assert.equal(store.migrate(),true);assert.equal(store.summary().done,5);for(const [k,v] of Object.entries(legacy))assert.equal(storage.getItem(k),v);assert.equal(store.migrate(),false);});
test('boat is partitioned once in global denominator and retains old garage state',()=>{const {store}=setup(legacy);const s=store.summary(),boats=s.groups.find(g=>g.id==='boats'),vehicles=s.groups.find(g=>g.id==='vehicules');assert.equal(boats.total,2);assert.equal(boats.done,1);assert.equal(vehicles.total,ids.vehicules.length-2);assert.equal(vehicles.done,1);assert.equal(s.total,ids.vehicules.length+ids.armes.length+new Set(ids.lieux).size+4+collectibles.filter(x=>x.trackable===true&&x.published!==false&&['confirmed','established'].includes(x.status)).length);});
test('toggle new content updates category and weighted global without rounding internally',()=>{const {store}=setup(legacy);store.migrate();const before=store.summary();assert.equal(store.toggle('ganado-retro-build',true),true);const s=store.summary();assert.equal(s.done,before.done+1);assert.equal(s.groups.find(g=>g.id==='customizations').percent,50);assert.equal(s.percent,s.done/s.total*100);store.toggle('ganado-retro-build',false);assert.equal(store.summary().done,before.done);});
test('style really has zero trackable items, null percent and no fictional checkbox',()=>{const {store}=setup();const s=store.summary(),g=s.groups.find(g=>g.id==='style');assert.equal(g.total,0);assert.equal(g.percent,null);assert.equal(store.toggle('style-vice-city',true),false);assert.equal(store.summary().done,0);assert.ok(s.percent>=0&&s.percent<=100);});
test('hub and progression refer to the very same legacy boat key',()=>{const {storage,store}=setup(legacy);store.toggle('shitzu-squalo',true);assert.equal(JSON.parse(storage.getItem('lk_own_vehicules'))['shitzu-squalo'],true);assert.equal(JSON.parse(storage.getItem('lk_own_vehicules'))['crest-kayak'],true);});
test('rename or move with stable canonical ID preserves state',()=>{const {storage,store}=setup();store.toggle('garage-paradise',true);const next=plain(acquisitions);const item=next.items.find(x=>x.id==='garage-paradise');item.name='Libellé modifié pour le test';const other=P.create({storage,acquisitions:next,ids,collectibles});assert.equal(other.checked(item),true);});
test('export and import reproduce checked IDs, maps, notebook raw data and plans',()=>{const {store,storage}=setup({...legacy,'lk-calculator-notebooks-v3':JSON.stringify({version:3,entries:[{id:'test-plan',tool:'plan',config:{version:3}}],active:{},references:{}})});store.migrate();store.toggle('garage-paradise',true);const output=store.exportData();assert.equal(output.version,2);assert.ok(output.data['lk-calculator-notebooks-v3']);const dst=setup();dst.store.applyImport(dst.store.prepareImport(JSON.stringify(output)),'replace');assert.deepEqual(dst.store.summary(),store.summary());assert.deepEqual(JSON.parse(dst.storage.getItem('lk-calculator-notebooks-v3')),JSON.parse(storage.getItem('lk-calculator-notebooks-v3')));});
test('old v1 import never clears new categories on the destination',()=>{const {store}=setup();store.toggle('garage-paradise',true);store.applyImport(store.prepareImport(JSON.stringify({site:'leonidakit',version:1,date:'2025-01-01',data:legacy})),'replace');assert.equal(store.summary().done,6);});
test('unknown references are signalled, retained for recovery and excluded from counts',()=>{const {store}=setup();const p=store.prepareImport(JSON.stringify({site:'leonidakit',version:1,data:{lk_own_vehicules:JSON.stringify({'unknown-removed-id':true,'crest-kayak':true}),lk_unrecognized:'anything'}}));assert.ok(p.issues.some(x=>x.includes('unknown-removed-id')));assert.ok(p.issues.some(x=>x.includes('lk_unrecognized')));store.applyImport(p,'merge');assert.equal(store.summary().done,1);});
test('one corrupt own entry does not erase good checks or original raw data',()=>{const raw=JSON.stringify({'crest-kayak':true,'shitzu-squalo':'bad'}),{store,storage}=setup({lk_own_vehicules:raw});assert.equal(store.summary().done,1);assert.equal(storage.getItem('lk_own_vehicules'),raw);store.toggle('shitzu-squalo',true);assert.equal(store.summary().done,2);assert.ok([...storage.map.values()].includes(raw));});
test('corrupt import keeps valid rubrics, makes recovery copy and never touches skipped local rubric',()=>{const {store,storage}=setup(legacy);const p=store.prepareImport(JSON.stringify({site:'leonidakit',version:1,data:{lk_own_vehicules:'bad json',lk_own_armes:'{}'}}));store.applyImport(p,'replace');assert.equal(storage.getItem('lk_own_vehicules'),legacy.lk_own_vehicules);assert.ok([...storage.map.values()].includes('bad json'));});
test('invalid file, future schema and invalid metadata cannot mutate storage',()=>{const {store,storage}=setup(legacy),before=[...storage.map];for(const text of ['{','null',JSON.stringify({site:'elsewhere',data:{}}),JSON.stringify({site:'leonidakit',version:7,data:legacy}),JSON.stringify({site:'leonidakit',version:2,schemaVersion:2,exportedAt:new Date().toISOString(),categories:[{id:'bad',checkedIds:[{}]}],data:legacy})])assert.throws(()=>store.prepareImport(text));assert.deepEqual([...storage.map],before);});
test('storage failure rolls back all already written rubrics',()=>{const {store,storage}=setup(legacy),before=[...storage.map],save=storage.setItem;let failed=false;storage.setItem=(k,v)=>{if(k==='lk_own_armes'&&!failed){failed=true;throw Error('Quota');}return save(k,v);};const p=store.prepareImport(JSON.stringify({site:'leonidakit',version:1,data:{lk_own_vehicules:'{}',lk_own_armes:'{}'}}));assert.throws(()=>store.applyImport(p,'replace'));assert.deepEqual([...storage.map],before);});
test('new calculator entries have no invented price, no duplicate existing boats and no unlisted clothing',()=>{const rows=c.window.LKCalcData.catalogue();assert.equal(rows.filter(x=>x.id==='crest-kayak').length,1);for(const item of acquisitions.items){const row=rows.find(x=>x.id===item.id);if(item.calculatorCompatible){assert.ok(row);assert.equal(row.price,null);assert.equal(row.evidenceLevel,1);assert.ok(row.acquisitionCondition);}else assert.equal(row,undefined);}assert.ok(rows.find(x=>x.id==='garage-paradise').url.endsWith('#garage-paradise'));});
