const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const {load}=require('./runtime-helper.cjs');const root=process.env.SITE_ROOT||path.resolve(__dirname,'../..');
const catalog=JSON.parse(fs.readFileSync(path.join(root,'outils/v-corrige.json'),'utf8'));
const baseline={window:{}};for(const f of ['armes-data.js','vehicules-data.js','progression-data.js','carte-gtadb.js'])vm.runInNewContext(fs.readFileSync(path.join(root,f),'utf8'),baseline);
const weaponCount=baseline.window.LK_ARMES.length,mapCount=baseline.window.LK_PROGRESS_IDS.lieux.length;
const categoryCount=cat=>catalog.filter(v=>v.cat===cat).length;
const total=a=>{const vis=a.d.querySelectorAll('.veh-card:not([hidden])').length;const b=a.d.getElementById('vplus');const m=b&&!b.hidden?b.textContent.match(/\((\d+) restant/):null;return vis+(m?Number(m[1]):0);};
const click=(a,id)=>a.d.getElementById(id).click();
const input=(a,id,value)=>{const e=a.d.getElementById(id);e.value=value;e.dispatchEvent(new a.w.Event('input',{bubbles:true}));};
const change=(a,id,value)=>{const e=a.d.getElementById(id);e.value=value;e.dispatchEvent(new a.w.Event('change',{bubbles:true}));};
const withPage=(file,fn,opts={})=>async()=>{const a=await load(root,file,opts);try{await fn(a);assert.deepEqual(a.errors.filter(x=>!x.includes('Not implemented: navigation')),[]);}finally{a.close();}};
test('Search renders hostile text literally, with no HTML node',withPage('index.html',a=>{input(a,'q','<svg data-audit="xss"></svg>');assert.equal(a.d.querySelector('[data-audit]'),null);assert.match(a.d.getElementById('suggest').textContent,/<svg/);}));
test('Global search finds model inspiration with accents',withPage('index.html',a=>{input(a,'q','Crown Victoria');assert.match(a.d.getElementById('suggest').textContent,/Stanier/);}));
test('Search keyboard selection exposes active descendant and Escape closes',withPage('index.html',a=>{input(a,'q','Sultan');const q=a.d.getElementById('q');q.dispatchEvent(new a.w.KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));assert.ok(a.d.getElementById(q.getAttribute('aria-activedescendant')));q.dispatchEvent(new a.w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(q.getAttribute('aria-expanded'),'false');}));
test('Slash does not hijack typing in an unrelated input',withPage('index.html',a=>{const mail=a.d.getElementById('mail');mail.focus();const event=new a.w.KeyboardEvent('keydown',{key:'/',bubbles:true,cancelable:true});mail.dispatchEvent(event);assert.equal(event.defaultPrevented,false);assert.equal(a.d.activeElement,mail);}));
test('Malformed filter hash cannot break the catalogue',withPage('vehicules.html#st=%22%5D%5B',a=>{assert.equal(a.d.querySelectorAll('.veh-card:not([hidden])').length,48);assert.equal(total(a),catalog.length);}));
test('Category, search and sort filter the complete catalogue',withPage('vehicules.html',a=>{a.d.querySelector('[data-filter=sport]').click();input(a,'vq','Sultan');assert.equal(a.d.querySelectorAll('.veh-card:not([hidden])').length,2);change(a,'vtri','za');assert.equal(a.d.querySelector('.veh-card:not([hidden]) h3').textContent,'Sultan RS');assert.equal(a.d.querySelector('[data-filter=sport]').getAttribute('aria-pressed'),'true');}));
test('Hash changes reset old filters and restore the new state',withPage('vehicules.html#cat=sport',a=>{a.w.location.hash='cat=avion';a.w.dispatchEvent(new a.w.HashChangeEvent('hashchange'));assert.equal(a.d.querySelectorAll('.veh-card:not([hidden])').length,Math.min(48,categoryCount('avion')));a.w.location.hash='';a.w.dispatchEvent(new a.w.HashChangeEvent('hashchange'));assert.equal(total(a),catalog.length);}));
test('Garage share is imported and unknown IDs are ignored',withPage('vehicules.html#garage=karin-sultan,unknown,constructor',a=>{const o=JSON.parse(a.w.localStorage.getItem('lk_own_vehicules'));assert.equal(o['karin-sultan'],1);assert.equal(Object.hasOwn(o,'constructor'),false);assert.equal(a.d.querySelectorAll('.is-own').length,1);}));
test('Garage buttons work without nesting interactive elements',withPage('vehicules.html',a=>{const c=a.d.querySelector('[data-id="karin-sultan"]');c.querySelector('.own-card').click();assert.equal(JSON.parse(a.w.localStorage.getItem('lk_own_vehicules'))['karin-sultan'],1);assert.equal(a.d.querySelector('a button'),null);assert.equal(a.d.querySelectorAll('.veh-card').length,catalog.length);}));
test('Corrupted collection JSON does not crash the hub',withPage('vehicules.html',a=>{assert.equal(a.d.querySelectorAll('.own-card').length,catalog.length);a.d.querySelector('.own-card').click();assert.ok(a.w.localStorage.getItem('lk_own_vehicules'));},{storage:{lk_own_vehicules:'null'}}));
test('Loadout deep link survives catalogue initialization',withPage('armes.html#lo=carabine,fusil-pompe,girardi-es9',a=>{assert.equal(a.d.getElementById('lo-poing').value,'girardi-es9');assert.ok(a.d.querySelector('#lo-art-poing svg, #lo-art-poing img.lo-photo'));}));
test('All loadout options reference actual cards with artwork',withPage('armes.html',a=>{for(const select of a.d.querySelectorAll('#loadout select'))for(const opt of select.options){if(!opt.value)continue;change(a,select.id,opt.value);assert.ok(a.d.querySelector('#lo-art-'+select.id.slice(3)+' svg, #lo-art-'+select.id.slice(3)+' img.lo-photo'),opt.value);}}));
test('Duplicate long weapon is rejected and an empty loadout clears the link',withPage('armes.html',a=>{change(a,'lo-dos','carabine');change(a,'lo-main','carabine');assert.match(a.d.getElementById('lo-verdict').textContent,/même arme/);change(a,'lo-dos','');change(a,'lo-main','');assert.equal(new URLSearchParams(a.w.location.hash.slice(1)).has('lo'),false);}));
test('Comparator validates URL IDs, uses labels and updates empty selection URL',withPage('comparateur.html?type=vehicules&ids=karin-sultan,karin-sultan,constructor',a=>{assert.equal(a.d.querySelectorAll('#cmp-table thead a').length,1);assert.match(a.d.getElementById('cmp-table').textContent,/Voitures de sport/);const s=a.d.querySelector('#cmp-pick select');s.value='';s.dispatchEvent(new a.w.Event('change'));assert.equal(new URLSearchParams(a.w.location.search).has('ids'),false);}));
test('Ranking accepts newly added vehicles and rejects stale options',withPage('classement-vehicules.html',a=>{assert.ok([...a.d.getElementById('cl-sel').options].some(o=>o.value==='ford-explorer-sport-trac'));change(a,'cl-sel','ford-explorer-sport-trac');click(a,'cl-add');assert.match(a.d.getElementById('cl-liste').textContent,/Explorer Sport Trac/);assert.equal(a.d.querySelector('[value="vapid-sadler"]'),null);}));
test('Ranking share deduplicates entries',withPage('classement-vehicules.html#top=karin-sultan,karin-sultan,constructor',a=>assert.equal(a.d.querySelectorAll('.cl-item').length,1)));
test('No gallery requests missing images',withPage('vehicules/karin-sultan.html',a=>{assert.equal(a.requests.length,0);assert.match(a.d.querySelector('.gal').textContent,/intégrer/);assert.equal(a.d.querySelectorAll('#reel-bt').length,1);assert.ok(a.d.querySelector('#carte a[href*="carte.html#lieu="]'));}));
test('404 page supports both searches and nested URLs',withPage('404.html',a=>{input(a,'q404','Sultan');assert.match(a.d.getElementById('suggest404').textContent,/Sultan/);},{url:'https://www.leonidakit.com/unknown/nested/route'}));
test('Clipboard rejection never announces success',withPage('comparateur.html',async a=>{Object.defineProperty(a.w.navigator,'clipboard',{value:{writeText:()=>Promise.reject(new Error('denied'))},configurable:true});click(a,'cmp-share');await new Promise(r=>setImmediate(r));assert.doesNotMatch(a.d.getElementById('cmp-share').textContent,/copié/i);assert.match(a.d.getElementById('lk-status').textContent,/impossible/i);}));
test('Newsletter does not fabricate a confirmation or use an invisible sink',withPage('index.html',a=>{assert.equal(a.d.querySelector('#signup').target,'_self');assert.equal(a.d.querySelector('iframe[name="brevo-sink"]'),null);const f=a.d.getElementById('signup');input(a,'mail','invalid');const e=new a.w.Event('submit',{cancelable:true});f.dispatchEvent(e);assert.equal(e.defaultPrevented,true);}));
test('Progression shows only actual stored IDs',withPage('progression.html',a=>{assert.equal(a.d.querySelector('#progress-vehicules strong').textContent,'1 / '+catalog.length);assert.equal(a.d.querySelector('#progress-armes strong').textContent,'1 / '+weaponCount);assert.equal(a.d.querySelector('#progress-lieux strong').textContent,'1 / '+mapCount);},{storage:{lk_own_vehicules:'{"karin-sultan":1,"unknown":1}',lk_own_armes:'{"girardi-es9":1}',lk_map_found:'{"vice-city":true}'}}));
test('Map starts despite malformed stored state',withPage('carte.html',a=>{assert.ok(a.w.LK_MAP);assert.equal(a.d.querySelector('.vstat .n').textContent,String(mapCount));},{storage:{lk_map_found:'null',lk_map_perso:'{}',lk_map_draw:'[null]',lk_map_layers:'null'}}));
test('Personal marker opens from its list without a standard map status',withPage('carte.html',a=>{a.d.querySelector('.ed-go').click();assert.match(a.d.getElementById('map-panel-in').textContent,/Test personnel/);assert.ok(a.d.getElementById('pm-edit'));},{storage:{lk_map_perso:'[{"n":"Test personnel","x":2500,"y":3200,"note":"Ma note"}]'}}));
test('Invalid persisted coordinates cannot inject HTML',withPage('carte.html',a=>assert.equal(a.d.querySelector('[data-audit]'),null),{storage:{lk_map_perso:'[{"n":"Test","x":"<img data-audit=xss>","y":1}]'}}));
test('Map rejects hostile or malformed imports before changing any saved data',withPage('carte.html',a=>{const before=a.w.localStorage.getItem('lk_map_found');for(const d of [{version:2,marqueurs:[{n:'X',x:'<svg>',y:1}],repere:{}},{version:2,marqueurs:[],repere:{},traces:[{t:'pen',p:null}]},{version:2,marqueurs:[],repere:{constructor:true}}])assert.throws(()=>a.w.LK.mapImport(d));assert.equal(a.w.localStorage.getItem('lk_map_found'),before);}));
test('Map accepts a valid full backup and restores found places and drawings',withPage('carte.html',a=>{const d=a.w.LK.mapImport({version:2,marqueurs:[{n:'Lieu',x:2400,y:3000}],repere:{'vice-city':true},traces:[{t:'line',a:[1,2],b:[3,4],c:'#e8452c',w:6,o:0.85}]});a.w.LK_MAP.setFound(d.repere);a.w.LK_MAP.setDraw(d.traces);assert.equal(a.d.querySelector('#map-prog-txt strong').textContent,'1');assert.equal(a.d.querySelectorAll('.dr-stroke').length,1);}));
test('Map modes are mutually exclusive',withPage('carte.html',a=>{click(a,'map-edit');click(a,'dr-on');assert.equal(a.d.getElementById('map-edit').getAttribute('aria-pressed'),'false');click(a,'map-ruler');assert.equal(a.d.getElementById('dr-on').getAttribute('aria-pressed'),'false');assert.equal(a.d.getElementById('map-ruler').getAttribute('aria-pressed'),'true');}));
test('Map search keyboard opens a place and photo requests all exist',withPage('carte.html',a=>{input(a,'map-search','Vice City');a.d.getElementById('map-search').dispatchEvent(new a.w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.match(a.d.getElementById('map-panel-in').textContent,/Vice City/);assert.equal(a.d.getElementById('map-panel').inert,false);assert.ok(a.requests.every(u=>fs.existsSync(path.join(root,new URL(u,a.w.location.href).pathname))));}));
test('Map extreme or malformed hash does not yield NaN transforms',withPage('carte.html#1,2,.',a=>assert.doesNotMatch(a.d.getElementById('map-world').style.transform,/NaN/)));
test('Licence filter rejects NC and ND, accepts the explicit free licences',()=>{const free=require('../licenses.cjs');for(const l of ['CC BY-NC 4.0','CC BY-ND 4.0','CC BY-SA-NC 3.0','CC BY 4.0 unknown'])assert.equal(free(l),false,l);for(const l of ['CC BY 4.0','CC BY-SA 3.0','CC0 1.0','Public domain'])assert.equal(free(l),true,l);});
test('Legacy category links keep the intended filter',withPage('vehicules.html#suv',a=>{assert.equal(total(a),categoryCount('suv'));for(const card of a.d.querySelectorAll('.veh-card:not([hidden])'))assert.equal(card.dataset.cat,'suv');}));
test('Saved ranking is unique, bounded and supports keyboard focus after moving',withPage('classement-vehicules.html',a=>{assert.equal(a.d.querySelectorAll('.cl-item').length,2);const b=a.d.querySelector('.cl-item [data-down]');b.focus();b.click();assert.equal(a.d.activeElement.closest('.cl-item').dataset.id,'karin-sultan');assert.equal(a.d.querySelector('.cl-item').dataset.id,'karin-sultan-rs');},{storage:{lk_classement:'["karin-sultan","karin-sultan","karin-sultan-rs","unknown"]'}}));
const backup={version:2,marqueurs:[{n:'Import réel',x:100,y:200}],repere:{'vice-city':true,unknown:true},traces:[{t:'line',a:[1,2],b:[3,4],c:'#e8452c',w:6,o:0.85}]};
function importFile(a,data){a.w.FileReader=class{readAsText(){this.result=JSON.stringify(data);this.onload();}};const i=a.d.getElementById('map-import-file');Object.defineProperty(i,'files',{value:[{size:100}],configurable:true});i.dispatchEvent(new a.w.Event('change'));}
test('Import file input restores every area and filters unknown place IDs',withPage('carte.html',a=>{importFile(a,backup);assert.equal(a.w.lastAlert,'Import réussi.');assert.equal(JSON.parse(a.w.localStorage.getItem('lk_map_perso'))[0].n,'Import réel');assert.equal(Object.hasOwn(JSON.parse(a.w.localStorage.getItem('lk_map_found')),'unknown'),false);assert.equal(a.d.querySelectorAll('.dr-stroke').length,1);a.d.querySelector('.ed-go').click();assert.match(a.d.getElementById('map-panel-in').textContent,/Import réel/);}));
test('Failed multi-area save rolls back prior writes and does not apply imported state',withPage('carte.html',a=>{const original=a.w.Storage.prototype.setItem;a.w.Storage.prototype.setItem=function(k,v){if(k==='lk_map_draw')throw new Error('Quota');return original.call(this,k,v);};importFile(a,backup);assert.match(a.w.lastAlert,/Import refusé/);assert.equal(a.w.localStorage.getItem('lk_map_perso'),null);assert.equal(a.w.localStorage.getItem('lk_map_found'),null);assert.equal(a.d.querySelectorAll('.dr-stroke').length,0);assert.equal(a.d.querySelectorAll('.ed-go').length,0);}));
test('Malformed drawing file leaves all existing map records untouched',withPage('carte.html',a=>{const old=a.w.localStorage.getItem('lk_map_perso');importFile(a,{...backup,traces:[{}]});assert.match(a.w.lastAlert,/Import refusé/);assert.equal(a.w.localStorage.getItem('lk_map_perso'),old);},{storage:{lk_map_perso:'[{"n":"Ancien","x":100,"y":200}]'}}));
test('Map can display a second photo when the first file is absent',withPage('carte.html#lieu=vice-city',async a=>{await new Promise(r=>setImmediate(r));assert.ok(a.d.querySelector('#mp-photos img'));assert.ok(a.requests.length);assert.ok(a.requests.every(u=>u&&fs.existsSync(path.join(root,new URL(u,a.w.location.href).pathname))));},{beforeScript(w,s){if(s.getAttribute('src')==='carte.js')w.LK_GTADB.enrichit['vice-city']={img2:'photos/L1,ig.webp',img2Src:'Photo fournie dans le projet'};}}));
test('Map drawing saves a real pointer stroke; undo and redo restore it',withPage('carte.html',a=>{click(a,'dr-on');const stage=a.d.getElementById('map-stage');for(const [type,x,y]of [['pointerdown',200,200],['pointermove',300,300],['pointerup',300,300]])stage.dispatchEvent(new a.w.MouseEvent(type,{clientX:x,clientY:y,bubbles:true,cancelable:true}));assert.equal(a.w.LK_MAP.getDraw().length,1);assert.equal(a.d.querySelectorAll('.dr-stroke').length,1);click(a,'dr-undo');assert.equal(a.w.LK_MAP.getDraw().length,0);click(a,'dr-redo');assert.equal(a.w.LK_MAP.getDraw().length,1);}));
test('Map zoom and ruler remain operable',withPage('carte.html',a=>{const before=a.w.LK_MAP.scale();click(a,'map-zin');assert.ok(a.w.LK_MAP.scale()>before);click(a,'map-zout');assert.ok(Number.isFinite(a.w.LK_MAP.scale()));click(a,'map-ruler');const stage=a.d.getElementById('map-stage');for(const [x,y]of [[100,100],[220,240]])stage.dispatchEvent(new a.w.MouseEvent('click',{clientX:x,clientY:y,bubbles:true}));assert.doesNotMatch(a.d.getElementById('map-ruler-box').textContent,/NaN|undefined/);assert.match(a.d.getElementById('map-ruler-box').textContent,/m|km/);}));
test('Vehicle narrative and declared inspiration keep corrected identities',()=>{const v=JSON.parse(fs.readFileSync(path.join(root,'outils/v-corrige.json')));const by=Object.fromEntries(v.map(x=>[x.id,x]));assert.match(by['annis-growler'].txt,/Pfister.*Porsche/);assert.match(by['invetero-coquette'].txt,/Corvette C7/);assert.doesNotMatch(by['invetero-coquette'].txt,/C8/);assert.match(by['maibatsu-sanchez'].txt,/Yamaha YZ450F/);assert.match(by['western-sea-sparrow'].txt,/Sikorsky S-300/);});
test('Every map category can be disabled and restored',withPage('carte.html',a=>{const filters=[...a.d.querySelectorAll('.map-filter')];assert.ok(filters.length>=11);for(const i of filters){i.checked=false;i.dispatchEvent(new a.w.Event('change'));}assert.equal([...a.d.querySelectorAll('.map-markers .mk')].filter(n=>n.style.display!=='none').length,0);for(const i of filters){i.checked=true;i.dispatchEvent(new a.w.Event('change'));}assert.ok([...a.d.querySelectorAll('.map-markers .mk')].some(n=>n.style.display!=='none'));}));
test('Image synchronisation preserves existing declarations and refuses files with no credit',()=>{const {spawnSync}=require('child_process'),os=require('os');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lk-images-'));try{fs.mkdirSync(path.join(dir,'outils'));fs.copyFileSync(path.join(root,'outils/images.js'),path.join(dir,'outils/images.js'));const src=[{id:'test-car',vues:['profil']}];fs.writeFileSync(path.join(dir,'outils/v-corrige.json'),JSON.stringify(src));fs.writeFileSync(path.join(dir,'outils/credits-images.json'),'{}');let r=spawnSync(process.execPath,[path.join(dir,'outils/images.js'),'--ecrire']);assert.equal(r.status,0,String(r.stderr));assert.deepEqual(JSON.parse(fs.readFileSync(path.join(dir,'outils/v-corrige.json'))),src);fs.mkdirSync(path.join(dir,'img/vehicules'),{recursive:true});fs.copyFileSync(path.join(root,'photos/L1,ig.webp'),path.join(dir,'img/vehicules/test-car-face.jpg'));r=spawnSync(process.execPath,[path.join(dir,'outils/images.js'),'--ecrire']);assert.equal(r.status,1);assert.deepEqual(JSON.parse(fs.readFileSync(path.join(dir,'outils/v-corrige.json'))),src);}finally{fs.rmSync(dir,{recursive:true,force:true});}});

// Défaut réel réparé en v7.2 : des WebP présents dans photos/ ne doivent jamais disparaître à la régénération de carte-gtadb.js.
test('Map generation preserves every available source photo',()=>{
 const source=JSON.parse(fs.readFileSync(path.join(root,'outils/data/carte-gtadb-source.json'),'utf8')),runtime=baseline.window.LK_GTADB;
 let available=0;
 for(const section of ['groupes','lieux','enrichit']){
  const entries=Array.isArray(source[section])?source[section].map(x=>[x.id,x]):Object.entries(source[section]);
  const live=new Map(Array.isArray(runtime[section])?runtime[section].map(x=>[x.id,x]):Object.entries(runtime[section]));
  for(const [id,point] of entries)for(const key of ['img','img2'])if(point[key]&&fs.existsSync(path.join(root,point[key]))){available++;assert.equal(live.get(id)?.[key],point[key],section+' '+id+' '+key);}
 }
 assert.ok(available>3000,'photos disponibles : '+available);
});
// Première vue lisible sans JavaScript, vues suivantes chargées seulement à la demande (fiches véhicules et armes).
test('Gallery exposes a static image and loads additional slides only on demand',async()=>{
 const am=JSON.parse(fs.readFileSync(path.join(root,'outils/armes-medias.json'),'utf8'));
 const fixtures=[['vehicules',catalog.find(v=>Array.isArray(v.medias)&&v.medias.length>1)?.id],['armes',Object.keys(am).find(id=>am[id].length>1)]];
 const {JSDOM}=require('jsdom');
 for(const [dir,id] of fixtures){assert.ok(id,dir+' : une fiche à plusieurs images est nécessaire');const file=dir+'/'+id+'.html';
  const raw=new JSDOM(fs.readFileSync(path.join(root,file),'utf8'));
  try{const first=raw.window.document.querySelector('.gal img[src]');assert.ok(first,'image statique');assert.ok(first.getAttribute('alt'));assert.ok(+first.getAttribute('width')>0&&+first.getAttribute('height')>0);}finally{raw.window.close();}
  const a=await load(root,file);
  try{const gallery=a.d.querySelector('.gal'),images=[...gallery.querySelectorAll('img')];assert.ok(images.length>1);assert.equal(images.filter(x=>x.hasAttribute('src')).length,1);gallery.querySelector('.gal-btn.next').click();assert.equal(images.filter(x=>x.hasAttribute('src')).length,2);for(const img of images.filter(x=>x.hasAttribute('src')))assert.ok(fs.existsSync(path.join(root,new URL(img.src).pathname)));assert.deepEqual(a.errors,[]);}finally{a.close();}
 }
});

// v7.3 : galeries « En images » des fiches du monde (sans légende, vignettes différées, lien vers la version 1280 px).
test('Editorial galleries stay caption-free and defer their thumbnails',()=>{
 const {JSDOM}=require('jsdom');
 for(const file of ['lieux/vice-city.html','personnages/jason.html','entreprises/electric-fang.html']){
  const dom=new JSDOM(fs.readFileSync(path.join(root,file),'utf8'));
  try{const d=dom.window.document,imgs=[...d.querySelectorAll('.lore-gallery img')];assert.ok(imgs.length>1,file);
   for(const img of imgs){assert.equal(img.getAttribute('loading'),'lazy');assert.ok(img.getAttribute('alt'));assert.ok(+img.getAttribute('width')>0&&+img.getAttribute('height')>0);assert.ok(fs.existsSync(path.join(root,img.getAttribute('src').replace(/^\//,''))),img.getAttribute('src'));
    const a=img.closest('a');assert.ok(a&&/-1280\.webp$/.test(a.getAttribute('href')));}
   assert.equal(d.querySelectorAll('.lore-gallery figcaption').length,0);}finally{dom.window.close();}
 }
});
// v7.3 : visuel officiel, alt et dimensions sur les panneaux des régions et des commerces de la carte.
test('Official region visual, alt and dimensions reach the map panel',withPage('carte.html#lieu=grassrivers',async a=>{await new Promise(r=>setImmediate(r));const img=a.d.querySelector('#map-panel-in img');assert.ok(img);assert.match(img.getAttribute('src'),/img\/officiel\/grassrivers/);assert.ok(+img.getAttribute('width')>0&&+img.getAttribute('height')>0);assert.ok(img.getAttribute('alt').length>5);}));
// v7.3 : le lien Google Maps n'accepte que des coordonnées réelles ; un panneau sans relevé réel n'en produit aucun.
test('Map only links Google Maps for real coordinates',async()=>{
 const links=a=>[...a.d.querySelectorAll('#map-panel-in a')].map(x=>x.getAttribute('href')||'');
 const okPoint=baseline.window.LK_GTADB.lieux.find(p=>p.sv);assert.ok(okPoint);
 let a=await load(root,'carte.html#lieu='+okPoint.id);try{await new Promise(r=>setImmediate(r));const gm=links(a).find(h=>h.startsWith('https://www.google.com/maps'));assert.ok(gm,'lien Google Maps attendu pour '+okPoint.id);assert.ok(gm.includes(encodeURIComponent(okPoint.sv)));assert.ok(!links(a).some(h=>/^javascript:/i.test(h)));assert.deepEqual(a.errors,[]);}finally{a.close();}
 a=await load(root,'carte.html#lieu=vice-city');try{await new Promise(r=>setImmediate(r));assert.ok(!links(a).some(h=>h.startsWith('https://www.google.com/maps')));}finally{a.close();}
});

// v7.4 : accueil (recherche centrée, calculateurs en tête, bandeau en photos), hubs (espaceurs, FAQ unifiée), fiches du monde (présentation, pile d'images, vignettes de carte)
test('Home page keeps the reworked sections in order and the region band uses official photos',withPage('index.html',a=>{
 const ids=['outils','etat','monde'].map(id=>a.d.getElementById(id));assert.ok(ids.every(Boolean));
 const pos=ids.map(e=>e.compareDocumentPosition(a.d.querySelector('.faq-sec'))&4);assert.ok(pos.every(Boolean),'chaque section précède la FAQ');
 assert.ok(a.d.getElementById('outils').compareDocumentPosition(a.d.getElementById('etat'))&4,'les calculateurs précèdent les régions');
 assert.ok(a.d.querySelector('#calc-feature.calc-v2 .calc-tiles li'));
 const strip=[...a.d.querySelectorAll('#strip img')];assert.ok(strip.length>=6);for(const img of strip)assert.ok(fs.existsSync(path.join(root,new URL(img.src).pathname.slice(1))));
 assert.ok(a.d.querySelectorAll('.faq-sec details').length>=10);
 const monde=[...a.d.querySelectorAll('#monde .lore-card img')].map(i=>i.getAttribute('src'));assert.equal(new Set(monde).size,monde.length,'quatre visuels distincts');
}));
test('Hub grids end with spacers and share the home FAQ markup',async()=>{
 for(const file of ['vehicules.html','armes.html']){const a=await load(root,file);try{const grid=a.d.getElementById('vgrid');assert.equal(grid.querySelectorAll('.veh-spacer').length,3);assert.ok(a.d.querySelector('#faq .faq details .ans'));assert.equal(a.d.querySelectorAll('.faq-item').length,0);assert.deepEqual(a.errors,[]);}finally{a.close();}}
});
test('World pages expose a presentation text, a stacked gallery and illustrated map cards',()=>{
 const {JSDOM}=require('jsdom');
 for(const file of ['lieux/vice-city.html','personnages/brian.html','planques/chantier-brian.html']){const dom=new JSDOM(fs.readFileSync(path.join(root,file),'utf8'));
  try{const d=dom.window.document;assert.ok(d.querySelector('.lore-texte p').textContent.length>300,file);if(file!=='planques/chantier-brian.html')assert.ok(d.querySelectorAll('.lore-stack .lore-slide img').length>=1,file);assert.equal(d.querySelectorAll('.lore-slide figcaption').length,0);for(const t of d.querySelectorAll('.lore-slide-txt'))assert.match(t.textContent,/GTA VI/);
   const cards=[...d.querySelectorAll('.lore-mapcard')];if(cards.length)assert.ok(cards.some(c=>c.querySelector('img')),file+' : au moins une vignette de carte illustrée');}finally{dom.window.close();}}
 const map=fs.readFileSync(path.join(root,'carte.html'),'utf8');assert.equal((map.match(/class="reg reg--link rise"/g)||[]).length,6);
});
