const fs=require('fs'),path=require('path');const {JSDOM,VirtualConsole}=require('jsdom');
async function load(root,file,opts={}){root=path.resolve(root);const errors=[],requests=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
const dom=new JSDOM(fs.readFileSync(path.join(root,file.split(/[?#]/)[0]),'utf8'),{url:opts.url || 'https://www.leonidakit.com/'+file,runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});const w=dom.window;
w.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});w.IntersectionObserver=class{observe(n){n.classList.add('in');if(n.dataset.count)n.textContent=n.dataset.count;}unobserve(){}disconnect(){}};
w.HTMLElement.prototype.scrollIntoView=function(){};w.HTMLElement.prototype.setPointerCapture=function(){};w.HTMLElement.prototype.releasePointerCapture=function(){};w.HTMLElement.prototype.getBoundingClientRect=function(){return{x:0,y:0,left:0,top:0,right:1000,bottom:700,width:1000,height:700}};w.scrollTo=()=>{};w.setInterval=()=>0;const timeouts=[];w.setTimeout=(f,ms)=>{if(ms<100)timeouts.push(f);return timeouts.length};w.clearTimeout=()=>{};w.requestAnimationFrame=f=>{timeouts.push(f);return 0;};w.alert=x=>{w.lastAlert=x};w.confirm=()=>true;w.prompt=()=>null;
w.URL.createObjectURL=()=> 'blob:local-test';w.URL.revokeObjectURL=()=>{};w.fetch=async url=>{requests.push(String(url));const rel=new URL(url,w.location.href).pathname.slice(1);return{ok:fs.existsSync(path.join(root,rel)),json:async()=>JSON.parse(fs.readFileSync(path.join(root,rel),'utf8'))}};
w.Image=function(){const e=w.document.createElement('img');Object.defineProperty(e,'src',{set(v){requests.push(v);queueMicrotask(()=>{if(fs.existsSync(path.join(root,new URL(v,w.location.href).pathname.slice(1))))e.onload?.();else e.onerror?.()})},get(){return e.getAttribute('src')}});return e};
for(const[k,v]of Object.entries(opts.storage||{}))w.localStorage.setItem(k,v);opts.before?.(w);
for(const s of w.document.querySelectorAll('script')){if(s.type==='application/ld+json')continue;let code=s.textContent;if(s.src){const p=path.join(root,new URL(s.src).pathname);if(!fs.existsSync(p)){errors.push('Missing script '+s.getAttribute('src'));continue;}code=fs.readFileSync(p,'utf8')}opts.beforeScript?.(w,s);try{w.eval(code+'\n//# sourceURL='+ (s.getAttribute('src')||file))}catch(e){errors.push(e.stack)}}
for(const f of timeouts.splice(0,300))try{f()}catch(e){errors.push(e.message)}await new Promise(r=>setImmediate(r));return{dom,w,d:w.document,errors,requests,flush:()=>{for(const f of timeouts.splice(0,300))try{f()}catch(e){errors.push(e.message)}},close:()=>w.close()};}
module.exports={load};
